### ISSUE TITLE
显示数据,出现数据显示不正常的情况。

### ISSUE THREAD

**Issue by zeXingZhang** [AAChartModel/AAChartKit#10]
刚绘好数据显示正常，绘完数据异常。
刚绘完：
![simulator screen shot 2017 4 20 10 33 08](https://cloud.githubusercontent.com/assets/14366614/25210907/de91e7e4-25b4-11e7-818a-d7a29b994010.png)
绘完后：
![simulator screen shot 2017 4 20 10 33 09](https://cloud.githubusercontent.com/assets/14366614/25210916/ef9f29ca-25b4-11e7-8dd6-a27a7097e9a2.png)

**Comment by AAChartModel** [comment]
兄弟你的这个问题很有深度啊,我之前在使用 highchart 过程中也遇到过类似的问题,像这种蛋疼的情况估计只能是 highchart 的 bug了,这就十分难解了!!!

**Comment by AAChartModel** [comment]
你将 AAChartType类型改为` area `  `area spline`  ` column `等其他类型或许能解决此问题(本建议仅供参考)

**Comment by zeXingZhang** [comment]
好的，我试试。谢谢 @AAChartModel
