### ISSUE TITLE
Problem with AreaChart

### ISSUE THREAD

**Issue by skuske** [AAChartModel/AAChartKit#100]
Have a look at the two screenshots below. The first one draws a line chart, the second one an area chart with exactly the same data. Problem: the area chart does not draw properly.

![line](https://user-images.githubusercontent.com/12996815/34415975-9536fec8-ebf1-11e7-9356-497681a2d83b.jpg)

![area](https://user-images.githubusercontent.com/12996815/34415974-94f6670a-ebf1-11e7-94b4-51d4ef74a255.jpg)

The data is an array of about 256 atmospheric pressure values rising from 978.9 to 996 in small steps. Why does the area chart not draw properly?

Thanks for this cool library which makes life really a LOT easier! Keep up the brilliant work! 🥇

**Comment by skuske** [comment]
I just noticed that in the area chart the y-axis starts at 0. That's the problem as that makes the resolution change. Is there any way to make the y-axis start at the same level as in the line chart?

**Comment by AAChartModel** [comment]
You can  try to change the `AAChartTypeArea` to be `AAChartTypeAreaspline`,may be it can help deal with this.

**Comment by AAChartModel** [comment]
```objective-c
AAPropStatementAndFuncStatement(assign, AAChartModel, BOOL,       yAllowDecimals);//是否允许 y 轴显示小数
AAPropStatementAndFuncStatement(strong, AAChartModel, NSArray  *, yPlotLines);//y 轴基线的配置
AAPropStatementAndFuncStatement(strong, AAChartModel, NSNumber *, yMax);//y 轴最大值
AAPropStatementAndFuncStatement(strong, AAChartModel, NSNumber *, yMin);//y 轴最小值（设置为0就不会有负数）
AAPropStatementAndFuncStatement(strong, AAChartModel, NSArray  *, yTickPositions);//自定义 y 轴坐标（如：[@(0), @(25), @(50), @(75) , (100)]）
```

**Comment by AAChartModel** [comment]
the `yMin` meaning the `y axis mini value`

**Comment by AAChartModel** [comment]
And this is the official lib of Highcharts,It might help you too.
 https://github.com/highcharts/highcharts-ios

**Comment by AAChartModel** [comment]
But I donnot like the official lib ,because it is too huge and complicated to use.
**postscript**:And my lib is five months earlier than the official lib of Highcharts.😝😝😝

**Comment by skuske** [comment]
y max and min might help. Thanks! :o)
