### ISSUE TITLE
项目打开了 Weak References in Manual Retain Release 之后出现错误

### ISSUE THREAD

**Issue by afunnyrainman** [AAChartModel/AAChartKit#1000]
AAPropSetFuncImplementation(AAStyle, NSString *, color);
AAPropSetFuncImplementation(AAStyle, NSString *, fontSize);
AAPropSetFuncImplementation(AAStyle, NSString *, fontWeight);
AAPropSetFuncImplementation(AAStyle, NSString *, textOutline);

错误
Returning block that lives on the local stack
所有这些全都报上面的错误，应该怎么改？大佬

**Comment by AAChartModel** [comment]
应该是 ARC 和 MRC 不同机制引起的吧, AAChartKit 只支持 ARC, 你应该可以在项目中指定 AAChartKit 部分文件开启 ARC 吧,这样的话,问题应该就能解决了

**Comment by afunnyrainman** [comment]
是的 很强 谢谢~~！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AAChartModel/AAChartKit"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月24日(星期四) 下午2:01
收件人:&nbsp;"AAChartModel/AAChartKit"<AAChartKit@noreply.github.com&gt;;
抄送:&nbsp;"Key"<876314095@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartKit] 项目打开了 Weak References in Manual Retain Release 之后出现错误 (#1000)





 
应该是 ARC 和 MRC 不同机制引起的吧, AAChartKit 只支持 ARC, 你应该可以在项目中指定 AAChartKit 部分文件开启 ARC 吧,这样的话,问题应该就能解决了
