### ISSUE TITLE
如何自定义X轴和y轴位置？比如将y轴放到最上方？

### ISSUE THREAD

**Issue by ddkcainiao** [AAChartModel/AAChartKit#1004]
谢谢

**Comment by AAChartModel** [comment]
![](https://raw.githubusercontent.com/AAChartModel/Gallery/master/AAChartKit/DataSortingBarChart.gif)

这种条形图应该就是你说的 Y轴在最上方, AAChartKit 的 demo 中有示例, 下载运行查看即可.

**Comment by AAChartModel** [comment]
X轴和 Y轴都有一个关键属性叫作` opposite ` ,专门用来调整 X轴和 Y轴的左右上下关系的.
