### ISSUE TITLE
如何把x轴的标记设置在view的右边

### ISSUE THREAD

**Issue by silendir** [AAChartModel/AAChartKit#1007]
如何把x轴的标记设置在view的右边
![image](https://user-images.githubusercontent.com/11792633/94359158-0151b500-00d8-11eb-9ff6-3edc3e81e8e4.png)
![image](https://user-images.githubusercontent.com/11792633/94359163-07e02c80-00d8-11eb-9da6-7566b50e9173.png)

**Comment by AAChartModel** [comment]
重复问题, 参见 #397 #1004
