### ISSUE TITLE
Touch delegate?

### ISSUE THREAD

**Issue by skuske** [AAChartModel/AAChartKit#101]
Is there any way to get notified which point of the graph is touched by the user? I need to display additional information based on the point of the graph the user touched... Thanks!!!

**Comment by skuske** [comment]
No way to do that?

**Comment by AAChartModel** [comment]
You can update the demo, which has an example of a new click event.

**Comment by AAChartModel** [comment]
The example of demo is based on the UIGesture of iOS

**Comment by AAChartModel** [comment]
However,this is just  a last resort !!! because there is a little bug of Highcharts:I cannot get the clicked event on iOS.

**Comment by AAChartModel** [comment]
This is the link of the bug
https://github.com/highcharts/highcharts/issues/7616

**Comment by skuske** [comment]
OK. Thanks for this. However - the example only gives me x,y coordinates where the touch happens. I actually need the index of the data that is touched. Otherwise this makles no sense.

**Comment by skuske** [comment]
Sorry, I missed that is DOES give me the index. I just found it in the logs - it was mixed up with some chinese characters and I did not notice it before. Sorry...

**Comment by skuske** [comment]
Unfortunately that only works if the chart is not zoomed in... :o(

**Comment by AAChartModel** [comment]
I've got the official reply.
highcharts/highcharts#7616

Maybe I can fix this issue if you give me more time,or you can resolve this problem by yourself through reading this [workaround](https://github.com/highcharts/highcharts/issues/6817
)

**Comment by skuske** [comment]
OK, thanks. :o)

**Comment by AAChartModel** [comment]
Refer to  #810
