### ISSUE TITLE
当折线图只有少数几个点的时候，如何让他从最左边开始

### ISSUE THREAD

**Issue by NashAnd** [AAChartModel/AAChartKit#1011]
![image](https://user-images.githubusercontent.com/14804016/95534670-fcb2c800-0a18-11eb-9298-376f3d6f8c8e.png)

**Comment by AAChartModel** [comment]
重复问题, 参见 https://github.com/AAChartModel/AAChartKit/issues/937

**Comment by NashAnd** [comment]
非常感谢
