### ISSUE TITLE
headerFormatSet

### ISSUE THREAD

**Issue by MrChenMj** [AAChartModel/AAChartKit#1014]
如何自定义头
<img width="204" alt="WeChat8f50ca0c58cbddea8f32bd22430ba8af" src="https://user-images.githubusercontent.com/10733465/95804740-1cf2c780-0d36-11eb-8399-462c0b99e3f1.png">

```objc
.seriesSet(@[
        AASeriesElement.new
        .nameSet(@"高压")
        .tooltipSet(AATooltip.new
                    .headerFormatSet(this.x + @"日均 <br/>")
                    .valueSuffixSet(@"mmHg")
                    )
        .dataSet(@[@70.0, @60.9, @90.5, @140.5, @180.2, @121.5, @125.2]),
        AASeriesElement.new
        .nameSet(@"低压")
```

qq 822784716@qq.com

**Comment by AAChartModel** [comment]
你的这个明显不对啊, 只有 formatter 是支持 JavaScript 函数的, format 属性一般都只能支持简单的字符串模板功能(内部不涉及 JavaScript 的判断逻辑), 参见在线文档 https://api.highcharts.com.cn/highcharts#tooltip.headerFormat

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/95805013-ecf7f400-0d36-11eb-89c7-a46f41861868.png)
下面这个能自定义吗，大佬

**Comment by AAChartModel** [comment]
自定义 legend 参见问题 https://github.com/AAChartModel/AAChartKit/issues/799

**Comment by MrChenMj** [comment]
大佬 请问图例如何设置字在左边

**Comment by AAChartModel** [comment]
> 图例如何设置字在左边

这个估计 Highcharts 不支持, 你其实也可以隐藏 AAChartView 的图例,然后自绘图例. 这样任何自定义样式都可以弄出来

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/96240153-23ea3600-0fd3-11eb-9776-24e82dee3163.png)
你好，大佬，x轴这条线怎么隐藏了啊？

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/96241763-306f8e00-0fd5-11eb-8404-b499659cd684.png)
还有这个间距可以控制吗？

**Comment by MrChenMj** [comment]
大佬，x轴背景颜色可以设置吗？

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/96807648-afd3e600-1449-11eb-9e49-4ee04b8213f1.png)
最下面的线怎么隐藏啊，大佬

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/96807702-d42fc280-1449-11eb-93c3-4db00cbdac0d.png)
zui'xi'ai最下面的线怎么隐藏啊，大神

**Comment by AAChartModel** [comment]
通过 AAOptions 来隐藏 X轴轴线即可

**Comment by MrChenMj** [comment]
大神，如果一条数据，我想默认显示到原点位置，怎么操作，

**Comment by MrChenMj** [comment]
大神方便加个qq吗？
![Uploading image.png…]()

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/96961014-52699300-1536-11eb-859b-476525f63cf9.png)

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/96961075-7f1daa80-1536-11eb-8821-a592a38d2609.png)

**Comment by AAChartModel** [comment]
参见 https://github.com/AAChartModel/AAChartKit/issues/937

**Comment by AAChartModel** [comment]
如果还是不够靠边的话, 可能是数据不够多的缘故, 没有数据的地方,你用 NSNull 占位即可.

AAChartKit 的 demo 中有示例.

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/97573770-39288100-1a25-11eb-9140-f2713304adf7.png)

大神，请问外面的数据怎么传进里面使用

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/97573888-607f4e00-1a25-11eb-88c5-5105397076b0.png)
我想点击的时候，弹窗显示对应model里面的数据

**Comment by MrChenMj** [comment]
大神方便加个qq吗，我qq 822784716

**Comment by AAChartModel** [comment]
```objc
@AAJSFunc(function () {
        ...
        ...
        ...
    })
```

这部分内容其实本质上还是字符串,所以如果你想从外部传值进去,用的还得是拼接字符串的方法

**Comment by AAChartModel** [comment]
参考 https://github.com/AAChartModel/AAChartKit/issues/852#issuecomment-599961664

关键内容如下

```objc
 NSArray *categoryArr = @[
        @"周转天数(天)",
        @"订单满足率",
        @"订单履约时效",
        @"动销率",
        @"畅销商品缺货率",
        @"高库存金额占比",
        @"不动销金额占比",
        @"停采金额占比",
     ];
    
    NSString *categoryJSArrStr = [categoryArr aa_toJSArray];
    
    NSString *xAxisLabelsFormatter = [NSString stringWithFormat:(@AAJSFunc(function () {
        return %@[this.value];
    })),categoryJSArrStr];
```

demo 中有这段代码的示例, 你断点调试或者 NSLog 控制台打印看看最终变量 xAxisLabelsFormatter 内容,你就明白了

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/97805159-56f91e80-1c8f-11eb-80be-0b937af94f74.png)
我已经设置主题颜色了   👇
self.aaChartModel = AAObject(AAChartModel)
    .chartTypeSet(chartType)//图表类型
    .colorsThemeSet(@[@"#4A8EF4",@"#F7A03F",@"#7FD9C9"])//设置主题颜色数组
    .legendEnabledSet(NO)
    //    .stackingSet(AAChartStackingTypeNormal)
    .markerSymbolSet(AAChartSymbolTypeCircle)
    .markerRadiusSet(@4)
    .zoomTypeSet(AAChartZoomTypeX);
但是我重写了这个方法👇

**Comment by MrChenMj** [comment]
options.tooltip
            .formatterSet(@AAJSFunc(function () {
                let selectedTopPoint = this.points[0].point.options;
                var arr = selectedTopPoint.name.split("$");
                var sureHigh_y = arr[1];
                var sure_Head = arr[0];
                
                var s = '<b>' +  this.x + '</b>' + '<br/>';
                let colorDot1 = '<span style=\"' + 'color:rgba(74,142,244,1.0); font-size:13px\"' + '>◉</span> ';
                let colorDot2 = '<span style=\"' + 'color:rgba(247,160,63,1.0); font-size:13px\"' + '>◉</span> ';
                let colorDot3 = '<span style=\"' + 'color:rgba(127,217,201,1.0); font-size:13px\"' + '>◉</span> ';
                
                var s1;
                var s2;
                var s3;
                let pointsNum = this.points.length;
                if (pointsNum === 1) {
                    let selectedPoint = this.points[0];
                    let selectedSurPoint = this.points[0].point.options;
                    var selectedPointIndex = selectedPoint.series.index;
                    if (selectedPointIndex === 0) {
                        s1 = colorDot1 + selectedPoint.series.name + ': ' + sureHigh_y + 'mmHg';
                        s2 = "";
                        s3 = "";
                    } else if (selectedPointIndex === 1) {
                        s1 = "";
                        s2 = colorDot2 + selectedPoint.series.name + ': ' + selectedSurPoint.name + 'mmHg';
                        s3 = "";
                    }else if (selectedPointIndex === 2) {
                        s1 = "";
                        s2 = "";
                        s3 = colorDot3 + selectedPoint.series.name + ': ' +  selectedSurPoint.name + '次/分钟';
                    }
                }
                else {
                    let selectedPoint1 = this.points[0];
                    let selectedPoint2 = this.points[1];
                    let selectedSurPoint2 = this.points[1].point.options;
                    let selectedPoint3 = this.points[2];
                    let selectedSurPoint3 = this.points[2].point.options;
                    
                    s1 = colorDot1 + selectedPoint1.series.name + ': ' + sureHigh_y + 'mmHg' + '<br/>';
                    s2 = colorDot2 + selectedPoint2.series.name + ': ' + selectedSurPoint2.name + 'mmHg' + '<br/>';
                    s3 = colorDot3 + selectedPoint3.series.name + ': ' + selectedSurPoint3.name + '次/分钟';
                }
                s += s1 + s2 + s3 ;
                return s;
            }));
就不显示对应的边框颜色了，请问大神怎么设置，对应的边框颜色呢

**Comment by MrChenMj** [comment]
大神好，对应的边框颜色是不是也在formatterSet里面可以设置？

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/99378585-8e5c0200-2902-11eb-962f-06d186de0dcf.png)
请问这个第一个字怎么处理

**Comment by AAChartModel** [comment]
把字体设置的小一点试试

**Comment by MrChenMj** [comment]
设置了，好像不起作用

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/99471981-a5dacf80-2982-11eb-9e49-44b39aac5bd9.png)
    self.aaChartModel.categoriesSet(@[@"1:15",
                                      @"11:34",
                                      @"11:34",
                                      @"11:34",
                                      @"11:35",
                                      @"11:35",
                                      @"11:49",
                                      @"11:50",
                                      @"11:50",
                                      @"11:51",
                                      @"15:05",
                                      @"15:58",
                                      @"15:59",
                                      @"16:23",
                                      @"17:48",
                                      @"19:32",
                                      @"19:32"])

**Comment by AAChartModel** [comment]
那你调整一下 X 轴的 Labels 的 rotation 或者 AAChartModel  的 margin 试试

**Comment by MrChenMj** [comment]
请问大神，当有一个值的时候，如何显示到最左边的位置

**Comment by AAChartModel** [comment]
> 请问大神，当有一个值的时候，如何显示到最左边的位置

重复问题, 参见 #937

**Comment by MrChenMj** [comment]
请问X轴能单独设置背景颜色吗？

**Comment by AAChartModel** [comment]
> 请问X轴能单独设置背景颜色吗？

https://github.com/AAChartModel/AAChartKit/issues/1056

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/99618185-d8a4c680-2a5b-11eb-8bbf-63e3b527836c.png)
大神 请问 x轴的背景颜色，不是线的颜色。或者设置内容颜色，应该怎么设置呢

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/99618371-2a4d5100-2a5c-11eb-9cd7-20216f4e4ed6.png)

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/99622092-700e1780-2a64-11eb-8c2f-d9fb4dddec77.png)大神这个要怎么处理一下呢，还是第一个显示不全，还有的的上面图标和下面的x轴文字对应不上，x轴的文字被挤没了

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/99622253-b499b300-2a64-11eb-935e-7f36a1556bb8.png)
