### ISSUE TITLE
图表x轴的滑动可不可以增加惯性,就是手指离开它还会向前滑动几个像素

### ISSUE THREAD

**Issue by silendir** [AAChartModel/AAChartKit#1015]
图表x轴的滑动可不可以增加惯性,就是手指离开它还会向前滑动几个像素

**Comment by AAChartModel** [comment]
使用 AAScrollablePlotArea 实现的可滑动图表默认是有惯性效果的,具体查看 AAChartKit 的 demo 中通过AAScrollablePlotArea实现的滑动图表示例 demo

**Comment by silendir** [comment]
好像和ToolTip的锁定Y轴一样...只能在模拟器上实现, 在真机上失效... 好尴尬

**Comment by silendir** [comment]
一缩放图表就会失效, 而且Reset Zoom 的按钮不会出现, 是否需要深度设置来开启?

**Comment by AAChartModel** [comment]
> 只能在模拟器上实现, 在真机上失效... 好尴尬

这么尴尬的吗?我后面测试一下看看
