### ISSUE TITLE
图表放大后出现的白底 黑字"Reset zoom" 可以自定义样式么? 只搜索到js代码,想实现国际化字符

### ISSUE THREAD

**Issue by silendir** [AAChartModel/AAChartKit#1018]
![image](https://user-images.githubusercontent.com/11792633/96204889-fc29ac80-0f97-11eb-9fab-eda09a1ee51d.png)

![image](https://user-images.githubusercontent.com/11792633/96204819-dac8c080-0f97-11eb-8f73-3914d8cc5052.png)

**Comment by AAChartModel** [comment]
```objc
    aaOptions.defaultOptions = AALang.new
    .resetZoomSet(@"重置缩放比例")
    .thousandsSepSet(@",")//千分位分割符;
```

**Comment by AAChartModel** [comment]
参见 https://api.highcharts.com.cn/highcharts#lang.resetZoom

**Comment by AAChartModel** [comment]
相关问题 https://github.com/AAChartModel/AAChartKit/issues/425
