### ISSUE TITLE
不支持xib吗？

### ISSUE THREAD

**Issue by 312353457** [AAChartModel/AAChartKit#1019]
老版本用xib写的，更新后一直报错

**Comment by AAChartModel** [comment]
你这个报错应该跟 xib没什么关系吧,报错可能是一些借口被废弃或者修改了

**Comment by 312353457** [comment]
编译报错都改了。  用代码添加布局就不报错，用xib布局就报错了，错误如下，小白求指教
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Configuration cannot be nil'
*** First throw call stack:
(0x197d45114 0x1ab56bcb4 0x197c482cc 0x1a36edd6c 0x1a36fbc64 0x19a1c88cc 0x1a0856ca8 0x1a0856ec0 0x1a07e648c 0x19aa5a2e4 0x1a0856ca8 0x1a07e648c 0x19a1ccae0 0x1a0856ca8 0x1a0856ec0 0x1a07e648c 0x19a1c7a6c 0x19a1ca444 0x199ec6ab0 0x199ec6e3c 0x199ec7510 0x199dfd0ac 0x199e11474 0x199e128a4 0x199df57ec 0x19aa89954 0x19af899e8 0x19af8feb4 0x19af9b1d0 0x19aee7500 0x19af11698 0x19af12948 0x197cc3ecc 0x197cbe5b0 0x197cbeaf8 0x197cbe200 0x1addb9598 0x19a584004 0x19a5895d8 0x1045edf38 0x19799d598)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Configuration cannot be nil'
terminating with uncaught exception of type NSException
