### ISSUE TITLE
按照文档设置AATooltip无效。大佬指导一下啊

### ISSUE THREAD

**Issue by QionglinFu1024** [AAChartModel/AAChartKit#1020]
CGFloat chartViewWidth  = self.view.frame.size.width;
    CGFloat chartViewHeight = self.view.frame.size.height - 250;
    self.aaChartView = [[AAChartView alloc]init];
    self.aaChartView.frame = CGRectMake(0, 60, chartViewWidth, chartViewHeight);
    _aaChartView.scrollEnabled = NO;
    [self.view addSubview:self.aaChartView];
    self.aaChartView.delegate = self;
    
    AAChartModel *aaChartModel = AAChartModel.new
    .chartTypeSet(AAChartTypeArea)
    .titleSet(@"")
    .subtitleSet(@"")
    .categoriesSet(@[@"Java",@"Swift",@"Python",@"Ruby", @"PHP",@"Go",@"C",@"C#",@"C++"])
    .legendEnabledSet(NO)
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(nil)
        .dataSet(@[@10, @20, @30, @40, @50, @60, @70, @80, @90, @100, @110, @10]),
    ])
    ;
    
    AATooltip *tooltip = aaChartModel.aa_toAAOptions.tooltip;
    tooltip
    .backgroundColorSet(@"#E1AA6C")
    .useHTMLSet(true)
    .formatterSet(@AAJSFunc(function () {
        return ' 🌕 🌖 🌗 🌘 🌑 🌒 🌓 🌔 <br/> '
        + ' Support JavaScript Function Just Right Now !!! <br/> '
        + ' The Gold Price For <b>2020 '
        +  this.x
        + ' </b> Is <b> '
        +  this.y
        + ' </b> Dollars ';
    }))
    .valueDecimalsSet(@2)//设置取值精确到小数点后几位
    .backgroundColorSet(@"#000000")
    .borderColorSet(@"#000000")
    .styleSet(AAStyleColorSize(@"#FFD700", 12))
    ;
    
    [self.aaChartView aa_drawChartWithChartModel:aaChartModel];

**Comment by AAChartModel** [comment]
这个自定义 AATooltip 的效果在 AAChartKit 的 demo 中有示例,下载运行查看即可.
