### ISSUE TITLE
柱状图点击之后有个选中效果，能不能取消掉

### ISSUE THREAD

**Issue by cuiyu8580** [AAChartModel/AAChartKit#1021]
柱状图点击之后，出现选中效果。有选中效果的情况下，再点击没有事件触发，需要点击其他地方取消选中效果，才能再次点击，pc端我看没有这个效果，这个是移植过来默认带了这个效果吗？怎么取消掉

**Comment by AAChartModel** [comment]
重复问题,参见 https://github.com/AAChartModel/AAChartKit/issues/442

**Comment by cuiyu8580** [comment]
老哥，没用啊，能不能帮我看看代码，这个一直都没用，后来我用其他办法代替了，现在过来代码优化，看看还是没用，最好能解决一下。代码
_aaChartModel = AAChartModel.new
    .chartTypeSet(AAChartTypeColumn)//图表类型
    .colorsThemeSet(@[@"#ff6822"])//设置主题颜色数组
    .dataLabelsEnabledSet(YES)//显示数据
    .legendEnabledSet(NO)
    .tooltipEnabledSet(NO)
    .yAxisLineWidthSet(@1)//Y轴轴线线宽为0即是隐藏Y轴轴线
    .categoriesSet(xArray)
    
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"Column")
        .dataSet(yArray)
        .statesSet(AAStates.new
                   .selectSet(AASelect.new
                                  .enabledSet(false))
                   )

        
    ]);
    
    AAOptions *aaOptions = _aaChartModel.aa_toAAOptions;
    AADataLabels *aaDataLabels = aaOptions.plotOptions.series.dataLabels;

    aaDataLabels
    .cropSet(false)
    .overflowSet(@"none");
    
    [self.aaChartView aa_drawChartWithOptions:aaOptions];

**Comment by cuiyu8580** [comment]
[
![1111](https://user-images.githubusercontent.com/13254617/111775333-94cbac00-88eb-11eb-8712-12a9536b3c53.png)
](url)

**Comment by cuiyu8580** [comment]
@AAChartModel 老哥，多谢了，中间那个2021-02柱状图上的选中效果

**Comment by AAChartModel** [comment]
你是说不想要这个选中的半透明阴影效果吗？这个是准星线，你可以设置宽度为0隐藏掉

**Comment by cuiyu8580** [comment]
.xAxisCrosshairSet([AACrosshair crosshairWithWidth:@0])
    .yAxisCrosshairSet([AACrosshair crosshairWithWidth:@0])
是这两个设置的吗？没有效果，最头疼 了

**Comment by cuiyu8580** [comment]
看了之前的问题，找到了答案，已解决，谢谢！

**Comment by AAChartModel** [comment]
我试了一下,似乎直接使用

```objc
    _aaChartModel.xAxisCrosshairSet([AACrosshair crosshairWithWidth:@0]);
```
确实不太行.

不过直接使用

```objc
   _aaChartModel.xAxisCrosshairSet((id)@false);
```

也就可以隐藏准星线了.

**Comment by AAChartModel** [comment]
> 看了之前的问题，找到了答案，已解决，谢谢！

你这里是直接设置准星线的背景色为透明色来实现隐藏的?
