### ISSUE TITLE
大佬x轴有三十个，但是数据只有十个，怎么让后面的x轴也显示出来？

### ISSUE THREAD

**Issue by QionglinFu1024** [AAChartModel/AAChartKit#1022]
CGFloat chartViewWidth  = self.view.frame.size.width;
    CGFloat chartViewHeight = self.view.frame.size.height - 250;
    self.aaChartView = [[AAChartView alloc]init];
    self.aaChartView.frame = CGRectMake(0, 60, chartViewWidth, chartViewHeight);
    _aaChartView.scrollEnabled = NO;
    [self.view addSubview:self.aaChartView];
    self.aaChartView.delegate = self;
    
    NSDictionary * gradientColorDic1 = [AAGradientColor gradientColorWithDirection:AALinearGradientDirectionToBottom startColorString:@"rgba(121, 237, 231, 0.3)" endColorString:@"rgba(68, 215, 202, 0)"];
    
    AAChartModel *aaChartModel = AAChartModel.new
    .xAxisCrosshairWidthSet(@2)
    .xAxisCrosshairColorSet(@"rgba(225, 170, 108, 1)")
    .xAxisCrosshairDashStyleTypeSet(AAChartLineDashStyleTypeShortDash)
    .markerSymbolStyleSet(AAChartSymbolStyleTypeInnerBlank)// markerpoint为空心效果
    .markerSymbolSet(AAChartSymbolTypeCircle)// markerpoint为圆形点○
    .markerRadiusSet(@6.0)
    .chartTypeSet(AAChartTypeArea)
    .titleSet(@"")
    .subtitleSet(@"")
    .categoriesSet(@[@"01",@"02",@"03",@"04", @"05",@"06",@"07",@"08",@"09",@"10",@"11",@"12",@"13",@"14", @"15",@"16",@"17",@"18",@"19",@"20",@"21",@"22",@"23",@"24", @"25",@"26",@"27",@"28",@"29",@"30"])
    .xAxisTickIntervalSet(@5)
    .legendEnabledSet(NO)
    .seriesSet(@[
        AASeriesElement.new
        .statesSet(AAStates.new
                   .hoverSet(AAHover.new
                             .enabledSet(true)
                             .lineWidthPlusSet(@0)
                             ))
        .markerSet(AAMarker.new
                   .lineColorSet(@"#44D7CA")
                   .statesSet(AAMarkerStates.new
                              .hoverSet(AAMarkerHover.new
                                        .fillColorSet(AAColor.redColor)
                                        .radiusSet(@10)
                                        )))
        .nameSet(@"08")
        .lineWidthSet(@3)
        .colorSet(@"rgba(68, 215, 202, 1)")
        .fillColorSet((id)gradientColorDic1)
        .dataSet(@[@10, @20, @30, @40, @0, @60, @70, @80, @90, @100, @110, @10]),
    ]);
    [self.aaChartView aa_drawChartWithChartModel:aaChartModel];
    
    AAOptions *aaOptions = aaChartModel.aa_toAAOptions;
    aaOptions.yAxis.labels.formatterSet(@AAJSFunc(function () {
        let yValue = this.value;
        if (yValue >= 80) {
            return "极佳";
        } else if (yValue >= 60 && yValue < 80) {
            return "非常棒";
        } else if (yValue >= 40 && yValue < 60) {
            return "相当棒";
        } else if (yValue >= 20 && yValue < 40) {
            return "还不错";
        } else {
            return "一般";
        }
    }))
    ;
    AATooltip *tooltip = aaOptions.tooltip;
    tooltip
    .useHTMLSet(true)
    .sharedSet(false)
    .formatterSet(@AAJSFunc(function () {
        
        let wholeContentString = this.point.x + '<br/>';
        let yValue = this.y;
        if (yValue != 0) {
            wholeContentString = '<span style= color:gray;font-size:10px;font-weight:bold;> 范围 </span><br><span style= font-size:35px;font-weight:1000;>' + this.x + '</span><span style=color:gray;font-size:15px;font-weight:bold; > 度 </span><br>';
        }
        return wholeContentString;
        
    }))
    .valueDecimalsSet(@2)//设置取值精确到小数点后几位
    .backgroundColorSet(@"#44D7CA")
    .borderColorSet(@"#44D7CA")
    .styleSet(AAStyleColorSize(@"#FFD700", 12))
    ;
    
    aaOptions.xAxis.labels.formatterSet(@AAJSFunc(function () {
        
//        return series.name + this.value;
    }));
    
    [self.aaChartView aa_refreshChartWithOptions:aaOptions];

![image](https://user-images.githubusercontent.com/26901908/96397240-af461000-11fb-11eb-9326-a5b8f5686133.png)

效果图是这样。后面的数据没有，但是x轴需要显示出来，这种应该怎么配置呢？然后还有自定义x轴数据的时候 return series.name + this.value;这样写不显示，求大佬指导一下～

**Comment by AAChartModel** [comment]
没有数据的地方,你用 NSNull 占位即可.

AAChartKit 的 demo 中有示例.
