### ISSUE TITLE
怎么设置x轴的第一个分类标题在坐标原点上

### ISSUE THREAD

**Issue by ShuangZiMoYin** [AAChartModel/AAChartKit#1023]
![CAAD26EAE2C91A6DA99942C240CC3C6D](https://user-images.githubusercontent.com/21330986/96433353-c276d100-1237-11eb-99ba-ecd5f83484d8.png)
<img width="336" alt="WechatIMG45" src="https://user-images.githubusercontent.com/21330986/96434081-efc37f00-1237-11eb-8379-4b15757b7c97.png">

**Comment by AAChartModel** [comment]
重复问题, 参见 https://github.com/AAChartModel/AAChartKit/issues/937

**Comment by ShuangZiMoYin** [comment]
按照上面的配置，依旧是没有在原点上，如果是在原点上，0上节点，中心应该是y轴穿过，现在没有
<img width="336" alt="WX20201020-162226@2x" src="https://user-images.githubusercontent.com/21330986/96560220-99fedd80-12f0-11eb-9fb2-a0d96828430a.png">
