### ISSUE TITLE
y轴标签能不能自定义不等间距？

### ISSUE THREAD

**Issue by QionglinFu1024** [AAChartModel/AAChartKit#1024]
![image](https://user-images.githubusercontent.com/26901908/96451547-55b90200-124a-11eb-875b-61dcedcba871.png)

NSDictionary *gradientColorDic1 = [AAGradientColor gradientColorWithDirection:AALinearGradientDirectionToBottom startColorString:@"rgba(121, 237, 231, 0.3)" endColorString:@"rgba(68, 215, 202, 0)"];

    AAChartModel *aaChartModel = AAChartModel.new
        .xAxisCrosshairWidthSet(@2)
        .xAxisCrosshairColorSet(@"rgba(225, 170, 108, 1)")
        .xAxisCrosshairDashStyleTypeSet(AAChartLineDashStyleTypeShortDash)
        .markerSymbolStyleSet(AAChartSymbolStyleTypeInnerBlank)// markerpoint为空心效果
        .markerSymbolSet(AAChartSymbolTypeCircle)// markerpoint为圆形点○
        .markerRadiusSet(@2.0)
        .chartTypeSet(AAChartTypeArea)
        .titleSet(@"")
        .subtitleSet(@"")
        .categoriesSet(@[@"08-01", @"08-02", @"08-03", @"08-04", @"08-05", @"08-06", @"08-07", @"08-08", @"08-09", @"08-10", @"08-11", @"08-12", @"08-13", @"08-14", @"08-15", @"08-16", @"08-17", @"08-18", @"08-19", @"08-20", @"08-21", @"08-22", @"08-23", @"08-24", @"08-25", @"08-26", @"08-27", @"08-28", @"08-29", @"08-30"])
        .xAxisTickIntervalSet(@5)
        .legendEnabledSet(NO)
        .seriesSet(@[
                       AASeriesElement.new
                       .statesSet(AAStates.new
                                  .hoverSet(AAHover.new
                                            .enabledSet(true)
                                            .lineWidthPlusSet(@0)
                                            ))
                       .markerSet(AAMarker.new
                                  .lineColorSet(@"#44D7CA")
                                  .statesSet(AAMarkerStates.new
                                             .hoverSet(AAMarkerHover.new
                                                       .fillColorSet(AAColor.redColor)
                                                       .radiusSet(@4)
                                                       )))
                       .nameSet(@"2020")
                       .lineWidthSet(@1)
                       .colorSet(@"rgba(68, 215, 202, 1)")
                       .fillColorSet((id)gradientColorDic1)
                       .dataSet(@[@1, @1, @50, @10, @89, @60, @100, @90, @56, @54, @32, @99, @88, @66, @670, @200, @600, @10, @300, @700, @10, @20, @10, @60, @20, @400, @500, @770, @800, @200, @1000, ]
                                ),
                   ]);
    [self.aaChartView aa_drawChartWithChartModel:aaChartModel];

    AAOptions *aaOptions = aaChartModel.aa_toAAOptions;
    aaOptions.yAxis
    .tickAmountSet(@6)
    .gridLineWidthSet(@0)//Y轴网格线宽度
    .tickPositionsSet(@[@0, @50, @100, @150, @200, @300]);//设置 Y 轴刻度值为一组指定值数组
    aaOptions.yAxis.labels.formatterSet(@AAJSFunc(function() {
        let yValue = this.value;
        if (yValue >= 300) {
            return "严重";
        } else if (yValue >= 200 && yValue < 300) {
            return "重度";
        } else if (yValue >= 150 && yValue < 200) {
            return "中度";
        } else if (yValue >= 100 && yValue < 150) {
            return "轻度";
        } else if (yValue >= 50 && yValue < 100) {
            return "良";
        } else {
            return "优";
        }
    }))
    ;

自定义y轴字符串以后，区间比较小，数值较大时会出现这个问题，大佬这种有解决方案吗？
效果图如下
![image](https://user-images.githubusercontent.com/26901908/96451854-c6f8b500-124a-11eb-8641-f81cd89b59f8.png)

**Comment by AAChartModel** [comment]
```objc
 let yValue = this.value;
    if (yValue >= 300) {
        return "严重";
    } else if (yValue >= 200 && yValue < 300) {
        return "重度";
    } else if (yValue >= 150 && yValue < 200) {
        return "中度";
    } else if (yValue >= 100 && yValue < 150) {
        return "轻度";
    } else if (yValue >= 50 && yValue < 100) {
        return "良";
    } else {
        return "优";
    }
```

这里面的值的范围需要根据你的项目中的实际的值来设置的,并不是死的,demo 中这样设置,只是使用示范而已
