### ISSUE TITLE
seriesSet

### ISSUE THREAD

**Issue by MrChenMj** [AAChartModel/AAChartKit#1026]
![image](https://user-images.githubusercontent.com/10733465/96805592-90868a00-1444-11eb-8b27-f3bde6a7821b.png)
![image](https://user-images.githubusercontent.com/10733465/96809256-1c9caf80-144d-11eb-8bae-3cc2f1fee4f2.png)
![image](https://user-images.githubusercontent.com/10733465/96809301-2de5bc00-144d-11eb-9d2a-7065f512b2db.png)

动态添加的数据就变成这样了，后面的一直把先添加的挤兑走了

**Comment by AAChartModel** [comment]
看不懂你截图的意思

**Comment by MrChenMj** [comment]
![image](https://user-images.githubusercontent.com/10733465/96816671-4905fb00-1450-11eb-825b-b4fca3c0b867.png)
黄线是后添加的，位置正确，蓝线位置错误

**Comment by MrChenMj** [comment]
NSArray *series = @[
        AASeriesElement.new
        .dataSet(@[@51, @120, @120, @120, @239, @107, @90,@90,@90,@90,@60,@100,@90]),
        AASeriesElement.new
        .dataSet(@[@130, @130, @130, @130, @240, @130, @130,@130,@130,@150,@100,@180,@150]),
        AASeriesElement.new
        .dataSet(@[]),
    ];
  
    self.aaChartModel.categoriesSet(dateArray);//设置 X 轴坐标文字内容
//    [self refreshTheChartView];
    [self onlyRefreshTheChartDataBySeries:series];

**Comment by MrChenMj** [comment]
- (void)configureTheYAxisPlotLineForAAChartView {
    self.aaChartModel
    .yAxisLineWidthSet(@0)//Y轴轴线线宽为0即是隐藏Y轴轴线
    .yAxisGridLineWidthSet(@0)//y轴横向分割线宽度为0(即是隐藏分割线)
    .yAxisMinSet(@-100)
    .yAxisMaxSet(@240)
    .yAxisLabelsEnabledSet(NO)
    .yAxisPlotLinesSet(@[
        AAPlotLinesElement.new
        .colorSet(@"#EE9497")
        .dashStyleSet(AAChartLineDashStyleTypeLongDashDot)
        .widthSet(@(1))
        .valueSet(@(140))
        .zIndexSet(@0)
        .labelSet(AALabel.new
                  .xSet(@0)
                  .ySet(@12)
                  .textSet(@"140")
                  .styleSet(AAStyleColor(@"#EE9497")))
        ,
        AAPlotLinesElement.new
        .colorSet(@"#B8C8E1")//颜色值(16进制)
        .dashStyleSet(AAChartLineDashStyleTypeSolid)//样式：Dash,Dot,Solid等,默认Solid
        .widthSet(@(1)) //标示线粗细
        .valueSet(@(0)) //所在位置
        .zIndexSet(@(0)) //层叠,标示线在图表中显示的层叠级别，值越大，显示越向前
        .labelSet(AALabel.new
                  .xSet(@0)
                  .ySet(@12)
                  .textSet(@"100")
                  .styleSet(AAStyleColor(@"#B8C8E1")))
        ,
        AAPlotLinesElement.new
        .colorSet(@"#BCE7D3")//颜色值(16进制)
        .dashStyleSet(AAChartLineDashStyleTypeLongDashDot)//样式：Dash,Dot,Solid等,默认Solid
        .widthSet(@(1)) //标示线粗细
        .valueSet(@(90)) //所在位置
        .zIndexSet(@(0)) //层叠,标示线在图表中显示的层叠级别，值越大，显示越向前
        .labelSet(AALabel.new
                  .xSet(@0)
                  .ySet(@12)
                  .textSet(@"90")
                  .styleSet(AAStyleColor(@"#BCE7D3")))
        ,
        AAPlotLinesElement.new
        .colorSet(@"#F1D030")
        .dashStyleSet(AAChartLineDashStyleTypeLongDashDot)
        .widthSet(@(1))
        .valueSet(@(120))
        .zIndexSet(@0)
        .labelSet(AALabel.new
                  .xSet(@0)
                  .ySet(@12)
                  .textSet(@"120")
                  .styleSet(AAStyleColor(@"#F1D030")))
        
                       ]);
}

**Comment by MrChenMj** [comment]
.stackingSet(AAChartStackingTypeNormal)是这个问题
