### ISSUE TITLE
请问有没有直接屏蔽双指缩放操作,不让图表双指缩放,因为好像和scroll有冲突

### ISSUE THREAD

**Issue by silendir** [AAChartModel/AAChartKit#1027]
请问有没有直接屏蔽双指缩放操作,不让图表双指缩放,因为好像和scroll有冲突, 一缩放scroll就失效没法还原,他们不要缩放..只要scroll. 还有scroll 滑到边界会有白边出现,这个也可以屏蔽么?

**Comment by AAChartModel** [comment]
```objc
typedef NSString *AAChartZoomType;

AACHARTKIT_EXTERN AAChartZoomType const AAChartZoomTypeNone;
AACHARTKIT_EXTERN AAChartZoomType const AAChartZoomTypeX;
AACHARTKIT_EXTERN AAChartZoomType const AAChartZoomTypeY;
AACHARTKIT_EXTERN AAChartZoomType const AAChartZoomTypeXY;
```

设置为 `AAChartZoomTypeNone` 即可屏蔽缩放功能

**Comment by AAChartModel** [comment]
> 还有scroll 滑到边界会有白边出现,这个也可以屏蔽么?

这个 Highcharts 貌似没有提供设置接口或参数

**Comment by silendir** [comment]
![IMG_1588](https://user-images.githubusercontent.com/11792633/96971092-36222200-1547-11eb-9897-f6fa656b966d.JPG)
就是拖到最边界.. 后面的白色会漏出来, 而且这个白色不能通过设置背景色去除.. 每一次重新构造都会闪一下白色

**Comment by silendir** [comment]
![image](https://user-images.githubusercontent.com/11792633/96971233-6c5fa180-1547-11eb-9c7b-79b5481199bd.png)
就是这个拉到最边缘的白色背景...而且不能通过设置webView背景色去除, 每一次初始化的时候  它都会 闪一下白色

**Comment by silendir** [comment]
我在webView上设置原生代码不能控制

**Comment by silendir** [comment]
请问这个白色层... 是哪里的view在哪一层的? 可不可以把它变白

**Comment by AAChartModel** [comment]
简单粗暴一点的做法就是设置 AAChartView 的背景色为透明

```objc
    aaChartView.isClearBackgroundColor = true;
```

然后设置 AAChartView 的父视图的颜色为你想要的背景色,应该就能避免这个白边问题了

**Comment by AAChartModel** [comment]
> 请问这个白色层... 是哪里的view在哪一层的? 可不可以把它变白

变白?你是说变黑吧.  目前我也不知道这个白色层是哪一层. 后面有时间再看看吧

**Comment by silendir** [comment]
虽然前景有点透明不知道会不会被怼..但是基本像模像样,感谢大神拯救... 我他妈今天被他们怼死...  拉伸那么好的功能...他们居然说不还原设计

**Comment by silendir** [comment]
我用界面监视器观察到是WKContentView上面的诸多个WKCompositingView 变白.. 但是我用keyforValue却捕捉不到

**Comment by AAChartModel** [comment]
> 虽然前景有点透明不知道会不会被怼..但是基本像模像样,感谢大神拯救... 我他妈今天被他们怼死... 拉伸那么好的功能...他们居然说不还原设计

直接怼产品和测试:去你妹的,又不是不能用🐶🐶🐶

**Comment by silendir** [comment]
![IMG_0016](https://user-images.githubusercontent.com/11792633/96997913-3f21ec00-1565-11eb-9e8e-28d3399f0492.jpg)
完蛋了...怎么圆圈外面有小蝌蚪尾巴?
![image](https://user-images.githubusercontent.com/11792633/96997969-55c84300-1565-11eb-90c1-a535b976f303.png)

**Comment by silendir** [comment]
完蛋了...怎么圆圈外面有小蝌蚪尾巴?
![IMG_0016](https://user-images.githubusercontent.com/11792633/96998044-6d073080-1565-11eb-8077-299adde312db.jpg)
![截屏2020-10-23 下午7 25 12](https://user-images.githubusercontent.com/11792633/96998096-7e503d00-1565-11eb-8435-e03692710a79.jpg)
