### ISSUE TITLE
tipTools在模拟器和真机上表现不一致

### ISSUE THREAD

**Issue by silendir** [AAChartModel/AAChartKit#1028]
模拟器上的:
![截屏2020-10-24 上午6 58 58](https://user-images.githubusercontent.com/11792633/97060790-13375280-15c7-11eb-9e07-6b4a9e4314f0.jpg)
真机上的:
![IMG_1606](https://user-images.githubusercontent.com/11792633/97060833-437ef100-15c7-11eb-8b38-fdc5d38bfd9b.jpg)
真机上无论点那里tipTools始终黏在左上角用的都是一样的代码:
    aaOptions.tooltip //有bug
        .positionerSet(@AAJSFunc(function (labelWidth, labelHeight, point) {
            let position = {};
            position["x"] = point.plotX;
            position["y"] = 20;
            return position;
        }));

**Comment by silendir** [comment]
或者能不能获取这个点击数据点的时机, 出发jspath 我自定义一个原生的在界面上跑, 这个点击时机是在哪里

**Comment by AAChartModel** [comment]
> 或者能不能获取这个点击数据点的时机

柱状图支持点击事件
