### ISSUE TITLE
数据点外出现小蝌蚪尾巴

### ISSUE THREAD

**Issue by silendir** [AAChartModel/AAChartKit#1029]
![96998044-6d073080-1565-11eb-8077-299adde312db](https://user-images.githubusercontent.com/11792633/97061064-0cf5a600-15c8-11eb-9585-b83501d79552.jpg)
![96998096-7e503d00-1565-11eb-8435-e03692710a79](https://user-images.githubusercontent.com/11792633/97061067-0ebf6980-15c8-11eb-837b-031363fdd930.jpg)

**Comment by AAChartModel** [comment]
这个应该是 Highcharts 在 iOS 14 上的一个 bug,我已经提了一个 issue 

https://github.com/highcharts/highcharts/issues/14424

**Comment by silendir** [comment]
#1028 这个模拟器可以移动x轴,真机不行是不是也是highcharts 的bug 要不一起交了吧, 这个功能对我来说太重要了

**Comment by AAChartModel** [comment]
> #1028 这个模拟器可以移动x轴,真机不行是不是也是highcharts 的bug 要不一起交了吧, 这个功能对我来说太重要了

这个是我这边的问题,我改了还没提交,今天下班前提交一下

**Comment by silendir** [comment]
谢谢大神! toolTip 可以超过那个100 显示在整个图表的最上面么?  是图表下沉?

**Comment by AAChartModel** [comment]
> 谢谢大神! toolTip 可以超过那个100 显示在整个图表的最上面么? 是图表下沉?

设置 Y轴最大值远超你的  AASeriesElement 的 data  数组中的最大值,同时自定义 AATooltip 的 Positioner 即可. 示例如下

```objc

- (AAOptions *)customTooltipPostionerFunction {
    NSArray *categoriesArr = @[
        @"孤岛危机",
        @"使命召唤",
        @"荣誉勋章",
        @"狙击精英",
        @"神秘海域",
        @"最后生还者",
        @"巫师3狂猎",
        @"对马之魂",
        @"蝙蝠侠阿甘骑士",
        @"地狱边境",
        @"闪客",
        @"忍者之印"
    ];
    
    AAChartModel *aaChartModel = AAChartModel.new
    .chartTypeSet(AAChartTypeColumn)
    .categoriesSet(categoriesArr)
    .yAxisMaxSet(@100)
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"单机大作")
        .colorSet(AAColor.redColor)
        .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6])
               ])
    ;
    
    AAOptions *aaOptions = aaChartModel.aa_toAAOptions;
    
    aaOptions.tooltip
    .positionerSet(@AAJSFunc(function (labelWidth, labelHeight, point) {
        let position = {};
        position["x"] = point.plotX;
        position["y"] = 20;
        return position;
    }));
    
    return aaOptions;
}
```

**Comment by silendir** [comment]
我们老板想我们做成HealthKit那个一样的.. 但他要的曲线HealthKit也没有,就您的可以实现, 烦死我

**Comment by silendir** [comment]
他要y轴外围去显示ToolTip. 但是y轴不能在ToolTip下面..就是苹果健康那个样..但是苹果健康是没有异色曲线的, 我说你这个四适应Tooltip更好看他们又不肯
![IMG_1763](https://user-images.githubusercontent.com/11792633/97383230-13f22080-1908-11eb-9229-0ec3c323a80a.PNG)
![IMG_1755](https://user-images.githubusercontent.com/11792633/97383233-16547a80-1908-11eb-8884-6960064e11be.PNG)

**Comment by AAChartModel** [comment]
> 我们老板想我们做成HealthKit那个一样的.. 但他要的曲线HealthKit也没有,就您的可以实现, 烦死我

苹果的 ResearchKit 是有曲线图表的,参见 http://www.cocoachina.com/articles/16046

**Comment by AAChartModel** [comment]
是在不行的话, AAChartView 的点击回调事件中支持获取 x 轴相关信息

```js
2020-10-28 10:56:03.597499+0800 AAChartKitDemo[94865:3129308] 👌👌👌👌  user finger moved over!!!,get the move over event series element message: 
 {
  "y" : 21.5,
  "index" : 5,
  "offset" : {
    "plotX" : 330.45833333333002,
    "plotY" : 120.02156334231807
  },
  "name" : "单机大作",
  "x" : 5,
  "category" : "最后生还者"
}
```

你可以隐藏 AAChartView 的 AATooltip,然后根据点击回调事件中的坐标信息,来自定义 UIView 视图以实现自定义绘图区外的浮动提示框.  

之前有 AAChartKit 的使用者就是这么做的.

**Comment by AAChartModel** [comment]
找到解决方案了, 为 Y 轴新增了两个关键属性, 稍晚一些时间,我会提交一下代码

**Comment by silendir** [comment]
大神实在太牛逼了... 苹果跟你比简直弱爆了

**Comment by AAChartModel** [comment]
> 大神实在太牛逼了... 苹果跟你比简直弱爆了

适当吹捧即可,你这样有点过分了哈🤣

**Comment by AAChartModel** [comment]
问题已解决,参见 #1033

**Comment by AAChartModel** [comment]
如 README 文档中所说, 不指定 pods 版本,更新至 AAChartKit 至最新内容即可使用新增的属性

**Comment by silendir** [comment]
已经更新了么?

**Comment by silendir** [comment]
大神 AALineStyle * 现在没有了

**Comment by AAChartModel** [comment]
你 pods 更新到最新内容的 AAChartKit 也没有?

**Comment by silendir** [comment]
现在AAmodel里面
//.xAxisGridLineWidthSet(@0.2)
    //.yAxisGridLineWidthSet(@0.2)
这些属性取消了... 有了一个新的style

**Comment by AAChartModel** [comment]
我把这几个接口合并成一个 style 了,你改一下就行了

**Comment by silendir** [comment]
了解了, 用习惯了,感觉挺好用

**Comment by silendir** [comment]
那个小蝌蚪还是有........

**Comment by AAChartModel** [comment]
https://github.com/highcharts/highcharts/issues/14424#issuecomment-716495903

**Comment by AAChartModel** [comment]
这是 WebKit 在 iOS v14  上的一个 bug, 没办法了.  只要设置了 AAMarker 的 borderWidth 就会有. 只能跟产品商量在 iOS 14 上更改设计样式了

**Comment by silendir** [comment]
您意思是highcharts表示没办法解决,必须等苹果的意思么?

**Comment by AAChartModel** [comment]
是的,这个不是 Highcharts 的 bug, 是 WKWebView 的渲染内核 WebKit 本身的 bug.  就好像你的应用 APP 的列表页的数据逻辑是完全正常的, 但是 UITableView 本身有 bug,你觉得能怎么解决问题?

**Comment by silendir** [comment]
![image](https://user-images.githubusercontent.com/11792633/97848876-b22d1e80-1d2c-11eb-98ec-703be3fcfaf7.jpeg)
关于这个的例子在哪里?

**Comment by AAChartModel** [comment]
这个问题不是已经在 #1033 解决了吗?
