### ISSUE TITLE
折线图 如何显示最大值和最小值？

### ISSUE THREAD

**Issue by bq767630631** [AAChartModel/AAChartKit#1034]
如题！  （图片插不进来 ，晕）

**Comment by AAChartModel** [comment]
重复问题, 参见 https://github.com/AAChartModel/AAChartKit/issues/546

**Comment by AAChartModel** [comment]
补充说明: 需要自己找到 data 数组中国的最大值和最小值,然后自定义对应的元素的 AADataElement 即可
