### ISSUE TITLE
请问tooltip怎么设置手动消失呢，希望在切换数据的时候，可以把tooltip消失

### ISSUE THREAD

**Issue by zhoupIT** [AAChartModel/AAChartKit#1035]
我看到有这个tooltipEnabled属性，但是设置了没有效果

**Comment by AAChartModel** [comment]
tooltipEnabled 这个属性是用来设置是否显示 tooltip 的, 而不是用来显示 tooltip 是否自动消失的

**Comment by zhoupIT** [comment]
那有什么办法可以让tooltip自动消失的么

**Comment by zhoupIT** [comment]
好了，我之前用的aa_updateXAxisCategories 和aa_onlyRefreshTheChartDataWithChartModelSeries来更新x轴和Y轴的。现在换成aa_refreshChartWithChartModel来更新数据 ，tooltip会自动消失了
谢谢大佬

**Comment by silendir** [comment]
就是直接Refresh来让它消失? 有没有办法在不改变图例(就是保持各种缩放和滚动offset的情况下) 直接消失?
