### ISSUE TITLE
如何禁止点击效果

### ISSUE THREAD

**Issue by JenkenXu** [AAChartModel/AAChartKit#1037]
<img width="144" alt="WeChat4c40b142cbc3877b923dcd7888dc499c" src="https://user-images.githubusercontent.com/31434367/97426045-db753580-194d-11eb-85ba-807fbeb97581.png">
点击时候不要有任何变化，连接点不变大，竖线别显示出来

**Comment by AAChartModel** [comment]
重复问题, 参见 https://github.com/AAChartModel/AAChartKit/issues/948

**Comment by AAChartModel** [comment]
> 竖线别显示出来

竖线是准星线,设置准星线隐藏即可

**Comment by AAChartModel** [comment]
> 连接点不变大

参见 https://github.com/AAChartModel/AAChartKit/issues/909
