### ISSUE TITLE
昨天做的那个功能，是新增了两个最大值和最小值。能不能在原来值的基础上标识最大和最小？新增的值对应的横坐标也有问题

### ISSUE THREAD

**Issue by bq767630631** [AAChartModel/AAChartKit#1039]
NSArray*max_min =  [self getMaxAndMinWithArr:orderArr];
    AAMarker *aaMarker = AAMarker.new
    .radiusSet(@2)//曲线连接点半径，默认是4
    .symbolSet(AAChartSymbolTypeCircle)//曲线点类型："circle", "square", "diamond", "triangle","triangle-down"，默认是"circle"
    .fillColorSet(@"#ffffff")//点的填充色(用来设置折线连接点的填充色)
    .lineWidthSet(@1)//外沿线的宽度(用来设置折线连接点的轮廓描边的宽度)
    .lineColorSet(@"");//外沿线的颜色(用来设置折线连接点的轮廓描边颜色，当值为空字符串时，默认取数据点或数据列的颜色)
    
    
    AADataLabels *aadatalb = AADataLabels.new
    .enabledSet(YES)
    .backgroundColorSet(@"#e83928")
    .borderRadiusSet(@3)
    .colorSet(@"#ffffff")
    .styleSet([AAStyle styleWithColor:@"#DAA520" fontSize:11 fontWeight:nil textOutline:@"0px 0px contrast"])  //textOutline:@"1px 1px #ffffff"
    .ySet(@0)
    .xSet(@0)
   
    ;
    
    AADataElement *data_max = AADataElement.new
    .markerSet(aaMarker)
    .dataLabelsSet(aadatalb)
    .ySet(max_min.firstObject)
    ;
    
    AADataElement *data_min = AADataElement.new
    .markerSet(aaMarker)
    .dataLabelsSet(aadatalb)
    .ySet(max_min.lastObject)
    ;
    
    NSMutableArray*dataArr = [NSMutableArray arrayWithArray:orderArr];
    [dataArr addObject:data_max];
    [dataArr addObject:data_min];
    
    AASeriesElement *element = AASeriesElement.new
    .nameSet(name)
    .typeSet(AAChartTypeLine)
    .borderRadiusSet(@2)
    .colorSet(@"#e83928")
    .markerSet(aaMarker)
    .dataSet(dataArr)
    ;

**Comment by AAChartModel** [comment]
```objc
NSMutableArray*dataArr = [NSMutableArray arrayWithArray:orderArr];
[dataArr addObject:data_max];
[dataArr addObject:data_min];
```

你这部分代码明显有问题啊, 应该是调用 NSMutableArray 的 replaceObjectAtIndex 方法来将原来的 NSNumber 元素替换为你改装的 data_max 和 data_min

**Comment by bq767630631** [comment]
额

**Comment by AAChartModel** [comment]
你看 AAChartKit 的 demo 中的示例代码就知道是怎么回事了
