### ISSUE TITLE
Configure tooltip on a per value basis

### ISSUE THREAD

**Issue by skuske** [AAChartModel/AAChartKit#104]
Highcharts offers the **tooltip.pointFormat** option, but it looks like this is not supported by AAChartKit. With HighCharts you can configure the tooltip output like this:

`tooltip.pointFormat = @"<b>{point.value:.1f} - {point.direction:.1f}°</b><br/>"`

In combination with the 'keys' option (https://api.highcharts.com/ios/highcharts/plotOptions.area.keys) it would be easy to display additional information in the tooltip for a specific point.

Any way to do that with AAChartKit?

**Comment by AAChartModel** [comment]
You can change it in AAOptionsConstructor.m by yourself.

change the content 
```objective-c
    AATooltip *tooltip = AAObject(AATooltip)
    .enabledSet(true)//启用浮动提示框
    .sharedSet(true)//多组数据共享一个浮动提示框
    .crosshairsSet(chartModel.tooltipCrosshairs)
    .valueSuffixSet(chartModel.tooltipValueSuffix);//浮动提示框的单位名称后缀
```
to be 

```objective-c
 AATooltip *tooltip = AAObject(AATooltip)
    .pointFormatSet(@"<b>{point.value:.1f} - {point.direction:.1f}°</b><br/>")
    .enabledSet(true)//启用浮动提示框
    .sharedSet(true)//多组数据共享一个浮动提示框
    .crosshairsSet(chartModel.tooltipCrosshairs)
    .valueSuffixSet(chartModel.tooltipValueSuffix);//浮动提示框的单位名称后缀
```

**Comment by AAChartModel** [comment]
That is to say,all you need to do is to add the content as follow
```objective-c
    .pointFormatSet(@"<b>{point.value:.1f} - {point.direction:.1f}°</b><br/>")
``

**Comment by skuske** [comment]
Yes, but that is a global change, which applies to all charts then... I would like to set this on a per chart basis, and not for all charts...

**Comment by AAChartModel** [comment]
per chart? Do you mean pie chart?

**Comment by skuske** [comment]
I mean any kind of chart. If I change AAOptionsConstructor.m as you suggested, then the change affects **all** charts that I create. However, I want to configure the tooltip while I configure the AAObject(AAChartModel). 

Example:

```
self.aaChartModel= AAObject(AAChartModel)
    .tooltip.pointFormat=@"<b>{point.y:.1f} - {point.rotation:.1f}°</b><br/>";
```

**Comment by skuske** [comment]
Got it - I added this:

To AAChartModel.h:

`AAPropStatementAndFuncStatement(copy  , AAChartModel, NSString *, tooltipValueString);`

To AAChartModel.m:

`AAPropSetFuncImplementation(AAChartModel, NSString *, tooltipValueString);`

and to AAOptionsConstructor.m:

`.pointFormatSet(chartModel.tooltipValueString)`

That lets me configure the tooltip as I want... :o) Maybe you implemet that to the next update.

**Comment by AAChartModel** [comment]
💐💐💐So nice!!!💐💐💐

**Comment by skuske** [comment]
Here's some more changes to support 'keys' of the series element - see this:

https://api.highcharts.com/ios/highcharts/series.area.keys

What you need to change in AAChartKit is this:

In AASeries.h add this:

`AAPropStatementAndFuncStatement(copy,   AASeries, NSArray      *, keys);`

In AASeries.m add this:

`AAPropSetFuncImplementation(AASeries, NSArray      *, keys);`

In AASeriesElement.h add this:

`AAPropStatementAndFuncStatement(copy,   AASeriesElement, NSArray  *, keys);`

In AASeriesElement.m add this:

AAPropSetFuncImplementation(AASeriesElement, NSArray  *, keys);

and in AAOptionsConstructor.m change this:

```
    AAPlotOptions *plotOptions = AAObject(AAPlotOptions)
    .seriesSet(AAObject(AASeries)
               //             .colorByPointSet(false)//决定了图表是否给每个数据列或每个点分配一个颜色，默认值是 false， 即默认是给每个数据类分配颜色，
               .stackingSet(chartModel.stacking)//设置是否百分比堆叠显示图形
               //               .animationSet(AAObject(AAAnimation)
               //                             .easingSet(chartAnimationType)
               //                             .durationSet(chartModel.animationDuration)
               //                             )
               );
```

to this:

```
    AAPlotOptions *plotOptions = AAObject(AAPlotOptions)
    .seriesSet(AAObject(AASeries)
               //             .colorByPointSet(false)//决定了图表是否给每个数据列或每个点分配一个颜色，默认值是 false， 即默认是给每个数据类分配颜色，
               .stackingSet(chartModel.stacking)//设置是否百分比堆叠显示图形
               .keysSet(chartModel.keys)
               //               .animationSet(AAObject(AAAnimation)
               //                             .easingSet(chartAnimationType)
               //                             .durationSet(chartModel.animationDuration)
               //                             )
               );
```

When you implement those changes, you can set 'keys' to a series element like this:

```
    self.aaChartModel= AAObject(AAChartModel)
    .seriesSet(@[
                 AAObject(AASeriesElement)
                 .nameSet(strNameSet)
                 .keysSet(@[@"y", @"rotation"])
                 .dataSet(valueArray)
                 ]
               )
```

That way you can easily configure your tooltip with additional values from the data array:

`.tooltipValueStringSet(@"<b>{point.y:.1f} - {point.rotation:.1f}°</b><br/>")`

Maybe you implement that, too! 👍
