### ISSUE TITLE
请问一下Tooltip设置的问题

### ISSUE THREAD

**Issue by XuDongLiu-star** [AAChartModel/AAChartKit#1040]
请问如何设置tooltip的时候或者设置headerFormat的时候如何获取到categories的值。就是自定义x轴的文字数组里的值。

**Comment by AAChartModel** [comment]
{point.x}

**Comment by AAChartModel** [comment]
demo 中有示例,搜一下看看就知道

**Comment by AAChartModel** [comment]
参见问题 #1033 

你看这里的月份信息就是这样获得的

```objc
    .footerFormatSet(@"2020 年 {point.x} ")
```

**Comment by AAChartModel** [comment]
关于市场深度图  参见 https://github.com/AAChartModel/AAChartKit/issues/772

**Comment by XuDongLiu-star** [comment]
你好。point.x取到的是1、2、3、4这种值，应该是数组的下标。而不是自定义x轴的值，我什么都不设置看您默认显示的却取到了x的值，想知道您用的什么方法去到的

**Comment by XuDongLiu-star** [comment]
或者我能在footformat中取到data数组中某点的值也行。我对js实在是不太懂，谢谢了

**Comment by AAChartModel** [comment]
参考: https://api.highcharts.com.cn/highcharts#tooltip.headerFormat

> 坐标轴类型的不同，point.key变量类型可能为类别名称， x值或者日期字符串。

由上可知, 你试试 {point.key}

**Comment by XuDongLiu-star** [comment]
{pint.key}获取不到数据，是空。我把代码贴上您帮我看下
       AAChartModel *aaChartModel = AAChartModel.new
      .backgroundColorSet(@"#151F2F")
  //    .titleSet(@"🟢买     🔴卖")
      .chartTypeSet(AAChartTypeArea)//图表类型
      .colorsThemeSet(@[@"#12B886",@"#EB4D5C"])//设置主题颜色数组
//      .colorsThemeSet(@[@"#15363C",@"#352636"])//设置主题颜色数组

      .yAxisLineWidthSet(@0)//Y轴轴线线宽为0即是隐藏Y轴轴线
      .yAxisGridLineWidthSet(@0)//y轴横向分割线宽度为0(即是隐藏分割线)
      .categoriesSet(categoriesSet)//设置 X 轴坐标文字内容 就是要显示这个数组里的值
      .legendEnabledSet(false)
      .seriesSet(@[
          AASeriesElement.new
          .nameSet(NSLocalizedString(@"买入", nil))
          .dataSet(bidArray),//数据
          AASeriesElement.new
          .nameSet(NSLocalizedString(@"卖出", nil))
          .dataSet(askArray),//数据
      ]);
      aaChartModel.yAxisTickPositions = array; //Y轴的自定义数据
      aaChartModel.animationDuration = @(0);
      aaChartModel.animationTypeSet(AAChartAnimationBounce);
      aaChartModel.markerRadius = @0;
    aaChartModel.yAxisVisible = NO;
    aaChartModel.xAxisVisible = NO;
    aaChartModel.connectNulls = NO;
      AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
      aaOptions.tooltip
      .sharedSet(false)
      .useHTMLSet(true)
      .headerFormatSet(@"数量:{point.y}")
      .pointFormatSet(@"价格:{point.x}"); //就是这里获取不到x轴的值，point.key还有其他的都是空，point.x是数组下标。值获取不到。如果我不设置就用您的默认显示就会显示x轴自定义数组的值。请问您默认怎么取值得？
[self.aaChartView aa_drawChartWithOptions:aaOptions];

**Comment by XuDongLiu-star** [comment]
哈哈，用示例里的formatterset 里的this.x可以获取到。谢谢了

**Comment by XuDongLiu-star** [comment]
主要不太懂这个js写法，惭愧
