### ISSUE TITLE
五边形的雷达图为什么在添加自定义的xAxis之后 五边形会倒过来，不添加就是正的

### ISSUE THREAD

**Issue by tipshot** [AAChartModel/AAChartKit#1041]
五边形的雷达图为什么在添加自定义的xAxis之后 五边形会倒过来，不添加就是正的。请问是什么地方影响的？如何解决？

**Comment by tipshot** [comment]
经过测试发现产生原因：一旦设置了X轴的categories就会产生这个原因。

**Comment by AAChartModel** [comment]
```objc
        case 0: _aaChartModel.xAxisReversed = isOn; break;
        case 1: _aaChartModel.yAxisReversed = isOn; break;
        case 2: _aaChartModel.inverted = isOn; break;
```

你试试调整 AAChartModel 的这几个属性,看看能不能解决这个翻转问题

**Comment by tipshot** [comment]
这个方法经测试后发现不行。

**Comment by tipshot** [comment]
![image](https://user-images.githubusercontent.com/18547353/97682960-3d12dc80-1ad3-11eb-93bc-0e36fe4fa925.png)
添加以上三个是这样的

**Comment by tipshot** [comment]
![image](https://user-images.githubusercontent.com/18547353/97683256-53209d00-1ad3-11eb-95bc-754d8a469901.png)
添加完之后变成这样的了

**Comment by tipshot** [comment]
![image](https://user-images.githubusercontent.com/18547353/97683623-6a5f8a80-1ad3-11eb-91ab-466c2fccc2f2.png)
这是我们d的设计图

**Comment by tipshot** [comment]
![image](https://user-images.githubusercontent.com/18547353/97685247-f40f5800-1ad3-11eb-85b1-66d4a6d5c11e.png)

**Comment by tipshot** [comment]
经过测试发现不行，无法调整成正常的

**Comment by AAChartModel** [comment]
不好意思我忘了, 这个问题之前已经解决过, 参见 https://github.com/AAChartModel/AAChartKit/issues/789

**Comment by AAChartModel** [comment]
AAChartKit 现在默认已经有了 

```objc
AAPropStatementAndPropSetFuncStatement(copy,   AASeriesElement, NSString *, pointPlacement)

```

这个属性, 不用手动添加, 你直接用就可以了.
