### ISSUE TITLE
几个数据值都为0时 怎么让扇形图显示 目前时一片空白 希望可以显示  比如3个数据 就各占三分之一 内容都是%0 而不是33%

### ISSUE THREAD

**Issue by KillWilde** [AAChartModel/AAChartKit#1042]

**Comment by AAChartModel** [comment]
我觉得你的需求有点奇怪

**Comment by KillWilde** [comment]
就是服务端返回的 3项数据都是0 android的用了其他的库显示的扇形 可以显示出来 每个项各占三分之一 我这边不知道能不能实现 目前扇形是一片空白；

**Comment by AAChartModel** [comment]
AAChartKit 倒是可以实现,就是有点复杂,你需要自定义的地方很多. 解决步骤基本是:

1. 判断三项数据是否都是 0, 如果是这种情况, 则将三项数据都替换为 1.
2. 如果显示 DataLabels 的话,需要通过  AADataLabels 的 formatter 函数来自定义 DataLabels 的文字内容.
3. 如果显示 Tooltip 的话, 需要通过 AATooltip 的 formatter 函数来自定义 Tooltip 的文字内容.

这几个步骤下来,虽然扇形图实际上显示的是`@[@1,@1,@1]`数组,但是从用户的角度看起来却是 `@[@0,@0,@0]`

**Comment by AAChartModel** [comment]
通过 Google ,竟然发现了一模一样的问题 , 参见https://stackoverflow.com/questions/48995295/highcharts-make-pie-chart-show-0-data

**Comment by KillWilde** [comment]
多谢 楼主
