### ISSUE TITLE
自定义pointFormat怎么设置AATooltip小圆点展示出来

### ISSUE THREAD

**Issue by Snail-hash** [AAChartModel/AAChartKit#1044]
![image](https://user-images.githubusercontent.com/29391046/97773795-ca1a6c00-1b8d-11eb-8add-ff361d2aa625.png)
element.tooltipSet(AATooltip.new
                       .pointFormatSet(count == 0 ? @"{series.name}: 0" : @"{series.name}: {point.y}"));

**Comment by AAChartModel** [comment]
在字符串前加上 `<span style=""color:{point.color}"">◉</span>`试试, 就像这样:

```objc
    .pointFormatSet(count == 0 ? @"<span style=""color:{point.color}"">◉</span>{series.name}: 0" : @"<span style=""color:{point.color}"">◉</span>{series.name}: {point.y}"));
```
