### ISSUE TITLE
大神 这种的该怎么设置填充到y轴最小值

### ISSUE THREAD

**Issue by liubang0909** [AAChartModel/AAChartKit#1051]
![截屏2020-11-08 上午3 23 37](https://user-images.githubusercontent.com/12213692/98449785-cbd9c600-2171-11eb-8c4c-2c4eac211f71.png)

**Comment by liubang0909** [comment]
markerSymbol的大小该怎么设置

**Comment by AAChartModel** [comment]
> 这种的该怎么设置填充到y轴最小值

你这不是已经填充到 Y 轴最小值了吗?

**Comment by AAChartModel** [comment]
> markerSymbol的大小该怎么设置

```objc
//折线连接点的半径长度
AAPropStatementAndPropSetFuncStatement(strong, AAChartModel, NSNumber *,  markerRadius) 
```

**Comment by liubang0909** [comment]
.thresholdSet(@(-30))    是设置这个属性吗大神。。 这个属性是啥意思啊。。

**Comment by AAChartModel** [comment]
> .thresholdSet(@(-30)) 是设置这个属性吗大神。。 这个属性是啥意思啊。。

https://api.highcharts.com.cn/highcharts#series%3Cspline%3E.threshold
