### ISSUE TITLE
想给PlotLines加个背景色,不知道能不能自定义

### ISSUE THREAD

**Issue by silendir** [AAChartModel/AAChartKit#1052]
![image](https://user-images.githubusercontent.com/11792633/98627428-33993800-234f-11eb-8cf3-610ae79b2874.jpeg)

![image](https://user-images.githubusercontent.com/11792633/98627381-17959680-234f-11eb-8279-54c0d474c157.jpeg)

**Comment by silendir** [comment]
![image](https://user-images.githubusercontent.com/11792633/98627906-49f3c380-2350-11eb-9d08-a5603075cd88.jpeg)
.textOutlineSet(@"5px 5px contrast")

**Comment by silendir** [comment]
写错地方, 效果出来了, 但是为什么有一个是白色的... 由哪个属性控制么?

**Comment by AAChartModel** [comment]
![](https://user-images.githubusercontent.com/11792633/98627381-17959680-234f-11eb-8279-54c0d474c157.jpeg)

看到这里的黄色警告⚠️了吗?你这个用的不对,赋值类型应该是 AAStyle 对象
