### ISSUE TITLE
雷达图 如何去掉选中效果（那条线）以及中间的“0”，

### ISSUE THREAD

**Issue by tipshot** [AAChartModel/AAChartKit#1057]
![image](https://user-images.githubusercontent.com/18547353/98789918-f069c280-243d-11eb-9205-b1f1d792f64b.png)

**Comment by tipshot** [comment]
![image](https://user-images.githubusercontent.com/18547353/98790822-31aea200-243f-11eb-9b2c-7b330d1f4316.png)

**Comment by AAChartModel** [comment]
> 选中效果（那条线）

这个是准星线,设置准星线宽度为 0 (隐藏准星线) 即可

**Comment by AAChartModel** [comment]
> 中间的“0”

这个你隐藏一下 x 轴或者是 Y 轴, 这个 0 应该就消失了

**Comment by tipshot** [comment]
> > 中间的“0”
> 
> 这个你隐藏一下 x 轴或者是 Y 轴, 这个 0 应该就消失了

隐藏Y轴后，分层色块也就随之消失了，但是需要实现的效果是去掉0，保留色块。

**Comment by AAChartModel** [comment]
那你再试试隐藏 X 轴或者 Y 轴的 labels
