### ISSUE TITLE
请问折线图是否可以在绘制完后默认选中第一个点显示tooltip呢？

### ISSUE THREAD

**Issue by feng-tianyou** [AAChartModel/AAChartKit#1058]
显示完折线图的数据
<img width="339" alt="image" src="https://user-images.githubusercontent.com/14937470/98884191-7b909a00-24ca-11eb-9f4b-84f932ba5691.png">
然后默认显示第一个点的tooltip
<img width="339" alt="image" src="https://user-images.githubusercontent.com/14937470/98884164-6ddb1480-24ca-11eb-9dc9-a226297eb398.png">

**Comment by zxxxxx** [comment]
找到对应方法了吗？ 我也想实现这个功能

**Comment by Ficky-Michy** [comment]
找到对应方法了吗？ 我也想实现这个功能

**Comment by AAChartModel** [comment]
问题已解决, 参考:

* https://github.com/AAChartModel/AAChartKit-Swift/issues/345
