### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by AlliumLiu** [AAChartModel/AAChartKit#106]
直接把AAChartKitLib文件夹拖入到工程 报错 Parse Issue
A parameter list without types is only allowed in a function definition
Expected ')'
Unexpected type name 'NSString': expected identifier
 .pch 文件 也添加了#import "AAGlobalMacro.h"

**Comment by congcongliu** [comment]
链接： https://github.com/congcongliu/AAChatDemo.git

**Comment by AAChartModel** [comment]
感觉你应该是添加. pch 文件的方式不对吧,你可以直接将文件夹拖入到你的实际项目的中,再在. pch 文件中添加
```objective-c
#import "AAGlobalMacro.h"
```
中再试一下.

**Comment by congcongliu** [comment]
果真是.pch 问题 要在 build setting那边设置 .pch 路径
