### ISSUE TITLE
两个图标grouping之后,点击虚位或者另一条图表,有一条会变成半透明, 这个效果怎么关闭掉?

### ISSUE THREAD

**Issue by silendir** [AAChartModel/AAChartKit#1060]
两个图标grouping之后,点击虚位或者另一条图表,有一条会变成半透明, 这个效果怎么关闭掉?
![98670894-5c8ced80-238e-11eb-9b4e-067285bd6bdb](https://user-images.githubusercontent.com/11792633/98891289-dd580080-24d8-11eb-84c9-9ddfd831c985.jpeg)
![98669480-64e42900-238c-11eb-9fd9-203ce0699635](https://user-images.githubusercontent.com/11792633/98891295-dfba5a80-24d8-11eb-8f93-011a30e1bfde.jpeg)

**Comment by AAChartModel** [comment]
https://github.com/AAChartModel/AAChartKit/issues/949
