### ISSUE TITLE
Y轴数据全部为0时Y轴向上偏移

### ISSUE THREAD

**Issue by Snail-hash** [AAChartModel/AAChartKit#1062]
![image](https://user-images.githubusercontent.com/29391046/98906472-0f2c8f80-24f8-11eb-9bf1-25852191fd37.png)
自定义Y轴坐标也不生效
chartModel.yAxisTickPositions = @[@0,@1];

**Comment by AAChartModel** [comment]
重复问题, 参见 https://github.com/AAChartModel/AAChartKit/issues/773
