### ISSUE TITLE
有没有办法实现这种峰值图?

### ISSUE THREAD

**Issue by silendir** [AAChartModel/AAChartKit#1064]
![image](https://user-images.githubusercontent.com/11792633/99027359-fc719380-25a7-11eb-814e-e95783921a71.jpeg)
必须在每个x轴数据插入一个0位..  [4, 0, 5,0,9]

**Comment by silendir** [comment]
但是这样tooltip会显示0位的数据, 
有没有一种办法把直方图削成尖?😝

**Comment by AAChartModel** [comment]
这个和图表类型没什么关系吧, 折线图的数据比较密集而且起伏比较大的时候就会出现这种显示效果吧
