### ISSUE TITLE
强烈建议老哥建个qq群。。

### ISSUE THREAD

**Issue by bq767630631** [AAChartModel/AAChartKit#1066]
这样大家讨论方便多了啊

**Comment by AAChartModel** [comment]
以下是我为什么不建立 QQ 群的原因.
1. QQ 群的伸手党客观上更多一些
2. 而且 QQ 群内的所有问题都是封闭的,群外的人无法访问
3. 历史问题无法被分门别类,难以被准确记录,导致很多问题反复被无效重提
4. 无法被搜索引擎检索,不利于项目传播.
5. 以我丰富的技术群潜水经验来看, 所有的技术群最后都无一例外的成为了吹水群.

为了避免给世界制造更多的无价值信息, 所以 QQ 群显然不是个好的选项.
