### ISSUE TITLE
How to change Y-Axis values now displaying (0,10,20,30)

### ISSUE THREAD

**Issue by Saipujith** [AAChartModel/AAChartKit#107]
@AAChartModel @congcongliu     How to change Y-Axis values now displaying (0,10,20,30) defaults for all type of charts.please check below image link

[img_0470](https://user-images.githubusercontent.com/13308273/34723379-59833300-f570-11e7-8735-48f89ac94026.PNG)

**Comment by AAChartModel** [comment]
This is automatically generated based on the chart series data you set

**Comment by Saipujith** [comment]
.categoriesSet(@[@"Java",@"Swift",@"Python",@"Ruby", @"PHP",@"Go",@"C",@"C#",@"C++",@"Perl",@"R",@"MATLAB",@"SQL"]) 

.categoriesSet(@[@"1",@"2",@"3",@"4", @"5",
                     @"6",@"7",@"8",@"9",@"10",@"11",@"12",@"13"])
i modified these values, updated x -axis values, but can't figure out y-axis values

[oldvalues](https://user-images.githubusercontent.com/13308273/34755924-7271a9f0-f5ed-11e7-9cc0-c83424a9f379.PNG)
[updatedxaxis](https://user-images.githubusercontent.com/13308273/34755925-72a149ee-f5ed-11e7-9e34-d13d2c0c416d.PNG)
