### ISSUE TITLE
求教，点击折线图后，折线图断开了。如何设置

### ISSUE THREAD

**Issue by NashAnd** [AAChartModel/AAChartKit#1070]
![441605595757_ pic](https://user-images.githubusercontent.com/14804016/99355897-141c8500-28e4-11eb-8d6f-23b583816eeb.jpg)

**Comment by NashAnd** [comment]
![WechatIMG44](https://user-images.githubusercontent.com/14804016/99356243-d0764b00-28e4-11eb-8794-920fc1a631f4.jpeg)
[](url)

**Comment by AAChartModel** [comment]
你这个是因为 AAMarker 标记点遮挡了折线吧,你隐藏标记点试试.

**Comment by NashAnd** [comment]
> 你这个是因为 AAMarker 标记点遮挡了折线吧,你隐藏标记点试试.

试了下，发现不是。

**Comment by AAChartModel** [comment]
问题是必现的吗?

**Comment by AAChartModel** [comment]
任何系统版本,任何机型上都会出现此问题?

**Comment by NashAnd** [comment]
iOS 系统下面14以上出现。以前没这个问题，后面才出现的。

**Comment by NashAnd** [comment]
如果两条折线图 上面的点 比较密集，就会出现。如果点少不会出现。

**Comment by AAChartModel** [comment]
这就有点蛋疼了,搞得不好是 iOS 14 上, WebKit 的 bug

**Comment by NashAnd** [comment]
除了AAMarker 有可能外， 还有其他因素会导致这种问题出现吗？

**Comment by AAChartModel** [comment]
之前就有iOS 14 上的 WebKit 的 bug 导致图表显示有些异常  https://github.com/highcharts/highcharts/issues/14424

**Comment by AAChartModel** [comment]
> 除了AAMarker 有可能外， 还有其他因素会导致这种问题出现吗？

你把控制台的 json 打印输出复制粘贴出来看看

**Comment by NashAnd** [comment]
{
  "credits" : {
    "enabled" : false
  },
  "touchEventEnabled" : true,
  "chart" : {
    "polar" : false,
    "backgroundColor" : "rgba(0,0,0,0)",
    "type" : "line",
    "inverted" : false,
    "pinchType" : "none",
    "panning" : true
  },
  "tooltip" : {
    "useHTML" : true,
    "followTouchMove" : true,
    "formatter" : "(function () { return \\\"The value for <b>\\\" + [\\\"2020-03-23\\\",\\\"2020-03-24\\\",\\\"2020-03-25\\\",\\\"2020-03-26\\\",\\\"2020-03-27\\\",\\\"2020-03-30\\\",\\\"2020-03-31\\\",\\\"2020-04-01\\\",\\\"2020-04-02\\\",\\\"2020-04-03\\\",\\\"2020-04-07\\\",\\\"2020-04-08\\\",\\\"2020-04-09\\\",\\\"2020-04-10\\\",\\\"2020-04-13\\\",\\\"2020-04-14\\\",\\\"2020-04-15\\\",\\\"2020-04-16\\\",\\\"2020-04-17\\\",\\\"2020-04-20\\\",\\\"2020-04-21\\\",\\\"2020-04-22\\\",\\\"2020-04-23\\\",][this.x] + \\\"<\/b> is <b>\\\" + this.y + \\\"<\/b> \\\"; })",
    "shadow" : true,
    "crosshairs" : true,
    "shared" : true,
    "enabled" : false,
    "animation" : true
  },
  "xAxis" : {
    "labels" : {
      "style" : {

      },
      "useHTML" : false,
      "formatter" : "(function () { return [\\\"2020-03-23\\\",\\\"2020-03-24\\\",\\\"2020-03-25\\\",\\\"2020-03-26\\\",\\\"2020-03-27\\\",\\\"2020-03-30\\\",\\\"2020-03-31\\\",\\\"2020-04-01\\\",\\\"2020-04-02\\\",\\\"2020-04-03\\\",\\\"2020-04-07\\\",\\\"2020-04-08\\\",\\\"2020-04-09\\\",\\\"2020-04-10\\\",\\\"2020-04-13\\\",\\\"2020-04-14\\\",\\\"2020-04-15\\\",\\\"2020-04-16\\\",\\\"2020-04-17\\\",\\\"2020-04-20\\\",\\\"2020-04-21\\\",\\\"2020-04-22\\\",\\\"2020-04-23\\\",][this.value]; })",
      "enabled" : true
    },
    "reversed" : false,
    "tickLength" : 0,
    "startOnTick" : false,
    "opposite" : false,
    "crosshair" : {
      "width" : 1,
      "color" : "#A9A9A9"
    },
    "endOnTick" : false,
    "gridLineWidth" : 0,
    "tickmarkPlacement" : "on",
    "tickInterval" : 22,
    "visible" : true
  },
  "plotOptions" : {
    "series" : {
      "states" : {
        "inactive" : {
          "enabled" : false
        }
      },
      "connectNulls" : false,
      "stacking" : "",
      "marker" : {
        "radius" : 0,
        "enabled" : true
      },
      "animation" : {
        "easing" : 13,
        "duration" : 100
      },
      "dataLabels" : {
        "softConnector" : true,
        "useHTML" : false,
        "allowOverlap" : false,
        "crop" : false,
        "enabled" : false,
        "inside" : false
      }
    }
  },
  "series" : [
    {
      "states" : {
        "hover" : {
          "enabled" : true,
          "lineWidthPlus" : 0
        }
      },
      "marker" : {
        "enabled" : false
      },
      "lineWidth" : 1.8,
      "zIndex" : 10,
      "borderWidth" : 1.2,
      "data" : [
        0,
        1.48,
        4.9000000000000004,
        3.1899999999999999,
        1.01,
        -1.6299999999999999,
        -2.1800000000000002,
        -1.24,
        3.5,
        1.79,
        5.21,
        5.1299999999999999,
        5.21,
        1.71,
        -0.46999999999999997,
        3.0299999999999998,
        3.4199999999999999,
        4.5800000000000001,
        6.2199999999999998,
        7.1500000000000004,
        6.3700000000000001,
        6.4500000000000002,
        5.0499999999999998
      ],
      "color" : "#0062FF",
      "showInLegend" : true,
      "allowPointSelect" : false,
      "visible" : true
    },
    {
      "states" : {
        "hover" : {
          "enabled" : true,
          "lineWidthPlus" : 0
        }
      },
      "marker" : {
        "enabled" : false
      },
      "lineWidth" : 1.2,
      "name" : "沪深300：",
      "borderWidth" : 1.2,
      "data" : [
        0,
        2.6899999999999999,
        5.4400000000000004,
        4.75,
        5.0899999999999999,
        4.0700000000000003,
        4.4100000000000001,
        4.0999999999999996,
        5.7800000000000002,
        5.1799999999999997,
        7.5800000000000001,
        7.0800000000000001,
        7.4400000000000004,
        6.7699999999999996,
        6.3200000000000003,
        8.3699999999999992,
        7.5599999999999996,
        7.71,
        8.7599999999999998,
        9.1500000000000004,
        7.8700000000000001,
        8.75,
        8.4800000000000004
      ],
      "color" : "#FF5B02",
      "showInLegend" : true,
      "allowPointSelect" : false,
      "visible" : true
    }
  ],
  "title" : {
    "useHTML" : false,
    "text" : ""
  },
  "colors" : [
    "#0062FF",
    "#FF5B02",
    "#06caf4",
    "#7dffc0"
  ],
  "yAxis" : {
    "labels" : {
      "useHTML" : false,
      "enabled" : true,
      "format" : "{value:.2f}%"
    },
    "reversed" : false,
    "title" : {
      "text" : ""
    },
    "startOnTick" : true,
    "max" : 9.1500000000000004,
    "allowDecimals" : true,
    "opposite" : false,
    "min" : -2.1800000000000002,
    "endOnTick" : true,
    "gridLineDashStyle" : "ShortDot",
    "tickPositions" : [
      -3,
      0,
      3,
      6,
      9,
      12
    ],
    "visible" : true
  },
  "legend" : {
    "enabled" : false,
    "floating" : false
  }
}

**Comment by AAChartModel** [comment]
我测试了一下,确实会出现这个断开的 bug,但是不是每次必现的, 有点蛋疼了

**Comment by AAChartModel** [comment]
我试了一下

```js
{
                "states" : {
                  "hover" : {
                    "enabled" : true,
                    "lineWidthPlus" : 5
                  }
                },
```

不把`lineWidthPlus` 设置为 0 就基本复现不了这个问题

**Comment by AAChartModel** [comment]
```js
 "tooltip" : {
    "useHTML" : true,
    "followTouchMove" : true,
    "formatter" : "(function () { return \\\"The value for <b>\\\" + [\\\"2020-03-23\\\",\\\"2020-03-24\\\",\\\"2020-03-25\\\",\\\"2020-03-26\\\",\\\"2020-03-27\\\",\\\"2020-03-30\\\",\\\"2020-03-31\\\",\\\"2020-04-01\\\",\\\"2020-04-02\\\",\\\"2020-04-03\\\",\\\"2020-04-07\\\",\\\"2020-04-08\\\",\\\"2020-04-09\\\",\\\"2020-04-10\\\",\\\"2020-04-13\\\",\\\"2020-04-14\\\",\\\"2020-04-15\\\",\\\"2020-04-16\\\",\\\"2020-04-17\\\",\\\"2020-04-20\\\",\\\"2020-04-21\\\",\\\"2020-04-22\\\",\\\"2020-04-23\\\",][this.x] + \\\"<\/b> is <b>\\\" + this.y + \\\"<\/b> \\\"; })",
    "shadow" : true,
    "crosshairs" : true,
    "shared" : true,
    "enabled" : false,
    "animation" : true
  },
```

另外, 你这里的 tooltip 的 enabled 属性既然为 false 了,那么你 tooltip 的 formatter 等其他属性的设置其实完全就是多余的了

**Comment by NashAnd** [comment]
enen。我试了"lineWidthPlus" : 0.1 可以。
