### ISSUE TITLE
更新后AALineStyle不见了

### ISSUE THREAD

**Issue by Candz** [AAChartModel/AAChartKit#1071]
手动加入这个文件后
.yAxisGridLineWidthSet(@0)//y轴横向分割线宽度为0(即是隐藏分割线)
这行报错
Called object type 'AALineStyle *' is not a function or function pointer

**Comment by AAChartModel** [comment]
什么叫 `AALineStyle不见了`, 你更新前你的项目中的 AAChartKit 有 AALineStyle 文件?

**Comment by ManBuTianYa** [comment]
pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git', :tag => '5.0.4'
你指定一下tag
