### ISSUE TITLE
如何固定y轴刻度

### ISSUE THREAD

**Issue by alexiiio** [AAChartModel/AAChartKit#1072]
比如我用柱状图设置y轴刻度（0 - 30 - 60 - 90 - 120），想让这几个刻度值一直显示，既比例固定。但图表会自动缩放，在一组数据最大值较小（比如 58）时，y轴设定的刻度不能完全显示。请问能否固定显示y轴刻度？

**Comment by AAChartModel** [comment]
```objc
//自定义 y 轴坐标（如：[@(0), @(25), @(50), @(75) , (100)]）
AAPropStatementAndPropSetFuncStatement(strong, AAChartModel, NSArray  *, yAxisTickPositions)
```

**Comment by AAChartModel** [comment]
```objc
AAPropStatementAndPropSetFuncStatement(strong, AAChartModel, NSNumber *, yAxisMax) //y 轴最大值
AAPropStatementAndPropSetFuncStatement(strong, AAChartModel, NSNumber *, yAxisMin) //y 轴最小值（设置为0就不会有负数）
```
然后再设置 Y 轴的最大值和最小值, 这样子将 Y轴的最大值和最小值固定住,应该就不会自动缩放了.

**Comment by alexiiio** [comment]
> ```objc
> ```objc
> AAPropStatementAndPropSetFuncStatement(strong, AAChartModel, NSNumber *, yAxisMax) //y 轴最大值
> AAPropStatementAndPropSetFuncStatement(strong, AAChartModel, NSNumber *, yAxisMin) //y 轴最小值（设置为0就不会有负数）
> ```
> 
> 
> 然后再设置 Y 轴的最大值和最小值, 这样子将 Y轴的最大值和最小值固定住,应该就不会自动缩放了.
> ```

确实可以，感谢！
