### ISSUE TITLE
如何隐藏或修改选中效果？

### ISSUE THREAD

**Issue by alexiiio** [AAChartModel/AAChartKit#1075]
选中一条数据时，会显示一个灰色的背景，请问这个背景能改变或隐藏掉吗？

![](https://raw.githubusercontent.com/alexiiio/LD-Notes/master/pics/IMG_4DCCB7A27E81-1.jpeg)

**Comment by AAChartModel** [comment]
这个是  crosshair(十字准星线), 调整AAChartModel 的 crosshair 属性即可.

**Comment by alexiiio** [comment]
> 这个是图表的 crosshair(十字准星线), 调整AAChartModel 的 crosshair 属性即可.

```
            .xAxisCrosshairSet([AACrosshair crosshairWithColor:[AAColor clearColor]])
```
这样写可以隐藏，谢谢！

**Comment by AAChartModel** [comment]
```objc
    .xAxisCrosshairSet([AACrosshair crosshairWithWidth:@0])

```

我觉得这样可能更好一点,  设置宽度为 0, Highcharts 内部应该就不会绘制这条线了, 你的这种可能还会绘制一条透明色的线. 所以说, 从洁癖的角度讲,可能设置宽度为 0 更好些🤣

**Comment by alexiiio** [comment]
> ```objc
> ```objc
>     .xAxisCrosshairSet([AACrosshair crosshairWithWidth:@0])
> ```
> 
> 
> 我觉得这样可能更好一点,  设置宽度为 0, Highcharts 内部应该就不会绘制这条线了, 你的这种可能还会绘制一条透明色的线. 所以说, 从洁癖的角度讲,可能设置宽度为 0 更好些🤣
> ```

我原本也是这么想的，但是设置宽度为0实际还是会有背景，估计内部做了判断，然后就用的clearColor可以实现隐藏效果。

**Comment by AAChartModel** [comment]
> 但是设置宽度为0实际还是会有背景，

我查了一下, 对于设置了 categories 的分类轴而言, 确实设置准星线的宽度为 0 时, 默认还是会有准星线显示.  

对于未设置 categories的非分类轴而言, 设置准星线的宽度为 0 ,则确实有效.

有兴趣可以使用以下 json 数据在线验证一下

```js
Highcharts.chart('container', {
	xAxis: {
		categories : [
			"Java",
			"Swift",
			"Python",
			"Ruby",
			"PHP",
			"Go",
			"C",
			"C#",
			"C++",
			"Perl",
			"R",
			"MATLAB",
			"SQL"
		],
		crosshair: {
			width: 0,
			color: 'green'
		}
	},
	yAxis: {
		crosshair: {
			width: 3,
			color: 'green'
		}
	},
	series: [{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
	}]
});

```

注释掉 categories 字段内容, 则 width 为 0 就会起作用.

在线链接: https://api.highcharts.com.cn/highcharts#xAxis.crosshair.width
