### ISSUE TITLE
toolTip的"气泡尖" 有时出现, 有时候不出现,位置已经在中部,是否有个什么值控制它的出现?

### ISSUE THREAD

**Issue by silendir** [AAChartModel/AAChartKit#1077]
![image](https://user-images.githubusercontent.com/11792633/99950913-3f0d4a00-2db8-11eb-8eee-7bd3342eafd1.jpeg)

**Comment by AAChartModel** [comment]
如果你的 tooltip 的共享属性 share 为 true 的话, 气泡尖就不会出现

**Comment by AAChartModel** [comment]
https://api.highcharts.com.cn/highcharts#tooltip.shared

**Comment by AAChartModel** [comment]
而且这个值的 true 或 false 会影响到 formatter 的取值逻辑, 相关内容参见 https://api.highcharts.com.cn/highcharts#tooltip.formatter

**Comment by AAChartModel** [comment]
> 是否有个什么值控制它的出现?

数据点提示框的形状名称 https://api.highcharts.com.cn/highcharts#tooltip.shape

**Comment by silendir** [comment]
感谢!很有用

**Comment by silendir** [comment]
不知道是不是位置的问题, 在曲线上设置.sharedSet(YES)没有生效, 是不是需要多个图表才能去尖尖

**Comment by silendir** [comment]
只有同一个图表里面有复数个曲线的... 开了才有效
