### ISSUE TITLE
大神，折线图点击其中一条折线，另一条折线颜色变浅了，怎么设置颜色不变呀

### ISSUE THREAD

**Issue by NashAnd** [AAChartModel/AAChartKit#1078]
![491606183811_ pic_hd](https://user-images.githubusercontent.com/14804016/100037747-bb963c00-2e3d-11eb-9802-7058d43a9d1b.jpg)

**Comment by AAChartModel** [comment]
重复问题, 参见 https://github.com/AAChartModel/AAChartKit/issues/949

**Comment by NashAnd** [comment]
大神给力呀，回复真快
