### ISSUE TITLE
在iPhone X中图例不显示。

### ISSUE THREAD

**Issue by wangzixilaile** [AAChartModel/AAChartKit#108]
在iPhone X中每个图的图例都不显示，刚开始以为是被挡住，因为Hierarchy中看是被挡到了，但是不管AAChartView设置多么的小还是不显示，在真机上测也不显示，swift版的也是同样的问题，只有在iPhone X中是不显示的，其他机型没问题。还望解决下。
![jietu20180110-151637](https://user-images.githubusercontent.com/17853963/34760134-82055bba-f619-11e7-8356-4f63f48d1670.jpg)
![1b6466dab7e1703ac5679080ef977fdc](https://user-images.githubusercontent.com/17853963/34760141-87881578-f619-11e7-9089-9502261b2ec8.jpg)

**Comment by AAChartModel** [comment]
嗯,确实没有仔细地注意 iPhone X相关的问题,做好iPhone X 的适配工作,大概知道问题了,晚上回去处理一下.

**Comment by wangzixilaile** [comment]
为什么下载你的最新版集成过后还是不显示图例呢？你的demo里的倒是显示出来了。
![jietu20180115-102409](https://user-images.githubusercontent.com/17853963/34924517-ca01ea46-f9de-11e7-8546-1bf324393930.jpg)

**Comment by AAChartModel** [comment]
注意不要将 AAChartView 作为第一个添加到控制器上的 view, 这样好像就会有问题

**Comment by AAChartModel** [comment]
```objective-c
- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.backgroundColor = [UIColor whiteColor];
    
    [self configureTheSegmentedControls];//添加 SegmentedControls
    [self configureTheSwitchs];//再添加 Switchs
    
    AAChartType chartType;
    switch (self.chartType) {
        case 0:
            chartType = AAChartTypeColumn;
            break;
        case 1:
            chartType = AAChartTypeBar;
            break;
        case 2:
            chartType = AAChartTypeArea;
            break;
        case 3:
            chartType = AAChartTypeAreaspline;
            break;
        case 4:
            chartType = AAChartTypeLine;
            break;
        case 5:
            chartType = AAChartTypeSpline;
            break;
        case 6:
            chartType = AAChartTypeScatter;
            break;
        default:
            break;
    }
    
    self.title = [NSString stringWithFormat:@"%@ chart",chartType];
    
    [self configTheChartView:chartType];//最后配置 AAChartView
    
}
```

你看我的代码都是最后再添加的 AAChartView

**Comment by AAChartModel** [comment]
你确定你已经更新了我的代码,最新的里面修改了 AAChartView 里面的 contentHeight 的一点点内容,添加了设备型号为 iPhone X 时更改 contentHeight的判断.

**Comment by wangzixilaile** [comment]
确定更新了，我把DerivedData里的东西都删除了，也反复添加了好多遍也都是一样的，我在AAChartView下面先添加了一个红色的view，再把AAChartView添加在红色的view上，大小设置的和红色的view一样，但是看起来像是被挡起来了，而且你的图例怎么和上面是分开的。
![jietu20180115-124214](https://user-images.githubusercontent.com/17853963/34927611-66e72fac-f9f2-11e7-9224-48bd0c46206c.jpg)

**Comment by wangzixilaile** [comment]
这个是柱状图，貌似只能出来一点点，曲线图一点点都显示不出来
![jietu20180115-130142](https://user-images.githubusercontent.com/17853963/34927898-b349207e-f9f4-11e7-9d3e-56bffbea3285.jpg)

**Comment by AAChartModel** [comment]
> 18256973864@163.com

这是我的邮箱地址，麻烦发送一份你的有问题的demo，我回去查看一下问题到底出在什么地方
