### ISSUE TITLE
我还有个憨憨问题，一直没找到点击柱状图的时候，弹出的弹框事件，可以自定义弹框吗

### ISSUE THREAD

**Issue by Laughing1206** [AAChartModel/AAChartKit#1080]
我还有个憨憨问题，一直没找到点击柱状图的时候，弹出的弹框事件，可以自定义弹框吗

**Comment by AAChartModel** [comment]
浮动提示框的自定义是通过 AATooltip 来实现的,具体内容参见 AAChartKit 的  示例demo
