### ISSUE TITLE
怎么设置柱形图的宽度

### ISSUE THREAD

**Issue by Laughing1206** [AAChartModel/AAChartKit#1081]
怎么设置柱形图的宽度

**Comment by Laughing1206** [comment]
还有就是怎么将第一个柱子往后移移，因为下面X轴第一个title显示不全

**Comment by Laughing1206** [comment]
还有就是怎么取消动画

**Comment by Laughing1206** [comment]
兄弟，急求解决方案

**Comment by AAChartModel** [comment]
> 怎么设置柱形图的宽度

重复问题, 参见 #537

**Comment by AAChartModel** [comment]
> 还有就是怎么取消动画

重复问题,参见 #1030

**Comment by AAChartModel** [comment]
> 还有就是怎么将第一个柱子往后移移，因为下面X轴第一个title显示不全

重复问题, 参见 https://github.com/AAChartModel/AAChartKit/issues/1074
