### ISSUE TITLE
AATooltip有的需要带valueSuffix，有的不需要，怎么处理

### ISSUE THREAD

**Issue by Laughing1206** [AAChartModel/AAChartKit#1082]
![切片](https://user-images.githubusercontent.com/11715852/100190502-56b81000-2f29-11eb-8c3a-87d17d6e4fe0.png)
累计事故是数量，不需要%，
增长率需要，怎么分开处理啊

**Comment by AAChartModel** [comment]
这个需要你自己在 AATooltip 的 formatter 属性中自己做逻辑判断, 参考 https://github.com/AAChartModel/AAChartKit/issues/651

demo 中有此问题的示例.
