### ISSUE TITLE
AAChartView放在tableView里面，每次滑动出入屏幕，AAChartView就会明显的刷新，怎么处理

### ISSUE THREAD

**Issue by Laughing1206** [AAChartModel/AAChartKit#1085]
AAChartView放在tableView里面，每次滑动出入屏幕，AAChartView就会明显的刷新，怎么处理

**Comment by AAChartModel** [comment]
禁用绘制图表的动画效果就可以了

**Comment by Laughing1206** [comment]
能加下QQ吗，禁了动画，我发现也不行啊

**Comment by Laughing1206** [comment]
1119027716

**Comment by AAChartModel** [comment]
那你就设置 tableView 的 cell 不要重用

**Comment by Laughing1206** [comment]
没放在cell里，在header上

**Comment by AAChartModel** [comment]
如果还不行的话,那就说明是 WKWebView 本身的特性决定的, AAChartView 继承自 WKWebView, 而WKWebView是重型控件,同一个列表上太多WKWebView, 性能肯定不会好到哪里去
