### ISSUE TITLE
AAChartView放在tableView里面，每次滑动出入屏幕，AAChartView就会明显的刷新，怎么处理，禁了动画也不行，会有个闪的过程

### ISSUE THREAD

**Issue by Laughing1206** [AAChartModel/AAChartKit#1086]
AAChartView放在tableView里面，每次滑动出入屏幕，AAChartView就会明显的刷新，怎么处理，禁了动画也不行，会有个闪的过程

可以加QQ吗
1119027716
急需帮助

**Comment by silendir** [comment]
_aaChartView1.isClearBackgroundColor = YES; //最有效的解决办法

**Comment by Laughing1206** [comment]
<img width="329" alt="图片" src="https://user-images.githubusercontent.com/11715852/100343329-2f8d3b80-301a-11eb-8920-62d2fc918eb1.png">
![BA4F7436-6F4C-4F20-BAA5-C2C2833D0D46](https://user-images.githubusercontent.com/11715852/100343352-35831c80-301a-11eb-924d-0867232ce7bc.png)

这块区域有最小限制吗，为什么字数一多，就显示不全了

**Comment by Laughing1206** [comment]
https://www.jianshu.com/p/2ecdbf854424
这块区域有最小限制吗，为什么字数一多，就显示不全了【图片在这个链接上】

**Comment by Laughing1206** [comment]
还有就是折线支持虚线吗

**Comment by Laughing1206** [comment]
tooltip能改成透明的吗
