### ISSUE TITLE
可否关闭图形选中时的高光效果?

### ISSUE THREAD

**Issue by silendir** [AAChartModel/AAChartKit#1088]
![image](https://user-images.githubusercontent.com/11792633/100427294-345ef780-30cd-11eb-8fcb-aaf4aec38911.jpeg)

**Comment by silendir** [comment]
选中那条绿棍子会稍微白一点...能关闭这个效果么?

**Comment by AAChartModel** [comment]
How to disable series highlighting? - Highcharts official 

 https://www.highcharts.com/forum/viewtopic.php?t=8541

试试这个官方问答的解决方案

**Comment by silendir** [comment]
试试

**Comment by silendir** [comment]
![image](https://user-images.githubusercontent.com/11792633/100564293-9604a900-32fb-11eb-814e-5e8163e0ee6d.jpeg)
不知道为什么崩了
