### ISSUE TITLE
柱状图能绘制成这样吗

### ISSUE THREAD

**Issue by Laughing1206** [AAChartModel/AAChartKit#1090]
<img width="227" alt="图片" src="https://user-images.githubusercontent.com/11715852/100445593-50bc5d80-30e8-11eb-8527-32b4c5072e4b.png">

柱状图能绘制成这样吗

**Comment by Laughing1206** [comment]
不能吗

**Comment by AAChartModel** [comment]
恐怕不行,没找到 Highcharts 设置修改柱状图的长条纹理样式的功能
