### ISSUE TITLE
xib支持

### ISSUE THREAD

**Issue by zj381652512** [AAChartModel/AAChartKit#1092]
```objc
- (instancetype)initWithCoder:(NSCoder *)coder {
    self = [super initWithCoder:coder];
    if (self) {
        self.configuration.userContentController = [[WKUserContentController alloc] init];
        self.UIDelegate = self;
        self.navigationDelegate = self;
        self.backgroundColor = [UIColor whiteColor];
    }
    return self;
}
```

**Comment by zj381652512** [comment]
xib中添加图表,暂时没发现有什么问题

**Comment by kite424** [comment]
你好，在xib如何具体使用呢？

**Comment by zj381652512** [comment]
> 你好，在xib如何具体使用呢？
AAChartView是WKWebView子类,往xib容器视图中拉一个WKWebView,将Class改为AAChartView

**Comment by zj381652512** [comment]
> 你好，在xib如何具体使用呢？
AAChartView是WKWebView子类,往xib容器视图中拉一个WKWebView,将Class改为AAChartView, 将xib的AAChartView连线到类扩展, 结果如下:

@interface ChartCell ()
@property (weak, nonatomic) IBOutlet DashView *dashView;
**@property (weak, nonatomic) IBOutlet AAChartView *chartView;**
@end
