### ISSUE TITLE
为什么数据为0的时候，折线没有链接，而是只显示了两个点 

### ISSUE THREAD

**Issue by Laughing1206** [AAChartModel/AAChartKit#1094]
<img width="420" alt="图片" src="https://user-images.githubusercontent.com/11715852/100816131-67640b00-3480-11eb-8553-a1050a1e363e.png">

**Comment by Laughing1206** [comment]
<img width="601" alt="图片" src="https://user-images.githubusercontent.com/11715852/100820554-6daab500-3489-11eb-94a7-0e9c9ff1d602.png">
这个属性已经设置了，但是没起作用

**Comment by Laughing1206** [comment]
<img width="601" alt="图片" src="https://user-images.githubusercontent.com/11715852/100820599-7e5b2b00-3489-11eb-968f-ef2ad518dc8a.png">

**Comment by Laughing1206** [comment]
![AE8CF3B4-B992-4838-BF39-F870B16F88BB](https://user-images.githubusercontent.com/11715852/100820696-bb272200-3489-11eb-9c5a-2d6c269fd89b.png)

**Comment by AAChartModel** [comment]
这个有可能是 Highcharts 的 bug, 你设置了线条的颜色为渐变色?

**Comment by Laughing1206** [comment]
我发现了，只要是数据一样的话，例如折线数据[@1, @1, @1, @1, @1...]
它都不连接，只显示点

**Comment by Laughing1206** [comment]
<img width="278" alt="图片" src="https://user-images.githubusercontent.com/11715852/100827445-aea9c600-3497-11eb-8088-eb02bca97b0f.png">

**Comment by Laughing1206** [comment]
只有数据不一样的时候，才会画线，怎么办

**Comment by Laughing1206** [comment]
解决了，是渐变问题，纯色是可以的
