### ISSUE TITLE
标题如何左对齐?(不是副标题)

### ISSUE THREAD

**Issue by xiyupingxuan** [AAChartModel/AAChartKit#1095]
问题如图
标题文字如何左对齐呢
还有.seriesSet.nameSet 如何隐藏 ,传(null) 会显示默认, 传@""空字符串也会显示一个和柱状颜色相同的圆点
[https://spacetime-app.oss-cn-hangzhou.aliyuncs.com/photo/37720446ca6b4e9fbcd7d4468be80170.png](url)

**Comment by xiyupingxuan** [comment]
> 问题如图
> 标题文字如何左对齐呢
> 还有.seriesSet.nameSet 如何隐藏 ,传(null) 会显示默认, 传@""空字符串也会显示一个和柱状颜色相同的圆点
> [https://spacetime-app.oss-cn-hangzhou.aliyuncs.com/photo/37720446ca6b4e9fbcd7d4468be80170.png](url)



> 问题如图
> 标题文字如何左对齐呢
> 还有.seriesSet.nameSet 如何隐藏 ,传(null) 会显示默认, 传@""空字符串也会显示一个和柱状颜色相同的圆点
不知道为什么贴不上图

**Comment by xiyupingxuan** [comment]
不知为什么贴不上图
 图片地址 https://spacetime-app.oss-cn-hangzhou.aliyuncs.com/photo/37720446ca6b4e9fbcd7d4468be80170.png  
辛苦作者

**Comment by AAChartModel** [comment]
![]( https://spacetime-app.oss-cn-hangzhou.aliyuncs.com/photo/37720446ca6b4e9fbcd7d4468be80170.png)

改成 markdown 格式的图片链接就可以了, 就像下面这样

`![]( https://spacetime-app.oss-cn-hangzhou.aliyuncs.com/photo/37720446ca6b4e9fbcd7d4468be80170.png)`

**Comment by xiyupingxuan** [comment]
> ![](https://camo.githubusercontent.com/ce0facdd2772a01d2bfcf7417ec394bfc15afc23881433c90d70c06ebd26dcf2/68747470733a2f2f737061636574696d652d6170702e6f73732d636e2d68616e677a686f752e616c6979756e63732e636f6d2f70686f746f2f33373732303434366361366234653966626364376434343638626538303137302e706e67)
> 
> 改成 markdown 格式的图片链接就可以了, 就像下面这样
> 
> `![]( https://spacetime-app.oss-cn-hangzhou.aliyuncs.com/photo/37720446ca6b4e9fbcd7d4468be80170.png)`

标题文字如何左对齐呢
还有.seriesSet.nameSet 如何隐藏 ,传(null) 会显示默认, 传@""空字符串也会显示一个和柱状颜色相同的圆点

**Comment by AAChartModel** [comment]
如何隐藏图表的图例 , 参见: #399

**Comment by xiyupingxuan** [comment]
![]( https://spacetime-app.oss-cn-hangzhou.aliyuncs.com/photo/4822c8a116d4422eb5a3da66d8bef79c.png)
> 感谢作者
还有一个问题 支持不支持数据在柱状图上面显示呢

**Comment by xiyupingxuan** [comment]
>
![]( https://spacetime-app.oss-cn-hangzhou.aliyuncs.com/photo/4822c8a116d4422eb5a3da66d8bef79c.png)


 感谢作者
还有一个问题 支持不支持数据在柱状图上面显示呢

**Comment by xiyupingxuan** [comment]
![]( https://spacetime-app.oss-cn-hangzhou.aliyuncs.com/photo/4822c8a116d4422eb5a3da66d8bef79c.png)
这样显示是否支持呢

**Comment by AAChartModel** [comment]
实现柱状图部分圆角的功能, 参见 https://github.com/AAChartModel/AAChartKit/issues/842

**Comment by xiyupingxuan** [comment]
感谢作者百忙之中答疑,
我指的是数据,直接显示在柱状图 顶部这种, 是否支持呢

**Comment by AAChartModel** [comment]
参考 AATitle 属性

```objc
@interface AATitle : NSObject

AAPropStatementAndPropSetFuncStatement(copy,   AATitle, NSString *, text) 
AAPropStatementAndPropSetFuncStatement(strong, AATitle, AAStyle  *, style) 
AAPropStatementAndPropSetFuncStatement(copy,   AATitle, NSString *, align)
AAPropStatementAndPropSetFuncStatement(copy,   AATitle, NSString *, verticalAlign)
AAPropStatementAndPropSetFuncStatement(strong, AATitle, NSNumber *, x)//标题相对于水平对齐的偏移量，取值范围为：图表左边距到图表右边距，可以是负值，单位px。 默认是：0.
AAPropStatementAndPropSetFuncStatement(strong, AATitle, NSNumber *, y) //标题相对于垂直对齐的偏移量，取值范围：图表的上边距（chart.spacingTop ）到图表的下边距（chart.spacingBottom），可以是负值，单位是px。默认值和字体大小有关。
AAPropStatementAndPropSetFuncStatement(assign, AATitle, BOOL          , useHTML) //是否 使用HTML渲染标题。 默认是：false.

@end
```

设置`align`属性为 `AAChartAlignTypeLeft`即可实现左对齐

关于 `AAChartAlignType` 枚举类型, 可选的有以下三种

```objc
typedef NSString *AAChartAlignType;

AACHARTKIT_EXTERN AAChartAlignType const AAChartAlignTypeLeft; //左对齐
AACHARTKIT_EXTERN AAChartAlignType const AAChartAlignTypeCenter; //居中对齐
AACHARTKIT_EXTERN AAChartAlignType const AAChartAlignTypeRight; //右对齐
```

**Comment by AAChartModel** [comment]
参考 `AAChartModel` 的 `dataLabelsEnabled`属性

```objc
AAPropStatementAndPropSetFuncStatement(assign, AAChartModel, BOOL,       dataLabelsEnabled) //是否显示数据,默认为否
```

设置 `dataLabelsEnabled` 为 `true` 即显示数据标签(数据标签默认在柱状图顶部)

**Comment by xiyupingxuan** [comment]
![]( https://spacetime-app.oss-cn-hangzhou.aliyuncs.com/photo/c3052bfda058498f9e8894eb105ef2f2.png) 
这是这样最高的那条柱状的数据就会在柱状内部.这个有什么思路可以解决吗

**Comment by AAChartModel** [comment]
那是因为你的图表的顶部空间不够用于显示 DataLabels 数据标签了, 你把 Y轴的最大值设置的比你的 data 数组中的最大值再大些就可以了.

**Comment by AAChartModel** [comment]
使用 AADataLabels 的属性`y`来处理此问题吧,更合理一些

```objc
AAPropStatementAndPropSetFuncStatement(strong, AADataLabels, NSNumber *, y) //数据标签的竖直偏移。 默认是：-6.
``

参见 https://api.highcharts.com.cn/highcharts#plotOptions.series.dataLabels.y

**Comment by AAChartModel** [comment]
https://jshare.com.cn/highcharts/eSNmQc/4

修改此处的在线示例代码为

```js
Highcharts.chart('container', {
	xAxis: {
		categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
	},
	plotOptions: {
		series: {
			dataLabels: {
				enabled: true,
				y: -10
			}
		}
	},
	series: [{
		type : 'column',
		data: [29.9, 71.5, 1106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
	}]
});

``` 

绘图结果

![image](https://user-images.githubusercontent.com/16357599/100833954-ec155000-34a5-11eb-900d-8a8cd5e32c75.png)

由上可知, 在 AAChartKit 中, 设置 AADataLabels 的属性 y 为 `@-10` 差不多就能满足你的需求了

**Comment by xiyupingxuan** [comment]
诚挚感谢!
问题已解决,
