### ISSUE TITLE
设置tooltipEnabled为NO后，滑动准星线同时选中多个折线。请问怎么设置？

### ISSUE THREAD

**Issue by DevZMJ** [AAChartModel/AAChartKit#1097]
![IMG_0461](https://user-images.githubusercontent.com/12655415/100865315-21d02e00-34d2-11eb-85d6-cc42b489b997.PNG)
问题如图

**Comment by AAChartModel** [comment]
参考 https://github.com/AAChartModel/AAChartKit/issues/949

**Comment by DevZMJ** [comment]
是否可在此状态下设置各曲线与准星线相交的点都高亮？
