### ISSUE TITLE
不好意思，想问下，折线图的多条路径能否反向生成，就是第一项指标对应的路径在最上边，然后第二项在下边，依次类推，我的意思是能否自由设置添加路径的顺序

### ISSUE THREAD

**Issue by ZFKK** [AAChartModel/AAChartKit#11]

**Comment by AAChartModel** [comment]
给个设计的效果图呗,你这样的描述让我很难明白你实际的具体需求呀!

**Comment by ZFKK** [comment]
![img_2070](https://cloud.githubusercontent.com/assets/16482997/25598548/3b971c8c-2f08-11e7-95ec-994334b3aea5.PNG)
![img_2069](https://cloud.githubusercontent.com/assets/16482997/25598551/409c1c14-2f08-11e7-8b1c-314f16ac122e.PNG)
实际要求的曲线顺序是2069，而现在的是2070的，现在需要的就是更改顺序

**Comment by ZFKK** [comment]
补充一下，2069指的是第二张图，也就是现在需要的，而现在的效果是第一张图，也就是2070

**Comment by AAChartModel** [comment]
我大概明白你的需求了, 你如果想要改变某一个颜色的图层的层次,其实只要调整 AAChartModel的属性series的数组中的数组的先后顺序就可以了.
`   self.chartModel= AAObject(AAChartModel)
    .chartTypeSet(chartType)
    .titleSet(@"编程语言热度")
    .subtitleSet(@"虚拟数据")
    .categoriesSet(@[@"Java",@"Swift",@"Python",@"Ruby", @"PHP",@"Go",@"C",@"C#",@"C++"])
    .yAxisTitleSet(@"摄氏度")
    .pointHollowSet(true)
    .seriesSet(@[
                 AAObject(AASeriesElement)
                 .nameSet(@"2018")
                 .dataSet(@[@45,@56,@34,@43,@65,@56,@47,@28,@49]),
                 
                  AAObject(AASeriesElement)
                 .nameSet(@"2019")
                 .dataSet(@[@31,@22,@33,@54,@35,@36,@27,@38,@39]),
                 
                 AAObject(AASeriesElement)
                 .nameSet(@"2020")
                 .dataSet(@[@21,@22,@19,@24,@33,@26,@18,@28,@33]),
                 ]
               )
    ;`
比如你这样配置 AAChartModel , 渲染的图表如下图所示
![36aadcac-db21-460d-8dea-280b460d8f8a](https://cloud.githubusercontent.com/assets/16357599/25601944/5fc42f18-2f22-11e7-953e-9985da0f19b8.png)

你再调整AAChartModel 的series 属性(数组)的先后顺序为 
` .seriesSet(@[
                 AAObject(AASeriesElement)
                 .nameSet(@"2020")
                 .dataSet(@[@21,@22,@19,@24,@33,@26,@18,@28,@33]),
           
                 
                  AAObject(AASeriesElement)
                 .nameSet(@"2019")
                 .dataSet(@[@31,@22,@33,@54,@35,@36,@27,@38,@39]),
                 
                 AAObject(AASeriesElement)
                 .nameSet(@"2018")
                 .dataSet(@[@45,@56,@34,@43,@65,@56,@47,@28,@49]),
                 ]
               )
`这时候渲染的图形效果如下
![3dcd1a72-6e3d-4b5e-baca-5c2ba1cf7af5](https://cloud.githubusercontent.com/assets/16357599/25602011/e74bd990-2f22-11e7-8133-c172638ac3a4.png)
