### ISSUE TITLE
新版的图例还是不显示。

### ISSUE THREAD

**Issue by wangzixilaile** [AAChartModel/AAChartKit#110]
新版的图例，我集成后还是不显示，而且你的图例和图分开了，但我的却没有，是哪里代码需要重新设置吗？而且demo上的y轴好像也没有了。
![jietu20180115-113833](https://user-images.githubusercontent.com/17853963/34926265-166bf412-f9e9-11e7-880d-48dcc7f257e3.jpg)
![jietu20180115-113707](https://user-images.githubusercontent.com/17853963/34926266-16a82db0-f9e9-11e7-8805-d293fe98463a.jpg)

**Comment by AAChartModel** [comment]
> demo上的y轴好像也没有了

这个是因为我添加了`yAxisVisible` 布尔属性,你设置为 `true` 接可以显示 Y 轴了

**Comment by AAChartModel** [comment]
图例如果不能正常显示,你可以在创建 AAChartView 的时候,自己调整一下它的内容宽度,比如这样
```objective-c
aaChartView.contentHeight = aaChartView.frame.size.height-20;
```
应该就可以了
