### ISSUE TITLE
大佬，提示框的阴影怎么去掉啊？

### ISSUE THREAD

**Issue by QionglinFu1024** [AAChartModel/AAChartKit#1100]
![image](https://user-images.githubusercontent.com/26901908/101017453-169a0280-35a5-11eb-80bf-1dc37ee3de8d.png)

self.aaChartModel = AAChartModel.new
    .xAxisCrosshairColorSet(@"#44D7CA")
    .xAxisCrosshairDashStyleTypeSet(AAChartLineDashStyleTypeLongDash)
    .xAxisCrosshairWidthSet(@.5)
    .markerSymbolStyleSet(AAChartSymbolStyleTypeInnerBlank)// markerpoint为空心效果
    .markerSymbolSet(AAChartSymbolTypeCircle)// markerpoint为圆形点○
    .markerRadiusSet(@2.0)
    .chartTypeSet(AAChartTypeArea)
    .titleSet(@"")
    .subtitleSet(@"")
    .categoriesSet(tempArray)
    .xAxisTickIntervalSet(@5)
    .legendEnabledSet(NO)
    .seriesSet(@[
        AASeriesElement.new
        .statesSet(AAStates.new
                   .hoverSet(AAHover.new
                             .enabledSet(true)
                             .lineWidthPlusSet(@0)
                             ))
        .markerSet(AAMarker.new
                   .lineColorSet(@"#44D7CA")
                   .statesSet(AAMarkerStates.new
                              .hoverSet(AAMarkerHover.new
                                        .fillColorSet(@"#44D7CA")
                                        .radiusSet(@4)
                                        )))
        .nameSet(years)
        .lineWidthSet(@1)
        .colorSet(@"#44D7CA")
        .fillColorSet((id)gradientColorDic1)
        .dataSet(tempData),
    ]);
    [_aaChartView aa_drawChartWithChartModel:self.aaChartModel];

AAOptions *aaOptions = self.aaChartModel.aa_toAAOptions;
    aaOptions.plotOptions.series.animation = (id)@(false);
    aaOptions.xAxis
    .lineWidthSet(@0.5)
    .lineColorSet(@"#999999")
    .labels.style.colorSet(@"#999999")
    .fontSizeSet(@"9px");
    aaOptions.xAxis.labels.formatterSet(@AAJSFunc(function () {
        return this.value.replace("-","");
    }));
    aaOptions.yAxis
    .tickAmountSet(@6)
    .lineWidthSet(@0.5)//y轴线宽
    .lineColorSet(@"#999999")//y轴线颜色
    .gridLineWidthSet(@0.5)//Y轴网格线宽度
    .labels.style.colorSet(@"#999999")
    .fontSizeSet(@"9px");//Y轴文字颜色
    
    AATooltip *tooltip = aaOptions.tooltip;
    tooltip
    .useHTMLSet(true)
    .sharedSet(false)
    .formatterSet(@AAJSFunc((function () {

    })))
    .valueDecimalsSet(@2)//设置取值精确到小数点后几位
    .backgroundColorSet(@"#44D7CA")
    .borderColorSet(@"#44D7CA")
    .styleSet(AAStyleColorSize(@"#FFD700", 12));
    
    [self.aaChartView aa_refreshChartWithOptions:aaOptions];
没找到设置的代码，求指导

**Comment by AAChartModel** [comment]
AATooltip 有一个 shadow 属性

```objc
AAPropStatementAndPropSetFuncStatement(assign, AATooltip, BOOL,       shadow)
```

设置为 false 即可隐藏提示框阴影.
