### ISSUE TITLE
柱形图(横向)的宽度,受文字数量影响,请问是否能固定图表size,文字自动换行?(如下图)

### ISSUE THREAD

**Issue by zj381652512** [AAChartModel/AAChartKit#1101]
![IMG_1282](https://user-images.githubusercontent.com/17876394/101302346-56e3d400-3876-11eb-9bcc-1e30d5dd51c9.png)

**Comment by AAChartModel** [comment]
重复问题, 参考 https://github.com/AAChartModel/AAChartKit/issues/465
