### ISSUE TITLE
如何改y轴数据显示的格式和AADataElement的格式

### ISSUE THREAD

**Issue by bq767630631** [AAChartModel/AAChartKit#1104]
![1607498578004](https://user-images.githubusercontent.com/12812584/101598156-b25ac100-3a32-11eb-99c8-e629ea9370d4.jpg)

如图，192k 不用k 要显示‘192, 234’ 三位加一个逗号，  192 407 也是 变成192,407
该如何设置。哎，太累了啊

**Comment by AAChartModel** [comment]
```js
yAxis: [{
    	title: {
    	    	...
    	},
    	labels: {
        	....,
        	format: '{value:.,0f}'//就这个地方设置显示格式
    	}
}]
```

参考: https://api.highcharts.com.cn/highcharts#yAxis.labels.format

**Comment by AAChartModel** [comment]
> 要显示‘192, 234’ 三位加一个逗号， 192 407 也是 变成192,407

重复问题, 参考: https://github.com/AAChartModel/AAChartKit/issues/425
