### ISSUE TITLE
请问大佬怎么默认显示所有数据的选中线啊

### ISSUE THREAD

**Issue by Maxcucurbit** [AAChartModel/AAChartKit#1105]
例如这样的，默认每个数据点都显示一条线来标注这里有条数据
<img width="464" alt="QQ20201209-203430@2x" src="https://user-images.githubusercontent.com/11735014/101630691-35454100-3a5e-11eb-83f8-63e05f71b62a.png">

**Comment by AAChartModel** [comment]
重复问题, 参考 https://github.com/AAChartModel/AAChartKit/issues/633
