### ISSUE TITLE
数据很少，怎样让图从左加载，而不是居中

### ISSUE THREAD

**Issue by TinyMio** [AAChartModel/AAChartKit#1109]
柱形图只有一条或者很少数据，数据就居中显示，设置了宽度也没起作用，宽度好像根据数据多少自适应了，怎样让从左边显示，宽度固定

**Comment by AAChartModel** [comment]
你设置较多的 X 轴的 categories 试试.  比如 data 数组只有一个元素,但是categories的数组元素有十个

**Comment by TinyMio** [comment]
也不行，我设置了data有一个，好多个categories，但是还是显示一条数据，在中间，而且宽度也不是我设置的

**Comment by AAChartModel** [comment]
参考这个问题 https://github.com/AAChartModel/AAChartKit/issues/475

没有数据的地方,使用 NSNull 进行空白占位即可. AAChartKit 的 demo 中用示例.

**Comment by TinyMio** [comment]
好，我试试，多谢
