### ISSUE TITLE
功能很齐全很赞，首次加载的时候绘图比较慢，有没有什么优化的方法呀

### ISSUE THREAD

**Issue by FLYKingdom** [AAChartModel/AAChartKit#111]
加载webView的时候 会延迟几秒才能加载出来，暂时没有找到好的优化思路

**Comment by AAChartModel** [comment]
你是在模拟器上查看的吗?模拟器上确实在首次加载绘图时有少许延迟,真机上的速度还是比较可观的,相对来说体验仍然能够算得上令人满意.不过您的建议仍然十分可贵,后续可考虑优化(不知道是不是真的有可优化的可能😝😝😝).

**Comment by AAChartModel** [comment]
现已移除了对jQuery.js文件的依赖,同时大幅度缩减了其他js文件的体积大小,显著提升了AAChartView的加载速度,真机测试发现使用AAChartKit图表发现无任何肉眼可见的延迟现象.请及时更新最新版的AAChartKit.具体参见 #151  #153
