### ISSUE TITLE
折线数据与实际比例不符

### ISSUE THREAD

**Issue by jxdwinter** [AAChartModel/AAChartKit#1111]
<img width="478" alt="Screen Shot 2020-12-24 at 14 22 17" src="https://user-images.githubusercontent.com/1195524/103066244-722f3d00-45f3-11eb-8562-c001de8e5f3c.png">

请问大神线上点的位置与实际的比例不符合，请问是我哪里设置错了吗？
代码如下：

<img width="935" alt="Screen Shot 2020-12-24 at 14 55 02" src="https://user-images.githubusercontent.com/1195524/103068412-069b9e80-45f8-11eb-944c-bcf4daa5cb39.png">

**Comment by AAChartModel** [comment]
stacking 堆积样式属性设置有误 , 你把这一样代码删除然后使用默认的非堆积样式即可. 你试试

**Comment by jxdwinter** [comment]
> stacking 堆积样式属性设置有误 , 你把这一样代码删除然后使用默认的非堆积样式即可. 你试试

.stackingSet(AAChartStackingTypeFalse) 谢谢大神！
