### ISSUE TITLE
请问如何修改五边形和六边形的大小？

### ISSUE THREAD

**Issue by jxdwinter** [AAChartModel/AAChartKit#1114]
<img width="212" alt="Screen Shot 2020-12-28 at 14 34 56" src="https://user-images.githubusercontent.com/1195524/103194211-e0d50900-4919-11eb-9375-6e270f2eb385.png">

**Comment by AAChartModel** [comment]
通过修改 AAChartView 的宽高即可调整雷达图的大小

**Comment by AAChartModel** [comment]
另外 margin 属性对调整雷达图的大小也同样有作用.

参考 https://github.com/AAChartModel/AAChartKit/issues/776
