### ISSUE TITLE
大佬，饼状图能做圆角么，设计图是这样的

### ISSUE THREAD

**Issue by kenanwangyi** [AAChartModel/AAChartKit#1116]
![1609488608151](https://user-images.githubusercontent.com/15629705/103435620-3710b780-4c4c-11eb-8f0a-9fab1f251219.jpg)

**Comment by AAChartModel** [comment]
<img width="615" alt="截屏2022-08-29 下午7 01 12" src="https://user-images.githubusercontent.com/16357599/187187034-599e452e-8b7d-4c0f-ad39-004820a4652e.png">


参考 pro 版本中的活动图使用示例:

* https://github.com/AAChartModel/AAChartKit-Pro
