### ISSUE TITLE
如何設定AATool Tip

### ISSUE THREAD

**Issue by PedoJoe** [AAChartModel/AAChartKit#1117]
我想問如何設定AATooltip 令到configuration能被套用到相應的AAChartModel, 因為我用了自訂AATooltip但是chart還是顯示不了相應結果

 AAChartModel *aaChartModel = AAChartModel.new
    .chartTypeSet(AAChartTypeColumn)
    .titleSet(@"Concentration of chemicals")
    .subtitleSet(@"ppb")
    .categoriesSet(@[@"NO2",@"H2",@"CO"])
    .yAxisTitleSet(@"Concentration")
    
    .seriesSet(@[
                 
                 AASeriesElement.new
                 .nameSet(@"Concertration")
                 // .dataSet(array),
                 .dataSet(@[@1000.0, @500.9, @100.5]),
                 ]);
   AAOptions *aaOptions = aaChartModel.aa_toAAOptions;
    
    AATooltip *tooltip = aaOptions.tooltip;
    tooltip
    .useHTMLSet(true)
    .formatterSet(@AAJSFunc(function () {
        let colorArr = [];
        colorArr.push("sandybrown");
        colorArr.push("red");
        colorArr.push("mediumspringgreen");
        let wholeContentStr = '<span style=\"' + 'color:lightgray; font-size:13px\"' +'>◉ Gas:</span><br/>'
        if( thisPoint.x == "H2" && thisPoint.y>= 1000 ){
            let spanStyleStartStr = '<span style=\"' + 'color:'+colorArr[1]+'; font-size:13px\"'+ '>◉ ';
            let spanStyleEndStr = '</span> <br/>';
            wholeContentStr += spanStyleStartStr + thisPoint.x +':' + thisPoint.y/1000 +'ppm' + spanStyleEndStr;
        }else if ( thisPoint.x=="H2" && thisPoint.y<=1000){
            let spanStyleStartStr = '<span style=\"' + 'color:'+colorArr[1]+'; font-size:13px\"'+ '>◉ ';
            let spanStyleEndStr = '</span> <br/>';
            wholeContentStr += spanStyleStartStr + thisPoint.x +':' + thisPoint.y +'ppb' + spanStyleEndStr;
        }
        else if ( thisPoint.x=="NO2"){
            let spanStyleStartStr = '<span style=\"' + 'color:'+colorArr[0]+'; font-size:13px\"'+ '>◉ ';
            let spanStyleEndStr = '</span> <br/>';
            wholeContentStr += spanStyleStartStr + thisPoint.x +':' + thisPoint.y +'ppb' + spanStyleEndStr;
        }else if( thisPoint.x == "CO"){
            let spanStyleStartStr = '<span style=\"' + 'color:'+colorArr[0]+'; font-size:13px\"'+ '>◉ ';
            let spanStyleEndStr = '</span> <br/>';
            wholeContentStr += spanStyleStartStr + thisPoint.x +':' + thisPoint.y +'ppb' + spanStyleEndStr;
        }
        return wholeContentStr;
    }))
    ;
   
    
   //  AAOptions *aaOptions = aaChartModel.aa_toAAOptions;
    [_aaChartView aa_drawChartWithChartModel:aaChartModel];

**Comment by AAChartModel** [comment]
想要使用 AAOptions 对象的配置,你应该使用 AAChartView 的 `aa_drawChartWithOptions`来绘制图表.
