### ISSUE TITLE
tooltip 如何隐藏

### ISSUE THREAD

**Issue by flyOfYW** [AAChartModel/AAChartKit#1119]
<img width="486" alt="WX20210112-120252@2x" src="https://user-images.githubusercontent.com/17938752/104268249-6b973580-54ce-11eb-8ebe-3439d657cbb4.png">

我这个一个tableView,cell中有AAChartView，当tooltip出现后，如果不触摸一下这个cell，tooltip不会消失，但我想让滑动的tableView的时候，可以消失cell中的所有的tooltip，我看了tooltip相关的api，但没有找;
不过AATooltip中有个enabled属性，不知道在AAChartView.html定义一个方法，通过aaGlobalChart中获取到tooltip，在通过enabled能否实现该需求

**Comment by AAChartModel** [comment]
AAChartKit 的 demo 中有图表属性高级更新的示例, 关键方法

```objc
    [self.aaChartView aa_updateChartWithOptions:options];

```

这个高级更新功能就是: 带有平滑的动画效果的, 局部更新图表的 AAOptions 的某一个部分的属性, 你查看一下 demo 示例,改动测试一下看看能否符合你的需求

**Comment by AAChartModel** [comment]
示例
* 动态显示 tooltip

     ```objc
    //动态显示 tooltip
    AATooltip *aaTooltip = AATooltip.new
    .enabledSet(true);

    [self.aaChartView aa_updateChartWithOptions:aaTooltip];
    ```


* 动态隐藏 tooltip

```objc
    //动态隐藏 tooltip
    AATooltip *aaTooltip = AATooltip.new
    .enabledSet(false);
    
    [self.aaChartView aa_updateChartWithOptions:aaTooltip];
```

**Comment by Ficky-Michy** [comment]
> 示例
> 
> * 动态显示 tooltip
>   ```objc
>   //动态显示 tooltip
>   AATooltip *aaTooltip = AATooltip.new
>   .enabledSet(true);
>   
>   [self.aaChartView aa_updateChartWithOptions:aaTooltip];
>   ```
> * 动态隐藏 tooltip
> 
> ```objc
>     //动态隐藏 tooltip
>     AATooltip *aaTooltip = AATooltip.new
>     .enabledSet(false);
>     
>     [self.aaChartView aa_updateChartWithOptions:aaTooltip];
> ```

有个奇怪的问题，我在swift中这样设置的：

  
```
 func aaChartView(_ aaChartView: AAChartView, clickEventMessage: AAClickEventMessageModel) {
        let x = Int(clickEventMessage.x ?? 0) ?? 0
        if(clickedX == x){
            var tooltip = AATooltip().enabled(false).shared(true)
            varAAChartView.aa_updateChart(options: tooltip, redraw: false)
            clickedX = -1
        }else{
            var tooltip = AATooltip().enabled(true).shared(true)
            varAAChartView.aa_updateChart(options: tooltip, redraw: false)
            clickedX = x
        }
    }
```


，但是执行了之后，会出现原本的两条线是一起被点击的变成了可以单独只点击一条线。
这是未aa_updateChart的情况，一切正常：

![WechatIMG44](https://user-images.githubusercontent.com/101419143/172595928-be11e17c-d693-41f2-b1a4-2c1ad6e821ea.jpeg)

这是aa_updateChart过后的情况，能够单独点击一条线：

<img width="341" alt="WechatIMG43" src="https://user-images.githubusercontent.com/101419143/172595956-99291a84-be96-4634-a85d-67ba3c2d86de.png">

**Comment by zhwIdea** [comment]
// 设置AAOptions
        let aaOptions = aaModel.aa_toAAOptions()

        // 设置 tooltip 自动隐藏的时间
        aaOptions.chart?.events(
            AAChartEvents()
                .load("""
            function() {
                const chart = this;
                Highcharts.addEvent(
                    chart.tooltip,
                    'refresh',
                    function () {
                        chart.tooltip.hide(3000); // 3s后自动隐藏
                });
            }
      """))
