### ISSUE TITLE
Y轴数据显示和X轴数据量大时的问题

### ISSUE THREAD

**Issue by huipengo** [AAChartModel/AAChartKit#112]
Y轴数据如果是35000000这种数据会被处理成35M，请问下这个在哪修改的？
X轴如果数据量特别大时，可以自定义固定个数么？
PS：这个框架很强大，很美观
![spline](https://user-images.githubusercontent.com/9402895/34970410-4250d3a6-faaf-11e7-948e-b6988299ace8.jpg)

**Comment by AAChartModel** [comment]
> Y轴数据如果是35000000这种数据会被处理成35M，请问下这个在哪修改的？

这个是 *Highcharts* 根据数值大小自动进行智能优化显示的,题主显示原有的值?

**Comment by songbai1211** [comment]
大神，这个怎么显示原有的值呢，我这边被转换成 k，希望显示原来的值
![eecccabb-976e-498c-9d61-40bf87f1a3fd](https://user-images.githubusercontent.com/4758161/35602121-885f2bea-0671-11e8-8bf0-25d5aadb328b.png)

**Comment by songbai1211** [comment]
如果自动优化了，但是怎么没有全部优化掉

**Comment by AAChartModel** [comment]
以上两个问题已得到有效解决,参见 #142  和 #144
