### ISSUE TITLE
柱状图怎么同时使用镜像跟分组

### ISSUE THREAD

**Issue by zhangle520** [AAChartModel/AAChartKit#1121]
大佬你好，我看你的镜像的案例都是两条数据的，一上一下，怎么多条数据分组，然后同时又镜像呢
![WX20210113-210750](https://user-images.githubusercontent.com/19368805/104456242-5b24af00-55e3-11eb-8b19-5d649e1a4e54.png)

**Comment by zhangle520** [comment]
可以设置柱形图的值区间吗，例如一个值是(-20,50)一个是(0,30),这样子的柱子

**Comment by AAChartModel** [comment]
> 可以设置柱形图的值区间吗，例如一个值是(-20,50)一个是(0,30),这样子的柱子

你说的这种叫柱形范围图 , 参考 https://github.com/AAChartModel/AAChartKit/issues/994

**Comment by zhangle520** [comment]
好的，谢谢，自己找还没发现
