### ISSUE TITLE
折线图是否能增加多一个Y轴？

### ISSUE THREAD

**Issue by Chauvetok** [AAChartModel/AAChartKit#1122]
大大：
你好，如果我想在折线图中右边增加多一个Y轴可以吗？数据要怎么处理呢？感谢~

![image](https://user-images.githubusercontent.com/16949950/104673887-94613a00-571d-11eb-9de4-1f4a91479830.png)

**Comment by AAChartModel** [comment]
重复问题, 参考 #759

**Comment by Chauvetok** [comment]
> 重复问题, 参考 #759

好的，感谢大佬。。。
