### ISSUE TITLE
你好，如何实现图中的datalebel样式

### ISSUE THREAD

**Issue by DevZMJ** [AAChartModel/AAChartKit#1127]
![0673B88D-1999-4C8F-AE1B-3852F12FF302](https://user-images.githubusercontent.com/12655415/106222964-8500e700-621b-11eb-9b02-231844798ac4.png)

**Comment by AAChartModel** [comment]
![](https://user-images.githubusercontent.com/16357599/50538101-dc4bad80-0ba4-11e9-83f6-8c9b812ae8b5.png)
![](https://user-images.githubusercontent.com/16357599/72063873-a1cb3380-3315-11ea-9164-4a86bf7dd133.png)

目前 DataLabels 只支持上图这两种类型的样式, 不带尖头的和带有尖头的这两种. 但是带有尖头的不支持你的设计稿中的样式.

相关 issue 参考链接:
* https://github.com/AAChartModel/AAChartKit/issues/521
* https://github.com/AAChartModel/AAChartKit/issues/827

dataLabels 的 shape 属性文档参考链接:
 https://api.highcharts.com.cn/highcharts#plotOptions.series.dataLabels.shape
