### ISSUE TITLE
真机加载时间长而且卡顿，这个怎么优化？

### ISSUE THREAD

**Issue by tongyuling** [AAChartModel/AAChartKit#1130]
数据量就20条，真机加载时间长，超过3秒，而且卡顿，这个怎么优化？

**Comment by tongyuling** [comment]
没人真机卡顿吗？？

**Comment by AAChartModel** [comment]
> 数据量就20条，真机加载时间长，超过3秒，而且卡顿，这个怎么优化？

我在 iPhone X 真机上测试是秒开的, 模拟器上可能有延迟.

**Comment by AAChartModel** [comment]
> 没人真机卡顿吗？？

本身是基于 WKWebView 实现的,所以有局限性, 你可以试试将 demo 在真机中运行, 来判断区别是 AAChartKit 本身的卡顿还是你项目和 AAChartKit 结合时导致的问题.  另外也要看你的真机是什么型号,四五年前的旧机型卡顿的话,那也应该不用太奇怪

**Comment by AAChartModel** [comment]
> 数据量就20条，真机加载时间长，超过3秒，而且卡顿，这个怎么优化？

* 或者可以直接弃用 AAChartKit,使用其他的原生图表框架, 
* 或者创建一个 AAChartView 单例, 直接提前预加载,然后后续的图表绘制都使用这个单例的重绘函数,应该也能部分解决问题.
