### ISSUE TITLE
iOS版本号9.3.3设置透明色无效

### ISSUE THREAD

**Issue by DevZMJ** [AAChartModel/AAChartKit#1131]
![C4A2AB25-079A-45B6-B75E-3F3BD1F563F7](https://user-images.githubusercontent.com/12655415/106597134-f250a700-6590-11eb-93a2-f50f9168a1e8.png)
设置属性为：
AASeriesElement.new
        .nameSet(@"")//线名
        .dataSet(self.chartsModel.YDataArray)//数据源
        .colorSet(line_blue)//线条色
        .zIndexSet(@5)
        .fillColorSet(AAColor.clearColor)//填充渐变色
透明填充色无效

**Comment by AAChartModel** [comment]
你试试直接将图表的类型设置为折线图而非折线填充图呢?

**Comment by AAChartModel** [comment]
> iOS版本号9.3.3设置透明色无效

在模拟器上运行也无效?

**Comment by DevZMJ** [comment]
模拟器还未试过 暂时放弃iOS9系统了
