### ISSUE TITLE
多条线，X轴的间隔不一样，怎样设置Category 标题？

### ISSUE THREAD

**Issue by zhufaming** [AAChartModel/AAChartKit#1135]
x 轴的显示文字是 时间戳格式化后的时时间，category 设置为一分钟间隔
第一条以一分钟为间隔：0  、 1、   2、  3 、   4 、  5 、 6 、 7、 8、 9、 10            接口返回10个点
第二条以5分钟为间隔： 0 、5 、10                                                                                接口返回3个点

请问，这种情况，第二天线的点怎样放在对应的x轴位置

**Comment by AAChartModel** [comment]
参考双X轴图表相关问题 https://github.com/AAChartModel/AAChartKit/issues/780

**Comment by zhufaming** [comment]
你好，需求不是双轴，实现效果
<img width="920" alt="打点间隔不一样@2x" src="https://user-images.githubusercontent.com/15395337/108685339-fee07380-752e-11eb-906e-05fbcadf9fad.png">
如下图
