### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by skuske** [AAChartModel/AAChartKit#114]
I am getting this error:

> -------> AAChartView.m [Line 221] 
☠️☠️💀☠️☠️WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______Error Domain=WKErrorDomain Code=4 "A JavaScript exception has occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: loadTheHighChartView, WKJavaScriptExceptionColumnNumber=21, WKJavaScriptExceptionSourceURL=about:blank, NSLocalizedDescription=A JavaScript exception has occurred}

Any idea how to find out what exactly causes the trouble? Thanks.

**Comment by AAChartModel** [comment]
Did you change the content of the `AAChartView.html`?

**Comment by skuske** [comment]
No, I did not. I actually tested that by re-downloading everything from GitHub, but the problem is still there...

**Comment by skuske** [comment]
I can - all graphs do draw fine. The only problem is that I see that error, but I do not know why...

**Comment by AAChartModel** [comment]
This is a little bit weird, and you can't draw chart correctly if there is the error information.

**Comment by skuske** [comment]
Hmmm - that is indeed strange. If that error shows up I should usually not be able to draw a chart?

**Comment by AAChartModel** [comment]
The error information means that the OC can not find the function of javascript named ` loadTheHighChartView`

**Comment by skuske** [comment]
That is what I thought. Funny that it draws the chart. So, I think I should just ignor that unless the chart stops drawing correctly.

**Comment by AAChartModel** [comment]
Maybe you did something wrong after drawing a chart view rightly!!!🤣🤣🤣

**Comment by skuske** [comment]
LOL. Yes. 👍

**Comment by AAChartModel** [comment]
OKay👌

**Comment by AAChartModel** [comment]
My English is so poor, I seriously doubt that the  grammar  of my English document has a lot of problems, consider of that you already fork the AAChartKit, can I ask you to help modify the document?

**Comment by skuske** [comment]
Yes, but I am extremely limited in time at the moment. Your English is pretty good so far - I understand everything you say... :) I forked it in order to apply the changes I mentioned in the other issues (tooltipstring, keys, and reset-zoom button text).
