### ISSUE TITLE
How to draw representation for 0 values in column chart?

### ISSUE THREAD

**Issue by gbesler** [AAChartModel/AAChartKit#1141]
I would like to draw a representation value for items with value 0 in column chart with @AAChartModel . Let's imagine I have 10 columns with all values 0. This way the chart looks so empty. I want to show a small portion of chart for the value 0. How to achieve that?

I have tried `yAxisMinSet([NSNumber numberWithInteger:-2])`, but it is not drawing anything.

<img width="205" alt="Screen Shot 2021-03-15 at 13 43 23" src="https://user-images.githubusercontent.com/6095238/111141301-6f117080-8594-11eb-9444-aa738c4018cb.png">

**Comment by AAChartModel** [comment]
You can try to change the property `threshold` value of AASeriesElement.

refer to https://github.com/AAChartModel/AAChartKit/issues/655
