### ISSUE TITLE
库封装的非常好！几个小小的建议和问题

### ISSUE THREAD

**Issue by LiuJinfan** [AAChartModel/AAChartKit#1142]
1.能否提供一个单击出现浮窗，双指缩放，单指滑动移动图表的可选项？因为这种交互方式更符合直觉，而且目前的交互方式的双指缩放和双指滑动会冲突。
2.折线图可以隐藏连接点吗？我在库里面只找到了样式AAChartSymbolType的枚举，没有找到隐藏的方法，在数据非常多的时候这些连接点会堆叠在一起，形成一大块墨水一样的图案。
3.reset zoom的浮窗可以隐藏吗，有时候并不希望他出现在视图中，因为可能会遮挡数据

**Comment by AAChartModel** [comment]
> 1.能否提供一个单击出现浮窗，双指缩放，单指滑动移动图表的可选项？因为这种交互方式更符合直觉，而且目前的交互方式的双指缩放和双指滑动会冲突。

查看 AATooltip 的属性 `followTouchMove`

```objc
 //在触摸设备上，tooltip.followTouchMove选项为true（默认）时，平移需要两根手指。若要允许用一根手指平移，请将followTouchMove设置为
AAPropStatementAndPropSetFuncStatement(assign, AATooltip, BOOL,       followTouchMove)false。
```

参考在线链接 https://api.highcharts.com/highcharts/tooltip.followTouchMove

**Comment by AAChartModel** [comment]
> 2.折线图可以隐藏连接点吗？我在库里面只找到了样式AAChartSymbolType的枚举，没有找到隐藏的方法，在数据非常多的时候这些连接点会堆叠在一起，形成一大块墨水一样的图案。

```objc
    .markerSymbolSet(AAChartSymbolTypeCircle)
    .markerRadiusSet(@6)//设置折线连接点宽度为0,即是隐藏连接点
```

**Comment by AAChartModel** [comment]
> 3.reset zoom的浮窗可以隐藏吗，有时候并不希望他出现在视图中，因为可能会遮挡数据


重复问题， 

参考 https://github.com/AAChartModel/AAChartKit/issues/954

参考 #1018
