### ISSUE TITLE
y轴背景色怎么设置成不透明？

### ISSUE THREAD

**Issue by TinyMio** [AAChartModel/AAChartKit#1147]
你好，有两个问题请教一下：
问题一：x轴可滑动时，y轴是透明的，x轴像是被遮住一样，有没有什么方法可以设置y轴的背景啊？如图一
问题二：曲线填充图，有两个数据时，曲线是条直线，能不能画成平滑的曲线而不是一条直线？如图二

图一：<img width="680" alt="WeChatc9ea269b11a28f8e446bd2494c43797b" src="https://user-images.githubusercontent.com/13376032/111953084-18221300-8b21-11eb-83e0-780d2c3536b4.png">
图二L<img width="692" alt="WeChat63b5465005463ad3fc9f1b1db457deb9" src="https://user-images.githubusercontent.com/13376032/111953104-1f492100-8b21-11eb-9293-fc8c09d150de.png">

**Comment by MrLiuBing** [comment]
同问问题一 希望大神解答

**Comment by AAChartModel** [comment]
> 问题一：x轴可滑动时，y轴是透明的，x轴像是被遮住一样，有没有什么方法可以设置y轴的背景啊？如图一


```objc
//Refer to online API document: https://api.highcharts.com/highcharts/chart.scrollablePlotArea
@interface AAScrollablePlotArea : NSObject

AAPropStatementAndPropSetFuncStatement(strong, AAScrollablePlotArea, NSNumber *, minHeight)
AAPropStatementAndPropSetFuncStatement(strong, AAScrollablePlotArea, NSNumber *, minWidth)
AAPropStatementAndPropSetFuncStatement(strong, AAScrollablePlotArea, NSNumber *, opacity)
AAPropStatementAndPropSetFuncStatement(strong, AAScrollablePlotArea, NSNumber *, scrollPositionX)
AAPropStatementAndPropSetFuncStatement(strong, AAScrollablePlotArea, NSNumber *, scrollPositionY)

@end
```

关键属性 

```objc
AAPropStatementAndPropSetFuncStatement(strong, AAScrollablePlotArea, NSNumber *, opacity)
```

参考在线链接 https://api.highcharts.com/highcharts/chart.scrollablePlotArea.opacity

**Comment by MrLiuBing** [comment]
感谢！

**Comment by AAChartModel** [comment]
> 问题二：曲线填充图，有两个数据时，曲线是条直线，能不能画成平滑的曲线而不是一条直线？如图二

不能直接支持此功能, 或许可以通过插入一个隐藏的点这种硬核的方式来解决问题吧. 但确实是无法直接支持的

**Comment by AAChartModel** [comment]
@MrLiuBing 你是怎么设置的?

**Comment by MrLiuBing** [comment]
- (void)configureColumnChartAndBarChartStyle {
    _chartModel
    .xAxisLabelsStyleSet(AAStyleColorSizeWeight(AAColor.grayColor, 9, AAChartFontWeightTypeBold))
    .categoriesSet(self.titles)
    .animationTypeSet(AAChartAnimationEaseOutCubic)//图形的渲染动画类型为 EaseOutCubic
    .animationDurationSet(@(1200))//图形渲染动画时长为1200毫秒
    .scrollablePlotAreaSet(
        AAScrollablePlotArea.new
        .opacitySet(@0.99)
        .minWidthSet(@1000)
        .scrollPositionXSet(@(500))
    );
}

**Comment by MrLiuBing** [comment]
@0.01也试过 没有变化

**Comment by MrLiuBing** [comment]
用您给的demo来试的话 给出的方法是正常的 肯定是我哪里没用好 我自己再仔细看下 谢谢
