### ISSUE TITLE
 当所有值为 0 时 怎么设置不悬浮 

### ISSUE THREAD

**Issue by Cmt810605682** [AAChartModel/AAChartKit#1149]
当所有值为 0 时 ,怎么设置不悬浮 让显示在底部?

**Comment by AAChartModel** [comment]
重复问题, 参考 https://github.com/AAChartModel/AAChartKit/issues/773

**Comment by Cmt810605682** [comment]
谢谢大佬 已解决!

**Comment by Cmt810605682** [comment]
![image](https://user-images.githubusercontent.com/13723646/112455057-51ae8480-8d94-11eb-8c34-439a355a1351.png)
大佬~提示框里面的 文字 怎么居中

**Comment by AAChartModel** [comment]
你这里是自定义了 tooltip 的文字内容吧? 自定义相关的代码贴出来看看👀

**Comment by Cmt810605682** [comment]
![{F61B8C19-DDEE-0FC6-BD6A-D617E815B397}](https://user-images.githubusercontent.com/13723646/112563232-f0c69100-8e13-11eb-91a2-115c874a2711.jpg)
感谢回复 这是我自定义提示框的代码

**Comment by Cmt810605682** [comment]
大佬 有空时候帮忙看下这个问题 谢谢

**Comment by Cmt810605682** [comment]
已解决!
