### ISSUE TITLE
我从cocoapods上导入该框架一直报错

### ISSUE THREAD

**Issue by liuleiai1** [AAChartModel/AAChartKit#115]
你好，我从cocoapods上导入该框架，一直有一个报错解决不了，ld: library not found for -lAAChartKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)，有空请看一下

**Comment by AAChartModel** [comment]
抱歉,暂时不支持 cocoapods 导入,目前能够 pod search 得到的版本是有问题的,请按照 README文档中的说明,手动导入,谢谢.

**Comment by liuleiai1** [comment]
好的，知道了

**Comment by AAChartModel** [comment]
之所以目前还没有支持 pod 导入主要是因为我似乎没有解决 cocoapods 导入后, AAChartView 无法正确加载到本地 HTML 资源文件的问题,话说大佬有这方面经验吗?可以帮忙解决一下不?

**Comment by liuleiai1** [comment]
我暂时也不知道如何解决，如果想到好的方法给你反馈

**Comment by AAChartModel** [comment]
🆗

**Comment by AAChartModel** [comment]
嗯,有其他使用问题,随时提问.

**Comment by DreamForStar** [comment]
我说我pod导入 拷贝你的代码 报了url是nil的问题

**Comment by AAChartModel** [comment]
参考我上面👆的话
> 之所以目前还没有支持 pod 导入主要是因为我似乎还是没有解决 cocoapods 导入后, AAChartView 无法正确加载到本地 HTML 资源文件的问题

@DreamForStar
