### ISSUE TITLE
不支持macOS吗？

### ISSUE THREAD

**Issue by HBrianChen** [AAChartModel/AAChartKit#1151]
Analyzing dependencies
Pre-downloading: `AAChartKit` from `https://github.com/AAChartModel/AAChartKit.git`
[!] The platform of the target `MyApp` (macOS 10.14) is not compatible with `AAChartKit (6.0.0)`, which does not support `macOS`.

**Comment by AAChartModel** [comment]
仅仅通过 Mac Catalyst  方式来支持 macOS

**Comment by AAChartModel** [comment]
你也可以自己新建一个 ChartView 类文件, 通过继承 mac 中的 WebView, 照抄 AAChartView 中的代码, 来实现让 AAChartKit 不用通过 Mac Catalyst 方式来支持 macOS.
