### ISSUE TITLE
折线图如何置空连线？

### ISSUE THREAD

**Issue by c1s1x1** [AAChartModel/AAChartKit#1155]
![image](https://user-images.githubusercontent.com/13296895/113808390-7c3b0d00-9798-11eb-9b7b-f598846eaba7.png)
X轴固定为一个月31天数据，但给的数据可能没有31天，可能只有13天或者22天这种，但置空后的线段就不连贯了，我想为空的天数就跳过直接连有数据的点，不知道如何设置

**Comment by c1s1x1** [comment]
AAChartView *aaChartView = [[AAChartView alloc]init];
    aaChartView.frame = CGRectMake(0, 0, self.TestView.frame.size.width - 30, self.TestView.frame.size.height);
    ////禁用 AAChartView 滚动效果(默认不禁用)
    [self.TestView addSubview:aaChartView];
    AAChartModel *aaChartModel= AAObject(AAChartModel)
    .chartTypeSet(AAChartTypeArea)//设置图表的类型(这里以设置的为折线面积图为例)
    .titleSet(@"2021年3月份体重记录")//设置图表标题
    .colorsThemeSet(@[@"#C0D6F1"])//设置主题颜色数组
    .yAxisVisibleSet(NO) .categoriesSet(@[@"1日",@"2日",@"3日",@"4日",@"5日",@"6日",@"7日",@"8日",@"9日",@"10日",@"11日",@"12日",@"13日",@"14日",@"15日",@"16日",@"17日",@"18日",@"19日",@"20日",@"21日",@"22日",@"23日",@"24日",@"25日",@"26日",@"27日",@"28日",@"29日",@"30日",@"31日"])//图表横轴的内容
    .categoriesSet(@[@"",@"",@"",@"",@"",@"",@"7日",@"",@"",@"",@"",@"",@"",@"14日",@"",@"",@"",@"",@"",@"",@"21日",@"",@"",@"",@"",@"",@"",@"28日",@"",@"",@""])//图表横轴的内容
    .seriesSet(@[
            AAObject(AASeriesElement)
            .nameSet(@"3月")
            .dataSet(@[@7.0,[NSNull null], [NSNull null], @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @21.3])]);
    /*图表视图对象调用图表模型对象,绘制最终图形*/
    [aaChartView aa_drawChartWithChartModel:aaChartModel];
    AAOptions *options =  [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];

    options.xAxis.tickInterval = @7;
    [aaChartView aa_drawChartWithOptions:options];

**Comment by c1s1x1** [comment]
```
AAChartView *aaChartView = [[AAChartView alloc]init];
    aaChartView.frame = CGRectMake(0, 0, self.TestView.frame.size.width - 30, self.TestView.frame.size.height);
    ////禁用 AAChartView 滚动效果(默认不禁用)
    [self.TestView addSubview:aaChartView];
    AAChartModel *aaChartModel= AAObject(AAChartModel)
    .chartTypeSet(AAChartTypeArea)//设置图表的类型(这里以设置的为折线面积图为例)
    .titleSet(@"2021年3月份体重记录")//设置图表标题
    .colorsThemeSet(@[@"#C0D6F1"])//设置主题颜色数组
    .yAxisVisibleSet(NO) .categoriesSet(@[@"1日",@"2日",@"3日",@"4日",@"5日",@"6日",@"7日",@"8日",@"9日",@"10日",@"11日",@"12日",@"13日",@"14日",@"15日",@"16日",@"17日",@"18日",@"19日",@"20日",@"21日",@"22日",@"23日",@"24日",@"25日",@"26日",@"27日",@"28日",@"29日",@"30日",@"31日"])//图表横轴的内容
    .categoriesSet(@[@"",@"",@"",@"",@"",@"",@"7日",@"",@"",@"",@"",@"",@"",@"14日",@"",@"",@"",@"",@"",@"",@"21日",@"",@"",@"",@"",@"",@"",@"28日",@"",@"",@""])//图表横轴的内容
    .seriesSet(@[
            AAObject(AASeriesElement)
            .nameSet(@"3月")
            .dataSet(@[@7.0,[NSNull null], [NSNull null], @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @21.3])]);
    /*图表视图对象调用图表模型对象,绘制最终图形*/
    [aaChartView aa_drawChartWithChartModel:aaChartModel];
    AAOptions *options =  [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];

    options.xAxis.tickInterval = @7;
    [aaChartView aa_drawChartWithOptions:options];
```

**Comment by c1s1x1** [comment]
已解决，AAChartModel里有AAPropSetFuncImplementation(AAChartModel, BOOL,       connectNulls) //设置折线是否断点重连(是否连接空值点)

**Comment by AAChartModel** [comment]
查看 AASeries 类文件中的属性 connectNulls

```objc
AAPropStatementAndPropSetFuncStatement(assign, AASeries, BOOL ,          connectNulls) //设置折线是否断点重连
```

参考知乎问答相关: //https://www.zhihu.com/question/24173311

**Comment by AAChartModel** [comment]
> 已解决，AAChartModel里有AAPropSetFuncImplementation(AAChartModel, BOOL, connectNulls) //设置折线是否断点重连(是否连接空值点)

由于这个是比较偏的冷门属性, 后续可能会从 AAChartModel 类文件中挪走, 所以推荐像下面这样配置

```objc
    aaOptions.plotOptions.series.connectNulls = true;
```
