### ISSUE TITLE
词云

### ISSUE THREAD

**Issue by BigPoro** [AAChartModel/AAChartKit#1159]
请问当前版本支持词云功能吗？不支持的话后续有支持的计划吗？

**Comment by BigPoro** [comment]
@AAChartModel

**Comment by AAChartModel** [comment]
![image](https://user-images.githubusercontent.com/16357599/114892566-78b22080-9e3f-11eb-93e8-f7ed756de88a.png)

![image](https://user-images.githubusercontent.com/16357599/114891791-c5492c00-9e3e-11eb-8775-a4b2af059298.png)

**Comment by AAChartModel** [comment]
AAChartKit-Pro 支持词云图, AAChartKit-Pro 链接地址 https://github.com/AAChartModel/AAChartKit-Pro

**Comment by AAChartModel** [comment]
参考 https://github.com/AAChartModel/AAChartKit/issues/1158
