### ISSUE TITLE
图表Y轴文字的值自定义显示风格显示的问题

### ISSUE THREAD

**Issue by linwenlong-monkey** [AAChartModel/AAChartKit#1161]
![image](https://user-images.githubusercontent.com/66247833/115000864-c11c1d80-9ed5-11eb-801e-4a757009aa44.png)
你好，这个图片上的20k，怎么设置不会按k的方式显示的，直接20000的。
![image](https://user-images.githubusercontent.com/66247833/115001058-ef016200-9ed5-11eb-88bb-ef7f7615d665.png)
需要这样展示，目前的框架支持这种吗

**Comment by AAChartModel** [comment]
> highcharts怎么样让y轴的值完整显示 而不是100000显示为100k?

```js
yAxis: [{
    	title: {
    	    	...
    	},
    	labels: {
        	....,
        	format: '{value:.,0f}'//就这个地方设置显示格式
    	}
}]
```

以上内容来源于网络.

你通过 AAOptions 来调整一下 AAYAxis 的 format 的值为 `{value:.,0f}` 如下👇

```objc
    aaOptions.yAxis.labels.format = @"{value:.,0f}";
```

即可

**Comment by AAChartModel** [comment]
另外自定义 Y 轴值的单位后缀 , 参考 #1174
