### ISSUE TITLE
点击图表后准星线 crosshair 显示和隐藏的问题

### ISSUE THREAD

**Issue by linwenlong-monkey** [AAChartModel/AAChartKit#1166]
![image](https://user-images.githubusercontent.com/66247833/115803116-cf58c500-a412-11eb-87e2-87c14c305018.png)

您好，图片上那个点击的背景视图怎么隐藏的

**Comment by AAChartModel** [comment]
```pod
pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'

```

你按照 README 中描述的, 将AAChartKit 更新到最新内容, 默认就不会有这个准星线了

**Comment by AAChartModel** [comment]
https://github.com/AAChartModel/AAChartKit/commit/2b00b03137b2a75a5c0a1f2ba5ff4eba3f3e26b1  在这次提交中, 去除了默认启用准星线的代码
