### ISSUE TITLE
柱状图(条形图)回调

### ISSUE THREAD

**Issue by MargoFG** [AAChartModel/AAChartKit#1167]
实现效果：
![image](https://user-images.githubusercontent.com/17683036/115823383-d85c8d00-a438-11eb-90b5-d696784f2b9e.png)
使用的是：
![image](https://user-images.githubusercontent.com/17683036/115823529-09d55880-a439-11eb-85a6-d01f281ca4a8.png)
但是需要在触摸的时候，我要获取到最小值和做大值（另做他用）
使用
![image](https://user-images.githubusercontent.com/17683036/115823618-338e7f80-a439-11eb-813c-3806d9fd09fe.png)
监听的回调只有最小值，没有最大值
![image](https://user-images.githubusercontent.com/17683036/115823669-4d2fc700-a439-11eb-8b6e-51364d9818a0.png)

**Comment by MargoFG** [comment]
怎样获取到 y1,y2,是否可以获取

**Comment by AAChartModel** [comment]
你通过 index 索引直接从你的 data 数组中去获取不是一样的吗?

**Comment by MargoFG** [comment]
是的，目前就是通过index 取得。
