### ISSUE TITLE
折线图使用 zones分区，加上最小minWidth之后，一部分显示不出来

### ISSUE THREAD

**Issue by tttyyyur** [AAChartModel/AAChartKit#1169]
![241619429333_ pic](https://user-images.githubusercontent.com/15380556/116060959-e74f7380-a6b4-11eb-8cad-950ac90e3e5f.jpg)

**Comment by AAChartModel** [comment]
尴尬了, 这个问题估计搞不定, 参考 https://github.com/AAChartModel/AAChartKit-Swift/issues/289

**Comment by tttyyyur** [comment]
好的，感谢解答
