### ISSUE TITLE
条形图 Datalabel 两根线如果靠的近就只显示一个值

### ISSUE THREAD

**Issue by LeeonLi** [AAChartModel/AAChartKit#1171]
条形图 Datalabel 两根线如果靠的近就只显示一个值 如图所示
![1619495777268](https://user-images.githubusercontent.com/6621848/116183067-d4d64800-a74f-11eb-8024-2e846796dc7e.jpg)

**Comment by AAChartModel** [comment]
重复问题, 参考 https://github.com/AAChartModel/AAChartKit/issues/707
