### ISSUE TITLE
我想知道这个bar的效果的宽度是否可以设置成固定宽度而不是动态的！！！！！

### ISSUE THREAD

**Issue by kite424** [AAChartModel/AAChartKit#1172]
![2](https://user-images.githubusercontent.com/57931594/116211305-3f01e380-a776-11eb-8a40-3d355be0f7c9.jpeg)
![1](https://user-images.githubusercontent.com/57931594/116211313-40cba700-a776-11eb-870a-5c2218efb3b4.jpeg)
是否可以设置，无论多少数据，成固定大小width的bar形状

**Comment by AAChartModel** [comment]
Highcharts 不支持直接设置条状图和柱状图的棱柱的宽度, 不过你可以通过 调整 AAScrollablePlotArea 的

```objc
AAPropSetFuncImplementation(AAScrollablePlotArea, NSNumber *, minHeight)
AAPropSetFuncImplementation(AAScrollablePlotArea, NSNumber *, minWidth)
```

这两个属性来间接设置棱柱的宽度. 

AAScrollablePlotArea 的具体使用参见使用 DEMO
