### ISSUE TITLE
如果横坐标数据数组中值都是0，这时候能不能让这条全是0的线在底部显示，不要显示在中间

### ISSUE THREAD

**Issue by a1906404** [AAChartModel/AAChartKit#1182]
![5BF1653834640731BDD7EE87ED837693](https://user-images.githubusercontent.com/13724610/118904527-a7df1480-b94c-11eb-8a1a-055cbd292316.jpg)

**Comment by AAChartModel** [comment]
重复问题, 参见 https://github.com/AAChartModel/AAChartKit/issues/773
