### ISSUE TITLE
mac os不能用？文档里写的兼容macOS，但是不能用，拖进项目中就会报错

### ISSUE THREAD

**Issue by hxcshr** [AAChartModel/AAChartKit#1185]

**Comment by AAChartModel** [comment]
仅支持通过 catalyst 来支持 macOS

**Comment by AAChartModel** [comment]
现已在此次提交  https://github.com/AAChartModel/AAChartKit/commit/0822374343856d08bab679380f535aaa827208c8 中新增了对 native macOS 的支持, 更新 AAChartKit 至最新内容试试.
