### ISSUE TITLE
AADataLabels的format属性设置

### ISSUE THREAD

**Issue by ZCFade** [AAChartModel/AAChartKit#1190]
![CD39C08E-A011-44E1-A7CC-23E943A392F3](https://user-images.githubusercontent.com/22791569/120620213-53c94980-c48f-11eb-8233-f86fe5b23889.png)

我想把这个format设置成我自己初始化的数组 对应柱状图最上面的每一个dataLabels   请问这里的formatSet该怎么写了？  我没很明白这个属性的设置规则

**Comment by AAChartModel** [comment]
你的设计稿是什么样子的?

**Comment by ZCFade** [comment]
> 你的设计稿子的？

![7DEEBAEA-572B-496E-A865-38060E6B4D9D](https://user-images.githubusercontent.com/22791569/120623659-8163c200-c492-11eb-9f7a-51ce172c6437.png)

**Comment by AAChartModel** [comment]
从你这个设计稿来看, 你这个不太好弄啊, 本身你的每个堆积的棱柱中间就已经显示了对应的数据的 dataLabel 了, 顶部的文字就没有剩余的 dataLabel 来显示了.

 而且你的这个顶部的数据看起来也不像是一组堆积的棱柱的值的总和啊, 从设计上看就有点奇怪

**Comment by ZCFade** [comment]
> 从你这个设计稿来看, 你这个不太好弄啊, 本身你的每个堆积的棱柱中间就已经显示了对应的数据的 dataLabel 了, 顶部的文字就没有剩余的 dataLabel 来显示了.
> 
> 而且你的这个顶部的数据看起来也不像是一组堆积的棱柱的值的总和啊, 从设计上看就有点奇怪

是的  所以我就想隐藏每一段的dataLabel  只显示最上面的那一个（也就是设置dataLabel的format属性），但是我看demo都是写的@"{point.name} "、@"{y}" 我想替换成我这边自定义的数组的值来对应Y轴和X轴  所以想问一下这个属性的赋值规则是啥

**Comment by AAChartModel** [comment]
其实你可以试试这个双 X 轴图表的方法  https://github.com/AAChartModel/AAChartKit/issues/780

让其中一个轴专门用来显示数据

**Comment by ZCFade** [comment]
> 其实你可以试试这个双 X 轴图表的方法 #780
> 
> 让其中一个轴专门用来显示数据

没办法呀  需求就是一根  不让起多根  最上面的白色子体数据是堆叠数据分别 * 1  * 2 * 3 * 4  然后相加得到的数据   这有办法通过dataLabel 的 format 计算处理吗（关闭dataLabelsEnabled属性，只打开最上面的那一行dataLabel）

**Comment by AAChartModel** [comment]
> 让其中一个轴专门用来显示数据

然后专门显示数据的这一个轴隐藏轴线, 只显示线上的值

**Comment by ZCFade** [comment]
可以留个联系方式吗   细问一下

**Comment by ZCFade** [comment]
> > 让其中一个轴专门用来显示数据
> 
> 然后专门显示数据的这一个轴隐藏轴线, 只显示线上的值

可以留个联系方式吗  细问一下
