### ISSUE TITLE
柱形范围图 可以设置柱子的宽度吗

### ISSUE THREAD

**Issue by bazingaJ** [AAChartModel/AAChartKit#1195]
AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
   aaOptions.plotOptions.column.groupPadding = @.05;
   aaOptions.plotOptions.column.pointPadding = @0;

设置了column的间距 对AAChartTypeColumnrange 不管用

**Comment by AAChartModel** [comment]
aaOptions.plotOptions.columnRange.groupPadding = @.05;
aaOptions.plotOptions.columnRange.pointPadding = @0;

**Comment by bazingaJ** [comment]
AAPropStatementAndPropSetFuncStatement(strong, AAPlotOptions, AAColumn     *, column) 
AAPropStatementAndPropSetFuncStatement(strong, AAPlotOptions, AALine       *, line) 
AAPropStatementAndPropSetFuncStatement(strong, AAPlotOptions, AAPie        *, pie) 
AAPropStatementAndPropSetFuncStatement(strong, AAPlotOptions, AABar        *, bar) 
AAPropStatementAndPropSetFuncStatement(strong, AAPlotOptions, AASpline     *, spline) 
AAPropStatementAndPropSetFuncStatement(strong, AAPlotOptions, AASeries     *, series) 
AAPropStatementAndPropSetFuncStatement(strong, AAPlotOptions, AAArea       *, area) 
AAPropStatementAndPropSetFuncStatement(strong, AAPlotOptions, AAAreaspline *, areaspline) 
AAPropStatementAndPropSetFuncStatement(strong, AAPlotOptions, NSObject     *, columnrange) 
AAPropStatementAndPropSetFuncStatement(strong, AAPlotOptions, NSObject     *, arearange) 

range 的 propertyPointerType是NSObject 按照你的写法会报错 Property 'groupPadding'(pointPadding) not found on object of type 'NSObject *'

**Comment by bazingaJ** [comment]
![image](https://user-images.githubusercontent.com/17940373/122514268-42ab3b80-d03e-11eb-894b-e0567baf0efa.png)

**Comment by bazingaJ** [comment]
等待您的回复，谢谢啦

**Comment by AAChartModel** [comment]
aaOptions.plotOptions.series.groupPadding = @.05;
aaOptions.plotOptions.series.pointPadding = @0;

**Comment by bazingaJ** [comment]
![image](https://user-images.githubusercontent.com/17940373/122530042-a8a0be80-d050-11eb-904b-8b0e55b1c3a5.png)
![image](https://user-images.githubusercontent.com/17940373/122530133-c110d900-d050-11eb-8c9f-22bbe8ece29d.png)

**Comment by bazingaJ** [comment]
大神，series 也没有groupPadding和pointPadding属性。0.0

**Comment by AAChartModel** [comment]
你先自己临时加上吧, 我后面有时间改下

**Comment by bazingaJ** [comment]
感谢，感谢。问题已解决。
