### ISSUE TITLE
关于多边形雷达图.categories 属性使用？

### ISSUE THREAD

**Issue by 90candy** [AAChartModel/AAChartKit#1206]
为何我在demo 进行配置 

四角形雷达图的属性
.categoriesSet(@[@"识记", @"理解", @"运用", @"分析"])

效果变成了一个正方形的多边形，而不是原来的竖着的菱形(图1为demo改的效果图，图2为期待的效果图)

<img width="200" alt="demo效果图1" src="https://user-images.githubusercontent.com/22791504/124559287-25fc6980-de6e-11eb-8ebd-1f622ce83f82.png">

<img width="291" alt="期待效果图2" src="https://user-images.githubusercontent.com/22791504/124559796-ade27380-de6e-11eb-8e20-833179327e94.png">

**Comment by AAChartModel** [comment]
重复问题, 参考 https://github.com/AAChartModel/AAChartKit/issues/301

**Comment by hhw2020** [comment]
> 重复问题, 参考 #301

我设置了pointPlacement = @"on"，多边形正了，但是yAxis.gridLine错位了。是我的问题吗？
