### ISSUE TITLE
你好，我的y轴的刻度值想格式化为：10000变成1w，300000变成30w

### ISSUE THREAD

**Issue by zhanghongdou** [AAChartModel/AAChartKit#1208]
你好，我的y轴的刻度值想格式化为：10000变成1w，300000变成30w，这个怎么设置，实在没找到设置的地方，请指教，谢谢

**Comment by AAChartModel** [comment]
现已为 AALang 新增了属性

```objc
AAPropStatementAndPropSetFuncStatement(strong, AALang, NSNumber    *, numericSymbolMagnitude) //国际单位符基数
AAPropStatementAndPropSetFuncStatement(strong, AALang, NSArray<NSString *>    *, numericSymbols) //国际单位符
```

如 README 中所言, 更新 AAChartKit 至最新内容, 即可使用新增属性

**Comment by AAChartModel** [comment]
**配置 AAOptions** 

```objc
- (AAOptions *)configureYAxisLabelsNumericSymbolsMagnitudeOfAerasplineChart {
    NSDictionary *gradientColorDic1 =
    [AAGradientColor gradientColorWithDirection:AALinearGradientDirectionToBottom
                               startColorString:@"#FC354C"
                                 endColorString:@"#0ABFBC"];
    
    AAChartModel *aaChartModel = AAChartModel.new
    .chartTypeSet(AAChartTypeAreaspline)
    .titleSet(@"Numeric symbols magnitude")
    .subtitleSet(@"Chinese and Japanese uses ten thousands (万) as numeric symbol")
    .categoriesSet(@[
        @"Jan", @"Feb", @"Mar", @"Apr", @"May", @"Jun",
        @"July", @"Aug", @"Spe", @"Oct", @"Nov", @"Dec"
    ])
    .markerRadiusSet(@8.0)//marker点半径为8个像素
    .markerSymbolStyleSet(AAChartSymbolStyleTypeInnerBlank)//marker点为空心效果
    .markerSymbolSet(AAChartSymbolTypeCircle)//marker点为圆形点○
    .yAxisLineWidthSet(@0)
    .yAxisGridLineStyleSet([AALineStyle styleWithWidth:@0])
    .legendEnabledSet(false)
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"Tokyo Hot")
        .lineWidthSet(@7.0)
        .colorSet(AAColor.redColor)//猩红色, alpha 透明度 1
        .fillColorSet((id)gradientColorDic1)
        .dataSet(@[@70000.0, @60000.9, @20000.5, @140000.5, @180000.2, @210000.5, @50000.2, @260000.5, @230000.3, @450000.3, @130000.9, @90000.6]),
               ]);
    
    AAOptions *aaOptions = aaChartModel.aa_toAAOptions;
    
    aaOptions.defaultOptions = AALang.new
    .numericSymbolMagnitudeSet(@10000) //国际单位符基数
    .numericSymbolsSet(@[@"万",@"億"]) //国际单位符
    ;
    
    return aaOptions;
}

```

**最终图表效果**
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-14 at 19 50 50](https://user-images.githubusercontent.com/16357599/125617611-f85df091-d37d-4d9d-b0ba-2c0651ad5cb4.png)

**Comment by zhanghongdou** [comment]
太感谢了，真的，膜拜大神




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月14日(星期三) 晚上7:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 你好，我的y轴的刻度值想格式化为：10000变成1w，300000变成30w (#1208)





 
配置 AAOptions
 - (AAOptions *)configureYAxisLabelsNumericSymbolsMagnitudeOfAerasplineChart {     NSDictionary *gradientColorDic1 =     [AAGradientColor gradientColorWithDirection:AALinearGradientDirectionToBottom                                startColorString:@"#FC354C"                                  endColorString:@"#0ABFBC"];          AAChartModel *aaChartModel = AAChartModel.new     .chartTypeSet(AAChartTypeAreaspline)     .titleSet(@"Numeric symbols magnitude")     .subtitleSet(@"Chinese and Japanese uses ten thousands (万) as numeric symbol")     .categoriesSet(@[         @"Jan", @"Feb", @"Mar", @"Apr", @"May", @"Jun",         @"July", @"Aug", @"Spe", @"Oct", @"Nov", @"Dec"     ])     .***@***.***)//marker点半径为8个像素     .markerSymbolStyleSet(AAChartSymbolStyleTypeInnerBlank)//marker点为空心效果     .markerSymbolSet(AAChartSymbolTypeCircle)//marker点为圆形点○     .***@***.***)     .yAxisGridLineStyleSet([AALineStyle ***@***.***)     .legendEnabledSet(false)     .seriesSet(@[         AASeriesElement.new         .nameSet(@"Tokyo Hot")         .***@***.***)         .colorSet(AAColor.redColor)//猩红色, alpha 透明度 1         .fillColorSet((id)gradientColorDic1)         .dataSet(@***@***.***, @60000.9, @20000.5, @140000.5, @180000.2, @210000.5, @50000.2, @260000.5, @230000.3, @450000.3, @130000.9, @90000.6]),                ]);          AAOptions *aaOptions = aaChartModel.aa_toAAOptions;          aaOptions.defaultOptions = AALang.new     .***@***.***) //国际单位符基数     .numericSymbolsSet(@[@"万",@"億"]) //国际单位符     ;          return aaOptions; } 
 
最终图表效果

**Comment by zhanghongdou** [comment]
pod 'AAChartKit', '~&gt; 6.0.0'




是因为我的版本太低了吗，没有找到这个属性



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AAChartModel/AAChartKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 晚上7:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartKit] 你好，我的y轴的刻度值想格式化为：10000变成1w，300000变成30w (#1208)





 
配置 AAOptions
 - (AAOptions *)configureYAxisLabelsNumericSymbolsMagnitudeOfAerasplineChart {     NSDictionary *gradientColorDic1 =     [AAGradientColor gradientColorWithDirection:AALinearGradientDirectionToBottom                                startColorString:@"#FC354C"                                  endColorString:@"#0ABFBC"];          AAChartModel *aaChartModel = AAChartModel.new     .chartTypeSet(AAChartTypeAreaspline)     .titleSet(@"Numeric symbols magnitude")     .subtitleSet(@"Chinese and Japanese uses ten thousands (万) as numeric symbol")     .categoriesSet(@[         @"Jan", @"Feb", @"Mar", @"Apr", @"May", @"Jun",         @"July", @"Aug", @"Spe", @"Oct", @"Nov", @"Dec"     ])     .***@***.***)//marker点半径为8个像素     .markerSymbolStyleSet(AAChartSymbolStyleTypeInnerBlank)//marker点为空心效果     .markerSymbolSet(AAChartSymbolTypeCircle)//marker点为圆形点○     .***@***.***)     .yAxisGridLineStyleSet([AALineStyle ***@***.***)     .legendEnabledSet(false)     .seriesSet(@[         AASeriesElement.new         .nameSet(@"Tokyo Hot")         .***@***.***)         .colorSet(AAColor.redColor)//猩红色, alpha 透明度 1         .fillColorSet((id)gradientColorDic1)         .dataSet(@***@***.***, @60000.9, @20000.5, @140000.5, @180000.2, @210000.5, @50000.2, @260000.5, @230000.3, @450000.3, @130000.9, @90000.6]),                ]);          AAOptions *aaOptions = aaChartModel.aa_toAAOptions;          aaOptions.defaultOptions = AALang.new     .***@***.***) //国际单位符基数     .numericSymbolsSet(@[@"万",@"億"]) //国际单位符     ;          return aaOptions; } 
 
最终图表效果

**Comment by zhanghongdou** [comment]
pod 'AAChartKit', '~&gt; 6.0.0'







你好，6.0.0版本里面，我没有找到这个需要的属性





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AAChartModel/AAChartKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 晚上7:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartKit] 你好，我的y轴的刻度值想格式化为：10000变成1w，300000变成30w (#1208)





 
现已为 AALang 新增了属性
 AAPropStatementAndPropSetFuncStatement(strong, AALang, NSNumber    *, numericSymbolMagnitude) //国际单位符基数 AAPropStatementAndPropSetFuncStatement(strong, AALang, NSArray<NSString *&gt;    *, numericSymbols) //国际单位符
 
如 README 中所言, 更新 AAChartKit 至最新内容, 即可使用新增属性

**Comment by AAChartModel** [comment]
不要指定版本, 我没有新发版本, 你直接如 README 中所言, 不指定版本, 更新到最新内容即可

**Comment by feng-tianyou** [comment]
> 不要指定版本, 我没有新发版本, 你直接如 README 中所言, 不指定版本, 更新到最新内容即可

大佬你好，我这边不指定版本也更新不到上述的两个属性，不知道怎么回事

**Comment by AAChartModel** [comment]
> > 不要指定版本, 我没有新发版本, 你直接如 README 中所言, 不指定版本, 更新到最新内容即可
> 
> 大佬你好，我这边不指定版本也更新不到上述的两个属性，不知道怎么回事

你把 AAChartKit 删了再重装试试呢?
