### ISSUE TITLE
Decimal places in data

### ISSUE THREAD

**Issue by nmssalman** [AAChartModel/AAChartKit#1209]
when i use 2.20 as a value to display in bar charts, it shows 2.2 and 0 is missing, i want to show the full text without rounding it. anyone can help?

**Comment by AAChartModel** [comment]
aaOptions.yAxis.labels.format = @"{value:.2f}";

**Comment by nmssalman** [comment]
@AAChartModel still same. here is my code.

  ```
val aaChartView = findViewById<AAChartView>(R.id.gantt_chart_view)
        val charGenerate = configureColumnrangeChart(projectNames.toTypedArray(), dateData)
        val aaOptions = charGenerate.aa_toAAOptions()
        aaOptions.yAxis!!.labels!!.format = "{value:.2f}"
        aaChartView.aa_drawChartWithChartOptions(aaOptions)
```

**Comment by AAChartModel** [comment]
Can you post your completed AAOptions configuration code?

**Comment by nmssalman** [comment]
i need to set the options to data series in the chart.  not to axis labels.

![image](https://user-images.githubusercontent.com/10008304/125723753-f15ff5d6-d61d-43d5-93e9-8ac4e4e985b2.png)

**Comment by nmssalman** [comment]
@AAChartModel can i set a date string for series values instead of double type?

**Comment by nmssalman** [comment]
@AAChartModel can i get a reply please.
