### ISSUE TITLE
我pod导入的版本是pod 'AAChartKit', '~> 6.0.0'，为什么我找不到这个属性AALang.new;         .numericSymbolMagnitudeSet(@10000)

### ISSUE THREAD

**Issue by zhanghongdou** [AAChartModel/AAChartKit#1210]
我pod导入的版本是pod 'AAChartKit', '~> 6.0.0'，为什么我找不到这个属性AALang.new;         .numericSymbolMagnitudeSet(@10000)

AALang里面没有这个我需要的属性

**Comment by AAChartModel** [comment]
不要指定版本号, 直接更新到 git 的最新内容即可

**Comment by zhanghongdou** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 中午1:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





 
不要指定版本号, 直接更新到 git 的最新内容即可

**Comment by zhanghongdou** [comment]
为什么我把pod更新了，pod搜索到的最新版本依然是6.0.0，我要如何才能获取您发布的最新版本呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AAChartModel/AAChartKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 中午1:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod 'AAChartKit', '~&gt; 6.0.0'，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





 
不要指定版本号, 直接更新到 git 的最新内容即可

**Comment by AAChartModel** [comment]
```ruby
pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'
```

你的 cocoapods 的 AAChartKit 命令是像上面这么写的吗?

**Comment by zhanghongdou** [comment]
感谢大神，谢谢谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 下午3:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





 pod 'AAChartKit', :git =&gt; 'https://github.com/AAChartModel/AAChartKit.git'
 
你的 cocoapods 的 AAChartKit 命令是像上面这么写的吗?

**Comment by zhanghongdou** [comment]
好尴尬，换了这个最新的之后，很多图标第一次刷不出来了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 下午3:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





 pod 'AAChartKit', :git =&gt; 'https://github.com/AAChartModel/AAChartKit.git'
 
你的 cocoapods 的 AAChartKit 命令是像上面这么写的吗?

**Comment by zhanghongdou** [comment]
为什么首次渲染不出来了呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AAChartModel/AAChartKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod 'AAChartKit', '~&gt; 6.0.0'，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





 pod 'AAChartKit', :git =&gt; 'https://github.com/AAChartModel/AAChartKit.git'
 
你的 cocoapods 的 AAChartKit 命令是像上面这么写的吗?

**Comment by AAChartModel** [comment]
你能在你的 Git 版本控制系统中, 看到你更新前后的代码差异吗? 能看到具体前后有哪些代码的改动吗?

**Comment by zhanghongdou** [comment]
就是我导入git这个最新的之后，图表首次都不出来，除非我再点击一个按钮，主动去触发一次，他才会出来




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 下午3:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





 pod 'AAChartKit', :git =&gt; 'https://github.com/AAChartModel/AAChartKit.git'
 
你的 cocoapods 的 AAChartKit 命令是像上面这么写的吗?

**Comment by AAChartModel** [comment]
我觉得是 AACharKit 更新本身导致的问题的可能性不大,  你试试将 AAChartKit 的 demo 在你的机器中运行然后看看呢

**Comment by zhanghongdou** [comment]
这个看不到的，我代码没有接入git仓库，只是有个属性报错，我禁掉了，.crosshairsSet(true)//启用准星线


只有这一个属性报错了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 下午4:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





 
你能在你的 Git 版本控制系统中, 看到你更新前后的代码差异吗? 能看到具体前后有哪些代码的改动吗?

**Comment by AAChartModel** [comment]
> 除非我再点击一个按钮，主动去触发一次，他才会出来

在你点击按钮之前, 确定有调用绘图方法吗?

**Comment by zhanghongdou** [comment]
那就奇怪了，因为我没有改动其他任何代码，并不是一个图表不显示，而是所有的首次都不展示了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 下午4:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





 
我觉得是 AACharKit 更新本身导致的问题的可能性不大,  你试试将 AAChartKit 的 demo 在你的机器中运行然后看看呢

**Comment by zhanghongdou** [comment]
调用了的，这个我确定的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 下午4:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





  
除非我再点击一个按钮，主动去触发一次，他才会出来
  
在你点击按钮之前, 确定有调用绘图方法吗?

**Comment by AAChartModel** [comment]
在 debug 模式下, 在绘制图表或刷新图表之前都会在控制台打印 AAOptions 的 json 信息, 你能看到吗?

**Comment by zhanghongdou** [comment]
看到了，所有数值都打印出来了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 下午4:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





 
在 debug 模式下, 在绘制图表或刷新图表之前都会在控制台打印 AAOptions 的 json 信息, 你能看到吗?

**Comment by AAChartModel** [comment]
在你没有点击按钮的时候, 就直接打印出来了?

**Comment by zhanghongdou** [comment]
我看了，每个图标的json都打印了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 下午4:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





 
在 debug 模式下, 在绘制图表或刷新图表之前都会在控制台打印 AAOptions 的 json 信息, 你能看到吗?

**Comment by zhanghongdou** [comment]
对的，因为我是进入vc请求网络数据，然后直接渲染，显示图表，json都打印了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 下午4:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





 
在你没有点击按钮的时候, 就直接打印出来了?

**Comment by zhanghongdou** [comment]
但是我放一个按钮，点击再次渲染的话，就会显示出来






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AAChartModel/AAChartKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod 'AAChartKit', '~&gt; 6.0.0'，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





 
在你没有点击按钮的时候, 就直接打印出来了?

**Comment by AAChartModel** [comment]
那你直接把 AAChartKit 的 demo 中的 ViewController 拖进你项目中去试试呢?

**Comment by zhanghongdou** [comment]
我等下试试






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 下午4:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





 
那你直接把 AAChartKit 的 demo 中的 ViewController 拖进你项目中去试试呢?

**Comment by zhanghongdou** [comment]
这是为什么，我什么也没改，就是pod导入一次你说的那个，现在我回到6.0.0，首次也不展示，我有点摸不着头脑了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AAChartModel/AAChartKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod 'AAChartKit', '~&gt; 6.0.0'，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





 
那你直接把 AAChartKit 的 demo 中的 ViewController 拖进你项目中去试试呢?

**Comment by zhanghongdou** [comment]
我发现使用6.0.0依然是刚才git链接导入的那个版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 下午4:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





 
那你直接把 AAChartKit 的 demo 中的 ViewController 拖进你项目中去试试呢?

**Comment by AAChartModel** [comment]
> 我发现使用6.0.0依然是刚才git链接导入的那个版本


你估计要先删除, 再重新 pod 安装, 不然有可能其实没有更新

**Comment by zhanghongdou** [comment]
好的，我等下试试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 下午5:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





  
我发现使用6.0.0依然是刚才git链接导入的那个版本
  
你估计要先删除, 再重新 pod 安装, 不然有可能其实没有更新

**Comment by AAChartModel** [comment]
> 那你直接把 AAChartKit 的 demo 中的 ViewController 拖进你项目中去试试呢?

我觉得你应该先试试这个, 来验证是否是 AAChartKit 本身的问题

**Comment by zhanghongdou** [comment]
我换回6.0.0，就好了，直接就出来了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 下午5:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





  
那你直接把 AAChartKit 的 demo 中的 ViewController 拖进你项目中去试试呢?
  
我觉得你应该先试试这个, 来验证是否是 AAChartKit 本身的问题

**Comment by zhanghongdou** [comment]
大神，我稍后再尝试将你的demo拉进去试试，现在在赶进度，还有一个问题就是，对于条形图，他的最大宽度能设置吗，我没有找到配置的地方




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AAChartModel/AAChartKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 下午5:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod 'AAChartKit', '~&gt; 6.0.0'，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





  
那你直接把 AAChartKit 的 demo 中的 ViewController 拖进你项目中去试试呢?
  
我觉得你应该先试试这个, 来验证是否是 AAChartKit 本身的问题

**Comment by AAChartModel** [comment]
> 对于条形图，他的最大宽度能设置吗，我没有找到配置的地方

https://github.com/AAChartModel/AAChartKit/issues/537

**Comment by zhanghongdou** [comment]
这里这条线，我可以调整他的颜色吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月16日(星期五) 中午11:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





  
对于条形图，他的最大宽度能设置吗，我没有找到配置的地方
  
#537

**Comment by zhanghongdou** [comment]
你好，图表的x轴文本太长，我想默认最多显示四个字符，但是tooltip显示完整




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AAChartModel/AAChartKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月16日(星期五) 中午11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod 'AAChartKit', '~&gt; 6.0.0'，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





  
对于条形图，他的最大宽度能设置吗，我没有找到配置的地方
  
#537

**Comment by AAChartModel** [comment]
> 你好，图表的x轴文本太长，我想默认最多显示四个字符，但是tooltip显示完整


参考问题: https://github.com/AAChartModel/AAChartKit/issues/1217

**Comment by AAChartModel** [comment]
> 这里这条线，我可以调整他的颜色吗


不知道你说的是哪条线

**Comment by zhanghongdou** [comment]
非常感谢，前几天忙着没顾得回你消息，太感谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月19日(星期一) 中午11:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





  
你好，图表的x轴文本太长，我想默认最多显示四个字符，但是tooltip显示完整
  
参考问题: #1217

**Comment by zhanghongdou** [comment]
尴尬，上次图片没发出去，你看我下面这个截图











------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月19日(星期一) 中午11:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 我pod导入的版本是pod &#39;AAChartKit&#39;, &#39;~&gt; 6.0.0&#39;，为什么我找不到这个属性AALang.new;         .***@***.***) (#1210)





  
这里这条线，我可以调整他的颜色吗
  
不知道你说的是哪条线

**Comment by AAChartModel** [comment]
> 尴尬，上次图片没发出去，你看我下面这个截图


问题已解决.  https://github.com/AAChartModel/AAChartKit/issues/1222
