### ISSUE TITLE
您好！1.如何将x轴放在图表上方？2.如何改变图表x轴，以时间方式显示 3.如何实现一条基准线，滑动视图时显示数据

### ISSUE THREAD

**Issue by people990** [AAChartModel/AAChartKit#1213]
您好！1.如何将x轴放在图表上方？2.如何改变图表x轴，以时间方式显示 3.如何实现一条基准线，滑动视图时显示数据。 谢谢，望请告知。

<img width="264" alt="ScreenShot2021-07-16 17 40 19" src="https://user-images.githubusercontent.com/16828887/125927598-1d596884-25c0-47b5-ae80-8975f726b9c6.png">

**Comment by AAChartModel** [comment]
> 1.如何将x轴放在图表上方?

查看 AAXAxis 中的关键属性

//是否将坐标轴显示在对立面，默认情况下 x 轴是在图表的下方显示，y 轴是在左方，坐标轴显示在对立面后，
//x 轴是在上方显示，y 轴是在右方显示（即坐标轴会显示在对立面）。该配置一般是用于多坐标轴区分展示，
//另外在 Highstock 中，y 轴默认是在对立面显示的。 默认是：false.
AAPropStatementAndPropSetFuncStatement(assign, AAXAxis, BOOL,       opposite) 

demo 中有使用示例

**Comment by AAChartModel** [comment]
> 2.如何改变图表x轴，以时间方式显示 

查看 AAXAxis 中的关键属性

```objc
AAPropStatementAndPropSetFuncStatement(copy,   AAXAxis, AAChartAxisType, type)
```

其中 AAChartAxisType 所有类型如下

```objc
typedef NSString *AAChartAxisType;

static AAChartAxisType const AAChartAxisTypeLinear      = @"linear";//线性轴
static AAChartAxisType const AAChartAxisTypeLogarithmic = @"logarithmic";//对数轴
static AAChartAxisType const AAChartAxisTypeDatetime    = @"datetime";//时间轴
static AAChartAxisType const AAChartAxisTypeCategory    = @"category";//分类轴
```

**Comment by AAChartModel** [comment]
> 3.如何实现一条基准线，滑动视图时显示数据

AACrosshair 类可以实现基准线效果.
