### ISSUE TITLE
你好，我这里有条线不知道如何调整颜色

### ISSUE THREAD

**Issue by zhanghongdou** [AAChartModel/AAChartKit#1222]
![image](https://user-images.githubusercontent.com/16813719/126594896-d4b0e159-b789-4f47-8365-3842861b1c14.png)
请问这条线的颜色该如何调呢，没有找到调的地方

**Comment by AAChartModel** [comment]
```objc
AAPropStatementAndPropSetFuncStatement(strong, AAXAxis, NSNumber *, lineWidth) //x轴轴线宽度
AAPropStatementAndPropSetFuncStatement(copy,   AAXAxis, NSString *, lineColor) //x轴轴线线颜色
```

**Comment by AAChartModel** [comment]
使用示例 

```objc
    aaOptions.xAxis
    .lineColorSet(AAColor.whiteColor)
    .lineWidthSet(@2)
 
```

**Comment by zhanghongdou** [comment]
谢谢，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年7月22日(星期四) 下午2:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 你好，我这里有条线不知道如何调整颜色 (#1222)





 
使用示例
     aaOptions.xAxis     .lineColorSet(AAColor.whiteColor)     .***@***.***)
