### ISSUE TITLE
is there any support for drawing a candleStick chart!?

### ISSUE THREAD

**Issue by iamomidk** [AAChartModel/AAChartKit#1226]
hi im trying to draw a candle stick chart pleas help me out
thanks. ❤️

**Comment by AAChartModel** [comment]
AAChart do not support candleStick chart.

**Comment by iamomidk** [comment]
is there going to be any update for supporting it!?
should i wait or smth!?

**Comment by AAChartModel** [comment]
There is no need to wait it.

**Comment by iamomidk** [comment]
im closing this issue then
take care
