### ISSUE TITLE
请问，怎么让面积图顶着Y轴画呢？（如图）让面积图左边跟Y轴没有间隙

### ISSUE THREAD

**Issue by myDebugLife** [AAChartModel/AAChartKit#1227]
![截屏2021-08-05 下午3 02 52](https://user-images.githubusercontent.com/24728197/128307037-19f540d6-958f-420e-bc07-b868a7e6140c.png)

**Comment by AAChartModel** [comment]
重复问题, 参见 https://github.com/AAChartModel/AAChartKit/issues/937
