### ISSUE TITLE
折线图可以设置实线与虚线交替出现的效果吗？这种类型的图标怎么实现？

### ISSUE THREAD

**Issue by YangyangD** [AAChartModel/AAChartKit#1232]
折线图可以设置实线与虚线交替出现的效果吗？

我需要实现这样一个类型的图表

![WeChat5e3567a1b0c795df782c28738aca771e](https://user-images.githubusercontent.com/24688189/130039630-35690052-05a6-42cc-88ed-9268b76e6b2e.png)

应该怎么设置呢？

**Comment by AAChartModel** [comment]
重复问题, 参考 https://github.com/AAChartModel/AAChartKit/issues/34

**Comment by AAChartModel** [comment]
关键属性是 connectNulls

**Comment by YangyangD** [comment]
属性 connectNulls  设置为true之后，是用实线连接的

**Comment by YangyangD** [comment]
怎么改成虚线呢？

**Comment by AAChartModel** [comment]
> 关键属性是 connectNulls

不好意思, 说错了

**Comment by AAChartModel** [comment]
配置 AAChartModel

```objc
- (AAChartModel *)configureMixedLineChart {
    return AAChartModel.new
    .chartTypeSet(AAChartTypeLine)
    .subtitleSet(@"虚拟数据")
    .categoriesSet(@[
        @"Java", @"Swift", @"Python", @"Ruby", @"PHP", @"Go",
        @"C", @"C#", @"C++", @"Perl", @"R", @"MATLAB", @"SQL"
                   ])
    .yAxisTitleSet(@"摄氏度")
    .dataLabelsEnabledSet(true)
    .yAxisGridLineStyleSet([AALineStyle styleWithWidth:@0])
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"本专业")
        .dataSet(@[@45, @88, @49, @43, @65, @56, @47, @28, @49, @44, @89, @55])
        .zoneAxisSet(@"x")
        .colorSet((id)AAGradientColor.freshPapayaColor)
        .lineWidthSet(@5)
        .zonesSet(@[
            AAZonesElement.new
            .valueSet(@8)
            .dashStyleSet(AAChartLineDashStyleTypeDot)
                  ]),
        AASeriesElement.new
        .nameSet(@"所有专业")
        .colorSet((id)AAGradientColor.pixieDustColor)
        .lineWidthSet(@5)
        .dataSet(@[[NSNull null], [NSNull null], @100, @109, @89, [NSNull null], [NSNull null], @120, [NSNull null], [NSNull null], [NSNull null], [NSNull null]])
               ]);
}
```

## 最终图表
<img width="774" alt="截屏2021-08-19 下午6 40 09" src="https://user-images.githubusercontent.com/16357599/130060106-3aa0b28c-31a2-4c32-a255-c0fcfb2d6a59.png">

**Comment by AAChartModel** [comment]
其中起关键作用的内容是

```objc
        .zonesSet(@[
            AAZonesElement.new
            .valueSet(@8)
            .dashStyleSet(AAChartLineDashStyleTypeDot)
                  ]),
```

**Comment by YangyangD** [comment]
大神，我试了一下效果还是不对啊，如果是想要让上面那条折线图的109和120之间用虚线链接起来

或者是让下面那条折线图的45和88用实线连接起来，而且88和49之间仍然保持虚线连接的状态，是怎么设置的？

我看到
.zonesSet(@[
            AAZonesElement.new
            .valueSet(@8)
            .dashStyleSet(AAChartLineDashStyleTypeDot)
                  ]),
里面是一个数组，就想着在里面放两个对象，但是这样一来就只有最后一个是生效的

我对  .valueSet(@8) 中8的理解也就是：设置为几，在这个数字之后就用实线连接，数字之前就用虚线连接



如图
![WeChat136dfae4f6cb14e9c4e9c91a5d117e94](https://user-images.githubusercontent.com/24688189/130163287-ffab477a-052b-4160-9e63-89856b7fc000.png)

**Comment by AAChartModel** [comment]
修改 zones 的数组内容为

```objc
        .zonesSet(@[
            AAZonesElement.new
            .valueSet(@3)
            .dashStyleSet(AAChartLineDashStyleTypeDash),
            AAZonesElement.new
            .valueSet(@8)
            .dashStyleSet(AAChartLineDashStyleTypeDot)
                  ])
```

## 最终图表效果


<img width="827" alt="截屏2021-08-20 上午10 01 28" src="https://user-images.githubusercontent.com/16357599/130167416-1a695660-c6e8-4416-b04d-e8c76cb5e128.png">

**Comment by YangyangD** [comment]
好的，太感谢了，我在修改 zones 的数组内容的时候设置错类型了，非常感谢
