### ISSUE TITLE
双层嵌套饼图，如何将2个饼图设置不同的主题颜色

### ISSUE THREAD

**Issue by ZTXBEST** [AAChartModel/AAChartKit#1234]
如题，我想实现一个双层嵌套饼图，2个饼图的主题颜色不一致，但是colorsSet设置的是同一组主题色，请问怎么设置2组不同的主题色呐

**Comment by AAChartModel** [comment]
## 配置 AAChartModel

```objc
//https://github.com/AAChartModel/AAChartKit/issues/1234
- (AAChartModel *)doubleLayerDoubleColorsPieChart {
    return AAChartModel.new
    .chartTypeSet(AAChartTypePie)
    .titleSet(@"浏览器市场占比历史对比")
    .subtitleSet(@"无任何可靠依据的虚拟数据")
    .dataLabelsEnabledSet(false)//是否直接显示扇形图数据
    .yAxisTitleSet(@"摄氏度")
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"Past")
        .colorsSet(@[
            AARgbaColor(255, 0, 0, 1.0),
            AARgbaColor(255, 0, 0, 0.8),
            AARgbaColor(255, 0, 0, 0.6),
            AARgbaColor(255, 0, 0, 0.4),
            AARgbaColor(255, 0, 0, 0.2),
                   ])
        .dataLabelsSet(AADataLabels.new
                       .enabledSet(true)
                       .formatSet(@"<b>{point.name}</b>: {point.percentage:.1f} %")
                       .styleSet(AAStyleColor(AARgbaColor(255, 0, 0, 1.0))))
        .sizeSet((id)@"25%")//尺寸大小
        .innerSizeSet(@"20%")//内部圆环半径大小占比
        .borderWidthSet(@0)//描边的宽度
        .allowPointSelectSet(false)//是否允许在点击数据点标记(扇形图点击选中的块发生位移)
        .dataSet(@[
            @[@"Firefox Past",   @3336.2],
            @[@"Chrome Past",     @126.8],
            @[@"Safari Past",     @188.5],
            @[@"Opera Past",      @146.0],
            @[@"Others Past",     @223.0],
                 ]),
        AASeriesElement.new
        .nameSet(@"Now")
        .colorsSet(@[
            AARgbaColor(30, 144, 255, 1.0),
            AARgbaColor(30, 144, 255, 0.8),
            AARgbaColor(30, 144, 255, 0.6),
            AARgbaColor(30, 144, 255, 0.4),
            AARgbaColor(30, 144, 255, 0.2),
                   ])
        .dataLabelsSet(AADataLabels.new
                       .enabledSet(true)
                       .formatSet(@"<b>{point.name}</b>: {point.percentage:.1f} %")
                       .styleSet(AAStyleColor(AARgbaColor(30, 144, 255, 1.0))))
        .sizeSet((id)@"80%")//尺寸大小
        .innerSizeSet(@"45%")//内部圆环半径大小占比
        .borderWidthSet(@0)//描边的宽度
        .allowPointSelectSet(false)//是否允许在点击数据点标记(扇形图点击选中的块发生位移)
        .dataSet(@[
            @[@"Firefox Now",   @6926.8],
            @[@"Chrome Now",     @336.2],
            @[@"Safari Now",     @388.5],
            @[@"Opera Now",      @446.0],
            @[@"Others Now",     @223.0],
                 ])
               ]);
}

```
## 最终图表
<img width="629" alt="截屏2021-08-21 下午6 42 56" src="https://user-images.githubusercontent.com/16357599/130319296-045260ed-4957-4b11-b454-56d9bd871ac0.png">

**Comment by AAChartModel** [comment]
为 AASeriesElement 新增了关键属性 `colors`

```objc
AAPropStatementAndPropSetFuncStatement(strong, AASeriesElement, NSArray  *, colors)

```

修改 podfile 文件如下, 

```ruby
pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'

```

执行 pod 更新命令, 更新 AAChartKit 至最新内容, 即可使用 AASeriesElement 最新添加的属性 colors

**Comment by ZTXBEST** [comment]
> ## 配置 AAChartModel
> ```objc
> //https://github.com/AAChartModel/AAChartKit/issues/1234
> - (AAChartModel *)doubleLayerDoubleColorsPieChart {
>     return AAChartModel.new
>     .chartTypeSet(AAChartTypePie)
>     .titleSet(@"浏览器市场占比历史对比")
>     .subtitleSet(@"无任何可靠依据的虚拟数据")
>     .dataLabelsEnabledSet(false)//是否直接显示扇形图数据
>     .yAxisTitleSet(@"摄氏度")
>     .seriesSet(@[
>         AASeriesElement.new
>         .nameSet(@"Past")
>         .colorsSet(@[
>             AARgbaColor(255, 0, 0, 1.0),
>             AARgbaColor(255, 0, 0, 0.8),
>             AARgbaColor(255, 0, 0, 0.6),
>             AARgbaColor(255, 0, 0, 0.4),
>             AARgbaColor(255, 0, 0, 0.2),
>                    ])
>         .dataLabelsSet(AADataLabels.new
>                        .enabledSet(true)
>                        .formatSet(@"<b>{point.name}</b>: {point.percentage:.1f} %")
>                        .styleSet(AAStyleColor(AARgbaColor(255, 0, 0, 1.0))))
>         .sizeSet((id)@"25%")//尺寸大小
>         .innerSizeSet(@"20%")//内部圆环半径大小占比
>         .borderWidthSet(@0)//描边的宽度
>         .allowPointSelectSet(false)//是否允许在点击数据点标记(扇形图点击选中的块发生位移)
>         .dataSet(@[
>             @[@"Firefox Past",   @3336.2],
>             @[@"Chrome Past",     @126.8],
>             @[@"Safari Past",     @188.5],
>             @[@"Opera Past",      @146.0],
>             @[@"Others Past",     @223.0],
>                  ]),
>         AASeriesElement.new
>         .nameSet(@"Now")
>         .colorsSet(@[
>             AARgbaColor(30, 144, 255, 1.0),
>             AARgbaColor(30, 144, 255, 0.8),
>             AARgbaColor(30, 144, 255, 0.6),
>             AARgbaColor(30, 144, 255, 0.4),
>             AARgbaColor(30, 144, 255, 0.2),
>                    ])
>         .dataLabelsSet(AADataLabels.new
>                        .enabledSet(true)
>                        .formatSet(@"<b>{point.name}</b>: {point.percentage:.1f} %")
>                        .styleSet(AAStyleColor(AARgbaColor(30, 144, 255, 1.0))))
>         .sizeSet((id)@"80%")//尺寸大小
>         .innerSizeSet(@"45%")//内部圆环半径大小占比
>         .borderWidthSet(@0)//描边的宽度
>         .allowPointSelectSet(false)//是否允许在点击数据点标记(扇形图点击选中的块发生位移)
>         .dataSet(@[
>             @[@"Firefox Now",   @6926.8],
>             @[@"Chrome Now",     @336.2],
>             @[@"Safari Now",     @388.5],
>             @[@"Opera Now",      @446.0],
>             @[@"Others Now",     @223.0],
>                  ])
>                ]);
> }
> ```
> 
> ## 最终图表
> <img alt="截屏2021-08-21 下午6 42 56" width="100%" src="https://user-images.githubusercontent.com/16357599/130319296-045260ed-4957-4b11-b454-56d9bd871ac0.png">

嗯呐，这个昨天搞出来了，但是现在遇到一个问题，我在hightcharts网站上看到，highcharts饼图是支持connectColor的，还可以设置那条线是虚线，但是oc版本的不支持，这个有没有什么方案可以实现呐

**Comment by ZTXBEST** [comment]
> 为 AASeriesElement 新增了关键属性 `colors`
> 
> ```objc
> AAPropStatementAndPropSetFuncStatement(strong, AASeriesElement, NSArray  *, colors)
> ```
> 
> 修改 podfile 文件如下,
> 
> ```ruby
> pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'
> ```
> 
> 执行 pod 更新命令, 更新 AAChartKit 至最新内容, 即可使用 AASeriesElement 最新添加的属性 colors

就是最终的实现效果是这样的
![image](https://user-images.githubusercontent.com/15209276/130319447-54cc293f-f471-44be-9450-d8dca64c261b.png)

**Comment by AAChartModel** [comment]
>  highcharts饼图是支持connectColor的

参考 https://github.com/AAChartModel/AAChartKit/issues/1236

**Comment by AAChartModel** [comment]
> 还可以设置那条线是虚线

由于 Highcharts 不支持通过 Options 直接配置 connector 为虚线样式. 

 参考这个在线使用示例 https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/css/pie-point/

由上在线示例可以看出, Highcharts 支持通过 CSS 来设置 connector 为虚线样式

在 AAChartKit 中想要实现同样的效果, 你需要像如下操作

<img width="1138" alt="截屏2021-08-21 下午7 56 28" src="https://user-images.githubusercontent.com/16357599/130320933-ecaaed61-0209-4196-8251-67cd6b7bae41.png">


也就是说要添加这部分内容到你的 AAChartKit.html 文件当中 

**添加 CSS 支持文件**
```html
        <script src="https://code.highcharts.com/css/highcharts.css"></script>
```
添加 CSS 设置内容

```css
            .highcharts-pie-series .highcharts-data-label-connector {
                stroke: gray;
                stroke-dasharray: 2, 2;
                stroke-width: 2px;
            }
```

修改之后的 AAChartView.html 文件的这部分内容为

```html
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width = device-width, initial-scale = 1.0, minimum-scale = 1.0, maximum-scale = 3.0,user-scalable = no,viewport-fit = cover">
        <script src="AAHighcharts.js"></script>
        <script src="AAHighcharts-More.js"></script>
        <script src="AAFunnel.js"></script>
        <script src="AAEasing.js"></script>
        <script src="AARounded-Corners.js"></script>
        <script src="https://code.highcharts.com/css/highcharts.css"></script>

<!--        <script src="https://code.highcharts.com/highcharts.js"></script>-->
<!--        <script src="https://code.highcharts.com/highcharts-more.js"></script>-->
<!--        <script src="https://code.highcharts.com/modules/funnel.js"></script>-->
        <style>
            *{ -webkit-user-select: none; 
                user-select: none; }
            .highcharts-pie-series .highcharts-data-label-connector {
                stroke: gray;
                stroke-dasharray: 2, 2;
                stroke-width: 2px;
            }
        </style>
    </head>
    <body style="margin:0px 0px 0px 0px;">
        <div id="container" style="width:100%; height: 100%;">
        </div>
        <script>
        var aaGlobalChart;
```

**Comment by AAChartModel** [comment]
在 AAChartKit 中想要实现同样的效果, 目前我能想到的办法是, 你需要像如下操作



## 你要添加这部分内容到你的 AAChartKit.html 文件当中 

**添加 CSS 支持文件**
```html
        <script src="https://code.highcharts.com/css/highcharts.css"></script>
```
**添加 CSS 设置内容**

```css
            .highcharts-pie-series .highcharts-data-label-connector {
                stroke: gray;
                stroke-dasharray: 2, 2;
                stroke-width: 2px;
            }
```

## 修改之后的 AAChartView.html 文件的这部分内容为

```html
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width = device-width, initial-scale = 1.0, minimum-scale = 1.0, maximum-scale = 3.0,user-scalable = no,viewport-fit = cover">
        <script src="AAHighcharts.js"></script>
        <script src="AAHighcharts-More.js"></script>
        <script src="AAFunnel.js"></script>
        <script src="AAEasing.js"></script>
        <script src="AARounded-Corners.js"></script>
        <script src="https://code.highcharts.com/css/highcharts.css"></script>

<!--        <script src="https://code.highcharts.com/highcharts.js"></script>-->
<!--        <script src="https://code.highcharts.com/highcharts-more.js"></script>-->
<!--        <script src="https://code.highcharts.com/modules/funnel.js"></script>-->
        <style>
            *{ -webkit-user-select: none; 
                user-select: none; }
            .highcharts-pie-series .highcharts-data-label-connector {
                stroke: gray;
                stroke-dasharray: 2, 2;
                stroke-width: 2px;
            }
        </style>
    </head>
    <body style="margin:0px 0px 0px 0px;">
        <div id="container" style="width:100%; height: 100%;">
        </div>
        <script>
        var aaGlobalChart;
```

<img width="1138" alt="截屏2021-08-21 下午7 56 28" src="https://user-images.githubusercontent.com/16357599/130320933-ecaaed61-0209-4196-8251-67cd6b7bae41.png">

**Comment by ZTXBEST** [comment]
> 在 AAChartKit 中想要实现同样的效果, 目前我能想到的办法是, 你需要像如下操作
> 
> ## 你要添加这部分内容到你的 AAChartKit.html 文件当中
> **添加 CSS 支持文件**
> 
> ```
>         <script src="https://code.highcharts.com/css/highcharts.css"></script>
> ```
> 
> **添加 CSS 设置内容**
> 
> ```css
>             .highcharts-pie-series .highcharts-data-label-connector {
>                 stroke: gray;
>                 stroke-dasharray: 2, 2;
>                 stroke-width: 2px;
>             }
> ```
> 
> ## 修改之后的 AAChartView.html 文件的这部分内容为
> ```
> <html>
>     <head>
>         <meta charset="UTF-8" />
>         <meta name="viewport" content="width = device-width, initial-scale = 1.0, minimum-scale = 1.0, maximum-scale = 3.0,user-scalable = no,viewport-fit = cover">
>         <script src="AAHighcharts.js"></script>
>         <script src="AAHighcharts-More.js"></script>
>         <script src="AAFunnel.js"></script>
>         <script src="AAEasing.js"></script>
>         <script src="AARounded-Corners.js"></script>
>         <script src="https://code.highcharts.com/css/highcharts.css"></script>
> 
> 
> 
> 
>         <style>
>             *{ -webkit-user-select: none; 
>                 user-select: none; }
>             .highcharts-pie-series .highcharts-data-label-connector {
>                 stroke: gray;
>                 stroke-dasharray: 2, 2;
>                 stroke-width: 2px;
>             }
>         </style>
>     </head>
>     <body style="margin:0px 0px 0px 0px;">
>         <div id="container" style="width:100%; height: 100%;">
>         </div>
>         <script>
>         var aaGlobalChart;
> ```
> 
> <img alt="截屏2021-08-21 下午7 56 28" width="1138" src="https://user-images.githubusercontent.com/16357599/130320933-ecaaed61-0209-4196-8251-67cd6b7bae41.png">

非常感谢老哥的指点，🤝
