### ISSUE TITLE
自定义饼图的 connector 连接线

### ISSUE THREAD

**Issue by AAChartModel** [AAChartModel/AAChartKit#1236]

**Comment by AAChartModel** [comment]
为 AADataLabel 新增了属性

```objc
AAPropStatementAndPropSetFuncStatement(copy,   AADataLabels, NSString *, connectorColor)
AAPropStatementAndPropSetFuncStatement(strong, AADataLabels, NSNumber *, connectorPadding)
AAPropStatementAndPropSetFuncStatement(copy,   AADataLabels, NSString *, connectorShape)
AAPropStatementAndPropSetFuncStatement(strong, AADataLabels, NSNumber *, connectorWidth)
AAPropStatementAndPropSetFuncStatement(copy,   AADataLabels, NSString *, crookDistance)
```

在线文档

https://api.highcharts.com/highcharts/plotOptions.pie.dataLabels.connectorColor

**Comment by ZTXBEST** [comment]
> 为 AADataLabel 新增了属性
> 
> ```objc
> AAPropStatementAndPropSetFuncStatement(copy,   AADataLabels, NSString *, connectorColor)
> AAPropStatementAndPropSetFuncStatement(strong, AADataLabels, NSNumber *, connectorPadding)
> AAPropStatementAndPropSetFuncStatement(copy,   AADataLabels, NSString *, connectorShape)
> AAPropStatementAndPropSetFuncStatement(strong, AADataLabels, NSNumber *, connectorWidth)
> AAPropStatementAndPropSetFuncStatement(copy,   AADataLabels, NSString *, crookDistance)
> ```
> 
> 在线文档
> 
> https://api.highcharts.com/highcharts/plotOptions.pie.dataLabels.connectorColor

这个是还没更新上去吗，我看最新的版本里还没connector这些属性

**Comment by AAChartModel** [comment]
> 这个是还没更新上去吗，我看最新的版本里还没connector这些属性

不好意思, 最近 GitHub push代码, 经常 443 错误, 这下提交成功了, 提交地址为 https://github.com/AAChartModel/AAChartKit/commit/4a864b6202ec34515615b0a23ddcfacb11eb5013
