### ISSUE TITLE
曲线图---线的宽度不一样，怎么解决？

### ISSUE THREAD

**Issue by 77521** [AAChartModel/AAChartKit#1240]
数据为  0，0，2，0，0，0，5的时候，0和0之间的连线宽度  和 曲线的0-2的曲线宽度不一样  
![WechatIMG1](https://user-images.githubusercontent.com/18029525/131313692-43adce01-5842-4827-b827-841b24aa2673.png)
怎么解决呢

**Comment by AAChartModel** [comment]
这大概是因为在 Highcharts 底层绘图中, 曲线线条被 X轴的轴线遮挡了

**Comment by AAChartModel** [comment]
你试试修改一下AASeriesElement 的 threshold(基准线)的值, 看看是否有效

**Comment by AAChartModel** [comment]
参考在线文档 https://api.highcharts.com.cn/highcharts#series%3Carea%3E.threshold

**Comment by 77521** [comment]
可以了  谢谢了

**Comment by 77521** [comment]
你好 现在  还有这个问题  怎么解决呢
