### ISSUE TITLE
（真机）曲线图-空心的圆点选中时多出两条线

### ISSUE THREAD

**Issue by stonesun1314** [AAChartModel/AAChartKit#1241]
真机的曲线图的空心圆点会多出两条线
![WeChatba227fee7db9e573b9fbbe5582bb6163](https://user-images.githubusercontent.com/1740938/131321076-31b8c06e-b778-4b50-bf1c-bc145f90c60c.png)
@AAChartModel

**Comment by stonesun1314** [comment]
![EC82404D-5094-48F0-BB63-29B437FB2570](https://user-images.githubusercontent.com/1740938/131323911-bd6babb2-74dd-4195-b829-121c85b0d96e.png)

**Comment by AAChartModel** [comment]
这个问题不好弄, 似乎是新版 WebKit 的 bug,  参考 https://github.com/highcharts/highcharts/issues/14424

**Comment by AAChartModel** [comment]
参考 https://github.com/AAChartModel/AAChartKit/issues/1070

**Comment by AAChartModel** [comment]
参考 https://bugs.webkit.org/show_bug.cgi?id=218181   

> This is a bug in a framework below WebKit.
> This will be fixed via a system software change.

在最新版本的 iOS 系统中应该没有这个问题了

**Comment by stonesun1314** [comment]
> 参考 https://bugs.webkit.org/show_bug.cgi?id=218181
> 
> > This is a bug in a framework below WebKit.
> > This will be fixed via a system software change.
> 
> 在最新版本的 iOS 系统中应该没有这个问题了

谢谢，大佬。
