### ISSUE TITLE
x轴右下侧标题怎么显示？

### ISSUE THREAD

**Issue by Magician-93** [AAChartModel/AAChartKit#1242]
大神，可以问下x轴文字隐藏后，x轴的标题怎么显示在列表的最右侧？就是在x轴的右下方。
看你demo中是通过
```objc
AAOptions *aaOptions = chartConfiguration;
        aaOptions.credits
        .enabledSet(true)
        .textSet(@"xxxxxxxx")
        .hrefSet(@"")
        .styleSet(AAStyle.new
                  .colorSet(AAColor.redColor)
                  .fontSizeSet(@"9px"));
```
我这样设置后没效果，不显示。

**Comment by AAChartModel** [comment]
你说的是图表的版权信息内容吧, 你断点看看你的 ` aaOptions.credits` 是否为空呢?

**Comment by Magician-93** [comment]
不为空，其他设置的属性都有效果，贴下代码：
AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aacharModel];
    aaOptions
    .yAxisSet(aaYAXis)
    .xAxisSet(aaXAxis)
    .tooltip
    .backgroundColorSet(@"rgba(0,0,0,0.8)")
    .borderColorSet(@"rgba(0,0,0,0.5)")
    .styleSet(AAStyleColorSize(@"#CCCCCC", 13))
    .pointFormatSet(@"<span style=""font-weight: bold; color: {series.color}"">{series.name}</span><b>{point.y}</b> ");
    return aaOptions;

**Comment by Magician-93** [comment]
<img width="444" alt="截屏2021-09-15 下午2 24 22" src="https://user-images.githubusercontent.com/17924034/133381468-0455fd93-b6c3-46f2-9f84-5425a0dca1c0.png">

**Comment by Magician-93** [comment]
近30日训练  这个字怎么显示

**Comment by AAChartModel** [comment]
参考 https://github.com/AAChartModel/AAChartKit/issues/1055

**Comment by Magician-93** [comment]
可以x轴标题设置偏移吧。框架很赞👍🏻 nb
