### ISSUE TITLE
雷达图pointPlacement = @"on", yAxis.gridLine错位，并且多了根线。demo试了也是这样。

### ISSUE THREAD

**Issue by hhw2020** [AAChartModel/AAChartKit#1245]
设置了categories后，雷达图错位。当我设置了pointPlacement = @"on"，雷达图正了。

但是yAxis.gridLine错位了，并且量化能力垂直那条线不知是从哪来的。

当我尝试legendEnabled = YES 反选掉后。这条垂直线依然在。

用demo的那个六边形雷达图试了下，是一样的。

<img width="902" alt="wecom-temp-03b5d822121c39037e6d550021413d54" src="https://user-images.githubusercontent.com/11314875/132668460-84321c8c-d7f8-4cad-990d-09c60a5908c3.png">

<img width="902" alt="wecom-temp-36dbb2ed51f14a50739461695bf2e040" src="https://user-images.githubusercontent.com/11314875/132668571-3d7fb6fe-3bad-4fdb-ae29-6b7442ea9399.jpg">

<img width="902" alt="wecom-temp-0e476c6ffd249f4d365fd23efda63a2c" src="https://user-images.githubusercontent.com/11314875/132671648-dfd35f54-d2aa-4c4d-9c1a-3a5867330fdf.jpg">

**Comment by hhw2020** [comment]
线错位的，aaOptions.xAxis.tickmarkPlacement = @"on"; 解决了。
但是竖向多出来那个线，一直没找到原因。demo也是一样

**Comment by AAChartModel** [comment]
多出来的那个估计是 Y轴的轴线, 你设置一下 Y 轴的轴线宽度为 0 ,试试看能否解决这个问题

**Comment by hhw2020** [comment]
> 多出来的那个估计是 Y轴的轴线, 你设置一下 Y 轴的轴线宽度为 0 ,试试看能否解决这个问题

aaOptions.yAxis.lineWidth = @0;
ok了，感谢作者。
