### ISSUE TITLE
bundle文件集成后是空的

### ISSUE THREAD

**Issue by qipei** [AAChartModel/AAChartKit#1246]
podspec文件应该改成s.resource_bundles = { 'AAChartKitLib' => 'AAChartKitLib/AAJSFiles.bundle/\*.\*' }

**Comment by AAChartModel** [comment]
```ruby

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tesssst

    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0'
    pod 'AAChartKit', '6.0.0'

end
```

我测试了这样导入  `AAChartKit`, bundle 文件正常啊

**Comment by AAChartModel** [comment]
<img width="969" alt="截屏2021-09-13 上午11 16 22" src="https://user-images.githubusercontent.com/16357599/133018817-f5ae866b-d725-476c-b86d-1fb84085f5f2.png">
