### ISSUE TITLE
new Chart( [renderTo], options, [callback]) 怎么传入callback

### ISSUE THREAD

**Issue by STDawn** [AAChartModel/AAChartKit#1249]
new Chart( [renderTo], options [, callback]) 怎么传入callback

**Comment by AAChartModel** [comment]
```
new Chart( [renderTo], options [, callback])
```
你这个代码是哪里来的, 看着不像是 JS 或者是 OC 的代码啊

**Comment by STDawn** [comment]
highcharts 的 构建函数， 
var charts = Highcharts.chart('container', {
  // Highcharts 配置
}, function(c){});
