### ISSUE TITLE
无用代码，项目报错

### ISSUE THREAD

**Issue by BinBear** [AAChartModel/AAChartKit#1250]
![image](https://user-images.githubusercontent.com/13587915/133762148-1754c580-4c9e-452a-9d06-caf6bba22a11.png)

作者有点不严谨啊，代码都无法跑起来就push上去了，而且cocoapod引入的话，只有指定地址才能获取最新版本，上面这个问题还不能回滚版本

**Comment by AAChartModel** [comment]
不好意思, 我之前本地 AAChartView.m 文件中有很长一段本地测试代码, 我在提交 demo 代码的改动的时候, 每次都会避开`AAChartView.m`文件.  不知道是我操作有误还是本地的 GitHub Desktop 有 bug, 很奇怪地昨天就额外交了这一行测试代码.

现已修复此问题.
