### ISSUE TITLE
请问这种热力图支不支持？

### ISSUE THREAD

**Issue by NSMichael** [AAChartModel/AAChartKit#1252]
https://www.highcharts.com.cn/demo/highcharts/heatmap/sand-signika
官方效果图我看是有的，请问大佬支不支持这种

![image](https://user-images.githubusercontent.com/3736158/134530119-6dd03283-c38d-4c5b-8460-0a17a38d128d.png)

**Comment by AAChartModel** [comment]
参考 `AAChartKit-Pro` 中的使用示例.

* https://github.com/AAChartModel/AAChartKit
