### ISSUE TITLE
请问？柱状图设置柱子最小宽度，随数据的增多，x 轴左右滑动怎么实现

### ISSUE THREAD

**Issue by zhufaming** [AAChartModel/AAChartKit#1256]
![image](https://user-images.githubusercontent.com/15395337/135372711-221e89c6-d73e-4681-928b-64d98ebfc1c8.png)
像这种，只有一条数据的时候，柱子太宽，数据太多，柱子又成了一根细线，很难受

**Comment by AAChartModel** [comment]
> 柱状图设置柱子最小宽度

间接设置柱状图宽度, 参考:

* https://github.com/AAChartModel/AAChartKit/issues/537

**Comment by AAChartModel** [comment]
> x 轴左右滑动怎么实现

参考 **demo** 中的 `AAScrollablePlotArea` 使用示例.
