### ISSUE TITLE
tooltip是否支持点击 自动消失

### ISSUE THREAD

**Issue by xintenggiegie** [AAChartModel/AAChartKit#1259]
点图表弹出tooltip，需求是点下tooltip 自动消失，可以实现这个功能吗

**Comment by lhpkxywm** [comment]
同问，我也需要这个，请问你解决了吗？

**Comment by xintenggiegie** [comment]
> 同问，我也需要这个，请问你解决了吗？

没有，我也不需要了。

**Comment by wtg934614282** [comment]
点击 tooltip 有没有事件啊

**Comment by AAChartModel** [comment]
> 点击 tooltip 有没有事件啊

* https://api.highcharts.com/highcharts/tooltip

我从官方文档中, 也没有查询到有支持 tooltip 点击事件的接口. 

目前我能想到的解决方案就只能是:

* 通过获取获取 AAChartView 的滑动事件中的坐标, 来自绘原生的 tooltip
* 为自绘的 tooltip 添加点击事件
