### ISSUE TITLE
how to set x axis data in line chart

### ISSUE THREAD

**Issue by showkeyjar** [AAChartModel/AAChartKit#1263]
I know this question is very basic, 

but I can not find any useful information in documents and issues.

In example there is only area data series, but I don't know how to specific x axis data in line chart.

please help!

**Comment by AAChartModel** [comment]
```objc
//x轴坐标每个点对应的名称(注意:这个不是用来设置 X 轴的值,仅仅是用于设置 X 轴文字内容的而已)
AAPropStatementAndPropSetFuncStatement(strong, AAChartModel, NSArray     <NSString *>*, categories) 

```
