### ISSUE TITLE
数值不连续的柱状图怎么配置

### ISSUE THREAD

**Issue by Ox8BADFOOD** [AAChartModel/AAChartKit#1265]
数值不连续的柱状图怎么配置

**Comment by AAChartModel** [comment]
## 配置 AAChartModel

```objc
- (AAChartModel *)setUpDiscontinuousDataChart {
    return AAChartModel.new
    .chartTypeSet(AAChartTypeColumn)
    .dataLabelsEnabledSet(true)//是否显示值
    .tooltipEnabledSet(true)
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"所有专业")
        .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2, [NSNull null], [NSNull null], [NSNull null], [NSNull null], @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6,])
        .colorSet((id)[AAGradientColor deepSeaColor])
               ]);
}
```

**Comment by AAChartModel** [comment]
参考 
* https://github.com/AAChartModel/AAChartKit/issues/809

**Comment by AAChartModel** [comment]
```objc
        .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2, [NSNull null], [NSNull null], [NSNull null], [NSNull null], @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6,])

```

由上可知, 空数据, 用`NSNull`实例对象占位即可.

**Comment by Ox8BADFOOD** [comment]
![image](https://user-images.githubusercontent.com/20883315/141968881-8e3095f3-72ab-4bfa-8370-37b12da5adea.png)
我想做成这种效果，红色的在一排，青色的在一排，蓝色的在一排，期望能提供建议，十分感谢

**Comment by AAChartModel** [comment]
你需要的这个是条码图, 参考:

* https://github.com/AAChartModel/AAChartKit-Pro/issues/1

**Comment by AAChartModel** [comment]
基础版本的 AAChartKit 不支持此类图表, 也就是说, 需要使用 Pro 版本的 AAChartKit, 链接🔗地址:

https://github.com/AAChartModel/AAChartKit-Pro

**Comment by AAChartModel** [comment]
一下是 Pro 版本的条码图效果

![Simulator Screen Shot - iPhone 13 Pro Max - 2021-11-16 at 18 55 54](https://user-images.githubusercontent.com/16357599/141973418-166383d7-8548-4d49-af39-0d44c4db3ffe.png)

![Simulator Screen Shot - iPhone 13 Pro Max - 2021-11-16 at 18 55 58](https://user-images.githubusercontent.com/16357599/141973466-2e43e73f-48d6-4a77-932d-3336c9576e99.png)

**Comment by AAChartModel** [comment]
不过这里有个坑, 数据量如果过大(超过 1000 个), 图表无法正常显示, 你可以斟酌使用.
