### ISSUE TITLE
有没有办法做出这样的效果?

### ISSUE THREAD

**Issue by shuyunidexiaodingdang** [AAChartModel/AAChartKit#1266]
![20211117160527](https://user-images.githubusercontent.com/16335766/142161415-d683f800-56b6-4df4-93ac-4d094db6c010.jpg)

**Comment by shuyunidexiaodingdang** [comment]
主要是虚线部分的做法

**Comment by AAChartModel** [comment]
重复问题, 参考
* https://github.com/AAChartModel/AAChartKit/issues/1232
