### ISSUE TITLE
求救：柱状图 怎么显示两位小数 图上的显示太多了

### ISSUE THREAD

**Issue by 77521** [AAChartModel/AAChartKit#1268]
![1637684488630](https://user-images.githubusercontent.com/18029525/143064453-d5e7c8b8-fccf-452a-8abe-da21a255207e.jpg)
AAChartModel *aaChartModel = AAChartModel.new
    .stackingSet(AAChartStackingTypeNormal)
    .chartTypeSet(AAChartTypeColumn)//图表类型
    .yAxisMaxSet(@(max))
//    .yAxisTickPositionsSet(@[@(0),@(2),@(4),@(6),@(8),@(10)])
    .borderRadiusSet(@9)
    .yAxisLineWidthSet(0)
    .legendEnabledSet(false)
    .yAxisTickIntervalSet(@(TickInterval))
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"")
        .colorSet((id)gradientColorDic1)
        .dataSet(fiveModel.valueArr)
        .dataLabelsSet(AADataLabels.new
                       .enabledSet(YES)
    
                       .styleSet(AAStyle.new
                                 .colorSet(@"#797979")
                                 .fontSizeSet(@"10px")
                                 .fontWeightSet(AAChartFontWeightTypeRegular)
                                 )
                       )
        ]);
    
    AAOptions *aaOptions = aaChartModel.aa_toAAOptions;
    aaOptions.touchEventEnabled = NO;
    aaOptions.yAxis.gridLineDashStyle = AAChartLineDashStyleTypeLongDash;//设置Y轴的网格线样式为 AAChartLineDashStyleTypeLongDash
    aaOptions.yAxis.gridLineWidth = @(1);
    aaOptions.plotOptions.series.dataLabels
    .allowOverlapSet(true)//允许字符重叠
    .formatSet(@"point.y:.2f") //保留二位小数
    ;
    aaOptions.tooltip
        .useHTMLSet(true)
        .formatterSet(@"{point.y:.2f}");
    aaOptions.xAxis
    .tickWidthSet(@0)//X轴刻度线宽度
    .lineWidthSet(@0)//X轴轴线宽度
    ;

    aaOptions.xAxis
    .labels.styleSet(AAStyleColorSize(@"#797979", 10.0))
    .formatterSet(xAxisLabelsFormatter);

    aaOptions.yAxis
    .labels.styleSet(AAStyleColorSize(@"#c3c3c3", 10.0));

    
    if (fiveModel.isFiveAnimationShow) {
        aaOptions.plotOptions.series.animation = (id)@false;//禁用图表的渲染动画效果
    }
    AAColumn *aaColumn = aaOptions.plotOptions.column;
    aaColumn.groupPadding = @0.05;
//    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
//    });
    [self.chartView aa_drawChartWithOptions:aaOptions];

**Comment by AAChartModel** [comment]
参考相似问题:

* https://github.com/AAChartModel/AAChartKit/issues/884
* https://github.com/AAChartModel/AAChartKit/issues/1267

**Comment by AAChartModel** [comment]
至于柱状图的 dataLabels 自定义, 参考在线文档
* https://api.highcharts.com.cn/highcharts/plotOptions.column.dataLabels.format.html
