### ISSUE TITLE
请问支不支持树状图

### ISSUE THREAD

**Issue by WolvesWang** [AAChartModel/AAChartKit#1278]

**Comment by AAChartModel** [comment]
Pro 版本的 AAChartKit 中支持树状图

* https://github.com/AAChartModel/AAChartKit-Pro

**Comment by WolvesWang** [comment]
非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2022年1月11日(星期二) 上午9:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartKit] 请问支不支持树状图 (Issue #1278)





 
Pro 版本的 AAChartKit 中支持树状图
  
https://github.com/AAChartModel/AAChartKit-Pro
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
