### ISSUE TITLE
如何能绘制出标准正态分布图

### ISSUE THREAD

**Issue by ShaochongDu** [AAChartModel/AAChartKit#1280]
![image](https://user-images.githubusercontent.com/16948310/149133052-9e08aefe-4526-4592-bd48-e92fb4be77f5.png)

ru'h如何才能绘制出上图中这种标准左右对称的正态分布图呢

**Comment by AAChartModel** [comment]
参考 Pro 版本中的使用示例:

* https://github.com/AAChartModel/AAChartKit-Pro

**Comment by AAChartModel** [comment]
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-29 at 18 56 25](https://user-images.githubusercontent.com/16357599/187186164-4565d920-9149-452c-ad4d-7680b4efde51.png)
