### ISSUE TITLE
怎么屏蔽掉点击时，其他部分的半透明效果

### ISSUE THREAD

**Issue by PiggyChen** [AAChartModel/AAChartKit#1281]
像下面的饼图，点击某一部分时，其他部分就会自动变成半透明，怎么屏蔽掉这半透明的效果（也就是点击时，其他部分不处理成半透明）

![Simulator Screen Shot - iPhone 11 Pro - 2022-01-23 at 17 34 57](https://user-images.githubusercontent.com/25243068/150672610-e1aa8473-1c56-4a37-9d61-76ea7c37d447.png)

**Comment by AAChartModel** [comment]
重复问题, 参考 
* https://github.com/AAChartModel/AAChartKit/issues/949
