### ISSUE TITLE
可拖拽图表1和2，页面都是空的

### ISSUE THREAD

**Issue by Hiphone-Du** [AAChartModel/AAChartKit#1283]
demo工程，Drawable Chart 可拖拽图表1和2页面都是空的，请问怎么回事？你们都没遇到吗

**Comment by AAChartModel** [comment]
demo 中的问题已在 https://github.com/AAChartModel/AAChartKit/commit/439e7501c3ac3997827b2fd61e954cb3e6b1d2bd 此次提交中修复.
