### ISSUE TITLE
在Android的BUILD_TYPE為debug模式時可以正常顯示,Release模式下會只有右下角有出現highcharts.com的文字

### ISSUE THREAD

**Issue by shadow9heaven** [AAChartModel/AAChartKit#1286]
如題
經測試在build.gradle 裡 android build_type中的  minifyEnabled參數為 true的時候會發生無法顯示AAchart的情況

```groovy
     buildTypes {
        debug {
            applicationIdSuffix '.debug'
            buildConfigField "String", "version", "\"debug\""
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled true
            //shrinkResources true
            buildConfigField "String", "version", "\"release\""
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
```

**Comment by AAChartModel** [comment]
有可能是代码混淆造成的吧, 参考此问题

* https://github.com/AAChartModel/AAChartCore/issues/97

**Comment by shadow9heaven** [comment]
在proguard-rules.pro中增加以下代碼後  可以正常顯示了
-keep class xxx.aachartmodel.aainfographics.aachartcreator.*{*;}
-keep class xxx.aachartmodel.aainfographics.aaoptionsmodel.*{*;}
-keep class xxx.aachartmodel.aainfographics.aatools.*{*;}
