### ISSUE TITLE
How to set tooltip position on the top of each bar column range

### ISSUE THREAD

**Issue by konotori** [AAChartModel/AAChartKit#1290]
Hey guys, i want to know how to set tooltip position on the top of each bar column range? Please help me, thank you!!

**Comment by AAChartModel** [comment]
Maybe this issue will be useful for you

* https://github.com/AAChartModel/AAChartKit/issues/966

**Comment by AAChartModel** [comment]
online doc:
* https://api.highcharts.com/highcharts/tooltip.positioner
