### ISSUE TITLE
marker

### ISSUE THREAD

**Issue by liujunliuhong** [AAChartModel/AAChartKit#1292]
当采用Point的形式来显示折线图时，期望显示所有点的marker，但是却发现marker没有显示，除非点击了某个点，有办法让其显示吗？

```swift
let element = AASeriesElement()
element.data = [[0, 200], [0, 300], [0, 400], [1, 100], [2, 120], [3, 130]]
```

Swift版本貌似有这个问题，OC版本没这个问题

**Comment by AAChartModel** [comment]
问题已解决, 参考

* https://github.com/AAChartModel/AAChartKit-Swift/issues/344

**Comment by AAChartModel** [comment]
```ruby
pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'
```

更新 **AAChartKit-Swift** 的 pod 的至最新内容即可.

**Comment by AAChartModel** [comment]
查看此次提交

* https://github.com/AAChartModel/AAChartKit-Swift/commit/9b6c25bbbd982c97e5bd99b805b516b8f403b36c


可知, 主要是在 **AAChartKit-Swift** 中, 为 AAMarker 添加了 enabled 属性, 并设置默认值为 true

**Comment by liujunliuhong** [comment]
多谢
