### ISSUE TITLE
如何更改scrollablePlotArea的minWidth

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1298]
需求是通过更改scrollablePlotArea的minWidth，动态的扩大视图的滚动范围

**Comment by AAChartModel** [comment]
可以试试 AAChartView 的这个方法

```objc
/// Update the X axis Extremes
/// @param min X axis minimum
/// @param max X axis maximum
- (void)aa_updateXAxisExtremesWithMin:(NSUInteger)min max:(NSUInteger)max;
```

demo 中有使用示例

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-03-29 at 09 17 20](https://user-images.githubusercontent.com/16357599/160513113-dd94ca6c-888d-49b6-9c9b-75c95e106b02.png)


![Simulator Screen Shot - iPhone 13 Pro Max - 2022-03-29 at 09 16 41](https://user-images.githubusercontent.com/16357599/160513046-322786b9-d6c6-498d-92bd-87aae79c34ca.png)

**Comment by lhpkxywm** [comment]
demo中的数据是一次性加载好的，但是我的图表数据是后台翻页请求过来的，我实现了拖动，但是数据翻页我不知道怎么解决。能否完善一下，使图表库实现数据翻页加载呢。另外，我尝试使用chartView.scrollView.delegate设置代理，但是设置后，我无法监听到scrollView的滚动事件。虽然图表库提供了moveOverEventMessage方法，但是它似乎只能监听到点击事件，对于scrollView滚动的惯性停止，似乎无法判断。我希望当我使用chartView.scrollView.delegate设置代理后，我能够通过系统提供的scrollView代理方法，来判断图表的滚动状态。

**Comment by lhpkxywm** [comment]
aa_updateXAxisExtremesWithMin:(NSUInteger)min max:(NSUInteger)max这里的Min和max分别是什么意思呢

**Comment by lhpkxywm** [comment]
最好还是完善一下demo，数据翻页这里涉及了很多没有注释的方法，我看的头都晕了，卡了三天了。aa_updateXAxisExtremesWithMin:(NSUInteger)min max:(NSUInteger)max这种方法在demo里没有找到引用的地方，用起来就得自己一点一点摸索，很痛苦，很折磨。
