### ISSUE TITLE
如何实现图表数据的翻页加载

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1301]
图表是横向滚动的，滚动到一定位置后加载新的数据，同时滚动位置和x轴都不能发生变化。

**Comment by AAChartModel** [comment]
从你的需求描述来看, 我觉得继续用 Highcharts 可能不是个好主意, 

实现分页加载至少要能够监听用户滚动事件, 图表滚动到最左侧(或最右侧)能够及时插入新的数据.

但是目前我还没有在文档中找到监听用户滚动图表到最左侧(或最右侧)时的方法. 也不知道 Highcharts 是不是真的有这个方法.

网上找到的这两个参考链接

* https://www.highcharts.com/forum/viewtopic.php?t=31925#p112138
* https://api.highcharts.com.cn/class-reference/Highcharts.Axis.html#getExtremes

也不知道是否有用.



这个需求的实现, 我个人觉得最好是使用原生的图表库, 比如 Charts 或者 CorePlot  之类的, 能够手动修改源码是最好的.

需求太复杂, 像 Highcharts 这种没有事先就有需要的功能的话,  实现起来就比较困难了. 而且 Highcharts 这种使用 TypeScript 与 JavaScript语言编写的大型项目源码过于庞杂, 改起来也不太现实.  Charts 或者 CorePlot  这类的原生语言的代码量较小的图表库或许是个更佳的选择.
