### ISSUE TITLE
折线图有多条折线，各折线数据个数不同，或数据不连续

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1302]
折线图，有两条折线，折线的横轴是日期，但是不是所有日期两条折线都有数据的，比如4月5号这一天，可能a折线有数据，b折线就没有数据，到了4月8号可能就反过来了，a折线没数据，b折线有数据，其它时间段两条折线都有数据，这样的折线图怎么画呢
我尝试过将数据改为nil或NSNull，但是这样会导致数据折线中断。
![image](https://user-images.githubusercontent.com/12290214/161919291-f23717ad-1954-4a02-99ff-d9b41785b927.png)

**Comment by AAChartModel** [comment]
估计你需要的是折线图的**断点重连** 的功能, 参考

* https://github.com/AAChartModel/AAChartKit/issues/1155

**Comment by AAChartModel** [comment]
Swift 版本的问题, 参考 

* https://github.com/AAChartModel/AAChartKit/issues/988
