### ISSUE TITLE
y轴格式化

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1303]
y轴的数值为整数，我需要将它改为小数，并且附加百分号%，该怎么做？

**Comment by AAChartModel** [comment]
Y轴 文字标签的格式化, 主要有两个关键属性 

* `format`  :https://api.highcharts.com/highcharts/yAxis.labels.format
* `formatter` : https://api.highcharts.com/highcharts/yAxis.labels.formatter

**Comment by AAChartModel** [comment]
参考相似问题 

* https://github.com/AAChartModel/AAChartKit/issues/675
* https://github.com/AAChartModel/AAChartKit/issues/952
