### ISSUE TITLE
图表没有数据时，如何给出无数据的提示

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1304]
如何设定无数据的提示文字

**Comment by AAChartModel** [comment]
查看在线文档

* https://api.highcharts.com/highcharts/noData.style

在线使用示例

* https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/no-data-to-display/no-data-line

从上可知, 实现默认的无数据效果还得额外的添加 JS 插件, 并且最终的实现效果并不怎么样.  所以 AAChartKit 中没有添加无数据提示的功能.

你可以直接使用原生方法实现:

1. 判断图表在没有数据(data 数组内容为空)时, 直接在图表区域添加一个自定义内容的 UILabel
2. 有数据时, 移除添加的 UILabel
