### ISSUE TITLE
Y轴左侧不希望显示value标题，如何使用系统自己算好的值填充y轴数据

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1306]
![image](https://user-images.githubusercontent.com/12290214/162341814-dc7cd01d-5a67-4abe-b282-28bce5a15c88.png)
我尝试使用AATitlle()占位，但是没有效果
![image](https://user-images.githubusercontent.com/12290214/162341936-d1f83213-e9ba-406a-a299-2a90bb9960bc.png)
如果使用了aaYAxis就必须通过categories手动设置值吗？我最开始并没有设置aaYAxis，图表库似乎帮我计算好了一套值并渲染在y轴上了，但是当我设置aaYAxis后，y轴就只显示0.00了

**Comment by AAChartModel** [comment]
> 我尝试使用AATitlle()占位，但是没有效果

你把 AATitle() 改为

```swift
AATitle()
.text("")
```
试试

**Comment by AAChartModel** [comment]
> 但是当我设置aaYAxis后，y轴就只显示0.00了

这是由于你的代码中的 AALabels 的 `format("0.00")`导致的

**Comment by lhpkxywm** [comment]
> > 但是当我设置aaYAxis后，y轴就只显示0.00了
> 
> 这是由于你的代码中的 AALabels 的 `format("0.00")`导致的

那我必须手动设置yAxis的categories呗？

**Comment by AAChartModel** [comment]
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/xaxis/labels-format-custom/

你参考这个在线示例, 把 `format("0.00")` 改为  `format("美元{value:.2f}`, 再运行看看效果, 你就大概知道 format 怎么用了.

**Comment by AAChartModel** [comment]
format 属性配置在线文档: https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting
