### ISSUE TITLE
点击图表时能否在x轴上显示对应的x轴文字

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1307]
![image](https://user-images.githubusercontent.com/12290214/162342475-36ae1ed3-5a79-4ec0-8327-62254e725d33.png)

**Comment by AAChartModel** [comment]
目前没有直接实现此功能的配置. 不过你可以试试 `AAChartView` 的这个更新 X 轴文字内容的方法

```objc
/// Update the X axis categories of chart
/// @param categories The X axis categories array
/// @param redraw Redraw whole chart or not
- (void)aa_updateXAxisCategories:(NSArray *)categories redraw:(BOOL)redraw;

```

在用户点击图表时, 获取点击事件对应的点, 然后调用此方法, 刷新图表的 X 轴的 `categories`的文字内容
