### ISSUE TITLE
刷新数据时，如果`[AASeriesElement]` 数组的元素个数有变化，如何传递x轴的数据

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1308]
refresh方法似乎只传递了y轴的`[AASeriesElement]`数组数据，如果这个数组个数和之前的数据相比有变化，x轴的数据也有变化，那么只刷新数据该如何传递新的数据

**Comment by AAChartModel** [comment]
参考文档 https://blog.csdn.net/eengel/article/details/73497208

**Comment by AAChartModel** [comment]
>  如果这个数组个数和之前的数据相比有变化

查看 `AAChartView` 中的代码:

```swift
    /// Add a new series element to the chart after the chart has been rendered.
    /// Refer to https://api.highcharts.com.cn/highcharts#Chart.addSeries
    ///
    /// - Parameter element: chart series element
    public func aa_addElementToChartSeries(element: AASeriesElement) {
        let elementJson = element.toJSON()!
        let pureElementJsonStr = elementJson.aa_toPureJSString()
        let jsStr = "addElementToChartSeriesWithElement('\(pureElementJsonStr)')"
        safeEvaluateJavaScriptString(jsStr)
    }
    
    /// Remove a specific series element from the chart after the chart has been rendered.
    /// Refer to https://api.highcharts.com.cn/highcharts#Series.remove
    ///
    /// - Parameter elementIndex: chart series element index
    public func aa_removeElementFromChartSeries(elementIndex: Int) {
        let jsStr = "removeElementFromChartSeriesWithElementIndex('\(elementIndex)')"
        safeEvaluateJavaScriptString(jsStr)
    }
```

这两个方法分别是用于**添加**和**移除**单个 `AASeriesment` 元素的

**Comment by AAChartModel** [comment]
如果你只是需要刷新 `【AASeriesment】`数组中的单个元素的话,  AAChartView 中还暂未添加刷新指定的 `AASeriesment` 元素的方法.

**Comment by lhpkxywm** [comment]
如果x轴的数据有变化，怎么办？addElement只是增加y轴的数据啊。
比如x轴之前是3-7到4-7，请求新数据后变成了1-7到4-7。这种

**Comment by lhpkxywm** [comment]
> 不过, 如果你只是需要刷新 `[AASeriesElement]`数组中的单个元素 `data` 的话, AAChartView 中还暂未添加刷新指定的 `AASeriesElement` 元素的方法.

我再说详细点，我有一排按钮，点击不同的按钮显示不同的数据，第一个按钮点击了显示收益率，第二个按钮点击了显示基金or股票的净值or价格，收益率横轴可能是日期，也可能是一天从9点半到15点。变化比较大，我该如何刷新数据？我看到几个refresh的方法，似乎没办法更改x轴上的categories。

**Comment by lhpkxywm** [comment]
> 不过, 如果你只是需要刷新 `[AASeriesElement]`数组中的单个元素 `data` 的话, AAChartView 中还暂未添加刷新指定的 `AASeriesElement` 元素的方法.

我再说详细点，我有一排按钮，点击不同的按钮显示不同的数据，第一个按钮点击了显示收益率，第二个按钮点击了显示基金or股票的净值or价格，收益率横轴可能是日期，也可能是一天从9点半到15点。变化比较大，我该如何刷新数据？我看到几个refresh的方法，似乎没办法更改x轴上的categories。
