### ISSUE TITLE
怎么保持同一个X轴上的多个范围图显示在同一个X轴坐标上

### ISSUE THREAD

**Issue by limice89** [AAChartModel/AAChartKit#1316]
[图片示例](https://i.postimg.cc/x1B5ZMR1/Simulator-Screen-Shot-i-Phone-11-2022-04-22-at-11-45-14.png)

**Comment by AAChartModel** [comment]
参考 Swift 版本的相同问题.

* https://github.com/AAChartModel/AAChartKit-Swift/issues/216
