### ISSUE TITLE
选中后模糊的白色圆点如何删除

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1318]
![image](https://user-images.githubusercontent.com/12290214/165032851-3756a19d-baaa-4259-8e31-2eb9977838d8.png)

**Comment by lhpkxywm** [comment]
蓝色的外圈和白色小圆点都删除。

**Comment by AAChartModel** [comment]
**禁用曲线图的手指滑动 marker 点的光圈变化放大的效果**

demo 中有此示例

```objc
// Refer to https://api.highcharts.com.cn/highcharts#plotOptions.spline.marker.states.hover.enabled
- (AAChartModel *)disableSplineChartMarkerHoverEffect {
    return AAChartModel.new
    .chartTypeSet(AAChartTypeSpline)
    .titleSet(@"Disable Spline Chart Marker Hover Effect")
    .categoriesSet(@[
        @"一月", @"二月", @"三月", @"四月", @"五月", @"六月",
        @"七月", @"八月", @"九月", @"十月", @"十一月", @"十二月"
                   ])
    .markerRadiusSet(@0)//marker点半径为0个像素
    .yAxisLineWidthSet(@0)
    .yAxisGridLineStyleSet([AALineStyle styleWithWidth:@0])
    .legendEnabledSet(false)
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"Tokyo Hot")
        .lineWidthSet(@5.0)
        .colorSet(AARgbaColor(220, 20, 60, 1.0))//猩红色, alpha 透明度 1
        .markerSet(AAMarker.new
                   .statesSet(AAMarkerStates.new
                              .hoverSet(AAMarkerHover.new
                                        .enabledSet(false))))
        .dataSet(@[@7.0, @6.9, @2.5, @14.5, @18.2, @21.5, @5.2, @26.5, @23.3, @45.3, @13.9, @9.6]),
               ]);
}
```

起作用的关键内容 

```objc
       .markerSet(AAMarker.new
                   .statesSet(AAMarkerStates.new
                              .hoverSet(AAMarkerHover.new
                                        .enabledSet(false))))
```

**Comment by lhpkxywm** [comment]
> **禁用曲线图的手指滑动 marker 点的光圈变化放大的效果**
> 
> demo 中有此示例
> 
> ```objc
> // Refer to https://api.highcharts.com.cn/highcharts#plotOptions.spline.marker.states.hover.enabled
> - (AAChartModel *)disableSplineChartMarkerHoverEffect {
>     return AAChartModel.new
>     .chartTypeSet(AAChartTypeSpline)
>     .titleSet(@"Disable Spline Chart Marker Hover Effect")
>     .categoriesSet(@[
>         @"一月", @"二月", @"三月", @"四月", @"五月", @"六月",
>         @"七月", @"八月", @"九月", @"十月", @"十一月", @"十二月"
>                    ])
>     .markerRadiusSet(@0)//marker点半径为0个像素
>     .yAxisLineWidthSet(@0)
>     .yAxisGridLineStyleSet([AALineStyle styleWithWidth:@0])
>     .legendEnabledSet(false)
>     .seriesSet(@[
>         AASeriesElement.new
>         .nameSet(@"Tokyo Hot")
>         .lineWidthSet(@5.0)
>         .colorSet(AARgbaColor(220, 20, 60, 1.0))//猩红色, alpha 透明度 1
>         .markerSet(AAMarker.new
>                    .statesSet(AAMarkerStates.new
>                               .hoverSet(AAMarkerHover.new
>                                         .enabledSet(false))))
>         .dataSet(@[@7.0, @6.9, @2.5, @14.5, @18.2, @21.5, @5.2, @26.5, @23.3, @45.3, @13.9, @9.6]),
>                ]);
> }
> ```
> 
> 起作用的关键内容
> 
> ```objc
>        .markerSet(AAMarker.new
>                    .statesSet(AAMarkerStates.new
>                               .hoverSet(AAMarkerHover.new
>                                         .enabledSet(false))))
> ```

如果只想去除蓝色的外圈呢
