### ISSUE TITLE
点击折线图显示的小圆点怎么去掉

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1320]
![image](https://user-images.githubusercontent.com/12290214/165253786-f8691bda-c3a9-427f-94d4-c79e925b1bec.png)
想替换成十字线

**Comment by AAChartModel** [comment]
配置 AAOptions

```objc
- (AAOptions *)configureAAPlotBandsForChart {
    AACrosshair *aaCrosshair =
    [AACrosshair crosshairWithColor:AAColor.grayColor
                          dashStyle:AAChartLineDashStyleTypeLongDashDotDot
                              width:@1.5];
    
    AAChartModel *aaChartModel = AAChartModel.new
    .chartTypeSet(AAChartTypeSpline)
    .backgroundColorSet(AAColor.whiteColor)
    .categoriesSet(@[@"一月", @"二月", @"三月", @"四月", @"五月", @"六月", @"七月", @"八月", @"九月", @"十月", @"十一月", @"十二月"])
    .markerRadiusSet(@0)
    .yAxisMaxSet(@50)
    .yAxisGridLineStyleSet([AALineStyle styleWithWidth:@0])
    .xAxisCrosshairSet(aaCrosshair)
    .yAxisCrosshairSet(aaCrosshair)
    .legendEnabledSet(false)
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"2017")
        .colorSet(AAColor.whiteColor)
        .lineWidthSet(@10)
        .dataSet(@[@7.0, @6.9, @2.5, @14.5, @18.2, @21.5, @5.2, @26.5, @23.3, @45.3, @13.9, @9.6]),
               ]);
    
    AAOptions *aaOptions = aaChartModel.aa_toAAOptions;
    aaOptions.yAxis.gridLineInterpolation = AAChartYAxisGridLineInterpolationTypePolygon;
    
    NSArray *aaPlotBandsArr = @[
        AAPlotBandsElement.new
        .fromSet(@0)
        .toSet(@5)
        .colorSet(@"#BC2B44"),
        AAPlotBandsElement.new
        .fromSet(@5)
        .toSet(@10)
        .colorSet(@"#EC6444"),
        AAPlotBandsElement.new
        .fromSet(@10)
        .toSet(@15)
        .colorSet(@"#f19742"),
        AAPlotBandsElement.new
        .fromSet(@15)
        .toSet(@20)
        .colorSet(@"#f3da60"),
        AAPlotBandsElement.new
        .fromSet(@20)
        .toSet(@25)
        .colorSet(@"#9bd040"),
        AAPlotBandsElement.new
        .fromSet(@25)
        .toSet(@50)
        .colorSet(@"#acf08f"),
    ];
    
    AAYAxis *aaYAxis = aaOptions.yAxis;
    aaYAxis.plotBands = aaPlotBandsArr;
    return aaOptions;
}
```

## 最终图表
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-04-26 at 16 51 53](https://user-images.githubusercontent.com/16357599/165262176-347f9c8b-9927-4ba2-ba39-20eb14271c7c.png)

**Comment by AAChartModel** [comment]
显示双准星线的关键代码

```objc
 AACrosshair *aaCrosshair =
    [AACrosshair crosshairWithColor:AAColor.grayColor
                          dashStyle:AAChartLineDashStyleTypeLongDashDotDot
                              width:@1.5];

...
...
   .xAxisCrosshairSet(aaCrosshair)
    .yAxisCrosshairSet(aaCrosshair)
...
...

```

**Comment by lhpkxywm** [comment]
> 配置 AAOptions
> 
> ```objc
> - (AAOptions *)configureAAPlotBandsForChart {
>     AACrosshair *aaCrosshair =
>     [AACrosshair crosshairWithColor:AAColor.grayColor
>                           dashStyle:AAChartLineDashStyleTypeLongDashDotDot
>                               width:@1.5];
>     
>     AAChartModel *aaChartModel = AAChartModel.new
>     .chartTypeSet(AAChartTypeSpline)
>     .backgroundColorSet(AAColor.whiteColor)
>     .categoriesSet(@[@"一月", @"二月", @"三月", @"四月", @"五月", @"六月", @"七月", @"八月", @"九月", @"十月", @"十一月", @"十二月"])
>     .markerRadiusSet(@0)
>     .yAxisMaxSet(@50)
>     .yAxisGridLineStyleSet([AALineStyle styleWithWidth:@0])
>     .xAxisCrosshairSet(aaCrosshair)
>     .yAxisCrosshairSet(aaCrosshair)
>     .legendEnabledSet(false)
>     .seriesSet(@[
>         AASeriesElement.new
>         .nameSet(@"2017")
>         .colorSet(AAColor.whiteColor)
>         .lineWidthSet(@10)
>         .dataSet(@[@7.0, @6.9, @2.5, @14.5, @18.2, @21.5, @5.2, @26.5, @23.3, @45.3, @13.9, @9.6]),
>                ]);
>     
>     AAOptions *aaOptions = aaChartModel.aa_toAAOptions;
>     aaOptions.yAxis.gridLineInterpolation = AAChartYAxisGridLineInterpolationTypePolygon;
>     
>     NSArray *aaPlotBandsArr = @[
>         AAPlotBandsElement.new
>         .fromSet(@0)
>         .toSet(@5)
>         .colorSet(@"#BC2B44"),
>         AAPlotBandsElement.new
>         .fromSet(@5)
>         .toSet(@10)
>         .colorSet(@"#EC6444"),
>         AAPlotBandsElement.new
>         .fromSet(@10)
>         .toSet(@15)
>         .colorSet(@"#f19742"),
>         AAPlotBandsElement.new
>         .fromSet(@15)
>         .toSet(@20)
>         .colorSet(@"#f3da60"),
>         AAPlotBandsElement.new
>         .fromSet(@20)
>         .toSet(@25)
>         .colorSet(@"#9bd040"),
>         AAPlotBandsElement.new
>         .fromSet(@25)
>         .toSet(@50)
>         .colorSet(@"#acf08f"),
>     ];
>     
>     AAYAxis *aaYAxis = aaOptions.yAxis;
>     aaYAxis.plotBands = aaPlotBandsArr;
>     return aaOptions;
> }
> ```
> 
> ## 最终图表
> ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-04-26 at 16 51 53](https://user-images.githubusercontent.com/16357599/165262176-347f9c8b-9927-4ba2-ba39-20eb14271c7c.png)

去掉小圆点的关键代码是哪句啊

**Comment by AAChartModel** [comment]
> 去掉小圆点的关键代码是哪句啊

参考相同问题:

* https://github.com/AAChartModel/AAChartKit/issues/909
