### ISSUE TITLE
气泡没有正常显示

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1323]
![image](https://user-images.githubusercontent.com/12290214/167558843-3482d6a2-6f90-46d7-bd9a-89d5ec65d18f.png)
红色框里其实应该有个气泡的，但是因为Y轴刻度的原因没显示出来。我不想手动计算Y轴的刻度，怎样才能显示出气泡呢？

**Comment by AAChartModel** [comment]
试试这个问题的解决方案: 

* https://github.com/AAChartModel/AAChartKit/issues/1033
