### ISSUE TITLE
Y轴格式化问题

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1324]
![image](https://user-images.githubusercontent.com/12290214/168191021-70558a95-677f-4fae-9aa4-1e4825a95f21.png)
这里Y轴的格式，想改成x.xx千，怎么弄啊

**Comment by AAChartModel** [comment]
## 配置 AAOptions

```swift
 func configureTheAxesLabelsFormattersOfDoubleYAxesChart2() -> AAOptions {
        let aaChart = AAChart()
            .backgroundColor(AAColor.white)
        
        let aaTitle = AATitle()
            .text("")
        
        let aaXAxis = AAXAxis()
            .visible(true)
            .min(0)
            .categories([
                "Java", "Swift", "Python", "Ruby", "PHP", "Go","C",
                "C#", "C++", "Perl", "R", "MATLAB", "SQL"
            ])
        
        let aaPlotOptions = AAPlotOptions()
            .series(AASeries()
                .marker(AAMarker()
                    .radius(7)//曲线连接点半径，默认是4
                    .symbol(AAChartSymbolType.circle.rawValue)//曲线点类型："circle", "square", "diamond", "triangle","triangle-down"，默认是"circle"
                    .fillColor(AAColor.white)//点的填充色(用来设置折线连接点的填充色)
                    .lineWidth(3)//外沿线的宽度(用来设置折线连接点的轮廓描边的宽度)
                    .lineColor("")//外沿线的颜色(用来设置折线连接点的轮廓描边颜色，当值为空字符串时，默认取数据点或数据列的颜色)
                ))
        
        let yAxis1 = AAYAxis()
            .visible(true)
            .lineWidth(1)
            .startOnTick(false)
            .endOnTick(false)
            .tickPositions([0, 50, 100, 150, 200])
            .labels(AALabels()
                .enabled(true)
                .style(AAStyle()
                    .color("DodgerBlue"))
                    .formatter("""
                function () {
                    var yValue = this.value;
                    var formattedYValue = (yValue / 1000).toFixed(3) + '千';
                    return formattedYValue;
                }
               """)
            )
            .gridLineWidth(0)
            .title(AATitle()
                .text(#"以「千」为单位"#)
                .style(AAStyle(color: "DodgerBlue", fontSize: 14, weight: .bold)))
        
        let yAxis2 = AAYAxis()
            .visible(true)
            .lineWidth(1)
            .startOnTick(false)
            .endOnTick(false)
            .tickPositions([0, 50, 100, 150, 200])
            .labels(AALabels()
                .enabled(true)
                .style(AAStyle()
                    .color(AAColor.red))
                    .formatter("""
                function () {
                    var yValue = this.value;
                    var formattedYValue = (yValue / 10000).toFixed(4) + '万';
                    return formattedYValue;
                }
               """)
            )
            .gridLineWidth(0)
            .title(AATitle()
                .text("以『万』为单位")
                .style(AAStyle(color: AAColor.red, fontSize: 14, weight: .bold)))
            .opposite(true)
        
        let aaTooltip = AATooltip()
            .enabled(true)
            .shared(true)
        
        let seriesArr = [
            AASeriesElement()
                .name("2020")
                .type(.spline)
                .lineWidth(7)
                .color(AAGradientColor.deepSea)
                .yAxis(1)
                .data([
                    0, 71.5, 106.4, 129.2, 144.0, 176.0,
                    135.6, 148.5, 216.4, 194.1, 95.6, 54.4
                ]),
            AASeriesElement()
                .name("2021")
                .type(.spline)
                .lineWidth(7)
                .color(AAGradientColor.sanguine)
                .yAxis(0)
                .data([
                    135.6, 148.5, 216.4, 194.1, 95.6, 54.4,
                    0, 71.5, 106.4, 129.2, 144.0, 176.0
                ])
        ]
        
        let aaOptions = AAOptions()
            .chart(aaChart)
            .title(aaTitle)
            .plotOptions(aaPlotOptions)
            .xAxis(aaXAxis)
            .yAxisArray([yAxis1,yAxis2])
            .tooltip(aaTooltip)
            .series(seriesArr)
        
        return aaOptions
    }
```

## 最终图表📈
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-05-13 at 11 35 43](https://user-images.githubusercontent.com/16357599/168206666-986cd00b-892c-4204-b128-f30125edfefa.png)

**Comment by AAChartModel** [comment]
因为暂未找到(可能也没有)使用 format 的简易方法. 所以以上示例采用了 formatter 属性来格式化 Y 轴的文字标签.

**Comment by AAChartModel** [comment]
综上, 你的 formatter 这样写应该就可以了:         

  .formatter("""
                function () {
                    var yValue = this.value;
                    var formattedYValue = (yValue / 1000).toFixed(2) + '千';
                    return formattedYValue;
                }
               """)

**Comment by AAChartModel** [comment]
参考相关问题:

*  https://github.com/AAChartModel/AAChartKit/issues/901
* https://github.com/AAChartModel/AAChartKit/issues/952

**Comment by lhpkxywm** [comment]
> 综上, 你的 formatter 这样写应该就可以了:
> 
> ```js
>            .formatter("""
>                 function () {
>                     var yValue = this.value;
>                     var formattedYValue = (yValue / 1000).toFixed(2) + '千';
>                     return formattedYValue;
>                 }
>                """)
> ```

当最小值为0的时候，Y轴的刻度要显示0而不是0.00千，我尝试这样做判断，但是图表报错了
![image](https://user-images.githubusercontent.com/12290214/168277794-f8dfb1e3-dfd9-41fa-9b28-de78d430b2b9.png)

**Comment by colaxp** [comment]
func configureColorfulGradientSplineChart() -> AAChartModel {
        let model = AAChartModel()
//            .chartType(.spline)
            .chartType(.areaspline)
            .categories(["8-20", "8-21", "8-22", "8-23", "8-24", "8-25",
                         "8-26"])
            .markerRadius(0)
            .legendEnabled(false)
            .dataLabelsEnabled(false) /// 显示原点数据
            .markerSymbolStyle(.innerBlank)
            .yAxisGridLineWidth(0)
            .yAxisAllowDecimals(true)
            .series([
                AASeriesElement()
                    .name("¥")
                    .lineWidth(3)
                    .color(AAGradientColor.linearGradient(
                        direction: .toRight,
                        stops: [
                            [0.00, "#7ae5fb"],//颜色字符串设置支持十六进制类型和 rgba 类型
                            [0.25, "#6bb9f8"],
                            [0.50, "#5b80f5"],
                            [0.75, "#5664f3"],
                            [1.00, "#534bf1"],
                        ]
                    ))
                    .fillColor(AAGradientColor.linearGradient(
                        direction: .toTop,
                        stops: [
                            [0.0, AARgba(117, 207, 249, 0.0)],//颜色字符串设置支持十六进制类型和 rgba 类型
                            [0.5, AARgba(117, 207, 249, 0.0)],
                            [1.0, AARgba(117, 207, 249, 0.6)]
                        ]
                    ))
                    
                    .threshold(0)
                    .data([22.5, 22.4, 44.7, 77.88, 99.33, 45.22, 8666]),
            
            ])
            
        model.colorsTheme = ["#1e90ff","#ef476f","#ffd066","#04d69f","#25547c"]
        model.animationType = .elastic
        model.zoomType = .xy
        
    
        
        
//        model.inverted = true // 反转xy
        return model
    } 想问下如果用上面的这种如何自定义Y'轴的单位显示

**Comment by AAChartModel** [comment]
```swift
private func customAxesGridLineStyle() -> AAOptions {
        let aaChartModel = AAChartModel()
            .chartType(.line)//图表类型
            .title("custom Axes Grid Line Style")//图表主标题
            .markerSymbolStyle(.borderBlank)
            .categories(["Jan", "Feb", "Mar", "Apr", "May", "Jun","Jul", "Aug", "Sep", "Oct", "Nov", "Dec"])
            .markerRadius(8)
            .series([
                AASeriesElement()
                    .name("2020")
                    .lineWidth(5.5)
                    .color(AAGradientColor.sanguine)
                    .data([7.0, 6.9, 2.5, 14.5, 18.2, 21.5, 5.2, 26.5, 23.3, 45.3, 13.9, 9.6])
            ])
        
        let aaOptions = aaChartModel.aa_toAAOptions()
        
        aaOptions.yAxis?
            .opposite(true)
            .gridLineDashStyle(.shortDashDot)
            .gridLineWidth(3)
            .gridLineColor(AAColor.lightGray)
        
        aaOptions.xAxis?
            .gridLineDashStyle(.shortDashDotDot)
            .gridLineWidth(3)
            .gridLineColor(AAColor.gray)
        
        return aaOptions
    }
```

类似于这样, 先将 `AAChartModel` 转化成 `AAOptions` , 再对 `AAOption` 实例进行进一步的详细配置.

@colaxp
