### ISSUE TITLE
如何取消饼状图内边距

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1325]
![image](https://user-images.githubusercontent.com/12290214/168198243-5c74850e-65b2-4793-b484-da7c6721132a.png)

**Comment by AAChartModel** [comment]
试试 AAChart 类的这几个属性


[margin:](https://api.highcharts.com.cn/highcharts/chart.margin.html)undefined
[marginBottom:](https://api.highcharts.com.cn/highcharts/chart.marginBottom.html)undefined
[marginLeft:](https://api.highcharts.com.cn/highcharts/chart.marginLeft.html)undefined
[marginRight:](https://api.highcharts.com.cn/highcharts/chart.marginRight.html)undefined
[marginTop:](https://api.highcharts.com.cn/highcharts/chart.marginTop.html)undefined
