### ISSUE TITLE
填充颜色没有效果

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1328]
![image](https://user-images.githubusercontent.com/12290214/168283446-0e0a57ef-bc2f-4eff-a0ce-e75bde338188.png)
哪里写的不对呢？

**Comment by AAChartModel** [comment]
控制台输出的 AAOptions 的 json 信息贴出来, 看看什么问题

**Comment by AAChartModel** [comment]
有可能是转换成 json 的时候有什么问题

**Comment by lhpkxywm** [comment]
> 有可能是转换成 json 的时候有什么问题

{
  "xAxis" : {
    "lineColor" : "#EEEEEE",
    "labels" : {
      "style" : {
        "color" : "#333333"
      }
    },
    "categories" : [
      "2022-04-15",
      "2022-04-16",
      "2022-04-17",
      "2022-04-18",
      "2022-04-19",
      "2022-04-20",
      "2022-04-21",
      "2022-04-22",
      "2022-04-23",
      "2022-04-24",
      "2022-04-25",
      "2022-04-26",
      "2022-04-27",
      "2022-04-28",
      "2022-04-29",
      "2022-04-30",
      "2022-05-01",
      "2022-05-02",
      "2022-05-03",
      "2022-05-04",
      "2022-05-05",
      "2022-05-06",
      "2022-05-07",
      "2022-05-08",
      "2022-05-09",
      "2022-05-10",
      "2022-05-11",
      "2022-05-12",
      "2022-05-13",
      "2022-05-14",
      "2022-05-15"
    ],
    "tickInterval" : 30,
    "crosshair" : {
      "width" : 0.5,
      "dashStyle" : "dash",
      "color" : "#747474"
    },
    "lineWidth" : 0.5,
    "tickWidth" : 0.5
  },
  "chart" : {
    "type" : "line"
  },
  "legend" : {
    "itemStyle" : {

    },
    "enabled" : false
  },
  "yAxis" : {
    "crosshair" : {
      "color" : "#747474",
      "width" : 0.5,
      "dashStyle" : "dash"
    },
    "title" : {
      "text" : ""
    },
    "min" : 0,
    "lineWidth" : 0.5,
    "labels" : {
      "formatter" : "(function() {    var yValue = this.value;    var formattedYValue = (yValue \/ 1000).toFixed(1) + \\\"千\\\";    return formattedYValue;})",
      "style" : {
        "color" : "#333333"
      }
    },
    "lineColor" : "#EEEEEE",
    "tickWidth" : 0.5
  },
  "touchEventEnabled" : true,
  "plotOptions" : {
    "series" : {
      "animation" : {
        "easing" : 1,
        "duration" : 800
      },
      "stacking" : "",
      "dataLabels" : {

      },
      "states" : {
        "inactive" : {
          "enabled" : false
        }
      },
      "marker" : {
        "radius" : 0
      }
    }
  },
  "title" : {
    "text" : ""
  },
  "credits" : {
    "enabled" : false
  },
  "series" : [
    {
      "marker" : {
        "states" : {
          "hover" : {
            "radius" : 4
          }
        }
      },
      "fillColor" : {
        "linearGradient" : {
          "x2" : 0,
          "x1" : 0,
          "y2" : 1,
          "y1" : 0
        },
        "stops" : [
          [
            0,
            "rgba(255,247,236,1)"
          ],
          [
            1,
            "rgba(246,236,211,0)"
          ]
        ]
      },
      "data" : [
        2097.48,
        2097.48,
        2097.48,
        2097.48,
        2097.48,
        2097.48,
        2097.48,
        2097.48,
        2097.48,
        2097.48,
        2097.48,
        2097.48,
        2097.48,
        4194.96,
        4194.96,
        4194.96,
        4194.96,
        4194.96,
        4194.96,
        4194.96,
        4194.96,
        4194.96,
        4194.96,
        4194.96,
        2097.48,
        2097.48,
        2097.48,
        2097.48,
        2697.48,
        2697.48,
        2697.48
      ]
    }
  ],
  "colors" : [
    "#fd8b2b"
  ],
  "tooltip" : {
    "shared" : true,
    "enabled" : false,
    "crosshairs" : true
  }
}

**Comment by lhpkxywm** [comment]
> { "xAxis" : { "lineColor" : "#EEEEEE", "labels" : { "style" : { "color" : "#333333" } }, "categories" : [ "2022-04-15", "2022-04-16", "2022-04-17", "2022-04-18", "2022-04-19", "2022-04-20", "2022-04-21", "2022-04-22", "2022-04-23", "2022-04-24", "2022-04-25", "2022-04-26", "2022-04-27", "2022-04-28", "2022-04-29", "2022-04-30", "2022-05-01", "2022-05-02", "2022-05-03", "2022-05-04", "2022-05-05", "2022-05-06", "2022-05-07", "2022-05-08", "2022-05-09", "2022-05-10", "2022-05-11", "2022-05-12", "2022-05-13", "2022-05-14", "2022-05-15" ], "tickInterval" : 30, "crosshair" : { "width" : 0.5, "dashStyle" : "dash", "color" : "#747474" }, "lineWidth" : 0.5, "tickWidth" : 0.5 }, "chart" : { "type" : "line" }, "legend" : { "itemStyle" : {
> 
> ```
> },
> "enabled" : false
> ```
> 
> }, "yAxis" : { "crosshair" : { "color" : "#747474", "width" : 0.5, "dashStyle" : "dash" }, "title" : { "text" : "" }, "min" : 0, "lineWidth" : 0.5, "labels" : { "formatter" : "(function() { var yValue = this.value; var formattedYValue = (yValue / 1000).toFixed(1) + \"千\"; return formattedYValue;})", "style" : { "color" : "#333333" } }, "lineColor" : "#EEEEEE", "tickWidth" : 0.5 }, "touchEventEnabled" : true, "plotOptions" : { "series" : { "animation" : { "easing" : 1, "duration" : 800 }, "stacking" : "", "dataLabels" : {
> 
> ```
>   },
>   "states" : {
>     "inactive" : {
>       "enabled" : false
>     }
>   },
>   "marker" : {
>     "radius" : 0
>   }
> }
> ```
> 
> }, "title" : { "text" : "" }, "credits" : { "enabled" : false }, "series" : [ { "marker" : { "states" : { "hover" : { "radius" : 4 } } }, "fillColor" : { "linearGradient" : { "x2" : 0, "x1" : 0, "y2" : 1, "y1" : 0 }, "stops" : [ [ 0, "rgba(255,247,236,1)" ], [ 1, "rgba(246,236,211,0)" ] ] }, "data" : [ 2097.48, 2097.48, 2097.48, 2097.48, 2097.48, 2097.48, 2097.48, 2097.48, 2097.48, 2097.48, 2097.48, 2097.48, 2097.48, 4194.96, 4194.96, 4194.96, 4194.96, 4194.96, 4194.96, 4194.96, 4194.96, 4194.96, 4194.96, 4194.96, 2097.48, 2097.48, 2097.48, 2097.48, 2697.48, 2697.48, 2697.48 ] } ], "colors" : [ "#fd8b2b" ], "tooltip" : { "shared" : true, "enabled" : false, "crosshairs" : true } }



> 有可能是转换成 json 的时候有什么问题

{
"xAxis" : {
"lineColor" : "#EEEEEE",
"labels" : {
"style" : {
"color" : "#333333"
}
},
"categories" : [
"2022-04-15",
"2022-04-16",
"2022-04-17",
"2022-04-18",
"2022-04-19",
"2022-04-20",
"2022-04-21",
"2022-04-22",
"2022-04-23",
"2022-04-24",
"2022-04-25",
"2022-04-26",
"2022-04-27",
"2022-04-28",
"2022-04-29",
"2022-04-30",
"2022-05-01",
"2022-05-02",
"2022-05-03",
"2022-05-04",
"2022-05-05",
"2022-05-06",
"2022-05-07",
"2022-05-08",
"2022-05-09",
"2022-05-10",
"2022-05-11",
"2022-05-12",
"2022-05-13",
"2022-05-14",
"2022-05-15"
],
"tickInterval" : 30,
"crosshair" : {
"width" : 0.5,
"dashStyle" : "dash",
"color" : "#747474"
},
"lineWidth" : 0.5,
"tickWidth" : 0.5
},
"chart" : {
"type" : "line"
},
"legend" : {
"itemStyle" : {

},
"enabled" : false
},
"yAxis" : {
"crosshair" : {
"color" : "#747474",
"width" : 0.5,
"dashStyle" : "dash"
},
"title" : {
"text" : ""
},
"min" : 0,
"lineWidth" : 0.5,
"labels" : {
"formatter" : "(function() { var yValue = this.value; var formattedYValue = (yValue / 1000).toFixed(1) + \"千\"; return formattedYValue;})",
"style" : {
"color" : "#333333"
}
},
"lineColor" : "#EEEEEE",
"tickWidth" : 0.5
},
"touchEventEnabled" : true,
"plotOptions" : {
"series" : {
"animation" : {
"easing" : 1,
"duration" : 800
},
"stacking" : "",
"dataLabels" : {

  },
  "states" : {
    "inactive" : {
      "enabled" : false
    }
  },
  "marker" : {
    "radius" : 0
  }
}
},
"title" : {
"text" : ""
},
"credits" : {
"enabled" : false
},
"series" : [
{
"marker" : {
"states" : {
"hover" : {
"radius" : 4
}
}
},
"fillColor" : {
"linearGradient" : {
"x2" : 0,
"x1" : 0,
"y2" : 1,
"y1" : 0
},
"stops" : [
[
0,
"rgba(255,247,236,1)"
],
[
1,
"rgba(246,236,211,0)"
]
]
},
"data" : [
2097.48,
2097.48,
2097.48,
2097.48,
2097.48,
2097.48,
2097.48,
2097.48,
2097.48,
2097.48,
2097.48,
2097.48,
2097.48,
4194.96,
4194.96,
4194.96,
4194.96,
4194.96,
4194.96,
4194.96,
4194.96,
4194.96,
4194.96,
4194.96,
2097.48,
2097.48,
2097.48,
2097.48,
2697.48,
2697.48,
2697.48
]
}
],
"colors" : [
"#fd8b2b"
],
"tooltip" : {
"shared" : true,
"enabled" : false,
"crosshairs" : true
}
}

**Comment by AAChartModel** [comment]
```js
  "chart" : {
    "type" : "line"
  }
```

你这里的图表类型需要改为  `AAChartType.area` 类型, fillColor 属性只对 **折线填充图, 曲线填充图**等 填充类图表有效.
