### ISSUE TITLE
如何关闭打印的日志，开发过程中数据打印被遮住了

### ISSUE THREAD

**Issue by liujie164** [AAChartModel/AAChartKit#1333]
<img width="789" alt="Snipaste_2022-05-19_17-45-08" src="https://user-images.githubusercontent.com/42240597/169264649-b7015f67-6868-432e-8719-b36d422cdd3b.png">

**Comment by AAChartModel** [comment]
直接在 `AAChartView` 的 **.m** 文件中 注释掉这段代码即可:

```objc
#if DEBUG
    [AAJsonConverter printPrettyPrintedJsonStringWithJsonObject:dic];
#endif
```
