### ISSUE TITLE
能否增加以下图表实现

### ISSUE THREAD

**Issue by promlife** [AAChartModel/AAChartKit#134]
![d3a95f31-b490-4fbe-8461-257316124274](https://user-images.githubusercontent.com/3366962/35398814-cab7c2ce-022d-11e8-8ba2-274cba95d9fb.png)

![image](https://user-images.githubusercontent.com/3366962/35397344-32cb0ce4-022a-11e8-88f7-6acf778f5ee6.png)

这种类型的图标是要求对于波动范围之外的区域重点关注，可滚动，可缩放，且可用竖线查看点的值

**Comment by AAChartModel** [comment]
你的这个需求相当的操蛋啊,话说这个效果图是你们的产品设计的,还是某一个类似产品的效果图?

**Comment by AAChartModel** [comment]
你的这种效果估计需要用几种类型图表拼接组合成的混合图才能勉强达到,单独的一种类型 highcharts 貌似不能够支持

**Comment by promlife** [comment]
哈哈，我们也感觉很奇怪，现在用原生勉强实现了效果，不过x轴缩放和滚动支持不是太好实现

**Comment by AAChartModel** [comment]
原生的是用的哪一个库吗?还是你自己画的?

**Comment by promlife** [comment]
https://github.com/gpbl/SwiftChart 在这个第三方库的基础上改造的，底层稍微按他的思路定制了下
