### ISSUE TITLE
如何让图形从最左边开始画图。

### ISSUE THREAD

**Issue by Breathing-J** [AAChartModel/AAChartKit#1342]
如标题，让折线图从最左边开始画线。X轴起点不留空隙。

**Comment by AAChartModel** [comment]
重复问题, 请参考:

* https://github.com/AAChartModel/AAChartKit/issues/577

**Comment by Breathing-J** [comment]
@AAChartModel 您好，试了你说的方法后，x轴的标题在屏幕比较窄的时候，显示一个，隐藏一个。X轴的labels自动隐藏了。如何去掉自动隐藏，显示所有X轴上label。

**Comment by AAChartModel** [comment]
> X轴的labels自动隐藏了

是什么效果? 截图看看👁

**Comment by Breathing-J** [comment]
@AAChartModel 感谢，已经解决了。您很棒，继续加油~
