### ISSUE TITLE
如何隐藏图表的选中的点的外层边缘线🧶?

### ISSUE THREAD

**Issue by AAChartModel** [AAChartModel/AAChartKit#1345]

**Comment by AAChartModel** [comment]
查看 demo 中的示例代码:

## 配置 AAChartModel

```objc
- (AAChartModel *)customSplineChartMarkerStatesHoverStyle {
    return AAChartModel.new
    .chartTypeSet(AAChartTypeAreaspline)
    .titleSet(@"Custom Spline Chart Marker States Hover Style")
    .categoriesSet(@[
        @"一月", @"二月", @"三月", @"四月", @"五月", @"六月",
        @"七月", @"八月", @"九月", @"十月", @"十一月", @"十二月"
                   ])
    .markerRadiusSet(@8.0)//marker点半径为8个像素
    .yAxisLineWidthSet(@0)
    .yAxisGridLineStyleSet([AALineStyle styleWithWidth:@0])
    .legendEnabledSet(false)
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"Tokyo Hot")
        .lineWidthSet(@5.0)
        .colorSet(AARgbaColor(220, 20, 60, 1.0))//猩红色, alpha 透明度 1
        .markerSet(AAMarker.new
                   .statesSet(AAMarkerStates.new
                              .hoverSet(AAMarkerHover.new
                                        .fillColorSet(AAColor.whiteColor)
                                        .radiusSet(@40)
                                        .lineColorSet(AAColor.greenColor)//设置 AAMarkerHover 外部边缘线颜色
                                        .lineWidthSet(@20))))//设置 AAMarkerHover 外部边缘线宽度
        .dataSet(@[@7.0, @6.9, @2.5, @14.5, @18.2, @21.5, @5.2, @26.5, @23.3, @45.3, @13.9, @9.6]),
               ]);
}
```

## 图表效果

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-05-27 at 14 45 23](https://user-images.githubusercontent.com/16357599/170646110-c3cee3d3-777e-42c1-a2f0-bd5d7314b6ed.png)


通过以上内容可知, 你所说的

实际上是 `AAMarkerHover` 的边缘线属性`line`, 可以通过设置`AAMarkerHover`的边缘线宽度为 0 来隐藏. 代码如下:

```objc
AAMarkerHover.new
lineWidthSet(@0)
```

**Comment by lhpkxywm** [comment]
> 查看 demo 中的示例代码:
> 
> ## 配置 AAChartModel
> ```objc
> - (AAChartModel *)customSplineChartMarkerStatesHoverStyle {
>     return AAChartModel.new
>     .chartTypeSet(AAChartTypeAreaspline)
>     .titleSet(@"Custom Spline Chart Marker States Hover Style")
>     .categoriesSet(@[
>         @"一月", @"二月", @"三月", @"四月", @"五月", @"六月",
>         @"七月", @"八月", @"九月", @"十月", @"十一月", @"十二月"
>                    ])
>     .markerRadiusSet(@8.0)//marker点半径为8个像素
>     .yAxisLineWidthSet(@0)
>     .yAxisGridLineStyleSet([AALineStyle styleWithWidth:@0])
>     .legendEnabledSet(false)
>     .seriesSet(@[
>         AASeriesElement.new
>         .nameSet(@"Tokyo Hot")
>         .lineWidthSet(@5.0)
>         .colorSet(AARgbaColor(220, 20, 60, 1.0))//猩红色, alpha 透明度 1
>         .markerSet(AAMarker.new
>                    .statesSet(AAMarkerStates.new
>                               .hoverSet(AAMarkerHover.new
>                                         .fillColorSet(AAColor.whiteColor)
>                                         .radiusSet(@40)
>                                         .lineColorSet(AAColor.greenColor)//设置 AAMarkerHover 外部边缘线颜色
>                                         .lineWidthSet(@20))))//设置 AAMarkerHover 外部边缘线宽度
>         .dataSet(@[@7.0, @6.9, @2.5, @14.5, @18.2, @21.5, @5.2, @26.5, @23.3, @45.3, @13.9, @9.6]),
>                ]);
> }
> ```
> 
> ## 图表效果
> ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-05-27 at 14 45 23](https://user-images.githubusercontent.com/16357599/170646110-c3cee3d3-777e-42c1-a2f0-bd5d7314b6ed.png)
> 
> 通过以上内容可知, 外层边缘线, 实际上是 `AAMarkerHover` 的边缘线属性`line`, 可以通过设置`AAMarkerHover`的边缘线宽度为 0 来隐藏. 代码如下:
> 
> ```objc
> AAMarkerHover.new
> lineWidthSet(@0)
> ```

swift版本并没有lineWidthSet这个属性字段啊

**Comment by AAChartModel** [comment]
对应的 Swift 版本示例代码如下:

```swift
    private func customSplineChartMarkerStatesHoverStyle() -> AAChartModel {
        AAChartModel()
            .chartType(.areaspline)
            .title("Custom Spline Chart Marker States Hover Style")
            .categories(["一月", "二月", "三月", "四月", "五月", "六月",
                         "七月", "八月", "九月", "十月", "十一月", "十二月"])
            .yAxisTitle("")
            .markerRadius(8.0)//marker点半径为8个像素
            .yAxisLineWidth(0)
            .yAxisGridLineWidth(0)
            .legendEnabled(false)
            .series([
                AASeriesElement()
                    .name("Tokyo Hot")
                    .lineWidth(5.0)
                    .color(AARgba(220, 20, 60, 1))//猩红色, alpha 透明度 1
                    .marker(AAMarker()
                        .states(AAMarkerStates()
                            .hover(AAMarkerHover()
                                .fillColor(AAColor.white)
                                .radius(40)
                                .lineColor(AAColor.green)//设置 AAMarkerHover 外部边缘线颜色
                                .lineWidth(20))//设置 AAMarkerHover 外部边缘线宽度
                    ))
                    .data([7.0, 6.9, 2.5, 14.5, 18.2, 21.5, 5.2, 26.5, 23.3, 45.3, 13.9, 9.6]),
            ])
    }
```
