### ISSUE TITLE
柱状图调节

### ISSUE THREAD

**Issue by liujie164** [AAChartModel/AAChartKit#1348]
![image](https://user-images.githubusercontent.com/42240597/171536259-57533844-137b-4b8f-88f8-42670bcdf13d.png)
这个图是其他APP的，我看这个提示框应该用的也是AAChartKit，我想做个一摸一样的，我通过后台截取获取到了他们的数据，数据格式如下：[{date:'00:10',value:10},{date:'00:20',value:10},{date:'00:30',value:10}....]等这种格式。
我尝试设置AAChartModel：如下
AAChartModel *chart = AAObject(AAChartModel);
    [chart setChartType:AAChartTypeColumn];
    [chart setZoomType:AAChartZoomTypeNone];
    [chart setAnimationType:AAChartAnimationBounce]
    [chart setAnimationDuration:@1300];
    [chart setXAxisVisible: NO];
    [chart setXAxisLabelsEnabled: NO];
    [chart setXAxisTickInterval:@3];
    [chart setYAxisVisible: NO];
    [chart setYAxisLabelsEnabled:NO];
    [chart setYAxisTickInterval:@3];
    [chart setBackgroundColor:@"#333333"];
    [chart setSeries:@[
                AAObject(AASeriesElement)///入睡
                    .dataSet([sleepModel rowBeginSleepData]),
                AAObject(AASeriesElement)///浅睡
                    .dataSet([sleepModel rowLightSleepData]),
                AAObject(AASeriesElement)///深睡
                    .dataSet([sleepModel rowDeepSleepData])
     ]];

得到的效果确实如下：
![image](https://user-images.githubusercontent.com/42240597/171538143-ef38acf6-7df1-4d9a-a5bf-25f3514fcc7d.png)

请问大神我改如何调整宽度，我通过borderWidthSet来设置的时候前面4根会变形，宽度都不一致，感谢大神帮下忙

**Comment by AAChartModel** [comment]
基础的柱状图应该无法直接坐到这种效果, 参考相同问题:

* https://github.com/AAChartModel/AAChartKit/issues/1265
