### ISSUE TITLE
请问我可以用 AAChartKit 实现类似于下图这种点击的柱状图高亮的效果吗

### ISSUE THREAD

**Issue by Lewanny** [AAChartModel/AAChartKit#1349]
![image](https://user-images.githubusercontent.com/16652970/173728629-b0631aef-6a23-4a7a-91ca-c39d1f045b6b.png)

**Comment by AAChartModel** [comment]
相同问题:

* https://github.com/AAChartModel/AAChartKit-Swift/issues/365
