### ISSUE TITLE
当页面滚动时，希望隐藏折线图的十字线和高亮点

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1362]
折线图渲染显示完毕后，点击图表先显示出十字线和高亮点，之后如果用户滚动了页面，希望将高亮点和十字线隐藏，也就是恢复到未点击的状态，如何做。找了好久都找不到。这功能产品必须要，很头疼。
![image](https://user-images.githubusercontent.com/12290214/178637713-f576e8b2-c09a-4689-9d72-1f6893728e70.png)

**Comment by AAChartModel** [comment]
参考重复问题:

* https://github.com/AAChartModel/AAChartKit/issues/909

**Comment by lhpkxywm** [comment]
我这个是先显示后再隐藏，不是一开始就隐藏折线图的十字线和高亮点。和上述的问题不太一样啊

**Comment by lhpkxywm** [comment]
> 参考重复问题:
> 
> * [作者您好，请问折线图点击的时候，连接点周围的圆形阴影如何去除？ #909](https://github.com/AAChartModel/AAChartKit/issues/909)

我这个是先显示后再隐藏，不是一开始就隐藏折线图的十字线和高亮点。和上述的问题不太一样啊

**Comment by liuson** [comment]
注入js 设置
chart.pointer.reset();
