### ISSUE TITLE
点击渲染完成后的折线图，显示十字线和高亮点后，点击折线图以外的其它区域，如何隐藏十字线和高亮点

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1363]
![image](https://user-images.githubusercontent.com/12290214/178672910-b76d39cb-fe2b-421f-b5f4-5bd6c150b6b9.png)
swift版本

**Comment by AAChartModel** [comment]
由于 HIghcharts 未提供对外开发的隐藏准星线和动态取消高亮的接口, 暂时为想到比较优雅的解决方案.


可以试试:

在点击折线图以外的其他区域时, 直接调用 AAChartView 的重绘方法, 直接重绘整个图表.

**Comment by lhpkxywm** [comment]
> 由于 HIghcharts 未提供对外开发的隐藏准星线和动态取消高亮的接口, 暂时未想到什么比较优雅的解决方案.
> 
> 不过可以试试:
> 
> * 在点击折线图以外的其他区域时, 直接调用 AAChartView 的重绘方法, 直接重绘整个图表.

这样图表会闪的吧。而且性能消耗也大啊
