### ISSUE TITLE
如何获取点击的数据对象所在的坐标y的值？

### ISSUE THREAD

**Issue by Maxcucurbit** [AAChartModel/AAChartKit#1369]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/11735014/181499260-08599ce0-9633-4070-b3fa-e67af117ccb6.png">
我自定义了一条用图片做的选中线，我想根据点击的对象的坐标Y来设置选中线的坐标Y值，我发现通过clickEventMessage回调获取的offsetY值是相对于图表Y轴起点的位置，我想获取到选中数据的屏幕绝对坐标Y值该如何获取呢？请大佬帮帮忙，或者告诉我图表Y轴的起始坐标也行。

**Comment by AAChartModel** [comment]
```objc
@interface AAEventMessageModel : NSObject

@property (nonatomic, copy)   NSString *name;
@property (nonatomic, strong) NSNumber *x;
@property (nonatomic, strong) NSNumber *y;
@property (nonatomic, copy)   NSString *category;
@property (nonatomic, strong) NSDictionary *offset;
@property (nonatomic, assign) NSUInteger index;

@end
```


这个

```objc
@property (nonatomic, strong) NSNumber *y;
```

不是代表的是 **坐标Y值** 吗?  使用起来有问题吗?

**Comment by AAChartModel** [comment]
参考在线 API:

*  https://api.highcharts.com/class-reference/Highcharts.Point#plotX

我估计这里的

plotX :number|undefined
The translated X value for the point in terms of pixels. Relative to the X axis position if the series has one, otherwise relative to the plot area. Depending on the series type this value might not be defined.

Type:
number | undefined
plotY :number|undefined
The translated Y value for the point in terms of pixels. Relative to the Y axis position if the series has one, otherwise relative to the plot area. Depending on the series type this value might not be defined.

Type:
number | undefined


应该就是你想要的那两个坐标属性.

**Comment by AAChartModel** [comment]
参考问题:
* https://stackoverflow.com/questions/16617129/what-are-the-plotx-ploty-values-of-a-point-in-highcharts

**Comment by Maxcucurbit** [comment]
其实我尝试通过点击回调来获取 moveOverEventMessage.offset.plotX 但是这个属性是相对于图表内的，如果我能知道图表的X轴和Y轴的原点位置，或者给我ToolTip的origin.y我就可以做到联动效果了

**Comment by Maxcucurbit** [comment]
<img width="768" alt="image" src="https://user-images.githubusercontent.com/11735014/181675010-705f488b-7552-4bd3-b556-093fd658e458.png">
其实就是想获取这个tooltip点的位置，有办法获取到吗

**Comment by Maxcucurbit** [comment]
> 参考问题:
> 
> * https://stackoverflow.com/questions/16617129/what-are-the-plotx-ploty-values-of-a-point-in-highcharts

能否告诉我这个Marker的绘制在哪个源文件里，我想找到这个坐标直接公开出来

**Comment by AAChartModel** [comment]
> 能否告诉我这个Tooltiop或者Marker的绘制在哪个源文件里

AAChartKit 中的所依赖的 HIghcharts 文件, 其实已经是编译压缩后的 release 版本的 JavaScript 文件了, 在 AAChartKit 包中的名称为 `AAHighcharts.js`,.

 你如果真要看源代码文件, 可以查看 Highcharts 的官方的 TypeScript 的仓库内容.

链接地址: 

* https://github.com/highcharts/highcharts

**Comment by Maxcucurbit** [comment]
> 
哎，没有其他办法来取得这个坐标了吗

**Comment by Maxcucurbit** [comment]
> > 能否告诉我这个Tooltiop或者Marker的绘制在哪个源文件里
> 
> AAChartKit 中的所依赖的 HIghcharts 文件, 其实已经是编译压缩后的 release 版本的 JavaScript 文件了, 在 AAChartKit 包中的名称为 `AAHighcharts.js`,.
> 
> 你如果真要看源代码文件, 可以查看 Highcharts 的官方的 TypeScript 的仓库内容.
> 
> 链接地址:
> 
> * https://github.com/highcharts/highcharts

还有其他办法来获取这个坐标吗？现在项目卡在这了

**Comment by AAChartModel** [comment]
查看此次提交 https://github.com/AAChartModel/AAChartKit-Swift-Pro/commit/4214c18c532f959d210f6f20544cd59010f0eec9 的内容.

**Comment by AAChartModel** [comment]
获取用户点击位置的代码逻辑, 参考:
 * https://www.highcharts.com/forum/viewtopic.php?t=11983
 * https://developer.mozilla.org/zh-CN/docs/Web/API/Element/getBoundingClientRect

**Comment by AAChartModel** [comment]
附言: 由于此方法获取的 DOMRect 值, 不是 Highcharts 的点击事件中获取的标准内容, 所以我没有将其放在 `AAEventMessageModel`中

```objc
@available(iOS 10.0, macCatalyst 13.1, macOS 10.13, *)
public class AAEventMessageModel: NSObject {
    public var name: String?
    public var x: Float?
    public var y: Float?
    public var category: String?
    public var offset: [String: Any]?
    public var index: Int?
}
```

因此如上面所说, 需要你自己自定义实现图表点击事件. 具体逻辑, 参考 AAChartKit-Swift-Pro 项目 demo 中的 

* CustomClickEventCallbackMessageVC

文件中的代码内容.



NOTE: 自定义**click**事件后, 就不能用 AAChartView 中的默认的**click**事件代理方法了, 因为肯定会冲突.
同理, 如果你自定义**move over**事件后, 就不能用 AAChartView 中的默认的**move over**事件代理方法了

**Comment by kedu** [comment]
怎么只能点击了不能滑动了

**Comment by kedu** [comment]
能不能重载click方法而不是重新写

**Comment by kedu** [comment]
oc版本有吗？
