### ISSUE TITLE
图表中的Y轴的相对于VC或者相对于ChartView的origin原点该怎么获取？

### ISSUE THREAD

**Issue by Maxcucurbit** [AAChartModel/AAChartKit#1370]
图表中的Y轴的相对于VC或者相对于ChartView的起始坐标该怎么获取？，比如chartview的origin点是(x:10,y:50),那么当图表完成绘制后，它的Y轴YAxis的位置怎么获取？我发现如果Y轴的位置会跟随它的文字来变化

**Comment by AAChartModel** [comment]
参考已解决的问题: 

* #1369
