### ISSUE TITLE
这种样式能实现吗

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1371]
如图，需要拉一根线显示最高点和最低点的值，如果最高最低点在右侧，则线向左拉
![image](https://user-images.githubusercontent.com/12290214/182281399-f5a0cefb-c78f-411a-b9d5-338425f3b7a6.png)

**Comment by AAChartModel** [comment]
不支持此功能.

**Comment by AAChartModel** [comment]
不过 Highcharts 的标注功能或许有一定参考价值. 

在线示例: https://www.highcharts.com/demo/annotations


不过标注功能需要引入额外的标注模块 `annotations.js`

```html
<script src="https://code.highcharts.com/modules/annotations.js"></script>

```

AAChartKit 本身未包含这部分模块内容. 如果你要使用的话, 需要自行下载导入这部分内容至 AAChartKit 中.

**Comment by AAChartModel** [comment]
如果只是单纯地想要标注最大值和最小值, 参考:

* https://github.com/AAChartModel/AAChartKit/issues/1203

**Comment by lhpkxywm** [comment]
> 不过 Highcharts 的标注功能或许有一定参考价值.
> 
> 在线示例: https://www.highcharts.com/demo/annotations
> 
> 不过标注功能需要引入额外的标注模块 `annotations.js`
> 
> ```
> <script src="https://code.highcharts.com/modules/annotations.js"></script>
> ```
> 
> AAChartKit 本身未包含这部分模块内容. 如果你要使用的话, 需要自行下载导入这部分内容至 AAChartKit 中.

如何导入这个js到aachartkit呢？

**Comment by AAChartModel** [comment]
> 如何导入这个js到aachartkit呢？

你需要先确定一下, 这个标注功能是否能够满足你的需求, 确定可以满足你的需求的话, 我再写一个示例给你参考一下

**Comment by AAChartModel** [comment]
不知道你这个需求中的图表, 是否支持缩放功能, 如果不需要缩放功能的话, 这个水平细线和文字内容, 你完全可以用原生的 UIView 来自绘.

获取数据点对应的坐标, 参考: 

* https://github.com/AAChartModel/AAChartKit/issues/1369
