### ISSUE TITLE
如图，希望marker的位置根据数据的特点向上或者向下偏移一点

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1377]
![47BEA53BA7DE0D309567B9501E752D4E](https://user-images.githubusercontent.com/12290214/183373347-aa5aeec5-cfc1-45d3-92de-6af153a0a2cd.jpg)
能做到吗？

**Comment by AAChartModel** [comment]
查看文档:

* https://api.highcharts.com/highcharts/series.area.marker

可以看到 marker 只有设置宽高的属性, 没有设置坐标的功能.

**Comment by AAChartModel** [comment]
不过可以使用 data 的 AADataElement 来间接实现这种效果:

打开 Highcharts 在线编辑器:
* https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/point/datalabels/

将其中的默认实例代码, 修改为如下配置:
```js
Highcharts.chart('container', {

    chart: {
        marginRight: 50
    },

    series: [{
        data: [29.9, 71.5, 106.4, 129.2, 144.0, {
            dataLabels: {
                enabled: true,
                align: 'left',
                style: {
                color:"red",
                    fontWeight: 'bold',
                    fontSize:"15px"
                },
                format:"▼",
                x: -12,
                y: -12,
                verticalAlign: 'middle',
                overflow: true,
                crop: false
            },
            y: 299.4
        }, 135.6, 148.5, 216.4, 194.1, 95.6, {
            dataLabels: {
                enabled: true,
                align: 'left',
                style: {
                color:"green",
                    fontWeight: 'bold',
                    fontSize:"15px"
                },
                format:"▲",
                x: -12,
                y: +12,
                verticalAlign: 'middle',
                overflow: true,
                crop: false
            },
            y: 54.4
        }]
    }]

});
```

便可得到如下效果:
<img width="548" alt="截屏2022-08-08 下午10 35 15" src="https://user-images.githubusercontent.com/16357599/183443316-e86f3e61-08fa-43e3-ad1c-2575780121b9.png">

**Comment by AAChartModel** [comment]
方法 2:

或者

* 额外创建一个只有最大值和最小值两个 data 元素的散点图, 形成混合图
* 同时禁用散点图的 tooltip 

差不多也能形成你设计稿的那种效果.

**Comment by AAChartModel** [comment]
方法 3:

直接获取最大值和最小值的坐标点, 自绘原生 UIView 视图于图表之上.

获取坐标点的值, 方法参考:

* https://github.com/AAChartModel/AAChartKit/issues/1369#issuecomment-1207725206
