### ISSUE TITLE
如何去除饼状图各部分之间的白色分割线

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1378]
![image](https://user-images.githubusercontent.com/12290214/183581239-1a4a0055-1311-47b9-93ee-38675e439984.png)
如图。

**Comment by AAChartModel** [comment]
参考:

* https://github.com/AAChartModel/AAChartKit/issues/1013

**Comment by AAChartModel** [comment]
设置 border 边缘线的宽度为 0, 应该就可以直接去除你所说的白色分割线了.

**Comment by mapleleaf99** [comment]
<img width="242" alt="image" src="https://github.com/AAChartModel/AAChartKit/assets/23233548/3beb72c6-7228-4c9a-b38c-c5a77afff16d">
总个数有五个，其中一个有值（100），其他四个的值为0，会有这样一条线，如何去掉
