### ISSUE TITLE
加载视图空白

### ISSUE THREAD

**Issue by lijiajunios** [AAChartModel/AAChartKit#1379]
contentHeight 和contentWidth 加上了还是空白，我把视图本身的颜色设置了也是空白，只有进入界面的一瞬间是设置的颜色

是我的版本问题么，我引入后自动引入7.0.0

**Comment by AAChartModel** [comment]
你的这个json数据明显有问题啊，一个data数字都没有，怎么可能会有图表显示？

**Comment by lijiajunios** [comment]
这个是完整的json数据表，上面那个我只是截取了部分日志，您的代码里面 ChartAdvancedUpdatingFeatureVC 和BasicChartVC  这两个类我直接拖进我自己的项目里面也是无法展示
2022-08-17 09:38:19.771046+0800 seeingFlow[10141:475817] ----------- console log AAOptions JSON information of AAChartView -----------:
{
  "credits" : {
    "enabled" : false
  },
  "touchEventEnabled" : false,
  "chart" : {
    "type" : "line",
    "panning" : false,
    "inverted" : false,
    "polar" : false
  },
  "series" : [
    {
      "lineWidth" : 5,
      "step" : true,
      "name" : "2017",
      "data" : [
        5.0999999999999996,
        32.200000000000003,
        23.300000000000001,
        37.399999999999999,
        23.5,
        40.600000000000001
      ],
      "showInLegend" : true,
      "allowPointSelect" : false,
      "visible" : true
    },
    {
      "lineWidth" : 5,
      "step" : true,
      "name" : "2018",
      "data" : [
        8.0999999999999996,
        39.200000000000003,
        21.300000000000001,
        34.399999999999999,
        24.5,
        35.600000000000001
      ],
      "showInLegend" : true,
      "allowPointSelect" : false,
      "visible" : true
    },
    {
      "lineWidth" : 5,
      "step" : true,
      "name" : "2019",
      "data" : [
        10.1,
        37.200000000000003,
        18.300000000000001,
        28.399999999999999,
        26.5,
        30.600000000000001
      ],
      "showInLegend" : true,
      "allowPointSelect" : false,
      "visible" : true
    },
    {
      "lineWidth" : 5,
      "step" : true,
      "name" : "2020",
      "data" : [
        13.1,
        35.200000000000003,
        16.300000000000001,
        31.399999999999999,
        25.5,
        26.600000000000001
      ],
      "showInLegend" : true,
      "allowPointSelect" : false,
      "visible" : true
    }
  ],
  "clickEventEnabled" : false
}

**Comment by AAChartModel** [comment]
你是通过 cocoaPod 导入的吗?

**Comment by lijiajunios** [comment]
是的，之前是手动拖入的我以为是我拖动的问题，换成了pod也是一样

**Comment by AAChartModel** [comment]
模拟器和真机都是一样的情况吗?

**Comment by AAChartModel** [comment]
你试试将导入的 AAChartKit 文件中的 AAChartView.html 文件中的 这段内容

```html
  <body style="margin:0px 0px 0px 0px;"> 
        <div id="container" style="width:100%; height: 100%;">
        </div>
```

改为

```html
    <body style="margin:0px 0px 0px 0px;">
        
        <p>&nbsp&nbsp&nbsp测试 AAChartKit 的 AAChartView 是否加载正常</P>
        <p>&nbsp&nbsp&nbsp测试 AAChartKit 的 AAChartView 是否加载正常</P>
        <p>&nbsp&nbsp&nbsp测试 AAChartKit 的 AAChartView 是否加载正常</P>
        <p>&nbsp&nbsp&nbsp测试 AAChartKit 的 AAChartView 是否加载正常</P>
        <p>&nbsp&nbsp&nbsp测试 AAChartKit 的 AAChartView 是否加载正常</P>
        <p>&nbsp&nbsp&nbsp测试 AAChartKit 的 AAChartView 是否加载正常</P>
        <p>&nbsp&nbsp&nbsp测试 AAChartKit 的 AAChartView 是否加载正常</P>
      
        <div id="container" style="width:100%; height: 100%;">
        </div>
```

也就是说, 在 div 标签的上方加上

```html
        <p>&nbsp&nbsp&nbsp测试 AAChartKit 的 AAChartView 是否加载正常</P>
```

几段重复`<p>` 这样的HTML 段落标签, 测试看看  AAChartView (也就是 WKWebView) 是否正常加载了.

**Comment by lijiajunios** [comment]
模拟器和真机一样的情况，<p>&nbsp&nbsp&nbsp测试 AAChartKit 的 AAChartView 是否加载正常</P>

**Comment by AAChartModel** [comment]
正常情况下, 如果 WKWebView 加载正常的话, 你添加上的测试代码会像下图红框标记出来的样子, 显示出测试文字内容

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-17 at 10 17 13](https://user-images.githubusercontent.com/16357599/185020459-d8e4d9f2-dce8-4250-8c1c-0f59a63d866e.png)

**Comment by lijiajunios** [comment]
<img width="991" alt="截屏2022-08-17 上午10 23 44" src="https://user-images.githubusercontent.com/22438017/185020701-bc0852b9-1312-4708-9790-5cf23c32ccde.png">

![IMG_7932](https://user-images.githubusercontent.com/22438017/185020721-868c35d1-7e88-4ffe-a28b-5d44c5b928a4.JPG)

**Comment by AAChartModel** [comment]
你再试试将 AAChartView.m 文件的这个方法 `- (NSURLRequest *)getJavaScriptFileURLRequest {...}`加上一句断言, 变为

```objc
- (NSURLRequest *)getJavaScriptFileURLRequest {
    NSString *resourcePath = [[NSBundle bundleForClass:[self class]] resourcePath];
    NSString *bundlePath = [resourcePath stringByAppendingPathComponent:@"/AAChartKitLib.bundle"];
    NSBundle *bundle = [NSBundle bundleWithPath:bundlePath];
    if (!bundle) { //installed manually
        bundle = [NSBundle mainBundle];
    }
    NSString *webPath = [bundle pathForResource:@"AAChartView"
                                         ofType:@"html"
                                    inDirectory:@"AAJSFiles.bundle"];
    NSAssert(webPath.length > 0, @"未成功获🉐 AAChartView.html 文件的加载路径, 请检查导入方式是否正确");
    NSURL *webURL = [NSURL fileURLWithPath:webPath];
    NSURLRequest *URLRequest = [[NSURLRequest alloc] initWithURL:webURL];
    return URLRequest;
}
```

重新运行试试, 看看是否是文件加载路径不正确

**Comment by AAChartModel** [comment]
正常情况下, 打断点, 应该能够看到 webPath 字符串变量的值类似:

`/Users/TestAdminName/Library/Developer/CoreSimulator/Devices/26B42A35-48FD-41E4-9C4C-7B6B7389437B/data/Containers/Bundle/Application/AA03972A-AFDB-41F5-BBBD-2EF4660D4F79/AAChartKitDemo.app/AAJSFiles.bundle/AAChartView.html`

这样的值

**Comment by lijiajunios** [comment]
大概找到具体的原因了, 我在webview的代理里面 didFinishNavigation  增加了 NSLog(@"%@",webView);
他的位置信息是 <AAChartView: 0x160962800; frame = (0 64; 414 512); alpha = 0; opaque = NO; layer = <CALayer: 0x2819981c0>>
加载完成后alpha自动变为了0 需要强制进行转换，self.alpha = 1;  我没有找到这块具体是什么原因，

**Comment by AAChartModel** [comment]
不知道你是不是设置了 AAChartView 的这个 `isClearBackgroundColor` 属性为 YES.

这个属性对应的 setter 方法为:

```objc
- (void)setIsClearBackgroundColor:(BOOL)isClearBackgroundColor {
    _isClearBackgroundColor = isClearBackgroundColor;
#if TARGET_OS_IPHONE
    if (_isClearBackgroundColor) {
        self.backgroundColor = [UIColor clearColor];
        self.opaque = NO;
    } else {
        self.backgroundColor = [UIColor whiteColor];
        self.opaque = YES;
    }
#elif TARGET_OS_MAC
    if (_isClearBackgroundColor) {
        self.layer.backgroundColor = [NSColor clearColor].CGColor;
        self.layer.opaque = NO;
    } else {
        self.layer.backgroundColor = [NSColor whiteColor].CGColor;
        self.layer.opaque = YES;
    }
#endif
}
```

也就是说 `isClearBackgroundColor` 属性为 YES 时 , 会将 `self.backgroundColor = [UIColor clearColor];` WebView 的背景色变为透明色.

**Comment by AAChartModel** [comment]
不过 

* View 的 backgroundÇolor 为 clearColor 
* View 的 alpha 值为 0

这两者应该还是有本质的不同.

所以我也不太清楚是什么情况导致的.

不知道是不是你的项目中有什么全局配置会影响到 WKWebView 的 alpha 值. 或者是 WKWebView 自身有什么潜在 bug.

也有可能是项目中的一些依赖库的 `RunTime` 方法会产生一些意料之外的 bug .

**Comment by lijiajunios** [comment]
不是这个的原因isClearBackgroundColor 我昨天看到了这个api特意设置了一下，因为我在外层设置了背景颜色，他是一闪而过，就没有考虑加载完成后alpha 变为0
也可能是runtime的原因，改天弄完我具体的看一下吧，这边最好也在外层暴漏一个回调，alpha可以在加载完成后进行设置

**Comment by AAChartModel** [comment]
>  这边最好也在外层暴漏一个回调，alpha可以在加载完成后进行设置


```objc
/// The delegate method of chart view finish loading
/// @param aaChartView AAChartView object instance
- (void)aaChartViewDidFinishLoad:(AAChartView *)aaChartView;
```

**Comment by lijiajunios** [comment]
aaChartViewDidFinishLoad/// Set the chart view background alpha
@property (nonatomic, assign) CGFloat isAlpha;

**Comment by AAChartModel** [comment]
```objc
@interface AAChartView:WKWebView
```

AAChartView 是直接继承自 WKWebView 的, 所以你可以直接在设置AAChartView 的 alpha

**Comment by lijiajunios** [comment]
试了无效果，我在在初始化WKWebView  或者init  或者AAChartView 初始化的地方我都增加了背景色以及alpha 通道的方法都无效，只有在didFinishNavigation里面增加 self.alpha =1; 才会正常展示，

**Comment by AAChartModel** [comment]
> > 这边最好也在外层暴漏一个回调，alpha可以在加载完成后进行设置
> 
> ```objc
> /// The delegate method of chart view finish loading
> /// @param aaChartView AAChartView object instance
> - (void)aaChartViewDidFinishLoad:(AAChartView *)aaChartView;
> ```

我的意思是你直接在这个 `AAChartView` 暴露的外部代理方法中设置 `aaChartView` 的 `alpha` 属性即可. 无需额外改动`AAChartView` 的源码, 也无需再为 `AAChartView` 额外添加`CGFloat isAlpha`属性.

**Comment by lijiajunios** [comment]
好的，我稍后改下
