### ISSUE TITLE
填充图盖住了水平的网格线

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1380]
![image](https://user-images.githubusercontent.com/12290214/185286646-4365b3a5-ccc5-480e-87d8-029339fce5d0.png)
红框部分希望显示水平的网格线。

**Comment by AAChartModel** [comment]
参考文档:

* https://api.highcharts.com/highcharts/yAxis.gridZIndex

**Comment by AAChartModel** [comment]
查看 `AAYAxis` 属性

```objc
AAPropStatementAndPropSetFuncStatement(strong, AAYAxis, NSNumber *, gridZIndex) //网格线的层叠值（zIndex） 默认是：1.

```

**Comment by lhpkxywm** [comment]
> 查看 `AAYAxis` 属性
> 
> ```objc
> AAPropStatementAndPropSetFuncStatement(strong, AAYAxis, NSNumber *, gridZIndex) //网格线的层叠值（zIndex） 默认是：1.
> ```

swift版本没有这个属性啊
