### ISSUE TITLE
大佬，关于设置valuePrefix，我看到AATooltip这个类里面是没有这个参数的

### ISSUE THREAD

**Issue by woshigaokeji** [AAChartModel/AAChartKit#1382]
我在文档里面看到了这个参数，https://api.highcharts.com.cn/highcharts/tooltip.pointFormat.html
这个参数是关于前缀值设置的。也可以通过html自定义tip，不过我希望大佬可以在新版本加入这个参数，感谢大佬。目前我项目用的是7.0.0版本

**Comment by AAChartModel** [comment]
```objc
AAPropStatementAndPropSetFuncStatement(copy,   AATooltip, NSString *, formatter) 
AAPropStatementAndPropSetFuncStatement(copy,   AATooltip, NSString *, headerFormat) 
AAPropStatementAndPropSetFuncStatement(copy,   AATooltip, NSString *, pointFormat)
AAPropStatementAndPropSetFuncStatement(copy,   AATooltip, NSString *, pointFormatter)
AAPropStatementAndPropSetFuncStatement(copy,   AATooltip, NSString *, footerFormat) 
```

这几个参数现在都有了, 更新 AAChartKit 至最新内容即可.

**Comment by AAChartModel** [comment]
[valueDecimals:](https://api.highcharts.com.cn/highcharts/tooltip.valueDecimals.html)undefined
[valuePrefix:](https://api.highcharts.com.cn/highcharts/tooltip.valuePrefix.html)undefined
[valueSuffix:](https://api.highcharts.com.cn/highcharts/tooltip.valueSuffix.html)undefined

这几个参数还没加, 有空加下.

**Comment by woshigaokeji** [comment]
好的，感谢大佬

**Comment by woshigaokeji** [comment]
好的，感谢大佬
