### ISSUE TITLE
柱形图tooltip提示框问题

### ISSUE THREAD

**Issue by shi-xinxin** [AAChartModel/AAChartKit#1388]
1.一个画面上绘制了两张柱形图，当点击第一个柱形图时弹出提示框，点击第二个柱形图时要求第一个提示框隐藏。需要如何实现？？
2.柱形图提示框AATooltip()的属性.shared() 设置为false时，点击柱形图空白区域不显示提示框，只有点击到柱子上才显示提示框。

**Comment by AAChartModel** [comment]
> 1.一个画面上绘制了两张柱形图，当点击第一个柱形图时弹出提示框，点击第二个柱形图时要求第一个提示框隐藏。需要如何实现？？

参考:

* https://github.com/AAChartModel/AAChartKit/issues/1093

**Comment by shi-xinxin** [comment]
不是让提示窗显示几秒后隐藏，而是要  在点击第二张图时，第一张图的气泡要隐藏

**Comment by AAChartModel** [comment]
那你试试在第二张图的点击事件handler 方法里, 执行隐藏 第一张图的 tooltip 的方法.

示例如下:

```objc
    __weak typeof(self) weakSelf = self;
    //第 2 个 AAChartView aaChartView1) 的点击事件代理方法
    [_aaChartView2 clickEventHandler:^(AAChartView *aaChartView,
                                      AAClickEventMessageModel *message) {
        NSString *jsFunctionStr = @AAJSFunc(aaGlobalChart.tooltip.hide(888););//设置 tooltip 自动隐藏的时间
        
        //让第 1 个 AAChartView(aaChartView1) 执行 JavaScript 方法
        [weakSelf.aaChartView1 evaluateJavaScript:jsFunctionStr completionHandler:^(id item, NSError * _Nullable error) {
    #if DEBUG
            if (!error) return;
            NSMutableDictionary *errorDic = [NSMutableDictionary dictionary];
            [errorDic setValue:error.domain forKey:@"domain"];
            [errorDic setValue:@(error.code) forKey:@"code"];
            [errorDic setValue:error.userInfo forKey:@"userInfo"];
            
            NSString *basicErrorInfo = @"                                                     \n\
    ☠️☠️💀☠️☠️WARNING!!!!!!!!!!!!!!!!!! JS ERROR WARNING !!!!!!!!!!!!!!!!!!WARNING☠️☠️💀☠️☠️ \
    ⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩⇩  \
    ------------------------------------------------------------------------------------------\n\
    %@                                                                                          \
    ------------------------------------------------------------------------------------------  \
    ⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧⇧\n\
    ☠️☠️💀☠️☠️WARNING!!!!!!!!!!!!!!!!!! JS ERROR WARNING !!!!!!!!!!!!!!!!!!WARNING☠️☠️💀☠️☠️";
            
            NSString *errorInfoStr = [NSString stringWithFormat:basicErrorInfo,errorDic];
            NSLog(@"%@",errorInfoStr);
    #endif
        }];
    }];
```

**Comment by AAChartModel** [comment]
去掉 debug 调试 js 输出信息,. 简写就是这样:

```objc
    __weak typeof(self) weakSelf = self;
    [_aaChartView2 clickEventHandler:^(AAChartView *aaChartView,
                                      AAClickEventMessageModel *message) {
        NSString *jsFunctionStr = @AAJSFunc(aaGlobalChart.tooltip.hide(888););//设置 tooltip 自动隐藏的时间
        
        //让第一个 AAChartView 执行 JavaScript 方法
        [weakSelf.aaChartView1 evaluateJavaScript:jsFunctionStr completionHandler:nil];
    }];
```

**Comment by AAChartModel** [comment]
原理和这个是一样的

* #1093

**Comment by AAChartModel** [comment]
想要立即隐藏, 将这里的

```objc
        NSString *jsFunctionStr = @AAJSFunc(aaGlobalChart.tooltip.hide(888););//设置 tooltip 自动隐藏的时间
```

`888` 改为 `0` 即可.

**Comment by shi-xinxin** [comment]
我绘制的这两张柱形图（实际上会有更多张），是用的一个同一个AAChartView()得到的，所以你上面说的办法不适用吧

**Comment by AAChartModel** [comment]
你是在同一个 AAChartView 里面添加了多个 div, 借以实现在同一个 AAChartView 中绘制多个柱状图📊的?

**Comment by AAChartModel** [comment]
如果你了解 JavaScript, 那就更容易了.

查看 AAChartView.html 文件中的这段内容.

```js
 let aaGlobalChart;
            function loadTheHighChartView(sender, receivedWidth, receivedHeight) {
                let container = document.getElementById('container');
                if (receivedWidth != 0) {
                    container.style.width = receivedWidth;
                }
                if(receivedHeight != 0) {
                    container.style.height = receivedHeight;
                }

                let aaOptions = JSON.parse(sender, function (key, value) {
                    if (typeof (value) == 'string'
                        && value.indexOf('function') !== -1) {
                        return eval(value)
                    }
                    return value;
                });

                if (aaOptions.defaultOptions) {
                    Highcharts.setOptions({
                        lang: aaOptions.defaultOptions
                    });
                }
                
                if (aaOptions.xAxisArray) {
                    aaOptions.xAxis = aaOptions.xAxisArray
                }
                if (aaOptions.yAxisArray) {
                    aaOptions.yAxis = aaOptions.yAxisArray
                }
                
                if (aaOptions.plotOptions) {
                    configurePlotOptions(aaOptions);
                }
                                
                aaGlobalChart = Highcharts.chart('container', aaOptions); //⭐️关键内容
            };
```

可知, 通过 

```js
                aaGlobalChart = Highcharts.chart('container', aaOptions); //⭐️关键内容
```

可获得对应的 chart 实例, 然后就直接调用 chart 实例对应的隐藏 tooltip 方法

```js
aaGlobalChart.tooltip.hide(888);
```

**Comment by shi-xinxin** [comment]
把demo中一张柱形图当成一个View，我在我的绘图区域多次添加这个View，只不过每个View里面的数据不同。然后把这些UIView拼接到一起来显示多张柱形图。    所以  点击第二张柱形图时，我想把上一次点击的提示窗关掉。

**Comment by AAChartModel** [comment]
> 2.柱形图提示框AATooltip()的属性.shared() 设置为false时，点击柱形图空白区域不显示提示框，只有点击到柱子上才显示提示框。

这里不知道你需要的是不是这种效果: 

* https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/tooltip/split/

**Comment by AAChartModel** [comment]
> 把demo中一张柱形图当成一个View，我在我的绘图区域多次添加这个View，只不过每个View里面的数据不同。然后把这些UIView拼接到一起来显示多张柱形图。 所以 点击第二张柱形图时，我想把上一次点击的提示窗关掉。

从你的描述来看, 好像是同一个页面多次 add 同一个 AAChartView 实例对象. 然而我记得同一个 AAChartView 实例对象不能同时显示不同的图表内容吧

能复制粘贴一下你现在的使用代码实例吗?不方便的话, 用伪代码表示也行.

**Comment by shi-xinxin** [comment]
我大概说一下吧  主要是内部的这个View
这是一个自定义的View
private var aaChartModel: AAChartModel!
    private var aaChartView: AAChartView!
    private var columns: [AASeriesElement] = []
    
    init(frame: CGRect,
         data1: [Double],
         data2: [Double]) {
        super.init(frame: frame)
        columns = [AASeriesElement().data([22,24,25])
            .color(AAColor.blue)
            .borderColor(AAColor.red)
            .borderWidth(2),
                   AASeriesElement().data([29,27,26])
            .color(AAColor.purple)
            .borderColor(AAColor.orange)
            .borderWidth(2)
        ]
        configureChart()
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    private func configureChart() {
        aaChartView = AAChartView()
        aaChartView.scrollView.isScrollEnabled = false
        let chartWidth = bounds.width
        let chartHeight = bounds.height
        aaChartView.frame = CGRect(x: 0, y: 0, width: chartWidth, height: chartHeight)
        self.addSubview(aaChartView)
        
        aaChartModel = AAChartModel()
            .chartType(.column)
            .legendEnabled(false)
            .inverted(true)
            .xAxisReversed(true)
            .xAxisReversed(false)
            .yAxisVisible(false)
            .yAxisGridLineWidth(0)
            .stacking(.normal)
            .series(columns)
        
        let aaOptions = AAOptionsConstructor.configureChartOptions(aaChartModel)
        aaOptions.plotOptions?
            .column?
            .groupPadding(0)
            .pointPadding(0)
        aaOptions.chart?.marginLeft(10)
        aaOptions.chart?.marginRight(10)
        aaOptions.chart?.marginTop(10)
        aaOptions.chart?.marginBottom(10)
        
        let aaTooltip = AATooltip()
            .enabled(true)
            .shared(true)
        
        aaTooltip.useHTML(true)
            .valueDecimals(2)
            .backgroundColor(AAColor.yellow)
            .borderColor(AAColor.red)
            .style(
                AAStyle()
                    .color(AAColor.black)
                    .fontSize(12)
            )
        aaOptions.tooltip(aaTooltip)

        aaChartView.aa_drawChartWithChartOptions(aaOptions)
    }


外部定义一个方法func A()来初始化这View，给它需要的数据。

这个func A()在一个循环里面，根据实际需求，add多个柱形图这个自定义的View。

**Comment by AAChartModel** [comment]
这样的话, 那道理还是一样的, 你在这个自定义的 View 中, 添加一个 block 或者是 delegate, 把自定义 view 内部的 AAChartView 的方法包装出去, 同时把 AAChartView 的隐藏 tooltip 的方法包装出去.  

这样, 隐藏 tooltip 的逻辑就和直接用 AAChartView 类似了.
