### ISSUE TITLE
睡眠图效果

### ISSUE THREAD

**Issue by yunyuchen** [AAChartModel/AAChartKit#1390]
![3affe881b56a9919a1d8403b3b70ce8](https://user-images.githubusercontent.com/7653015/189067472-fe1356aa-3944-41e2-980a-5cb21397f060.jpg)
您好，请问像这样的图表我们的开源库能实现这样的效果吗？

**Comment by AAChartModel** [comment]
你的这个睡眠图设计样式太特殊了, 无法支持. 仅支持这种常规类型的睡眠图:

* #873 
* #1158

**Comment by yunyuchen** [comment]
好的 谢谢

**Comment by userObjectc** [comment]
实现了么? 可以发我一份吗?

**Comment by ghjjane** [comment]
同问，实现了吗？
