### ISSUE TITLE
如何给单独一个点设置图片？

### ISSUE THREAD

**Issue by kedu** [AAChartModel/AAChartKit#1396]
试了AADataElement的markerSet，用base64是无效的

**Comment by AAChartModel** [comment]
参考:
* //https://github.com/AAChartModel/AAChartKit/issues/695

**Comment by AAChartModel** [comment]
以上稍作修改后的示例代码, `base64Symbol` 常量可在 AAChartKit 的 demo 中找到.

**Comment by kedu** [comment]
好的

**Comment by AAChartModel** [comment]
参考文档:
* https://api.highcharts.com.cn/highcharts/series.line.marker.html (中文官网)
* https://api.highcharts.com/highcharts/series.line.marker.html (英文官网)
