### ISSUE TITLE
Tooltip only appears on tap, but not when I move the finger

### ISSUE THREAD

**Issue by skuske** [AAChartModel/AAChartKit#140]
That has actually changed: I now have to tap onto a graph to make the tooltip appear. Before I was able to tap and keep the finger on the graph and the tooltip remained visible, but was updating with the position of my finger...

**Comment by AAChartModel** [comment]
🤣Since I want to support dragging a chart with single finger on my phone after the chart is enlarged, that function conflicts with the function you want.I have removed the code now

**Comment by skuske** [comment]
OK, understood. However, I would leave it like that as in the original iOS wrapper for HighCharts dragging is done by two fingers, too...
