### ISSUE TITLE
X轴的文字能固定显示指定的几个吗？

### ISSUE THREAD

**Issue by Maxcucurbit** [AAChartModel/AAChartKit#1402]
我有两个问题请教一下：
1.比如一个图表显示的数据超过100个，但是我只想让X轴文字显示["00:00", "04:00", "08:00", "12:00", "16:00", "20:00", "23:59"]，我该如何设置？
2.是否支持不连续的曲线图表？

**Comment by AAChartModel** [comment]
> 1.比如一个图表显示的数据超过100个，但是我只想让X轴文字显示["00:00", "04:00", "08:00", "12:00", "16:00", "20:00", "23:59"]，我该如何设置？


参考:
* #480 
* #762

**Comment by AAChartModel** [comment]
> 2.是否支持不连续的曲线图表？

参考:
* #1220 
* #1265

**Comment by Maxcucurbit** [comment]
> 

多谢！
