### ISSUE TITLE
请问这种效果可以实现吗?我们这边很多都是toolTip的尖角在一边的,需求有点奇葩

### ISSUE THREAD

**Issue by wangfang871111** [AAChartModel/AAChartKit#1406]
请问这种效果可以实现吗?我们这边很多都是toolTip的尖角在一边的,需求有点奇葩
<img width="341" alt="双曲线" src="https://user-images.githubusercontent.com/16934606/194744125-565882cd-b428-445a-8e62-ae5fde66f34f.png">
不胜感激

**Comment by AAChartModel** [comment]
参考:
* https://www.highcharts.com/forum/viewtopic.php?f=9&t=49629

**Comment by AAChartModel** [comment]
参考此次提交的内容, 查看如何配置 AAOptions
* https://github.com/AAChartModel/AAChartKit/commit/31565002bdb6dd72ed144a6562e4f37f9a142305

**Comment by wangfang871111** [comment]
大神牛逼,不剩感激
