### ISSUE TITLE
请问可拖拽图表怎么监测开始滑动事件呢

### ISSUE THREAD

**Issue by Yates-yang** [AAChartModel/AAChartKit#1409]
请问可拖拽图表怎么监测开始滑动事件呢，试了用scollviewdelegate发现没响应，请问是否有别的接口监测呢

**Comment by AAChartModel** [comment]
不支持此功能, 因为 Highcharts 未提供接口. 
参考文档: https://api.highcharts.com/highcharts/chart.scrollablePlotArea
