### ISSUE TITLE
如何设置折线图的x轴，x轴过多显示不美观

### ISSUE THREAD

**Issue by yangmiaomiao-coder** [AAChartModel/AAChartKit#1416]
如何设置折线图的x轴，x轴过多显示不美观

**Comment by AAChartModel** [comment]
参考: 
* #633
* #1386

**Comment by yangmiaomiao-coder** [comment]
试过了，没用
















在 2022-10-28 10:13:21，"An An" ***@***.***> 写道：

参考:

#633
#1386
