### ISSUE TITLE
怎么才能去掉底下的“series1”这几个字符呢

### ISSUE THREAD

**Issue by yangmiaomiao-coder** [AAChartModel/AAChartKit#1418]

**Comment by AAChartModel** [comment]
如果你希望显示图例的同时, 隐藏字符, 可以直接为 AASeriesElement 的 name 设置空字符串 `@"" ` 即可.

**Comment by AAChartModel** [comment]
如果你希望直接隐藏图例的
* 可以直接将 AAChartModel 的 legendEnabled 设置为 `false` 
* 或者直接将 AAOptions 的 AALegend 的 enabled 属性设置为 `false`
