### ISSUE TITLE
X轴的显示,可以控制最多显示格数吗

### ISSUE THREAD

**Issue by guochao285575** [AAChartModel/AAChartKit#142]
![image](https://user-images.githubusercontent.com/16434139/35553539-45352b06-05d3-11e8-9c6d-90eae68d19fb.png)

### 期待作者的回复

**Comment by AAChartModel** [comment]
应该是可以的,等我后面稍微改一下

**Comment by AAChartModel** [comment]
```objective-c       
_aaChartModel.xAxisTickInterval = @3;//设置 X轴坐标点的间隔数,默认是1
```
手机端的屏幕较为狭窄, 如果X轴坐标点过多,文字过于密集的时候可以设置此属性值,用户的密集恐惧症将得到有效治疗😝
