### ISSUE TITLE
柱状图如何自定义柱子的宽度呢

### ISSUE THREAD

**Issue by zhongxunchao** [AAChartModel/AAChartKit#1421]
目前看起来是根据图表的整体宽度和柱子数量计算出来的宽度，如果想要自定义宽度，要怎么做？

**Comment by AAChartModel** [comment]
直接设置柱状图📊的柱子的宽度, 参考:
* https://github.com/AAChartModel/AAChartKit/issues/1381

**Comment by AAChartModel** [comment]
参考:
* #1295

**Comment by AAChartModel** [comment]
另参考:
* https://github.com/AAChartModel/AAChartKit/issues/1381

直接设置柱子宽度, 如果过大的话, 会出现柱子之间彼此遮盖的问题. 如图:

![](https://user-images.githubusercontent.com/16357599/187337952-24609eff-70f1-4095-b9cb-9a72c41ea16e.png)

**Comment by AAChartModel** [comment]
参考在线文档:
* https://api.highcharts.com/highcharts/series.column.pointWidth
