### ISSUE TITLE
曲线图上mark点的默认光圈可以去掉吗？

### ISSUE THREAD

**Issue by zhongxunchao** [AAChartModel/AAChartKit#1423]
如下图所示，绘制一条或多条曲线的情况下，总会有一条默认曲线在点击mark点后，mark点周围展示一圈半透明的光圈（红色箭头所指）。这个光圈可以去除吗？
![1668042093401](https://user-images.githubusercontent.com/10545093/200974842-2c21f660-37fa-4ad0-941e-011441324e56.jpg)

**Comment by AAChartModel** [comment]
重复问题, 参考:
* https://github.com/AAChartModel/AAChartKit/issues/909

**Comment by zhongxunchao** [comment]
> 重复问题, 参考:
> 
> * [作者您好，请问折线图点击的时候，连接点周围的圆形阴影如何去除？ #909](https://github.com/AAChartModel/AAChartKit/issues/909)

这里只是想去除外层的光圈，内部的mark点仍然保留。设置过AAMarkerHover.new.enabledSet(false)之后，mark点也看不见了。

**Comment by AAChartModel** [comment]
参考:
* https://github.com/AAChartModel/AAChartKit/issues/1345
