### ISSUE TITLE
修改提示框里面文字大小和精确到小数点后两位没效果

### ISSUE THREAD

**Issue by LH0120** [AAChartModel/AAChartKit#1426]
element.tooltip.style.fontSize = @"8";
element.tooltip.style.fontWeight = @"thin";
element.tooltip.valueDecimals = @2;

_chartModel.aa_toAAOptions.tooltip.style.fontSize = @"8";
_chartModel.aa_toAAOptions.tooltip.style.fontWeight = @"thin";
_chartModel.aa_toAAOptions.tooltip.valueDecimals = @2;

用这两种方式修改提示框里面文字大小和精确到小数点后两位都没效果，请问下是用错了吗？

**Comment by LH0120** [comment]
已解决

**Comment by xubillde** [comment]
@LH0120 解决代码是咋样的
