### ISSUE TITLE
折线填充图 准星线高度能否调整

### ISSUE THREAD

**Issue by Suzhibin** [AAChartModel/AAChartKit#1427]
作者的框架 真好。但需求千变万化，我目前还差几个细节，无法找到解决办法。帮我看看
![企业微信截图_295a811a-d2f2-413b-85a3-981ad9002784](https://user-images.githubusercontent.com/18522008/205531661-cd41e5a9-102b-45b6-a232-eeb1546839fc.png)
1.准星线高度  能否调整，（翻了提问 ，好像不能）
2.X 轴坐标文字和dataLabels的文字 能否点击改变颜色
3.X  轴坐标第一个和最后一个 填充区 可以 外延一定距离吗？

**Comment by AAChartModel** [comment]
> 1.准星线高度 能否调整，（翻了提问 ，好像不能）


参考:

* https://github.com/AAChartModel/AAChartKit/issues/1383

**Comment by Suzhibin** [comment]
> > 1.准星线高度 能否调整，（翻了提问 ，好像不能）
> 
> 参考:
> 
> * [x轴的y值指示线(动态高度)效果实现 #1383](https://github.com/AAChartModel/AAChartKit/issues/1383)

感谢 ，但不是网格线 ，是AACrosshair

**Comment by AAChartModel** [comment]
参考我在Highcharts官方社区的提问内容:
* https://www.highcharts.com/forum/viewtopic.php?f=9&t=49985&sid=54de847301d2042bcdd36559b56282fc
