### ISSUE TITLE
折线下方添加标识问题

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1428]
如下图，我需要在折线图表的最左下原点下方的位置添加一个上三角▲的符号。我尝试给原点的数据设置AADataElement，但是折线没有绘制出来，疑似是想要绘制的上三角▲超出了图表有效区域。如之奈何
![image](https://user-images.githubusercontent.com/12290214/205556643-d69dc81d-00b8-4dc4-a48f-514d10cef3c8.png)
如何给Y轴和折线图区域之间增加额外的距离以便能够绘制出上三角▲符号呢？

**Comment by AAChartModel** [comment]
试试 AASeriesElement 的这个属性

```swift
    public var threshold: Float?           //The threshold, also called zero level or base level. For line type series this is only used in conjunction with negativeColor. default：0.
```

**Comment by AAChartModel** [comment]
参考文档:

* https://api.highcharts.com.cn/highcharts/series.line.threshold.html

**Comment by AAChartModel** [comment]
将 threshold 这个值设置的比默认的 0 小一些, 或许可以使得图表的底部让出一部分空间来显示你需要的标志

**Comment by lhpkxywm** [comment]
> 将 threshold 这个值设置的比默认的 0 小一些, 或许可以使得图表的底部让出一部分空间来显示你需要的标志

我试了下没用唉，并且根据深度测试，不是底部空间不够，是左侧空间不够。因为它是数据的第一个点，在最左边，所以显示不出来。则呢么增加左侧的额外空间呢

**Comment by AAChartModel** [comment]
这个我就不清楚了, 你可以在 Highcharts 官方社区问问, 
* Highcharts 的 GitHub 主页 https://github.com/highcharts/highcharts
* 或者是 Highcharts 的官方的专门论坛 https://www.highcharts.com/forum/

原理应该都是一样的

**Comment by AAChartModel** [comment]
或者你额外新增一个散点图类型的 AASeriesElement, 然后禁用交互事件应该勉强也行

**Comment by AAChartModel** [comment]
或者直接调用 Highcharts 提供的自绘  DataLabel 的方法, Highcharts 自身也有这部分自绘图表内容的功能.
