### ISSUE TITLE
为什么NSNumber用assign修饰？ 开启编译优化后会崩溃

### ISSUE THREAD

**Issue by kedu** [AAChartModel/AAChartKit#1434]
AAPropStatementAndPropSetFuncStatement(assign, AAYAxis, NSNumber *, minRange)

**Comment by kedu** [comment]
现在把历史版本的这个改成strong就正常了，发现还有number用assign修饰，所以过来问下原因
AAPropStatementAndPropSetFuncStatement(strong, AAYAxis, NSNumber *, max)  //y轴最大值
AAPropStatementAndPropSetFuncStatement(strong, AAYAxis, NSNumber *, min)  //y轴最小值（设置为0就不会有负数）

**Comment by AAChartModel** [comment]
不知道你是不是用的之前的某一个版本的 AAChartKit, 我看最新的代码是正确的

```objc
AAPropStatementAndPropSetFuncStatement(strong, AAYAxis, NSNumber *, minRange)
```

**Comment by kedu** [comment]
还以为有特殊原因，没特殊原因的话我NSNumber全改strong就可以了
