### ISSUE TITLE
ZoomButton 隐藏的问题

### ISSUE THREAD

**Issue by Suzhibin** [AAChartModel/AAChartKit#1435]
以下代码 配置 无法隐藏 缩放按钮，还有新的方法吗

```objc
    aaOptions.chart
    .resetZoomButtonSet(AAResetZoomButton.new
                        .themeSet(@{
                            @"display":@"none"//隐藏图表缩放后的默认显示的缩放按钮
                                  }));
```

**Comment by AAChartModel** [comment]
参考: https://www.highcharts.com/forum/viewtopic.php?f=9&t=46196

**Comment by AAChartModel** [comment]
参考官方 API:  https://api.highcharts.com/highcharts/chart.resetZoomButton.theme

此 API 已被标记为`Deprecated 10.2.1 废弃`.

**Comment by AAChartModel** [comment]
> 参考: https://www.highcharts.com/forum/viewtopic.php?f=9&t=46196

通过官方论坛给出的回复示例来看, 最新的配置方式如下:

```objc
    aaOptions.chart
    .resetZoomButtonSet(AAResetZoomButton.new
                        .themeSet(@{
                            @"style": @{
                                @"display":@"none"//隐藏图表缩放后的默认显示的缩放按钮
                            }
                        }));
```

**Comment by Suzhibin** [comment]
> > 参考: https://www.highcharts.com/forum/viewtopic.php?f=9&t=46196
> 
> 通过官方论坛给出的回复示例来看, 最新的配置方式如下:
> 
> ```objc
>     aaOptions.chart
>     .resetZoomButtonSet(AAResetZoomButton.new
>                         .themeSet(@{
>                             @"style": @{
>                                 @"display":@"none"//隐藏图表缩放后的默认显示的缩放按钮
>                             }
>                         }));
> ```

好使，太感谢了。
