### ISSUE TITLE
x轴文案可以用图片代替吗？

### ISSUE THREAD

**Issue by kedu** [AAChartModel/AAChartKit#1438]

**Comment by AAChartModel** [comment]
重复问题, 参考;
* https://github.com/AAChartModel/AAChartKit/issues/938

**Comment by AAChartModel** [comment]
此方法在雷达图中可能有问题, 参考:
* https://github.com/AAChartModel/AAChartKit/issues/1139

**Comment by AAChartModel** [comment]
参考 Highcharts 官方在线示例链接:
*  https://www.highcharts.com/demo/column-comparison
