### ISSUE TITLE
请问如何隐藏x轴的描述文案，如创建表格使用里程和耗电，x轴位值就会显示这两个文案，这个可以隐藏吗

### ISSUE THREAD

**Issue by spikeroog** [AAChartModel/AAChartKit#1439]
请问如何隐藏x轴的描述文案，如创建表格使用里程和耗电，x轴位值就会显示这两个文案，这个可以隐藏吗

**Comment by AAChartModel** [comment]
不太清楚你说的是哪两个文案

**Comment by spikeroog** [comment]
![](https://resource-upload-server.oss-cn-beijing.aliyuncs.com/Xnip2023-01-10_13-55-37.png)
如图红框内的内容，请问如何隐藏啊

**Comment by AAChartModel** [comment]
这部分内容是 AALegend(图例).

参考相同问题:
* https://github.com/AAChartModel/AAChartKit/issues/1418

**Comment by AAChartModel** [comment]
参考:
* https://github.com/AAChartModel/AAChartKit/issues/399

**Comment by spikeroog** [comment]
成功隐藏掉了，谢谢，最后请教下柱状图的单个柱的宽度如何设置，我想给它缩窄一些

**Comment by AAChartModel** [comment]
参考:
* https://github.com/AAChartModel/AAChartKit/issues/1295

**Comment by AAChartModel** [comment]
* **间接设置宽度**

参考:
* https://github.com/AAChartModel/AAChartKit/issues/537

**Comment by spikeroog** [comment]
> * **间接设置宽度**
> 
> 参考:
> 
> * [柱状图 categoriesSet一条数据，怎么控制柱体的宽度和柱体之间的间隙？ #537](https://github.com/AAChartModel/AAChartKit/issues/537)

好的谢谢，已解决

**Comment by spikeroog** [comment]
![](https://resource-upload-server.oss-cn-beijing.aliyuncs.com/Xnip2023-01-10_15-09-40.png)
现在设置AALegend隐藏后，东西是隐藏了，但是底部的间距还在呢，请问如果去掉这部分间距，把上面的chart图标顶下来呢

**Comment by AAChartModel** [comment]
参考:

* https://github.com/AAChartModel/AAChartKit/issues/776
* https://github.com/AAChartModel/AAChartKit/issues/1284
* https://github.com/AAChartModel/AAChartKit/issues/1408

**Comment by AAChartModel** [comment]
参考 Highcharts 在线 API 文档:

*  https://api.highcharts.com/highcharts#chart.margin
