### ISSUE TITLE
大神，y轴显示问题，这个怎么显示原有的值呢，我这边被转换成 k，希望显示原来的值

### ISSUE THREAD

**Issue by songbai1211** [AAChartModel/AAChartKit#144]
![eecccabb-976e-498c-9d61-40bf87f1a3fd](https://user-images.githubusercontent.com/4758161/35602945-e60f6c6a-0675-11e8-88f9-099e32ef577d.png)
数据如果转换，但是没有全部被转化，这个在哪里修改啊，大神，求救

**Comment by AAChartModel** [comment]
现在已经修改为默认Y轴显示原有的数值,不进行自动转化缩写

**Comment by songbai1211** [comment]
太感谢了，

**Comment by AAChartModel** [comment]
话说兄弟你用过了 原生的charts这个库了吗?感觉怎么样?

**Comment by songbai1211** [comment]
没用过，我看那个太复杂，我就不想用了，你这个很给力，各种自定义，大赞，强推，

**Comment by AAChartModel** [comment]
是啊,我已开始是想用那个 charts, 结果配置过程太复杂,愣是没弄出来结果就用了 OC 和 js 混编了,然后又封装了一下,关键 highcharts 的默认样式很美观,比较可靠.
