### ISSUE TITLE
饼图类型，当其数据源中的数据值大部分都为 0 的时， dataLabels 显示不全

### ISSUE THREAD

**Issue by mapleleaf99** [AAChartModel/AAChartKit#1446]
<img width="292" alt="image" src="https://user-images.githubusercontent.com/23233548/218983606-c88fe5d2-2abb-48eb-b403-a3927618b3e9.png">
如题，如图

**Comment by mapleleaf99** [comment]
数据源= @[
        @[@"AAAA",   @(0)],
        @[@"BBBB",          @(0)],
        @[@"CCCC",      @(0)],
        @[@"DDDD",       @(0)],
        @[@"EEEE",     @(10)]

**Comment by AAChartModel** [comment]
试试类似 JS 这样配置看看:

```js
Highcharts.chart('container', {
  series: [{
    type: 'pie',
    dataLabels: {
      padding: 0,
      style: {
        fontSize: '8px'
      }
    },
    data: [{
      name: 'AAAAA',
      y: 0
   },
   {
      name: 'BBBBB',
      y: 0
   },
   {
      name: 'CCCCC',
      y: 0
   },
   {
      name: 'DDDDD',
      y: 0
   },
   {
      name: 'EEEEE',
      y: 10
   },]
  }]
});

```

**Comment by AAChartModel** [comment]
<img width="346" alt="截屏2023-02-15 17 26 09" src="https://user-images.githubusercontent.com/16357599/218987933-99d57107-9bfe-4edf-89bf-0503e12b3682.png">

**Comment by AAChartModel** [comment]
参考:
* https://stackoverflow.com/questions/55702909/highcharts-pie-chart-is-not-showing-all-of-datalabels-its-cut-off

**Comment by mapleleaf99** [comment]
调节了padding和fontsize还是一样

**Comment by mapleleaf99** [comment]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/23233548/218990861-36033c3a-03dd-4dc8-8eeb-e884b84ca509.png">
这样设置是否有问题

**Comment by mapleleaf99** [comment]
调整了size，可以显示了，谢谢

**Comment by mapleleaf99** [comment]
<img width="310" alt="image" src="https://user-images.githubusercontent.com/23233548/219247887-70d893cf-3aae-4abd-8c18-33833fa69fea.png">
数据源数据都为0的时候： @[
                @[@"AAAA",   @(0)],
                @[@"BBBB",   @(0)],
                @[@"CCCC",   @(0)],
                @[@"DDDD",   @(0)],
                @[@"EEEE",   @(0)]
                ];
，应该显示五等分吧

**Comment by mapleleaf99** [comment]
<img width="969" alt="image" src="https://user-images.githubusercontent.com/23233548/219249160-79b3add5-33b3-497c-ae54-71da3756d9db.png">
报错信息

**Comment by AAChartModel** [comment]
参考:

* https://github.com/AAChartModel/AAChartKit/issues/1447
