### ISSUE TITLE
请问下，单个折线图中 tooplip提示框底部会有个尖角，怎么样可以去除

### ISSUE THREAD

**Issue by Livjxbill993** [AAChartModel/AAChartKit#1448]

**Comment by AAChartModel** [comment]
参考:
* #957 

> Can be one of: "callout", "circle" or "rect". 

设置 `AATooltip` 的 `shape` 属性为 `rect` 即可.

**Comment by AAChartModel** [comment]
参考:
* https://github.com/AAChartModel/AAChartKit/issues/993
