### ISSUE TITLE
aa_refreshChartWithChartModel 刷新的时候 有个错误

### ISSUE THREAD

**Issue by xumiaojun** [AAChartModel/AAChartKit#145]
我在简书中，评论里说这个问题解决 ？

错误如下：

☠️☠️💀☠️☠️WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: loadTheHighChartView, WKJavaScriptExceptionColumnNumber=21, WKJavaScriptExceptionSourceURL=about:blank, NSLocalizedDescription=A JavaScript exception occurred}

**Comment by AAChartModel** [comment]
虽然报的错误相同,但是原因不同.你的这个情况应该是在错误的时机调用了
```objective-c
/*更新 AAChartModel 内容之后,刷新图表*/
[_aaChartView aa_refreshChartWithChartModel:aaChartModel];
```
这个刷新图表的方法.这个方法只能在已经调用了
```objective-c
/*图表视图对象调用图表模型对象,绘制最终图形*/
[_aaChartView aa_drawChartWithChartModel:aaChartModel];
```
这个方法之后再进行调用.

**Comment by AAChartModel** [comment]
这个错误原因是没有正确的获得 AAChartView.html 的上下文内容导致的错误.
