### ISSUE TITLE
底部name颜色怎么修改呢？

### ISSUE THREAD

**Issue by CoderFM** [AAChartModel/AAChartKit#1454]
![WechatIMG16](https://user-images.githubusercontent.com/22071707/223003901-979eb9e8-89ee-4468-b800-d5d2610f4a66.jpeg)
底部烤烟，混合型文本颜色用什么修改呢？

**Comment by AAChartModel** [comment]
重复问题, 参考;
* https://github.com/AAChartModel/AAChartKit/issues/1235
