### ISSUE TITLE
柱状图如何设置宽度 

### ISSUE THREAD

**Issue by yangmiaomiao-coder** [AAChartModel/AAChartKit#1455]

**Comment by AAChartModel** [comment]
参考:
* https://github.com/AAChartModel/AAChartKit/issues/1421

**Comment by AAChartModel** [comment]
直接设置柱状图📊宽度, 参考在线文档:

* https://api.highcharts.com/highcharts/series.column.pointWidth


直接设置 column 的 pointWidth 就行了, 但是会有棱柱过宽时, 互相遮盖的问题, 如下图所示:

![](https://user-images.githubusercontent.com/16357599/187337952-24609eff-70f1-4095-b9cb-9a72c41ea16e.png)

**Comment by AAChartModel** [comment]
间接设置宽度, 参考:

* https://github.com/AAChartModel/AAChartKit/issues/537

这样不会产生棱柱过宽时, 彼此遮盖的问题.
