### ISSUE TITLE
图层与水平轴线显示层级问题

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartKit#1457]
![image](https://user-images.githubusercontent.com/12290214/225531023-465a91ef-dffa-4eaf-8892-9311c079a01c.png)
如上图，红色线条zindex=4,蓝色线条zindex=3，水平轴线(灰色的细线)zindex=2，红色线条下的填充部分(与红色线条独立，但使用同一个数据)zindex=1
按照以上的zindex来显示，红色填充图层(zindex=1)不应该对水平轴线(zindex=2)有遮挡，但上图的显示效果可以看出，在透明度较高颜色较深的区域，轴线显示模糊，被填充图层遮挡了。
填充色的代码如下
let gradientColorDic = AAGradientColor.linearGradient(direction: .toBottom, startColor: "rgba(255,0,0,1)", endColor: "rgba(255,0,0,0)")
我应该如何做，才能让水平轴线清楚的显示在填充图层上呢？

**Comment by AAChartModel** [comment]
你有试试这个关于网格线的这个`gridZIndex`属性吗?

* https://api.hcharts.cn/highcharts/xAxis.gridZIndex.html

**Comment by AAChartModel** [comment]
> 水平轴线(灰色的细线)zindex=2

这个按理说, 对应的是 `gridZIndex ` 这个属性.

参考在线示例:

* https://jshare.com.cn/github/highcharts/highcharts/tree/master/samples/highcharts/xaxis/gridzindex

**Comment by lhpkxywm** [comment]
> > 水平轴线(灰色的细线)zindex=2
> 
> 这个按理说, 对应的是 `gridZIndex ` 这个属性.
> 
> 参考在线示例:
> 
> * https://jshare.com.cn/github/highcharts/highcharts/tree/master/samples/highcharts/xaxis/gridzindex

是的，我使用的就是gridZIndex,代码如下图。
![image](https://user-images.githubusercontent.com/12290214/225786896-0e3583f7-8c4b-4c59-980b-7c68e1b356f2.png)
而且，AAYAxis也没有zIndex属性啊

**Comment by lhpkxywm** [comment]
> 你有试试这个关于网格线的这个`gridZIndex`属性吗?
> 
> * https://api.hcharts.cn/highcharts/xAxis.gridZIndex.html

Axis对象只有gridZIndex属性，根本就没有zIndex属性，所以使用的肯定是gridZIndex，不然会报错的

**Comment by AAChartModel** [comment]
从你的需求来看, 你是想要网格线能够在穿插在这几个 `AASeriesElement` 之间, 但是我试了一下, 应该做不到.

参考: 
* https://www.highcharts.com/forum/viewtopic.php?t=33293

**Comment by AAChartModel** [comment]
> Unfortunately series are placed in one group that has same z index, so it is not possible to place series in different layers in relation to other elements. As a workaround you could add custom elements that will be placed behind axis' grid.

从这个 Highcharts 的官方回复来看, 各个 `AASeriesElement` 只能是同一个组(`group`), 也就是说各个 `AASeriesElement`是被当做一个整体看待的.

调整网格线层级 `gridZIndex ` , 只能让网格线在这个组(`group`)的整体之上或者是整体之下, 但是就是不能穿插在他们之间.

我测试的结果也是和这个官方回复相符.

**Comment by lhpkxywm** [comment]
> > Unfortunately series are placed in one group that has same z index, so it is not possible to place series in different layers in relation to other elements. As a workaround you could add custom elements that will be placed behind axis' grid.
> 
> 从这个 Highcharts 的官方回复来看, 各个 `AASeriesElement` 只能是同一个组(`group`), 也就是说各个 `AASeriesElement`是被当做一个整体看待的.
> 
> 调整网格线层级 `gridZIndex ` , 只能让网格线在这个组(`group`)的整体之上或者是整体之下, 但是就是不能穿插在他们之间.
> 
> 我测试的结果也是和这个官方回复相符.

处女膜撕裂的忧伤
