### ISSUE TITLE
柱状图点击的时候,可以获取柱子的中心点坐标么,感谢大大

### ISSUE THREAD

**Issue by wangfang871111** [AAChartModel/AAChartKit#1460]
柱状图和曲线图不一样,没有那种market的标记,但是现在需求又要在柱状图顶部加圆形的球体,我每次点击的时候把model的offset的x和y都带出来,本来以为可以了,但是我发现,随着y坐标轴刻度的增大,整个图表会往左细小的偏移,我猜测是因为y的text长度变长导致的,目前我想到的办法是,如果能准确知道点击的柱状图的中心点,应该就可以解决这个问题,不知道我描述的准确没,不胜感激

![图表偏移327](https://user-images.githubusercontent.com/16934606/228038026-18865640-9ea8-48fe-9b9b-84b5524e2087.png)

**Comment by AAChartModel** [comment]
参考:

* https://github.com/AAChartModel/AAChartKit-Swift/issues/372

**Comment by wangfang871111** [comment]
感谢大佬,只有swift版本的么,我这边项目时oc的.....

**Comment by AAChartModel** [comment]
在 OC 版本的 AAChartKit 的 demo 中新增了与 Swift 完全相同的`CustomClickEventCallbackMessageVC`示例代码, 下载运行查看即可.

**Comment by wangfang871111** [comment]
感谢大佬的帮助!万分感谢!
