### ISSUE TITLE
请问这饼状图的边框以及文本的边框怎么调整啊

### ISSUE THREAD

**Issue by CoderFM** [AAChartModel/AAChartKit#1461]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/22071707/228726771-b900113e-3c0f-42a8-b4ec-28147bfda57c.png">
请问这饼状图的边框以及文本的边框怎么调整啊

**Comment by AAChartModel** [comment]
参考:

* https://github.com/AAChartModel/AAChartKit/issues/1013

**Comment by AAChartModel** [comment]
参考:
* https://github.com/AAChartModel/AAChartKit/issues/1036
