### ISSUE TITLE
我需要让value显示在类似tooltip的气泡中，气泡样式可以设置本地图片，并且让气泡常驻，请问哪个类能实现该需求？

### ISSUE THREAD

**Issue by DaZhuzhu** [AAChartModel/AAChartKit#1469]
tooltip好像只有在点击value的时候才会显示，而且不能将tooltip设置为本地的一张图片。

**Comment by AAChartModel** [comment]
> 而且不能将tooltip设置为本地的一张图片

参考:
* https://github.com/AAChartModel/AAChartKit/issues/1404
