### ISSUE TITLE
请问怎么设置X轴的标题在刻度线的下方并剧中显示

### ISSUE THREAD

**Issue by Costword** [AAChartModel/AAChartKit#1471]
![9aafaf49ff74832bffe9900cbe63e94b](https://user-images.githubusercontent.com/17446833/234449749-58451e03-d432-480c-bfef-dbf6586b6d55.png)

**Comment by AAChartModel** [comment]
**参考 Highcharts 的 X 轴的属性 `tickmarkPlacement` 在线文档:**

* https://api.highcharts.com/highcharts/xAxis.tickmarkPlacement


设置此属性为 `on`的在线示例如下:

* https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/xaxis/tickmarkplacement-on/

对应的, 在 iOS 中, 可以这样设置:

```objc
   aaOptions.xAxis
    .tickmarkPlacementSet(@"on")//本参数只对分类轴有效。 当值为 on 时刻度线将在分类上方显示；当值为 between 时，刻度线将在两个分类中间显示。当 tickInterval 为 1 时，默认是 between，其他情况默认是 on。 默认是：null.
    ;
```

**Comment by AAChartModel** [comment]
不过以上的设置, 如果数据量较小的时候, 可能存在左边边距较大的问题. 所以最终的解决方法, 可参考:

* https://github.com/AAChartModel/AAChartKit/issues/577
