### ISSUE TITLE
Y轴自定义区间数值，X轴固定三个时间点位，这种情况要怎么配置呢

### ISSUE THREAD

**Issue by yanpd** [AAChartModel/AAChartKit#1473]
![image](https://user-images.githubusercontent.com/20255662/234742434-04cb47a3-3436-4dd7-81fa-1e81dade0330.png)

**Comment by AAChartModel** [comment]
> Y轴自定义区间数值

参考:

* https://github.com/AAChartModel/AAChartKit/issues/1470

**Comment by AAChartModel** [comment]
> X轴固定三个时间点位

查看与Y轴的类似的对应的相关属性
* https://api.highcharts.com/highcharts/xAxis.tickInterval
* https://api.highcharts.com/highcharts/xAxis.tickPositions

**Comment by AAChartModel** [comment]
同时, X 轴和 Y轴还有灵活度更高的属性 `formatter` 可以用来自定义 X 轴和 Y 轴的 `labels`.

参考:
* https://github.com/AAChartModel/AAChartKit/issues/952
* https://github.com/AAChartModel/AAChartKit/issues/1324
* https://github.com/AAChartModel/AAChartKit/issues/1330
