### ISSUE TITLE
如何获取Pod的稳定版本，精确到commit的哈希值

### ISSUE THREAD

**Issue by lannastudio** [AAChartModel/AAChartKit#1477]
pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git', :commit => '精确的commit哈希值'
hi 开发者，一般情况下，在Podfile中指定commit的哈希值会更加安全，请问我如何得到AAChartKit稳定版本的哈希值

**Comment by AAChartModel** [comment]
如果你需要的是有 `tag` 值的 `commit`, 参考:

* https://github.com/AAChartModel/AAChartKit/tags

每个 tag 都有对应的哈希值, 复制粘贴即可.

**Comment by AAChartModel** [comment]
如果你需要的是任意 `commit` 的哈希值, 参考:

* https://github.com/AAChartModel/AAChartKit/commits/master

此 **git log** 中可以找到任意次 `commit` 的相关信息
