### ISSUE TITLE
折线图线宽问题

### ISSUE THREAD

**Issue by Ivia** [AAChartModel/AAChartKit#1482]
<img width="1027" alt="image" src="https://github.com/AAChartModel/AAChartKit/assets/10719336/826db44f-7546-4f22-8ee0-bff126650ac5">

如图，设置了折线图的线宽为3，但是如果有连续为0的数据，靠近x轴的线会非常细，可以设置成一样的宽度吗

**Comment by AAChartModel** [comment]
参考相同问题:
 * https://github.com/AAChartModel/AAChartKit/issues/1414

**Comment by AAChartModel** [comment]
参考 Highcharts 的官方 issue :
* https://github.com/highcharts/highcharts/issues/3160
* https://github.com/highcharts/highcharts/issues/8235

**Comment by Ivia** [comment]
已解决，感谢
