### ISSUE TITLE
渐变色重叠。如何渐变色重叠不显示混合颜色 显示单一颜色

### ISSUE THREAD

**Issue by btxXiaoXiao** [AAChartModel/AAChartKit#1483]
渐变色重叠。如何渐变色重叠不显示混合颜色 显示单一颜色
![1901689151687_ pic](https://github.com/AAChartModel/AAChartKit/assets/39784116/fa52e2f0-dc3e-4e45-a22b-d59f499affd0)

**Comment by AAChartModel** [comment]
将渐变色的颜色透明度float数值都改为1.0就可以了
