### ISSUE TITLE
请问如何实现这种睡眠图效果

### ISSUE THREAD

**Issue by Quu-FY** [AAChartModel/AAChartKit#1486]
您好，请问下下图这种图表如何实现
![wecom-temp-126694-bc00573ae556a42658c5bfb48179ecbe_副本](https://github.com/AAChartModel/AAChartKit/assets/139857818/310438c4-9a09-43ae-a8b8-845e33a7543a)

**Comment by AAChartModel** [comment]
重复问题, 参考:

* https://github.com/AAChartModel/AAChartKit/issues/1265

**Comment by Quu-FY** [comment]
> 重复问题，参考：
> 
> * [数值不连续的柱状图怎么配置 #1265](https://github.com/AAChartModel/AAChartKit/issues/1265)

我尝试了使用AAChartTypeColumnrange类型的柱状图，但是无法解决每个睡眠状态不同需要不同颜色的问题

**Comment by AAChartModel** [comment]
参考:

* https://github.com/AAChartModel/AAChartKit-Swift/issues/371

**Comment by Quu-FY** [comment]
> 参考：>> * * [大佬，请问怎么实现这种类似甘特图的图表？AAChartKit-Swift#371]（https://github.com/AAChartModel/AAChartKit-Swift/issues/371）
每日睡眠图表是用甘特图我实现了，这个是不同的图表诶，是多日的图表，每日的数据放在一个区间柱状图内（竖直是每日的数据），每一时间段状态用不同的颜色标记出来的，这种用甘特图也能实现么？实现思路是怎么样的呢

**Comment by AAChartModel** [comment]
那我估计应该搞不定. 你可以直接去 Highcharts 的官方社区提问, 看看是否有解决方案, 如果 Highcharts 官方都无法解决, 那应该就是真的没辙了.

**Comment by Quu-FY** [comment]
> 那我估计应该搞不定. 你可以直接去 Highcharts 的官方社区提问, 看看是否有解决方案, 如果 Highcharts 官方都无法解决, 那应该就是真的没辙了.

好的，谢谢了 ^ _ ^
