### ISSUE TITLE
请问一下 AAEventMessageModel 的name如何修改，就是我想修改点击弹框的文字

### ISSUE THREAD

**Issue by szweee** [AAChartModel/AAChartKit#1489]
![IMG_4CC6D3A186B0-1](https://github.com/AAChartModel/AAChartKit/assets/20777870/58ef1fac-f654-45c9-8c81-5e59e52b431b)

**Comment by AAChartModel** [comment]
设置 AATooltip 的关键属性 `pointFormat`.

参考:

* https://github.com/AAChartModel/AAChartKit/issues/375
* https://github.com/AAChartModel/AAChartKit/issues/745

**Comment by AAChartModel** [comment]
参考:

* https://github.com/AAChartModel/AAChartKit/issues?q=pointformat
