### ISSUE TITLE
x轴 空值的时候 如何链接前后的点

### ISSUE THREAD

**Issue by Gjiangkai** [AAChartModel/AAChartKit#1494]
你好 如果x轴 中间的某个值为空 如何把前后的点链接起来 x轴上的点数是固定的 只是有的会没有数据 但是位置不变
![441691742482_ pic](https://github.com/AAChartModel/AAChartKit/assets/15081783/533f3742-8eb6-4bef-9008-4f9dc0543ba7)

**Comment by AAChartModel** [comment]
参考:

* #1232

**Comment by Gjiangkai** [comment]
非常感谢
