### ISSUE TITLE
请问下如何将睡眠甘特图的x坐标轴格式化

### ISSUE THREAD

**Issue by Quu-FY** [AAChartModel/AAChartKit#1495]
![IMG_5235](https://github.com/AAChartModel/AAChartKit/assets/139857818/67f4af40-8677-4dcd-931d-9ea6cf08ab60)
现在X坐标轴是时间戳，我想格式化成小时分钟格式

**Comment by AAChartModel** [comment]
自定义 `X` 轴和 `Y` 轴的 `labels`, 参考相似问题:

* https://github.com/AAChartModel/AAChartKit/issues/1473

**Comment by AAChartModel** [comment]
参考:

* https://github.com/AAChartModel/AAChartKit/issues/363

**Comment by Quu-FY** [comment]
解决了，非常感谢
