### ISSUE TITLE
在代码使用的时候发现 柱状图的颜色 只能设置一次,是否可以判断柱状图的数值 然后根据数值的区间来设置不同的颜色,希望大神指点下,不胜感激~

### ISSUE THREAD

**Issue by DreamForStar** [AAChartModel/AAChartKit#150]
还是我大神,请不要屏蔽我..我又来了  趁着你还在~~~

**Comment by AAChartModel** [comment]
奇怪,你为什么会担心我会屏蔽你啊?

**Comment by DreamForStar** [comment]
因为我很菜,问题比较多,会很烦你 还有个是否可以关闭加载动画 因为加载的时候有点慢 谢谢

**Comment by AAChartModel** [comment]
难道我不是一直都在么?😝

**Comment by AAChartModel** [comment]
关闭加载动画? AAChartKit 没有加载动画吧

**Comment by DreamForStar** [comment]
呃呃 这是我第一次在GitHub上面提问, 但是加载数据会很慢..就是需要等一会才会有数据出来 这个是控件自身的原因吗?

**Comment by DreamForStar** [comment]
好的 我去尝试一下 请问上面的显示颜色的那个问题有办法解决吗? 谢谢

**Comment by AAChartModel** [comment]
主要是原 highcharts的 这个 js 库在首次被 AAChartView 加载上下文文件内容的时候会比较慢,加载完成之后,刷新数据等还是很快的.

**Comment by AAChartModel** [comment]
颜色的这个问题可以解决,不过你要等一段时间,可能要到星期天,因为最近我的工作项目问题比较多,我需要优先解决自己工作中的问题.
话说你先在真机中测试一下运行速度,如果速度太慢无法满足你的实际项目需求,那么建议你可以放弃 AAChartKit, 转换为使用 GitHub 上其他的原生的 iOS 图表库.顺便也及时回复我一下,这样我就可以不用解决你的这个柱状图📊颜色问题了哈

**Comment by DreamForStar** [comment]
NONONO 我比较执着 基本都写完了 我要一直坚持使用您的框架 而且 项目中别的同事也在使用您的框架 谢谢帮我解答 我的项目暂时不会很急 有时间帮我解决下颜色的问题 估计年后才会上线 谢谢

**Comment by DreamForStar** [comment]
你好,大神,希望你没有忘记这个问题,如果在闲暇之余解决了这个问题,麻烦请回复我一下 谢谢 不胜感激

**Comment by AAChartModel** [comment]
相信我还在这里,从不曾离去,我的...

**Comment by DreamForStar** [comment]
会唱歌的优秀程序员 哈哈

**Comment by AAChartModel** [comment]
我查了一下文档,如果你要单独的为柱状图的某一个长条设置颜色只能是这种操作
将AAChartModel 的属性 series 中的数据元素中的内容
``` objective-c
                AAObject(AASeriesElement)
                 .nameSet(@"2017")
                 .dataSet(@[@320, @342, @351, @434, @564,]),
```
改为
```objective-c
                 AAObject(AASeriesElement)
                 .nameSet(@"2017")
                 .dataSet(@[@320, @{
    @"y":@342,
    @"color":@"#000000"
    }, @351, @434, @564,]),
``

这样的意思就是将柱状图的第二个棱柱的颜色设置为黑色,这里面的颜色色值需要你自己按照自己的项目需求,根据棱柱的数值来自己决定棱柱的颜色

**Comment by DreamForStar** [comment]
好的 谢谢,我自己尝试一下,新年快乐

**Comment by DreamForStar** [comment]
大神,觉得你这个框架可宽展性很强 能不能推荐下学习的相关的资料 想研究下...

**Comment by AAChartModel** [comment]
这个需求问题解决了是吧?
关于学习,你直接学习一下官方的 highcharts-ios 即可
https://github.com/highcharts/highcharts-ios

**Comment by AAChartModel** [comment]
这个简直不能称之为框架,只是一层对 highcharts 的封装,就好像是包了一层语法糖而已.因为本身 highcharts 就极其友好,他的整个图表的绘制工作几乎全都由json 语句描述即可.所以你看我看起来好像写了那么多代码,其实就是在写一个 OC 的 json 语法糖而已.

**Comment by AAChartModel** [comment]
不过官方的为了追求大而全面,封装了余下的几乎百分之八十我们平常根本用不到的功能,所以整个官方的库非常的大,貌似有 10M 以上.所以不建议直接在项目中使用,但是用来学习还是不错的.

**Comment by DreamForStar** [comment]
好的 应该可以解决我的问题 谢谢比心

**Comment by DreamForStar** [comment]
额 大神 我把新的lib拖进去以后 y轴显示一个灰色的value?~

**Comment by AAChartModel** [comment]
那个 value 是Y轴的默认标题吧,要隐藏的话应该设置字符串为空即可

**Comment by DreamForStar** [comment]
好了 谢谢

**Comment by AAChartModel** [comment]
> 根据数值的区间来设置不同的颜色

这个功能也正常是吗?如果可以请关闭这个 issue, 还有问题,开下一个 issue 提问: )

**Comment by gaoguanbao** [comment]
可以设置Legend图例标题字体不同的颜色吗？

**Comment by Maxcucurbit** [comment]
大佬，我又来了，我也有个跟他一样的需求，要画一个柱状区间columnrange图,拿某一个柱子举例，比如一个柱子的范围是20~100,20~40的区间显示白色，41~60的区间显示绿色，61~80的区间显示蓝色，81~100的区间显示红色，请问能实现这个效果吗？

**Comment by AAChartModel** [comment]
@Maxcucurbit 你的需求应该和这个问题的需求不一样, 你的同一个棱柱, 添加多段颜色的这个功能, Highcharts 我估计实现不了.

 参考相同的此问题:

* #1486

**Comment by Maxcucurbit** [comment]
> @Maxcucurbit 你的需求应该和这个问题的需求不一样, 你的同一个棱柱, 添加多段颜色的这个功能, Highcharts 我估计实现不了.
> 
> 参考相同的此问题:
> 
> * [请问如何实现这种睡眠图效果 #1486](https://github.com/AAChartModel/AAChartKit/issues/1486)
确实是要这样的效果，谢谢解答
