### ISSUE TITLE
Xcode升级到 15.0.0 之后，AAChartModel报错：  Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by telami** [AAChartModel/AAChartKit#1501]
<img width="861" alt="image" src="https://github.com/AAChartModel/AAChartKit/assets/25978237/afef8365-101b-4114-ae14-f0cf823a565f">

**Comment by geekstars** [comment]
Please comment on the lines of code that have errors.

**Comment by vx8** [comment]
I forked and tested this project with xCode 15, working as expected.

You can find it here -> https://github.com/vx8/AAChartKit-Swift

**Comment by AAChartModel** [comment]
> Please comment ( // ) on the lines of code that have errors.

如楼上所说, 先手动将报错的部分注释掉应该就可以了. 我后面有时间再处理下.

**Comment by AAChartModel** [comment]
报错的这部分内容直接注释掉, 对代码其实没啥硬性影响.

**Comment by telami** [comment]
@AAChartModel 要不您这直接改了吧，提交一版

**Comment by AAChartModel** [comment]
刚刚看到有好心人已经改过了, 提了 pull request, 我已合并.

参看:

* https://github.com/AAChartModel/AAChartKit-Swift/pull/459

**Comment by AAChartModel** [comment]
更新 AAChartKit-Swift 至最新内容即可.

参看: 
* https://github.com/AAChartModel/AAChartKit-Swift/issues/359
