### ISSUE TITLE
这种仪表咋实现呢？

### ISSUE THREAD

**Issue by xbindai** [AAChartModel/AAChartKit#1523]
<img width="1780" alt="iShot_2023-12-15_18 12 54" src="https://github.com/AAChartModel/AAChartKit/assets/84165254/8e988a46-3d05-4551-8f61-a1d46f39128c">
大神，这个图demo里面有实现吗？

**Comment by AAChartModel** [comment]
*  https://github.com/AAChartModel/AAChartKit-Pro
* https://github.com/AAChartModel/AAChartKit-Swift-Pro
Pro 版本有此示例.
