### ISSUE TITLE
ios AALegend 如何禁止点击 禁用点击区块 （尝试过 很多属性都不能满足需求）

### ISSUE THREAD

**Issue by xuchanglu** [AAChartModel/AAChartKit#1528]
![3230867268](https://github.com/AAChartModel/AAChartKit/assets/17775953/04a3b0e5-8606-4775-a7ce-ec48964861f9)

我的问题是 ios 如何禁用 点击 线上或者线下或 活动按钮 的点击事件

**Comment by xuchanglu** [comment]
以下是我的代码
    AALegend *aaLegend = AALegend.new
    .enabledSet(true)
//    .floatingSet(false)
    .alignSet(AAChartAlignTypeLeft)
    .verticalAlignSet(AAChartVerticalAlignTypeTop)
    .borderColorSet(@"#ccc")
    .borderWidthSet(@0)
    .xSet(@(10))
    .ySet(@-10)
    ;
    

  NSArray *aaSeriesArr = @[
        AASeriesElement.new
        .nameSet(@"线上")
        .allowPointSelectSet(true)//是否允许在点击数据点标记(扇形图点击选中的块发生位移)
        .showInLegendSet(true)
        .statesSet(AAStates.new
                   .hoverSet(AAHover.new
                             .enabledSet(false)//禁用点击区块之后出现的半透明遮罩层
                             )
        )
        .dataSet([self getDatasByType:@"线上"]),
        AASeriesElement.new
        .nameSet(@"线下")
        .statesSet(AAStates.new
                   .hoverSet(AAHover.new
                             .enabledSet(false)//禁用点击区块之后出现的半透明遮罩层
                             ))
        .dataSet([self getDatasByType:@"线下"]),
        AASeriesElement.new
        .nameSet(@"活动")
        .statesSet(AAStates.new
                   .hoverSet(AAHover.new
                             .enabledSet(false)//禁用点击区块之后出现的半透明遮罩层
                             ))
        .dataSet([self getDatasByType:@"活动"]),
    ];

**Comment by AAChartModel** [comment]
参考相同问题:

* https://github.com/AAChartModel/AAChartKit/issues/928
