### ISSUE TITLE
柱形图的Y轴坐标轴刻度线怎么能设置为虚线？

### ISSUE THREAD

**Issue by jinger428** [AAChartModel/AAChartKit#1537]
柱形图设置了 aaOptions.yAxis.tickPositions=@[@0,@20,@40];怎么将刻度线设置为虚线，而不是用    _aaChartModel
    .yAxisPlotLinesSet，因为这么设置的刻度线会压在图形上方，而默认的刻度线会在图形下方。并且设置了aaOptions.yAxis.tickWidth和aaOptions.yAxis.tickColor并没有起到效果，不知道问题出在哪儿？

**Comment by AAChartModel** [comment]
我感觉应该是把`刻度线 tick` 和`标志线 plotLines` 以及`网格线 gridLine` 这三者弄混了,  可以先查看在线文档:
* https://api.highcharts.com/highcharts/xAxis

**Comment by jinger428** [comment]
![Snip20240307_2](https://github.com/AAChartModel/AAChartKit/assets/24770263/0f7bfef5-a123-4b1a-ae28-c3b39f5719d2)
感谢您的回复。想再次确认一下，图中的这个横线可以自定义颜色，或者换成虚线吗？

**Comment by AAChartModel** [comment]
你图中所示的是 `Y` 轴的`网格线 gridLine` , 对应的的属性是 `AAYAxis` 中的如下内容:

```objc
AAPropStatementAndPropSetFuncStatement(strong, AAYAxis, NSNumber *, gridLineWidth) // y 轴网格线宽度
AAPropStatementAndPropSetFuncStatement(copy,   AAYAxis, NSString *, gridLineColor) // y 轴网格线颜色
AAPropStatementAndPropSetFuncStatement(copy,   AAYAxis, NSString *, gridLineDashStyle) //网格线线条样式，所有可用的线条样式参考：Highcharts线条样式
AAPropStatementAndPropSetFuncStatement(strong, AAYAxis, NSNumber *, gridZIndex) //网格线的层叠值（zIndex） 默认是：1.
AAPropStatementAndPropSetFuncStatement(copy,   AAYAxis, AAChartYAxisGridLineInterpolationType, gridLineInterpolation) //Polar charts only. Whether the grid lines should draw as a polygon with straight lines between categories, or as circles. Can be either circle or polygon. 默认是：null.
```

参考对应的在线文档:
* https://api.highcharts.com/highcharts/yAxis.gridLineColor
* https://api.highcharts.com/highcharts/yAxis.gridLineDashStyle
等等, 就不一一列举了.

**Comment by jinger428** [comment]
非常感谢！
