### ISSUE TITLE
柱状图 dataLabels的设置问题

### ISSUE THREAD

**Issue by gaojing0428** [AAChartModel/AAChartKit#1539]
你好，我的柱状图上面，两个数据是一样的，这个时候dataLabels只显示了一个，这个怎么解决？
![Snip20240326_13](https://github.com/AAChartModel/AAChartKit/assets/165002681/66f03a07-14ad-4925-b153-3ff4c1a90c76)

**Comment by gaojing0428** [comment]
相差不多的时候，也是只显示一个

**Comment by AAChartModel** [comment]
参考相同问题:
* https://github.com/AAChartModel/AAChartKit/issues/707

**Comment by gaojing0428** [comment]
label全部显示出来了，但是文字会重叠，有办法解决吗？
![image](https://github.com/AAChartModel/AAChartKit/assets/165002681/a7d7fcb2-01c6-429f-99a6-79841545b768)

**Comment by AAChartModel** [comment]
```objc
//允许DataLabels重叠
AAPropStatementAndPropSetFuncStatement(assign, AADataLabels, BOOL, allowOverlap)
```

这个有点难搞, 毕竟你的数值都太接近了. 这个属性`allowOverlap = true`就是允许重叠的意思.  

真的非要避免重叠, 只能

* 将字体调整小一点
* 或者自定义每个 AADataElement 的 datalabels 的位置属性
 
 来避免重叠.

**Comment by gaojing0428** [comment]
谢谢，分别调整了align属性，解决了~
