### ISSUE TITLE
你好如何实现双Y轴柱形图组合折线图的效果两个Y轴代表了不同图

### ISSUE THREAD

**Issue by linqifeng26147** [AAChartModel/AAChartKit#1545]
![Uploading 截屏2024-04-26 09.47.42.png…]()

**Comment by linqifeng26147** [comment]
![截屏2024-04-26 09 47 42](https://github.com/AAChartModel/AAChartKit/assets/95924075/99c42e94-0916-41c4-bde7-39a8438a1935)

**Comment by AAChartModel** [comment]
参考相似问题:
* https://github.com/AAChartModel/AAChartKit/issues/771
