### ISSUE TITLE
浮动窗可以进行添加点击方法吗

### ISSUE THREAD

**Issue by linqifeng26147** [AAChartModel/AAChartKit#1547]
我们公司的项目需要点击浮动窗进行跳转,有相关的能力提供吗

**Comment by linqifeng26147** [comment]
@AAChartModel

**Comment by AAChartModel** [comment]
参考:
* https://www.highcharts.com/forum/viewtopic.php?t=48311

**Comment by AAChartModel** [comment]
* https://github.com/AAChartModel/AAChartKit-Swift/issues/372

你也可以参考这个方法, 获取的点击事件的相关信息, 通过 `UIView` 来自行绘制 `tooltip`, 这样就可以随意定制 `tooltip` 的点击事件了.
