### ISSUE TITLE
如何设置使堆积柱状图y轴只显示总数

### ISSUE THREAD

**Issue by piitw** [AAChartModel/AAChartKit#1549]
请问如何设置使柱状图只显示总数，而不显示分段数据；如图所示。
![WeChat7b99005087756007c8c9819ac1a3803e](https://github.com/AAChartModel/AAChartKit/assets/17700529/ecd9888c-6922-4622-ac57-ba2cd1b7efde)

**Comment by AAChartModel** [comment]
参考相同问题:
* #827
