### ISSUE TITLE
能实现柱状图堆叠效果吗

### ISSUE THREAD

**Issue by liunianhuaguoyanxi** [AAChartModel/AAChartKit#1551]
每个柱状图中的色块代表其子内容，比如柱状图的11月，柱子的长度代表总数据，柱子的外框色代表他属于那个板块（如全国热搜），柱子中的每个色块又代表子数据
<img width="333" alt="image" src="https://github.com/user-attachments/assets/da2e3a32-b4f5-4c65-8289-c71760cebaea">

**Comment by AAChartModel** [comment]
参考:
* #685 
* #706

**Comment by AAChartModel** [comment]
参考:
* #462
