### ISSUE TITLE
您好作者,请问一下X轴可以设置成时间刻度吗

### ISSUE THREAD

**Issue by XcodePlayer** [AAChartModel/AAChartKit#1554]
![image](https://github.com/user-attachments/assets/4ec08665-d0c9-4d9b-8066-55a09cedcfb3)
左右两边是日期,从x轴中间往两边时间递减,请问能实现这种效果吗?
拜托作者看到回复一下,谢谢!

**Comment by AAChartModel** [comment]
据我所知, **Highcharts** 能够将 `X` 轴的轴线设置成时间刻度类型. 
但是应该只能是`单调递增`或者是`单调递减`的.

你说的这种`先递增再递减`的应该不行.

**Comment by XcodePlayer** [comment]
好的,麻烦你了!
我看了AAChartKit-ProDemo里的X轴范围图
![image](https://github.com/user-attachments/assets/5c5f4eb8-eb96-4f79-beb4-b468465bea4f)
这里的Y轴对应的条形图高度是可以调节的吗,我尝试了下没找到方法

**Comment by AAChartModel** [comment]
问: 
======
Highcharts 怎么设置 Xrange 图表的 series 的宽度?

答:
======
在 Highcharts 中，你可以通过以下两种方式来设置 Xrange 图表的 series 的宽度：

**1. 使用 `pointWidth` 属性:**

   -  `pointWidth` 属性允许你为每个柱子或条形点指定一个固定的像素宽度。 [1](https://api.highcharts.com/highcharts/plotOptions.xrange.pointWidth) [6](https://api.highcharts.com/highstock/series.xrange.pointWidth)
   -  当 `pointWidth` 设置为 `undefined` 时，宽度将根据 `pointPadding` 和 `groupPadding` 计算。 [4](https://api.highcharts.com/highcharts/series.xrange.lineWidth)

**2. 使用 `groupPadding` 和 `pointPadding`:**

   -  `groupPadding` 控制组之间间距的大小,  `pointPadding`  控制组内点之间间距的大小。 [3](https://stackoverflow.com/questions/76468389/highcharts-xrange-needs-to-fill-chart-width) 
   -  通过设置 `groupPadding: 0` 和 `pointPadding: 0` 可以使 series 填满整个图表宽度。 [3](https://stackoverflow.com/questions/76468389/highcharts-xrange-needs-to-fill-chart-width)

**请注意:**  `pointWidth`  会影响不基于点值的维度。 对于柱状图，它是水平长度，对于条形图，它是垂直长度。[1](https://api.highcharts.com/highcharts/plotOptions.xrange.pointWidth)


PS:
======
以上内容整理自在线 AI 工具.

**Comment by AAChartModel** [comment]
我的 demo 示例中的效果, 演示的是第二种方法:

> **2. 使用 `groupPadding` 和 `pointPadding`:**


```objc
    .plotOptionsSet(AAPlotOptions.new
                    .seriesSet(AASeries.new
                               .pointPaddingSet(@0)
                               .groupPaddingSet(@0)))
```

**Comment by AAChartModel** [comment]
参考相似问题:
* https://github.com/AAChartModel/AAChartKit/issues/537

**Comment by AAChartModel** [comment]
> 据我所知, **Highcharts** 能够将 `X` 轴的轴线设置成时间刻度类型. 但是应该只能是`单调递增`或者是`单调递减`的.
> 
> 你说的这种`先递增再递减`的应该不行.

话说回来, 看你的截图所示, 你的`X` 轴时间轴其实一直是单调递增(并非先递增再递减)的, 只是`X` 轴文字样式和内容有点特别. 这种情况, 应该需要你自己自定义`X` 轴文字, **Highcharts** 其实有提供此自定义方法.
参考:
* https://github.com/AAChartModel/AAChartKit/issues/1473

**Comment by XcodePlayer** [comment]
好的,非常感谢您的提点.
