### ISSUE TITLE
求教，柱状体点击x轴标签提示tooltip怎么实现啊，xAxis没找到设置？

### ISSUE THREAD

**Issue by Zorodon** [AAChartModel/AAChartKit#1561]

**Comment by AAChartModel** [comment]
这里刚好有个相同问题, 参考:
* https://github.com/AAChartModel/AAChartKit/issues/1531

**Comment by AAChartModel** [comment]
参考此次提交的内容即可.

* https://github.com/AAChartModel/AAChartKit/commit/434c92c878d31ad3cb8062e83bf2046decb194a0

**Comment by AAChartModel** [comment]
主要参考这段代码即可:

```objc
//How to add click event to X-axis label and access data ?
//https://www.highcharts.com/forum/viewtopic.php?t=40590
//https://codepen.io/anon/pen/LmObxY?editors=1010
//https://github.com/AAChartModel/AAChartKit/issues/1531
+ (AAOptions *)addClickEventToXAxisLabelAndAccessData {
    AAOptions *options = AAOptions.new
    .chartSet(AAChart.new
              .typeSet(AAChartTypeColumn)
              .eventsSet(AAChartEvents.new
                         .loadSet(@AAJSFunc(function() {
                             var axis = this.xAxis[0];
                             var ticks = axis.ticks;
                             var points = this.series[0].points;
                             var tooltip = this.tooltip;

                             points.forEach(function(point, i) {
                                 if (ticks[i]) {
                                     var label = ticks[i].label.element;

                                     label.onclick = function() {
                                         tooltip.getPosition(null, null, point);
                                         tooltip.refresh(point);
                                     };
                                 }
                             });
                         }))))
    .xAxisSet(AAXAxis.new
              .categoriesSet(@[@"Africa", @"America", @"Asia", @"Europe", @"Oceania"]))
    .yAxisSet(AAYAxis.new
              .minSet(@0))
    .tooltipSet(AATooltip.new
                .valueSuffixSet(@" millions"))
    .plotOptionsSet(AAPlotOptions.new
                    .seriesSet(AASeries.new
                               .dataLabelsSet(AADataLabels.new
                                              .enabledSet(YES))))
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"Year 1800")
        .dataSet(@[@107, @31, @635, @203, @2])
    ]);

    return options;
}
```

**Comment by Zorodon** [comment]
@AAChartModel 感谢大佬，顺便问下，如果我AADataElement不设置y值，可以隐藏数据0的柱状图，我的柱状图是嵌套的，隐藏了其中数据0的，但是这时候我点击其中一条柱状图，就不显示tooltip了，好像和这个y值有关系，我应该在自定义tooltip怎么判断是否有设置y值呢，代码如下

**Comment by AAChartModel** [comment]
你能贴一下你的图表截图吗?  
还有你的 `AAOptions` 配置代码(请使用纯文本, 不要截图).

**Comment by Zorodon** [comment]
aaOptions.tooltip
        .formatterSet(@AAJSFunc(function () {
            var s = '<b>' +  this.x + '</b>' + '<br/>';
            const colorDot1 = '<span style=\"' + 'color:#1890FF; font-size:11px\"' + '>●</span> ';
            const colorDot2 = '<span style=\"' + 'color:#DC3C3C; font-size:11px\"' + '>●</span> ';
            const colorDot3 = '<span style=\"' + 'color:#13C2C2; font-size:11px\"' + '>●</span> ';////
            const colorDot4 = '<span style=\"' + 'color:#8BC74D; font-size:11px\"' + '>●</span> ';

            var s1 =  colorDot1 + this.points[0].series.name + ': ' + '<b>' + this.points[0].y + '</b>';
            var s2 =  colorDot2 + this.points[1].series.name + ': ' + '<b>' + this.points[1].y + '</b>';
           
            var s3 =  colorDot3 + this.points[2].series.name + ': ' + '<b>' + this.points[2].y + '</b>';
            var s4 =  colorDot4 + this.points[3].series.name + ': ' + '<b>' + this.points[3].y + '</b>';
            
            s += s1 + '<br/>' + s2 + '<br/>' + s3 + '<br/>' + s4;
            return s;
        }));
缩减了下代码，主要是这个tooltip设置，数据那边就是0处理成[NSNull null]，这样设置tooltip就点击没法提示了，感觉和这个this.points.y有关，因为没设置y值，没有y值就取不到point？ 不太会js判断，求教哈哈哈

**Comment by Zorodon** [comment]
搞定了，我用AADataLabels的formatterSet去判断0，不用[NSNull null]填充就好
