### ISSUE TITLE
如何隐藏一条线，保留当前最大最小值，图形位置不变；另外我在几个点上面加了图片，如果数据密集，会重在一起，如何解决？

### ISSUE THREAD

**Issue by kedu** [AAChartModel/AAChartKit#1568]
如题，两个问题

**Comment by AAChartModel** [comment]
> 如何隐藏一条线，保留当前最大最小值，图形位置不变?

可以用另一个独立 `AASeriesElement` , 并设置为散点图, 专门用来表示当前的**最大值**和**最小值**. 
同时, 要为这个单独的 `AASeriesElement` 设置

```objc
.showInLegendSet(false)
```
使其不显示在图表的 `legend` 中.


参考相关问题:

* https://github.com/AAChartModel/AAChartKit/issues/1294

**Comment by AAChartModel** [comment]
> 另外我在几个点上面加了图片，如果数据密集，会重在一起，如何解决？

这个和常规的数据 `labels` 堆叠其实都是同一个问题, 没有太好的解决方案, 可以参考一下这个方法:
* https://stackoverflow.com/questions/22671871/overlap-datalabels-line-chart-highcharts

**Comment by kedu** [comment]
好的，感谢
