### ISSUE TITLE
边界值时，折线图线宽问题

### ISSUE THREAD

**Issue by fuchaojie** [AAChartModel/AAChartKit#1571]
![20241016130132](https://github.com/user-attachments/assets/35daf18f-af31-49ba-b21f-c958eacd0ec6)
设置了折线的线宽，但是边界的最大值、最小值时，折线变细，数值时时间单位，最大值、最小值不能大于24小时或小于0，怎么解决？求更新！

**Comment by AAChartModel** [comment]
不知道你要的是不是这里的这个效果:
* https://api.highcharts.com/highcharts/series.line.clip

**Comment by fuchaojie** [comment]
![20241016161041](https://github.com/user-attachments/assets/8ac2bc22-fb76-4c31-bf4c-ee475dfa1aee)
![20241016161053](https://github.com/user-attachments/assets/7058baea-ba8b-4711-9f9e-cbaa0ed04471)
具体怎么用，上面是代码片段，没找到clip属性

**Comment by fuchaojie** [comment]
> 不知道你要的是不是这里的这个效果:
> 
> * https://api.highcharts.com/highcharts/series.line.clip

是这个效果，对应OC的怎么写？感谢

**Comment by AAChartModel** [comment]
更新至最新内容:
* https://github.com/AAChartModel/AAChartKit/issues/1337

**Comment by AAChartModel** [comment]
参考此次提交的内容, 配置 `AASeriesElement` 的新增属性 `clip` 即可.
* https://github.com/AAChartModel/AAChartKit/commit/8d7184258defb1db577f32b046e5d38909fc6955

**Comment by AAChartModel** [comment]
实测这个属性 `clip` 的效果有点延迟, 不过暂无解决方案.

**Comment by fuchaojie** [comment]
已更新解决，感谢！！！
