### ISSUE TITLE
Marker active color

### ISSUE THREAD

**Issue by erdemildiz** [AAChartModel/AAChartKit#1573]
Hi everybody;

How can I disable or remove marker outline color? It actives when marker mouse over and take low opacity of marker color? I dont want? My marker range is 4.5

![Screenshot 2024-10-17 at 14 21 45](https://github.com/user-attachments/assets/74bacd98-c267-4ff1-9e9e-1b481adcf5ab)

**Comment by erdemildiz** [comment]
SOLVED Myself
```
  marker: {
       ...
          states: {
            hover: {
              enabled: false
            }
          }
        }
```

**Comment by AAChartModel** [comment]
Refer to:
 * https://github.com/AAChartModel/AAChartKit/issues/1345
