### ISSUE TITLE
Datalabels font size and font weight commitment is gone

### ISSUE THREAD

**Issue by skuske** [AAChartModel/AAChartKit#160]
You merged my datalabels font size and font weight commitment today, but now it's gone... ???

**Comment by skuske** [comment]
All required changes in AAOptionsConstructor.m are gone...

**Comment by skuske** [comment]
Columnrange and arearange datalabels do not appear.

**Comment by skuske** [comment]
I tested this again with AAChartTypeColumnrange and AAChartTypeArearange - the data labels do not appear...

**Comment by AAChartModel** [comment]
I merged it and changed a lot of my code because there are many duplicated content,then I did some mistakes,I have corrected it now.

**Comment by skuske** [comment]
Cool. Thanks! :o)

**Comment by AAChartModel** [comment]
😄
