### ISSUE TITLE
Updated project description

### ISSUE THREAD

**Issue by skuske** [AAChartModel/AAChartKit#164]
@"An An': is that your name? I was not sure how to contact you directly. Therefore I send you an updated project description as an issue... ;o)

Your old description reads better when you change it to this:

> AAChartKit is an elegant, friendly and easy to use chart library for iOS, based on the open source ‚Highcharts‘ JS libraries. AAChartKit is extremely powerful, easy to configure and a pleasure to use. Currently AAChartKit includes support for the following chart types: column chart, bar chart, area chart, area spline chart, line chart, spline chart, radar chart, polar chart, pie chart, bubble chart, pyramid chart, funnel chart, column range and arrange chart. More chart types are planned to be supported. AAChartKit gives you easy and fast access to a wide range of chart types, hassle free and quickly to integrate into your own project.

Hope that helps. When I find the time I'll need updating the readme and will also commit a few things. Great project - keep up the brilliant work.

Best wishes,

Stefan

**Comment by AAChartModel** [comment]
The space of description in GitHub is too small to show the whole content ,so I replaced my preface in README with your new description rather than  my `old description` .^_^

**Comment by skuske** [comment]
🥇 :o)
