### ISSUE TITLE
修改barChart的浮动提示框的显示内容？

### ISSUE THREAD

**Issue by JonKerr-China** [AAChartModel/AAChartKit#166]
你好，最近在用您的框架做柱状图表。有个需求是点击柱状图时，浮动框能显示除了对应Y轴值以外的其他值。请问有什么办法，或者在哪修改源码能做到呢？

**Comment by AAChartModel** [comment]
感觉应该不需要修改源码,只需要对 AAChartModel 的属性作相应的自定义设置即可.可否具体描述一下还要显示除了 Y轴以外的其他的那些值?

**Comment by JonKerr-China** [comment]
谢谢您的及时回答。现在需求是，显示几个股票，Y轴的值是只显示持股变动的值，但是点击bar以后显示的浮动框，除了显示持股变动，还需要显示累计持有的值。

**Comment by AAChartModel** [comment]
同一个条形图图表,单独点击一个 bar,这个bar 显示的"累计持有的值"是不变的吗?就是说手在左右滑动的时候,累计持有的值一直是固定的某一个值,不会变化吧?如果累计持有的值也会变化,估计 AAChartKit 做不到啊

**Comment by JonKerr-China** [comment]
...这样吗...谢谢您啦。T.T

**Comment by JonKerr-China** [comment]
再打扰下，请问有办法在替换ToolTip上变动的数值吗？ 就是不显示“持股变动”了。只显示变动的“累计持有的值”。

**Comment by AAChartModel** [comment]
https://api.hcharts.cn/highcharts#tooltip
这里是 highcharts 官网的有关于修改 tooltip 内容和样式的文档,你找找看,恐怕应该是没有能够满足你需要的接口.不过说实话,我具体也不是很明白你说的究竟是要什么效果😢

**Comment by JonKerr-China** [comment]
![temp](https://user-images.githubusercontent.com/24284157/35836957-14b16d8c-0b1e-11e8-80af-c731a31ea2f4.jpg)类似这样的效果的。如果累计值不能另外加，能不能把第一个对应Y轴的值替换了？

**Comment by ShobhitChourasia** [comment]
Any updates on this, as I also need to update the value of x-axis data in the prompt box.

Translated from google: 
对此进行任何更新，因为我还需要在提示框中更新x轴数据的值。

**Comment by a123478we** [comment]
@AAChartModel 能够修改浮动框  标题的内容吗？

**Comment by AAChartModel** [comment]
问题已解决,参见问题 #569
