### ISSUE TITLE
如何禁止手指按住AAChartView的tipsTool跟着移动

### ISSUE THREAD

**Issue by BinBear** [AAChartModel/AAChartKit#168]
您好：
有几个问题想请教一下。
1、我想禁止手指按住AAChartView的tipsTool跟着移动，因为我项目中要做成banner图那样，一屏显示一个AAChartView，这样的话就会手势冲突
2、坐标点数可以跟x格数不一样吗，因为我一个区间内有四个点

**Comment by AAChartModel** [comment]
> 1、我想禁止手指按住AAChartView的tipsTool跟着移动


这个你将 AAChartKit 中的 AATooltip.h中的
```objective- c
//AAPropStatementAndFuncStatement(assign, AATooltip, BOOL,       followTouchMove);//在触摸设备上，tooltip.followTouchMove选项为true（默认）时，平移需要两根手指。若要允许用一根手指平移，请将followTouchMove设置为false。
```
解开注释就可以了

**Comment by AAChartModel** [comment]
> 2、坐标点数可以跟x格数不一样吗，因为我一个区间内有四个点

这个是啥意思?如果你说的是嫌弃 X轴的文字数量过多,太密集,你可以设置 AAChartModel 的xAxisTickInterval属性即可.这个属性是用来设置x轴刻度点间隔数(设置每隔几个点显示一个 X轴的内容)

**Comment by AAChartModel** [comment]
>    2、坐标点数可以跟x格数不一样吗，因为我一个区间内有四个点

如果你的X轴坐标点间隔不是均匀的,有一个简单粗暴的方式,将
```objective-c
        _aaChartModel.categories = @[@"Java", @"Swift", @"Python", @"Ruby", @"PHP", @"Go", @"C", @"C#", @"C++", @"Perl", @"R", @"MATLAB", @"SQL"];//设置 X 轴坐标内容
```

改为
```objective-c

        _aaChartModel.categories = @[@"Java", @"", @"", @"", @"", @"", @"C", @"C#", @"C++", @"Perl", @"R", @"MATLAB", @"SQL"];//设置 X 轴坐标内容
```

空字符串的部分就默认不显示了

**Comment by AAChartModel** [comment]
能给一张图说明一下吗?

**Comment by BinBear** [comment]
![image](https://user-images.githubusercontent.com/13587915/35916315-fac4fe48-0c44-11e8-8f9e-4793d7241d63.png)
这样子的

**Comment by AAChartModel** [comment]
这种情况那就只能是我上文所说的,设置 AAChartModel 的属性xAxisTickInterval(设置每隔几个点显示一个 X轴的内容),你先尝试一下,看是不是你要的效果

**Comment by BinBear** [comment]
效果不是很好，因为x轴是固定的，但是坐标点不固定，这样就没法确定隔几个点。

**Comment by BinBear** [comment]
现在想请教一下另外一个问题：
![image](https://user-images.githubusercontent.com/13587915/35964964-4933624a-0cf4-11e8-9bbd-44c1b64e5a45.png)
就是能不能把提示框里面的数字小数位前每三位显示逗号，而不是显示空格

**Comment by AAChartModel** [comment]
这种冷门的奇怪需求恐怕无法满足

https://api.hcharts.cn/highcharts#tooltip
这里是 highcharts 的自定义tooltip 样式和内容的文档链接,你可以看看,应该是无法支持此类较为琐碎的极其微小的细节设置的.

**Comment by AAChartModel** [comment]
重点是 tooltip 的这个函数属性pointFormat
一个不同值的后缀的某点格式 https://code.hcharts.cn/highcharts/hhhhGw

**Comment by AAChartModel** [comment]
兄弟,抱歉了😢,我又仔细研究了一下文档,似乎确实可以格式化字符串内容样式,下班回去尝试着改一下再答复你.

**Comment by BinBear** [comment]
@AAChartModel 👌，辛苦了，感谢。其实这个细节设置倒还好，主要是x轴是固定的，坐标点不固定的绘制这个需求不好弄

**Comment by BinBear** [comment]
@AAChartModel 如何让tooltip的浮框默认显示最后一个点呢

**Comment by AAChartModel** [comment]
默认显示最后一个点？你是说保留小数点最后一位吗？

**Comment by AAChartModel** [comment]
还是说浮动提示框浮动显示在最后一个点的位置？

**Comment by BinBear** [comment]
@AAChartModel 浮动提示框浮动显示在最后一个点的位置

**Comment by BinBear** [comment]
@AAChartModel 浮动提示框浮动显示在最后一个点的位置有解决的办法吗，项目明天要上线了，比较急

**Comment by AAChartModel** [comment]
我查看了 highcharts 官方文档,似乎只有让 tooltip 始终显示在某一个固定位置的属性,但是没有一开始图表还未被点击时,就显示在某一个固定位置的功能,不知道下面的这种是不是能满足你们的业务需求
https://code.hcharts.cn/highcharts/hhhhGx

**Comment by AAChartModel** [comment]
如果不行的话,恐怕就办不到了,因为基于 highcharts 封装的 AAChartKit 基本不可能做到超出 highcharts 本身以外的功能.

**Comment by AAChartModel** [comment]
到时候建议可以看看 Swift 版本的 charts, 可能会有相应的解决办法

**Comment by BinBear** [comment]
@AAChartModel 那如果是要让 tooltip 始终显示在某一个固定位置的话，那还怎么设置呢，直接修改Js文件吗？

**Comment by AAChartModel** [comment]
直接加上下面这些吧
放弃上面的操作,换为下面的这种,避免出现长长的的 tooltip 连线

直接在 AAChartView.html 代码
``` js
                JavaScriptObject.credits = {enabled:false};//去掉表格右下角版权信息
```
```js
                var tooltip = JavaScriptObject.tooltip;
                tooltip.positioner = function () {
                    return { x: 80, y: 50 };
                };
                tooltip.borderWidth = 0;
                tooltip.shadow = false;
```
