### ISSUE TITLE
作者你好，想问下UIScrollView里嵌套多个ChartView滑动冲突怎么解决

### ISSUE THREAD

**Issue by boomstack** [AAChartModel/AAChartKit#171]
UIScrollView里放了5个表格，无法滑动，禁止掉了wkWebView的滑动和用户交互，但是UIScrollView也滑动不了

**Comment by AAChartModel** [comment]
只是禁用了 AAChartView 的滑动和交互,应该是不会对 UIScrollView 的滑动交互产生影响的啊,有 Demo 吗?

**Comment by AAChartModel** [comment]
想一想,父视图和子视图的用户交互手势相同时,容易产生手势冲突.但是你现在都已经禁用了 AAChartView 的滑动和用户交互,没有理由还会有手势冲突啊.这个时候如果你的 AAChartView 的父视图(也就是 UIScrollView)仍然不能滑动,更大的肯能性是你的个人代码有些许问题,跟 AAChartKit 的关系应该不大

**Comment by boomstack** [comment]
多谢作者提醒！用的masnory，是其他视图更新后ScrollView的布局没更新，思维还没从Android转过来，哈哈

**Comment by AAChartModel** [comment]
Android? 话说大佬是要往全栈方向发展么?
