### ISSUE TITLE
哈喽 大神 新年快乐 我又来了

### ISSUE THREAD

**Issue by DreamForStar** [AAChartModel/AAChartKit#176]
赶在十五之前说声新年快乐,又来找你帮我解决问题,
```js
 {
            score = 0;
            time = "00:00";
        },
                {
            score = 0;
            time = "01:00";
        },
```
服务器返回的这样的类型 时间和对应的数据 让在一个字典里面 除了我自己把数据抽出来重新整理 还有比较简易的方法解决吗 不胜感激.

**Comment by AAChartModel** [comment]
这个恐怕要让你的后台改一下json数据结构了,这是最快最轻便的办法😊

**Comment by DreamForStar** [comment]
恩恩 我自己把他当数据拿过来 然后自己有重新组合了一下 但是今天报了AAHighchartsLib.js, NSLocalizedDescription=发生 JavaScript 异常 这样的一个错误 数据拿到就直接去设置cell了 而且 刷新tableview也没有任何作用 求解

**Comment by DreamForStar** [comment]
☠️☠️💀☠️☠️WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______Error Domain=WKErrorDomain Code=4 "发生 JavaScript 异常" UserInfo={WKJavaScriptExceptionLineNumber=10, WKJavaScriptExceptionMessage=Error: Highcharts error #14: www.highcharts.com/errors/14, WKJavaScriptExceptionColumnNumber=55, WKJavaScriptExceptionSourceURL=file:///Users/dreamforstar/Library/Developer/CoreSimulator/Devices/975B46B4-F5DD-42B4-B224-AFF737BFFCD8/data/Containers/Bundle/Application/8287EB9E-DE8A-4CE8-B29D-9946AC132A21/XXX.app/AAHighchartsLib.js, NSLocalizedDescription=发生 JavaScript 异常}

**Comment by DreamForStar** [comment]
完整的报错..

**Comment by DreamForStar** [comment]
sorry 元宵节快乐 我自己傻了```

**Comment by AAChartModel** [comment]
>  我自己傻了
你的意思是这个报错的问题是你自己误操作导致的?现在解决了?

**Comment by DreamForStar** [comment]
是的 是我自己传过去的数据有问题 所以出错了 现在解决了

**Comment by AAChartModel** [comment]
大兄弟,描述问题的时候要清晰简单一些啊,你这样肆意挥洒情绪,搞得我有点懵逼呢.那我现在关闭问题了,有新的问题,再开一个 issue😊
