### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by skuske** [AAChartModel/AAChartKit#183]
I see the following leaks while using AAChartKit - you can reproduce this when you open the demo, then open the ColumnChart demo screen. When you profile this in Instruments, you see the following memory leaks. How can we fix that?

![bildschirmfoto 2018-03-05 um 10 55 18 kopie](https://user-images.githubusercontent.com/12996815/36968842-0a308496-2064-11e8-84b4-4200274c2a65.png)

**Comment by AAChartModel** [comment]
Can you fix that?please help me!😊

**Comment by skuske** [comment]
Looks like it is related to the AAJsonConverter:

![bildschirmfoto 2018-03-05 um 11 08 53](https://user-images.githubusercontent.com/12996815/36969422-bab06eac-2065-11e8-8348-425e87fee1cc.png)

**Comment by AAChartModel** [comment]
I need more time to resolve this problem😢

**Comment by skuske** [comment]
I found the cause. You need to 

`free(props);`

in line 57 of AAJsonConverter.m:

```
+ (NSDictionary*)getObjectData:(id)obj {
    NSMutableDictionary *dic = [NSMutableDictionary dictionary];
    unsigned int propsCount;
    Class class = [obj class];
    do {
        objc_property_t *props = class_copyPropertyList(class, &propsCount);
        for (int i = 0;i < propsCount; i++) {
            objc_property_t prop = props[i];
            
            NSString *propName = [NSString stringWithUTF8String:property_getName(prop)];
            id value = [obj valueForKey:propName];
            if (value == nil) {
                value = [NSNull null];
                continue;
            } else {
                value = [self getObjectInternal:value];
            }
            [dic setObject:value forKey:propName];
        }
        free(props);
        class = [class superclass];
    } while (class != [NSObject class]);
    
    return dic;
}
```
