### ISSUE TITLE
我自定义的xlabels，但是显示没有按照我定义的显示来

### ISSUE THREAD

**Issue by songbai1211** [AAChartModel/AAChartKit#186]
大神，我自己定义的x 轴的坐标
```js
@"04", @"05",@"06",@"07",@"08",@"09",@"10",@"11",@"12",@"13",@"14",@"15",@"16",@"17",@"18",@"17",
@"18",@"19",@"20",@"21",@"22",@"23",@"24",@"25",@"26",@"27",@"28",@"1",@"2",@"3"，
```
但是显示的时候就变了，从28后就变了，麻烦大神给看下，谢谢了
![528c94d7-1b5f-406f-b527-1918047adbc1](https://user-images.githubusercontent.com/4758161/37080201-5b3a02fa-2220-11e8-9067-8d6efe3d1d7b.png)

**Comment by AAChartModel** [comment]
不是变了,你仔细看这里每隔一个刻度就隐藏了一个刻度值,是因为你的 X轴值太多了, highcharts 自动每隔一段隐藏一部分值,你可以横屏查看一下,应该就能够全部显示出来了

**Comment by songbai1211** [comment]
大神，我看了，显示的还是28后，显示的感觉不对，这个能全部显示出来吗？或者说这种情况怎么处理好点，因为我们是从当日算起，让前面推30天，有没有解决方法，？谢谢啊

**Comment by songbai1211** [comment]
我看了下，主要是我这个是单数导致最后一个数字出现错了，数组是29个，导致错误了，

**Comment by AAChartModel** [comment]
你有使用 GitHub 上其他的图表库吗?如果只是单纯地绘制折线图这一种图表,倒不是十分建议使用 AAChartKit. 可能其他的专门的绘制折线图的图表库是更好的选择.

**Comment by songbai1211** [comment]
谢谢了，已经改掉了，改成偶数就可以了，（只用了你家，还有饼状图什么）哈哈，再次🙏😂

**Comment by AAChartModel** [comment]
我好想不太明白你说的单数和偶数指的是什么呢!!!😅不过还是欢迎你再次提问😊
