### ISSUE TITLE
如果y坐标都是0的话，折线图无法显示

### ISSUE THREAD

**Issue by heichong** [AAChartModel/AAChartKit#2]
如果y坐标都是0的话，折线图无法显示，有没有办法让它显示？

**Comment by AAChartModel** [comment]
感谢提交的问题,现已改为当数据全为0时,居中显示一条横线,纵坐标显示为0(highcharts默认样式).

**Comment by TomLongJoy** [comment]
数据为0的时候怎么让横线在X轴上。
![zero_line](https://user-images.githubusercontent.com/18641052/54519220-f9706b00-49a0-11e9-94bb-3f90242a7906.png)

**Comment by AAChartModel** [comment]
@TomLongJoy 

参见 https://github.com/AAChartModel/AAChartKit/issues/773#issuecomment-568376674
