### ISSUE TITLE
你好，加载网络上的js代码，表格右下角的highChart logo能去掉吗？

### ISSUE THREAD

**Issue by xiongoahc** [AAChartModel/AAChartKit#20]

**Comment by AAChartModel** [comment]
关于版权信息,请点击查看这里
https://www.hcharts.cn/docs/basic-credits

**Comment by xiongoahc** [comment]
版权信息是默认显示的，若不需要可以通过增加代码：

credits:{
     enabled:false // 禁用版权信息
}
作为iOSer的我不知道加在哪里，求指教，谢谢

**Comment by xiongoahc** [comment]
![image](https://cloud.githubusercontent.com/assets/22147969/26185473/c361204c-3bbd-11e7-838a-ac7fd018c1ff.png)
在请教我们前端姐姐之后，解决了O(∩_∩)O哈哈~
JavaScriptObject.credits = {enabled:false};//去掉右下角版权信息

**Comment by AAChartModel** [comment]
提交代码,让我合并一下呗☺
