### ISSUE TITLE
视图重复添加了

### ISSUE THREAD

**Issue by dagundejuzi** [AAChartModel/AAChartKit#201]
我看了下图层，有两个 webview，发现是 init方法导致添加了两遍。注释掉一个就好了。
![snip20180313_2](https://user-images.githubusercontent.com/16382880/37295679-bba0f1b2-2653-11e8-9bd2-05d333779c00.png)

**Comment by AAChartModel** [comment]
😅额,这个问题不是早在你提的这个 issue #93  当中就解决了么?

**Comment by dagundejuzi** [comment]
哦，我说这个问题怎么那么眼熟。。。直接 git clone 下来的还是17年的，要怎么才能拿到最新的？

**Comment by AAChartModel** [comment]
直接点击仓库的下载按钮下载吧
