### ISSUE TITLE
是否支持设置柱形图的柱子宽度？

### ISSUE THREAD

**Issue by MickeyLeez** [AAChartModel/AAChartKit#203]
是否支持设置柱形图的柱子宽度？

**Comment by AAChartModel** [comment]
然后调用 AAChartView 的这个绘图方法
```objective-c
        [aaChartView aa_drawChartWithOptions:aaOptions];

```

**Comment by topws** [comment]
@AAChartModel 我设置自定义的宽度后，为啥有的柱之间的间距会不同（个别情况，如下图）
<img width="444" alt="6ddadbeb-943a-4647-9ad8-c72cae025442" src="https://user-images.githubusercontent.com/16485279/45085772-1a275080-b134-11e8-99df-c5ef0d33865c.png">

下面是设置的代码：
AAPlotOptions *plotOptions = AAObject(AAPlotOptions);
	AASeries *aaplotSeries = AAObject(AASeries);
	AAChartModel *aaChartModel= AAObject(AAChartModel);
	aaplotSeries.animation = (AAObject(AAAnimation)
							  .easingSet(aaChartModel.animationType)
							  .durationSet(aaChartModel.animationDuration)
							  );
	plotOptions.series = aaplotSeries;
	
	AADataLabels *aaDataLabels;
	AAColumn *aaColumn = (AAObject(AAColumn)
						  .borderWidthSet(@0)
						  .groupPaddingSet(@0.1)
						  .dataLabelsSet(aaDataLabels));
	plotOptions.column = aaColumn;
	chartOptions.plotOptions = plotOptions;

**Comment by AAChartModel** [comment]
@topws 这个可能就是 Highcharts 的 bug 了!

**Comment by topws** [comment]
好吧，我去原库看看有没有解决方案

**Comment by chang-gong** [comment]
@AAChartModel  柱形范围图类型 AAChartTypeColumnrange 按照上面的方法设置柱子宽度无效
