### ISSUE TITLE
请问有没有点击每个柱形的回调，和添加dataLabel 数据的单位

### ISSUE THREAD

**Issue by zhaoyuntian** [AAChartModel/AAChartKit#208]
![2018-03-16 11 00 39](https://user-images.githubusercontent.com/16586931/37501424-502d21a4-2909-11e8-8bc8-dfba1bf4f6a0.png)

**Comment by AAChartModel** [comment]
暂未添加此功能

**Comment by zhaoyuntian** [comment]
OK

**Comment by AAChartModel** [comment]
获取柱形图表的点击事件回调, 参见  #810

**Comment by AAChartModel** [comment]
> 添加dataLabel 数据的单位

参见 #521  和 #589
