### ISSUE TITLE
圆形图

### ISSUE THREAD

**Issue by yuxinuser** [AAChartModel/AAChartKit#213]
这个可以显示圆形图的吗 就是图中间显示文字 边缘是一个类似进度的

**Comment by AAChartModel** [comment]
这个真没有🤣

**Comment by yuxinuser** [comment]
谢谢 这个我看了找到一个和你的这个结合下就可以实现了

**Comment by AAChartModel** [comment]
如果只是单纯地要画一个环形进度条,应该用不着 AAChartKit 吧,你说的结合一下是什么情况?

**Comment by yuxinuser** [comment]
就是我们里面有四种样式的图表还是感谢了现在都可以解决了

**Comment by AAChartModel** [comment]
也就是说 AAChartKit 解决了余下的三种类型图表?可以说是很荣幸了 O(∩_∩)O哈哈~

**Comment by yuxinuser** [comment]
对的 是的呢
