### ISSUE TITLE
为什么选择用highcharts而不是echarts?

### ISSUE THREAD

**Issue by wushenchao** [AAChartModel/AAChartKit#216]
为什么选择用highcharts而不是echarts?

**Comment by AAChartModel** [comment]
* 之前的公司在进行前端图表工具库选型时,选用了Highcharts,也已经是相当于替我做了一次选型
 *  Highcharts已经营多年,社区发展更成熟,文档更齐全
 * 因为我之前的公司在手机端实现数据分析功能时,使用的就是Highcharts,所以对Highcharts很熟悉,额外学习Echart有很高的学习成本.
 * 个人感觉Highcharts的图形参数配置更加的人性化
 * Highcharts的图表交互细节更丰富,渲染动画更精致,默认的UI也漂亮
 * 不想在工作之外再学习另一个没有明显优势的工具库
 * 人的选择本来就有随机性,哪里有那么多为什么 😄O(∩_∩)O😄！
