### ISSUE TITLE
区域图的颜色渐变 和 tooltip固定显示

### ISSUE THREAD

**Issue by dagundejuzi** [AAChartModel/AAChartKit#217]
目标是这样，只差 tiptool 和区域的颜色渐变。
![snip20180327_6](https://user-images.githubusercontent.com/16382880/37942741-33a0cc56-31a7-11e8-88fa-dc9a3b64284e.png)

1、想解决区域的蓝紫色渐变。
已知 AAOptions 的 `colorsSet` 和 `gradientColorEnableSet` 其实是对数据点颜色的设置，区域的颜色设置是AASeries的`fillColor`，看了 highcharts 官网，它支持多个颜色的，所以尝试加了

`AAPropStatementAndFuncStatement(strong,   AASeries, NSArray     *, fillColor);`

但是这样整个区域的颜色都没了，如果用NSString 类型，是可以设置颜色，但是是单色。

2、怎么让提示框在每个数据点都固定的显示？

**Comment by dagundejuzi** [comment]
回复好快！文字太密了我换成了图片。。。 tooltip的找到问题了，固定显示的还没解决。
这是我们自己的效果。

**Comment by dagundejuzi** [comment]
这个改动地方还蛮多的，想把这个作为 demo 加到这个框架里，但是，我不知道怎么合进去，fork吗？

**Comment by dagundejuzi** [comment]
还担心改的地方和原框架会有冲突

**Comment by AAChartModel** [comment]
我最近 对 AAChartKit 改的东西比较多,你如果想要将改动的东西合并到 AAChartKit 中,需要 fork 一下最新的代码,再手动添加你的代码,,最后向我提交一个 Pull Request

**Comment by dagundejuzi** [comment]
那个，区域内多个颜色渐变，和每个数据点都固定显示 tooltip 的还没搞定。。。

**Comment by AAChartModel** [comment]
查了一下文档,感觉实现起来应该不困难,我将在这个周末抽空加上实现的示例

**Comment by dagundejuzi** [comment]
还有个问题，想要数据线挨着 Y轴开始绘制，要设置什么值？或者加上哪个属性？

**Comment by dagundejuzi** [comment]
虽然有个 offset 属性，但是它是以像素为单位的，不同大小的屏幕不好算啊。

**Comment by AAChartModel** [comment]
抱歉,我在 Highcharts 官网上目前还没找到那个属性是用来设置你要的这个功能的.

**Comment by dagundejuzi** [comment]
我是看到实例图有些是从 y 轴开始绘制的，而且这个需求应该蛮常见的，感觉应该可以设置。可能是要组合设置？

**Comment by dagundejuzi** [comment]
比如这个示例： https://code.hcharts.cn/highcharts/hhhhgW

**Comment by AAChartModel** [comment]
官方的从 y 轴开始的是那些没有设置 categories 的图表,如果设置了categories就默认居中显示了

**Comment by dagundejuzi** [comment]
那不设置categories的话，X轴要显示 label，用什么属性？

**Comment by AAChartModel** [comment]
暂时还没有找到😳

**Comment by dagundejuzi** [comment]
还有数据区域的渐变色，图片里蓝紫色渐变的那个，只要能让AASeries的fillColor，支持数组形式的就好了。。。

**Comment by AAChartModel** [comment]
支持数组形式?你是要做成什么样式,现在不是已经支持颜色渐变功能吗?
