### ISSUE TITLE
请教楼主这个是什么问题。

### ISSUE THREAD

**Issue by doomc** [AAChartModel/AAChartKit#218]
```java
-------> AAChartView.m [Line 265] 
☠️☠️💀☠️☠️WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______Error 
Domain=WKErrorDomain Code=4 "发生 JavaScript 异常" 
UserInfo={WKJavaScriptExceptionLineNumber=1, 
WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: loadTheHighChartView, 
WKJavaScriptExceptionColumnNumber=21, 
WKJavaScriptExceptionSourceURL=about:blank, 
NSLocalizedDescription=发生 JavaScript 异常}
```

**Comment by AAChartModel** [comment]
在没有成功加载` AAChartView.html` 文件上下文时,就先使用了 AAChartView 调用 js 函数的方法,就会报这种错误❌.

**Comment by AAChartModel** [comment]
注意 README 文档中的使用说明
4.  绘制图形(创建 AAChartView 实例对象后,首次绘制图形调用此方法)
```objective-c
/*图表视图对象调用图表模型对象,绘制最终图形*/
[chartView aa_drawChartWithChartModel:chartModel];
```
5.  刷新图形(首次绘制图形完成之后,后续刷新均建议调用此方法)
```objective-c
/*更新 AAChartModel 内容之后,刷新图表*/
[chartView aa_refreshChartWithChartModel:chartModel];
```

6.  仅仅刷新图形的数据(进行数据的动态更新操作时,建议使用此方法)
```objective-c
/*仅仅更新 AAChartModel 对象的 series 属性时,动态刷新图表*/
[chartView aa_onlyRefreshTheChartDataWithChartModel:chartModel];
```

**Comment by AAChartModel** [comment]
只有先调用了aa_drawChartWithChartModel方法,然后才能调用
`aa_onlyRefreshTheChartDataWithChartModelSeries `方法
或者是
`aa_refreshChartWithChartModel`方法

**Comment by doomc** [comment]
感谢楼主解答，我是先调用了aa_drawChartWithChartModel方法  -> 然后aa_refreshChartWithChartModel ，当绘制完毕后就出来上述问题了，问题还需讨论

**Comment by doomc** [comment]
AAChartView.html 删除后可以屏蔽路径问题吗

**Comment by AAChartModel** [comment]
要靠 AAChartView 来加载AAChartView.html文件来实现绘图功能,你删除了html 文件肯定就连图表都无法绘制了啊

**Comment by doomc** [comment]
我看简述不是可以删除5项嘛 误导了，误导了。还是说上述问题吧

**Comment by doomc** [comment]
- (void)AAChartViewDidFinishLoad {
    NSLog(@"🔥🔥🔥🔥🔥 AAChartView content did finish load!!!");
}
这个方法表示绘制完毕 而且完成了对吗

**Comment by AAChartModel** [comment]
是的

**Comment by doomc** [comment]
我最后的打印日志是这样的
2018-03-27 17:16:49.561131+0800 JKHousekeeper[7409:1341608] -------> AAChartView.m [Line 265] 
☠️☠️💀☠️☠️WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______Error Domain=WKErrorDomain Code=4 "发生 JavaScript 异常" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: loadTheHighChartView, WKJavaScriptExceptionColumnNumber=21, WKJavaScriptExceptionSourceURL=about:blank, NSLocalizedDescription=发生 JavaScript 异常}


2018-03-27 17:17:00.752593+0800 JKHousekeeper[7409:1341850] [MTA] DidDisconnect:withError: "Error Domain=MTAGCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer}"
2018-03-27 17:17:05.040532+0800 JKHousekeeper[7409:1341608] 🔥🔥🔥🔥🔥 AAChartView content did finish load!!!

**Comment by doomc** [comment]
最后绘制的图形会加载出来，但是延迟了2s

**Comment by doomc** [comment]
我是在移除AAJSFiles 文件 和 html 修改了之后才出现的

**Comment by AAChartModel** [comment]
你误会了我的说明文档中的意思了

## 附言

在 ***AAChartKit*** 封装库的初始设计中,为提升`.js`文件的加载速度,故将所依赖的`.js`文件放置在本地.然而由于本项目功能较多,故放置于本地的附加`JavaScript`文件库体积较大,整个`AAJSFiles`文件夹下所有的`.js`文件体积合计共有`250KB左右`(当然,在项目打包为压缩后的`.ipa`工程安装包文件时,是远小于这个体积的),若对工程文件体积大小较为敏感的使用者,可使用以下建议的替代方案
1.  删除在本 ***AAChartKit*** 项目文件中,`AAJSFiles`文件夹下的`4`项`.js`文件.需要被删除的文件名称如下
* AAHighchartsLib.js
* AAHighchartsMore.js
* AAHighcharts-3d.js
* AAFunnel.js
2.  将`AAChartView.html`文件中的以下内容
``` html
<script src="AAHighchartsLib.js">
</script>
<script src="AAHighchartsMore.js">
</script>
<script src="AAHighcharts-3d.js">
</script>
<script src="AAFunnel.js">
</script>
```
替换为
``` html
<script src="https://img.hcharts.cn/highcharts/highcharts.js">
</script>
<script src="https://img.hcharts.cn/highcharts/highcharts-more.js">
</script>
```
即可.

**Comment by AAChartModel** [comment]
我的文中可没有说明可以删除 HTMl 文件啊,文中的意思是想要缩减 AAChartKit 体积大小,可以删除所依赖的 `JS` 文件注意是 `JS` 文件

**Comment by doomc** [comment]
没有使用替代方案，问题还是一样哦。感谢楼主回复

**Comment by AAChartModel** [comment]
那就只能让你给个 Demo 了,不然这里面比较难以判断到底是什么原因了.
可以肯定的是你一定是在错误的时机调用了`aa_refreshChartWithChartModel`

**Comment by doomc** [comment]
我的一个测试demo，麻烦帮我看看我想搞清楚具体原因

**Comment by doomc** [comment]
楼主方便留个邮箱吗

**Comment by DogTwoChen** [comment]
同时使用aa_drawChartWithChartModel和aa_drawChartWithOptions,会产生此问题,注掉aa_drawChartWithOptions就不再报此错误
