### ISSUE TITLE
请问柱状图中的柱宽是固定的吗？是否可以自定义。

### ISSUE THREAD

**Issue by BoYangZuo** [AAChartModel/AAChartKit#227]
本以为是xAxisGridLineWidth属性 可是设置以后发现这个属性是点击某个柱子之后出现的视图的宽度 找了N遍有没有发现对应的属性

**Comment by BoYangZuo** [comment]
貌似只能通过设置contentWidth和x轴的坐标个数来定义宽度

**Comment by AAChartModel** [comment]
不是,有人提过和你一样的issue,已经关闭了

**Comment by AAChartModel** [comment]
参见issue #203  https://github.com/AAChartModel/AAChartKit/issues/203

**Comment by AAChartModel** [comment]
Demo 中也有示例啊,就是那个 cell 上的标题为:"缝隙很小的柱状图"示例,目前只能通过调整棱柱之间的间隙百分比来间接调整棱柱的宽度.
