### ISSUE TITLE
能不能自定义显示顺序

### ISSUE THREAD

**Issue by TierZ** [AAChartModel/AAChartKit#232]
如下图，一个是demo里的样式，一个是我这边的需求，就是显示的时候，能不能顺序设置成一样的，我看您那个图表的颜色 和悬浮框上面的 以及下面标注 的 顺序是相反的

![1](https://user-images.githubusercontent.com/24585019/38549532-cace82cc-3ce6-11e8-9dd1-ce82422a8d1c.png)
![2](https://user-images.githubusercontent.com/24585019/38549533-cb2c6f22-3ce6-11e8-8cb2-3da69a5ffbb8.png)

**Comment by AAChartModel** [comment]
至于你下面的那个显示效果应该是百度的 echart的效果,你可以尝试使用echart 解决这个问题

**Comment by AAChartModel** [comment]
![img_0072](https://user-images.githubusercontent.com/16357599/38551820-c2bd9a40-3cec-11e8-8a1f-71340790a512.PNG)
你也可以设置 AAChartModel 的`yAxisReversed`为 true, 也可以达到你要的这个效果,不过这个只对图表的堆积样式为 *AAChartStackingTypePercent* 适用

**Comment by AAChartModel** [comment]
reversed: Boolean  
设定图例项排列顺序是否相对于数列的排列顺序做逆序。 默认是：false.
在线实例： Stacked bar with reversed legend
https://code.hcharts.cn/highcharts/hhhhXr
