### ISSUE TITLE
aa_onlyRefreshTheChartDataWithChartModelSeries请问这个方法怎么用的

### ISSUE THREAD

**Issue by vlove550** [AAChartModel/AAChartKit#236]
![d1004be0-75af-4313-840e-e5e176fd25f3](https://user-images.githubusercontent.com/13690937/38609237-25661bd6-3db0-11e8-95cf-b6a123a799d4.png)
这样写为什么回报错的？

**Comment by vlove550** [comment]
self.pieChartView = [[AAChartView alloc]initWithFrame:CGRectMake(0, 0, SCREEN_WIDTH, 300)];
    ////设置图表视图的内容高度(默认 contentHeight 和 AAChartView 的高度相同)
    //self.aaChartView.contentHeight = self.view.frame.size.height-250;
    [self.view addSubview:self.pieChartView];
    
    AAChartModel *pieChartModel = AAObject(AAChartModel)
    .chartTypeSet(AAChartTypePie)
    .titleSet(@"型材类别统计(kg)")
    .subtitleSet(@"")
    .dataLabelEnabledSet(true)//是否直接显示扇形图数据
    .yAxisTitleSet(@"")
    .seriesSet(@[AAObject(AASeriesElement)
                 .nameSet(@"重量")
                 .dataSet(@[
                            @[@"门窗类",@8725]
                            ])
                 ]);
    [_pieChartView aa_drawChartWithChartModel:pieChartModel];
    
    NSArray *chartArray = @[AAObject(AASeriesElement)
                            .nameSet(@"重量")
                            .dataSet(@[
                                       @[@"门窗类",@8725],
                                       @[@"门窗类2",@300],
                                       @[@"门窗类3",@1800]
                                       ])
                            ];
    [_pieChartView aa_onlyRefreshTheChartDataWithChartModelSeries:chartArray];

**Comment by vlove550** [comment]
NSData *jsonData = [NSJSONSerialization dataWithJSONObject:series options:NSJSONWritingPrettyPrinted error:&parseError];
会解释json数据失败，会跳到这个方法

**Comment by AAChartModel** [comment]
换成这种就行了
```objective-c
    NSArray * chartArray = @[
                        @{@"name":@"重量",
                          @"data":@[
                                   @[@"门窗类",@8725],
                                   @[@"门窗类2",@300],
                                   @[@"门窗类3",@1800]
                                   ]},
                        ];
```

**Comment by AAChartModel** [comment]
```objective-c
- (void)aa_onlyRefreshTheChartDataWithOptionsSeries:(NSArray<NSDictionary *> *)series ;
```

注意这个函数接受的参数类型
`NSArray<NSDictionary *> *`
数组里面的元素必须是字典,不能是对象

**Comment by vlove550** [comment]
这样数据结构是对了，但是图表没有刷新数据，还是只有一开始的@"门窗类"，没有后面加上去的那些数据

**Comment by AAChartModel** [comment]
是不是控制台还报错了
```java
2018-04-12 10:54:34.114727+0800 AAChartKitDemo[22789:679597] -------> AAChartView.m [Line 264] 

☠️☠️💀☠️☠️WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred"
 UserInfo={
WKJavaScriptExceptionLineNumber=1, 
WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: onlyRefreshTheChartDataWithSeries, 
WKJavaScriptExceptionColumnNumber=34, 
WKJavaScriptExceptionSourceURL=about:blank, 
NSLocalizedDescription=A JavaScript exception occurred}
```

**Comment by AAChartModel** [comment]
```objective-c
    NSArray *chartSeriesArr = @[
                                @{@"name":@"重量",
                                  @"data":@[
                                          @[@"门窗类",@8725],
                                          @[@"门窗类2",@300],
                                          @[@"门窗类3",@1800]
                                          ]},
                                ];
    
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self.aaChartView aa_onlyRefreshTheChartDataWithChartModelSeries:chartSeriesArr];
    });
```
你改成这样就行了,延迟3秒钟再调用刷新数据的方法`aa_onlyRefreshTheChartDataWithChartModelSeries `,
因为这个方法必须在先调用了`aa_drawChartWithChartModel `,并且图表成功绘制之后才能使用,直接调用的话, AAChartView 找不到 html 上下文内容,就会报错

**Comment by AAChartModel** [comment]
你的这个也只是测试代码吧,真实的生产环境中,没有谁在图表绘制成功之后没有任何的时间延迟就立马刷新图表吧

**Comment by AAChartModel** [comment]
另外：你的这个门窗类数量在刷新前后不一致,导致 AAChartView 在刷新数据的时候过度不自然,不是平滑过渡的,有一种突然跳跃的感觉,改成这样会好一点
```objective-c
    AAChartModel *aaChartModel= AAObject(AAChartModel)
    .chartTypeSet(AAChartTypePie)
    .colorsThemeSet(@[@"#0c9674",@"#7dffc0",@"#d11b5f",@"#facd32",@"#ffffa0",@"#EA007B"])
    .titleSet(@"")
    .subtitleSet(@"")
    .dataLabelEnabledSet(true)//是否直接显示扇形图数据
    .yAxisTitleSet(@"摄氏度")
    .tooltipEnabledSet(false)//禁用浮动提示框 tooltip
    .seriesSet(@[
                 @{@"name":@"重量",
                   @"data":@[
                           @[@"门窗类",@25],
                           @[@"门窗类2",@0],
                           @[@"门窗类3",@0]
                           ]},]
               
               )
    ;
    
    [self.aaChartView aa_drawChartWithChartModel:aaChartModel];
    
    NSArray *chartSeriesArr = @[
                                @{@"name":@"重量",
                                  @"data":@[
                                          @[@"门窗类",@8725],
                                          @[@"门窗类2",@300],
                                          @[@"门窗类3",@1800]
                                          ]},
                                ];
    
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self.aaChartView aa_onlyRefreshTheChartDataWithChartModelSeries:chartSeriesArr];
    });
```

```objective-c
                           @[@"门窗类",@25],
                           @[@"门窗类2",@0],
                           @[@"门窗类3",@0]
```

门窗类2和门窗类3在没有值的时候,最好像上面👆这样直接设置为0,这样图表在刷新数据的时候才会有一个平滑的自然地过渡动画

**Comment by vlove550** [comment]
是的，是这个原因了！感谢大神分享这么好的框架！
