### ISSUE TITLE
关于扇形图

### ISSUE THREAD

**Issue by thj0808** [AAChartModel/AAChartKit#238]
￼扇形图是否可以只显示扇形，隐藏下边的那些小圆形（什么颜色代表什么内容的那些圆形图）

谢谢！

**Comment by AAChartModel** [comment]
设置 AAChartModel 的布尔属性legendEnabled = false(隐藏图形的图例)即可

**Comment by thj0808** [comment]
非常感谢，昨天没有仔细看属性值。

那再问个问题，是否可以在扇形图上显示文字呢

**Comment by AAChartModel** [comment]
demo中不是有示例吗?
