### ISSUE TITLE
警告问题

### ISSUE THREAD

**Issue by xorshine** [AAChartModel/AAChartKit#245]
☠️☠️💀☠️☠️WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______Error Domain=WKErrorDomain Code=4 "发生 JavaScript 异常" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: loadTheHighChartView, WKJavaScriptExceptionColumnNumber=21, WKJavaScriptExceptionSourceURL=about:blank, NSLocalizedDescription=发生 JavaScript 异常}

这个警告是怎么了？

**Comment by AAChartModel** [comment]
你应该是在不恰当的时间调用了AAChartView 的刷新的方法,这个报错是因为 AAChartView 还没有加载到 html 文件上下文内容,就先进行了 OC调用js 的操作,导致`AAChartView`找不到js函数.
