### ISSUE TITLE
[BUG] getJavaScriptFileURLRequest doesn't work via cocoapods

### ISSUE THREAD

**Issue by iKorich** [AAChartModel/AAChartKit#248]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'

**Comment by AAChartModel** [comment]
AAChartKit does not support cocoapods yet

**Comment by AAChartModel** [comment]
AAChartKit  supported `CocoaPods` ,More details in README file.
