### ISSUE TITLE
AAChartKit OC版本

### ISSUE THREAD

**Issue by dubin109222** [AAChartModel/AAChartKit#25]
我想问下这个OC版本的放大之后双指拖动可以改成单指拖动吗？我没有找到这个在哪里设置的

**Comment by AAChartModel** [comment]
感谢您所提的问题.由于`AAChartKit`是基于 `Highcharts` 的产物,很遗憾`Highcharts`在适配移动端时,并没有提供单指侧滑拖动图表的功能,所以确实` AAChartKit` 确实没有提供相关方面的功能,十分抱歉!
