### ISSUE TITLE
请问有点击条形图的  回调方法吗

### ISSUE THREAD

**Issue by zp19900223zp** [AAChartModel/AAChartKit#252]

**Comment by AAChartModel** [comment]
暂无此功能

**Comment by zp19900223zp** [comment]
我看你的代办事项里面，有这个功能，什么时候可以完善这个功能

**Comment by AAChartModel** [comment]
整个我无法做出准确的实际承诺啊,至少要一两个星期吧,因为我最近公司的鸟事确实是比较多,比较恶心.

**Comment by zp19900223zp** [comment]
好吧，如果完善了，可以发一份邮件吗

**Comment by zp19900223zp** [comment]
好的，功能很强大，效果非常的好，非常适合我开发的项目。美中不足的地方就是点击没有回调。

**Comment by lenkamao** [comment]
果然没有这个功能,我差点一行一行代码读取了.很感谢!但是我还是想问一下点击时候那个选中的准星线怎么实现的,其实我就是想加个回调事件

**Comment by kevinH0510** [comment]
急需点击事情。。。

**Comment by BadSuNian** [comment]
诶。。 这项目打包js了 放开吧  我们帮你完善

**Comment by AAChartModel** [comment]
AAChartKit 现已支持点击事件回调,参见已解决重复问题 #810 及 AAChartKit 中点击事件相关的 demo 代码.
