### ISSUE TITLE
Design Issue iOS

### ISSUE THREAD

**Issue by munish26** [AAChartModel/AAChartKit#255]
I am integrating it to ios devices. But facing an issue in the screen resolution of iPhone 5 and 6. The polar chart is going out of the screen and cutting the titles around the chart. Please check the attached screenshots and help me fix this 

Thanks
![6](https://user-images.githubusercontent.com/38952152/39581448-3a373990-4f09-11e8-90e4-29905aa8cb62.png)
![5s](https://user-images.githubusercontent.com/38952152/39581451-3ace7210-4f09-11e8-9ef1-5e5136b4177d.png)
![6](https://user-images.githubusercontent.com/38952152/39581453-3b0805c0-4f09-11e8-8419-14f95a7c1959.png)

**Comment by AAChartModel** [comment]
It is easy for me,I will fix it tomorrow😊

**Comment by AAChartModel** [comment]
Update AAChartKit Demo and do something as follow

1. Configure AAOptions instance object
```objective-c
    AAChartModel *aaChartModel= AAObject(AAChartModel)
    .chartTypeSet(AAChartTypeColumn)//图表类型
    .titleSet(@"")//图表主标题
    .subtitleSet(@"")//图表副标题
    .colorsThemeSet(@[@"#fe117c",@"#ffc069",@"#06caf4",@"#7dffc0"])//设置主体颜色数组
    .yAxisTitleSet(@"")//设置 Y 轴标题
    .polarSet(true)
    .categoriesSet(@[@"Java", @"Swift", @"Python", @"Ruby", @"PHP", @"Go", @"C", @"C#", @"C++", @"Perl", @"R", @"MATLAB", @"SQL"])
    .seriesSet(@[
                 AAObject(AASeriesElement)
                 .nameSet(@"2017")
                 .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6]),
                 ]
               );
    
    AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
    aaOptions.chart.marginLeft = @70;
    aaOptions.chart.marginRight = @70;
```

2. Draw chart with AAOptions instance object
```objective-c
    [aaChartView aa_drawChartWithOptions:aaOptions];
```

**Comment by AAChartModel** [comment]
The key content is this
```objective-c
 aaOptions.chart.marginLeft = @70;//configure the left margin of chart
 aaOptions.chart.marginRight = @70;//configure the right margin of chart
```

**Comment by munish26** [comment]
Hi, Thanks for the update

I am writing code in swift and unable to alloc      AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];


Please check and let me know if you can help in this
` viewChart = AAChartView.init(frame: CGRect(x:0, y:0, width:piechartBackView.frame.size.width, height:piechartBackView.frame.size.height))
        piechartBackView.addSubview(viewChart)
        viewChart.scrollEnabled = false
        piechartBackView.bringSubview(toFront: addbtn)
        
        let aaChartModel = AAChartModel()
        aaChartModel.chartType = AAChartTypeColumn
        aaChartModel.title = ""//The chart title
        aaChartModel.subtitle = ""//The chart title
        aaChartModel.dataLabelEnabled = false //Enable or disable the data labels. Defaults to false
        aaChartModel.polar = true
        aaChartModel.yAxisVisible = false
        aaChartModel.legendEnabled = false
        aaChartModel.borderRadius = 80
        aaChartModel.tooltipValueSuffix = ""//the value suffix of the chart tooltip
        let catArr = Array(pieChartData.keys)
        var valArr = [Float]()
        var nameLblArr = [String]()
        for item in catArr {
            nameLblArr.append(item.capitalized.replacingOccurrences(of: "_", with: " "))
            valArr.append(pieChartData[item] as? Float ?? 0.0)
        }
        aaChartModel.categories = nameLblArr
        
        aaChartModel.colorsTheme = ["#00b8a2"/*,"#ffc069","#06caf4","#7dffc0","#fe227c","#1dc6ad","#06ffac","#c94848"*/]
        
        let element1 = AASeriesElement() //"Value"
        element1.name = "Value"
        element1.data = valArr
        aaChartModel.series = [element1/*,element2,element3,element4,element5,element6,element7,element8*/]
        
        let aaOptions = AAOptions()
        aaOptions.chart.marginLeft = 70
        aaOptions.chart.marginRight = 70
        
//        viewChart.aa_drawChart(with: aaChartModel)
        viewChart.aa_drawChart(with: aaOptions)`

**Comment by AAChartModel** [comment]
Are you using AAChartKit or AAChartKit-Swift in your project?

**Comment by munish26** [comment]
AAChartKit

**Comment by AAChartModel** [comment]
Sorry,I have no experience on Swift and OC Hybrid programming,Maybe you should use AAChartKit-Swift in your project and change a little source code of AAChartKit-Swift for your project

**Comment by AAChartModel** [comment]
I wrote it in README and the font is bold !!! 😊

**Comment by munish26** [comment]
Okay, I will convert it, But Did you update these margin parameters in AAChartKit-Swift too?

I am trying to update this in your demo AAChartKit-Swift code and unable to access AAOptionsConstructor in Swift code too. Any lead on this  😔

**Comment by AAChartModel** [comment]
I will fix it later ,there is many difference between `AAChartKit` and `AAChartKit-Swift`

**Comment by munish26** [comment]
Can you tell me when you will update `AAChartKit-Swift `? I need to integrate it to my project on urgent bases, your support will be appreciable.

Thanks

**Comment by AAChartModel** [comment]
This week's weekend.😊
Speaking off topic, did you specifically register GitHub to raise this issue?

**Comment by munish26** [comment]
Yeah, They didn't allow me to post issue without an account. I have an account on bitbucket, not on github.

**Comment by AAChartModel** [comment]
>  Can we give different colors to every sector of the polar chart?

I will give you a different colors polar chart demo,So do not worry about this:)
But the annular style  string  around the polar chart is impossible for me on the screenshot!!!!

**Comment by AAChartModel** [comment]
Could you tell me where did you get the screenshot photo?

**Comment by munish26** [comment]
> annular style string around the polar chart is impossible for me

That's fine, I don't want annular style string, straight is fine for me. But can you save them from overlapping the polar outer ring?

![6](https://user-images.githubusercontent.com/38952152/39623138-493516ca-4fb2-11e8-86e4-f368bfd26580.png)

**Comment by munish26** [comment]
> Could you tell me where did you get the screenshot photo?


That's from some other library. Here's the link https://www.anychart.com

**Comment by AAChartModel** [comment]
In my opinion, if you just want to draw single type chart in your project ,you should use AnyChart.js rather than AAChartKit!!!

**Comment by munish26** [comment]
I am finding your library better and easy to integrate, So If you can help me change the colors of sectors that will be fantastic. ALong will those minor fixes of text overlap and out margins.

**Comment by munish26** [comment]
Hey, Any update??

**Comment by AAChartModel** [comment]
> The polar chart is going out of the screen and cutting the titles around the chart.
To resolve this problem
You can configure the AAChartModel instance object as follow 
```swift
            aaChartModel = AAChartModel()
                .chartType(AAChartType.Column)
                .polar(true)
                .dataLabelEnabled(false)
                .categories(["January", "February", "March", "April", "May", "June",
                             "July", "August", "September", "October", "November", "December"])
                .marginLeft(50)//left margin of chart
                .marginRight(30)//right margin of chart
                .series(
                    [
                        AASeriesElement()
                            .name("Tokyo")
                            .data([7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6])
                            .toDic()!,
                        ]
            )
```

**Comment by munish26** [comment]
I am unable to get these properties, marginLeft and marginRight

**Comment by AAChartModel** [comment]
Update the AAInfographic Demo,then you can configure the AAChartModel instance object as follow 
```swift
        aaChartModel = AAChartModel()
                .chartType(AAChartType.Column)
                .polar(true)
                .dataLabelEnabled(false)
                .categories(["January", "February", "March", "April", "May", "June",
                             "July", "August", "September", "October", "November", "December"])
                .marginLeft(50)
                .marginRight(30)
                .series(
                    [
                        ["name":"2018",
                         "data":[7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6],
                         "colorByPoint":true //🌈🌈let chart be colorful🌈🌈
]
                        ]
            )
```

**Comment by AAChartModel** [comment]
> text overlap and out margins.

I donnot fix this yet!!!o(╯□╰)o

**Comment by munish26** [comment]
Can you give mein commit id from which to update

**Comment by AAChartModel** [comment]
The AAInfographics(AAChartKit-Swift) was updated,not the AAChartKit

**Comment by munish26** [comment]
Okay, and can you help me with different colors of each sector?

**Comment by AAChartModel** [comment]
You can not get colorful polar chart yet?

**Comment by munish26** [comment]
I did, thanks, I didn't check the colortype key in the code. It's colorful now.

But Marginleft and right doesn't fix the outer outgoings of labels

**Comment by munish26** [comment]
Hey
Its fixed and it working all fine now. Thanks, mate for your support.

Beers for you are due on me till we meet! ;) 🍻
