### ISSUE TITLE
刷新数据刷不出来

### ISSUE THREAD

**Issue by nobut** [AAChartModel/AAChartKit#257]
你好：请问刷新数据刷不出来咋回事儿啊？都设置对了感觉
AAChartView.m [Line 266] 
☠️☠️💀☠️☠️WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=0, WKJavaScriptExceptionMessage=TypeError: undefined is not a function, WKJavaScriptExceptionColumnNumber=0, NSLocalizedDescription=A JavaScript exception occurred}

**Comment by nobut** [comment]
![](https://ws1.sinaimg.cn/large/006tKfTcly1fqz7274xn6j30l00f2n07.jpg)为啥更改的值变成0x0了呢

**Comment by AAChartModel** [comment]
描述一下你是怎么使用的,代码贴上来看看

**Comment by nobut** [comment]
[self addaachartView];
    [self addaachartModel];
    
    UILabel *labelV = [[UILabel alloc] initWithFrame:CGRectMake(20, 75, self.view.size.width - 40, 75)];
//    labelV.backgroundColor = [UIColor orangeColor];
    [labelV setFont:[UIFont systemFontOfSize:12]];
    labelV.text = @"    友情提示！：L/mo（R/mo）代表身体左侧（右侧）部位这一个月的用量。L/yr（R/yr ）代表身体左侧（右侧）部位去年这个月的用量。可以点击四个圆点进行选择比较。";
    labelV.numberOfLines = 0;
    [self.view addSubview:labelV];
    [_aaChartView aa_drawChartWithChartModel:_aaChartModel];
    [_aaChartView aa_refreshChartWithChartModel:_aaChartModel];
    
    NSArray *chartSeriesArr = @[
                                @{@"nameSet":@"L/mo",
                                  @"dataSet":@[@"90.0", @"69.0", @"9.5", @"14.5", @"18.2", @"21.5", @"25.2", @"26.5", @"23.3", @"18.3", @"13.9", @"9.6"]},
                                ];
    
    //刷新数据
    [_aaChartView aa_onlyRefreshTheChartDataWithChartModelSeries:chartSeriesArr];

**Comment by AAChartModel** [comment]
你误解了我的代码,错误地构造了 chartSeriesArr,应该是这样的
```objective-c
                 AAObject(AASeriesElement)
                 .nameSet(@"L/mo")
                 .dataSet(@[@"90.0", @"69.0", @"9.5", @"14.5", @"18.2", @"21.5", @"25.2", @"26.5", @"23.3", @"18.3", @"13.9", @"9.6"]),
```
或者是这样的
```objective-c
    NSArray *chartSeriesArr = @[
                                @{@"name":@"L/mo",
                                  @"data":@[@"90.0", @"69.0", @"9.5", @"14.5", @"18.2", @"21.5", @"25.2", @"26.5", @"23.3", @"18.3", @"13.9", @"9.6"]},
                                ];
```

**Comment by AAChartModel** [comment]
另外
```objective-c
    [_aaChartView aa_drawChartWithChartModel:_aaChartModel];
    [_aaChartView aa_refreshChartWithChartModel:_aaChartModel];
```
这两句中的下面这一句是完全多余的.没有更新 AAChartModel 的内容,没有必要使用`aa_refreshChartWithChartModel `这个函数.注意看我的 README 文档中的介绍

**Comment by nobut** [comment]
按照您上面的写了还是不行。我不刷新数据的时候出现一个下面的警告。刷新数据的时候出现了两个警告
2018-05-04 14:08:19.972328+0800 [5784:1342160] -------> AAChartView.m [Line 266] 
☠️☠️💀☠️☠️WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: loadTheHighChartView, WKJavaScriptExceptionColumnNumber=21, WKJavaScriptExceptionSourceURL=about:blank, NSLocalizedDescription=A JavaScript exception occurred}

2018-05-04 14:08:19.972469+0800 [5784:1342160] -------> AAChartView.m [Line 266] 
☠️☠️💀☠️☠️WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=0, WKJavaScriptExceptionMessage=TypeError: undefined is not a function, WKJavaScriptExceptionColumnNumber=0, NSLocalizedDescription=A JavaScript exception occurred}

**Comment by AAChartModel** [comment]
附言:如果你没有频繁刷新图表数据的需求,也没有必要调用`aa_onlyRefreshTheChartDataWithChartModelSeries `这个刷新数据的函数.而是应该
1.直接一次性配置完成AAChartModel,
2.然后调用绘制图表的函数`aa_drawChartWithChartModel `即可
就像下面这样

```objective-c
    self.aaChartModel= AAObject(AAChartModel)
    .chartTypeSet(chartType)//图表类型
    .titleSet(@"")//图表主标题
    .subtitleSet(@"")//图表副标题
    .yAxisLineWidthSet(@0)//Y轴轴线线宽为0即是隐藏Y轴轴线
    .colorsThemeSet(@[@"#fe117c",@"#ffc069",@"#06caf4",@"#7dffc0"])//设置主体颜色数组
    .yAxisTitleSet(@"")//设置 Y 轴标题
    .tooltipValueSuffixSet(@"℃")//设置浮动提示框单位后缀
    .backgroundColorSet(@"#4b2b7f")
    .yAxisGridLineWidthSet(@0)//y轴横向分割线宽度为0(即是隐藏分割线)
    .seriesSet(@[
                                AAObject(AASeriesElement)
                                .nameSet(@"L/mo")
                                .dataSet(@[@"90.0", @"69.0", @"9.5", @"14.5", @"18.2", @"21.5", @"25.2", @"26.5", @"23.3", @"18.3", @"13.9", @"9.6"]),
                                ]
               );
    
    [self.aaChartView aa_drawChartWithChartModel:_aaChartModel];
```

感觉你上面的古怪用法,完全有违我设计这些接口的初衷啊

**Comment by AAChartModel** [comment]
你先不要调用刷新的接口,先复制我上面的这个代码,把你要的图表画出来

**Comment by nobut** [comment]
[https://ws3.sinaimg.cn/large/006tKfTcly1fqza4iq1a2j30qu0igjwj.jpg](url)

**Comment by AAChartModel** [comment]
链接地址有误 404

**Comment by nobut** [comment]
https://ws3.sinaimg.cn/large/006tKfTcly1fqza4iq1a2j30qu0igjwj.jpg

**Comment by AAChartModel** [comment]
嗯,这次的 chartSeriesArray 没有问题

**Comment by nobut** [comment]
我没有频繁刷新的需求。我是想做一个扫条形码，扫完更新一下图表。

**Comment by AAChartModel** [comment]
一步一步来,你先将我的 demo 当中绘制图表的那部分代码,直接复制粘贴到你的现在的项目当中,复现我的图表内容,这个可以做到吗?

**Comment by AAChartModel** [comment]
成功之后,再将我的 demo 代码的数据替换成你的数据

**Comment by nobut** [comment]
我已经在我的工程用你的代码实现了图表的展示，现在是我有新数据怎么更新你的图表呢？

**Comment by AAChartModel** [comment]
图表绘制成功之后,只是更新数据只要像下面👇这样做就可以了
```objective-c
    NSArray *series = @[
                        AAObject(AASeriesElement)
                        .nameSet(@"2019")
                        .dataSet(@[@0.9, @0.6, @3.5, @8.4, @13.5, @17.0, @18.6, @17.9, @14.3, @9.0, @3.9, @1.0]),
                        ];
    
    [self.chartView aa_onlyRefreshTheChartDataWithChartModelSeries:series];
```

**Comment by AAChartModel** [comment]
错了,应该是这样
```objective-c
    NSArray *series = @[
                        @{@"name":@"2019",
                          @"data":@[@0.9, @0.6, @3.5, @8.4, @13.5, @17.0, @18.6, @17.9, @14.3, @9.0, @3.9, @1.0]},
                        ];
    
    [self.chartView aa_onlyRefreshTheChartDataWithChartModelSeries:series];
```

**Comment by nobut** [comment]
好，谢谢你

**Comment by AAChartModel** [comment]
我后来又仔细看了一下,发现我之前的 README 文档的排版确实有些问题.后面的刷新图表的内容, 容易让人误以为也是绘制图表时必须要调用的.所以现在我已经吧 README 文档当中的这部分内容

5.  刷新图形(首次绘制图形完成之后,后续刷新均建议调用此方法)
```objective-c
/*更新 AAChartModel 内容之后,刷新图表*/
[chartView aa_refreshChartWithChartModel:chartModel];
```

6.  仅仅刷新图形的数据(进行数据的动态更新操作时,建议使用此方法)
```objective-c
/*仅仅更新 AAChartModel 对象的 series 属性时,动态刷新图表*/
[chartView aa_onlyRefreshTheChartDataWithChartModel:chartModel];
```

改成了下面👇这样,这下应该不容易引起误会了

🌹🌹🌹 好了,至此,有关于绘制图形的任务,一切皆已经搞定!!! 你将得到你想要的任意图形!!!

### 更新图形内容
如果你需要更新图表内容,你应该阅读以下内容,根据你的实际需要,选择调用适合你的函数

*  仅仅刷新图形的数据(进行数据的动态更新操作时,建议使用此方法)
```objective-c
/*仅仅更新 AAChartModel 对象的 series 属性时,动态刷新图表*/
[_aaChartView aa_onlyRefreshTheChartDataWithChartModelSeries:aaChartModelSeriesArray];
```

*  刷新图形除数据属性 `series` 以外的其他属性(首次绘制图形完成之后,后续刷新图表的属性均建议调用此方法 注意:仅仅刷新图形数据,则建议使用上面的👆`aa_onlyRefreshTheChartDataWithChartModelSeries`方法)
```objective-c
/*更新 AAChartModel 内容之后,刷新图表*/
[_aaChartView aa_refreshChartWithChartModel:aaChartModel];
```

**Comment by nobut** [comment]
https://ws3.sinaimg.cn/large/006tKfTcly1fqzdhf82eaj31kw10gkhe.jpg
    2017默认是7.0现在假如我2017有个数据更新到90.0
    用你的 demo ，在- (void)viewDidLoad 或者在- (void)setUpTheAAChartViewWithChartType:(AAChartType)chartType方法添加如下代码 
NSArray *series = @[
                                                                                                                            @{@"name":@"2017",
                                                                                                                              @"data":@[@90.0, @0.6, @3.5, @8.4, @13.5, @17.0, @18.6, @17.9, @14.3, @9.0, @3.9, @1.0]},
                                                                                                                            ];
    
    [self.aaChartView aa_onlyRefreshTheChartDataWithChartModelSeries:series];
更新还是没有刷新出来。如图2017还是显示没刷新之前的7.0

**Comment by AAChartModel** [comment]
感觉你遇到的问题和这个 https://github.com/AAChartModel/AAChartKit/issues/236 一样,你可以参考一下

**Comment by nobut** [comment]
我就是看完#236 按照他的写的，最后不行才找的您 😂

**Comment by nobut** [comment]
好了，辛苦，辛苦。谢谢您

**Comment by AAChartModel** [comment]
可以了?所以你之前并没有看清楚 #236 的这个问题的关键啊!!!😢

**Comment by nobut** [comment]
嗯，没问题了。怪我没想那么多。😭

**Comment by nongmogege** [comment]
作者大大您好，我想问一下。怎么确保图标绘制完成了？是否有一个图标绘制完成之后的回调函数？

**Comment by AAChartModel** [comment]
@nongmogege AAChartView.h 文件中有一个图表绘制完成的代理方法,你找找看
