### ISSUE TITLE
Y轴数值显示问题

### ISSUE THREAD

**Issue by coderzzi** [AAChartModel/AAChartKit#259]
> 这个库非常棒！但是使用 AAChartTypeArea 的图 遇到如下两个问题。
#### 请问，Y 轴小于 0.000001 的数值，默认的有效小数是多少位？我们需要更多的小数位，应该如何设置？
---
#### Bug 1 ：Y 轴数值，小于 0.000001（ 6 位小数），就失真了，显示成 0 了。
> 举个栗子：（显示成 0 的 Bug 情境）
> ```objc
> AAObject(AAChartModel)
> .chartTypeSet(AAChartTypeArea)
> .categoriesSet(@[@(0.0000001),@(0.0000002,@(0.0000003),@(0.0000004),@(0.0000005))])  // 7位小数
> ```
##### 点是正常的，但是 Y 轴数值，却都成了 0 ，无法呈现真实数值。如下图：
![wechatimg6](https://user-images.githubusercontent.com/39031388/39676183-a74ead6a-5198-11e8-8fd2-39134eec4616.jpeg)

---

#### Bug 2 ：Y 轴数值，小于 0.000001（ 6 位小数），超过 10 位小数，会被进位；而且实际 A < B ，进位后会出现 A > B 的情况。
> 举个栗子：（显示，被进位的 Bug 情境）
> ```objc
> AAObject(AAChartModel)
> .chartTypeSet(AAChartTypeArea)
> > .categoriesSet(@[@(0.0000004444),@(2.00000066666),@(3.00000088888),@(4.00000094444),@(5.00000099999)])  // 第一个数，被进位了成了 0.0000005
> ```
##### 仔细观察一下，真实数值 *前者<后者*，但是实际显示却是 *前者>后者*。如下图：

![wechatimg10](https://user-images.githubusercontent.com/39031388/39676338-7bfcc716-519b-11e8-9d10-cb850716a75f.jpeg)

![wechatimg11](https://user-images.githubusercontent.com/39031388/39676342-a025af04-519b-11e8-95f0-897d9713d236.jpeg)

**Comment by AAChartModel** [comment]
这是个问题,我需要花点时间查查文档,有可能无解,你要做好预防😳

**Comment by coderzzi** [comment]
我本来想试着改底层的，但底层加壳了😭

**Comment by AAChartModel** [comment]
确实,简直毫无希望😝,也不算是加壳了吧,只是为了节省流量和提升加载速度, js 源代码被压缩了,结果造成了事实上的代码被封印了的结果😊

**Comment by AAChartModel** [comment]
你看我之前的源代码里设置 Y轴显示精度的内容
```objective-c
    aaYAxis.labelsSet(AAObject(AALabels)
                      .enabledSet(aaChartModel.yAxisLabelsEnabled)//设置 y 轴是否显示数字
                      .styleSet(AAObject(AAStyle)
                                .colorSet(aaChartModel.yAxisLabelsFontColor)//yAxis Label font color
                                .fontSizeSet(AAFontSizeFormat(aaChartModel.yAxisLabelsFontSize))//yAxis Label font size
                                .fontWeightSet(aaChartModel.yAxisLabelsFontWeight)//yAxis Label font weight
                                )
                      .formatSet(@"{value:.,0f}")//让y轴的值完整显示 而不是100000显示为100k
                      )
```

最好的办法是直接去官网查看 API 文档 https://api.hcharts.cn/highcharts ,查找 Y轴的` format `这个属性

**Comment by coderzzi** [comment]
好的，谢谢😊我试试看

**Comment by coderzzi** [comment]
@AAChartModel  大神，帮帮忙，这个 Issue 再看一下，我真的解决不了这个问题了。😭

**Comment by AAChartModel** [comment]
现已添加了设置图表数据精度的示例代码,如下配置图表内容即可:

1.配置 AAOptions 实例对象
```objective-c
    AAChartModel *aaChartModel = AAObject(AAChartModel)
    .chartTypeSet(AAChartTypeArea)
    .titleSet(@"Adjust data accuracy")
    .yAxisTitleSet(@"")
    .dataLabelEnabledSet(true)
    .symbolSet(AAChartSymbolTypeCircle)
    .markerRadiusSet(@6)//设置折线连接点宽度为0,即是隐藏连接点
    .yAxisGridLineWidthSet(@0.5)
    .symbolStyleSet(AAChartSymbolStyleTypeInnerBlank)
    .seriesSet(@[AAObject(AASeriesElement)
                 .nameSet(@"2017")
                 .dataSet(@[@(0.0000001),@(0.0000002),@(0.0000003),@(0.0000004),@(0.0000005)])
                 .lineWidthSet(@5)
                 ]
               );
//  数值格式化字符串是采用了 C 语言浮点型格式化的子集，格式化字符是在大括号内，变量之后，用冒号（:）分隔的内容。默认情况下点号（.）表示小数点，空格（ ）代表千分符，当然这两个符号可以在 语言文字 选项集里中来设定。具体参见 https://www.hcharts.cn/docs/basic-labels-string-formatting#h2-1
    AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
    aaOptions.tooltip.valueDecimals = @9;//设置tooltip取值精确到小数点后9位
    aaOptions.plotOptions.area.dataLabels.format = @"{point.y:.9f}";//设置dataLabels取值精确到小数点后9位
```

2.绘制图表
```objective-c
    [aaChartView aa_drawChartWithOptions: aaOptions];
```

**Comment by coderzzi** [comment]
优秀！谢谢大神！

**Comment by AAChartModel** [comment]
> https://jshare.com.cn/highcharts/SUKyx7

从上面这个链接中的示例中可以看到, Highcharts 貌似对小数的精度最大只是支持到小数点后面9位,你如果设置的最大精度超过了9(比如10或者11),那么精度大小又重新归零了.

如果你的项目对小数的精度有更加精确的要求,那么 AAChartKit 很可能不是你的最佳选择,你应该寻找其他的图表库来解决这个问题.

**Comment by coderzzi** [comment]
我们项目最大需要8位小数，9位小数足够使用了，谢谢谢谢~

**Comment by AAChartModel** [comment]
**附言:**
另外, AAChartKit 应该通过 AASeriesElement 的 data 属性来进行数据的赋值,你给的示例代码是这样的> 举个栗子：（显示成 0 的 Bug 情境）
> ```objc
> AAObject(AAChartModel)
> .chartTypeSet(AAChartTypeArea)
> .categoriesSet(@[@(0.0000001),@(0.0000002,@(0.0000003),@(0.0000004),@(0.0000005))])  // 7位小数
> ```

通过 categories 赋值是什么操作呢?

**Comment by coderzzi** [comment]
非常抱歉，我的栗子里，由于是临时栗子，一时粗心代码写错了，修改过来了。（我项目中接入的写法是正常的）

**Comment by coderzzi** [comment]
对了，大神，y轴坐标刻度小于0.000001就显示0了，比如：y轴坐标刻度0.0000009，实际却显示为0，这个问题要怎么解决？
