### ISSUE TITLE
请问点击图表怎么能拿到回调？

### ISSUE THREAD

**Issue by smileWorld333** [AAChartModel/AAChartKit#26]
如题

**Comment by gjlaiziji** [comment]
no people answer?

**Comment by YouMotherFucker** [comment]
有时候伸手党有时候真的让人很无语,你说你光伸手也就算了,好歹你总要能够描述清楚你的需求具体是什么吧,能够完整的表达自己到底想要什么这是一个合格的开发者最基本的素质吧!你说你要拿事件回调,你指的是什么事件呢?是点击 legend 图例事件?是图表数据的刷新刷新事件?是标志线被扫过的手势事件?你什么也没说,就一句干瘪的

>请问点击图表怎么能拿到回调?

你能指望原作者能有什么样的正面反馈?
说了这么多,我想说的是: `AAChartKit`作者到底什么时候能够为图表添加事件回调啊?上述所说的三种哪怕一样也行啊!
急!急!急!急!急!急!在线等!

**Comment by angeldolphin** [comment]
都说了是点击.....即时刷新是点击么？标志线被扫过是点击么？其实作者以前的版本可以拿到回调。

**Comment by angeldolphin** [comment]
都说了是点击.....即时刷新是点击么？标志线被扫过是点击么？其实作者以前的版本可以拿到回调。

**Comment by AAChartModel** [comment]
现已有GitHub 同好在项目的 Demo 中使用 UIGesture 实现了图表的点击事件回调,可参考.

**Comment by tipshot** [comment]
@AAChartModel 能否给个链接？或者具体名字也可以。或者其他方便查找的信息也行。膜拜，，，

**Comment by AAChartModel** [comment]
就在demo的右上角,touch event点击进入查看即可

**Comment by AAChartModel** [comment]
点击事件问题已解决,参见 #810
