### ISSUE TITLE
为什么不加入cocoapods引入功能呢？

### ISSUE THREAD

**Issue by simon9211** [AAChartModel/AAChartKit#262]

**Comment by AAChartModel** [comment]
因为还未解决 pod 导入后,无法正确加载本地 HTML 文件的问题.

**Comment by simon9211** [comment]
明白

**Comment by AAChartModel** [comment]
兄弟可有解决此问题的秘技相授?

**Comment by simon9211** [comment]
好像https://shop.highsoft.com也有iOS的sdk，收费的

**Comment by simon9211** [comment]
能把html文件打包到bundle里面，然后一起pod下来

**Comment by AAChartModel** [comment]
highcharts 商业使用本来就是需要收费的,我感觉 AAChartKit 早晚要经历从删库到跑路的命运🤣🤣🤣

**Comment by coderzzi** [comment]
@AAChartModel 大神，帮忙解决一下 issue #259

**Comment by iKimee** [comment]
NSURL *url = [[NSBundle mainBundle] URLForResource:@"index.html" withExtension:nil];;
    [self.webView loadRequest:[NSURLRequest requestWithURL:url]];
本地HTML加载，这个方法是可以的，项目中有使用

**Comment by wooodypan** [comment]
@AAChartModel 我试了下可以的啊
贴下我的podspec配置：
``` ruby
    aachart.ios.deployment_target = '8.0'
    aachart.resource = 'PWiOSTool/AAChartKitLib/AAJSFiles.bundle'
    aachart.source_files = 'PWiOSTool/AAChartKitLib/**/*.h'
```
亲测可用（bundle文件能拉下来）
```
  pod 'PWiOSTool/AAChartKitLib', :git => 'https://git.coding.net/panway/PWiOSTool.git'
```

**Comment by AAChartModel** [comment]
现已支持`cocoapods`导入,详细信息参见README文档
