### ISSUE TITLE
chart 和 tableview 使用 性能怎么样

### ISSUE THREAD

**Issue by Rcrosp** [AAChartModel/AAChartKit#264]

**Comment by AAChartModel** [comment]
Demo 中有 AAChartView 添加在 tableView 的单元格上的示例,效果可能并不怎么样!

如果你的需求是 tableView 上加载大量的图表📈,更好的选择应该是使用iOS原生语言绘制的图表库,比如 Charts(Swift 语言)之类的,不过这些原生语言的图表库的坑,可是一点也不会比 AAChartKit 少🤣, 且行且珍惜!!!🌈🌈🌈

**Comment by AAChartModel** [comment]
目前 AAChartKit 的坑主要也就是性能不及原生,其它的基本都没有什么太大毛病,我之前工作中的图表分析需求基本都是完全满足了.
