### ISSUE TITLE
横坐标做有点的数值都为0，如何设置不显示点，只显示一条直线？

### ISSUE THREAD

**Issue by coderzzi** [AAChartModel/AAChartKit#265]
AAChartTypeArea 的 图。当横坐标所有点的数值都为0时，如何设置可以不显示点，只显示一条直线？如下图：
￼
![wechatimg127](https://user-images.githubusercontent.com/39031388/39803287-2de6c7d4-53a3-11e8-9f46-f4b1cc259f8c.jpeg)

**Comment by AAChartModel** [comment]
那需要你自己去判断,当数组中的数值全部为0时,设置 markerRadius(折线连接点半径) 的值为0

**Comment by coderzzi** [comment]
谢谢，很好用👍
