### ISSUE TITLE
AAChartTypePie 的图，请问圆点大小怎么设置？

### ISSUE THREAD

**Issue by coderzzi** [AAChartModel/AAChartKit#266]
AAChartTypePie 的图，请问那xie些圆点的大小怎么设置？我想让它小一点，如下图：

![wechatimg128](https://user-images.githubusercontent.com/39031388/39825157-b8b72c24-53e3-11e8-948f-77608ab48539.jpeg)

**Comment by AAChartModel** [comment]
这个暂不支持.
