### ISSUE TITLE
关于曲线图设置了categories 后，会出现一条浅蓝色的区域

### ISSUE THREAD

**Issue by bk201brian** [AAChartModel/AAChartKit#268]
你好，我的曲线图设置了categories 后，选中某个数据会出现一条浅蓝色的区域，请问怎样修改这个区域的宽度和颜色？

**Comment by AAChartModel** [comment]
默认出现的其实是图形的准星线,修改 X 轴的准星线(crosshair)线宽和颜色即可

**Comment by iOSleep** [comment]
@AAChartModel 根据提示修改了
.xAxisCrosshairWidthSet(@0) 没有效果
需要给一个不为0的值，然后修改 xAxisCrosshairColorSet
