### ISSUE TITLE
不连续的数据，如何设置跳过中间的间距？

### ISSUE THREAD

**Issue by liubang0909** [AAChartModel/AAChartKit#269]
刚看了下源码。。竟然是先转json用webView加载本地js的形式来实现的？？这样的话，根据自己需求来改功能的话，是不是要修改js？这个对于一般的不太精通js的iOSer来说是不是有点不友好？wkWebView的性能虽然相对的提高了，但还是个重量级的控件...希望能直接使用原生代码来实现。。

**Comment by AAChartModel** [comment]
> 希望能直接使用原生代码来实现

你真的明白你在说什么吗?!!!!

**Comment by liubang0909** [comment]
。。没必要生气啊。。 我的意思是绘图使用iOS的代码实现  而不是类似hchart的语法

**Comment by AAChartModel** [comment]
不是生气的问题,是你确实不知道你所说的话的轻重.
FMDB是封装的 sqlite, 便于 iOS 开发者更容易操作 c语言数据库,你的话就好等于是在说希望 FMDB 作者能够完全用 OC 来再实现一遍 sqlite 一样,当然不是没有可能,但是你明白这中间的工作量吗?

**Comment by liubang0909** [comment]
。。可能是我经验还比较少，真的，大家交流下而已，目前见到的图表库，都是使用iOS原生的绘图来实现的。。性能上也会好很多，图表加载的时候会慢上很多，可能是加载文件的原因,我当然知道您的努力付出，和hchart做了一层对接，感谢您的分享。。有冒犯的地方还希望见谅。。

**Comment by AAChartModel** [comment]
> 图表加载的时候会慢上很多

这个你是因为在模拟器上的吧!真机上没有什么明显的可感知的延迟迹象,参见这里 https://github.com/AAChartModel/AAChartKit/issues/260
