### ISSUE TITLE
X轴左右滑动的时候怎么使Y轴顶在左边?

### ISSUE THREAD

**Issue by DogTwoChen** [AAChartModel/AAChartKit#273]
我去看了HighCharts是能实现这种效果的,希望得到帮助

**Comment by AAChartModel** [comment]
能给个链接吗?

**Comment by DogTwoChen** [comment]
https://code.hcharts.cn/demos/hhhhDv左边Y轴固定

**Comment by AAChartModel** [comment]
> X轴左右滑动的时候怎么使Y轴顶在左边

你给的这个链接不能算是这个效果吧,这个是数据动态滚动刷新效果啊

**Comment by AAChartModel** [comment]
你看这个官网的介绍 https://www.hcharts.cn/docs/basic-zoom ,我确实是没找到你要的这种效果

**Comment by DogTwoChen** [comment]
![Uploading 屏幕快照 2018-05-14 下午4.58.13.png…]()
我的需求就是这个左边的y轴不随webview的scrollview移动

**Comment by AAChartModel** [comment]
参考这个问题,https://github.com/AAChartModel/AAChartKit-Swift/issues/58 你可能需要highcharts官方的封装框架.
其实这个滚动刷新的特性还在我的待办清单列表里,但是近期内我不太有时间去添加这个特性

**Comment by DogTwoChen** [comment]
好哒感谢

**Comment by AAChartModel** [comment]
官方框架比较重,你斟酌选择一下
