### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ulises01** [AAChartModel/AAChartKit#274]
![captura de pantalla 2018-05-14 a la s 09 21 20](https://user-images.githubusercontent.com/39272359/40006965-e2edd07e-5758-11e8-8539-36d4716b72b5.png)

**Comment by AAChartModel** [comment]
Do you import `AAGlobalMacro.h` as I said in README?

### The required 'pre' work
1. Drag the `AAChartKitLib` folder into your project.

2. Add the following to your `.pch` file.
```objective-c
#import "AAGlobalMacro.h"
```
