### ISSUE TITLE
AAChartView是否有内存泄漏

### ISSUE THREAD

**Issue by flyOfYW** [AAChartModel/AAChartKit#277]
AAChartView的dealloc方法不走，是否有内存泄漏，但是我用instruments检测不到内存泄漏，请问是否有内存泄漏

**Comment by lovephoenix** [comment]
@AAChartModel 麻烦回复一下这个问题呗，发现确实有内存增长

**Comment by AAChartModel** [comment]
问题已在此次提交 https://github.com/AAChartModel/AAChartKit/commit/dafb7070ab8e9e06ca4f98ec54f01b03de185e48 中解决
