### ISSUE TITLE
Grouped Bar Chart with customizable x axis

### ISSUE THREAD

**Issue by Ruchita-Bora** [AAChartModel/AAChartKit#278]
I am trying to create bar chart as shown in image below. Is this possible with this library? I need a grouped bar chart with customizable xaxis (show images instead of labels).
![screen shot 2018-05-17 at 11 46 12 am](https://user-images.githubusercontent.com/20037382/40159890-e6cb01c2-59c8-11e8-8a0a-e68eea891458.png)

**Comment by AAChartModel** [comment]
AAChartKit do not support it
