### ISSUE TITLE
为什么我会出现这种情况呢

### ISSUE THREAD

**Issue by ChenZeBin** [AAChartModel/AAChartKit#285]
![](http://lc-HSNl7zbI.cn-n1.lcfile.com/nx0EiHGQ8zS9aWGY2O8vk1MNclS12tNFKOJB86na.jpg)

**Comment by AAChartModel** [comment]
是你在 demo 运行的时候旋转了 iPhone 模拟器吧?

**Comment by ChenZeBin** [comment]
没有，真机跑的时候也是酱紫。

**Comment by AAChartModel** [comment]
这个就不知道了,没遇到过这种情况,也没办法复现问题
