### ISSUE TITLE
x 轴问题

### ISSUE THREAD

**Issue by iOSleep** [AAChartModel/AAChartKit#286]
![wx20180521-113906](https://user-images.githubusercontent.com/26478957/40289546-999a2ef2-5ceb-11e8-8b1a-c7e1b28ebeda.png)

设置了 categories 后，两边的这个应该如何隐藏，或者所有的都不要？

**Comment by AAChartModel** [comment]
```objective-c
AAPropSetFuncImplementation(AAXAxis, NSString *, tickColor);//x轴轴线下方刻度线颜色
```

设置AAXAxis模型对象的tickColor颜色和图表的背景色相同,即相当于隐藏了 X轴的刻度线(tick)
