### ISSUE TITLE
这个环形的缝隙怎么去掉？

### ISSUE THREAD

**Issue by coderzzi** [AAChartModel/AAChartKit#290]
这个环形的缝隙怎么去掉？
![image](https://user-images.githubusercontent.com/39031388/40316606-697bd192-5d51-11e8-8d7d-66df34b98a98.png)

**Comment by coderzzi** [comment]
@AAChartModel 大神，这个环形的缝隙怎么去掉？

**Comment by AAChartModel** [comment]
现已为 AASeriesElement 模型添加了 borderWidth(描边的宽度) 属性,更新一下 AAChartKit, 然后像这样设置 AAChartModel 即可
```objective-c
        AAChartModel *aaChartModel= AAObject(AAChartModel)
        .chartTypeSet(AAChartTypePie)
        .colorsThemeSet(@[@"#0c9674",@"#7dffc0",@"#d11b5f",@"#facd32",@"#ffffa0",@"#EA007B"])
        .titleSet(@"")
        .subtitleSet(@"")
        .dataLabelEnabledSet(true)//是否直接显示扇形图数据
        .yAxisTitleSet(@"摄氏度")
        .seriesSet(
                   @[
                     AAObject(AASeriesElement)
                     .nameSet(@"语言热度值")
                     .innerSizeSet(@"20%")//内部圆环半径大小占比
                     .sizeSet(@200)//尺寸大小
                     .borderWidthSet(@0)//💗💗💗描边的宽度,值为0时,也就是没有描边💗💗💗
                     .allowPointSelectSet(false)//是否允许在点击数据点标记(扇形图点击选中的块发生位移)
                     .dataSet(
                              @[
                                @[@"Firefox",   @3336.2],
                                @[@"IE",        @26.8],
                                @[@"Safari",    @88.5],
                                @[@"Opera",     @46.0],
                                @[@"Others",    @223]
                                ]
                              ),
                     ]
                   )
        ;
```

**Comment by jackieyipMaolian** [comment]
.borderWidthSet(@0)

**Comment by AAChartModel** [comment]
在 iPhoneX 以下的设备上没有问题?只在iPhoneX上出现?

**Comment by jackieyipMaolian** [comment]
其他设备还没试，X上看了还存在1像素宽度的效果，然后新库的 .colorsThemeSet() 这个方法设置颜色也失效了（这是个数组，但全都使用了第一个数据的颜色），这边，代码就回退了

**Comment by jackieyipMaolian** [comment]
大神，我想获取渲染后扇形图的圆心位置，应该如何获取

**Comment by AAChartModel** [comment]
> 新库的 .colorsThemeSet() 这个方法设置颜色

这个问题参加 #428

**Comment by AAChartModel** [comment]
> 大神，我想获取渲染后扇形图的圆心位置，应该如何获取？

这个 AAChartKit 恐怕无能为力,需要你自己去想办法暴力计算了

**Comment by jackieyipMaolian** [comment]
> > 大神，我想获取渲染后扇形图的圆心位置，应该如何获取？
> 
> 这个 AAChartKit 恐怕无能为力,需要你自己去想办法暴力计算了

哦，无法获取渲染后图形的位置，对于想在界面上叠加别的自定义效果总是会出现适配问题...

**Comment by AAChartModel** [comment]
你现在的扇形图的半径是不是不固定的(因为为了一定的灵活性, Highcharts 的扇形图半径默认是不固定的)?

为了使的扇形图的圆心固定,你可以设置扇形图的直径为某一个具体的值,使得扇形图的圆心固定,这样也好计算一些

**Comment by AAChartModel** [comment]
另外如果你对扇形图的自定义效果比较苛刻,可能 AAChartKit 就应该不是你的第一选择,你可以尝试一下其他的开源iOS图表库如: Swift 语言编写的 Charts 之类的,或者是某一个专门的只用于绘制扇形图图表的库,而不是 AAChartKit 这种大而全的库

**Comment by jackieyipMaolian** [comment]
恩恩，我现在使用了.sizeSet()，设定了固定的尺寸。但是图形会根据数据点行数的多少，导致圆心上移和下移。

比如，以一行数据点为基准。当数据点两行以上时，扇形图就会上移。而且这个数据点的行数也无法获取，无法确定渲染后的数据点行数是多少，如果数据点行数能获取的话，就容易计算了

**Comment by jackieyipMaolian** [comment]
> 你现在的扇形图的半径是不是不固定的(因为为了一定的灵活性, Highcharts 的扇形图半径默认是不固定的)?
> 
> 为了使的扇形图的圆心固定,你可以设置扇形图的直径为某一个具体的值,使得扇形图的圆心固定,这样也好计算一些

恩恩，我现在使用了.sizeSet()，设定了固定的尺寸。但是图形会根据数据点行数的多少，导致圆心上移和下移。

比如，以一行数据点为基准。当数据点两行以上时，扇形图就会上移。而且这个数据点的行数也无法获取，无法确定渲染后的数据点行数是多少，如果数据点行数能获取的话，就容易计算了

**Comment by jackieyipMaolian** [comment]
@AAChartModel 大神，我找到办法暴力计算了，就差不知道下方数据点的的默认字体是什么，字号是多少？

**Comment by AAChartModel** [comment]
嗯,这个你别急,我回去看看官方文档.着急的话,你也可以自己去 Highcharts 官网看看文档

**Comment by AAChartModel** [comment]
https://api.hcharts.cn/highcharts  Highcharts官方文档地址

**Comment by jackieyipMaolian** [comment]
> https://api.hcharts.cn/highcharts Highcharts官方文档地址

谢谢大神，我刚刚在这官方的扇形图样例H5里找到了字体（font-family:"Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, sans-serif）和字号（12，Blod）

**Comment by btxXiaoXiao** [comment]
大神。这个扇形点击之后上面的颜色透明怎么取消呀

**Comment by AAChartModel** [comment]
@btxXiaoXiao 参见 https://github.com/AAChartModel/AAChartKit/issues/979
