### ISSUE TITLE
希望能够单独修改线条颜色和坐标点图片，能单独修改填充区域的颜色

### ISSUE THREAD

**Issue by liaoruixiang** [AAChartModel/AAChartKit#293]
<img width="324" alt="qq20180522-200508 2x" src="https://user-images.githubusercontent.com/19679927/40361357-a682688a-5dfb-11e8-9145-c8ddd407dd2b.png">
感觉这个自定义需求还是蛮多的。

**Comment by AAChartModel** [comment]
这个不是已经支持了吗？！！！AASeriesElement支持单独设置线条颜色和区域填充颜色

**Comment by liaoruixiang** [comment]
谢谢提醒，我在AAchartModel里面找了半天没找到，抱歉。
