### ISSUE TITLE
选中状态

### ISSUE THREAD

**Issue by BruceWee01** [AAChartModel/AAChartKit#297]
你好，AAChartModel没有提供选中时是否需要高亮显示的属性吗，现在饼图选中默认是有选择边框的，还有就是饼图当数据变化时怎么不让饼图的大小变化呢？目前demo扇形图如果去掉某个元素（比如IE)或者增加扇形图大小好像是缩放的

**Comment by BruceWee01** [comment]
还有就是饼图当数据变化时怎么不让饼图的大小变化呢？目前demo扇形图如果去掉某个元素（比如IE)或者增加扇形图大小好像是缩放的

**Comment by AAChartModel** [comment]
这个周末会加上功能和示例.

**Comment by BruceWee01** [comment]
好的，谢谢，还有浮动提示框的内容.nameSet(@"语言热度值")这样设置以后每一个悬浮提示框都一样的，这里能不能改成数组赋值然后每一个提示框显示都不一样呢？
