### ISSUE TITLE
如何实现类似空白的数据效果

### ISSUE THREAD

**Issue by iOSleep** [AAChartModel/AAChartKit#298]
![image](https://user-images.githubusercontent.com/26478957/40472849-2b145320-5f6d-11e8-85d3-5ff516c87f83.png)

![image](https://user-images.githubusercontent.com/26478957/40473878-03d4609a-5f70-11e8-8e9a-44816752de60.png)

使用 stacking 的方式进行图1的效果编写，但是不知道怎么让 dataLable 的展示位置在后一个的后面

**Comment by AAChartModel** [comment]
现在 AAChartKit 还没有实现自由设置 dataLabels 的功能,你可以查一查 highcharts 的官方文档,看有没有什么解决方案 https://api.hcharts.cn/highcharts

**Comment by iOSleep** [comment]
我找到了一个 stackLable 的东西，改一下可以实现功能。

**Comment by AAChartModel** [comment]
可以方便贴一下实现代码么?这样也方便后面的有需要的使用者!
