### ISSUE TITLE
显示样式的一些控制

### ISSUE THREAD

**Issue by BruceWee01** [AAChartModel/AAChartKit#299]
你好，AAChartModel没有提供选中时是否需要高亮显示的属性吗，现在饼图选中默认是有选择边框的，还有就是饼图当数据变化时怎么不让饼图的大小变化呢？目前demo扇形图如果去掉某个元素（比如IE)或者增加扇形图大小好像是缩放的

**Comment by AAChartModel** [comment]
重复问题,参见 #303
