### ISSUE TITLE
如果直接拖拽,到新的project里面会全是parse issue

### ISSUE THREAD

**Issue by wwu94** [AAChartModel/AAChartKit#3]

**Comment by wwu94** [comment]
直接拖进来的:
<img width="218" alt="screen shot 2017-04-11 at 12 24 31 am" src="https://cloud.githubusercontent.com/assets/26948166/24892819/6a35a0f2-1e4d-11e7-98f2-9258a29012d7.png">

但是build一下就全是parse issue: 
<img width="339" alt="screen shot 2017-04-11 at 12 24 21 am" src="https://cloud.githubusercontent.com/assets/26948166/24892808/4d50905a-1e4d-11e7-8378-43695a5a9d31.png">

**Comment by AAChartModel** [comment]
兄弟,注意看说明文档,文档中有下面这一句

**2.在你的项目的 .pch 全局宏定义文件中添加
#import "AAGlobalMacro.h"**

**Comment by wwu94** [comment]
看到了
有加这个

**Comment by AAChartModel** [comment]
这就没道理了,其他人用都是正常的呀,不然你建一个仓库,把链接发给我,让我看一下问题出在哪里了吧

**Comment by wwu94** [comment]
没事我重新启动了一下电脑不知道为什么就可以了...
大概是玄学

**Comment by AAChartModel** [comment]
这个可以有,祝您玩的愉快!不过也有可能是 XCode 的bug,毕竟XCode也是人写的软件,哈哈😝
