### ISSUE TITLE
将AAChartKit 3.0的AAChartKitLib拖入工程即报错误？

### ISSUE THREAD

**Issue by Kingsleeeey** [AAChartModel/AAChartKit#300]
将AAChartKit 3.0的AAChartKitLib拖入工程即报警告和错误，无法运行，去除AAChartKitLib文件夹错误解除即可运行，请大神看看是何种原因导致。附上截图，错误信息。
![1527219814394](https://user-images.githubusercontent.com/34328533/40525131-ef2b2f7e-6010-11e8-9f3c-763f81169a5d.jpg)

![1527219781961](https://user-images.githubusercontent.com/34328533/40525126-e3cb22ec-6010-11e8-8766-8f137778e023.jpg)

￼

**Comment by AAChartModel** [comment]
你们这些从来不看 README 的让我说什么好,参见 #288

**Comment by Kingsleeeey** [comment]
在全局的.pch中是导入了#import "AAGlobalMacro.h"报错才提出的，还需要其它配置吗？

**Comment by AAChartModel** [comment]
那估计是你的. pch 文件配置的有些问题,之前有使用者就是这种情况.

**Comment by Kingsleeeey** [comment]
哦，谢谢你的解答，我自行查看一下。

**Comment by sundusk** [comment]
我也遇到这种问题了  你解决了吗

**Comment by Kingsleeeey** [comment]
查看你的.pch文件中是否引入了#ifdef __OBJC__ #endif这个宏定义。如果有，请将#import "AAGlobalMacro.h"置于宏定义之外引入，该开源项目中涉及到runtime机制，而非仅针对Objective-C语言。希望能够帮到你。

在 2018-06-22 08:56:40，"sundusk" <notifications@github.com> 写道：


我也遇到这种问题了 你解决了吗
