### ISSUE TITLE
雷达图坐标问题

### ISSUE THREAD

**Issue by jokerping** [AAChartModel/AAChartKit#301]
雷达图sh设置数据后就会自动在外围显示一圈字，如下图
![image](https://user-images.githubusercontent.com/11515705/40540517-04b272e6-604b-11e8-80ac-b128207fca15.png)

设置categoriesSet这个属性自定义文字的时候图就会乱掉，求解

**Comment by jokerping** [comment]
![image](https://user-images.githubusercontent.com/11515705/40540885-4a64c914-604c-11e8-897d-acda4916f36d.png)
这是乱掉的样子

**Comment by jokerping** [comment]
以及如何设置雷达图间隔，就是上图只有两圈，如何设置更多或者更少的圈

**Comment by FLGiOS** [comment]
aaOptions.xAxis.tickmarkPlacement = @"on"; 添加这句代码 可以解决坐标错乱问题
aaOptions.yAxis.tickPositions 这个方法可以添加更多的间隔线

**Comment by King-whb** [comment]
间隔如果设置@[@(20), @(40), @(60),@(80),@(100)]，最后的100不显示，另外标准的刻度会错乱，同求解决办法

**Comment by myDonghao** [comment]
研究了一上午highcharts，终于找到解决方案了。
因为本库是映射OC转成js的。所以理论上只要 highcharts 支持的属性，都可以手动添加上去
首先 在 AASeriesElement 中添加一个属性pointPlacement，
.h中添加
AAPropStatementAndPropSetFuncStatement(copy,   AASeriesElement, NSString *, pointPlacement)

.m中添加
AAPropSetFuncImplementation(AASeriesElement, NSString *, pointPlacement)

添加数据的时候 加一条
AASeriesElement.new
                 .dataSet(@[@37.0, @46.9, @19.5, @64.5, @80.0])
                 **.pointPlacementSet(@"on")**

---------
参考链接
实验的链接
https://jshare.com.cn/demos/hhhhig
js代码
var chart = Highcharts.chart('container', {
	chart: {
		polar: true,
		type: 'line'
	},
	title: {
		text: 'Budget vs spending',
	},
	xAxis: {
		categories: ['Sales', 'Marketing', 'Development', 'Customer Support',
					 'Information Technology', 'Administration'],
		tickmarkPlacement: 'on',
		lineWidth: 0
	},
	yAxis: {
		gridLineInterpolation: 'polygon',
		lineWidth: 0,
		min: 0,
		tickPositions:[0,20,40,60,80,100]
	},
	series: [ {
		name: 'Actual Spending',
		data: [50, 39, 42, 31, 26],
		// pointPlacement: 'on'
	}]
});

**Comment by King-whb** [comment]
那个数据老错乱，我去试试

**Comment by Crayonnerry** [comment]
朋友你这个x轴的坐标是怎么显示的？为什么我如果显示x轴坐标 就会在外部显示一个圆，我不想显示圆 只想显示坐标。求解

**Comment by myDonghao** [comment]
> 朋友你这个x轴的坐标是怎么显示的？为什么我如果显示x轴坐标 就会在外部显示一个圆，我不想显示圆 只想显示坐标。求解

坐标轴线宽吧。  lineWidth 设置成 0 ；

**Comment by seanLee** [comment]
@myDonghao  我也是找到这个属性了,然后过来搜索了一波,谢谢兄弟😂

**Comment by AAChartModel** [comment]
属性`pointPlacement `已添加至最新的 **AAChartKit** 的 `AASeriesElement` 文件中.
