### ISSUE TITLE
导入到项目中报错了

### ISSUE THREAD

**Issue by IGujie** [AAChartModel/AAChartKit#306]
☠️☠️💀☠️☠️WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______Error Domain=WKErrorDomain Code=4 "发生 JavaScript 异常" UserInfo={WKJavaScriptExceptionLineNumber=10, WKJavaScriptExceptionMessage=Error: Highcharts error #17: www.highcharts.com/errors/17, WKJavaScriptExceptionColumnNumber=55, WKJavaScriptExceptionSourceURL=file:///var/containers/Bundle/Application/4EAB8056-137E-4F21-8B08-174B147D265E/NewStoreManager.app/AAHighchartsLib.js, NSLocalizedDescription=发生 JavaScript 异常}

**Comment by AAChartModel** [comment]
你是怎么使用的?贴上代码

**Comment by IGujie** [comment]
sorry，我找到原因，是我图标类型设置错了，感谢你的回答

.chartTypeSet(@"bar")//图表类型
