### ISSUE TITLE
设置图表类型为pie，属性.dataLabelEnabledSet设置为false崩溃

### ISSUE THREAD

**Issue by Vutumn** [AAChartModel/AAChartKit#312]
崩溃地方在AAOptions.m的363行
 .dataLabelsSet(aaDataLabels
                                            .formatSet(@"<b>{point.name}</b>: {point.percentage:.1f} %")
                                            )

**Comment by AAChartModel** [comment]
你把`formatSet(@"<b>{point.name}</b>: {point.percentage:.1f} %")`这一句删掉就行了
