### ISSUE TITLE
折线图点击图上的点 有没有回调事件？在线等急！！！！

### ISSUE THREAD

**Issue by hui123** [AAChartModel/AAChartKit#321]
折线图点击图上的点 有没有回调事件？在线等急！！！！

**Comment by AAChartModel** [comment]
AAChartKit 不支持点击事件回调

**Comment by hui123** [comment]
点击点弹框 的是哪一个事件？能否告知一下 回调的数据函数？

**Comment by AAChartModel** [comment]
AAChartKit是封装的 Highcharts 前端图表库,所以获得点击事件需要 js 逆向传值给 OC, 但是我目前没有做这块的内容.

**Comment by AAChartModel** [comment]
如果你必须要使用图表的点击事件回调功能,建议你你可以使用其他的原生图表库.

**Comment by hui123** [comment]
好的谢谢

**Comment by LarkinXQ** [comment]
这是一个很强大的图表库，希望作者完善点击事件的回调，这样更加完美！

**Comment by AAChartModel** [comment]
如README中所言
> 🖱 支持图表的用户点击事件及单指滑动事件,可在此基础上实现双表联动乃至多表联动,以及其他更多更复杂的自定义用户交互效果.

https://github.com/AAChartModel/AAChartKit/blob/master/CHINESE-README.md#%E6%94%AF%E6%8C%81%E7%9B%91%E5%90%AC%E7%94%A8%E6%88%B7%E7%82%B9%E5%87%BB%E4%BA%8B%E4%BB%B6%E5%8F%8A%E5%8D%95%E6%8C%87%E6%BB%91%E5%8A%A8%E4%BA%8B%E4%BB%B6
