### ISSUE TITLE
你好 这个代码可以实现玫瑰图 显示百分比吗？中间还带有间隔的 还有那个检测合格率的 带阴影的,谢谢了, 好像代码里面和highchatrs都是把玫瑰图归为了柱状图类别，只能设置数字，不能显示百分比？

### ISSUE THREAD

**Issue by bb5201314** [AAChartModel/AAChartKit#328]
￼
![2018-06-20 9 16 00](https://user-images.githubusercontent.com/8929444/41632038-97485af2-746a-11e8-9f5b-76a737e20b5a.png)››››››››
![2018-06-20 9 17 02](https://user-images.githubusercontent.com/8929444/41632083-c95ecdd2-746a-11e8-8362-0204d08366a0.png)

**Comment by AAChartModel** [comment]
> 好像代码里面和highchatrs都是把玫瑰图归为了柱状图类别，只能设置数字，不能显示百分比

你说的没错,确实不可以
