### ISSUE TITLE
Y轴连续数据相同 不会绘制线（绘制折线或曲线）

### ISSUE THREAD

**Issue by stevenJiechen** [AAChartModel/AAChartKit#336]

**Comment by AAChartModel** [comment]
你说的这个问题可能是 Highcharts 的一个小 bug,之前有 AAChartKit 的使用者提到过.

**Comment by AAChartModel** [comment]
解决问题的方法是:
在Y轴连续数据相同时,设置 AAChartModel 的**gradientColorEnable**属性为 **false **

**Comment by AAChartModel** [comment]
> 在Y轴连续数据相同时

为了避免你需要自己做这种特殊情况的判断,最好的办法就是不要直接设置 AAChartModel 的gradientColorEnable属性为 false,因为在现实情况下,折线和曲线实在是没有设置为渐变色的必要(gradientColorEnable= true 就是设置图表颜色为渐变色)
