### ISSUE TITLE
Readme 里面怎么不放pod的配置指导？

### ISSUE THREAD

**Issue by DeliriousLee** [AAChartModel/AAChartKit#337]
然后找了一下podspec才用cocopod加载

**Comment by DeliriousLee** [comment]
嗯，在使用的时候发现了，好像在加载的时候会报错，[NSURL  initFileURLWithPath] 之后找不到文件就报错了

**Comment by AAChartModel** [comment]
AAChartKit 现已支持 Cocoapods 导入, 具体内容参见 README 文档
