### ISSUE TITLE
Y轴显示精度问题

### ISSUE THREAD

**Issue by topws** [AAChartModel/AAChartKit#343]
注释有一句。“formatSet(@"{value:.,0f}")//让y轴的值完整显示 而不是100000显示为100k“

怎么写才能显示为100k?

**Comment by topws** [comment]
还有一个问题，我的X轴显示的数据有很多，比如有五十个，所以X轴的标签就显示不下了，我能指定每隔几个显示一个标签吗？比如0，10，20，30，40这种？

**Comment by AAChartModel** [comment]
参见 Demo 中的这段被我注释了的代码:        
```objective-c
_aaChartModel.xAxisTickInterval = @3;//设置 X轴坐标点的间隔数,默认是1(手机端的屏幕较为狭窄, 如果X轴坐标点过多,文字过于密集的时候可以设置此属性值,用户的密集恐惧症将得到有效治疗😝)
```
所以说只要修改 AAChartModel 实例对象的_`xAxisTickInterval`属性就可以了
