### ISSUE TITLE
Does aachartkit supports graph like each column has uniq record  

### ISSUE THREAD

**Issue by voraviral** [AAChartModel/AAChartKit#347]
Hi my requirement is like each column has a unique values which is not repeating in another column. Highchart web graph supports the same. I'm attaching an example image to showcase my issue.

Each column has different value and that column can be a stacked based on data, e.g column 1 has 1 record, column 2 has 3 records (in stack) column 3 has 2 records .. 
let me know if I can achieve the same using AAChartkit
![screen shot 2018-07-02 at 8 07 24 pm](https://user-images.githubusercontent.com/1261955/42170227-9313471c-7e33-11e8-95af-533ec728f4de.png)

**Comment by AAChartModel** [comment]
Can you give me the online example link that graph like each column has uniq record?

**Comment by voraviral** [comment]
Sorry , for security reasons I'm not able to share online demo what our web team has created. But let me give you some more screen shots and highchart demo which is near to my requirement. 

![chart demo](https://user-images.githubusercontent.com/1261955/42200854-cc6a10a2-7eb2-11e8-9add-de2ba10043fc.png)
In this screen you can see each column has different values which can be checked using color and names mentioned at bottom. 

This is [high-chart](https://www.highcharts.com/demo/column-stacked) url which graph our team has used and customised.

**Comment by AAChartModel** [comment]
Update to the latest version AAChartKit,then
1. configure the AAOptions like this:
```objective-c
 AAOptions * aaOptions = (id)@{
                            @"chart": @{
                                    @"type": @"column"
                                    },
                            @"title": @{
                                    @"text": @"Stacked column chart"
                                    },
                            @"xAxis": @{
                                    @"categories": @[@"Apples", @"Oranges", @"Pears", @"Grapes", @"Bananas"]
                                    },
                            @"yAxis": @{
                                    @"min": @0,
                                    @"title": @{
                                            @"text": @"Total fruit consumption"
                                            },
                                    @"stackLabels": @{
                                            @"enabled": @true,
                                            @"style": @{
                                                    @"fontWeight": @"bold",
                                                    }
                                            }
                                    },
                            @"legend": @{
                                    @"align": @"right",
                                    @"x": @-30,
                                    @"verticalAlign": @"top",
                                    @"y": @25,
                                    @"floating": @true,
                                    
                                    @"borderColor": @"#CCC",
                                    @"borderWidth": @1,
                                    @"shadow": @false
                                    },
                            @"tooltip": @{
                                    @"headerFormat": @"<b>{point.x}</b><br/>",
                                    @"pointFormat": @"{series.name}: {point.y}<br/>Total: {point.stackTotal}"
                                    },
                            @"plotOptions": @{
                                    @"series":@{
                                            @"animation":@{
                                                    @"easing":@"bounce",
                                                    @"duration":@1000
                                                    }
                                            },
                                    @"column": @{
                                            @"stacking": @"normal",
                                            @"dataLabels": @{
                                                    @"enabled": @true,
                                                    
                                                    }
                                            }
                                    },
                            @"series": @[@{
                                             @"name": @"John",
                                             @"data": @[@5, @3, @4, @7, @2]
                                             }, @{
                                             @"name": @"Jane",
                                             @"data": @[@2, @2, @3, @2, @1]
                                             }, @{
                                             @"name": @"Joe",
                                             @"data": @[@3, @4, @4, @2, @5]
                                             }]
                            };
```
2. Draw the chart:
```objective-c
    [aaChartView aa_drawChartWithOptions:aaOptions];
```

**Comment by AAChartModel** [comment]
**Method 2**
1.configure the AAOptions instance object like this:
```objective-c
 AAChart *aaChart = AAObject(AAChart)
                        .typeSet(AAChartTypeColumn);

    AATitle *aaTitle = AAObject(AATitle)
                        .textSet(@"Stacked column chart");

    AAXAxis *aaXAsix = AAObject(AAXAxis)
                        .visibleSet(true)
                        .categoriesSet(@[@"Apples", @"Oranges", @"Pears", @"Grapes", @"Bananas"]);

    AAYAxis *aaYAxis = AAObject(AAYAxis)
                        .visibleSet(true)
                        .minSet(@0)
                        .titleSet(AAObject(AATitle)
                                  .textSet(@"Total fruit consumption")
                                  )
                        .stackLabelsSet(AAObject(AALabels)
                                        .enabledSet(true)
                                        .styleSet(AAObject(AAStyle)
                                                  .fontWeightSet(AAChartFontWeightTypeBold)
                                                  )
                                        );

    AALegend *aaLegend = AAObject(AALegend)
                          .enabledSet(true)
                          .alignSet(AALegendAlignTypeRight)
                          .xSet(@(-30))
                          .verticalAlignSet(AALegendVerticalAlignTypeTop)
                          .ySet(@25)
                          .borderColorSet(@"#ccc")
                          .borderWidthSet(@1);

    AATooltip *aaTooltip = AAObject(AATooltip)
                            .headerFormatSet(@"<b>{point.x}</b><br/>")
                            .pointFormatSet(@"{series.name}: {point.y}<br/>Total: {point.stackTotal}");

    AAPlotOptions *aaPlotOptions = AAObject(AAPlotOptions)
                                    .seriesSet(AAObject(AASeries)
                                               .animationSet(AAObject(AAAnimation)
                                                             .easingSet(@"bounce")
                                                             .durationSet(@1000)
                                                             )
                                               )
                                    .columnSet(AAObject(AAColumn)
                                               .stackingSet(AAChartStackingTypeNormal)
                                               .dataLabelsSet(AAObject(AADataLabels)
                                                              .enabledSet(true)
                                                              )
                                               );

    NSArray *seriesElementArr = @[
                                  AAObject(AASeriesElement)
                                  .nameSet(@"John")
                                  .dataSet(@[@5, @3, @4, @7, @2]),
                                  AAObject(AASeriesElement)
                                  .nameSet(@"Jane")
                                  .dataSet(@[@5, @3, @4, @7, @2]),
                                  AAObject(AASeriesElement)
                                  .nameSet(@"Joe")
                                  .dataSet(@[@5, @3, @4, @7, @2]),
                                  ];

    AAOptions *aaOptions = AAObject(AAOptions)
    .chartSet(aaChart)
    .titleSet(aaTitle)
    .xAxisSet(aaXAsix)
    .yAxisSet(aaYAxis)
    .legendSet(aaLegend)
    .tooltipSet(aaTooltip)
    .plotOptionsSet(aaPlotOptions)
    .seriesSet(seriesElementArr);
```

2.Draw the chart:
```objective-c
    [aaChartView aa_drawChartWithOptions:aaOptions];
```

**Comment by AAChartModel** [comment]
**Method 3**
1.Configure the AAOptions instance object like this:
```objective-c
  AAOptions *options2 = AAObject(AAOptions)
    .chartSet(AAObject(AAChart)
              .typeSet(AAChartTypeColumn)
              )
    .titleSet(AAObject(AATitle)
              .textSet(@"Stacked column chart")
              )
    .xAxisSet(AAObject(AAXAxis)
              .visibleSet(true)
              .categoriesSet(@[@"Apples", @"Oranges", @"Pears", @"Grapes", @"Bananas"])
              )
    .yAxisSet(AAObject(AAYAxis)
              .visibleSet(true)
              .minSet(@0)
              .titleSet(AAObject(AATitle)
                        .textSet(@"Total fruit consumption")
                        )
              .stackLabelsSet(AAObject(AALabels)
                              .enabledSet(true)
                              .styleSet(AAObject(AAStyle)
                                        .fontWeightSet(AAChartFontWeightTypeBold)
                                        )
                              )
              )
    .legendSet(AAObject(AALegend)
               .enabledSet(true)
               .alignSet(AALegendAlignTypeRight)
               .xSet(@(-30))
               .verticalAlignSet(AALegendVerticalAlignTypeTop)
               .ySet(@25)
               .borderColorSet(@"#ccc")
               .borderWidthSet(@1)
               )
    .tooltipSet(AAObject(AATooltip)
                .headerFormatSet(@"<b>{point.x}</b><br/>")
                .pointFormatSet(@"{series.name}: {point.y}<br/>Total: {point.stackTotal}")
                )
    .plotOptionsSet(AAObject(AAPlotOptions)
                    .seriesSet(AAObject(AASeries)
                               .animationSet(AAObject(AAAnimation)
                                             .easingSet(@"bounce")
                                             .durationSet(@1000)
                                             )
                               )
                    .columnSet(AAObject(AAColumn)
                               .stackingSet(AAChartStackingTypeNormal)
                               .dataLabelsSet(AAObject(AADataLabels)
                                              .enabledSet(true)
                                              )
                               )
                    )
    .seriesSet(@[
                 AAObject(AASeriesElement)
                 .nameSet(@"John")
                 .dataSet(@[@5, @3, @4, @7, @2]),
                 AAObject(AASeriesElement)
                 .nameSet(@"Jane")
                 .dataSet(@[@5, @3, @4, @7, @2]),
                 AAObject(AASeriesElement)
                 .nameSet(@"Joe")
                 .dataSet(@[@5, @3, @4, @7, @2]),
                 ]);

```
2.Draw the chart:
```objective -c
[aaChartView aa_drawChartWithOptions:aaOptions];
```

**Comment by AAChartModel** [comment]
More details you can see in the AAChartKit latest version demo,The above  code content comes from come from the custom style stacked column chart of AAChart demo.

**Comment by voraviral** [comment]
is it possible to give different color to each column stack and different name when user tap on any stack ?

**Comment by AAChartModel** [comment]
Considering that your colleague have finished the chart job,you can ask them how to configure the `options` of Highcharts in web,and then you can configure the `AAOptions` of `AAChartKit` through refering to the `options` of `Highcharts` in front-end, After all, the AAOptions of AAChartKit is just the mirror of `options` in `Highcharts`.

By the way,the `options` of chart in HighCharts just the simple json dictionary.

**Comment by AAChartModel** [comment]
Or you can send the ` options (json)` of HighCharts to me directly,I will help you to configure the AAOptions instance object in AAChartKit.Avoid to leak the commercial secrets, you can just use virtual data instead the real data.😊😊😊

**Comment by voraviral** [comment]
I've created code and which is working perfect as per my needs, only thing is on tooltip it shows all series, can you please help me to show only tooltip for selected values , that I'm not able to do. 

`AAChartModel *aaChartModel = AAObject(AAChartModel)
        .chartTypeSet(AAChartTypeColumn)
        .titleSet(@"January 16-16 November recharge coupon analysis")
        .stackingSet(AAChartStackingTypeNormal)
        //Theme color array
        .categoriesSet(@[@"Production",@"Insurance",@"physicalCommited",@"% Sold",@"% Re-Owned"])
        .seriesSet(@[
                    AAObject(AASeriesElement)
                    .nameSet(@"exp. production")
                    .dataSet(@[@82000.89,@0,@0,@0,@0])
                    .colorSet(@"#00fe34")
                    .allowPointSelectSet(YES)
                    .dataLabelsSet((AAObject(AADataLabels)
                                    .enabledSet(NO)
                                    .styleSet(AAObject(AAStyle)
                                              .colorSet(@"#000000")
                                              .fontSizeSet(@"11px")
                                              )
                                    ))
                    .colorByPointSet(YES)
                    ,
                    AAObject(AASeriesElement)
                    .nameSet(@"Insurance")
                    .dataSet(@[@0,@34000000,@0,@0,@0])
                    .colorSet(@"#f0hd94")
                    .allowPointSelectSet(YES)
                    .dataLabelsSet((AAObject(AADataLabels)
                                    .enabledSet(NO)
                                    .styleSet(AAObject(AAStyle)
                                              .colorSet(@"#000000")
                                              .fontSizeSet(@"11px")
                                              )
                                    ))
                    ,
                    AAObject(AASeriesElement)
                    .nameSet(@"Physical Committed")
                    .dataSet(@[@0,@0,@9000678,@0,@0])
                    .allowPointSelectSet(YES)
                    .dataLabelsSet((AAObject(AADataLabels)
                                    .enabledSet(NO)
                                    .styleSet(AAObject(AAStyle)
                                              .colorSet(@"#000000")
                                              .fontSizeSet(@"11px")
                                              )
                                    ))
                    .colorByPointSet(YES)
                    
                    ,
                   
                    AAObject(AASeriesElement)
                    .nameSet(@"Long Puts")
                    .dataSet(@[@0,@0,@0,@404657,@0])
                    .allowPointSelectSet(YES)
                    .dataLabelsSet((AAObject(AADataLabels)
                                    .enabledSet(NO)
                                    .styleSet(AAObject(AAStyle)
                                              .colorSet(@"#000000")
                                              .fontSizeSet(@"11px")
                                              )
                                    ))
                    ,
                    AAObject(AASeriesElement)
                    .nameSet(@"Short Cals")
                    .dataSet(@[@0,@0,@0,@600965874,@0])
                    .allowPointSelectSet(YES)
                    .dataLabelsSet((AAObject(AADataLabels)
                                    .enabledSet(NO)
                                    .styleSet(AAObject(AAStyle)
                                              .colorSet(@"#000000")
                                              .fontSizeSet(@"11px")
                                              
                                              )
                                    ))
                    ,
                    AAObject(AASeriesElement)
                    .nameSet(@"Long Future")
                    .dataSet(@[@0,@0,@0,@0,@5585578])
                    .allowPointSelectSet(YES)
                    .dataLabelsSet((AAObject(AADataLabels)
                                    .enabledSet(NO)
                                    .styleSet(AAObject(AAStyle)
                                              .colorSet(@"#000000")
                                              .fontSizeSet(@"11px")
                                              
                                              )
                                    ))
                    ,
                    AAObject(AASeriesElement)
                    .nameSet(@"Short Puts")
                    .dataSet(@[@0,@0,@0,@0,@297545673])
                    .allowPointSelectSet(YES)
                    .dataLabelsSet((AAObject(AADataLabels)
                                    .enabledSet(NO)
                                    .styleSet(AAObject(AAStyle)
                                              .colorSet(@"#000000")
                                              .fontSizeSet(@"11px")
                                              
                                              )
                                    ))
                    ,
                    AAObject(AASeriesElement)
                    .nameSet(@"Long Calls")
                    .dataSet(@[@0,@0,@0,@0,@89345678])
                    .allowPointSelectSet(YES)
                    .dataLabelsSet((AAObject(AADataLabels)
                                    .enabledSet(NO)
                                    .styleSet(AAObject(AAStyle)
                                              .colorSet(@"#000000")
                                              .fontSizeSet(@"11px")
                                              
                                              )
                                    ))
                    ,
                    
                    
                   ]);
        return aaChartModel;`

**Comment by AAChartModel** [comment]
Now,I added a new property named `tooltipShared` for `AAChartModel`,you can show only tooltip for selected values only and not for any other value of that column through setting the `tooltipShared` be `NO`. Please Update the AAChartKit to be the latest version.

Additional content:
if you do not want to show the DataLabel of chart,you should set the dataLabelEnabled of AAChartModel be NO rather than setting the DataLabel instance object of AASeriesElement.


The whole content of setting AAChartModel as follow:
```objective-c
        AAChartModel *aaChartModel = AAObject(AAChartModel)
        .chartTypeSet(AAChartTypeColumn)
        .titleSet(@"January 16-16 November recharge coupon analysis")
        .stackingSet(AAChartStackingTypeNormal)
        .dataLabelEnabledSet(NO)//❤️_❤️_❤️_
        .tooltipSharedSet(NO)//❤️_❤️_❤️_
        //Theme color array
        .categoriesSet(@[@"Production",@"Insurance",@"physicalCommited",@"% Sold",@"% Re-Owned"])
        .seriesSet(@[
                     AAObject(AASeriesElement)
                     .nameSet(@"exp. production")
                     .dataSet(@[@82000.89,@0,@0,@0,@0])
                     .colorSet(@"#00fe34")
                     .allowPointSelectSet(YES)
                     .colorByPointSet(YES)
                     ,
                     AAObject(AASeriesElement)
                     .nameSet(@"Insurance")
                     .dataSet(@[@0,@34000000,@0,@0,@0])
                     .colorSet(@"#f0hd94")
                     .allowPointSelectSet(YES)
                     ,
                     AAObject(AASeriesElement)
                     .nameSet(@"Physical Committed")
                     .dataSet(@[@0,@0,@9000678,@0,@0])
                     .allowPointSelectSet(YES)
                     .colorByPointSet(YES)
                     ,
                     AAObject(AASeriesElement)
                     .nameSet(@"Long Puts")
                     .dataSet(@[@0,@0,@0,@404657,@0])
                     .allowPointSelectSet(YES)
                     ,
                     AAObject(AASeriesElement)
                     .nameSet(@"Short Cals")
                     .dataSet(@[@0,@0,@0,@600965874,@0])
                     .allowPointSelectSet(YES)
                     ,
                     AAObject(AASeriesElement)
                     .nameSet(@"Long Future")
                     .dataSet(@[@0,@0,@0,@0,@5585578])
                     .allowPointSelectSet(YES)
                     ,
                     AAObject(AASeriesElement)
                     .nameSet(@"Short Puts")
                     .dataSet(@[@0,@0,@0,@0,@297545673])
                     .allowPointSelectSet(YES)
                     ,
                     AAObject(AASeriesElement)
                     .nameSet(@"Long Calls")
                     .dataSet(@[@0,@0,@0,@0,@89345678])
                     .allowPointSelectSet(YES)
                     ,                     
                     ]);
        return aaChartModel;
```

**Comment by voraviral** [comment]
thank you very much @AAChartModel it was awesome...
