### ISSUE TITLE
扇形图 设置 半径的问题。

### ISSUE THREAD

**Issue by kallywang-jia** [AAChartModel/AAChartKit#35]
扇形图 设置dataLabelEnabled=YES后，半径大小就会根据数据的长短A来显示；就算设置AASeriesElement 的 borderRadius=B，刚加载出来半径为A，点击后，变为B。该情况怎么处理呢？应用场景是：不同的页面，数据占比不一样，然后半径大小不一致，看上起效果不太好。

**Comment by AAChartModel** [comment]
问题已解决,同问题 #172
