### ISSUE TITLE
隐藏X轴的刻度线，但是显示X轴的横坐标名称显示

### ISSUE THREAD

**Issue by hakehong** [AAChartModel/AAChartKit#356]
![451531127630_ pic](https://user-images.githubusercontent.com/12205409/42441864-bf861988-839b-11e8-8bcf-686a1714158d.jpg)

**Comment by seanLee** [comment]
@hakehong 你是直接改了HTML吗。

**Comment by AAChartModel** [comment]
**seanLee**同学有可能是看的某一个图表📈网页中有使用到highCharts,并且具有X轴轴线及X轴刻度线隐藏,然而X轴文字不隐藏的视觉效果.  从他的截图来看,你也只需要设置 `lineColor`和`tickColor`为`#ffffff(白色)`即可达到视觉上的X轴轴线和X轴刻度线被完美隐藏的效果.

```objective-c
AAPropSetFuncImplementation(AAXAxis, NSString *, lineColor) //x轴轴线线颜色
AAPropSetFuncImplementation(AAXAxis, NSNumber *, max)  //x轴最大值
AAPropSetFuncImplementation(AAXAxis, NSNumber *, min)  //x轴最小值（设置为0就不会有负数）
AAPropSetFuncImplementation(AAXAxis, NSString *, tickColor) //x轴轴线下方刻度线颜色
```

`x轴轴线线颜色`和`x轴轴线下方刻度线颜色`此两者目前都是被AAChartKit所支持的.

**Comment by seanLee** [comment]
@AAChartModel 是啊～我一开始是看HighCharts的Demo里看到有设置这个属性,然后```AAChartModel```这个类是没办法设置属性的,我以为是不支持.后来看到这个Issue之后,全局搜了一下,然后对着Demo自定义了```AAOptions```这个类,现在可以实现这个功能了.谢谢作者,很好用的一个库

**Comment by AAChartModel** [comment]
Highchartsz可配置的属性实在是太多了,AAChartModel支持全部内容有点不太现实,现在的AAChartModel都已经过于臃肿了.只能是有所取舍的在AAChartModel中添加属性.

**Comment by seanLee** [comment]
哈哈～我想表达的意思是我没有仔细看文档😂 这个库已经很棒啦,维护的时间越长,代码肯定会相对来说更臃肿

**Comment by AAChartModel** [comment]
🤣🤣🤣

**Comment by hakehong** [comment]
> @hakehong 你是直接改了HTML吗。

好久之前的事，忘记了。
