### ISSUE TITLE
能否为折线区域填充图添加自定义的半透明渐变色图形效果?

### ISSUE THREAD

**Issue by YouMotherFucker** [AAChartModel/AAChartKit#36]
项目中需要设置折线区域填充图的蓝色渐变效果,在`AAChartKit`的 DEMO 示例中似乎没有找到呢!

**Comment by AAChartModel** [comment]
这个可以有,后续补充!

**Comment by AAChartModel** [comment]
设置 AAChartModel 的布尔属性gradientColorEnable为 Yes 即是开启图标的渐变色功能
