### ISSUE TITLE
数据比较大的时候，每三位数用空格自动隔开，想把空格换为英文逗号，有方法吗

### ISSUE THREAD

**Issue by xiaozhao81** [AAChartModel/AAChartKit#361]
您好，框架功能非常全，非常漂亮，适配非常好，现在有个需求，想要将数据比较大的时候，每三位数自动用空格隔开，换位用英文逗号隔开，有方法吗，谢谢，（包括y轴和tooltip上的数字  ， 1000 000 换为 1000,000）

**Comment by AAChartModel** [comment]
这个解决方法比较简单, Swift 版本的 AAChartKit 已经有人提过这个问题,我这个周末抽空加上这个方法

**Comment by AAChartModel** [comment]
具体的相关内容参见 AAChartKit-Swift 的 issues 列表里面的这个已关闭问题 #https://github.com/AAChartKit/AAChartKit-Swift/issues/77

**Comment by AAChartModel** [comment]
问题已解决,参见 #417
