### ISSUE TITLE
关于更新后AAChartTypePie类型主题色显示异常的问题

### ISSUE THREAD

**Issue by Kingsleeeey** [AAChartModel/AAChartKit#367]
更新后项目出现AAChartTypePie类型主题色只显示一种颜色的问题，如图
![simulator screen shot - iphone x - 2018-07-23 at 10 24 04](https://user-images.githubusercontent.com/34328533/43054214-086866d4-8e63-11e8-8201-fad2d454868f.png)

**Comment by AAChartModel** [comment]
将 AASeriesElement 的布尔属性`colorByPoint`注释掉即可
```objective-c
AAPropStatementAndPropSetFuncStatement(assign, AASeriesElement, BOOL      , colorByPoint);
```

在 OC 当中布尔属性声明之后默认是 false, 但是colorByPoint= false 时,表示扇形图不支持彩色,所以注释掉这个`colorByPoint `属性即可.
