### ISSUE TITLE
dataLabelEnabledSet,饼状图设置为false就崩溃。

### ISSUE THREAD

**Issue by afunnyrainman** [AAChartModel/AAChartKit#368]
dataLabelEnabledSet饼状图设置为false就崩溃。这个应该是显示或者隐藏线和文字介绍的吧？

**Comment by AAChartModel** [comment]
这些底部可点按的小圆点其实是图表的图例(legend),设置 AAChartModel 的布尔属性legendEnabled为 NO 即可隐藏图例.

```objective-c
aaChartModel.legendEnabled = NO;
```

**Comment by afunnyrainman** [comment]
图例是去掉了，可是大佬，dataLabelEnabledSet饼状图设置为false就崩溃。我是想把每一个圆饼出来的一条线和名字也去掉。
