### ISSUE TITLE
针对问题#30，我想问 点击底部，数据显示或隐藏的接口是哪个？

### ISSUE THREAD

**Issue by kallywang-jia** [AAChartModel/AAChartKit#37]
我现在的需求是折线填充图由于数据太多，要做个开关，开关关闭后，所有数据在图表上都不显示。开关打开后，所有数据都显示。

**Comment by AAChartModel** [comment]
可否展示一下你折现填充图数据太多之后具体显示的是一个什么样子的状态?

**Comment by kallywang-jia** [comment]
就是手机上有19条曲线，用户可能只关注一条线。我想做个开关，打开就显示19条线，关闭一条也不显示。用户关闭，然后再选自己关注的那条就好了。

**Comment by kallywang-jia** [comment]
![b1f931f1-66ed-4cae-a8d7-78c24f9ae758](https://user-images.githubusercontent.com/12370723/29416302-36506c30-8398-11e7-95c9-705552d0d767.png)

**Comment by kallywang-jia** [comment]
开关放到 1 的下面，关闭时，相当于一次性点击了 2014~2020 这7个按钮

**Comment by AAChartModel** [comment]
明白你的意思了,这个是可以实现的!不过需要花一点时间,最迟这个礼拜天回复可以么,因为我最近也是比较的忙呢,天天加班!

**Comment by kallywang-jia** [comment]
太赞了，我下周一发版。

**Comment by bluesky0109** [comment]
请教下 2014-2020整块 红框的如何隐藏掉？？

**Comment by AAChartModel** [comment]
aaChartModel.legendEnabled = NO;//隐藏图表的图例(图表底部可点按的小圆点)
