### ISSUE TITLE
使用pod导入页面显示一片空白，手动导入正常显示

### ISSUE THREAD

**Issue by fanxiaocong** [AAChartModel/AAChartKit#371]
您好，我这边使用 pod 导入 AAChartKit 框架后，运行的时候报错，然后我修改的 AAChartKit 框架中加载 html 的代码，运行成功后页面显示一片空白，换成手动导入就显示正常，请问您那边有解决方案吗？

**Comment by fanxiaocong** [comment]
@AAChartModel 我对比了一下 pod 与您 Demo 中的源文件，发发现有很多地方不一样，您提交的 pod 的文件应该不是最新的，当我修改了 pod 的源文件，与您的Demo中的源文件保持一致，就可以正常显示了。

**Comment by AAChartModel** [comment]
那你可否将你的修改的内容提交一下呢,我合并之后或许大家都可以使用 pod 来导入了

**Comment by fanxiaocong** [comment]
@AAChartModel 已经提交了，您看下吧
