### ISSUE TITLE
单指滑动 怎么让浮动框不跟随

### ISSUE THREAD

**Issue by FLGiOS** [AAChartModel/AAChartKit#374]
数据多时候，需要做单指滑动，浮动窗和滑动有冲突怎么关闭呢

**Comment by AAChartModel** [comment]
在`AATooltip.h`可以看到这样一段被注释掉了的代码
```objective-c
//AAPropStatementAndPropSetFuncStatement(assign, AATooltip, BOOL,       followTouchMove);//在触摸设备上，tooltip.followTouchMove选项为true（默认）时，平移需要两根手指。若要允许用一根手指平移，请将followTouchMove设置为false。
```

**Comment by AAChartModel** [comment]
所以你只要将`AATooltip.h` 文件和 `AATooltip.m` 文件中的这个属性解开注释即可

就如注释中所说
>  在触摸设备上，tooltip.followTouchMove选项为true（默认）时，平移需要两根手指。若要允许用一根手指平移，请将followTouchMove设置为false。

所以你只要解开 AATooltip 的这个属性的注释, AATooltip 的布尔属性就默认为 false

**Comment by FLGiOS** [comment]
谢谢你的回复，打开注释后可以不跟随了，但是点击出现的浮动窗消失了，，然后就不知道刚刚点了哪个。。能设置点击出现的浮动窗不会因为滑动而消失吗

**Comment by AAChartModel** [comment]
> hideDelay: Number  
当鼠标移出数据点或者图表后，数据提示框会在设定的延迟时间后消失 默认是：500.

从官方文档中的这个属性来看,应该就是添加并设置这个属性值为远超过500ms 之后就能够做到你说的
> 能设置点击出现的浮动窗不会因为滑动而消失吗

这个效果了吧,我后面可以加上这个属性.

**Comment by FLGiOS** [comment]
嗯，就是点击出现准星线和浮动窗，，左右滑动的时候，，准星线和浮动窗保持在那。。那就辛苦你了。。
