### ISSUE TITLE
关于y轴坐标精度问题

### ISSUE THREAD

**Issue by ChaoYug** [AAChartModel/AAChartKit#376]
你好,在操作双y轴时,右边y轴坐标是需要保留一位小数,传值为1.0时只显示1,请问是否有什么方式可以进行处理?感谢.

**Comment by ChaoYug** [comment]
![1533285758735](https://user-images.githubusercontent.com/20300751/43633604-495c4052-973c-11e8-960f-d6fd77b25137.jpg)
如图

**Comment by AAChartModel** [comment]
方便粘贴一下你的代码吗?我好复现一下问题

**Comment by ChaoYug** [comment]
AALabels *labels = (AAObject(AALabels)
                        .enabledSet(true)//设置y轴是否显示数字
                        .styleSet(AAObject(AAStyle)
                                  .colorSet(@"#B1B1B1")
                                  .fontSizeSet(@"12px")
                                  .fontWeightSet(AAChartSymbolTypeDiamond)
                                  )
                        .formatSet(@"{value:.,1f}")
                        );
    
    AAYAxis *yAxisOne = AAObject(AAYAxis)
    .visibleSet(true)
    // y轴线颜色
    .gridLineColorSet(@"#FFFFFF")
    .tickPositionsSet(@[@0.1,@0.2,@0.3,@0.4,@0.5,@0.6,@0.7,@0.8,@0.9,@1.0])
    .labelsSet(labels.formatSet(@"{value}"))
    .titleSet(AAObject(AATitle)
              .textSet(@"")
              )
    .oppositeSet(true);
    
    AAYAxis *yAxisTwo = AAObject(AAYAxis)
    .visibleSet(true)
    .gridLineColorSet(@"#FFFFFF")
    .titleSet(AAObject(AATitle)
              .textSet(@"")
              );
    
    NSArray *yAxisArr = @[// Primary yAxis
                          yAxisOne,
                          // Secondary yAxis
                          yAxisTwo,
                          ];
    AATooltip *aaTooltip = AAObject(AATooltip).sharedSet(true).enabledSet(true);
    NSArray *aaSeries = @[
                          AAObject(AASeriesElement)
                          .nameSet(@"未处理")
                          .typeSet(AAChartTypeColumn)
                          .stackingSet(AAChartStackingTypeNormal)
                          .yAxisSet(@1)
                          .dataSet(@[@30,@60,@40,@30,@45,@9])
                          .dataLabelsSet(AAObject(AADataLabels)
                                         .enabledSet(NO)
                                         )
                          ,
                          AAObject(AASeriesElement)
                          .nameSet(@"已处理")
                          .typeSet(AAChartTypeColumn)
                          .stackingSet(AAChartStackingTypeNormal)
                          .yAxisSet(@1)
                          .dataSet(@[@90,@70,@80,@50,@87,@91])
                          .dataLabelsSet(AAObject(AADataLabels)
                                         .enabledSet(NO)
                                         )
                          ,
                          AAObject(AASeriesElement)
                          .nameSet(@"处理率")
                          //                          .markerSet((id)@0)
                          .yAxisSet(@0)
                          .lineWidthSet(@3)
                          .typeSet(AAChartTypeSpline)
                          .stackingSet(AAChartStackingTypeNormal)
                          .dataSet(@[@0.2, @0.8, @0.7, @0.3, @0.5, @0.6])
                          .dataLabelsSet(AAObject(AADataLabels)
                                         .enabledSet(NO)
                                         .formatSet(@"{value:.,.2f}")
                                         )
                          ];
    
    //X轴
    NSDictionary *xAxis = @{
                            @"categories":@[@"1栋", @"2栋", @"3栋", @"4栋", @"5栋", @"6栋"],
                            @"tickColor":@"#FFFFFF",
                            };

    AAOptions *chartOptions = AAObject(AAOptions);
    chartOptions.colorsSet(@[@"rgba(255,144,128,1)",@"rgba(0,191,183,1)", @"rgba(252,230,48,1)",]);//主题颜色数组
    chartOptions.tooltip.valueDecimals = @2;
    chartOptions.plotOptions.area.dataLabels.format = @"{point.y:.2f}";
    chartOptions.title = (id)@"";
    chartOptions.yAxis = (id)yAxisArr;
    chartOptions.tooltip = aaTooltip;
    chartOptions.series = aaSeries;
    chartOptions.xAxis = (id)xAxis;

    [self.aaChartView aa_drawChartWithOptions:chartOptions];

**Comment by ChaoYug** [comment]
@AAChartModel

**Comment by ChaoYug** [comment]
请问是否有好的解决方法?

**Comment by AAChartModel** [comment]
这样配置 AAOptions 实例对象就可以了

```objective-c
 AALabels *labels = (AAObject(AALabels)
                        .enabledSet(true)//设置y轴是否显示数字
                        .styleSet(AAObject(AAStyle)
                                  .colorSet(@"#B1B1B1")
                                  .fontSizeSet(@"12px")
                                  .fontWeightSet(AAChartSymbolTypeDiamond)
                                  )
                        .formatSet(@"{value:.,.2f}")
                        );
    
    AAYAxis *yAxisOne = AAObject(AAYAxis)
    .visibleSet(true)
    // y轴线颜色
    .gridLineColorSet(@"#FFFFFF")
    .tickPositionsSet(@[@0.1,@0.2,@0.3,@0.4,@0.5,@0.6,@0.7,@0.8,@0.9,@1.0])
    .labelsSet(labels)
    .titleSet(AAObject(AATitle)
              .textSet(@"")
              )
    .oppositeSet(true);
    
    AAYAxis *yAxisTwo = AAObject(AAYAxis)
    .visibleSet(true)
    .gridLineColorSet(@"#FFFFFF")
    .titleSet(AAObject(AATitle)
              .textSet(@"")
              );
    
    NSArray *yAxisArr = @[// Primary yAxis
                          yAxisOne,
                          // Secondary yAxis
                          yAxisTwo,
                          ];
    AATooltip *aaTooltip = AAObject(AATooltip).sharedSet(true).enabledSet(true);
    NSArray *aaSeries = @[
                          AAObject(AASeriesElement)
                          .nameSet(@"未处理")
                          .typeSet(AAChartTypeColumn)
                          .stackingSet(AAChartStackingTypeNormal)
                          .yAxisSet(@1)
                          .dataSet(@[@30,@60,@40,@30,@45,@9])
                          ,
                          AAObject(AASeriesElement)
                          .nameSet(@"已处理")
                          .typeSet(AAChartTypeColumn)
                          .stackingSet(AAChartStackingTypeNormal)
                          .yAxisSet(@1)
                          .dataSet(@[@90,@70,@80,@50,@87,@91])
                          ,
                          AAObject(AASeriesElement)
                          .nameSet(@"处理率")
                          //                          .markerSet((id)@0)
                          .yAxisSet(@0)
                          .lineWidthSet(@3)
                          .typeSet(AAChartTypeSpline)
                          .stackingSet(AAChartStackingTypeNormal)
                          .dataSet(@[@0.2, @0.8, @0.7, @0.3, @0.5, @0.6])
                          ];
    
    //X轴
    NSDictionary *xAxis = @{
                            @"categories":@[@"1栋", @"2栋", @"3栋", @"4栋", @"5栋", @"6栋"],
                            @"tickColor":@"#FFFFFF",
                            };
    
    AAOptions *chartOptions = AAObject(AAOptions);
    chartOptions.colorsSet(@[@"rgba(255,144,128,1)",@"rgba(0,191,183,1)", @"rgba(252,230,48,1)",]);//主题颜色数组
    chartOptions.title = (id)@"";
    chartOptions.yAxis = (id)yAxisArr;
    chartOptions.tooltip = aaTooltip;
    chartOptions.series = aaSeries;
    chartOptions.xAxis = (id)xAxis;
```

也就是说是

```objective-c
                        .formatSet(@"{value:.,.2f}")
```
是这句话在起作用

**Comment by AAChartModel** [comment]
话说你这图表的配色怎么看起来这么像是 ECharts 2.0啊?

**Comment by ChaoYug** [comment]
是吗,还真没注意.刚刚尝试过了,问题已解决,非常感谢.

**Comment by AAChartModel** [comment]
附言:
如果你不想显示 dataLabel, 不用为每个 AASeriesElement 实例对象添加这部分代码,不作任何设置,默认 dataLabel 就是不显示的
```objective-c
                          .dataLabelsSet(AAObject(AADataLabels)
                                         .enabledSet(NO)
                                         .formatSet(@"{value:.,.2f}")
                                         )
```

**Comment by ChaoYug** [comment]
好的,谢谢建议.
