### ISSUE TITLE
legend图例标题颜色

### ISSUE THREAD

**Issue by huangzhengguo** [AAChartModel/AAChartKit#387]
请问图例标题颜色怎么更改，只有黑色吗？

**Comment by AAChartModel** [comment]
1.自定义 AAOptions 实例对象

```objective-c
   AAChartModel *aaChartModel= AAObject(AAChartModel)
    .chartTypeSet(AAChartTypeLine)
    .titleSet(@"")
    .subtitleSet(@"")
    .categoriesSet(@[@"Java",@"Swift",@"Python",@"Ruby", @"PHP",@"Go",@"C",@"C#",@"C++",@"Perl",@"R",@"MATLAB",@"SQL"])
    .seriesSet(@[
                 AAObject(AASeriesElement)
                 .nameSet(@"2018")
                 .dataSet(@[@31,@22,@33,@54,@35,@36,@27,@38,@39,@54,@41,@29]),
                 ]
               );

    //设定图例项的CSS样式。只支持有关文本的CSS样式设定。 默认是：{ "color": "#333333", "cursor": "pointer", "fontSize": "12px", "fontWeight": "bold" }.
    AAItemStyle *aaItemStyle = AAObject(AAItemStyle)
    .colorSet(@"#ff0000")//字体颜色
    .cursorSet(@"pointer")//(在移动端这个属性没什么意义,其实不用设置)指定鼠标滑过数据列时鼠标的形状。当绑定了数据列点击事件时，可以将此参数设置为 "pointer"，用来提醒用户改数据列是可以点击的。
    .fontSizeSet(@"20px")//字体大小
    .fontWeightSet(AAChartFontWeightTypeThin);//字体为细体字
    
    AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
    aaOptions.legend.itemStyle = aaItemStyle;
```

2.绘制图形

```objective-c
    [aaChartView aa_drawChartWithOptions:aaOptions];

```

**Comment by huangzhengguo** [comment]
非常感谢，用AAItemStyle这个类的时候一直报错，receiver 'AAItemStyle' for class message is a forward declaration，还要引用 #import "AAItemStyle.h" 就好了

**Comment by AAChartModel** [comment]
嗯,忘了提了,这个我在解决这个问题的时候  f1f4b6a  忘了提了😅😅😅

**Comment by topws** [comment]
@AAChartModel 我用AAOptions赋值时，代码无效啊。
AAOptions *chartOptions = AAObject(AAOptions);
.....
chartOptions.legend.itemStyle = aaItemStyle;
跑起来的图例并没有变化，如果我要是赋值一个新的AALend又会出现创建失败，无Set方法，只能new一个出来，但是new出来的图例就直接不显示了。（PS：我本意是想只展示两个图例（一共三个折线图），但是没发现入口，想改动大小来展示全部的）

**Comment by AAChartModel** [comment]
@topws   说实话,你的描述相当混乱.最好是新开一个 issue, 贴上你的需要需求效果图,和你现在的有问题代码.
你现在这样既没有具体目标效果,也没有实际的问题代码.导致我既复现不了你的问题.也满足不了你的要求.

**Comment by topws** [comment]
@AAChartModel 抱歉啊，
<img width="238" alt="8884c7c2-5d54-40f9-9751-f3d47b317619" src="https://user-images.githubusercontent.com/16485279/44440581-566a9500-a5fb-11e8-8bb6-1640d5f8c32f.png">
初始需求是，上图中的四个图例，我只想展示部分的，比如2017和2018.但是没有发现入口，我就打算修改图例的文字和颜色的大小
<img width="736" alt="211c3dd4-444d-4c49-b08b-2264c5fa3de7" src="https://user-images.githubusercontent.com/16485279/44440634-8d40ab00-a5fb-11e8-9ea6-44f1f2aead39.png">这是我设置图例样式的代码，但是运行后，图例还是默认的字体和颜色。

**Comment by AAChartModel** [comment]
@topws 请直接贴上代码的文本,而不是代码图片.贴代码图片累死人不说,还容易出错,何况你这也不是 AAOptions 代码的全部内容吧

**Comment by AAChartModel** [comment]
如果需要代码格式化高亮, GitHub 评论默认是支持 markdown 语法的,直接使用 markdown 语法格式化高亮就好了

**Comment by topws** [comment]
@AAChartModel 以下是代码片段，但是X和Y轴的都是数组内容，网络取来的，我就不放上去了，大神你费点斤随便写两个假数据。
//提示框样式
	AATooltip *aaTooltip = AAObject(AATooltip).sharedSet(true).enabledSet(true);
	aaTooltip.backgroundColor = @"#1E59F5";
	aaTooltip.borderColor = @"#1E59F5";
	aaTooltip.borderRadius = @(4);
	aaTooltip.style = @{@"color":@"#FFFFFF",
						@"fontSize":@"9px",};
	//图例样式
	AAItemStyle *aaItemStyle = AAObject(AAItemStyle)
	.colorSet(@"#C2C2C2")
//	.cursorSet(@"pointer")
	.fontSizeSet(@"9px")
	.fontWeightSet(AAChartFontWeightTypeBold);//字体为细体字
	
	AAOptions *chartOptions = AAObject(AAOptions);
	chartOptions.title = aaTitle;
	chartOptions.yAxis = (id)yAxisArr;
	chartOptions.xAxis = xAxis;
	chartOptions.tooltip = aaTooltip;
	chartOptions.legend.itemStyle = aaItemStyle;

	if ([self getArfterDigitZeroCount:priceYArr.firstObject] > 5) {
		chartOptions.tooltip.valueDecimals = @9;
		chartOptions.plotOptions.area.dataLabels.format = @"{point.y:.9f}";
	}

	chartOptions.series = aaSeries;
	AAChart *aaChart = AAObject(AAChart)
	.backgroundColorSet(@"rgba(0,0,0,0)");
	chartOptions.chart = aaChart;

**Comment by topws** [comment]
另，其实我的原始需求，就是2017，2018，2019三个图例，只展示2017，2018这两个图例的需求还是希望能解答下，是否是不支持。我highcharts哪里搜了下，iusse也没有提及到我这个问题。。。

**Comment by AAChartModel** [comment]
现在已经为 AASeriesElement 添加了一个新的属性`showInLegend`,你更新下载一下 AAChartKit至最新版.再查看我新开的 issue #399

**Comment by topws** [comment]
@AAChartModel 真的非常的靠谱！！！给你点赞！
PS：我更改legend的样式的代码为啥是无效的？是我的写法有问题吗？

**Comment by AAChartModel** [comment]
```objective-c
	chartOptions.legend.itemStyle = aaItemStyle;
```
你这样直接给 option 的 legend 属性赋值,问题是你的 legend 对象这时候是 `nil` 啊

**Comment by topws** [comment]
疏忽了。。。贴上创建一个新图例的完整代码，部分值不设置会不显示
AALegend *aaLegend = AAObject(AALegend)
	.itemStyleSet(aaItemStyle)
	.enabledSet(true)
	.layoutSet(AALegendLayoutTypeHorizontal)
	.alignSet(AALegendAlignTypeCenter)
	.itemMarginTopSet(@(2));
