### ISSUE TITLE
打包的时候A parameter list without types is only allowed in a function definition

### ISSUE THREAD

**Issue by afunnyrainman** [AAChartModel/AAChartKit#389]
请问 打包的时候出现这个A parameter list without types is only allowed in a function definition错误是为什么。网上说Apple LLVM 6.1 - Language设置C Language Dialect为Compiler Default或者GNU99[-std=gnu99]，设置了还是不管用。

**Comment by AAChartModel** [comment]
你确定这个问题是由于AAChartKit导致的?没有遇到过啊!!!

**Comment by afunnyrainman** [comment]
首先谢谢您这么快的回复信息，我debug不会出现但是
![a3006f5a-aa6c-46a0-8f27-c0558983ca97](https://user-images.githubusercontent.com/22904462/44021866-7d8f4a5c-9f18-11e8-8807-5a87c10ca37a.png)我签名的时候确实出现了这个问题，而且也确实的指向了AAChartKitLib路径下的AAStyle。

**Comment by AAChartModel** [comment]
## 使用方法

### 准备工作
1. 将项目`Demo`中的文件夹`AAChartKitLib`拖入到所需项目中.
1. 在你的项目的 `.pch` 全局宏定义文件中添加
```objective-c
#import "AAGlobalMacro.h"
```


请问你如我所言,在你的项目的.pch文件中导入了`AAGlobalMacro.h`这个宏的头文件吗?

**Comment by AAChartModel** [comment]
因为你的这个提示错误信息,只要我在AAChartKit的demo中,将.pch文件的
```objective-c
#import "AAGlobalMacro.h"
```
注释掉,就会完全重现啊

**Comment by afunnyrainman** [comment]
哦！！对不起，我pch设置只设置了debug的，忘记了设置签名的。

**Comment by afunnyrainman** [comment]
谢谢您!

**Comment by AAChartModel** [comment]
找到问题了就好!!!🙂

**Comment by AAChartModel** [comment]
另外我想吐槽一下你的项目的文件名用**汉语拼音**的命名方式这样不太好吧,话说这样会给维护项目的后来人带来歧义和困扰吧.况且耶不利于项目的国际化推广啊(手动狗头)!!!
从前我也是有的变量名不知道中文所对应的英文单词,偷懒就直接用拼音,后来随着经验的积累,越发的觉得不妥.有时间还是尽量用英文来进行项目文件的命名吧.

            -----------------------来自MarkDown程序员的真诚建议(滑稽)

**Comment by afunnyrainman** [comment]
好的，谢谢您的经验。

**Comment by AAChartModel** [comment]
看你的仓库列表,你主要是玩的安卓这一块的吗?iOS开发只是副业?后续我有安卓方面的问题可否请教?
