### ISSUE TITLE
同一个X坐标对应不同Y值或者两个X值挨的太近，点的标记不显示

### ISSUE THREAD

**Issue by huangzhengguo** [AAChartModel/AAChartKit#392]
![img_1841](https://user-images.githubusercontent.com/20478851/44127014-c928189e-a06d-11e8-8440-47026d202756.PNG)
我这个横坐标数据较多，一天24小时，每分钟占一个点，两个点离的太近的话标记就不显示了，只有点击的时候显示

我的项目是下面的，可能中间会需要绘制垂直的线
![img_1844](https://user-images.githubusercontent.com/20478851/44127246-0cbee230-a06f-11e8-9db9-6c5cff35799f.PNG)

**Comment by AAChartModel** [comment]
这是highcharts官网关于marker数据点的相关文档
https://api.hcharts.cn/highcharts#plotOptions.series.marker

似乎并没有找到数据过于密集的情况下,还能显示marker数据点的相关信息
