### ISSUE TITLE
x轴数据显示不完整

### ISSUE THREAD

**Issue by Vutumn** [AAChartModel/AAChartKit#393]
```swift
chartModel.categories = ["00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00"]
```
我的category设置如上，然后显示出来如下

![image](https://user-images.githubusercontent.com/7233176/44129975-d22b3826-a07d-11e8-8812-b170b29e4224.png)

第一条数据直接显示省略号了

**Comment by AAChartModel** [comment]
我设置
```objective-c
    _aaChartModel.categories = @[@"00:00", @"01:00", @"02:00", @"03:00", @"04:00", @"05:00", @"06:00", @"07:00", @"08:00", @"09:00", @"10:00", @"11:00", @"12:00", @"13:00", @"14:00", @"15:00", @"16:00", @"17:00", @"18:00", @"19:00", @"20:00", @"21:00", @"22:00", @"23:00"];//设置 X 轴坐标文字内容
```

并未复现你的问题

请贴上你的完整代码

**Comment by Vutumn** [comment]
我刚测试了，是因为我给他们添加了空值nil，导致y轴距离左边没有空间可以让00:00显示，我赋值0就显示出来了

**Comment by Vutumn** [comment]
上图
![image](https://user-images.githubusercontent.com/7233176/44130607-e91deef4-a080-11e8-83d1-7e710da9a8b8.png)
![Uploading BF54366F-1E7A-46FD-8290-0A81C01E6B32.png…]()

**Comment by Vutumn** [comment]
![image](https://user-images.githubusercontent.com/7233176/44130824-f61f3d46-a081-11e8-8b2c-c4e3ce1d54e8.png)

**Comment by Vutumn** [comment]
现在我就像让下面显示完全，然后不显示数据，因为数据源可能是空值

**Comment by AAChartModel** [comment]
>  现在我就想让x轴显示完全，然后不显示y轴数据，因为数据源可能是空值，不知道是否可以把x轴的数据往右边移一点

说实话你这段话看的我很费解

**Comment by Vutumn** [comment]
我的意思是我想让第二图的x轴变成第一张图的x轴

**Comment by AAChartModel** [comment]
> 我刚测试了，是因为我给他们添加了空值nil，导致y轴距离左边没有空间可以让00:00显示，我赋值0就显示出来了

你不是已经解决了这个X轴的显示问题了吗?

> 第二图的x轴变成第一张图的x轴

???

**Comment by Vutumn** [comment]
没解决啊，你仔细看下，第一张图y轴是给了数据的，所以y轴距离左边有点距离，能让x轴第一条数据完整显示出来，第二张图y轴我传的是nil，所以y轴没有数据，导致y轴距离左边很近，所以x轴第一条数据没有位置显示，才显示省略号。我只是找到了原因。不知道我这样说你能否理解。

**Comment by AAChartModel** [comment]
所以说你觉得你在没有说明这些问题,直接贴上两张图,没有任何注释,让人直接猜能猜到你要表达的内容吗?

> 第二张图y轴我传的是nil

我也不知道你具体是什么情况,你能直接把你出现问题的代码贴出来吗?

**Comment by Vutumn** [comment]
chartModel = AAChartModel()
        chartModel.chartType = AAChartTypeLine
        chartModel.title = ""
        chartModel.subtitle = ""
     
        chartModel.yAxisTitle = ""
        chartModel.yAxisGridLineWidth = 0
       // chartModel.legendEnabled = false
        chartModel.colorsTheme = ["#fe117c","#ffc069","#06caf4","#7dffc0"]
        chartModel.connectNulls = false

chartModel.categories = ["00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00"]
        let defaultData = AASeriesElement()
        defaultData.name = "今日"
        var dataArray: [Any] = []
        for _ in 0...chartModel.categories.count - 1 {
            dataArray.append(NSNull())
        }
        defaultData.data = dataArray
        chartModel.series = [defaultData]

**Comment by Vutumn** [comment]
用swift写的，基本设置都是一样。出现问题的原因就是在于nsnull那一段

**Comment by AAChartModel** [comment]
你的swift的这部分代码,用OC些差不多就是这样
```objective-c
 AAChartModel *aaChartModel= AAObject(AAChartModel)
    .chartTypeSet(AAChartTypeColumn)//图表类型
    .titleSet(@"")//图表主标题
    .subtitleSet(@"")//图表副标题
    .colorsThemeSet(@[@"#fe117c",@"#ffc069",@"#06caf4",@"#7dffc0"])//设置主体颜色数组
    .yAxisTitleSet(@"")//设置 Y 轴标题
    .categoriesSet(@[@"00:00", @"01:00", @"02:00",
                     @"03:00", @"04:00", @"05:00",
                     @"06:00", @"07:00", @"08:00",
                     @"09:00", @"10:00", @"11:00",
                     @"12:00", @"13:00", @"14:00",
                     @"15:00", @"16:00", @"17:00",
                     @"18:00", @"19:00", @"20:00",
                     @"21:00", @"22:00", @"23:00"])
    .seriesSet(@[
                 AAObject(AASeriesElement)
                 .nameSet(@"2017")
                 .dataSet(@[[NSNull null], [NSNull null], [NSNull null],
                            [NSNull null], [NSNull null], [NSNull null],
                            [NSNull null], [NSNull null], [NSNull null],
                            [NSNull null], [NSNull null], [NSNull null],
                            [NSNull null], [NSNull null], [NSNull null],
                            [NSNull null], [NSNull null], [NSNull null],
                            [NSNull null], [NSNull null], [NSNull null],
                            [NSNull null], [NSNull null], [NSNull null],]),
                 ]
               );
 
```

**Comment by Vutumn** [comment]
是啊，不知道你那边是否复现了这个问题

**Comment by AAChartModel** [comment]
给AAChartKit的这部分代码
```objective-c
    AAChart *aaChart = AAObject(AAChart)
    .typeSet(aaChartModel.chartType)//绘图类型
    .invertedSet(aaChartModel.inverted)//设置是否反转坐标轴，使X轴垂直，Y轴水平。 如果值为 true，则 x 轴默认是 倒置 的。 如果图表中出现条形图系列，则会自动反转
    .backgroundColorSet(aaChartModel.backgroundColor)//设置图表的背景色(包含透明度的设置)
    .pinchTypeSet(aaChartModel.zoomType)//设置手势缩放方向
    .panningSet(true)//设置手势缩放后是否可平移
    .polarSet(aaChartModel.polar);
```
加上一句
```
    .marginLeftSet(@30)//❤️❤️❤️设置图标左侧边距❤️❤️❤️

```

变成
```objective-c
    AAChart *aaChart = AAObject(AAChart)
    .marginLeftSet(@30)//❤️❤️❤️设置图标左侧边距❤️❤️❤️
    .typeSet(aaChartModel.chartType)//绘图类型
    .invertedSet(aaChartModel.inverted)//设置是否反转坐标轴，使X轴垂直，Y轴水平。 如果值为 true，则 x 轴默认是 倒置 的。 如果图表中出现条形图系列，则会自动反转
    .backgroundColorSet(aaChartModel.backgroundColor)//设置图表的背景色(包含透明度的设置)
    .pinchTypeSet(aaChartModel.zoomType)//设置手势缩放方向
    .panningSet(true)//设置手势缩放后是否可平移
    .polarSet(aaChartModel.polar);
```

即可.

`marginLeft`这个属性就是用来给图表设置左侧边距的

**Comment by AAChartModel** [comment]
通过AAOptions对象来构建图表的配置项,属性更多,自由度更高.因为AAChartModel其实还是要转成AAOptions对象.之所以有AAChartModel是为了简化配置.因为直接配置AAOptions相对繁琐,容易出错

**Comment by AAChartModel** [comment]
下次再有问题,请务必讲问题描述清楚,配合实际代码和图片更好.不然你让我光靠猜来理解你的意思,实在是太困难了!!!

**Comment by Vutumn** [comment]
主要从很久之前开始用了，习惯直接用model了，现在用options，虽然可配置的对象多了，但是繁琐，我日常也一般也用不到，就一直用model了

**Comment by Vutumn** [comment]
哈哈，好的下次一定注意，也是我太着急了，没想明白就直接表述出来了
