### ISSUE TITLE
一个柱子以某个值为界限，分为两种不同颜色

### ISSUE THREAD

**Issue by dagundejuzi** [AAChartModel/AAChartKit#395]
RT，是否可达到这种效果？
![image](https://user-images.githubusercontent.com/16382880/44379089-f4e0f280-a536-11e8-8eac-36b5632584b0.png)

**Comment by dagundejuzi** [comment]
在官网找到了negativeColor，在 AAchart 里要怎么设置？

**Comment by dagundejuzi** [comment]
抱歉，新版有了。使用柱形范围图+阈值标示线 大概能出这样的形状，但是 1、数据点的数据不显示，2、negativeColor的颜色，只要柱状有低于阈值的，整个柱状都会变色。如图
![image](https://user-images.githubusercontent.com/16382880/44388954-228c6280-a55c-11e8-8f74-76e6d2416c7d.png)
如果使用基准线以下异色混合图（demo 中的negativeColorMixed ） 2组数据来拼图，两组的柱形会错开。（图片一直传不上来 。。。）

**Comment by dagundejuzi** [comment]
![e52c0e97-6450-472b-b05b-85deca17702e](https://user-images.githubusercontent.com/16382880/44390996-443c1880-a561-11e8-9a0b-15ab2ea51cc0.jpeg)

**Comment by AAChartModel** [comment]
你这算是完成了吗?

**Comment by dagundejuzi** [comment]
没有，最前面的图是要的效果，后面两个是我尝试的效果，都不行。

**Comment by AAChartModel** [comment]
后面我有时间尝试着弄一下看看,你的这个设计稿和 Highcharts 默认样式出入确实比较大

**Comment by dagundejuzi** [comment]
打算先用其他图表来显示。然后，这种组内数据间的间隙怎么去掉？
![f07067d5423c6d55db23e8826d97bd6c](https://user-images.githubusercontent.com/16382880/46064558-474ea800-c1a2-11e8-9da0-9954fd354ad3.png)

**Comment by AAChartModel** [comment]
你要求的这个效果好像Swift 版本的库倒是蛮符合的

![](https://github.com/i-schuetz/SwiftCharts/raw/master/Screenshots/IMG_0027.jpeg)

你可以试试这个是否可行,而且这个是原生的库,性能可能更好,不过是 Swift 写的, OC 项目中如果使用的话需要混编桥接

**Comment by dagundejuzi** [comment]
换的话……它和charts 哪个好点？
另外，在 highcharts 里找到一个 zones ，这个估计可以实现效果了。

**Comment by AAChartModel** [comment]
参见双 Y 轴镜像效果图表  https://github.com/AAChartModel/AAChartKit/issues/759#issuecomment-544848782

**Comment by AAChartModel** [comment]
## Landscape
![image](https://user-images.githubusercontent.com/16357599/66562001-3a261080-eb8d-11e9-9972-8dc78da1e7ae.png)

## Protrait
![image](https://user-images.githubusercontent.com/16357599/66562264-d51eea80-eb8d-11e9-9d6e-fad7d4467f4c.png)
