### ISSUE TITLE
找不到aachartview.html文件

### ISSUE THREAD

**Issue by gerrywg** [AAChartModel/AAChartKit#398]
在使用Pod导入后, 
- (NSURLRequest *)getJavaScriptFileURLRequest {
    NSString *webPath = [[NSBundle mainBundle] pathForResource:@"AAChartView" ofType:@"html"];
    NSURL *webURL = [NSURL fileURLWithPath:webPath];
    NSURLRequest *URLRequest = [[NSURLRequest alloc] initWithURL:webURL];
    return URLRequest;
}

这里执行会出错，找不到这个html文件，在pod里面看了一下是有的

**Comment by gerrywg** [comment]
![2018-08-22 2 39 36](https://user-images.githubusercontent.com/17895936/44446948-3f3aa000-a619-11e8-83a7-1cb3c37a0bba.png)
出错的图如上面附件

**Comment by AAChartModel** [comment]
暂不支持 Cocoapods 导入,我在 README 中没有写能够支持 Cocoapods 导入的相关内容吧

**Comment by lijiangg** [comment]
我也遇到了这个问题  还好看到这里。。。 麻烦作者在readme里面加上暂不支持cocoapods导入吧 真的让人难受

**Comment by AAChartModel** [comment]
AAChartKit 现已支持 Cocoapods 导入, 具体内容参见 README 文档
