### ISSUE TITLE
iOS 8.4的不能用的呀

### ISSUE THREAD

**Issue by PerHao** [AAChartModel/AAChartKit#4]
demo不能在iOS 8.4上运行，这个可以适配iOS 7吗？

**Comment by AAChartModel** [comment]
兄弟,你确定真的是这样的情况,我在 iOS 8.1的系统上(模拟器)运行都是正常的啊!!!

**Comment by PerHao** [comment]
我的8.4的真机就不能正常显示，折线图那一片区域是白的，然后我的其他设备都是正常的，我这也只有一台8.4的测试机，其余的都没问题，你这样说我就不确定了，因为我的测试机越狱了

**Comment by AAChartModel** [comment]
兄弟不是很急吧?容我回去再找真机测试看看,希望能尽力解决你的问题.

**Comment by PerHao** [comment]
谢啦，回头我再找别的真机试试

**Comment by AAChartModel** [comment]
因为我在自己的公司项目中使用的也是这套代码,希望能互相扶持吧!

**Comment by AAChartModel** [comment]
问题找到了,是条件编译的时候遇到的问题,现已修正,你将文件 AAGlobalMacro. h和AAChartView.m 中的__IPHONE_OS_VERSION_MAX_ALLOWED修改为__IPHONE_OS_VERSION_MIN_REQUIRED,编译运行一下就可以了.

**Comment by PerHao** [comment]
非常感谢
