### ISSUE TITLE
请问AAChartTypePie 扇形图每个扇区颜色如何设置

### ISSUE THREAD

**Issue by dlhub** [AAChartModel/AAChartKit#40]
AAChartTypePie 中 colorsThemeSet 不能控制每个扇区的颜色，应该如何设置？

**Comment by AAChartModel** [comment]
设置图表的主题颜色,数组内容必须为如下这样的的十六进制字符串颜色数组
```objective-c
 .colorsThemeSet(@[@"#b5282a",@"#e7a701",@"#50c18d",@"#fd4800",@"#f1c6c5"])
```

**Comment by dlhub** [comment]
可能我没描述清楚。我说的是 Pie Chart 扇形图 这种类型。Demo没有给出样例如何修改颜色。全是红色的。
@[
                     AAObject(AASeriesElement)
                     .nameSet(@"语言热度占比")
                     .innerSizeSet(@"35%")
                     .dataSet(@[
                                @[@"Java"  , @67],
                                @[@"Swift" , @44],
                                @[@"Python", @83],
                                @[@"OC"    , @11],
                                @[@"Ruby"  , @42],
                                @[@"PHP"   , @31],
                                @[@"Go"    , @63],
                                @[@"C"     , @24],
                                @[@"C#"    , @888],
                                @[@"C++"   , @66],
                                ]),
                     ]
                   )
比如我需要各种开发语言颜色不一样，如修改 Swift 为其它颜色。请教我应该怎么做，谢谢！
