### ISSUE TITLE
急需指点下

### ISSUE THREAD

**Issue by flyOfYW** [AAChartModel/AAChartKit#403]
为什么X抽上，我只想显示周一至周日，我设置了，但是为啥周日之后还多个7、8、9、10、11

**Comment by AAChartModel** [comment]
你的 Series 数据源应该不对,最好直接贴上你的有问题的代码,你这样没来由的瞎问,是不可能知道具体问题的

**Comment by flyOfYW** [comment]
@AAChartModel  if (self.chartType == SecondeViewControllerChartTypeArea
               || self.chartType == SecondeViewControllerChartTypeAreaspline) {
        _aaChartModel.categories = @[@"周一",@"周2",@"周3",@"周4",@"周5",@"周6",@"周7"];
        _aaChartModel.symbolStyle = AAChartSymbolStyleTypeBorderBlank;//设置折线连接点样式为:内部白色
        _aaChartModel.gradientColorEnabled = true;//启用渐变色
        _aaChartModel.xAxisTickInterval = @1;
        _aaChartModel.xAxisCrosshairWidth = @1;//Zero width to disable crosshair by default
        _aaChartModel.xAxisCrosshairColor = @"#FFE4C4";//(浓汤)乳脂,番茄色准星线
        _aaChartModel.xAxisCrosshairDashStyleType = AALineDashSyleTypeSolid;

**Comment by AAChartModel** [comment]
你关键的数据源AASeriesElement 中的 data 数组呢?

**Comment by AAChartModel** [comment]
你是直接在 AAChartKit 的 demo 中添加测试数据改的吧?

**Comment by flyOfYW** [comment]
是的，AASeriesElement那里没改

**Comment by AAChartModel** [comment]
demo 中的

```objective-c
                 AAObject(AASeriesElement)
                 .nameSet(@"2017")
                 .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6]),
```

数据源数组明显是九个, category 数组个数理应相等,才能在图表视图上呈现出一一对应的关系.这个问题的原因应该很明显吧

**Comment by flyOfYW** [comment]
明白了，seriesSet是控制列的

**Comment by AAChartModel** [comment]
附言:   

> 急需指点下

这种文字真的适合用来给 issue作为标题吗?

**Comment by flyOfYW** [comment]
不好意思，因为急着赶项目，没来得及看文档
