### ISSUE TITLE
Pie Chart 扇形图 设置颜色

### ISSUE THREAD

**Issue by dlhub** [AAChartModel/AAChartKit#41]
Pie Chart 扇形图 设置颜色。Demo没有给出样例如何修改颜色。全是红色的。
   AAChartModel *chartModel= AAObject(AAChartModel)
        .chartTypeSet(AAChartTypePie)
        .titleSet(@"编程语言热度")
        .subtitleSet(@"虚拟数据")
        .dataLabelEnabledSet(true)//是否直接显示扇形图数据
        .yAxisTitleSet(@"摄氏度")
        .seriesSet(
                   @[
                     AAObject(AASeriesElement)
                     .nameSet(@"语言热度占比")
                     .innerSizeSet(@"35%")
                     .dataSet(@[
                                @[@"Java"  , @67],
                                @[@"Swift" , @44],
                                @[@"Python", @83],
                                @[@"OC"    , @11],
                                @[@"Ruby"  , @42],
                                @[@"PHP"   , @31],
                                @[@"Go"    , @63],
                                @[@"C"     , @24],
                                @[@"C#"    , @888],
                                @[@"C++"   , @66],
                                ]),
                     ]
                   )
        ;
比如我需要各种开发语言颜色不一样，如修改 Swift 为其它颜色。请教我应该怎么做，谢谢！

**Comment by AAChartModel** [comment]
感谢提醒,因在某一次版本更新中增加了新特性影响到扇形图的主题颜色设置功能了☹️,现已修复此问题,题主可更新`AAChartKit`的测试示例 DEMO 重新查看效果,如再有问题,可及时沟通😝.

**Comment by dlhub** [comment]
非常感谢你的回答，版主真是及时雨，谢谢提供好用的图表控件！👍

**Comment by AAChartModel** [comment]
(🌺🌺🌺)好说好说,后续的持久改进和优化离不开诸位的支持呢!(🌺🌺🌺)
