### ISSUE TITLE
折线图中 :datalabel 文字修改(不是修改字体大小颜色)

### ISSUE THREAD

**Issue by lunaWARE** [AAChartModel/AAChartKit#424]
我想给每个点增加一个字段 ,显示时 dataLabel 内容可以由拼接新的字符串 怎么修改
那个 keys 怎么用?数组里边放字符串还是数字?是每个点对应一个 key 么?

**Comment by lunaWARE** [comment]
补充下:想在 lineChart 中使用

**Comment by lunaWARE** [comment]
恩..这问题我自己解决了🤦‍♀️

不过keys 值设置的 还是不太懂,大佬看到给讲一下吧,谢啦~

**Comment by a123478we** [comment]
这个问题你怎么解决的？

**Comment by lunaWARE** [comment]
我当时是需要显示横纵坐标的值,修改了formatSet样式.
.dataLabelsSet(
      AAObject(AADataLabels)
                                            .enabledSet(YES)
                                            .allowOverlapSet(YES)
                                            .styleSet(AAObject(AAStyle)
                                                      .colorSet(@"#4A4A4A")
                                                      .fontSizeSet(@"14px")
                                                      .fontWeightSet(@"thin")
                                                      )
                                            .formatSet(@"{point.name}  {point.y}"))
