### ISSUE TITLE
设置chartView了背景颜色，xcode看了一下层级在最下面一层，怎么设置顶层的背景颜色呢？

### ISSUE THREAD

**Issue by 2952883085** [AAChartModel/AAChartKit#429]

**Comment by AAChartModel** [comment]
颜色在最底层和最上层有什么区别么?

**Comment by 2952883085** [comment]
我这个想给chartView加个背景图片，如果在最顶层我可以直接给self.view设置背景，将chartView背景设置成透明就可以实现效果了，现在在最底层实现不了呀

**Comment by 2952883085** [comment]
你好大神，刚看到了一个设置透明的属性，我试下看看

**Comment by AAChartModel** [comment]
AAChartKit 的 Demo 中有添加背景图片的图表示例,你可以看看是不是你要的效果

**Comment by 2952883085** [comment]
好的，谢谢了哈
