### ISSUE TITLE
JavaScript 异常

### ISSUE THREAD

**Issue by Eesnh** [AAChartModel/AAChartKit#43]
控制台打印出这个错误，这个是什么原因，求告知 
WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______Error Domain=WKErrorDomain Code=4 "发生 JavaScript 异常" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: loadTheHighChartView, WKJavaScriptExceptionSourceURL=about:blank, NSLocalizedDescription=发生 JavaScript 异常, WKJavaScriptExceptionColumnNumber=21}

**Comment by AAChartModel** [comment]
错误信息中的关键语句
```
Can't find variable: loadTheHighChartView
```
这种错误是指未找到 OC 想要调用的名为`loadTheHighChartView `这个JavaScript方法

**Comment by AAChartModel** [comment]
你是改动了我的`AAChartView.html`源文件 中的代码么?下载最新的 `DEMO` ,运行并无异常啊!如若你的代码不是最新的,请更新`DEMO`重新运行试试.如有问题,可再向我咨询😝.

**Comment by Eesnh** [comment]
是最新的呀，用cocoapods导入的，无法获取那些html文件

**Comment by AAChartModel** [comment]
换成`README.md`文档中的手动导入吧,之前的项目的 `cocoapods` 配置有些许问题.手动导入亲测可用.
