### ISSUE TITLE
使用填充折线图 点击tip提示图数据，底部多出一个阴影

### ISSUE THREAD

**Issue by leon11307322** [AAChartModel/AAChartKit#430]
楼主大大，想请教个问题，使用填充折线图的时候，设置了tooltipEnabledSet后，点击某一个tip提示图数据，底部y轴的方向还有一个竖向条状阴影，可以去掉的吗，没有看到开放出来的字段呀

**Comment by AAChartModel** [comment]
> 底部y轴的方向还有一个竖向条状阴影

这个阴影是准星线 crosshair, 修改 crosshair 的宽度为 0 即可隐藏准星线
