### ISSUE TITLE
AAChartTypePie类型的饼图，图表主题颜色数组设置无效

### ISSUE THREAD

**Issue by sgmorals** [AAChartModel/AAChartKit#434]
.colorsThemeSet(@[@"#0c9674",@"#7dffc0",@"#d11b5f",@"#facd32",@"#ffffa0",@"#EA007B"])

**Comment by AAChartModel** [comment]
重复问题,参见 #428

**Comment by sgmorals** [comment]
扇形图，这里扇形设置颜色无效 



        AAChartModel *aaChartModel= AAObject(AAChartModel)
        .chartTypeSet(AAChartTypePie)
        .colorsThemeSet(@[@"#0c9674",@"#7dffc0",@"#d11b5f",@"#facd32",@"#ffffa0",@"#EA007B"])
        .titleSet(@"")
        .subtitleSet(@"")
        .dataLabelEnabledSet(true)//是否直接显示扇形图数据
        .yAxisTitleSet(@"摄氏度")
        .seriesSet(
                   @[
                     AAObject(AASeriesElement)
                     .nameSet(@"语言热度值")
                     .innerSizeSet(@"20%")//内部圆环半径大小占比
                     .sizeSet(@300)//尺寸大小
                     .borderWidthSet(@0)//描边的宽度
                     .allowPointSelectSet(false)//是否允许在点击数据点标记(扇形图点击选中的块发生位移)
                     .statesSet(@{@"hover": @{@"enabled": @(bool_false)}})//禁用点击区块之后出现的半透明遮罩层 (先定义bool变量的原因是，直接用true，false，处理完成之后容易变成0或者1。https://www.cnblogs.com/haojuncong/p/4652998.html )
                     .dataSet(
                              @[
                                @[@"Firefox",   @3336.2],
                                @[@"IE",        @26.8],
                                @{
                                    @"name":@"Chrome",
                                    @"y":@100.8,
                                    @"sliced":@(true),
                                    @"selected":@(true)
                                    },
                                @[@"Safari",    @88.5],
                                @[@"Opera",     @46.0],
                                @[@"Others",    @223]
                                ]
                              ),
                     ]
                   )
        ;

**Comment by AAChartModel** [comment]
>  当图表为扇形图时,设置 `AASeriesElement` 的属性 `colorByPoint` 为 `YES`即可


看清这里的描述,Model 模型是 **AASeriesElement**

而且属性是 **ColorByPoint**

一下能看错两个英文单词,你是怎么做到的? 😅

**Comment by sgmorals** [comment]
已解决，谢谢大佬
