### ISSUE TITLE
希望后期加入pod 管理

### ISSUE THREAD

**Issue by EliYenn** [AAChartModel/AAChartKit#44]

**Comment by wanshaofeng001** [comment]
-> AAChartKit (2.1.6)
   An elegant and friendly chart library for iOS developer
   pod 'AAChartKit', '~> 2.1.6'
   - Homepage: https://github.com/AAChartModel/AAChartKit
   - Source:   https://github.com/AAChartModel/AAChartKit.git
   - Versions: 2.1.6, 2.1.5, 2.1.2, 2.1.0, 2.0.9, 2.0.8, 2.0.7, 2.0.2, 2.0.1, 2.0.0 [master repo]

**Comment by wanshaofeng001** [comment]
pod search AAChartKit
就找到了

**Comment by AAChartModel** [comment]
找到了是没错,但是是有问题的, pod 导入的 AAChartView 无法加载 HTML 文件😢

**Comment by AAChartModel** [comment]
已支持`CocoaPods`导入`AAChartKit`,详细信息参见 **README** 文档
