### ISSUE TITLE
如何去掉条形图的点击效果

### ISSUE THREAD

**Issue by fengjuxiangwan** [AAChartModel/AAChartKit#442]
点击的时候 提示框可以去掉。。但是怎么去掉背景颜色变化

**Comment by AAChartModel** [comment]
参见问题 #822

**Comment by AAChartModel** [comment]
修改 AASelect 的 enable 属性为 false 即可, 就像这样

```objc

```- (AAChartModel *)customBarChartSelectColor {
    return AAChartModel.new
    .chartTypeSet(AAChartTypeBar)
    .titleSet(@"Custom Bar Chart select color")
    .yAxisTitleSet(@"")
    .yAxisReversedSet(true)
    .xAxisReversedSet(true)
    .easyGradientColorsSet(true)
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"ElementOne")
        .dataSet(@[@211,@183,@157,@133,@111,@91,@73,@57,@43,@31,@21,@13,@7,@3])
        .allowPointSelectSet(YES)
        .statesSet(AAStates.new
                   .selectSet(AASelect.new
                              .enableSet(false)
                              ))
    ]);
}

**Comment by AAChartModel** [comment]
参考在线文档 https://api.highcharts.com.cn/en/highcharts/series.column.states.select.enabled.html

**Comment by cuiyu8580** [comment]
你好！这个AASelect下面就没有enable这个属性？是要我们自己实现的吗，这个下面只有这三个
@implementation AASelect
AAPropSetFuncImplementation(AASelect, NSString *, borderColor)
AAPropSetFuncImplementation(AASelect, NSString *, color)
AAPropSetFuncImplementation(AASelect, AAHalo *, halo)
@end

**Comment by tipshot** [comment]
> 你好！这个AASelect下面就没有enable这个属性？是要我们自己实现的吗，这个下面只有这三个
> 
> ```objc
> @implementation AASelect
> AAPropSetFuncImplementation(AASelect, NSString *, borderColor)
> AAPropSetFuncImplementation(AASelect, NSString *, color)
> AAPropSetFuncImplementation(AASelect, AAHalo *, halo)
> @end
> ```

同样的疑问

**Comment by AAChartModel** [comment]
按照 README 文档中所述,不指定 AAChartKit 版本,更新 AAChartKit 的 pod 到最新内容即可

**Comment by AAChartModel** [comment]
```objc

@interface AASelect : NSObject

AAPropStatementAndPropSetFuncStatement(assign, AASelect, BOOL,       enabled)
AAPropStatementAndPropSetFuncStatement(copy,   AASelect, NSString *, borderColor)
AAPropStatementAndPropSetFuncStatement(copy,   AASelect, NSString *, color)
AAPropStatementAndPropSetFuncStatement(strong, AASelect, AAHalo   *, halo)

@end
```

已为 AASelect 新增属性 enabled ,默认为 true

```objc
@implementation AASelect

- (instancetype)init {
    self = [super init];
    if (self) {
        _enabled = true;
    }
    return self;
}
```

如上所述, 更新 AAChartKit 的 pod 到最新内容即可
