### ISSUE TITLE
折线图  上不能显示小数吗？

### ISSUE THREAD

**Issue by hudong0714** [AAChartModel/AAChartKit#443]
比如30.5  显示错误

**Comment by AAChartModel** [comment]
谁说不可以的啊, demo 中不是有显示小数精度为九位数的图表示例吗?

把你显示错误的配置 AAChartModel 或者配置 AAOptions 的源代码贴出来看看

**Comment by hudong0714** [comment]
AAChartModel *ChartModel= AAObject(AAChartModel)
    .chartTypeSet(AAChartTypeLine)
    .zoomTypeSet(AAChartZoomTypeX)
    .symbolSet(@"circle")
    .markerRadiusSet(@4)
    .yAxisLabelsEnabledSet(YES)
    .tooltipValueSuffixSet(@"bpm")
    .titleSet(@"")
    .yAxisTitleSet(@"")
    .categoriesSet(self.dateArr)
    .legendEnabledSet(NO)
    .seriesSet(@[
                 AAObject(AASeriesElement)
                 .nameSet(@"体重")
                 .colorSet(@"#6ece74")
                 .dataSet(self.array_weight),
                 AAObject(AASeriesElement)
                 .nameSet(@"BMI")
                 .colorSet(@"#67d4ff")
                 .dataSet(self.array_bmi)
                 ])
    ;
[self.aaChartView aa_drawChartWithChartModel:ChartModel];

array_weight值为
        60, 
	60, 
	60, 
	60.1, 
	60.1, 
	60.1, 
	60.1, 
	52.4, 
	52.5, 
	60, 
	60, 
	60, 
	60,

**Comment by hudong0714** [comment]
![2018-09-18 10 46 38](https://user-images.githubusercontent.com/16092054/45661443-23e78580-bb30-11e8-83cf-9dfbf9f958cf.png)

**Comment by AAChartModel** [comment]
为什么我复现不了你的问题?

而且你看我的示例 demo 中的数据
```objective-c
@[
                 AAObject(AASeriesElement)
                 .nameSet(@"2017")
                 .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6]),
                 AAObject(AASeriesElement)
                 .nameSet(@"2018")
                 .dataSet(@[@0.2, @0.8, @5.7, @11.3, @17.0, @22.0, @24.8, @24.1, @20.1, @14.1, @8.6, @2.5]),
                 AAObject(AASeriesElement)
                 .nameSet(@"2019")
                 .dataSet(@[@0.9, @0.6, @3.5, @8.4, @13.5, @17.0, @18.6, @17.9, @14.3, @9.0, @3.9, @1.0]),
                 AAObject(AASeriesElement)
                 .nameSet(@"2020")
                 .dataSet(@[@3.9, @4.2, @5.7, @8.5, @11.9, @15.2, @17.0, @16.6, @14.2, @10.3, @6.6, @4.8])
                 ]
```

这里面不都是小数吗?也没看到有什么异常啊,恐怕帮不了你了

**Comment by hudong0714** [comment]
我把这个数组 写死 是可以正常显示的，但是从外部传进来这个数组 （同样数据）小数就会显示和上面截图一样。数组里放的NSNumber

**Comment by AAChartModel** [comment]
或许你可以将外部传进来的数组元素全部遍历一遍转换成 NSNumber 试试,可能是数据类型导致的数据精度问题
