### ISSUE TITLE
箱线图如何设置填充色？一个数据源如何设置2个不同的颜色？

### ISSUE THREAD

**Issue by sharks-cha** [AAChartModel/AAChartKit#446]
![image](https://user-images.githubusercontent.com/16301573/45922404-ddae6f80-befd-11e8-9a0e-6044259b0df5.png)
请问这样的效果如何实现？

**Comment by AAChartModel** [comment]
你这效果需要的是K线图,而不是箱线图吧?!

**Comment by sharks-cha** [comment]
但是我不需要单线图，只有这么一个效果，不知如何是好了。。。

**Comment by AAChartModel** [comment]
只有这个效果的话,建议你使用原生 Swift 写的图表库 Charts, 他的这个效果跟你要求的基本可以说是完全一致.不过是 Swift 写的,在 OC 项目中使用的话需要桥接.

![](https://camo.githubusercontent.com/6dbee4e35fde8691e5ac29417583dc8e16608895/68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d50416e64726f696443686172742f6d61737465722f73637265656e73686f74732f63616e646c65737469636b63686172742e706e67)

charts 传送门:
https://github.com/danielgindi/Charts

**Comment by sharks-cha** [comment]
好的，多谢
