### ISSUE TITLE
AAChartKit 使用 MIT 授权证书是否合理?

### ISSUE THREAD

**Issue by AAChartModel** [AAChartModel/AAChartKit#447]
由于 Highcharts 商业使用需要付费(个人和非商业用途免费),基于` Highcharts` 开发的`AAChartKit`第三方库开源在 GitHub 上,并使用 MIT 开源证书是否合理?与 Highcharts 官方的授权协议是否冲突?普通商业用户在将 `AAChartKit` 用于商业用途时,理论上用户是否有侵犯 Highcharts 版权的问题? `AAChartKit`原作者是否需要承担连带责任?

**Comment by DeliriousLee** [comment]
关注此问题一波

**Comment by buzheng1949** [comment]
关注

**Comment by zzyspace** [comment]
要跪... 得换库了
