### ISSUE TITLE
更新数据内容的aaChartModelSeriesArray是什么东西

### ISSUE THREAD

**Issue by a123478we** [AAChartModel/AAChartKit#450]
> Refresh the chart data (this method is recommended for updating the series data dynamically)
 ```objc
//Refresh the chart dynamically only when the series attribute of the AAChartModel object is updated
[_aaChartView aa_onlyRefreshTheChartDataWithChartModelSeries:aaChartModelSeriesArray];
```

aaChartModelSeriesArray是什么？一个包含字典的数组？

**Comment by AAChartModel** [comment]
是啊,怎么了?有什么问题吗?

**Comment by a123478we** [comment]
> 是啊,怎么了?有什么问题吗?

 [_chartView  aa_onlyRefreshTheChartDataWithChartModelSeries:@[ AAObject(AAChartModel)
            .seriesSet(@[
                          AAObject(AASeriesElement)
                          .nameSet(@"All")
                          .dataSet(@[])
                          ]) ]];

后面要传的是这样 ，还是什么？能举个例子吗？

**Comment by AAChartModel** [comment]
后面传

```objc
    NSArray *series = @[
                        @{@"name":@"2017",
                          @"type":@"bar",
                          @"data":@[@7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6]},
                        @{@"name":@"2018",
                          @"type":@"line",
                          @"data":@[@0.2, @0.8, @5.7, @11.3, @17.0, @22.0, @24.8, @24.1, @20.1, @14.1, @8.6, @2.5]},
                        ];
    
    [self.chartView aa_onlyRefreshTheChartDataWithChartModelSeries:series];
```

刷新的时候传入这种元素为字典的数组即可

**Comment by a123478we** [comment]
> 后面传
> 
> ```objc
>     NSArray *series = @[
>                         @{@"name":@"2017",
>                           @"type":@"bar",
>                           @"data":@[@7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6]},
>                         @{@"name":@"2018",
>                           @"type":@"line",
>                           @"data":@[@0.2, @0.8, @5.7, @11.3, @17.0, @22.0, @24.8, @24.1, @20.1, @14.1, @8.6, @2.5]},
>                         ];
>     
>     [self.chartView aa_onlyRefreshTheChartDataWithChartModelSeries:series];
> ```
> 
> 刷新的时候传入这种元素为字典的数组即可

不行，没有图表，是空的？

**Comment by a123478we** [comment]
能不能加个微信或者QQ啥的？

**Comment by AAChartModel** [comment]
你没有下载 demo 运行查看吗? demo 中有刷新图表数据的示例啊,柱状图,条形图,折线图,曲线图,折线填充图,曲线填充图的数据刷新的相关示例都有,你仔细看一下
