### ISSUE TITLE
legend图例中的左边图片可以修改吗？？

### ISSUE THREAD

**Issue by superlu88** [AAChartModel/AAChartKit#458]
<img width="267" alt="2018-10-11 11 15 05" src="https://user-images.githubusercontent.com/42953479/46778605-08deee80-cd47-11e8-939c-7532fa39ceee.png">
像上面这样显示方形的图片，不知道可不可以，怎么修改？？？

**Comment by AAChartModel** [comment]
恐怕不支持,这是Highcharts有关于legend图例的API文档 https://api.hcharts.cn/highcharts#legend    ,其中似乎并没有关于可以自定义为你图中要求的样式

**Comment by superlu88** [comment]
好的，谢谢

**Comment by AAChartModel** [comment]
我发现图例左边的点的形状大小是可以更改为方形的. 

参考 Legend 的这几个关键属性


[symbolHeight:](https://api.highcharts.com/highcharts/legend.symbolHeight)undefined
[symbolPadding:](https://api.highcharts.com/highcharts/legend.symbolPadding)5
[symbolRadius:](https://api.highcharts.com/highcharts/legend.symbolRadius)undefined
[symbolWidth:](https://api.highcharts.com/highcharts/legend.symbolWidth)undefined

类似于下面这样设置, 即可得到一个方形的 legend item

```js
Highcharts.chart('container', {

    chart: {
        type: 'column'
    },

    title: {
        text: 'Round legend symbols'
    },

    xAxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr']
    },

    legend: {
        symbolHeight: 12,
        symbolWidth: 12,
        symbolRadius: 0
    },

    series: [{
        data: [1, 3, 2, 4]
    }, {
        data: [6, 4, 5, 3]
    }, {
        data: [2, 7, 6, 5]
    }]

});

```

关键内容:

```js
    legend: {
        symbolHeight: 12,
        symbolWidth: 12,
        symbolRadius: 0
    },
```
