### ISSUE TITLE
禁用图例的点击效果怎么设置啊？？？

### ISSUE THREAD

**Issue by superlu88** [AAChartModel/AAChartKit#459]
问一下，oc这边应该怎么写啊？？aaOptions.plotOptions.series.events =？

**Comment by Victor1104** [comment]
请问知道怎么写了嘛？我试了好几种都不行

**Comment by Victor1104** [comment]
朋友  我知道咋写了`aaOptions.plotOptions.series.events = @{@"legendItemClick":@"false"};`希望对你还有用

**Comment by superlu88** [comment]
感谢，用了一下，效果可以。
