### ISSUE TITLE
图形单击事件回调

### ISSUE THREAD

**Issue by zhouzhou94alone** [AAChartModel/AAChartKit#471]
作者何时支持为图形添加单击的事件回调呢?非常需要,作者大大加油啊

**Comment by AAChartModel** [comment]
近期没有这方面的打算,如果你有这方面的需要,建议最好使用其他的iOS原生图表库,如 Swift 编写的 Charts 等.

**Comment by AAChartModel** [comment]
问题已解决,参见 #810
