### ISSUE TITLE
如何修改AAMarker的背景颜色文字大小 文字颜色

### ISSUE THREAD

**Issue by mabaoliang** [AAChartModel/AAChartKit#474]
气泡AAMarker的背景颜色文字大小 文字颜色

**Comment by AAChartModel** [comment]
aaOptions.plotOptions.series
    .markerSet(AAMarker.new
               .radiusSet(@7)//曲线连接点半径，默认是4
               .symbolSet(AAChartSymbolTypeCircle)//曲线点类型："circle", "square", "diamond", "triangle","triangle-down"，默认是"circle"
               .fillColorSet(@"#ffffff")//点的填充色(用来设置折线连接点的填充色)
               .lineWidthSet(@3)//外沿线的宽度(用来设置折线连接点的轮廓描边的宽度)
               .lineColorSet(@"")//外沿线的颜色(用来设置折线连接点的轮廓描边颜色，当值为空字符串时，默认取数据点或数据列的颜色)
               );
