### ISSUE TITLE
X刻度线下方的文字斜体 有办法调整吗

### ISSUE THREAD

**Issue by wncios** [AAChartModel/AAChartKit#478]

**Comment by AAChartModel** [comment]
可以调整.你希望调整至什么样的设计效果?

**Comment by AAChartModel** [comment]
麻烦你把你现在的 AAChartModel 或者 AAOptions 实例对象配置代码贴一下(不要截图,请直接粘贴代码)

**Comment by wncios** [comment]
_aaChartModel = [[AAChartModel alloc] init];
        _aaChartModel.xAxisLabelsFontColor = @"#999999";
        _aaChartModel.yAxisVisible = NO;
        _aaChartModel.legendEnabled = NO;
        _aaChartModel.tooltipEnabled = NO;
        _aaChartModel.dataLabelEnabled = YES;
        _aaChartModel.titleFontSize = @12.5;
        _aaChartModel.chartTypeSet(AAChartTypeColumn);
        _aaChartModel.titleSet(@"");
        _aaChartModel.dataLabelFontColor = @"#35b31c";
        _aaChartModel.dataLabelFontWeight = @"11.5";
        _aaChartModel.xAxisCrosshairWidthSet(@1);
        _aaChartModel.xAxisCrosshairColorSet(@"rgba(0,0,0,0)");




self.aaChartModel.colorsThemeSet(@[@"#35b31c",@"#35b31c",@"#35b31c",@"#35b31c",@"#35b31c",@"#35b31c",@"#35b31c",@"#ef3118",@"#ef3118",@"#ef3118",@"#ef3118", @"#ef3118",@"#ef3118"]);
    self.aaChartModel.categoriesSet(@[@"12%",@"10%",@"8%",@"6%",@"4%",@"2%",@"0%",@"-2%",@"-4%",@"-6%",@"-8%",@"-10%",@"-12%"]);
    
    
    self.aaChartModel.seriesSet(@[@{@"name" : @"",
                                    @"data" : records,
                                    @"colorByPoint" : @true}]);
    
    
    self.aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:self.aaChartModel];
    self.aaOptions.plotOptions.column.groupPadding = @0.2;//设置棱柱之间的间距百分比
    self.aaOptions.xAxis.tickColor = @"#ffffff";
    self.aaOptions.xAxis.lineColor = @"#ffffff";
    self.aaChartModel.xAxisReversed = YES;

**Comment by wncios** [comment]
现在造成的问题就是刻度线下方的文字是斜体的，调整了大小也没用

**Comment by AAChartModel** [comment]
好的,我回去看看

**Comment by Zhanghuyang** [comment]
我也遇到這種問題，現在能解決嗎，文字斜體

**Comment by AAChartModel** [comment]
```objc
//只针对水平轴有效，允许在防止轴标签重叠时自动旋转轴标签的角度。
//当空间足够时，轴标签不会被旋转。当图表变小时（主要是宽度变小） ，
//轴标签开始旋转对应的角度，然后会依次删除间隔的轴标签并尝试旋转数
//组中的角度。可以通过将此参数设置为 false 来关闭轴标签旋转（这将导
//致标签自动换行）。 默认是：[-45].

AAPropStatementAndPropSetFuncStatement(strong, AALabels, id        , autoRotation)
```

@Zhanghuyang

**Comment by whokill** [comment]
找不到这个AAPropStatementAndPropSetFuncStatement的属性呢

**Comment by AAChartModel** [comment]
> 找不到这个AAPropStatementAndPropSetFuncStatement的属性呢

@whokill 这是 OC 的属性, Kotlin 版本的参考:
* https://github.com/AAChartModel/AAChartCore-Kotlin/issues/153
