### ISSUE TITLE
Y轴是否能设置刻度线？

### ISSUE THREAD

**Issue by LinJiaXing1102** [AAChartModel/AAChartKit#480]

**Comment by NoLiuxin** [comment]
AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:self.aaChartModel];
    aaOptions.yAxis.gridLineDashStyle = AALineDashStyleTypeLongDash;//设置Y轴的网格线样式为 AALineDashSyleTypeLongDash
    aaOptions.yAxis.lineColor = @"#000000";
    aaOptions.yAxis.allowDecimals = YES;
    aaOptions.yAxis.tickLength = @(5);
    //设置Y轴刻度数组
    self.yLineChartArray = @[@0.0,@20.0,@40.0,@60.0,@80.0];
    aaOptions.yAxis.tickPositions = self.yLineChartArray;

    //设置 x 轴准刻度的样式为不显示
    aaOptions.xAxis.tickWidth = @(0);
    //设置 x 轴准星线的样式
    aaOptions.xAxis.crosshair = (AACrosshair.new
                                 .widthSet(@1.0)//宽度
                                 .colorSet(@"#6E7DBE")//颜色
                                 .dashStyleSet(AALineDashStyleTypeLongDash)//虚线
                                 );

    aaOptions.plotOptions.series.events = @{@"legendItemClick":@"false"};
    
    [self.aaChartView aa_drawChartWithOptions:aaOptions];
    
    [self.aaChartView aa_showTheSeriesElementContentWithSeriesElementIndex:0];
