### ISSUE TITLE
设置了Y轴标示线但是不显示标示线的label标记text,怎么让他显示啊？

### ISSUE THREAD

**Issue by Crayonnerry** [AAChartModel/AAChartKit#481]

**Comment by Crayonnerry** [comment]
标示线的文字标签设置了但是不显示

**Comment by AAChartModel** [comment]
这个恐怕搞不定了,似乎是Highcharts 在 iOS 12上面的一个 bug.暂无解决方案😅

**Comment by AAChartModel** [comment]
之前有人遇到过 #448

**Comment by Crayonnerry** [comment]
啊啊啊。。好尴尬，这是要去看底层的框架了吗  - -

**Comment by zhouzhou94alone** [comment]
我也遇到了这个问题 请问解决了吗?

**Comment by zhouzhou94alone** [comment]
> 啊啊啊。。好尴尬，这是要去看底层的框架了吗 - -

请问你是怎么解决的?

**Comment by Crayonnerry** [comment]
还没解决 - - 没时间去研究。。

**Comment by AAChartModel** [comment]
找到解决方法了,等我回去处理一下

**Comment by zhouzhou94alone** [comment]
> 找到解决方法了,等我回去处理一下

大大 怎样 解决了吗?😅

**Comment by AAChartModel** [comment]
Fixed in https://github.com/AAChartModel/AAChartKit/commit/0ac31feef5ee409ebfdbdb3dfa6336402a4786c4  commit

在 https://github.com/AAChartModel/AAChartKit/commit/0ac31feef5ee409ebfdbdb3dfa6336402a4786c4 这次提交中已解决.
