### ISSUE TITLE
关于内存泄露

### ISSUE THREAD

**Issue by ChaoYeee** [AAChartModel/AAChartKit#485]
最近在做引入测试时,发现aachart存在内存泄露问题,但是跑源demo并没有发现,自己写的却检测出来了,所以想请教下自己是否写法存在问题,感谢解惑.
附Leaks截图及代码:
![1](https://user-images.githubusercontent.com/20300751/48684909-e4501f00-ebee-11e8-9c4a-3313d70feb5c.jpg)

代码部分:
- (void)viewDidLoad
{
    [super viewDidLoad];
    
    self.navigationItem.title = @"图表内存泄露测试";
    
    // 初始化Chart
    AAChartView *aaChartView = [[AAChartView alloc] initWithFrame:CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width, [UIScreen mainScreen].bounds.size.height)];
    [self.view addSubview:aaChartView];
    
    // 绘制统计表
    AALabels *labels = (AAObject(AALabels)
                        // 设置y轴是否显示数字
                        .enabledSet(true)
                        .styleSet(AAObject(AAStyle)
                                  .colorSet(@"#B1B1B1")
                                  .fontSizeSet(@"12px")
                                  .fontWeightSet(AAChartSymbolTypeDiamond)
                                  )
                        .formatSet(@"{value:.,.1f}")
                        );
    
    AAYAxis *yAxisOne = AAObject(AAYAxis)
    .visibleSet(true)
    // y轴线颜色
    .gridLineColorSet(@"#FFFFFF")
    .labelsSet(labels)
    .allowDecimalsSet(true)
    .titleSet(AAObject(AATitle)
              .textSet(@"")
              )
    .oppositeSet(true);
    
    AAYAxis *yAxisTwo = AAObject(AAYAxis)
    .visibleSet(true)
    .gridLineColorSet(@"#FFFFFF")
    .titleSet(AAObject(AATitle)
              .textSet(@"")
              );
    
    NSArray *yAxisArr = @[
                          yAxisOne,
                          yAxisTwo,
                          ];
    
    AATooltip *aaTooltip = AAObject(AATooltip).sharedSet(true).enabledSet(true);
    NSArray *aaSeries = @[
                          AAObject(AASeriesElement)
                          .nameSet(@"未处理")
                          .typeSet(AAChartTypeColumn)
                          .stackingSet(AAChartStackingTypeNormal)
                          // 区分y轴数据
                          .yAxisSet(@1)
                          .dataSet(@[@10,@20,@30,@40,@50,@60,@70,@80])
                          .dataLabelsSet(AAObject(AADataLabels)
                                         .enabledSet(NO)
                                         )
                          ,
                          AAObject(AASeriesElement)
                          .nameSet(@"已处理")
                          .typeSet(AAChartTypeColumn)
                          .stackingSet(AAChartStackingTypeNormal)
                          .yAxisSet(@1)
                          .dataSet(@[@80,@70,@60,@50,@40,@30,@20,@10])
                          .dataLabelsSet(AAObject(AADataLabels)
                                         .enabledSet(NO)
                                         )
                          ,
                          AAObject(AASeriesElement)
                          .nameSet(@"处理率")
                          .yAxisSet(@0)
                          .lineWidthSet(@3)
                          .typeSet(AAChartTypeLine)
                          .stackingSet(AAChartStackingTypeNormal)
                          .dataSet(@[@1,@2,@3,@4,@5,@6,@7,@8])
                          .dataLabelsSet(AAObject(AADataLabels)
                                         .enabledSet(NO)
                                         )
                          ];
    // X轴
    NSDictionary *xAxis = @{
                            @"categories":@[@"嘿",@"哈",@"提",@"饿",@"洗",@"萨克",@"发",@"是"],
                            @"tickColor":@"#FFFFFF",
                            };
    
    AAOptions *chartOptions = AAObject(AAOptions);
    // 主题颜色数组
    chartOptions.colorsSet(@[@"rgba(110,180,250,1)",@"rgba(242,155,118,1)", @"rgba(54,187,184,1)"]);
    chartOptions.yAxis = (id)yAxisArr;
    chartOptions.tooltip = aaTooltip;
    chartOptions.series = aaSeries;
    chartOptions.xAxis = (id)xAxis;
    chartOptions.title = (id)@"";
    
    // 绘制表
    [aaChartView aa_drawChartWithOptions:chartOptions];
}

**Comment by ChaoYug** [comment]
@AAChartModel

**Comment by AAChartModel** [comment]
问题已解决. 更新 AAChartKit 至最新内容即可
