### ISSUE TITLE
扇形图图保留一位小数，加起来超过100%

### ISSUE THREAD

**Issue by LuXiangZhao** [AAChartModel/AAChartKit#487]

**Comment by AAChartModel** [comment]
这很正常吧,在处理各种小数的时候, Highcharts 肯定会进行各种四舍五入的操作,这样使得总数合计就不太可能完全吻合100%.   你可以将同样的数据套用到其他的图表库中测试一下.

**Comment by LuXiangZhao** [comment]
谢谢这么快恢复，我也觉得正常，保留小数点越多越准确，有时候这种问题就是没法跟测试解释，😔

**Comment by AAChartModel** [comment]
😝😝😝

**Comment by LuXiangZhao** [comment]
最后发现是我自己算错了，扇形图计算没问题
