### ISSUE TITLE
iOS 8.3  xcode8.3.2 上初始化UI界面不显示

### ISSUE THREAD

**Issue by Brances** [AAChartModel/AAChartKit#49]
ARNING!!!!! THERE ARE SOME ERROR INFOMATION_______Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo=0x17426ff00 {NSLocalizedDescription=A JavaScript exception occurred}

**Comment by AAChartModel** [comment]
现已修复此问题,您可以下载最新的 AAChartKit 测试运行效果
