### ISSUE TITLE
请问条形图的y轴的文本能不能换行

### ISSUE THREAD

**Issue by vlove550** [AAChartModel/AAChartKit#492]
![_29b0899f-1ae1-4adb-b503-8fdf32ab722a](https://user-images.githubusercontent.com/13690937/49774108-9b434480-fd2e-11e8-902b-aa2b82af82ba.png)
请问能不能把y轴太长的文字换行

**Comment by AAChartModel** [comment]
参考issue #492,

![](https://user-images.githubusercontent.com/16357599/47204165-3ebe4b80-d3b5-11e8-9ca8-6ad9de1c0ab9.png)
条形图文字换行与柱状图文字换行类似,都是在需要换行的地方适当地插入`<br>`这种HTML超文本标签即可

**Comment by vlove550** [comment]
谢谢,解决了
