### ISSUE TITLE
双Y轴

### ISSUE THREAD

**Issue by tipshot** [AAChartModel/AAChartKit#496]

**Comment by tipshot** [comment]
是否可以设置双Y轴，并且单独控制是否显示刻度线，是否显示刻度数字？如果有谁看到这个问题，并且可以解答，非常欢迎给于解答，感谢。

**Comment by AAChartModel** [comment]
AAChartKit的示例
demo中不是有双Y轴的示例代码吗?

**Comment by tipshot** [comment]
aa_drawChartWithChartModel使用这个方法是否可以设置出双Y轴，如果可以，是否可以分别控制两条Y轴的参数？

**Comment by AAChartModel** [comment]
`aa_drawChartWithChartModel `方法内部调用的其实还是`aa_drawChartWithOptions `,`aa_drawChartWithChartModel`相当封装了一个快捷简便的调用方法而已.AAChartModel其实最终还是通过AAOption.m文件当中的AAOptionsConstructor转换成了AAOptions实例对象,之后再被AAChartVIew调用的

**Comment by AAChartModel** [comment]
AAChartModel封装了大部分比较重要的常规的AAOptions属性,但是像双Y轴这种比较特殊的图表,如果也封装在AAChartModel当中容易导致AAChartModel和AAOptionsConstructor代码冗余.所以双Y轴图表的AAOptions就被设计成了需要自己配置.你在使用的时候如果闲麻烦,也可以自己进行进一步的封装.

而且HighCharts的全部属性实在是太多,而且大部分的属性对于常规用户来说都属于冗余内容.没有添加的必要,如果全部封装到AAChartModel当中,那么AAChartModel的文件大小将不可想象. 所以这也是为什么一些比较冷门样式的图表的AAOptions需要自己配置.因为AAOptions的自由度更高.当然配置起来也会相对而言复杂一点.

**Comment by tipshot** [comment]
大佬，非常感谢详细耐心的解答，你这样一个一个的回复感觉非常负责认真并且是义务，非常感谢。是否可以创建一个交流群？这样大家可以互相探讨一下AAChartKit，你也不必这样一个一个的回复解答。
