### ISSUE TITLE
如何去掉pie chart下面的文字

### ISSUE THREAD

**Issue by Vutumn** [AAChartModel/AAChartKit#50]
当可显示范围很小时，想让扇形图全部显示，但是无奈下面的内容文字占了大部分空间，请问如何去掉

**Comment by Vutumn** [comment]
最后采用了scrollview固定坐标，禁止滑动的方式解决了问题

**Comment by AAChartModel** [comment]
设置**AAChartModel**的`legendEnabled`输入性为 `NO`即可关闭图表的 `legend`图例,也就是你所说的去掉图表下方的可点按的圆点和文字
