### ISSUE TITLE
提示框效果能做到这样么

### ISSUE THREAD

**Issue by Unrealplace** [AAChartModel/AAChartKit#501]
<img width="295" alt="2018-12-17 6 10 38" src="https://user-images.githubusercontent.com/16250045/50080899-1e313700-0228-11e9-90c3-33b91544dd8a.png">

**Comment by Unrealplace** [comment]
解决了，没用这个框架，自己画了一个。 李杨 软件开发工程师 邮箱：oliverleemail@gmail.com 13837196824 yang8191111 签名由 网易邮箱大师 定制 在2018年12月25日 16:28，MondoYang 写道： 你这个解决了没有？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Unrealplace** [comment]
> 你这个解决了没有？

解决了

**Comment by AAChartModel** [comment]
@MondoYang 

目前没找到比较好的实现方法,不过CocoaChina有网友分享的示例代码倒是可以参考,研究学习一下

http://code.cocoachina.com/view/137760#all_comment

![](http://code.cocoachina.com/uploads/attachments/20181023/137760/66695d7663d42737d49df3cbf8af8703.png)

![](http://code.cocoachina.com/uploads/attachments/20181023/137760/46a7a1db1887d04eba227dce4900b5ca.png)

**Comment by Unrealplace** [comment]
我没有用他这个框架，根据需求自己画的。 李杨 软件开发工程师 邮箱：oliverleemail@gmail.com 13837196824 yang8191111 签名由 网易邮箱大师 定制 在2018年12月27日 16:27，MondoYang 写道： 怎么解决的？方便共享一下么？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Unrealplace** [comment]
> 怎么解决的？方便共享一下么？

我没有他这个框架，根据项目需求自己画了一个，只能支持单双y轴和多曲线。
![wechatimg1](https://user-images.githubusercontent.com/16250045/50476832-b8516600-0a04-11e9-950f-70c6071359f1.jpeg)

**Comment by AAChartModel** [comment]
参见 #653
