### ISSUE TITLE
双Y轴左边无法绘制label

### ISSUE THREAD

**Issue by tipshot** [AAChartModel/AAChartKit#503]
```objc
- (void)test1{
    
    CGFloat chartViewWidth  = self.view.frame.size.width;
    CGFloat chartViewHeight = self.view.frame.size.height;
    _aaChartView = [[AAChartView alloc]init];
    _aaChartView.frame = CGRectMake(100, 30, chartViewWidth*0.5, chartViewHeight*0.5);
    [self.view addSubview:_aaChartView];
    
    [_aaChartView aa_drawChartWithOptions:[self configureDoubleYAxisChartOptions]];
}

- (AAOptions *)configureDoubleYAxisChartOptions {
    
    AATitle *aaTitle = AATitle.new.textSet(@"Options绘制 双Y轴混合图");
    
    AALabels *xlabels = AALabels.new
    .enabledSet(true)//设置X轴是否显示数字
    .formatSet(@"{value:.,0f}月")
    .styleSet(AAStyle.new
              .colorSet(@"#666666")//yAxis Label font color
              .fontSizeSet(@"10px")//yAxis Label font size
              .fontWeightSet(AAChartFontWeightTypeBold)//yAxis Label font weight
              );
    
    AAXAxis *xAxisOne = AAXAxis.new
    .gridLineWidthSet(@0)
    .lineWidthSet(@2)
    .lineColorSet(@"#666666")
    .minSet(@0)
    .visibleSet(true)
    .startOnTickSet(true)
    .labelsSet(xlabels)
    ;
    
    
    AALabels *YlabelOne = AALabels.new
    .enabledSet(true)//设置 y 轴是否显示数字
    .formatSet(@"{value:.,0f}°A")
    .styleSet(AAStyle.new
              .colorSet(@"#ff0000")//yAxis Label font color
              .fontSizeSet(@"15px")//yAxis Label font size
              .fontWeightSet(AAChartFontWeightTypeBold)//yAxis Label font weight
              );
    
    
    AAYAxis *yAxisOne = AAYAxis.new
    .gridLineWidthSet(@0)
    .lineWidthSet(@2)
    .lineColorSet(@"#666666")
    .visibleSet(true)
    .labelsSet(YlabelOne.formatSet(@"{value}mm"))
    .titleSet(AATitle.new.textSet(@""))
    .oppositeSet(false)
    ;
    
    
    AALabels *YlabelTwo = AALabels.new
    .enabledSet(true)//设置 y 轴是否显示数字
    .formatSet(@"{value:.,0f}°A")
    .styleSet(AAStyle.new
              .colorSet(@"#ff0000")//yAxis Label font color
              .fontSizeSet(@"15px")//yAxis Label font size
              .fontWeightSet(AAChartFontWeightTypeBold)//yAxis Label font weight
              );
    
    
    AAYAxis *yAxisTwo = AAYAxis.new
    .gridLineWidthSet(@0)
    .lineWidthSet(@2)
    .lineColorSet(@"#666666")
    .visibleSet(true)
    .labelsSet(YlabelTwo.formatSet(@"{value}mm"))
    .titleSet(AATitle.new.textSet(@""))
    .oppositeSet(true);
    
    NSArray *aaYAxisArr = @[yAxisOne,// Primary yAxis
                            yAxisTwo // Secondary yAxis
                            ];
    
    AATooltip *aaTooltip = AATooltip.new
    .enabledSet(true)
    .sharedSet(true)
    ;
    
    NSArray *aaSeries = @[
                          AASeriesElement.new
                          .nameSet(@"2018")
                          .typeSet(AAChartTypeLine)
                          .yAxisSet(@1)
                          .dataSet(@[@27, @25, @22, @14, @10, @7, @5, @4, @5, @10, @18, @25])
                          .dataLabelsSet(AADataLabels.new.enabledSet(true)),
                          
                          AASeriesElement.new
                          .nameSet(@"2018")
                          .typeSet(AAChartTypeLine)
                          .yAxisSet(@1)
                          .dataSet(@[@0.2, @0.8, @5.7, @11.3, @17.0, @22.0, @24.8, @24.1, @20.1, @14.1, @8.6, @2.5])
                          .dataLabelsSet(AADataLabels.new.enabledSet(true))
                          ];
    
    AAOptions *aaOptions = AAOptions.new;
    aaOptions.title = aaTitle;
    aaOptions.yAxis = (id)aaYAxisArr;
    aaOptions.xAxis = xAxisOne;
    aaOptions.tooltip = aaTooltip;
    aaOptions.series = aaSeries;
    
    return aaOptions;
}
```
已经感觉到这是一个小问题，但是就是找不出来，或者是我对机制了解不够深？

**Comment by tipshot** [comment]
![image](https://user-images.githubusercontent.com/18547353/50088355-c1407b80-023d-11e9-9089-c809fc6e8adf.png)

**Comment by tipshot** [comment]
> * (void)test1{
>   CGFloat chartViewWidth  = self.view.frame.size.width;
>   CGFloat chartViewHeight = self.view.frame.size.height;
>   _aaChartView = [[AAChartView alloc]init];
>   _aaChartView.frame = CGRectMake(100, 30, chartViewWidth_0.5, chartViewHeight_0.5);
>   [self.view addSubview:_aaChartView];
>   [_aaChartView aa_drawChartWithOptions:[self configureDoubleYAxisChartOptions]];
>   }
> * (AAOptions *)configureDoubleYAxisChartOptions {
>   AATitle *aaTitle = AATitle.new.textSet(@"Options绘制 双Y轴混合图");
>   AALabels *xlabels = AALabels.new
>   .enabledSet(true)//设置X轴是否显示数字
>   .formatSet(@"{value:.,0f}月")
>   .styleSet(AAStyle.new
>   .colorSet(@"#666666")//yAxis Label font color
>   .fontSizeSet(@"10px")//yAxis Label font size
>   .fontWeightSet(AAChartFontWeightTypeBold)//yAxis Label font weight
>   );
>   AAXAxis *xAxisOne = AAXAxis.new
>   .gridLineWidthSet(@0)
>   .lineWidthSet(@2)
>   .lineColorSet(@"#666666")
>   .minSet(@0)
>   .visibleSet(true)
>   .startOnTickSet(true)
>   .labelsSet(xlabels)
>   ;
>   AALabels *YlabelOne = AALabels.new
>   .enabledSet(true)//设置 y 轴是否显示数字
>   .formatSet(@"{value:.,0f}°A")
>   .styleSet(AAStyle.new
>   .colorSet(@"#ff0000")//yAxis Label font color
>   .fontSizeSet(@"15px")//yAxis Label font size
>   .fontWeightSet(AAChartFontWeightTypeBold)//yAxis Label font weight
>   );
>   AAYAxis *yAxisOne = AAYAxis.new
>   .gridLineWidthSet(@0)
>   .lineWidthSet(@2)
>   .lineColorSet(@"#666666")
>   .visibleSet(true)
>   .labelsSet(YlabelOne.formatSet(@"{value}mm"))
>   .titleSet(AATitle.new.textSet(@""))
>   .oppositeSet(false)
>   ;
>   AALabels *YlabelTwo = AALabels.new
>   .enabledSet(true)//设置 y 轴是否显示数字
>   .formatSet(@"{value:.,0f}°A")
>   .styleSet(AAStyle.new
>   .colorSet(@"#ff0000")//yAxis Label font color
>   .fontSizeSet(@"15px")//yAxis Label font size
>   .fontWeightSet(AAChartFontWeightTypeBold)//yAxis Label font weight
>   );
>   AAYAxis *yAxisTwo = AAYAxis.new
>   .gridLineWidthSet(@0)
>   .lineWidthSet(@2)
>   .lineColorSet(@"#666666")
>   .visibleSet(true)
>   .labelsSet(YlabelTwo.formatSet(@"{value}mm"))
>   .titleSet(AATitle.new.textSet(@""))
>   .oppositeSet(true);
>   NSArray *aaYAxisArr = @[yAxisOne,// Primary yAxis
>   yAxisTwo // Secondary yAxis
>   ];
>   AATooltip *aaTooltip = AATooltip.new
>   .enabledSet(true)
>   .sharedSet(true)
>   ;
>   NSArray *aaSeries = @[
>   AASeriesElement.new
>   .nameSet(@"2018")
>   .typeSet(AAChartTypeLine)
>   .yAxisSet(@1)
>   .dataSet(@[@27, @25, @22, @14, @10, @7, @5, @4, @5, @10, @18, @25])
>   .dataLabelsSet(AADataLabels.new.enabledSet(true)),
>   ```
>                       AASeriesElement.new
>                       .nameSet(@"2018")
>                       .typeSet(AAChartTypeLine)
>                       .yAxisSet(@1)
>                       .dataSet(@[@0.2, @0.8, @5.7, @11.3, @17.0, @22.0, @24.8, @24.1, @20.1, @14.1, @8.6, @2.5])
>                       .dataLabelsSet(AADataLabels.new.enabledSet(true))
>                       ];
>   ```
>   AAOptions *aaOptions = AAOptions.new;
>   aaOptions.title = aaTitle;
>   aaOptions.yAxis = (id)aaYAxisArr;
>   aaOptions.xAxis = xAxisOne;
>   aaOptions.tooltip = aaTooltip;
>   aaOptions.series = aaSeries;
>   return aaOptions;
>   }
>   已经感觉到这是一个小问题，但是就是找不出来，或者是我对机制了解不够深？

**Comment by AAChartModel** [comment]
将 

```objc
    NSArray *aaSeries = @[
                          AASeriesElement.new
                          .nameSet(@"2018")
                          .typeSet(AAChartTypeLine)
                          .yAxisSet(@1hella 
)
                          .dataSet(@[@27, @25, @22, @14, @10, @7, @5, @4, @5, @10, @18, @25])
                          .dataLabelsSet(AADataLabels.new.enabledSet(true)),
                          
                          AASeriesElement.new
                          .nameSet(@"2018")
                          .typeSet(AAChartTypeLine)
                          .yAxisSet(@1)
                          .dataSet(@[@0.2, @0.8, @5.7, @11.3, @17.0, @22.0, @24.8, @24.1, @20.1, @14.1, @8.6, @2.5])
                          .dataLabelsSet(AADataLabels.new.enabledSet(true))
                          ];
```
改为

```objc
    NSArray *aaSeries = @[
                          AASeriesElement.new
                          .nameSet(@"2018")
                          .typeSet(AAChartTypeLine)
                          .yAxisSet(@0)
                          .dataSet(@[@27, @25, @22, @14, @10, @7, @5, @4, @5, @10, @18, @25])
                          .dataLabelsSet(AADataLabels.new.enabledSet(true)),
                          
                          AASeriesElement.new
                          .nameSet(@"2018")
                          .typeSet(AAChartTypeLine)
                          .yAxisSet(@1)
                          .dataSet(@[@0.2, @0.8, @5.7, @11.3, @17.0, @22.0, @24.8, @24.1, @20.1, @14.1, @8.6, @2.5])
                          .dataLabelsSet(AADataLabels.new.enabledSet(true))
                          ];

```

因为AASeriesElement的属性yAxis相当于是索引,你将两个AASeriesElement都设置为1就导致错乱了

**Comment by tipshot** [comment]
X轴和Y轴的刻度线设置的参数是什么？比如控制是否显示刻度线，设置刻度线参数之类的。

**Comment by AAChartModel** [comment]
```objc
 AAYAxis *aaYAxis = AAYAxis.new
    .labelsSet(AALabels.new
               .enabledSet(aaChartModel.yAxisLabelsEnabled)//设置 y 轴是否显示数字
               .styleSet(AAStyle.new
                         .colorSet(aaChartModel.yAxisLabelsFontColor)//yAxis Label font color
                         .fontSizeSet(AAFontSizeFormat(aaChartModel.yAxisLabelsFontSize))//yAxis Label font size
                         .fontWeightSet(aaChartModel.yAxisLabelsFontWeight)//yAxis Label font weight
                         )
               .formatSet(@"{value:.,0f}")//让y轴的值完整显示 而不是100000显示为100k
               )
    .minSet(aaChartModel.yAxisMin)//设置 y 轴最小值,最小值等于零就不能显示负值了
    .maxSet(aaChartModel.yAxisMax)//y轴最大值
    .tickPositionsSet(aaChartModel.yAxisTickPositions)//自定义Y轴坐标
    .allowDecimalsSet(aaChartModel.yAxisAllowDecimals)//是否允许显示小数
    .plotLinesSet(aaChartModel.yAxisPlotLines) //标示线设置
    .reversedSet(aaChartModel.yAxisReversed)
    .gridLineWidthSet(aaChartModel.yAxisGridLineWidth)//y轴网格线宽度
    .titleSet(AATitle.new.textSet(aaChartModel.yAxisTitle))//y 轴标题
    .lineWidthSet(aaChartModel.yAxisLineWidth)//设置 y轴轴线的宽度,为0即是隐藏 y轴轴线
    .visibleSet(aaChartModel.yAxisVisible)
    .tickIntervalSet(aaChartModel.yAxisTickInterval);
    
    if ([aaChartModel.yAxisCrosshairWidth floatValue]>0) {
        aaYAxis.crosshairSet(AACrosshair.new
                             .widthSet(aaChartModel.yAxisCrosshairWidth)
                             .colorSet(aaChartModel.yAxisCrosshairColor)
                             .dashStyleSet(aaChartModel.yAxisCrosshairDashStyleType)
                             );
    }
```

你参照着AAOptionsConstructor.m文件里面的这部分内容来写就行了.

**Comment by tipshot** [comment]
回复还即时，非常感谢！

**Comment by tipshot** [comment]
还有一个就是，图表背景如何替换成自定义的图片？

**Comment by AAChartModel** [comment]
至于你说的刻度线相关的细致配置,highCharts官方文档链接在这里 https://api.hcharts.cn/highcharts#yAxis.tickAmount

目前我还没有添加这些较多的有关于刻度线的属性.如有需要,你可以自行将这些属性添加到AAYAxis类文件当中.或者我也可以在稍晚点的时间将这些属性添加完成

**Comment by AAChartModel** [comment]
plotBackgroundImage: String  
指定绘图区背景图片的地址。如果需要设置整个图表的背景，请通过 CSS 来给容器元素（div）设置背景图。另外如果需要在导出图片中包含这个背景图，要求这个地址是公网可以访问的地址（包含可以访问且是绝对路径）。

https://api.hcharts.cn/highcharts#chart.plotBackgroundImage

在AAChartKit中的设置如下

```objc
    aaOptions.chart.plotBackgroundImage = @"https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=2859216016,2109779587&fm=27&gp=0.jpg";

```

AAChartKit的使用AAOptions绘图的示例中有这个相关示例

**Comment by AAChartModel** [comment]
当然你也可以设置AAChartView背景色为透明色,然后在底部添加一张图片,当然这种方式可能不太官方😅

**Comment by tipshot** [comment]
第一个问题：上面的设置刻度线的参数我没有找到具体是哪个？现在我想先把刻度线调出来，具体详细设置后面再说，能否知道你说的你稍晚点将这些属性添加完成，大概是多久呢？嘿嘿。
第二个问题：刚才那个图片我直接复制你贴出的代码，发现并没有任何变化，图片没有出来，下面是我的代码：
    AAOptions *aaOptions = AAOptions.new;
    aaOptions.title = aaTitle;
    aaOptions.yAxis = (id)aaYAxisArr;
    aaOptions.xAxis = xAxisOne;
    aaOptions.tooltip = aaTooltip;
    aaOptions.chart.plotBackgroundImage = @"https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=2859216016,2109779587&fm=27&gp=0.jpg";
    aaOptions.series = aaSeries;

第三个问题：是否可以添加你的微信或者qq呢？我的qq是：782873256；非常感谢！

**Comment by AAChartModel** [comment]
aaOptions.chart = AAChart.new.plotBackgroundImageSet(@"https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=2859216016,2109779587&fm=27&gp=0.jpg");

**Comment by AAChartModel** [comment]
```objc    
aaOptions.chart = AAChart.new.plotBackgroundImageSet(@"https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=2859216016,2109779587&fm=27&gp=0.jpg");
```

这句代码没有起作用?

**Comment by tipshot** [comment]
哦哦，你给我的背景图已经出现了，但是因为不能满足项目需求，现在想把背景色设置成透明色，然后在底部加一张图片，现在的问题是无法把背景设置成透明。不起作用。
![image](https://user-images.githubusercontent.com/18547353/50142353-dfad8200-02e4-11e9-9f9f-a5b26a5f647c.png)

**Comment by tipshot** [comment]
这是我想要实现的效果。

**Comment by tipshot** [comment]
![image](https://user-images.githubusercontent.com/18547353/50142423-16839800-02e5-11e9-911f-7a76e73d3a0c.png)

**Comment by tipshot** [comment]
刚才看了一下层次图，发现你的这个参数设置的是最底层的View的背景色？
![image](https://user-images.githubusercontent.com/18547353/50143268-2bf9c180-02e7-11e9-993e-56edf2876844.png)

**Comment by AAChartModel** [comment]
```objc
 //设置 AAChartView 的背景色是否为透明
    self.aaChartView.isClearBackgroundColor = YES;
```

设置AAChartView为透明色这一句代码应该就够了,demo中的AAChartView其实就是透明色

**Comment by AAChartModel** [comment]
AAChartView内部实际上是一个UIView上添加了WKWebView,你直接设置
```objc
aaChartView.backgroundColor = [UIColor clearColor]; 
```
肯定是不行的

**Comment by AAChartModel** [comment]
```objc
   //设置 AAChartView 的背景色是否为透明
    self.aaChartView.isClearBackgroundColor = YES;

```

上面这句代码实际上执行的是下面👇这句代码(我重写了isClearBackgroundColor的setter方法)


```objc
- (void)setIsClearBackgroundColor:(BOOL)isClearBackgroundColor {
    _isClearBackgroundColor = isClearBackgroundColor;
    if (_isClearBackgroundColor == YES) {
        self.backgroundColor = [UIColor clearColor];
        if (AASYSTEM_VERSION >= 9.0) {
            [_wkWebView setBackgroundColor:[UIColor clearColor]];
            [_wkWebView setOpaque:NO];
        } else {
            [_uiWebView setBackgroundColor:[UIColor clearColor]];
            [_uiWebView setOpaque:NO];
        }
    }
}
```

同时还牵涉到了这部分代码

```objc
  if (self.isClearBackgroundColor == YES) {
        options.chart.backgroundColor = @"rgba(0,0,0,0)";
    }

```

所以说,设置AAChartView一个小小的透明背景色,实际上牵涉到的内容比你想象的要多

**Comment by AAChartModel** [comment]
```objc
   //设置 AAChartView 的背景色是否为透明
    self.aaChartView.isClearBackgroundColor = YES;

```
也就是说上面👆这句总共做了三件事:
1. 设置AAChartView(继承自UIView)本身背景色为透明色
```objc
 self.backgroundColor = [UIColor clearColor];

```

2. 设置WebView背景色为透明色
```objc
  if (AASYSTEM_VERSION >= 9.0) {
            [_wkWebView setBackgroundColor:[UIColor clearColor]];
            [_wkWebView setOpaque:NO];
        } else {
            [_uiWebView setBackgroundColor:[UIColor clearColor]];
            [_uiWebView setOpaque:NO];
        }
```
3. 设置WebView中的内容 div 为透明色
```objc
        options.chart.backgroundColor = @"rgba(0,0,0,0)";
```

**Comment by tipshot** [comment]
嗯嗯，设置成功了，非常感谢耐心详细的解答，这个问题已经解决了，已经设置背景图为透明色了，但是这个参数确实容易让人误解，给人的感觉是设置了，并没有起作用。嘿嘿，，，

**Comment by tipshot** [comment]
还有一个问题：就是图表下面的name这个标题说明是否可以设置去掉？
![image](https://user-images.githubusercontent.com/18547353/50145218-fa372980-02eb-11e9-9bc6-b4b85e2c6248.png)

**Comment by AAChartModel** [comment]
> 但是这个参数确实容易让人误解，给人的感觉是设置了，并没有起作用。嘿嘿，，，

如有兴趣,欢迎提pull Request🙂

**Comment by AAChartModel** [comment]
> 还有一个问题：就是图表下面的name这个标题说明是否可以设置去掉？

设置`nameSet(@" ")`而不是`nameSet(@"")`

也就是说设置name为一个是空格的字符串而不是一个空字符串

**Comment by AAChartModel** [comment]
如果想要将图例(可点按的小圆点)也一并隐藏,直接设置AASeriesElement的`showInLegend = true`

```objc
AAPropStatementAndPropSetFuncStatement(assign, AASeriesElement, BOOL      , showInLegend) //Whether to display this particular series or series type in the legend. The default value is true for standalone series, false for linked series. 默认是：true.
```

**Comment by tipshot** [comment]
X轴设置categories后，出现如下问题。
![image](https://user-images.githubusercontent.com/18547353/50205863-b6542b00-03a4-11e9-9db2-10a35660618e.png)

![image](https://user-images.githubusercontent.com/18547353/50205831-9cb2e380-03a4-11e9-9a6c-9718cf885b98.png)

**Comment by tipshot** [comment]
- (AAOptions *)configureTheAAOptionsOfAreaChart {
    
    AAChart *aaChart = AAChart.new.typeSet(AAChartTypeArea);
    AATitle *aaTitle = AATitle.new.textSet(@" ");
    AASubtitle *aaSubtitle = AASubtitle.new
    .textSet(@" ")
    .alignSet(AAChartTitleAlignTypeLeft);
    
    //X轴
    AALabels *xlabels = AALabels.new
    .enabledSet(true)//设置X轴是否显示数字
    .formatSet(@"{value:.,0f}")
    .styleSet(AAStyle.new
              .colorSet(@"#ffffff")//yAxis Label font color
              .fontSizeSet(@"15px")//yAxis Label font size
              .fontWeightSet(AAChartFontWeightTypeRegular)//yAxis Label font weight
              );
    
    //X轴
    AAXAxis *aaXAxis = AAXAxis.new
    .startOnTickSet(true)
    .gridLineWidthSet(@0)
    .lineWidthSet(@2)
    .lineColorSet(@"#ffffff")
    .minSet(@0)
    .labelsSet(xlabels)
    .visibleSet(true)
    .categoriesSet(@[@"0", @"10", @"20", @"30", @"40", @"50", @"60"])
    ;
    
   
    //Y轴
    AAYAxis *aaYAXis = AAYAxis.new
    .visibleSet(true)
    .lineWidthSet(@2)
    .lineColorSet(@"#ffffff")
    .gridLineWidthSet(@0)
    .tickPositionsSet(@[@(0),@(50),@(50), @(100), @(150), @(200),@(250)])
    ;
    
    AAYAxis *aaYAXisTwo = AAYAxis.new
    .visibleSet(false)
    .lineWidthSet(@0)
    .lineColorSet(@"#ffffff")
    .gridLineWidthSet(@0)
    .tickPositionsSet(@[@(0),@(50),@(50), @(100), @(150), @(200),@(250)])
    .oppositeSet(YES)
    ;
    NSArray * aaYaxisArray = @[aaYAXis,aaYAXisTwo];
    //浮窗
    AATooltip *aaTooltip = AATooltip.new.enabledSet(true).valueSuffixSet(@"xB0C");
    
    //图例
    AALegend *aaLegend = AALegend.new
    .enabledSet(true)//是否显示图例。如果不显示，下面的设置就没用。
    .alignSet(AALegendAlignTypeRight)
    .layoutSet(AALegendLayoutTypeVertical)
    .verticalAlignSet(AALegendVerticalAlignTypeMiddle)
    .itemMarginTopSet(@10)
    ;
    
    NSArray *aaSeries = @[
                          AASeriesElement.new
                          .nameSet(@"2022")
                          .colorSet(@"#BC2B44")
                          .markerSet(AAMarker.new.radiusSet(@0))
                          .lineWidthSet(@0)
                          .yAxisSet(@1)
                          .dataSet(@[@250.0, @250.0, @250.0, @250.0, @250.0, @250.0, @250.0]),
                          AASeriesElement.new
                          .nameSet(@"2021")
                          .colorSet(@"#EC6444")
                          .markerSet(AAMarker.new.radiusSet(@0))
                          .lineWidthSet(@0)
                          .yAxisSet(@1)
                          .dataSet(@[@225.0, @225.0, @225.0, @225.0, @225.0, @225.0, @225.0]),
                          AASeriesElement.new
                          .nameSet(@"2020")
                          .colorSet(@"#f19742")
                          .markerSet(AAMarker.new.radiusSet(@0))
                          .lineWidthSet(@0)
                          .yAxisSet(@1)
                          .dataSet(@[@200.0, @200.0, @200.0, @200.0, @200.0, @200.0, @200.0]),
                          AASeriesElement.new
                          .nameSet(@"2019")
                          .colorSet(@"#f3da60")
                          .markerSet(AAMarker.new.radiusSet(@0))
                          .lineWidthSet(@0)
                          .yAxisSet(@1)
                          .dataSet(@[@175.0, @175.0, @175.0, @175.0, @175.0, @175.0, @175.0]),
                          AASeriesElement.new
                          .nameSet(@"2018")
                          .colorSet(@"#9bd040")
                          .markerSet(AAMarker.new.radiusSet(@0))
                          .lineWidthSet(@0)
                          .yAxisSet(@1)
                          .dataSet(@[@150.0, @150.0, @150.0, @150.0, @150.0, @150.0, @150.0]),
                          AASeriesElement.new
                          .nameSet(@"2017")
                          .colorSet(@"#acf08f")
                          .markerSet(AAMarker.new.radiusSet(@0))//折线原点的半径，这里直接取消折线原点
                          .lineWidthSet(@0)
                          .yAxisSet(@1)
                          .dataSet(@[@110.0, @110.0, @110.0, @110.0, @110.0, @110.0, @110.0]),
                          AASeriesElement.new
                          .typeSet(AAChartTypeLine)
                          .nameSet(@"2017")
                          .colorSet(@"#ffffff")
                          .markerSet(AAMarker.new.radiusSet(@0))
                          .yAxisSet(@0)
                          .dataSet(@[@86.0, @91.0, @102.0, @110.0, @134.0, @158.0, @225.0]),
                          ];
    
    
    AAOptions *aaOptions = AAOptions.new;
    aaOptions.chart = aaChart;
    aaOptions.title = aaTitle;
    aaOptions.subtitle = aaSubtitle;
    aaOptions.xAxis = aaXAxis;
    aaOptions.yAxis = (id)aaYaxisArray;
    aaOptions.tooltip = aaTooltip;
    aaOptions.legend = aaLegend;
    aaOptions.series = aaSeries;
    return aaOptions;
}

**Comment by AAChartModel** [comment]
你使用多组折线填充图充当背景,来实现设计中的数值区域颜色分块渐变的需求,虽然的确是解决问题的办法,但却不是highCharts设计的初衷. 

 传送门: https://jshare.com.cn/demos/hhhhxD ,这里的在线示例中显示,Y轴的plotBands属性似乎才是实现此需求的官方指定的最佳方案(虽然代码实际上写起来也肯定是又臭又长🤣)

**Comment by AAChartModel** [comment]
另外我最近比较忙,你提出的另外的几点问题我恐怕暂时不能及时解决,至少得留待这个周末了

**Comment by tipshot** [comment]
好的，好的，非常感谢，等你周末的消息哈，我和两天已在看，但是一直没有找到原因。等你周末吧。

**Comment by tipshot** [comment]
![image](https://user-images.githubusercontent.com/18547353/50513129-bb198d00-0ad0-11e9-9485-5c67458ebef1.png)
这个问题是什么原因呢？现在快交工了，，，😂🤣
