### ISSUE TITLE
X轴categories为汉字后，X轴文字全部为0 ？

### ISSUE THREAD

**Issue by tipshot** [AAChartModel/AAChartKit#511]
<img width="794" alt="wx20181224-192517 2x" src="https://user-images.githubusercontent.com/18547353/50398403-4aadfb80-07b2-11e9-97f6-25816832a8ec.png">
<img width="723" alt="wx20181224-192529 2x" src="https://user-images.githubusercontent.com/18547353/50398404-4b469200-07b2-11e9-8953-20d833408373.png">

**Comment by tipshot** [comment]
另外一张图使用model绘制，添加的字符串就是正常的。

**Comment by tipshot** [comment]
然后我注意到使用model绘制，内部也是把model的categories直接把值传给了AAXAxis的categories。
![image](https://user-images.githubusercontent.com/18547353/50399756-c1e88d00-07bc-11e9-86d1-6ba727c9bf79.png)

**Comment by AAChartModel** [comment]
麻烦把代码文本贴一下

**Comment by AAChartModel** [comment]
我估计你有可能 `xLables`写错了,试试注释掉它运行一下看看

**Comment by tipshot** [comment]
好的，我这网略有点扯淡的慢，谢谢。

**Comment by tipshot** [comment]
是的，果然是的，非常感谢！！~！

**Comment by AAChartModel** [comment]
okay👌
