### ISSUE TITLE
设置Y轴最大值，最小值问题

### ISSUE THREAD

**Issue by a123478we** [AAChartModel/AAChartKit#519]
设置了     yAxisMaxSet  但是不起作用。看了 highchart  有个endOnTick，需要设置。请问咱们这里有这个属性吗？

**Comment by mailes** [comment]
同问，这个怎么解决。

**Comment by AAChartModel** [comment]
@mailes 你用的是最近最新的代码吗?

**Comment by mailes** [comment]
> @mailes 你用的是最近最新的代码吗?

可以了，用最新的代码。
