### ISSUE TITLE
您好，图表用透明背景色后，datalabel有一块黑色的背景，怎样设置使使这块黑色背景去掉啊？

### ISSUE THREAD

**Issue by ZhongLv-HoneyMoon** [AAChartModel/AAChartKit#525]
您好，图表用透明背景色后，datalabel有一块黑色的背景，怎样设置使使这块黑色背景去掉啊？就是下图红圈中的黑色部分，我理解为它是datalabel放置的背景视图的颜色，我可以给它改成透明色吗？怎么改呢？
<img width="368" alt="2018-12-27 3 37 51" src="https://user-images.githubusercontent.com/18362066/50471127-466e2200-09ee-11e9-80a1-e4043398746d.png">

**Comment by AAChartModel** [comment]
![image](https://user-images.githubusercontent.com/18547353/50410708-aff70080-0835-11e9-9437-7bd2c254f7ed.png)
能否把文字的白色背景（白色边框）去掉，换成正常的？


```swift
    (AAStyle.new
     .colorSet(@"#00ff00")//Title font color
     .fontSizeSet(@"14px")//Title font size
     .fontWeightSet(AAChartFontWeightTypeBold)//Title font weight
     .textOutlineSet(@"0px 0px contrast")
     )
```

AAStyle的这个属性`textOutline`就是用于设置文字边缘线宽度的,`.textOutlineSet(@"0px 0px contrast")`表示边缘线宽度为0.边缘线主要用于提高文字对比度,避免文字与背景颜色过于接近,导致用户识别困难.

**Comment by AAChartModel** [comment]
以上答案来自类似问题 #512
