### ISSUE TITLE
扇形图中的线和提示文字会缺少?

### ISSUE THREAD

**Issue by sujiewen** [AAChartModel/AAChartKit#527]
扇形图中的线和提示文字会缺少?角度在180开始,在下面线会出问题呢!
![1546012466452](https://user-images.githubusercontent.com/1973318/50520557-fed5bc00-0afb-11e9-8dc8-3e39faa58a63.jpg)

请看Demo

[testChart.zip](https://github.com/AAChartModel/AAChartKit/files/2715172/testChart.zip)

@AAChartModel

**Comment by AAChartModel** [comment]
你在AADataLabels.m文件的初始化方法里加上

```objc
- (instancetype)init {
    self = [super init];
    if (self) {
        self.allowOverlap = true;//允许数据标签文字重叠
    }

    return self;
}
```

允许数据标签文字重叠即可

**Comment by sujiewen** [comment]
@AAChartModel  好像不行呢....

**Comment by sujiewen** [comment]
![wechatimg202](https://user-images.githubusercontent.com/1973318/50580255-3e4b3200-0e87-11e9-8c53-5a22ec09f179.jpeg)
在里面设置和配置属性都不一样

**Comment by sujiewen** [comment]
@AAChartModel

**Comment by sujiewen** [comment]
> 你在AADataLabels.m文件的初始化方法里加上
> 
> ```objc
> - (instancetype)init {
>     self = [super init];
>     if (self) {
>         self.allowOverlap = true;//允许数据标签文字重叠
>     }
> 
>     return self;
> }
> ```
> 
> 允许数据标签文字重叠即可

按这个还是不行呢,帮帮忙
