### ISSUE TITLE
X轴标题可以隐藏不显示么

### ISSUE THREAD

**Issue by ldy1691github** [AAChartModel/AAChartKit#529]

**Comment by NoLiuxin** [comment]
self.aaChartModel= AAObject(AAChartModel)
.yAxisTitleSet(@"")//设置 Y 轴标题

**Comment by NoLiuxin** [comment]
AAPropSetFuncImplementation(AAChartModel, BOOL,       yAxisLabelsEnabled) //y 轴是否显示文字
AAPropSetFuncImplementation(AAChartModel, NSNumber *, yAxisLabelsFontSize) //y 轴文字字体大小
AAPropSetFuncImplementation(AAChartModel, NSString *, yAxisLabelsFontColor) //y 轴文字字体颜色
AAPropSetFuncImplementation(AAChartModel, AAChartFontWeightType , yAxisLabelsFontWeight) //y 轴文字字体粗细
AAPropSetFuncImplementation(AAChartModel, NSString *, yAxisTitle) //y 轴标题

**Comment by NoLiuxin** [comment]
AAPropSetFuncImplementation(AAChartModel, BOOL,       xAxisLabelsEnabled) //x 轴是否显示文字
