### ISSUE TITLE
扇形图DataLabel 上如何个性化设置

### ISSUE THREAD

**Issue by wangxj4268** [AAChartModel/AAChartKit#531]
你好，请问一下扇形图DataLabel 上如何个性化设置，比如当前扇形分为三个区域，但是每个区域中对应的DataLabel 中的文字+数字+单位都需要不同的颜色：请问这种该怎么实现呢？

**Comment by wangxj4268** [comment]
如：

**Comment by wangxj4268** [comment]
有谁遇到同样的问题么

**Comment by wangxj4268** [comment]
@AAChartModel 大神，抽空帮我看看呗

**Comment by AAChartModel** [comment]
配置AAOptions实例对象

```objc
AAOptions *aaOptions = AAOptions.new
    .chartSet(AAChart.new.typeSet(AAChartTypePie))
    .titleSet(AATitle.new
              .useHTMLSet(true)
              .textSet(@"<span style=""color:#1E90FF;font-weight:thin;font-size:13px""> &nbsp&nbsp&nbsp近七天 </span>  <br> <span style=""color:#A9A9A9;font-weight:thin;font-size:10px""> 运行状态占比 </span>")//标题文本内容
              .alignSet(AAChartTitleAlignTypeCenter)//标题水平居中
              .verticalAlignSet(AAChartTitleVerticalAlignTypeMiddle)//标题垂直居中
              .ySet(@0)//标题相对于垂直对齐的偏移量，取值范围：图表的上边距（chart.spacingTop ）到图表的下边距（chart.spacingBottom），可以是负值，单位是px。默认值和字体大小有关。
              )
    .colorsSet(@[@"#1E90FF",@"#87CEFA",@"#A9A9A9",@"#fd4800",@"#F4A460"])//设置颜色主题
    .seriesSet(@[
                 AASeriesElement.new
                 .sizeSet(@200)//环形图的半径大小
                 .innerSizeSet(@"60%")//内部圆环半径大小占比
                 .allowPointSelectSet(false)//是否允许在点击数据点标记(扇形图点击选中的块发生位移)
                 .dataLabelsSet(AADataLabels.new
                                .enabledSet(true)
                                .useHTMLSet(true)
                                .distanceSet(@10)
                                .formatSet(@"<span style=""color:#A9A9A9;font-weight:thin;font-size:10px"">{point.name}</span> <span style=""color:#1E90FF;font-weight:bold;font-size:15px"">{point.percentage:.1f}</span><span style=""color:#1E90FF;font-weight:thin;font-size:10px"">%</span>")
                                )
                 .dataSet(
                          @[
                            @[@"Firefox",   @150],
                            @[@"Opera",      @15],
                            @[@"Others",     @35]
                            ]
                          ),
                 ]);
```

2. 绘图结果
![image](https://user-images.githubusercontent.com/16357599/61841172-6ef7c500-aec6-11e9-85e3-41b9413029ee.png)

**Comment by AAChartModel** [comment]
AAChartKit的demo中有此示例,你可参照此示例作相应的自定义文字操作.

**Comment by AAChartModel** [comment]
主要是像这样
```html
<span style=""color:#A9A9A9;font-weight:thin;font-size:10px"">{point.name}</span> 
<span style=""color:#1E90FF;font-weight:bold;font-size:15px"">{point.percentage:.1f}</span>
<span style=""color:#1E90FF;font-weight:thin;font-size:10px"">%</span>
```
使用HTML字符串实现富文本功能.

**Comment by wangxj4268** [comment]
自己找到方法了，刚要来关闭issues却发现博主已经回复我了，感谢！

但是我的需求是每个dateLabel上的文字+数字+单位的颜色都不一样，博主上面贴的代码块设置的统一的，无法区分每个dateLabel的颜色，所以我贴一下如何实现我自己的需求吧，希望能帮助有和我一样需求的人（主要就是在设置数据源时，对每个扇形单独设置dataLabels即可）：
.dataSet(
                          @[
                            @{
                                @"name":@"空闲中",
                                @"y":freeCountNumber,
                                @"sliced":@(false),
                                @"selected":@(false),//是否需要默认选中
                                @"dataLabels":@{    //分别设置每个扇形的dateLabel
                                        @"enabled":@(true),
                                        @"useHTML":@(true),
                                        @"distance":@10,
                                        @"format":@"<span style=""color:#12d698;font-weight:thin;font-size:10px"">{point.percentage:.0f}</span><span style=""color:#12d698;font-weight:thin;font-size:10px"">%</span><br><span style=""color:#666666;font-weight:thin;font-size:10px"">{point.name}</span>"
                                        }
                                },
                            @{
                                @"name":@"待命中",
                                @"y":standbyNumber,
                                @"sliced":@(false),
                                @"selected":@(false),//是否需要默认选中
                                @"dataLabels":@{
                                        @"enabled":@(true),
                                        @"useHTML":@(true),
                                        @"distance":@10,
                                        @"format":@"<span style=""color:#ffad43;font-weight:thin;font-size:10px"">{point.percentage:.0f}</span><span style=""color:#ffad43;font-weight:thin;font-size:10px"">%</span><br><span style=""color:#666666;font-weight:thin;font-size:10px"">{point.name}</span>"
                                        }
                                },
                            @{
                                @"name":@"工作中",
                                @"y":useCountNumber,
                                @"sliced":@(false),
                                @"selected":@(false),//是否需要默认选中
                                @"dataLabels":@{
                                        @"enabled":@(true),
                                        @"useHTML":@(true),
                                        @"distance":@10,
                                        @"format":@"<span style=""color:#00aeff;font-weight:thin;font-size:10px"">{point.percentage:.0f}</span><span style=""color:#00aeff;font-weight:thin;font-size:10px"">%</span><br><span style=""color:#666666;font-weight:thin;font-size:10px"">{point.name}</span>"
                                        }
                                }
                            ]
                          )
