### ISSUE TITLE
出现这个日志，怎么回事？

### ISSUE THREAD

**Issue by tipshot** [AAChartModel/AAChartKit#536]
![image](https://user-images.githubusercontent.com/18547353/51072289-06b76380-1699-11e9-850f-08da0997032f.png)

**Comment by AAChartModel** [comment]
这个一般是因为在本地HTML内容还未完全加载完成(也就是说OC还没有完全获得HTML文件上下文内容),就先进行了OC调用JS方法的操作.导致OC找不到JS方法名.
