### ISSUE TITLE
怎么实现 点击折线 获得对应点的 X轴Y轴的数据

### ISSUE THREAD

**Issue by ldy1691github** [AAChartModel/AAChartKit#544]
你说的“

现已有 GitHub 同好在项目的 Demo 中使用 UIGesture 实现了图表的点击事件回调,可参考.” 具体什么意思，可以具体点么

**Comment by NoLiuxin** [comment]
#pragma mark -- AAChartViewEventDelegate
- (void)aaChartView:(AAChartView *)aaChartView moveOverEventWithMessage:(AAMoveOverEventMessageModel *)message
实现代理

@interface AAMoveOverEventMessageModel : NSObject

@property (nonatomic, copy)   NSString *name;
@property (nonatomic, strong) NSNumber *x;
@property (nonatomic, strong) NSNumber *y;
@property (nonatomic, copy)   NSString *category;
@property (nonatomic, strong) NSDictionary *offset;
@property (nonatomic, assign) NSUInteger index;

@end

index为Y的位置。x是X的位置，这样就可以根据数据的array取到具体的值了
