### ISSUE TITLE
有没有能够标记折线图最大值最小值的方法

### ISSUE THREAD

**Issue by Crayonnerry** [AAChartModel/AAChartKit#546]

**Comment by NoLiuxin** [comment]
![WeChat1f2f607200864810b2dfe45721917c46](https://user-images.githubusercontent.com/8954358/62851983-9cdc6680-bd1a-11e9-969b-32089241fe08.png)
![WeChat1b50a42a64aa505359a196feb322883f](https://user-images.githubusercontent.com/8954358/62852021-c3020680-bd1a-11e9-9750-10b5ea47c34c.png)
请看图。需要更新到最新版本。

关键代码

 AADataElement *singleSpecialData = AADataElement.new
    .markerSet(AAMarker.new
               .radiusSet(@8)//曲线连接点半径
               .symbolSet(AAChartSymbolTypeCircle)//曲线点类型："circle", "square", "diamond", "triangle","triangle-down"，默认是"circle"
               .fillColorSet(@"#FFFFFF")//点的填充色(用来设置折线连接点的填充色)
               .lineWidthSet(@5)//外沿线的宽度(用来设置折线连接点的轮廓描边的宽度)
               .lineColorSet(@"#FF0000")//外沿线的颜色(用来设置折线连接点的轮廓描边颜色，当值为空字符串时，默认取数据点或数据列的颜色)
               )
    .ySet(@60.0);

self.towArray = @[@10.0, @15.0, @18.0, singleSpecialData, @50.0, @60.0, @34.0];
