### ISSUE TITLE
能不能编辑浮动提示框x轴显示的内容

### ISSUE THREAD

**Issue by a123478we** [AAChartModel/AAChartKit#547]
<img width="297" alt="2019-02-12 9 45 14" src="https://user-images.githubusercontent.com/14817057/52605801-3c738600-2eab-11e9-8935-9e3d3f93107e.png">

能不能编辑  提示框go  这行的显示内容？

**Comment by AAChartModel** [comment]
```objc
AAPropStatementAndPropSetFuncStatement(copy,   AATooltip, NSString *, formatter) 
AAPropStatementAndPropSetFuncStatement(copy,   AATooltip, NSString *, headerFormat) 
AAPropStatementAndPropSetFuncStatement(copy,   AATooltip, NSString *, pointFormat) 
AAPropStatementAndPropSetFuncStatement(copy,   AATooltip, NSString *, footerFormat) 
```

关键属性 `headerFormat`

参见 API 文档 https://api.highcharts.com.cn/en/highcharts/tooltip.headerFormat.html
