### ISSUE TITLE
能否隐藏x轴的线条，用标示线代替

### ISSUE THREAD

**Issue by Vutumn** [AAChartModel/AAChartKit#55]

**Comment by AAChartModel** [comment]
设置`AAChartModel`的属性`xAxisGridLineWidth`的值为`0`,即可隐藏*X轴*的网格线
```Objective-C
AAPropStatementAndFuncStatement(strong, AAChartModel, NSNumber *, xAxisGridLineWidth);//x 轴网格线的宽度
```

**Comment by Vutumn** [comment]
我的意思是自定义下面这个
![image](https://user-images.githubusercontent.com/7233176/31573621-ea25d0e2-b084-11e7-83d6-17000885b0b2.png)
想自定义它的颜色然后吧竖直的线去掉

**Comment by AAChartModel** [comment]
暂无自定义*X轴*颜色并和样式的功能.
