### ISSUE TITLE
AAFunnel.js  AAHighchartsLib.js  AAHighchartsMore.js文件内容自己编写的吗

### ISSUE THREAD

**Issue by Maling1255** [AAChartModel/AAChartKit#557]
有些疑惑 这三个js文件代码是从网络上下载的吗，怎么生成的？？  多谢了

**Comment by AAChartModel** [comment]
## 前言

 ***AAChartKit*** 项目,是[AAInfographics](https://github.com/AAChartModel/AAChartKit-Swift)的 `Objective-C` 语言版本,是在流行的开源前端图表库*Highcharts*的基础上,封装的面向对象的,一组简单易用,极其精美的图表绘制控件.可能是这个星球上 UI 最精致的第三方 iOS 开源图表库了(✟我以无神论者的名义向上帝起誓🖐,我真的没有在说鬼话✟)


以上内容来源于AAChartKit的README使用说明文档

                                                                                                                         

关键语句: 
>  是在流行的开源前端图表库_Highcharts_的基础上



所以,你说呢?!

**Comment by AAChartModel** [comment]
不过按照highCharts官方的开源协议来说,我这个项目似乎是有问题的.

**Comment by AAChartModel** [comment]
> 非商业使用免费
> 在个人网站、学校网站及非盈利机构中使用 Highcharts 完全不需要经过我们的许可，直接可以任意使用！

> 商业网站或网站，请查看我们的 使用协议及价格。

以上内容摘自highCharts官网声明


企业用于商业用途的使用highCharts是需要付费的,按理来说,在商业项目中使用AAChartKit时不适合的
