### ISSUE TITLE
一张图中的两条折线， 折点 相近时候的显示问题。

### ISSUE THREAD

**Issue by tipshot** [AAChartModel/AAChartKit#558]
如图，当两条折线的折点靠近的时候，只显示一个折点的数据，请问这个是否可以吧两个折点的数据都显示出来？
![image](https://user-images.githubusercontent.com/18547353/53217808-80793e80-3694-11e9-8a46-0eaaef5fb714.png)

**Comment by tipshot** [comment]
![image](https://user-images.githubusercontent.com/18547353/53866907-a1934500-402d-11e9-9f9e-b67492b43465.png)

**Comment by tipshot** [comment]
因为对代码不是太熟悉，并不知道在源码里面如何修改。烦请作者给与知道和支持。

**Comment by AAChartModel** [comment]
重复问题,参见 https://github.com/AAChartModel/AAChartKit/issues/707
