### ISSUE TITLE
X轴categories含有 ' 或者 ''  符号时,就是时间分秒的符号,不显示.

### ISSUE THREAD

**Issue by tipshot** [AAChartModel/AAChartKit#560]
X轴categories含有 ' 或者 ''  符号时,就是时间分秒的符号,不显示.

**Comment by tipshot** [comment]
就是在X轴上的数据源内容含有 ‘ 或者 ’‘ 的时候，X轴上的文字就不显示了，

**Comment by tipshot** [comment]
![image](https://user-images.githubusercontent.com/18547353/53724858-c8267400-3ea5-11e9-9d73-df8310988217.png)

**Comment by AAChartModel** [comment]
这是等于解决了吗?
