### ISSUE TITLE
Missing '@end'

### ISSUE THREAD

**Issue by xiaozymiao** [AAChartModel/AAChartKit#561]
AAChart拖到项目中之后会报错Missing '@end'

**Comment by AAChartModel** [comment]
没在.pch文件中导入AAChartKit的宏定义文件???

**Comment by xiaozymiao** [comment]
是的就是这个原因，谢谢你

我想在问一下，集成成功之后有几百多个警告信息，这个能避免吗

**Comment by AAChartModel** [comment]
参见 #498 #414
