### ISSUE TITLE
如何在dataSet数据个数不足时显示全部图表？

### ISSUE THREAD

**Issue by ywdonga** [AAChartModel/AAChartKit#578]
在实际使用的过程中发现，当dataSet的个数不足时 无法展示全部图表，而当dataSet为0是 x轴的文字都不见了。请问有什么方法可以设置为在任何时候都展示整个图表吗？

**Comment by AAChartModel** [comment]
使用 null 对象来占据一个空数据位置即可的到下图

![](https://user-images.githubusercontent.com/16357599/47836514-90b69680-dde3-11e8-9474-df6997dc0d56.png)

**Comment by AAChartModel** [comment]
参见 https://github.com/AAChartModel/AAChartKit/issues/475#issuecomment-434947020
