### ISSUE TITLE
现在想在数字后面加单位，这个目前有参数设置吗

### ISSUE THREAD

**Issue by Vutumn** [AAChartModel/AAChartKit#58]
好像现在只是传数据数组进去能识别，如何加个单位呢

**Comment by AAChartModel** [comment]
是要在浮动提示框后面添加单位后缀吗?

**Comment by AAChartModel** [comment]
设置 AAChartModel 的字符串属性tooltipValueSuffix内容,即可添加浮动提示框的代为后缀.
