### ISSUE TITLE
警告   导致图表加载不出来

### ISSUE THREAD

**Issue by a123478we** [AAChartModel/AAChartKit#580]
☠️☠️💀☠️☠️!!!!!WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______{
    code = 4;
    domain = WKErrorDomain;
    userInfo =     {
        NSLocalizedDescription = "A JavaScript exception occurred";
        WKJavaScriptExceptionColumnNumber = 21;
        WKJavaScriptExceptionLineNumber = 1;
        WKJavaScriptExceptionMessage = "ReferenceError: Can't find variable: loadTheHighChartView";
        WKJavaScriptExceptionSourceURL = "about:blank";
    };
}

**Comment by lidengjie** [comment]
我也出现了这个问题，但是图出来了！不知道什么原因

**Comment by AAChartModel** [comment]
重复问题,参见问题  #245
