### ISSUE TITLE
AATooltip如何在点击的时候更换自定义的数据？

### ISSUE THREAD

**Issue by ywdonga** [AAChartModel/AAChartKit#582]
大佬，AATooltip可以更新自定义的内容吗？就是每次点击改变AATooltip中的内容，并且这个要显示的内容与x轴y轴数据没有直接关系
![image](https://user-images.githubusercontent.com/16291063/55226918-1fbfc180-5251-11e9-9286-50f8b7f7ef52.png)

**Comment by AAChartModel** [comment]
使用 AATooltip 的 formatter 属性自定义 tooltip 显示内容即可.具体内容参见 AAChartKit 的 demo 中自定义 tooltip 的 formatter 的示例代码.
