### ISSUE TITLE
y值时间格式化成区间，stacking合并求和并格式化时分显示

### ISSUE THREAD

**Issue by 211Yang** [AAChartModel/AAChartKit#583]
![image](https://user-images.githubusercontent.com/5978235/55284412-adfa8b80-53a8-11e9-940a-4e0fabd1ce57.png)
这个效果如何实现，y值时间格式化成区间，x轴也显示时间，格式不一样，stacking合并求和并格式化时分显示，合并格式化js里面可以实现，但是你这里试了好像不行。求大神帮忙看下，拜托了🙏

`
tooltip.formatter = [[HIFunction alloc] initWithJSFunction:@"function () {return '<b>' + this.x + '</b><br/>' +this.series.name + ': ' + this.y + '<br/>' +'平均时长: ' +Highcharts.numberFormat(this.point.stackTotal/60,0)+'时'+ Highcharts.numberFormat(this.point.stackTotal%60,0)+'分';}"];
`

**Comment by AAChartModel** [comment]
问题已在 #569 中解决.
