### ISSUE TITLE
箱线图没有异常值吗

### ISSUE THREAD

**Issue by xiaoxiaohua** [AAChartModel/AAChartKit#593]
您好，箱线图没有异常值显示这个功能吗。。。急问，希望早日回复。谢谢

**Comment by AAChartModel** [comment]
箱线图的异常值是个什么东西?有设计稿效果图吗?

**Comment by xiaoxiaohua** [comment]
主要包含六个数据节点，将一组数据从大到小排列，分别计算出他的上边缘，上四分位数Q3，中位数，下四分位数Q1，下边缘，还有一个异常值(异常值可以有多个)。




数据异常值

 

一批数据中的异常值值得关注，忽视异常值的存在是十分危险的，不加剔除地把异常值包括进数据的计算分析过程中，对结果会带来不良影响；重视异常值的出现，分析其产生的原因，常常成为发现问题进而改进决策的契机。箱形图为我们提供了识别异常值的一个标准：异常值被定义为小于Q1－1.5IQR或大于Q3+1.5IQR的值。虽然这种标准有点任意性，但它来源于经验判断，经验表明它在处理需要特别注意的数据方面表现不错。这与识别异常值的经典方法有些不同。众所周知，基于正态分布的3σ法则或z分数方法是以假定数据服从正态分布为前提的，但实际数据往往并不严格服从正态分布。它们判断异常值的标准是以计算数据批的均值和标准差为基础的，而均值和标准差的耐抗性极小，异常值本身会对它们产生较大影响，这样产生的异常值个数不会多于总数0.7%。显然，应用这种方法于非正态分布数据中判断异常值，其有效性是有限的。箱形图的绘制依靠实际数据，不需要事先假定数据服从特定的分布形式，没有对数据作任何限制性要求，它只是真实直观地表现数据形状的本来面貌；另一方面，箱形图判断异常值的标准以四分位数和四分位距为基础，四分位数具有一定的耐抗性，多达25%的数据可以变得任意远而不会很大地扰动四分位数，所以异常值不能对这个标准施加影响，箱形图识别异常值的结果比较客观。由此可见，箱形图在识别异常值方面有一定的优越性





------------------ 原始邮件 ------------------
发件人: "An An"<notifications@github.com>;
发送时间: 2019年4月13日(星期六) 中午12:36
收件人: "AAChartModel/AAChartKit"<AAChartKit@noreply.github.com>;
抄送: "hua"<1319125931@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AAChartModel/AAChartKit] 箱线图没有异常值吗 (#593)




箱线图的异常值是个什么东西?有设计稿效果图吗?

**Comment by AAChartModel** [comment]
误差图参见此问题 https://github.com/AAChartModel/AAChartKit/issues/775
