### ISSUE TITLE
折线图多条线，点击线上的点，能不能区分是哪条线？

### ISSUE THREAD

**Issue by lszHub** [AAChartModel/AAChartKit#599]
现在category里面返回的是对应X轴的信息，能不能把对应的线的信息也返回来。
allowPointSelect这个属性能在柱状图和饼图里面使用，能不能支持在折线图使用。
”选中的点可以通过 Chart.getSelectedPoints 来获取“，这个没搞明白怎么用。
感谢作者

**Comment by AAChartModel** [comment]
>  ”选中的点可以通过 Chart.getSelectedPoints 来获取“

这句话从哪里来的?是我说的???

**Comment by lszHub** [comment]
额，AASeriesElement的allowPointSelect属性 你是这么注释的。比如现在折线图两个折线，我点其中的一个点能区分出是哪个么？求解答，感谢

**Comment by AAChartModel** [comment]
那我要改一下项目代码了,目前确实是不支持此功能.

**Comment by lszHub** [comment]
感谢大神，辛苦

**Comment by AAChartModel** [comment]
实现AAChartView的代理方法

```objc
- (void)AAChartView:(AAChartView *)chartView moveOverEventWithMessage:(AAMoveOverEventMessageModel *)message {
    NSLog(@"🚀selected point series element name: %@",message.name);
    NSLog(@"🦋🦋🦋🦋🦋 user finger moved over!!!,get the move over event message: %@",[AAJsonConverter jsonDictWithString:[AAJsonConverter getPureOptionsString:message]] );
}
```

`message.name`表示是选中的某一个AASeriesElement中的名称,通过这个名称就可以判断到底是那一条折线被点击了.

**Comment by AAChartModel** [comment]
最新的AAChartKit已添加了此示例代码

**Comment by lszHub** [comment]
牛逼👏
