### ISSUE TITLE
你好，请问柱形图和折线图的色值怎么修改？

### ISSUE THREAD

**Issue by mengjiahao22** [AAChartModel/AAChartKit#6]

**Comment by AAChartModel** [comment]
AAPropStatementAndFuncStatement(strong, AAChartModel, NSArray *, colorsTheme);//图表主题颜色数组属性
    self.colorsTheme =  @[@"#b5282a",@"#e7a701",@"#50c18d",@"#c37779",@"#f1c6c5"];//默认颜色数组
chartModel.colorTheme  = @[@"#b5332a",@"#e7a661",@"#50c88d",@"#c37339",@"#f1c225"]; 这样自定义设置颜色数组即可
