### ISSUE TITLE
图表加载不出来的问题

### ISSUE THREAD

**Issue by BaoLeiLi** [AAChartModel/AAChartKit#60]
您好，昨天我问您标题位置的修改，然后您做了一些修改，让我更新一下，我今天更新了一下，然后图表就加载不出来了

**Comment by AAChartModel** [comment]
控制台有什么输出报错吗?我这边是一切正常的啊

**Comment by AAChartModel** [comment]
https://github.com/AAChartModel/AAChartKit/commit/b67388e09c78d729a38d64d2ee7247a8f0db74c3
点击以上链接地址,其中内容是关于上一次`commit` 的全部内容,从中可以看到我只是对`AATitle`拓展了
1. verticalAlign
2.y
这两个属性,并未作其他改动.
您可以下载最新 Demo 本地运行查看是否有异常情况,你也可以再仔细查查是否还有其他干扰因素导致了图表无法加载的问题.
