### ISSUE TITLE
x轴如何显示少量数据？

### ISSUE THREAD

**Issue by NSMichael** [AAChartModel/AAChartKit#602]
![image](https://user-images.githubusercontent.com/3736158/56458312-90bd4980-63b7-11e9-8617-05ec72896e99.png)
你看我这个日期 显示的太多了啊，太难看，如何才能像下图一样，间隔一段距离

![image](https://user-images.githubusercontent.com/3736158/56458335-d1b55e00-63b7-11e9-9a2e-05092e49a2db.png)

**Comment by AAChartModel** [comment]
```objc     
//设置 X轴坐标点的间隔数,默认是1
//(手机端的屏幕较为狭窄, 如果X轴坐标点过多,
//文字过于密集的时候可以设置此属性值,用户的
//密集恐惧症将得到有效治疗😝) 
_aaChartModel.xAxisTickInterval = @3;
```

**Comment by tipshot** [comment]
swift版本还没加上去好像

**Comment by AAChartModel** [comment]
@tipshot 你通过 AAOptions 的 xAxis 属性来设置效果是一样的

**Comment by tipshot** [comment]
好的，非常感谢
