### ISSUE TITLE
设置 是否 堆积 的关键代码在哪里？

### ISSUE THREAD

**Issue by tipshot** [AAChartModel/AAChartKit#604]
![image](https://user-images.githubusercontent.com/18547353/56493163-ca5d9400-6520-11e9-8f4c-8672af126424.png)

**Comment by AAChartModel** [comment]
typedef NSString *AAChartStackingType;
AACHARTKIT_EXTERN AAChartStackingType const AAChartStackingTypeFalse;//无堆叠效果
AACHARTKIT_EXTERN AAChartStackingType const AAChartStackingTypeNormal;//常规堆叠效果
AACHARTKIT_EXTERN AAChartStackingType const AAChartStackingTypePercent;//百分比堆叠效果
