### ISSUE TITLE
你好，准星线的删除、准星线向内显示如何设置

### ISSUE THREAD

**Issue by AnriKaede** [AAChartModel/AAChartKit#606]

**Comment by YouMotherFucker** [comment]
什么叫准星线的删除？你指的是隐藏？什么又叫做准星线的向内显示？




| |
18256973864
|
|
邮箱：18256973864@163.com
|

Signature is customized by Netease Mail Master

在2019年04月24日 15:09，AnriKaede 写道：

**Comment by AnriKaede** [comment]
图片发到18256973864@163.com了

**Comment by AnriKaede** [comment]
因为网页js可以了

**Comment by AAChartModel** [comment]
你这种说话只说一半的情况,让我怎么帮你?
