### ISSUE TITLE
代理方法没走

### ISSUE THREAD

**Issue by MingSirZz** [AAChartModel/AAChartKit#611]
点击折线图的某个点时候没有走代理方法 
<img width="300" alt="WechatIMG61" src="https://user-images.githubusercontent.com/24559141/56875136-5c115800-6a71-11e9-80ce-979fcc0e6cbc.png">

下面这个方法没有执行

```objc
-(void)AAChartView:(AAChartView *)chartView moveOverEventWithMessage:(AAMoveOverEventMessageModel *)message
{
    BYLog(@"%@~~~%@",chartView,message);
}
```

**Comment by AAChartModel** [comment]
AAChartKit的demo中点击事件运行正常吗? 控制台是否有输出?

**Comment by MingSirZz** [comment]
我刚才看demo是正常的有输出，但是我拉到项目中的就是不执行这个方法，我也是没搞懂什么情况，
<img width="379" alt="WechatIMG62" src="https://user-images.githubusercontent.com/24559141/56875629-b06a0700-6a74-11e9-8c39-0de754238ce7.png">

**Comment by MingSirZz** [comment]
你需要看代码的话我发你一份....真给我整懵逼了，时间比较紧急不能换别的了😅

**Comment by RanBingle** [comment]
我这儿也是，不走代理方法。请问你找到方法解决了吗？

**Comment by RanBingle** [comment]
> 我这儿也是，不走代理方法。请问你找到方法解决了吗？


    发现了，原来没添加这一句代码：.touchEventEnabledSet(true)//支持用户点击事件
