### ISSUE TITLE
moveOverEventWithMessage这个方法是只要手指滑到就会走

### ISSUE THREAD

**Issue by wangleios** [AAChartModel/AAChartKit#619]
我要实现功能是点击横向柱状图的某一项来刷新tableview数据,然后滑动tableview会触发moveOverEventWithMessage这个回调,有没有点击柱状图的某一列的回调方法,我看了demo里的实现方式,那个方式应该确定柱状图的宽度和item数量,那么柱状图的宽度怎么给个死值,或者作者有没有比较好的解决方案

**Comment by AAChartModel** [comment]
其实 moveOverEventWithMessage 这个代理回调方法只要手指滑动或者点击都会触发

**Comment by AAChartModel** [comment]
> 我看了demo里的实现方式,那个方式应该确定柱状图的宽度和item数量

moveOverEventWithMessage 这个方法的触发条件和 `柱状图的宽度和item数量`并没有什么关系

**Comment by wangleios** [comment]
谢谢回复,demo里的另一种实现方式是给chart加了个tap事件 ..moveOverEventWithMessage这个回调手指滑动会和tableview滑动会同时触发,所以我想要只有点击的回调 ,这种情况是不是只能和demo一样加tap事件了

**Comment by AAChartModel** [comment]
其实highCharts有单独的只相应点击事件的回调方法,只是我目前还没有添加到AAChartKit中.恐怕要到周末才能狗有时间加上此功能了

**Comment by wangleios** [comment]
哦哦,感谢大佬抽空回复,有了这个方法就可以解决我这边的问题了,再次谢谢了

**Comment by ccBlus** [comment]
请问作者现在加上单独点击触发事件的功能了吗

**Comment by AAChartModel** [comment]
@ccBlus 抱歉,暂未添加单独点击触发事件功能

**Comment by ccBlus** [comment]
> @ccBlus 抱歉,暂未添加单独点击触发事件功能

那请问有没有好的解决方法，可以实现这个效果呢，谢谢
