### ISSUE TITLE
饼状图设置@{@"legendItemClick":@"false"}  不起作用

### ISSUE THREAD

**Issue by wangleios** [AAChartModel/AAChartKit#620]
图例还是可以点击.只有饼状图这样设置不起作用

**Comment by DogTwoChen** [comment]
请问解决了吗,遇到同样的问题

**Comment by AAChartModel** [comment]
https://api.highcharts.com.cn/highcharts#plotOptions.pie.events.legendItemClick

>  Not applicable to pies, as the legend item is per point. See point.events.

不适用于馅饼，因为图例的item是每个点。参见point.events。

**Comment by DogTwoChen** [comment]
哦哦,因为在使用饼图的时候发现了bug,点击下面的图例的时候,有时候引线旁边的数据会不显示
![361566892484_ pic](https://user-images.githubusercontent.com/18676761/63752018-05167500-c8e3-11e9-8b0f-52aa62e77d8d.jpg)
![351566892464_ pic](https://user-images.githubusercontent.com/18676761/63752021-06e03880-c8e3-11e9-8e85-8ba6e566e52b.jpg)

**Comment by gaoguanbao** [comment]
> https://api.highcharts.com.cn/highcharts#plotOptions.pie.events.legendItemClick
> 
> > Not applicable to pies, as the legend item is per point. See point.events.
> 
> 不适用于饼状图，因为图例的item是每个点。参见point.events。


调试了一下 下面代码的这种实现方式是可以适用饼状图的  但是应用到项目里面却无法适用  还请作者指导一下
Highcharts.chart('container', {
	chart: {
		type: 'pie'
	},
	legend: {
		enabled: true,
	},
	series: [{
		data: [{name:1,y:29.9,events: {
			legendItemClick: function () {
				return false;
			}
		}},{name:2,y:71.5,events: {
			legendItemClick: function () {
				return false;
			}
		}}, {name:3,y:106.4}],
		showInLegend:true
	}]
});

**Comment by gaoguanbao** [comment]
调试了一下 下面代码的这种实现方式是可以适用饼状图的 但是应用到项目里面却无法适用 还请作者指导一下
Highcharts.chart('container', {
chart: {
type: 'pie'
},
legend: {
enabled: true,
},
series: [{
data: [{name:1,y:29.9,events: {
legendItemClick: function () {
return false;
}
}},{name:2,y:71.5,events: {
legendItemClick: function () {
return false;
}
}}, {name:3,y:106.4}],
showInLegend:true
}]
});

**Comment by AAChartModel** [comment]
@gaoguanbao 请问你的CocoaPods 的 AAChartKit 的是最新版本的吗? 旧版本的 AAChartKit 不支持 `legendItemClick `的 JavaScript 函数,但是最新版本的 AAChartKit 已经支持了此功能.
