### ISSUE TITLE
请问饼状图线的文字不显示是什么原因?如图

### ISSUE THREAD

**Issue by wangleios** [AAChartModel/AAChartKit#621]
![WechatIMG33](https://user-images.githubusercontent.com/16556063/57822994-8e88b800-77c8-11e9-8dc8-d7a16998f8de.jpeg)

**Comment by AAChartModel** [comment]
可能是这个问题 #600 

另:下次有问题请用📱手机或 💻电脑直接截图上传,不要拍照,这种拍照效果视图模糊,画面歪斜,观看体验极差

**Comment by wangleios** [comment]
抱歉啊.这个手机是公司测试机,wx,qq都没登录

**Comment by wangleios** [comment]
您好,我按以下代码设置
 aaOptions.plotOptions.pie.dataLabels.allowOverlap = true;
  [_circleView aa_refreshChartWithOptions:aaOptions];
不起作用
