### ISSUE TITLE
折线图，点击折线会变粗，这个怎么去掉效果

### ISSUE THREAD

**Issue by wuxuezhen** [AAChartModel/AAChartKit#624]
折线图，点击折线会变粗，这个怎么去掉效果

**Comment by HobaoKing** [comment]
解决了吗? 怎么弄的

**Comment by wuxuezhen** [comment]
没有




| |
xzzhenw
邮箱：xzzhenw@163.com
|

Signature is customized by Netease Mail Master

在2019年08月31日 14:07，Jeff.Wang 写道：

解决了吗? 怎么弄的

**Comment by dengxingwen** [comment]
同问

**Comment by pcjbird** [comment]
the same

**Comment by NashAnd** [comment]
the same

**Comment by AAChartModel** [comment]
问题已解决,参见 #864

**Comment by AAChartModel** [comment]
参见更简洁的方法 https://github.com/AAChartModel/AAChartKit/issues/948
