### ISSUE TITLE
xAxisTickInterval这个属性如何在swift中使用？

### ISSUE THREAD

**Issue by Maxcucurbit** [AAChartModel/AAChartKit#638]
没有对应的属性，我要怎样设置呢

**Comment by AAChartModel** [comment]
```swift
        let aaOptions = AAOptionsConstructor.configureAAoptions(aaChartModel: aaChartModel)
        let aaXAxis = aaOptions["xAxis"] as! NSMutableDictionary
        aaXAxis["tickInterval"] = 3
```

**Comment by Maxcucurbit** [comment]
> ```swift
>     let aaOptions = AAOptionsConstructor.configureAAoptions(aaChartModel: aaChartModel)
>     let aaXAxis = aaOptions["xAxis"] as! NSMutableDictionary
>     aaXAxis["tickInterval"] = 3 //设置x轴刻度间隔为3
> ```

完美，谢谢！
