### ISSUE TITLE
当数据中出现单个英文单引号的时候会报错。

### ISSUE THREAD

**Issue by zhanghua1802** [AAChartModel/AAChartKit#640]
```java
☠️☠️💀☠️☠️!!!!!WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______{
 code = 4;
 userInfo = {
 WKJavaScriptExceptionLineNumber = 1;
 WKJavaScriptExceptionMessage = SyntaxError: Unexpected identifier 'S'. Expected ')' to end an argument list.;
 WKJavaScriptExceptionColumnNumber = 0;
 WKJavaScriptExceptionSourceURL = file:///Users/zhanghua/Library/Developer/CoreSimulator/Devices/0FB4DBEA-52B2-441C-AD51-7060CF902E01/data/Containers/Bundle/Application/5DE67D84-1B17-4A2A-96CF-055633A9C9C4/BoJunKanKan.app/AAChartKitLib.bundle/AAJSFiles.bundle/AAChartView.html;
 NSLocalizedDescription = A JavaScript exception occurred;
}
;
 domain = WKErrorDomain;
}
```
![image](https://user-images.githubusercontent.com/17582847/58937371-ce7a0400-87a4-11e9-9c91-b084e5a24f86.png)

我暂时把问题解决了先简单的解决了一下，iOS好像也用不到单引号。

**Comment by AAChartModel** [comment]
我在AATooltip的formatter属性的setter方法和block方法里面有写过去除单引号

```objc
- (void)setFormatter:(NSString *)formatter {
    _formatter = [self getFinalJSFuncStringWithString:formatter];
}

- (AATooltip * (^) (NSString * formatter))formatterSet {
    return ^(NSString * formatter) {
        _formatter = [self getFinalJSFuncStringWithString:formatter];
        return self;
    };
}

- (NSString *)getFinalJSFuncStringWithString:(NSString *)jsString {
    NSString *finalJSFunc = [NSString stringWithFormat:@"(%@)",jsString];
    finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"'" withString:@"\""];
    finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\0" withString:@""];
    finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\n" withString:@""];
    finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\\" withString:@"\\\\"];
    finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\"" withString:@"\\\""];
    finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\'" withString:@"\\\'"];
    finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\n" withString:@"\\n"];
    finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\r" withString:@"\\r"];
    finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\f" withString:@"\\f"];
    finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\u2028" withString:@"\\u2028"];
    finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\u2029" withString:@"\\u2029"];
    return finalJSFunc;
}

不过数据里面会有出现单引号的情况倒是还没有遇到过.
```

**Comment by zhanghua1802** [comment]
> 我在AATooltip的formatter属性的setter方法和block方法里面有写过去除单引号
> 
> ```objc
> - (void)setFormatter:(NSString *)formatter {
>     _formatter = [self getFinalJSFuncStringWithString:formatter];
> }
> 
> - (AATooltip * (^) (NSString * formatter))formatterSet {
>     return ^(NSString * formatter) {
>         _formatter = [self getFinalJSFuncStringWithString:formatter];
>         return self;
>     };
> }
> 
> - (NSString *)getFinalJSFuncStringWithString:(NSString *)jsString {
>     NSString *finalJSFunc = [NSString stringWithFormat:@"(%@)",jsString];
>     finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"'" withString:@"\""];
>     finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\0" withString:@""];
>     finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\n" withString:@""];
>     finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\\" withString:@"\\\\"];
>     finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\"" withString:@"\\\""];
>     finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\'" withString:@"\\\'"];
>     finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\n" withString:@"\\n"];
>     finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\r" withString:@"\\r"];
>     finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\f" withString:@"\\f"];
>     finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\u2028" withString:@"\\u2028"];
>     finalJSFunc = [finalJSFunc stringByReplacingOccurrencesOfString:@"\u2029" withString:@"\\u2029"];
>     return finalJSFunc;
> }
> ```
> 
> 不过数据里面会有出现单引号的情况倒是还没有遇到过.

就是类似I‘m OK、That's all right之类的，有个品牌名字叫that's all。

**Comment by Choice-Fei** [comment]
我这是x轴坐标有单引号，报错。。。心态炸裂
<img width="488" alt="image" src="https://user-images.githubusercontent.com/13918369/91157290-b539dc00-e6f7-11ea-89ab-76c92532ef99.png">
