### ISSUE TITLE
如何自定义浮动提示框tooltip中formatter属性？（重点：如何修改字体颜色）

### ISSUE THREAD

**Issue by wanderingsoulsdc** [AAChartModel/AAChartKit#647]
如图，在同一图表中有两条折线图，代表的物种不同，导致后面所需要的后缀也不相同。
请问我该如何进行设置才能实现?

**Comment by wanderingsoulsdc** [comment]
![20190618190142](https://user-images.githubusercontent.com/31684709/59677418-60016100-91fc-11e9-9604-f9c037fe2c44.jpg)

**Comment by wanderingsoulsdc** [comment]
![20190618190142](https://user-images.githubusercontent.com/31684709/59677418-60016100-91fc-11e9-9604-f9c037fe2c44.jpg)

**Comment by wanderingsoulsdc** [comment]
self.aaOptions.tooltip = AAObject(AATooltip)
    .useHTMLSet(true)
    .formatterSet(@AAJSFunc(function () {
        return ' 🌕 🌖 🌗 🌘🌑 🌒 🌓 🌔 <br/> '
        + ' Support JavaScript Function Just Right Now !!! <br/> '
        + ' The Gold Price For <b>2020 '
        +  this.x
        + ' </b> Is <b> '
        + this.y
        + ' </b> Is <b> '
        + this.series.name
        + ' </b> Dollars ';
        
    }))

**Comment by wanderingsoulsdc** [comment]
formatterSet(@AAJSFunc(function () {
        
        var s = '<b>' + this.x + '</b>';
        if(this.points[0].series.name == 'dogs') {
            s += '<br/>' + this.points[0].series.name + ': ' + this.points[0].y + '只';
        }else{
            s += '<br/>' + this.points[0].series.name + ': ' + this.points[0].y;
        }
        
        if(this.points[1].series.name == 'trees') {
            s += '<br/>' + this.points[1].series.name + ': ' + this.points[1].y + '棵';
        }else{
            s += '<br/>' + this.points[1].series.name + ': ' + this.points[1].y;
        }
        
        return s;
        
    }))

通过查阅highchart文档已解决，感谢

**Comment by wanderingsoulsdc** [comment]
highchart文档支持添加提示前面的点并改变颜色，但我在上面function中添加直接报错不会生成图表
formatterSet(@AAJSFunc(function () {

    var s = '<b>' + this.x + '</b>';
    s += '<span style="color: blue;">\u25CF </span>';
    if(this.points[0].series.name == 'dogs') {
        s += '<br/>' + this.points[0].series.name + ': ' + this.points[0].y + '只';
    }else{
        s += '<br/>' + this.points[0].series.name + ': ' + this.points[0].y;
    }
    
    if(this.points[1].series.name == 'trees') {
        s += '<br/>' + this.points[1].series.name + ': ' + this.points[1].y + '棵';
    }else{
        s += '<br/>' + this.points[1].series.name + ': ' + this.points[1].y;
    }
    
    return s;
    
}))
报错信息如下：
AAChartView.m [Line 332] 
☠️☠️💀☠️☠️!!!!!WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______{
    code = 4;
    domain = WKErrorDomain;
    userInfo =     {
        NSLocalizedDescription = "\U53d1\U751f JavaScript \U5f02\U5e38";
        WKJavaScriptExceptionColumnNumber = 55;
        WKJavaScriptExceptionLineNumber = 53;
        WKJavaScriptExceptionMessage = "SyntaxError: Unexpected identifier 'color'";
        WKJavaScriptExceptionSourceURL = "file:///var/containers/Bundle/Application/E9A2B3BE-F856-466F-83CD-8A5FF802AC5C/osec.app/AAJSFiles.bundle/AAChartView.html";
    };
}


但我在highcharts中formatter 的api文档实例中：是可行的 如下图
<img width="500" alt="WeChat349e72b7e4ab22ecb46f92bf4cf3036a" src="https://user-images.githubusercontent.com/31684709/59750217-04dd7600-92b1-11e9-9caf-a7843794e845.png">

**Comment by AAChartModel** [comment]
在highcharts中formatter 的在线示例中这样配置
```js
var chart = Highcharts.chart('container', {
	title: {
		text: '2014 ~ 2020 汪星人生存指数'
	},
	subtitle: {
		text: '数据来源：www.无任何可靠依据.com'
	},
	yAxis: {
		title: {
			text: '数量'
		}
	},
	tooltip:{
		shared:true,
		formatter: function () {
			var s = '第' + '<b>' +  this.x + '</b>' + '年' + '<br/>';
			let colorDot1 = '<span style=\"' + 'color:red; font-size:13px\"' + '>◉</span> ';
			let colorDot2 = '<span style=\"' + 'color:blue; font-size:13px\"' + '>◉</span> ';
			let s1 = colorDot1  + this.points[0].series.name + ': ' + this.points[0].y + '只' + '<br/>';
			let s2 =  colorDot2 + this.points[1].series.name + ': ' + this.points[1].y + '棵';
			s += s1 + s2;
			return s;
		},
	},
	series: [{
		name: '🐶狗子',
		data: [43934, 52503, 57177, 69658, 97031, 119931, 137133, 154175]
	}, {
		name: '🌲树木',
		data: [24916, 24064, 29742, 29851, 32490, 30282, 38121, 40434]
	},  ],
});
```

得到的结果如下
![image](https://user-images.githubusercontent.com/16357599/59817296-f1ceb280-9351-11e9-9322-303c4247815a.png)

**Comment by AAChartModel** [comment]
在AAChartKit的demo中这样配置AAOptions:

```js
        NSDictionary *gradientColorDic1 =
        [AAGradientColor configureGradientColorWithDirection:AALinearGradientDirectionToTop
                                            startColorString:@"rgba(256,0,0,0.3)"//颜色字符串设置支持十六进制类型和 rgba 类型
                                              endColorString:@"rgba(256,0,0,1.0)"];
        
        NSDictionary *gradientColorDic2 =
        [AAGradientColor configureGradientColorWithDirection:AALinearGradientDirectionToTop
                                            startColorString:@"rgba(0,0,256,0.3)"//颜色字符串设置支持十六进制类型和 rgba 类型
                                              endColorString:@"rgba(0,0,256,1.0)"];
        
        AAChartModel *aaChartModel = AAChartModel.new
        .chartTypeSet(AAChartTypeArea)//图表类型
        .titleSet(@"2014 ~ 2020 汪星人生存指数")//图表主标题
        .subtitleSet(@"数据来源：www.无任何可靠依据.com")//图表副标题
        .markerSymbolStyleSet(AAChartSymbolStyleTypeInnerBlank)//折线连接点样式为内部白色
        .stackingSet(AAChartStackingTypeNormal)
        //    .xAxisTickIntervalSet(@15)//x轴刻度点间隔数(设置每隔几个点显示一个 X轴的内容)
        .yAxisTitleSet(@"")//设置 Y 轴标题
        .yAxisGridLineWidthSet(@0.8)//y轴横向分割线宽度(为0即是隐藏分割线)
        .seriesSet(@[
                     AASeriesElement.new
                     .lineWidthSet(@1.5)
                     .colorSet((id)gradientColorDic1)
                     .nameSet(@"🐶狗子")
                     .dataSet(@[@43934, @52503, @57177, @69658, @97031, @119931, @137133, @154175]),
                     AASeriesElement.new
                     .lineWidthSet(@1.5)
                     .colorSet((id)gradientColorDic2)
                     .nameSet(@"🌲树木")
                     .dataSet(@[@24916, @24064, @29742, @29851, @32490, @30282, @38121, @40434]),
                     ]
                   );
        /*Custom Tooltip Style --- 自定义图表浮动提示框样式及内容*/
        AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
        aaOptions.tooltip
        .useHTMLSet(true)
        .formatterSet(@AAJSFunc(function () {
            var s = '第' + '<b>' +  this.x + '</b>' + '年' + '<br/>';
            let colorDot1 = '<span style=\"' + 'color:red; font-size:13px\"' + '>◉</span> ';
            let colorDot2 = '<span style=\"' + 'color:blue; font-size:13px\"' + '>◉</span> ';
            let s1 = colorDot1  + this.points[0].series.name + ': ' + this.points[0].y + '只' + '<br/>';
            let s2 =  colorDot2 + this.points[1].series.name + ': ' + this.points[1].y + '棵';
            s += s1 + s2;
            return s;
        }))
        ;
        return aaOptions;
```
即可得到
![image](https://user-images.githubusercontent.com/16357599/59817389-3b1f0200-9352-11e9-95d8-122266cb300b.png)

**Comment by AAChartModel** [comment]
> ```js
>     s += '<span style="color: blue;">\u25CF </span>';
>     if(this.points[0].series.name == 'dogs') {
>         s += '<br/>' + this.points[0].series.name + ': ' + this.points[0].y + '只';
>     }else{
>         s += '<br/>' + this.points[0].series.name + ': ' + this.points[0].y;
>     }
>     
>     if(this.points[1].series.name == 'trees') {
>         s += '<br/>' + this.points[1].series.name + ': ' + this.points[1].y + '棵';
>     }else{
>         s += '<br/>' + this.points[1].series.name + ': ' + this.points[1].y;
>     }
>     
>     return s;
>     
> }))
> ```

你这里的配置失败的主要原因就是
```html
 '<span style="color: blue;">\u25CF </span>'
```
字符串引号里面又嵌套了一层引号,导致有点问题,

即便是像👇下面这样,对里面的双引号加上`\`转义字符也不行,
```html
 '<span style=\"color: blue;\">\u25CF </span>'
```
具体原因我也不甚清楚.

```js
 let colorDot1 = '<span style=\"' + 'color:red; font-size:13px\"' + '>◉</span> ';
```
我上面的这种做法就是内部的双引号拆开,同时加上`\`转义字符,避免引号多层嵌套,就可以了.

**Comment by AAChartModel** [comment]
> 在highcharts中formatter 的在线示例中这样配置
> 
> ```js
> var chart = Highcharts.chart('container', {
> 	title: {
> 		text: '2014 ~ 2020 汪星人生存指数'
> 	},
> 	subtitle: {
> 		text: '数据来源：www.无任何可靠依据.com'
> 	},
> 	yAxis: {
> 		title: {
> 			text: '数量'
> 		}
> 	},
> 	tooltip:{
> 		shared:true,
> 		formatter: function () {
> 			var s = '第' + '<b>' +  this.x + '</b>' + '年' + '<br/>';
> 			let colorDot1 = '<span style=\"' + 'color:red; font-size:13px\"' + '>◉</span> ';
> 			let colorDot2 = '<span style=\"' + 'color:blue; font-size:13px\"' + '>◉</span> ';
> 			let s1 = colorDot1  + this.points[0].series.name + ': ' + this.points[0].y + '只' + '<br/>';
> 			let s2 =  colorDot2 + this.points[1].series.name + ': ' + this.points[1].y + '棵';
> 			s += s1 + s2;
> 			return s;
> 		},
> 	},
> 	series: [{
> 		name: '🐶狗子',
> 		data: [43934, 52503, 57177, 69658, 97031, 119931, 137133, 154175]
> 	}, {
> 		name: '🌲树木',
> 		data: [24916, 24064, 29742, 29851, 32490, 30282, 38121, 40434]
> 	},  ],
> });
> ```
> 
> 得到的结果如下
> ![image](https://user-images.githubusercontent.com/16357599/59817296-f1ceb280-9351-11e9-9322-303c4247815a.png)


重点内容
```html
 let colorDot1 = '<span style=\"' + 'color:red; font-size:13px\"' + '>◉</span> ';
```
我上面的这种做法就是内部的双引号拆开,同时加上`\`转义字符,避免引号多层嵌套,就可以了.

**Comment by AAChartModel** [comment]
> highchart文档支持添加提示前面的点并改变颜色，但我在上面function中添加直接报错不会生成图表
> 
> ```js
> formatterSet(@AAJSFunc(function () {
> 
>     var s = '<b>' + this.x + '</b>';
>     s += '<span style="color: blue;">\u25CF </span>';
>     if(this.points[0].series.name == 'dogs') {
>         s += '<br/>' + this.points[0].series.name + ': ' + this.points[0].y + '只';
>     }else{
>         s += '<br/>' + this.points[0].series.name + ': ' + this.points[0].y;
>     }
>     
>     if(this.points[1].series.name == 'trees') {
>         s += '<br/>' + this.points[1].series.name + ': ' + this.points[1].y + '棵';
>     }else{
>         s += '<br/>' + this.points[1].series.name + ': ' + this.points[1].y;
>     }
>     
>     return s;
>     
> }))
> ```
> 
> 报错信息如下：
> 
> ```js
> AAChartView.m [Line 332] 
> ☠️☠️💀☠️☠️!!!!!WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______{
>     code = 4;
>     domain = WKErrorDomain;
>     userInfo =     {
>         NSLocalizedDescription = "\U53d1\U751f JavaScript \U5f02\U5e38";
>         WKJavaScriptExceptionColumnNumber = 55;
>         WKJavaScriptExceptionLineNumber = 53;
>         WKJavaScriptExceptionMessage = "SyntaxError: Unexpected identifier 'color'";
>         WKJavaScriptExceptionSourceURL = "file:///var/containers/Bundle/Application/E9A2B3BE-F856-466F-83CD-8A5FF802AC5C/osec.app/AAJSFiles.bundle/AAChartView.html";
>     };
> }
> ```
> 
> 但我在highcharts中formatter 的api文档实例中：是可行的 如下图
> <img alt="WeChat349e72b7e4ab22ecb46f92bf4cf3036a" width="500" src="https://user-images.githubusercontent.com/31684709/59750217-04dd7600-92b1-11e9-9caf-a7843794e845.png">

另外你的这个formatter的function的分支条件判断多余了,其实不用弄得这么复杂.
像这样简单处理就可以了

```js
    function () {
        var s = '第' + '<b>' +  this.x + '</b>' + '年' + '<br/>';
        let colorDot1 = '<span style=\"' + 'color:red; font-size:13px\"' + '>◉</span> ';
        let colorDot2 = '<span style=\"' + 'color:blue; font-size:13px\"' + '>◉</span> ';
        let s1 = colorDot1  + this.points[0].series.name + ': ' + this.points[0].y + '只' + '<br/>';
        let s2 =  colorDot2 + this.points[1].series.name + ': ' + this.points[1].y + '棵';
        s += s1 + s2;
        return s;
    }
```

**Comment by wanderingsoulsdc** [comment]
好的好的，非常感谢回复，我先实际操作一下。
