### ISSUE TITLE
toolTip中数值为0数据怎么才能不显示？

### ISSUE THREAD

**Issue by Zhendeshede** [AAChartModel/AAChartKit#651]

**Comment by AAChartModel** [comment]
你可以在通过AATooltip属性`formatter`来自定义tooltip内容.`formatter`是JavaScript函数,你可以通过JavaScript来过滤为0的数据,使其不被显示.

**Comment by Zhendeshede** [comment]
问题是在不会写JS，web开发人员也不会

**Comment by AAChartModel** [comment]
这个不难.你把你这边的示例数据贴出来一下,我根据你的示例数据改改.

**Comment by Zhendeshede** [comment]
.seriesSet(@[
                 AASeriesElement.new
                 .nameSet(@"上市")
                 .dataSet(@[@0,@0,@0]),
                 AASeriesElement.new
                 .nameSet(@"终止")
                 .dataSet(@[@4,@5,@1]),
                 AASeriesElement.new
                 .nameSet(@"无进展")
                 .dataSet(@[@2,@0,@1]),
                 AASeriesElement.new
                 .nameSet(@"进行中")
                 .dataSet(@[@3,@5,@2]),
                 ]);

如果‘无进展’数据为0，会显示“无进展:0”,我希望它不显示，当数据不为0时再显示。

**Comment by Zhendeshede** [comment]
.categoriesSet(@[@"临床一期",@"临床二期",@"临床三期"])

**Comment by AAChartModel** [comment]
1. 配置AAOptions实例对象

```js
 AAChartModel *aaChartModel = AAChartModel.new
    .chartTypeSet(AAChartTypeLine)//图表类型
    .titleSet(@"")//图表主标题
    .subtitleSet(@"")//图表副标题
    .colorsThemeSet(@[@"red",@"mediumspringgreen",@"deepskyblue",@"sandybrown"])//设置主体颜色数组
    .markerSymbolStyleSet(AAChartSymbolStyleTypeBorderBlank)//折线连接点样式为外边缘空白
    .yAxisTitleSet(@"")//设置 Y 轴标题
    .yAxisGridLineWidthSet(@0.8)//y轴横向分割线宽度(为0即是隐藏分割线)
    .categoriesSet(@[@"临床一期",@"临床二期",@"临床三期"])
    .markerRadiusSet(@8.0)
    .xAxisCrosshairDashStyleTypeSet(AALineDashStyleTypeDashDot)
    .xAxisCrosshairWidthSet(@1.0)
    .xAxisCrosshairColorSet(AAColor.darkGrayColor)
    .seriesSet(@[
                 AASeriesElement.new
                 .nameSet(@"上市")
                 .dataSet(@[@0,@0,@7]),
                 AASeriesElement.new
                 .nameSet(@"终止")
                 .dataSet(@[@4,@5,@1]),
                 AASeriesElement.new
                 .nameSet(@"无进展")
                 .dataSet(@[@2,@0,@1]),
                 AASeriesElement.new
                 .nameSet(@"进行中")
                 .dataSet(@[@3,@5,@2]),
                 ]
               );
    
    
    /*Custom Tooltip Style --- 自定义图表浮动提示框样式及内容*/
    AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
    aaOptions.tooltip
    .useHTMLSet(true)
    .formatterSet(@AAJSFunc(function () {
        let colorDot0 = '<span style=\"' + 'color:red; font-size:13px\"' + '>◉</span> ';
        let colorDot1 = '<span style=\"' + 'color:mediumspringgreen; font-size:13px\"' + '>◉</span> ';
        let colorDot2 = '<span style=\"' + 'color:deepskyblue; font-size:13px\"' + '>◉</span> ';
        let colorDot3 = '<span style=\"' + 'color:sandybrown; font-size:13px\"' + '>◉</span> ';
        let colorDotArr = [];
        colorDotArr.push(colorDot0);
        colorDotArr.push(colorDot1);
        colorDotArr.push(colorDot2);
        colorDotArr.push(colorDot3);
        let wholeContentString = this.points[0].x + '<br/>';
        for (let i = 0;i < 4;i++) {
            let yValue = this.points[i].y;
            if (yValue != 0) {
                let prefixStr = colorDotArr[i];
                wholeContentString += prefixStr + this.points[i].series.name + ': ' + this.points[i].y + '<br/>';
            }
        }
        return wholeContentString;
    }))
    ;
```
2. 最终效果图
![image](https://user-images.githubusercontent.com/16357599/59846747-49414280-9393-11e9-9edf-94369d8ece79.png)

**Comment by AAChartModel** [comment]
这里上市数据被我改成了
```js
AASeriesElement.new
                 .nameSet(@"上市")
                 .dataSet(@[@0,@0,@7]),
```
图表看起来稍微好看一点,值为非0和0时的显隐性对比也更加明显一点了

**Comment by Zhendeshede** [comment]
非常感谢

**Comment by AAChartModel** [comment]
> 1. 配置AAOptions实例对象
> 
> ```js
>  AAChartModel *aaChartModel = AAChartModel.new
>     .chartTypeSet(AAChartTypeLine)//图表类型
>     .titleSet(@"")//图表主标题
>     .subtitleSet(@"")//图表副标题
>     .colorsThemeSet(@[@"red",@"mediumspringgreen",@"deepskyblue",@"sandybrown"])//设置主体颜色数组
>     .markerSymbolStyleSet(AAChartSymbolStyleTypeBorderBlank)//折线连接点样式为外边缘空白
>     .yAxisTitleSet(@"")//设置 Y 轴标题
>     .yAxisGridLineWidthSet(@0.8)//y轴横向分割线宽度(为0即是隐藏分割线)
>     .categoriesSet(@[@"临床一期",@"临床二期",@"临床三期"])
>     .markerRadiusSet(@8.0)
>     .xAxisCrosshairDashStyleTypeSet(AALineDashStyleTypeDashDot)
>     .xAxisCrosshairWidthSet(@1.0)
>     .xAxisCrosshairColorSet(AAColor.darkGrayColor)
>     .seriesSet(@[
>                  AASeriesElement.new
>                  .nameSet(@"上市")
>                  .dataSet(@[@0,@0,@7]),
>                  AASeriesElement.new
>                  .nameSet(@"终止")
>                  .dataSet(@[@4,@5,@1]),
>                  AASeriesElement.new
>                  .nameSet(@"无进展")
>                  .dataSet(@[@2,@0,@1]),
>                  AASeriesElement.new
>                  .nameSet(@"进行中")
>                  .dataSet(@[@3,@5,@2]),
>                  ]
>                );
>     
>     
>     /*Custom Tooltip Style --- 自定义图表浮动提示框样式及内容*/
>     AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
>     aaOptions.tooltip
>     .useHTMLSet(true)
>     .formatterSet(@AAJSFunc(function () {
>         let colorDot0 = '<span style=\"' + 'color:red; font-size:13px\"' + '>◉</span> ';
>         let colorDot1 = '<span style=\"' + 'color:mediumspringgreen; font-size:13px\"' + '>◉</span> ';
>         let colorDot2 = '<span style=\"' + 'color:deepskyblue; font-size:13px\"' + '>◉</span> ';
>         let colorDot3 = '<span style=\"' + 'color:sandybrown; font-size:13px\"' + '>◉</span> ';
>         let colorDotArr = [];
>         colorDotArr.push(colorDot0);
>         colorDotArr.push(colorDot1);
>         colorDotArr.push(colorDot2);
>         colorDotArr.push(colorDot3);
>         let wholeContentString = this.points[0].x + '<br/>';
>         for (let i = 0;i < 4;i++) {
>             let yValue = this.points[i].y;
>             if (yValue != 0) {
>                 let prefixStr = colorDotArr[i];
>                 wholeContentString += prefixStr + this.points[i].series.name + ': ' + this.points[i].y + '<br/>';
>             }
>         }
>         return wholeContentString;
>     }))
>     ;
> ```
> 
> 1. 最终效果图
>    ![image](https://user-images.githubusercontent.com/16357599/59846747-49414280-9393-11e9-9edf-94369d8ece79.png)

## 以下是`formatter`最新更简洁干净, 更通用的写法

```objc
- (AAOptions *)customLineChartTooltipStyleWhenValueBeZeroDoNotShow {
    AAChartModel *aaChartModel = AAChartModel.new
    .chartTypeSet(AAChartTypeLine)//图表类型
    .colorsThemeSet(@[@"red",@"mediumspringgreen",@"deepskyblue",@"sandybrown"])//设置主体颜色数组
    .markerSymbolStyleSet(AAChartSymbolStyleTypeBorderBlank)//折线连接点样式为外边缘空白
    .yAxisGridLineStyleSet([AALineStyle styleWithWidth:@0])//y轴横向分割线宽度(为0即是隐藏分割线)
    .categoriesSet(@[@"临床一期",@"临床二期",@"临床三期",@"临床四期",])
    .markerRadiusSet(@8.0)
    .xAxisCrosshairSet([AACrosshair crosshairWithColor:AAColor.darkGrayColor
                                             dashStyle:AAChartLineDashStyleTypeDashDot
                                                 width:@1])
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"上市")
        .dataSet(@[@0,@0,@0,@7]),
        AASeriesElement.new
        .nameSet(@"终止")
        .dataSet(@[@0,@2.5,@5,@5]),
        AASeriesElement.new
        .nameSet(@"无进展")
        .dataSet(@[@0,@2,@0,@1]),
        AASeriesElement.new
        .nameSet(@"进行中")
        .dataSet(@[@3,@3,@2,@2]),
    ]);
    
    
    AAOptions *aaOptions = aaChartModel.aa_toAAOptions;
    aaOptions.tooltip
    .useHTMLSet(true)
    .formatterSet(@AAJSFunc(function () {
        let wholeContentStr = this.points[0].x + '<br/>';
        let length = this.points.length;
        for (let i = 0; i < length; i++) {
            let thisPoint = this.points[i];
            let yValue = thisPoint.y;
            if (yValue != 0) {
                let prefixStr = '<span style=\"' + 'color:'+ thisPoint.color + '; font-size:13px\"' + '>◉ ';
                wholeContentStr += prefixStr + thisPoint.series.name + ': ' + yValue + '<br/>';
            }
        }
        return wholeContentStr;
    }))
    ;
    
    //禁用图例点击事件
     aaOptions.plotOptions.series.events = AAEvents.new
     .legendItemClickSet(@AAJSFunc(function() {
         return false;
     }));
    
    return aaOptions;
}
```
