### ISSUE TITLE
x轴左边有间隙，看了其他回答，依然有问题

### ISSUE THREAD

**Issue by LSK1994** [AAChartModel/AAChartKit#658]
看您在其他问题里说 ：
  AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
 
    AAYAxis *aaYAxis = aaOptions.yAxis;
    aaYAxis.offsetSet(@(-15));//设置Y轴偏移量

我的版本是AAChartKit 3.0.2
offsetSet报错，找不到这个
Property 'offsetSet' not found on object of type 'AAYAxis *'

**Comment by AAChartModel** [comment]
你直接

```ruby
pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'

```
吧, 3.0.2版本太旧了,有很多属性都没有支持.

**Comment by LSK1994** [comment]
尴尬了 ，这样是3.0.2的，
Pre-downloading: `AAChartKit` from `https://github.com/AAChartModel/AAChartKit.git`
Downloading dependencies
Installing AAChartKit 3.0.2 (was 2.1.6)

![image](https://user-images.githubusercontent.com/17511513/60086727-34d3c000-976e-11e9-8bba-9491b6049c85.png)

**Comment by LSK1994** [comment]
pod update 'AAChartKit' --verbose --no-repo-update 
这样还是3.0.2

**Comment by LSK1994** [comment]
应该是pods的问题，重新更新一下，这个方法可以用了，但版本还是3.0.2

设置aaYAxis.offsetSet(@(-15));之前是这样：
![image](https://user-images.githubusercontent.com/17511513/60090044-55067d80-9774-11e9-859e-26a4aba4322b.png)

设置之后是这样，
![image](https://user-images.githubusercontent.com/17511513/60089920-1244a580-9774-11e9-86e9-cec69880e1c7.png)


没有达到预期效果，期望x轴左边线在y轴的地方
![image](https://user-images.githubusercontent.com/17511513/60090044-55067d80-9774-11e9-859e-26a4aba4322b.png)

**Comment by AAChartModel** [comment]
强制X轴文字从轴的头部原点位置(0,0)开始,估计要像这里

http://jsfiddle.net/BlackLabel/yVG7R/187/

的一样,使用JavaScript函数自定义X轴文字内容方才可行.

**Comment by AAChartModel** [comment]
参见已解决问题 https://github.com/AAChartModel/AAChartKit/issues/937
