### ISSUE TITLE
组装参数 aa_drawChartWithChartModel 设置完后报错 ☠️☠️💀☠️☠️!!!!!WARNING!!!!! THERE ARE SOME ERROR INFOMATION

### ISSUE THREAD

**Issue by yy103zhu** [AAChartModel/AAChartKit#659]
```objc
- (AAChartModel *)configParamMethod:(NSArray *)categories Datas:(NSArray *)datas {
    AAChartModel *aaChartModel= AAChartModel.new
    .chartTypeSet(AAChartTypeArea)//设置图表的类型
    .titleSet(@"")
    .subtitleSet(@"")
    .yAxisTitleSet(@"")
    .markerRadiusSet(@3)
    .categoriesSet(categories)
    .legendEnabledSet(NO)
    .seriesSet(@[
                 AAObject(AASeriesElement)
                 .colorSet((id)[AAGradientColor blueToWhiteColor])
                 .nameSet(@" ")
                 .dataSet(datas),
                 ]);
    aaChartModel.yAxisAllowDecimals = NO;
    return aaChartModel;
}
```

```js
☠️☠️💀☠️☠️!!!!!WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______{
    code = 4;
    domain = WKErrorDomain;
    userInfo =     {
        NSLocalizedDescription = "发生 JavaScript 异常";
        WKJavaScriptExceptionColumnNumber = 21;
        WKJavaScriptExceptionLineNumber = 1;
        WKJavaScriptExceptionMessage = "ReferenceError: Can't find variable: loadTheHighChartView";
        WKJavaScriptExceptionSourceURL = "about:blank";
    };
}
```

**Comment by AAChartModel** [comment]
你是完全显示不出来,还是说只是偶发的?

**Comment by AAChartModel** [comment]
你把你的配置代码放在AAChartKit的demo中试试效果如何呢?

**Comment by yy103zhu** [comment]
我自己写的固定参数传进去不报错 就是每次请求出来的数据都报错 这样的错误，但是UI界面也显示正常了  就是打印日志老报这个错

**Comment by AAChartModel** [comment]
你有调用 

```objc
/*更新 AAChartModel 内容之后,刷新图表*/
[_aaChartView aa_refreshChartWithChartModel:aaChartModel];
```

这个刷新的方法吗?

**Comment by XQZZZ** [comment]
☠️☠️💀☠️☠️!!!!!WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______{
    code = 4;
    domain = WKErrorDomain;
    userInfo =     {
        NSLocalizedDescription = "\U53d1\U751f JavaScript \U5f02\U5e38";
        WKJavaScriptExceptionColumnNumber = 21;
        WKJavaScriptExceptionLineNumber = 1;
        WKJavaScriptExceptionMessage = "ReferenceError: Can't find variable: loadTheHighChartView";
        WKJavaScriptExceptionSourceURL = "about:blank";
    };
}

您好，我的也是报这个警告，页面 可以正常显示

**Comment by huipengo** [comment]
您好，我的也报这个错
```
-------> AAChartView.m [Line 328] 
☠️☠️💀☠️☠️!!!!!WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______{
    code = 4;
    domain = WKErrorDomain;
    userInfo =     {
        NSLocalizedDescription = "A JavaScript exception occurred";
        WKJavaScriptExceptionColumnNumber = 21;
        WKJavaScriptExceptionLineNumber = 1;
        WKJavaScriptExceptionMessage = "ReferenceError: Can't find variable: loadTheHighChartView";
        WKJavaScriptExceptionSourceURL = "about:blank";
    };
}
```

**Comment by AAChartModel** [comment]
调用`aa_refreshChartWithOptions`你得确保AAChartView已经完成加载,或者AAChartView已经完成绘制.

如果直接在`aa_drawChartWithOptions `方法后面紧跟着直接调用了`aa_refreshChartWithOptions`,这个时候HTML文件和JS文件内容上下文还没有加载完成,导致此问题.

**Comment by XQZZZ** [comment]
您好， 我在项目中没有调用aa_refreshChartWithOptions方法；UI加载时，每个图表都会报一个。




------------------ 原始邮件 ------------------
发件人: "An An"<notifications@github.com>;
发送时间: 2019年7月29日(星期一) 晚上6:50
收件人: "AAChartModel/AAChartKit"<AAChartKit@noreply.github.com>;
抄送: "XQ"<3093066830@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [AAChartModel/AAChartKit] 组装参数 aa_drawChartWithChartModel 设置完后报错 ☠️☠️💀☠️☠️!!!!!WARNING!!!!! THERE ARE SOME ERROR INFOMATION (#659)




调用aa_refreshChartWithOptions你得确保AAChartView已经完成加载,或者AAChartView已经完成绘制.
 
如果直接在aa_drawChartWithOptions 方法后面紧跟着直接调用了aa_refreshChartWithOptions,这个时候HTML文件和JS文件内容上下文还没有加载完成,导致此问题.
