### ISSUE TITLE
浮动框的标题全是一样，能否支持每条显示不同的标题

### ISSUE THREAD

**Issue by raodaye** [AAChartModel/AAChartKit#662]
AASeriesElement.new
                 .nameSet(@"Tokyo Hot")
                 .lineWidthSet(@5.0)
                 .fillOpacitySet(@0.4)
                 .dataSet(@[@0.45, @0.43, @0.50, @0.55, @0.58,])

你好。能否支持把名字的设置也变成数组类型，让每一列显示的提示框的名字不一样？

**Comment by AAChartModel** [comment]
给个设计稿看看👀👀

**Comment by raodaye** [comment]
![image](https://user-images.githubusercontent.com/16401245/60243620-324aa500-98eb-11e9-8b8d-cbec2041218b.png)
像这种每一条点上去要显示不同的名字，能实现吗？

**Comment by AAChartModel** [comment]
>  浮动框的标题全是一样

现在的浮动提示框的标题不都是根据X轴的categories文字来的吗?哪里一样了?

**Comment by raodaye** [comment]
是的，但是那个name的设置是字符串，.nameSet(@"Tokyo Hot")这种，我想能不能改为数组呢？

**Comment by AAChartModel** [comment]
不能,name只支持字符串.不明白你要将name改成数组干什么. `categories` 不就是数组吗?

**Comment by raodaye** [comment]
比如像上面那个设计图      一般情况下是 ：蓝色的代表一类，黄色的代表一类，绿色的代表一类。这样name是字符串就没问题。但是现在需求是，每一条柱状图的浮动框要显示不一样的名字，就算都是蓝色的柱状图，名字都是不一样的。
![image](https://user-images.githubusercontent.com/16401245/60244915-0846b200-98ee-11e9-98b7-f0904533e6a1.png)
就像这几个serises,  name赋值后，颜色一样显示的名字都一样了

**Comment by AAChartModel** [comment]
那就需要用到formatter的JavaScript函数了,参见:

使用JavaScript函数自定义AATooltip ---> #653

**Comment by AAChartModel** [comment]
formatter因为支持JavaScript函数,自由度最高,几乎可以定制任何想要的自定义tooltip浮动提示框

**Comment by AAChartModel** [comment]
https://jshare.com.cn/highcharts/hhhhGu 

可以通过这个在线工具测试formatter的JavaScript函数.

**Comment by AAChartModel** [comment]
参考问题:  AATooltip的formatter如何设置？---> #549

**Comment by raodaye** [comment]
自定义过后还要把name的类型改为数组么？

**Comment by AAChartModel** [comment]
name 类型是根据highCharts官方提供的API来的

**Comment by AAChartModel** [comment]
https://api.highcharts.com.cn/highcharts#series%3Carea%3E.name

你觉得可以随意更改吗?

**Comment by raodaye** [comment]
那他是字符串怎么能显示不同的名字呢？

**Comment by raodaye** [comment]
大佬，你有想法吗？

**Comment by raodaye** [comment]
哦，我理解你的意思了，刚才没听明白，谢谢你了

**Comment by raodaye** [comment]
![image](https://user-images.githubusercontent.com/16401245/60420557-a0a8a380-9c1a-11e9-8423-e0486a40192a.png)
这个方法写上去报错了，是什么原因啊

**Comment by raodaye** [comment]
formatter的设置里面能不能引入一个外部的数据源？？？

**Comment by AAChartModel** [comment]
使用字符串替换的方式应该就可以了.
