### ISSUE TITLE
请问可以将y轴标题设置到刻度线正上方吗

### ISSUE THREAD

**Issue by bsyqc163** [AAChartModel/AAChartKit#668]
![Simulator Screen Shot - iPhone Xs - 2019-07-11 at 16 50 39](https://user-images.githubusercontent.com/21351578/61036892-96498f00-a3fc-11e9-8d5a-7180fdb6c726.png)

**Comment by AAChartModel** [comment]
麻烦把你的AAChartModel代码文本贴一下(不要截图)

**Comment by bsyqc163** [comment]
您好，我就是用您Demo里的方法，因为我们要做的是两个y轴，
- (AAOptions *)configureDoubleYAxisChartOptions {
    
    AATitle *aaTitle = AATitle.new.textSet(@"双Y轴混合图");
    
    AAXAxis *aaXAxis = AAXAxis.new
    .visibleSet(true)
    .minSet(@0)
    .categoriesSet(@[@"Java", @"Swift", @"Python", @"Ruby", @"PHP", @"Go"]);
    
    AAYAxis *yAxisOne = AAYAxis.new
    .visibleSet(true)
    .titleSet(AATitle.new.textSet(@"温度")
              .styleSet(AAStyle.new
                        .colorSet(@"#1e90ff")//Title font color
                        .fontSizeSet(@"14px")//Title font size
                        .fontWeightSet(AAChartFontWeightTypeBold)//Title font weight
                        .textOutlineSet(@"0px 0px contrast")
                        ))
    .oppositeSet(true);
    

    AAYAxis *yAxisTwo = AAYAxis.new
    .visibleSet(true)
    .titleSet(AATitle.new.textSet(@"降雨量")
              .styleSet(AAStyle.new
                        .colorSet(@"#1e90ff")//Title font color
                        .fontSizeSet(@"14px")//Title font size
                        .fontWeightSet(AAChartFontWeightTypeBold)//Title font weight
                        ));
    
    NSArray *aaYAxisArr = @[yAxisOne,// Primary yAxis
                            yAxisTwo // Secondary yAxis
                            ];
    
    AATooltip *aaTooltip = AATooltip.new.enabledSet(true).sharedSet(true);
    
    NSArray *aaSeries = @[
                          AASeriesElement.new
                          .nameSet(@"2017")
                          .typeSet(AAChartTypeColumn)
                          .borderRadiusSet(@4)
                          .colorSet((id)AAGradientColor.mysticMauveColor)
                          .yAxisSet(@(0))
                          .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2, @21.5])
                          .dataLabelsSet(AADataLabels.new.enabledSet(false))
                          ,
                          AASeriesElement.new
                          .nameSet(@"2018")
                          .typeSet(AAChartTypeLine)
                          .colorSet(AAColor.redColor)
                          .yAxisSet(@(1))
                          .dataSet(@[@1.2, @0.8, @0.5, @0.32, @0.8, @1.0])
                          .dataLabelsSet(AADataLabels.new.enabledSet(false))
                          ];
    
    AAOptions *aaOptions = AAOptions.new;
    aaOptions.title = aaTitle;
    aaOptions.xAxis = aaXAxis;
    aaOptions.yAxis = (id)aaYAxisArr;
    aaOptions.tooltip = aaTooltip;
    aaOptions.series = aaSeries;
    return aaOptions;
}

**Comment by bsyqc163** [comment]
设置align也不好使，以下这样设置直接就不显示了
AAYAxis *yAxisTwo = AAYAxis.new
    .visibleSet(true)
    .titleSet(AATitle.new.textSet(@"降雨量")
              .alignSet(AAChartTitleAlignTypeLeft)
              .verticalAlignSet(AALegendVerticalAlignTypeTop)
              .styleSet(AAStyle.new
                        .colorSet(@"#1e90ff")//Title font color
                        .fontSizeSet(@"14px")//Title font size
                        .fontWeightSet(AAChartFontWeightTypeBold)//Title font weight
                        ));

**Comment by bsyqc163** [comment]
**请问y轴可以设置横向的虚线，那x轴好像没有相应的属性设置虚线**
AAYAxis *yAxisTwo = AAYAxis.new
    .visibleSet(true)
    .lineWidthSet(@(0.5))
    **.gridLineDashStyleSet(AALineDashStyleTypeDashDot)**

而x轴没有，只能设置线的width
AAXAxis *aaXAxis = AAXAxis.new
    .visibleSet(true)
    .gridLineWidthSet(@(0.5))
