### ISSUE TITLE
设置touchEventEnabled没效果吗？

### ISSUE THREAD

**Issue by guipingName** [AAChartModel/AAChartKit#669]
点击图表，不需要显示当前的xy值，设置touchEventEnabled无效

**Comment by AAChartModel** [comment]
想要获取点击事件,除了touchEventEnabled同时还要设置代理方法,详情参见readme文档.

**Comment by AAChartModel** [comment]
支持用户点击和滑动事件:  https://github.com/AAChartModel/AAChartKit/blob/master/CHINESE-README.md#%E6%94%AF%E6%8C%81%E7%9B%91%E5%90%AC%E7%94%A8%E6%88%B7%E7%82%B9%E5%87%BB%E4%BA%8B%E4%BB%B6%E5%8F%8A%E5%8D%95%E6%8C%87%E6%BB%91%E5%8A%A8%E4%BA%8B%E4%BB%B6

**Comment by guipingName** [comment]
我想禁止点击事件，设置touchEventEnabled=NO，还是可以点击

**Comment by guipingName** [comment]
111
