### ISSUE TITLE
折线图只有两个点是不是不会连线

### ISSUE THREAD

**Issue by korea1501541730** [AAChartModel/AAChartKit#670]
我现在的数据折线图只有两个点。经常出现不会连线

**Comment by korea1501541730** [comment]
测试发现Y轴0-100.当折线图只有两个值比如76，76是。折线图不会连线100%的出现

**Comment by korea1501541730** [comment]
![4EC4AFEDC9F026B48C40CF1F3482C834](https://user-images.githubusercontent.com/9499610/61389896-4d0da980-a8ec-11e9-92f4-c9cf5fa7f859.png)
请看图，希望大佬修复下。

**Comment by AAChartModel** [comment]
之前有遇到过这个问题,折线数据相同,而且同时使用了渐变色就会有这个问题.你禁用掉渐变色试试.

**Comment by AAChartModel** [comment]
而且折线使用渐变色意义不大吧

**Comment by korea1501541730** [comment]
好的。已经去掉了，谢谢各位大佬

**Comment by AAChartModel** [comment]
okay🙂
