### ISSUE TITLE
请问y轴数据可以设置文字吗

### ISSUE THREAD

**Issue by littleZhangqq** [AAChartModel/AAChartKit#675]
正常说y轴其实用来显示值的变化的，x是周期，但是现在x周期内y轴的值变化需要用汉字来显示，看到了能把xy轴转换的属性，但是转换之后值的变化不是横着而是竖直显示，请问该咋弄呢？没法贴图片。。。我用文字来表示吧。。：
y：
良好
一般
恶劣
x:    1，2，3，4，5，6`

**Comment by littleZhangqq** [comment]
这个是我的model设置：
`AAChartModel *model =  AAChartModel.new
    .chartTypeSet(AAChartTypeSpline)
    .markerSymbolSet(AAChartSymbolTypeCircle)
    .markerRadiusSet(@6)//设置折线连接点宽度为0,即是隐藏连接点
    .xAxisGridLineWidthSet(@(1))
    .yAxisGridLineWidthSet(@(1))
    .yAxisTitleSet(@"")
    .categoriesSet(@[@"提前", @"准时", @"延时"])
    .yAxisTickPositionsSet(@[@(1),@(2),@(3),@(4),@(5),@(6)])
    .subtitleSet(@"(程度)")
    .markerSymbolStyleSet(AAChartSymbolStyleTypeInnerBlank)
    .dataLabelEnabledSet(true)
    .invertedSet(true)
    .seriesSet(@[
                 AASeriesElement.new
                 .nameSet(@"时间")
                 .dataSet(@[@(1), @(2), @(2)])
                 .lineWidthSet(@3.5)
                 .zonesSet(@[]),
                 ]);`

**Comment by AAChartModel** [comment]
>  没法贴图片

将图片直接拖拽至此文字输入框即可上传图片,怎么会没法贴图片?

**Comment by littleZhangqq** [comment]
好的。。。
<img width="120" alt="QQ20190716-174701@2x" src="https://user-images.githubusercontent.com/14501914/61294075-a4861980-a807-11e9-8a71-50f87cb06234.png">
是这个样式的

**Comment by AAChartModel** [comment]
已为Y轴labels添加了formatter属性.使用示例如下:👇


1.配置AAOptions实例对象
```objc
 AAChartModel *aaChartModel = AAChartModel.new
    .chartTypeSet(AAChartTypeLine)//图表类型
    .titleSet(@"")//图表主标题
    .subtitleSet(@"")//图表副标题
    .colorsThemeSet(@[@"#04d69f",@"#1e90ff",@"#ef476f",@"#ffd066",])
    .markerSymbolStyleSet(AAChartSymbolStyleTypeBorderBlank)//折线连接点样式为内部白色
    .markerRadiusSet(@8)
    .stackingSet(AAChartStackingTypeNormal)
    .yAxisTitleSet(@"")//设置 Y 轴标题
    .seriesSet(@[
                 AASeriesElement.new
                 .nameSet(@"Tokyo Hot")
                 .lineWidthSet(@5.0)
                 .fillOpacitySet(@0.4)
                 .dataSet( @[@29.9, @71.5, @106.4, @129.2, @144.0, @176.0, @135.6, @148.5, @216.4, @194.1, @95.6, @54.4]),
                 ]
               );
    /*Custom Tooltip Style --- 自定义图表浮动提示框样式及内容*/
    AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
    aaOptions
    .yAxis.labels
    .formatterSet(@AAJSFunc(function () {
        let yValue = this.value;
        if( yValue >=200) {
            return "极佳";
        } else if( yValue >=150 && yValue< 200 ) {
            return "非常棒";
        } else if( yValue >=100 && yValue< 150) {
            return "相当棒";
        } else if( yValue >=50 && yValue< 100)  {
            return "还不错";
        } else {
            return "一般";
        }
    }));
    return aaOptions;
```

2. 绘图效果

![image](https://user-images.githubusercontent.com/16357599/61344789-249e9480-a885-11e9-9f93-22303a611a0e.png)

**Comment by AAChartModel** [comment]
至于如何配置formatter函数,可打开这个在线`JavaScript`编辑器链接,

https://jshare.com.cn/highcharts/hhhhnn

将下面的`JavaScript`代码复制粘贴进去,自行更改配置在线测试


```js
$(function () {
	$('#container').highcharts({
		title: {
			text: 'Chart reflow is set to true'
		},
		subtitle: {
			text: 'When resizing the window or the frame, the chart should resize'
		},
		
		yAxis: {
			visible:true,
			labels: {
				formatter:function () {
					let yValue = this.value;
					if( yValue >=200) {
						return "极佳";
					} else if( yValue >=150 && yValue< 200 ) {
						return "非常棒";
					} else if( yValue >=100 && yValue< 150) {
						return "相当棒";
					} else if( yValue >=50 && yValue< 100)  {
						return "还不错";
					} else {
						return "一般";
					}
				},
			}
		},
		series: [{
			data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
		}]
	});
});
```

**Comment by littleZhangqq** [comment]
好的，万分感谢！！

**Comment by AAChartModel** [comment]
需要更新一下AAChartKit,我在https://github.com/AAChartModel/AAChartKit/commit/0ee11190742e1cb661eca11ed851407fd26b8b39
这次提交里面新加的功能.

**Comment by littleZhangqq** [comment]
大佬 你这个修改的y轴文字可以是固定的吗？现在是y轴显示文字是根据dataset里的值来控制y轴文字的显示范围，比如数据10个类型，但是dataset里的值只有5种，那么y轴最多只能显示到5种，默认应该是显示10个类型范围的。请问这种的能改吗？

**Comment by srx080561** [comment]
双y轴该怎么取呢

**Comment by AAChartModel** [comment]
@srx080561 现已支持双 Y 轴图表的 Y 轴Labels 的 formatter 函数

![](https://user-images.githubusercontent.com/16357599/92723997-7dd85a00-f39c-11ea-836d-791a3702ba72.png)
