### ISSUE TITLE
自定义浮动提示框tooltip内容

### ISSUE THREAD

**Issue by XQZZZ** [AAChartModel/AAChartKit#677]
大神.dataSet数组放的是 时间戳，浮动提示框tooltip内容我要显示成具体时间：xx年xx月xx日 x时x分；要怎么转换？谢谢！

**Comment by AAChartModel** [comment]
AATooltip 支持formatter(JavaScript 函数)字符串,可通过配置formatter中的JavaScript函数内容来完成时间戳到时间的转换.

参考   #569
