### ISSUE TITLE
Customizing the view

### ISSUE THREAD

**Issue by OrcunT** [AAChartModel/AAChartKit#688]

**Comment by OrcunT** [comment]
Hello there,

I would like to customize the bar chart screen by adding some detail information (labels) under the generated bar chart. 

I couldnt manage to customize the generated scrollview. 

Any clues?

**Comment by AAChartModel** [comment]
>  I couldnt manage to customize the generated scrollview.


I do not understand what you mean in this sentence

**Comment by OrcunT** [comment]
Ok, there are 3 problems in my project whenever i want to use bar chart. i added the screenshot of my app.1- i dont want the bar chart part of the screen to be scrollable 2- i want to make the whole screen scrollable 3- i want to modify - add / remove ui elements - to the lower part where i circled with red markerSo, can you provide an example for those?  30.07.2019, 04:29, "An An" <notifications@github.com>:I couldnt manage to customize the generated scrollview.I do not understand what you mean in this sentence—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by OrcunT** [comment]
My bad, found the answer in documantation.
