### ISSUE TITLE
AAChartTypeSpline类型的图标可以加一个，默认选中某一点并且显示提示弹框吗？

### ISSUE THREAD

**Issue by NoLiuxin** [AAChartModel/AAChartKit#690]
AAChartTypeSpline类型的图标可以加一个，默认选中某一点并且显示提示弹框吗？

**Comment by Ficky-Michy** [comment]
> AAChartTypeSpline类型的图标可以加一个，默认选中某一点并且显示提示弹框吗？

解决了吗？ @NoLiuxin

**Comment by NoLiuxin** [comment]
> 

没有，研究demo有一个可以选中第一个，但是没啥用

**Comment by AAChartModel** [comment]
参考重复问题:

* https://github.com/AAChartModel/AAChartKit/issues/623
