### ISSUE TITLE
Changing the color of bars in column chart

### ISSUE THREAD

**Issue by OrcunT** [AAChartModel/AAChartKit#692]
Hi there,

I would like to change the bar colors in column chart, i tried .fillcolor and .fillcolorset but couldnt manage to change the colors of bars. 

Any chance for a little help? :)

**Comment by AAChartModel** [comment]
## 1. Configure AAChartModel Instance Object



```objc

- (AAChartModel *)setUpColorfulBarChart {
    NSArray *colorsNameArr = @[@"red",
                               @"orange",
                               @"yellow",
                               @"green",
                               @"cyan",
                               @"blue",
                               @"purple",
                               @"gray",
                               @"darkGray",
                               @"lightGray",
                               @"magenta",
                               @"brown",
                               @"black"];
    
    NSArray *colorsArr = @[[AAColor redColor],
                           [AAColor orangeColor],
                           [AAColor yellowColor],
                           [AAColor greenColor],
                           [AAColor cyanColor],
                           [AAColor blueColor],
                           [AAColor purpleColor],
                           [AAColor grayColor],
                           [AAColor darkGrayColor],
                           [AAColor lightGrayColor],
                           [AAColor magentaColor],
                           [AAColor brownColor],
                           [AAColor blackColor]
                           ];
    
    return AAChartModel.new
    .chartTypeSet(AAChartTypeBar)
    .animationTypeSet(AAChartAnimationBounce)
    .titleSet(@"Colorful Chart")
    .subtitleSet(@"use AAColor to get color string")
    .dataLabelsEnabledSet(false)
    .categoriesSet(colorsNameArr)
    .colorsThemeSet(colorsArr)
    .stackingSet(AAChartStackingTypePercent)
    .seriesSet(@[
                 AASeriesElement.new
                 .nameSet(@"Tokyo")
                 .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6])
                 .colorByPointSet(@true)
                 ]);
}

```

## 2. You Get

![image](https://user-images.githubusercontent.com/16357599/62445059-f0d2d280-b791-11e9-9a44-db6a472873f7.png)

**Comment by AAChartModel** [comment]
## 1. Configure AAChartModel Instance Object
- (AAChartModel *)setUpColorfulGradientColorChart {
    NSArray *gradientColorNamesArr = @[@"oceanBlue",
                                       @"sanguine",
                                       @"lusciousLime",
                                       @"purpleLake",
                                       @"freshPapaya",
                                       @"ultramarine",
                                       @"pinkSugar",
                                       @"lemonDrizzle",
                                       @"victoriaPurple",
                                       @"springGreens",
                                       @"mysticMauve",
                                       @"reflexSilver",
                                       @"newLeaf",
                                       @"cottonCandy",
                                       @"pixieDust",
                                       @"fizzyPeach",
                                       @"sweetDream",
                                       @"firebrick",
                                       @"wroughtIron",
                                       @"deepSea",
                                       @"coastalBreeze",
                                       @"eveningDelight",
                                       ];
    
    NSArray *gradientColorArr = @[[AAGradientColor oceanBlueColor],
                                  [AAGradientColor sanguineColor],
                                  [AAGradientColor lusciousLimeColor],
                                  [AAGradientColor purpleLakeColor],
                                  [AAGradientColor freshPapayaColor],
                                  [AAGradientColor ultramarineColor],
                                  [AAGradientColor pinkSugarColor],
                                  [AAGradientColor lemonDrizzleColor],
                                  [AAGradientColor victoriaPurpleColor],
                                  [AAGradientColor springGreensColor],
                                  [AAGradientColor mysticMauveColor],
                                  [AAGradientColor reflexSilverColor],
                                  [AAGradientColor newLeafColor],
                                  [AAGradientColor cottonCandyColor],
                                  [AAGradientColor pixieDustColor],
                                  [AAGradientColor fizzyPeachColor],
                                  [AAGradientColor sweetDreamColor],
                                  [AAGradientColor firebrickColor],
                                  [AAGradientColor wroughtIronColor],
                                  [AAGradientColor deepSeaColor],
                                  [AAGradientColor coastalBreezeColor],
                                  [AAGradientColor eveningDelightColor],
                                  ];
    
    return AAChartModel.new
    .chartTypeSet(AAChartTypeBar)
    .titleSet(@"Colorful Column Chart")
    .subtitleSet(@"single data array colorful column chart")
    .categoriesSet(gradientColorNamesArr)
    .colorsThemeSet(gradientColorArr)
    .yAxisTitleSet(@"gradient color")
    .stackingSet(AAChartStackingTypePercent)
    .seriesSet(@[
                 AASeriesElement.new
                 .nameSet(@"ElementOne")
                 .dataSet(@[@3.9, @4.2, @5.7, @8.5, @11.9, @15.2, @17.0, @16.6, @14.2, @10.3, @6.6, @4.8,
                            @3.9, @4.2, @5.7, @8.5, @11.9, @15.2, @17.0, @16.6, @14.2, @10.3,])
                 .colorByPointSet(@true),//When using automatic point colors pulled from the options.colors collection, this option determines whether the chart should receive one color per series or one color per point. Default Value：false.
                 ]);
}

```

## 2. You Get

**Comment by AAChartModel** [comment]
To get a colorful bar chart ,all you need to do is configuring `colorsTheme` array of AAChartModel and then setting `colorByPoint` of AASeriesElement be `true`

**Comment by AAChartModel** [comment]
Refer to 
* #418
