### ISSUE TITLE
支持自定义设置Y轴刻度线数量tickAmount

### ISSUE THREAD

**Issue by AAChartModel** [AAChartModel/AAChartKit#699]

**Comment by NoLiuxin** [comment]
![1578551645829](https://user-images.githubusercontent.com/8954358/72043825-2e153080-32ed-11ea-9017-f4bd354da1b6.jpg)
作者你好，我这边遇到一个问题，使用了tickAmount属性，但是Y轴的最大值计算有问题，明明最大值是91.4但是只取到了90

**Comment by NoLiuxin** [comment]
我是设置了tickAmount = @7; 但是改成6就可以了，是不是只能设置偶数，但是内部计算逻辑有问题？
