### ISSUE TITLE
pod 方式导入编译报错   pod 'AAChartKit'

### ISSUE THREAD

**Issue by Jonas-o** [AAChartModel/AAChartKit#70]
```
pod 'AAChartKit'  
```
导入头文件就编译报错，
```objective-c
#import <AAChartKit/AAChartKit.h> 
```
 提示
```
 Could not build module "AAChartKit"
```

**Comment by AAChartModel** [comment]
暂不支持 pod 导入,请按照REAMDME 文档说明的操作步骤,进行手动导入.

**Comment by Jonas-o** [comment]
嗖嘎，我是用pod搜索到了，我以为已经支持了呢

**Comment by AAChartModel** [comment]
那个是测试版本,还是有部分问题未被解决,而且哪个版本距离现在的最新版已近有很多的的代码优化和改动了.

**Comment by AAChartModel** [comment]
最近刚换了 Mac, 后续有空闲时间会及时补上.造成了些许不便,再次说一声抱歉了😭

**Comment by Jonas-o** [comment]
ok，没问题的，另外讨教个问题，因为我不太懂JS所以想问问如何手动清除ChartView上的展示信息？就是点击柱形图的时候展示具体数据的那个小窗口

**Comment by AAChartModel** [comment]
你说的那个小窗口是 ***AATooltip*** 对象对应的东西,叫作浮动提示框

**Comment by AAChartModel** [comment]
现已为 ***AATooltip***添加禁用启用属性`enabled`,这里是`AAOptionsConstructor.m` 中的具体配置代码
```objective-c
    AATooltip *tooltip = AAObject(AATooltip)
    .enabledSet(true)//启用浮动提示框
    .sharedSet(true)//多组数据公享一个浮动提示框
    .crosshairsSet(chartModel.crosshairs);
    //  .useHTMLSet(true)
    //  .valueSuffixSet(@"摄氏度");//浮动提示框的单位名称后缀
```
详情参见 #71

**Comment by AAChartModel** [comment]
您还可以考虑使用 `AAChartKit-Swift`
https://github.com/AAChartModel/AAChartKit-Swift
代码更简洁,执行效率更高,因为所有的 iOS 端的 `AAOptionsConstructo.m` 的配置工作全都放在了`AAOptionsConstructo.js`中,使用更简洁,执行效率更高.😝

**Comment by Jonas-o** [comment]
可能我没有表达清楚，我的意思是说，在 `浮动提示框` 原有的显示逻辑之下，有没有另外的手动隐藏的办法，比如滑动页面的时候手动隐藏已显示的  `浮动提示框`

**Comment by AAChartModel** [comment]
额,这个功能恐怕没有耶

**Comment by Jonas-o** [comment]
嗯嗯，好吧，那就不隐藏了🤣🤣

**Comment by AAChartModel** [comment]
好说好说,还有使用上的问题,欢迎随时 **issue** 我(*^__^*) 嘻嘻……

**Comment by Jonas-o** [comment]
OK，感谢开源🤝

**Comment by AAChartModel** [comment]
工作中用到了,之前的代码一直比较散乱,耦合严重,吃了点亏.索性封装起来方便后续使用.封装后感觉使用起来比较简洁易用,好东西不敢藏私🤝

**Comment by Jonas-o** [comment]
这两天研究的时候遇到一个疑问，当图例上下垂直排列的时候怎么定义其间距，也就是上下图例之间的距离？垂直排列的时候图例之间靠的太紧了水平位置排列的时候左右的间距还可以，不用修改。

**Comment by AAChartModel** [comment]
问题已解决,参见 #79
