### ISSUE TITLE
支持横屏(全屏)效果是怎样设置

### ISSUE THREAD

**Issue by DogTwoChen** [AAChartModel/AAChartKit#700]

**Comment by NoLiuxin** [comment]
横屏需要自己处理吧，我都是自己处理的，打开横屏，需要横屏的界面就横屏，只要约束正确就可以的。
![WeChata925d12f387b81f24d978fec11d6f05a](https://user-images.githubusercontent.com/8954358/62842806-84068d80-bce7-11e9-8daa-7551f1d1db2f.png)

**Comment by 15160378563** [comment]
@NoLiuxin 你是长按chartView弹出横屏界面的吗

**Comment by NoLiuxin** [comment]
@15160378563 不是的，我这边的设计是直接有个横屏按钮，我建议你找设计商讨一下，毕竟价格按钮也是小改动

**Comment by AAChartModel** [comment]
参见已解决问题 https://github.com/AAChartModel/AAChartKit/issues/915
