### ISSUE TITLE
能否实现苹果健康中心率图那样的表格？

### ISSUE THREAD

**Issue by lwy121810** [AAChartModel/AAChartKit#702]
![IMG_4712](https://user-images.githubusercontent.com/16394109/62998215-6e3ac900-be9d-11e9-84e9-1eea1f8bed5c.PNG)

我想实现上面的效果，本来打算使用散点图来实现，但没发现可以修改图例的样式的方法

**Comment by lwy121810** [comment]
> ![IMG_4712](https://user-images.githubusercontent.com/16394109/62998215-6e3ac900-be9d-11e9-84e9-1eea1f8bed5c.PNG)
> 
> 我想实现上面的效果，本来打算使用散点图来实现，但没发现可以修改图例的样式的方法

**Comment by AAChartModel** [comment]
这种苹果独有的图表类型可以参考官方的ResearchKit框架中自带的charts

http://researchkit.org/docs/docs/ChartsAndGraphs/ChartsAndGraphs.html

![](http://researchkit.org/docs/docs/ChartsAndGraphs/ChartsImages/Overview/DiscereteGraphChartMultipleLinesOverview.png)
