### ISSUE TITLE
y轴网格长度怎么限制呢？和移动y轴的自定义坐标呢？

### ISSUE THREAD

**Issue by lilongcnc** [AAChartModel/AAChartKit#708]
作者您好，我想要限制y轴的长度，看了下设置了tickPositionSet（@“outSide”）没有用。
还有y轴的自定义坐标,y轴的坐标名字可以移动吗？

**Comment by AAChartModel** [comment]
可以给个设计稿吗?不太知道你说的效果是什么样子

**Comment by lilongcnc** [comment]
方便加您个QQ吗？

**Comment by lilongcnc** [comment]
或者有交流群吗？ 我的QQ 654451416
