### ISSUE TITLE
浮动提示框的隐藏与显示问题

### ISSUE THREAD

**Issue by NoLiuxin** [AAChartModel/AAChartKit#710]
作者你好，我现在是把图表放在的tableview上了，点击图表会出现浮动提示框，现在想实现tableview滑动一定距离后隐藏掉显示的浮动提示框，目前查看了源码貌似并没有暴露隐藏浮动提示框的属性，但是我发现如果点击图表的非绘制区域就可以隐藏掉浮动提示框，所以此功能可以暴露出来吗？

**Comment by AAChartModel** [comment]
参见问题  #728
