### ISSUE TITLE
你好，我有个效果需要实现 想请教下使用AA改如何去定义X轴的data？

### ISSUE THREAD

**Issue by tan694525925** [AAChartModel/AAChartKit#711]
![WX20190821-152525](https://user-images.githubusercontent.com/13333806/63411354-f08c3580-c427-11e9-9eaf-d656571e8f2b.png)
类似这种图形的     希望能得到你的回复  感谢！

**Comment by tan694525925** [comment]
我的传值如下：
.dataSet(@[
                               @[@170,@280],
                               @[@280,@299],
                               @[@340,@350],
                               @[@360,@310],
                               @[@400,@400],
                               @[@520,@360],
                               ]),
得到的


![WX20190821-161759](https://user-images.githubusercontent.com/13333806/63414892-5cbe6780-c42f-11e9-9c40-fd1f4f6a2e19.png)
这个X轴的数值  需要在哪里修改什么定义参数吗

**Comment by AAChartModel** [comment]
可以通过categories来设置X轴文字

**Comment by tan694525925** [comment]
> 可以通过类别来设置X轴文字
因为X轴的数值不是固定的 是灵活的展示  设置categories 是不是就固定了X轴的文字显示

**Comment by a381511** [comment]
我也遇到这个问题,X周显示的文字数量 跟数据数量不对等 ,我只是想显示区间,但是现在会自动加上编号展示

**Comment by AAChartModel** [comment]
通过 JavaScript 函数自定义 X轴文字,参见问题 #751
