### ISSUE TITLE
怎么支持长按手势

### ISSUE THREAD

**Issue by 15160378563** [AAChartModel/AAChartKit#712]
是否可以在AAChartView上添加长按手势，现在我添加了一个长按手势在AAChartView怎么会不触发？？

**Comment by AAChartModel** [comment]
```objc
@interface AAChartView:UIView
```

AAChartView继承自UIView,关于手势的操作就和普通的UIView一样就可以了啊,没什么特别的吧

**Comment by AAChartModel** [comment]
> 是否可以在AAChartView上添加长按手势，现在我添加了一个长按手势在AAChartView怎么会不触发？？

不过你这里也有可能是你代码的问题,或者是由于图表的点击事件和你的长按手势冲突了.你可以多试试其他几种手势比如左滑右滑看看

**Comment by 15160378563** [comment]
好的  谢谢作者了

**Comment by 15160378563** [comment]
其他手势是可以  就长按不触发  好像是和浮动框冲突了  大神，请教一下  这该怎么解决吗

**Comment by 15160378563** [comment]
@AAChartModel
