### ISSUE TITLE
如何在折线图上添加自定义矩形范围框框

### ISSUE THREAD

**Issue by wangaiguo415** [AAChartModel/AAChartKit#716]

**Comment by AAChartModel** [comment]
不知道你需要的是不是这种为图表添加值域背景颜色带的功能?

![](https://user-images.githubusercontent.com/16357599/62686264-f3823180-b9f6-11e9-945c-510e57850c94.png)

**Comment by wangaiguo415** [comment]
就类似于附件这样的 ，不知道你正文是怎么有图片的（苦笑）




------------------ 原始邮件 ------------------
发件人: "An An"<notifications@github.com>;
发送时间: 2019年8月27日(星期二) 下午5:06
收件人: "AAChartModel/AAChartKit"<AAChartKit@noreply.github.com>;
抄送: "★轩辕★"<505263623@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AAChartModel/AAChartKit] 如何在折线图上添加自定义矩形范围框框 (#716)




不知道你需要的是不是这种为图表添加值域背景颜色带的功能?

**Comment by AAChartModel** [comment]
> 就类似于附件这样的

可参见此问题:柱形图 X 轴添加值域颜色分割带 #698

**Comment by AAChartModel** [comment]
> 不知道你正文是怎么有图片的（苦笑）

GitHub的issue问题评论区完整地支持`MarkDown`语法. 具体可自行搜索🔍`MarkDown`标准语法有关内容.

**Comment by wangaiguo415** [comment]
您好，再一次的打扰，请问如何设置两个Y轴，就左右各一个那种。还得自个增加吗？


------------------ 原始邮件 ------------------
发件人: "An An"<notifications@github.com>;
发送时间: 2019年8月29日(星期四) 晚上6:43
收件人: "AAChartModel/AAChartKit"<AAChartKit@noreply.github.com>;
抄送: ""<505263623@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AAChartModel/AAChartKit] 如何在折线图上添加自定义矩形范围框框 (#716)




Closed #716.

**Comment by AAChartModel** [comment]
>  请问如何设置两个Y轴，就左右各一个那种

参见 issue #722
