### ISSUE TITLE
可以左右都有Y轴吗？表示不同的东西

### ISSUE THREAD

**Issue by wangaiguo415** [AAChartModel/AAChartKit#722]

**Comment by AAChartModel** [comment]
## 配置AAOptions
```objc

- (AAOptions *)configureDoubleYAxisChartOptions {
    
    AATitle *aaTitle = AATitle.new.textSet(@"双Y轴混合图");
    
    AALabels *labels = AALabels.new
    .enabledSet(true)//设置 y 轴是否显示数字
    .formatSet(@"{value:.,0f}°C")//让y轴的值完整显示 而不是100000显示为100k,同时单位后缀为°C
    .styleSet(AAStyle.new
              .colorSet(@"#ff0000")//yAxis Label font color
              .fontSizeSet(@"15px")//yAxis Label font size
              .fontWeightSet(AAChartFontWeightTypeBold)//yAxis Label font weight
              );
    
    AAXAxis *aaXAxis = AAXAxis.new
    .visibleSet(true)
    .minSet(@0)
    .categoriesSet(@[@"Java", @"Swift", @"Python", @"Ruby", @"PHP", @"Go", @"C", @"C#", @"C++", @"Perl", @"R", @"MATLAB", @"SQL"]);
    
    AAYAxis *yAxisOne = AAYAxis.new
    .visibleSet(true)
    .labelsSet(labels)
    .titleSet(AAAxisTitle.new
              .textSet(@"温度")
              .styleSet(AAStyle.new
                        .colorSet(@"#1e90ff")//Title font color
                        .fontSizeSet(@"14px")//Title font size
                        .fontWeightSet(AAChartFontWeightTypeBold)//Title font weight
                        .textOutlineSet(@"0px 0px contrast")
                        ))
    .oppositeSet(true);
    

    AAYAxis *yAxisTwo = AAYAxis.new
    .visibleSet(true)
    .labelsSet(labels.formatSet(@"{value}mm"))
    .titleSet(AAAxisTitle.new
              .textSet(@"降雨量")
              .styleSet(AAStyle.new
                        .colorSet(@"#1e90ff")//Title font color
                        .fontSizeSet(@"14px")//Title font size
                        .fontWeightSet(AAChartFontWeightTypeBold)//Title font weight
                        ));
    
    NSArray *aaYAxisArr = @[yAxisOne,// Primary yAxis
                            yAxisTwo // Secondary yAxis
                            ];
    
    AATooltip *aaTooltip = AATooltip.new.enabledSet(true).sharedSet(true);
    
    NSArray *aaSeries = @[
                          AASeriesElement.new
                          .nameSet(@"2017")
                          .typeSet(AAChartTypeColumn)
                          .borderRadiusSet(@4)
                          .colorSet((id)AAGradientColor.mysticMauveColor)
                          .yAxisSet(@1)
                          .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6])
                          .dataLabelsSet(AADataLabels.new.enabledSet(true))
                          ,
                          AASeriesElement.new
                          .nameSet(@"2018")
                          .typeSet(AAChartTypeLine)
                          .colorSet(AAColor.redColor)
                          .yAxisSet(@0)
                          .dataSet(@[@0.2, @0.8, @5.7, @11.3, @17.0, @22.0, @24.8, @24.1, @20.1, @14.1, @8.6, @2.5])
                          .dataLabelsSet(AADataLabels.new.enabledSet(true))
                          ];
    
    AAOptions *aaOptions = AAOptions.new;
    aaOptions.title = aaTitle;
    aaOptions.xAxis = aaXAxis;
    aaOptions.yAxis = (id)aaYAxisArr;
    aaOptions.tooltip = aaTooltip;
    aaOptions.series = aaSeries;
    return aaOptions;
}

```


## 图形效果

![image](https://user-images.githubusercontent.com/16357599/64230649-fd2c8580-cf1f-11e9-8029-2c68ccb25933.png)

**Comment by AAChartModel** [comment]
## 配置AAOptions
```objc
- (AAOptions *)configureTheMirrorColumnChart {
    NSDictionary *gradientColorDic1 =
    [AAGradientColor gradientColorWithDirection:AALinearGradientDirectionToTopLeft
                               startColorString:@"#7052f4"//颜色字符串设置支持十六进制类型和 rgba 类型
                                 endColorString:@"#00b0ff"];
    
    NSDictionary *gradientColorDic2 =
    [AAGradientColor gradientColorWithDirection:AALinearGradientDirectionToBottomRight
                               startColorString:@"#EF71FF"//颜色字符串设置支持十六进制类型和 rgba 类型
                                 endColorString:@"#4740C8"];
    AAOptions *aaOptions = AAOptions.new
    .chartSet(AAChart.new
              .typeSet(AAChartTypeColumn)
//              .backgroundColorSet(@"#161139")
              )
    .titleSet(AATitle.new.textSet(@""))
    .xAxisSet(AAXAxis.new
              .visibleSet(true)
              .categoriesSet(@[@"一月", @"二月", @"三月", @"四月", @"五月", @"六月", @"七月", @"八月", @"九月", @"十月", @"十一月", @"十二月"]))
    .yAxisSet((id)@[AAYAxis.new
                    .visibleSet(true)
                    .gridLineWidthSet(@0)
                    .titleSet(AAAxisTitle.new.textSet(@"收入")),
                    AAYAxis.new
                    .visibleSet(true)
                    .titleSet(AAAxisTitle.new.textSet(@"支出"))
                    .lineWidthSet(@1)
                    .oppositeSet(true)
                    ])
    .tooltipSet(AATooltip.new
                .enabledSet(true)
                .sharedSet(true))
    .plotOptionsSet(AAPlotOptions.new
                    .seriesSet(AASeries.new
                               .animationSet(AAAnimation.new
                                             .easingSet(AAChartAnimationBounce)
                                             .durationSet(@1000)
                                             )
                               )
                    .columnSet(AAColumn.new
                               .groupingSet(false)
                               .borderWidthSet(@0)
                               .borderRadiusSet(@5)
                               )
                    )
    .seriesSet(@[
                 AASeriesElement.new
                 .nameSet(@"收入")
                 .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @13.9,@7.0, @6.9, @9.5, @14.5,])
                 .colorSet((id)gradientColorDic1),
                 AASeriesElement.new
                 .nameSet(@"支出")
                 .dataSet(@[@-20.1, @-14.1, @-8.6, @-2.5, @-0.8, @-5.7, @-11.3, @-17.0, @-22.0, @-24.8, @-24.1, @-20.1, @-14.1, @-8.6, @-2.5])
                 .colorSet((id)gradientColorDic2),
]);
    return aaOptions;
}

```


## 图形效果
![image](https://user-images.githubusercontent.com/16357599/64230733-2ea55100-cf20-11e9-9406-f78811d078ce.png)

**Comment by wangaiguo415** [comment]
非常非常非常感谢



------------------ 原始邮件 ------------------
发件人: "An An"<notifications@github.com>; 
发送时间: 2019年9月4日(星期三) 下午2:26
收件人: "AAChartModel/AAChartKit"<AAChartKit@noreply.github.com>; 
抄送: ""<505263623@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AAChartModel/AAChartKit] 可以左右都有Y轴吗？表示不同的东西 (#722)




配置AAOptions
 - (AAOptions *)configureDoubleYAxisChartOptions {          AATitle *aaTitle = AATitle.new.textSet(@"双Y轴混合图");          AALabels *labels = AALabels.new     .enabledSet(true)//设置 y 轴是否显示数字     .formatSet(@"{value:.,0f}°C")//让y轴的值完整显示 而不是100000显示为100k,同时单位后缀为°C     .styleSet(AAStyle.new               .colorSet(@"#ff0000")//yAxis Label font color               .fontSizeSet(@"15px")//yAxis Label font size               .fontWeightSet(AAChartFontWeightTypeBold)//yAxis Label font weight               );          AAXAxis *aaXAxis = AAXAxis.new     .visibleSet(true)     .minSet(@0)     .categoriesSet(@[@"Java", @"Swift", @"Python", @"Ruby", @"PHP", @"Go", @"C", @"C#", @"C++", @"Perl", @"R", @"MATLAB", @"SQL"]);          AAYAxis *yAxisOne = AAYAxis.new     .visibleSet(true)     .labelsSet(labels)     .titleSet(AAAxisTitle.new               .textSet(@"温度")               .styleSet(AAStyle.new                         .colorSet(@"#1e90ff")//Title font color                         .fontSizeSet(@"14px")//Title font size                         .fontWeightSet(AAChartFontWeightTypeBold)//Title font weight                         .textOutlineSet(@"0px 0px contrast")                         ))     .oppositeSet(true);          AAYAxis *yAxisTwo = AAYAxis.new     .visibleSet(true)     .labelsSet(labels.formatSet(@"{value}mm"))     .titleSet(AAAxisTitle.new               .textSet(@"降雨量")               .styleSet(AAStyle.new                         .colorSet(@"#1e90ff")//Title font color                         .fontSizeSet(@"14px")//Title font size                         .fontWeightSet(AAChartFontWeightTypeBold)//Title font weight                         ));          NSArray *aaYAxisArr = @[yAxisOne,// Primary yAxis                             yAxisTwo // Secondary yAxis                             ];          AATooltip *aaTooltip = AATooltip.new.enabledSet(true).sharedSet(true);          NSArray *aaSeries = @[                           AASeriesElement.new                           .nameSet(@"2017")                           .typeSet(AAChartTypeColumn)                           .borderRadiusSet(@4)                           .colorSet((id)AAGradientColor.mysticMauveColor)                           .yAxisSet(@1)                           .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6])                           .dataLabelsSet(AADataLabels.new.enabledSet(true))                           ,                           AASeriesElement.new                           .nameSet(@"2018")                           .typeSet(AAChartTypeLine)                           .colorSet(AAColor.redColor)                           .yAxisSet(@0)                           .dataSet(@[@0.2, @0.8, @5.7, @11.3, @17.0, @22.0, @24.8, @24.1, @20.1, @14.1, @8.6, @2.5])                           .dataLabelsSet(AADataLabels.new.enabledSet(true))                           ];          AAOptions *aaOptions = AAOptions.new;     aaOptions.title = aaTitle;     aaOptions.xAxis = aaXAxis;     aaOptions.yAxis = (id)aaYAxisArr;     aaOptions.tooltip = aaTooltip;     aaOptions.series = aaSeries;     return aaOptions; } 
 
图形效果

**Comment by AAChartModel** [comment]
AAChartKit的demo中有此两者的使用示例,可直接下载运行查看.
