### ISSUE TITLE
拆线图点击怎么后面那一块背景色去掉

### ISSUE THREAD

**Issue by huangzhentong** [AAChartModel/AAChartKit#730]
拆线图想点击的时候没有后面的背景色

**Comment by AAChartModel** [comment]
> 后面那一块背景色

那个背景色是准星线,设置准星线(crosshair)的宽度为`0`即可隐藏准星线.

**Comment by jianniou** [comment]
我试了，宽度为0，并不能把后面高亮背景去掉

**Comment by AAChartModel** [comment]
@jianniou 有点小bug,已修复.  Cocoapods 更新一下值最新AAChartKit即可.

**Comment by jianniou** [comment]
其实就是隐藏的准星线， crosshairs 这个变量也能解决
