### ISSUE TITLE
Broken link for android version

### ISSUE THREAD

**Issue by OrcunT** [AAChartModel/AAChartKit#732]
Hi there,

The link for the android version is directs back to objective-c project. Is that broken?

**Comment by AAChartModel** [comment]
It has been fixed now.

## Source Code⛓

Language Version | Project Name | Target Platform | Source Code Link |
------------ | ------------- |------------- | ------------- |
Swift | AAInfographics |  iOS |https://github.com/AAChartModel/AAChartKit-Swift |
Objective C | AAChartKit | iOS | https://github.com/AAChartModel/AAChartKit |
Kotlin | AAInfographics | Android | https://github.com/AAChartModel/AAChartCore-Kotlin |
Java | AAChartCore | Android | https://github.com/AAChartModel/AAChartCore |
