### ISSUE TITLE
X轴文字和点从轴的头部原点位置（0,0）开始,为什么pod上有只有2.1.6版本?

### ISSUE THREAD

**Issue by 274180213** [AAChartModel/AAChartKit#733]
设计图:
<img width="612" alt="s" src="https://user-images.githubusercontent.com/13343398/65317161-dd5aba00-dbcd-11e9-8219-4df27826b2d5.png">
效果图:
<img width="395" alt="w" src="https://user-images.githubusercontent.com/13343398/65317254-109d4900-dbce-11e9-8e88-922b63ab3307.png">
CocoaPods 图:
<img width="472" alt="p1" src="https://user-images.githubusercontent.com/13343398/65317372-4a6e4f80-dbce-11e9-8295-2b559a5831e6.png">
<img width="483" alt="p2" src="https://user-images.githubusercontent.com/13343398/65317383-4f330380-dbce-11e9-9a04-8a97f0c85247.png">
我直接
pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'
版本最高才3.0.2

**Comment by 274180213** [comment]
使用JavaScript函数自定义X轴文字内容之后的效果:
<img width="401" alt="z" src="https://user-images.githubusercontent.com/13343398/65320437-6aa10d00-dbd4-11e9-9b3b-1a8436ae98a2.png">

**Comment by AAChartModel** [comment]
>  为什么pod上有只有2.1.6版本

因为我经常会对AAChartKit内部代码进行小范围的重构,每次更新都提交推送至Cocoapods太麻烦了,所以就偷了点懒,后续的都没有继续提交至Cocoapods上了.

**Comment by yacosdad** [comment]
> > 为什么pod上有只有2.1.6版本
> 
> 因为我经常会对AAChartKit内部代码进行小范围的重构,每次更新都提交推送至Cocoapods太麻烦了,所以就偷了点懒,后续的都没有继续提交至Cocoapods上了.

这样偷懒不行啊，s.dependency 不能依赖未发布的版本，只能更新到 2.1.6，速度更新下吧。
