### ISSUE TITLE
图标刷新加载不出来的问题

### ISSUE THREAD

**Issue by tan694525925** [AAChartModel/AAChartKit#734]
![WX20190923-110253](https://user-images.githubusercontent.com/13333806/65399879-b977be00-ddf1-11e9-9cf7-1c35212cf446.png)
您好，这种图标刷新不出来的原因是什么呢？ 有时候是可以加载出来的

**Comment by AAChartModel** [comment]
这种情况没有遇到过,有可能是你刷新时的数据给的不太对.
