### ISSUE TITLE
iOS 8 无法显示

### ISSUE THREAD

**Issue by fanxingmao** [AAChartModel/AAChartKit#737]
Could not create a sandbox extension for '/'

**Comment by AAChartModel** [comment]
之前苹果在iOS 13推出来之后,应用审核中禁用了UIWebView,所以AAChartKit移除了UIWebView.

**Comment by AAChartModel** [comment]
WKWebView虽然是iOS 8就推出来的新控件,但是再iOS 8下有个坑----无法直接加载本地资源文件,所以这个问题我需要改一下AAChartKit里面的逻辑.

**Comment by fanxingmao** [comment]
> WKWebView虽然是iOS 8就推出来的新控件,但是再iOS 8下有个坑----无法直接加载本地资源文件,所以这个问题我需要改一下AAChartKit里面的逻辑.

好的

**Comment by AAChartModel** [comment]
问题已修复了,新增了 

```objc
- (NSURL *)localFileURLForBuggyiOS8WKWebViewWithFileURL:(NSURL *)fileURL {
...
...
}
```

方法,借以兼容iOS 8中的WKWebView的问题.


**PS:** 考虑到连淘宝、支付宝、微信、微博,这些个亿万级用户的国民APP最低兼容系统版本号都是iOS 9 +,我有点怀疑这个功能的实际价值😂😂😂
