### ISSUE TITLE
执行添加数据报错

### ISSUE THREAD

**Issue by CocoaJiang** [AAChartModel/AAChartKit#741]
nating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'

**Comment by AAChartModel** [comment]
请使用

```ruby
pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'

```

来导入最新版本的bAAChartKit.  Cocoapods 上的不是最新版的AAChartKit.
