### ISSUE TITLE
怎么让Y轴的数据不从0开始，最大最小值设置没有效果呢

### ISSUE THREAD

**Issue by mailes** [AAChartModel/AAChartKit#744]
yAxisMax
yAxisMin
在设置之后好像没有效果呢。

**Comment by AAChartModel** [comment]
请贴上你的代码看看(贴代码文本,不要截图)

**Comment by mailes** [comment]
AAChartModel *aaChartModel= AAObject(AAChartModel)
    .chartTypeSet(AAChartTypeAreaspline)
    .titleSet(@"")
    .subtitleSet(@"")
    .categoriesSet(categorys)
    .yAxisTitleSet(@"")
    .yAxisMinSet(@10.0)
    .yAxisMaxSet(@130.0)
    .xAxisTickIntervalSet(@2)
    .seriesSet(@[
                 AAObject(AASeriesElement)
                 .nameSet(@"体重")
                 .colorSet(@"#2494F3")
                 .dataSet(arys)
                 ])
    ;
    aaChartModel.legendEnabled = NO;
    aaChartModel.yAxisVisible = YES;
    aaChartModel.easyGradientColors = YES;
    aaChartModel.zoomType = AAChartZoomTypeXY;
    aaChartModel.tooltipValueSuffix=@"kg";
    [_aaChartView aa_drawChartWithChartModel:aaChartModel];

yAxisMinSet
yAxisMaxSet
设置了，可是在Y轴显示上 还是从0开始的。
categorys 是x轴日期
arys 是体重数组

**Comment by mailes** [comment]
.yAxisMinSet([NSNumber numberWithInteger:5])
    .yAxisMaxSet([NSNumber numberWithInteger:80])
这样设置也不行。

**Comment by mailes** [comment]
-
![Simulator Screen Shot - iPhone 8 - 2019-10-12 at 15 52 31](https://user-images.githubusercontent.com/2554806/66697502-c27cf080-ed08-11e9-981e-43b1d9da2d6a.png)

**Comment by mailes** [comment]
> 请贴上你的代码看看(贴代码文本,不要截图)

请看上面，谢谢。

**Comment by mailes** [comment]
突然好用了！
发现必须得是先声明
NSNumber * minnum=xxx// 
然后在yAxisMinSet(minnum)
这样才好用！
如果直接是yAxisMinSet(@10) 这样不起效果，最大值也是！
不知道什么原因！！！

**Comment by mailes** [comment]
上述作废！依然不好用。

**Comment by AAChartModel** [comment]
https://github.com/AAChartModel/AAChartKit/commit/f193d96fec41597115195aecbf458b454d17e267

是因为我在此次提交中为 X轴和 Y轴新增了 startOnTick 和 endOnTick 这两个属性. 之前提交了代码之后忘了说了.

**Comment by mailes** [comment]
> [f193d96](https://github.com/AAChartModel/AAChartKit/commit/f193d96fec41597115195aecbf458b454d17e267)
> 
> 是因为我在此次提交中为 X轴和 Y轴新增了 startOnTick 和 endOnTick 这两个属性. 之前提交了代码之后忘了说了.

可以了！！！！！很棒！！！！！
