### ISSUE TITLE
自定义双y轴AATooltip

### ISSUE THREAD

**Issue by 15160378563** [AAChartModel/AAChartKit#745]
能否实现自定义tooltip头部OC拼接字符串以及分类颜色自定义
![14_46_15__10_14_2019](https://user-images.githubusercontent.com/22139358/66733261-8aed8000-ee91-11e9-8b89-906bc86b6249.jpg)

**Comment by AAChartModel** [comment]
可以实现,AAChartKit 的 demo 中有很多关于如何自定义 AATooltip 的使用示例.下载运行最新 AAChartKit 的 demo查看学习即可.

**Comment by AAChartModel** [comment]
复杂情况,可使用 formatter 属性(JavaScript 函数字符串)来自定义 AATooltip

```objc
AAPropStatementAndPropSetFuncStatement(copy,   AATooltip, NSString *, formatter) 

```
