### ISSUE TITLE
图表背景色问题

### ISSUE THREAD

**Issue by JustCompThin** [AAChartModel/AAChartKit#746]
多图表, (柱状图和折线图混合)设置了图表背景色为黑色  chartView背景色没问题 但是绘制出来的图 一直是白色的...

**Comment by AAChartModel** [comment]
贴一下你的代码看看(纯文本,不要截图)

**Comment by JustCompThin** [comment]
// 主要代码如下

#import "AAChartKit.h"

@interface ChartView()

@property (nonatomic, strong) AAChartView   *aaChartView;

@end

@implementation ChartView

- (instancetype)initWithFrame:(CGRect)frame {
    if (self = [super initWithFrame:frame]) {

    	self.backgroundColor = [UIColor colorWithHexString:@"#000033"];
        
    	AAChartView  *aaChartView = [[AAChartView alloc] initWithFrame:CGRectMake(0, 0, SCREEN_WIDTH, frame.size.height)];
        aaChartView.backgroundColor = kDashBackgroundColor;
        aaChartView.isClearBackgroundColor = true;
        aaChartView.scrollEnabled = false;

        self.aaChartView = aaChartView;

    }
    return self;
}

// dataSource 是从接口获取的数据
- (void)setChartDataSource:(NSDictionary *)chartSource{

    [self addSubview:self.aaChartView];

	AAOptions *options = [self configColumnrangeMixedLineChartWithSource:chartSource];
    [self.aaChartView aa_drawChartWithOptions:options];

}


- (AAOptions *)configColumnrangeMixedLineChartWithSource:(NSDictionary *)chartSource {
    
    NSMutableArray *yVals1 = chartSource[@"yValue1"];
    NSMutableArray *yVals2 = chartSource[@"yValue2"];
    NSMutableArray *yValsPersent = [[NSMutableArray alloc] init];
    NSMutableArray *y2ValsPersent = [[NSMutableArray alloc] init];
    NSMutableArray *xTitleArray = chartSource[@"xValues"];
    
    float y1Max = [chartSource[@"maxValueY1"] floatValue];
    float perY = y1Max/5;
    for (NSInteger index = 0; index <= 5; index++) {
        NSString *y1Str = [NSString stringWithFormat:@"%.1f",perY * index];
        [yValsPersent addObject:y1Str];
    }
    
    float y2Max = [chartSource[@"maxValueRateY"] floatValue];
    float y2Min = [chartSource[@"minValueRateY"] floatValue];
    
    float perY2 = floorf((y2Max - y2Min)/xTitleArray.count);
    for (NSInteger index = xTitleArray.count-1; index >= 0; index--) {
        NSString *y2Str = [NSString stringWithFormat:@"%.1f",y2Max -  perY2 * index];
        [y2ValsPersent addObject:y2Str];
    }
    
    AATitle *aaTitle = AATitle.new.textSet(@"");
    
    // 设置X轴显示内容
    AAXAxis *aaXAxis = AAXAxis.new.visibleSet(true)
                        .minSet(@0)
                        .categoriesSet(xTitleArray);
    
    // 设置Y轴标题样式
    AAStyle *aaYAxisTitleStyle  = AAStyle.new.colorSet(@"#00ffff")
                                    .fontSizeSet(@"12px")
                                    .textOutlineSet(@"0px 0px contrast");
    
    // 设置Y轴显示内容的样式
    AALabels *aaYAxisLabels = AALabels.new.enabledSet(true)
                                    .formatSet(@"{value:..2f}")
                                    .styleSet(AAStyle.new.colorSet(@"ff0000")
                                    .fontSizeSet(@"10px"));
    
    AALabels *aaY2AxisLabels = AALabels.new.enabledSet(true)
                                    .formatSet(@"{value:..2f}%")
                                    .styleSet(AAStyle.new.colorSet(@"ff0000")
                                    .fontSizeSet(@"10px"));
    // 设置第一个Y轴的显示内容
    AAYAxis *yAxisFirst = AAYAxis.new.visibleSet(true).labelsSet(aaYAxisLabels).titleSet(AAAxisTitle.new.textSet(@"").styleSet(aaYAxisTitleStyle));
    
    // 设置第二个Y轴的显示内容
    AAYAxis *yAxisSencod = AAYAxis.new.visibleSet(true).labelsSet(aaY2AxisLabels).titleSet(AAAxisTitle.new.textSet(@"").styleSet(aaYAxisTitleStyle)).oppositeSet(true);
    
    // 设置ToolTip
    AATooltip *aaToolTip = AATooltip.new.enabledSet(true).sharedSet(true);
    aaToolTip.valueDecimals = @2;
    
    NSDictionary *gradientColorDic1 = [AAGradientColor gradientColorWithDirection:AALinearGradientDirectionToTop startColorString:@"#f54e2a" endColorString:@"#ff9a77"];

    NSDictionary *gradientColorDic2 = [AAGradientColor gradientColorWithDirection:AALinearGradientDirectionToTop startColorString:@"#ff7676" endColorString:@"#007733"];

    NSDictionary *gradientColorDicLine = [AAGradientColor gradientColorWithDirection:AALinearGradientDirectionToTop startColorString:@"#17ead9" endColorString:@"#77ffff"];
    
    AAMarker *marker = AAMarker.new.radiusSet(@1).symbolSet(AAChartSymbolTypeCircle).fillColorSet(@"#000033").lineWidthSet(@3).lineColorSet(@"#77ffff");
    
    NSArray *aaSeries = @[
        AASeriesElement.new.nameSet(@"实际用能").typeSet(AAChartTypeColumn).colorSet((id)gradientColorDic1).yAxisSet(@0).dataSet(yVals1),
        AASeriesElement.new.nameSet(@"计划用能").typeSet(AAChartTypeColumn).colorSet((id)gradientColorDic2).yAxisSet(@0).dataSet(yVals2),
        AASeriesElement.new.nameSet(@"节能率").typeSet(AAChartTypeLine).colorSet((id)gradientColorDicLine).yAxisSet(@1).markerSet(marker).dataSet(chartSource[@"rateValues"])
        ];
    
    AAOptions *aaOptions = AAOptions.new.titleSet(aaTitle).backgroundColorSet(@"#000").xAxisSet(aaXAxis).yAxisSet((id)@[yAxisFirst,yAxisSencod]).tooltipSet(aaToolTip).seriesSet(aaSeries);
    return aaOptions;
}

@end

View Debug Hierarchy 工具显示 aaChartView 背景色没问题, 最上层的WKCompositingView 是白色的...

**Comment by JustCompThin** [comment]
`
// 主要代码如下

#import "AAChartKit.h"

@interface ChartView()

@property (nonatomic, strong) AAChartView   *aaChartView;

@end

@implementation ChartView

- (instancetype)initWithFrame:(CGRect)frame {
    if (self = [super initWithFrame:frame]) {

    	self.backgroundColor = [UIColor colorWithHexString:@"#000033"];
        
    	AAChartView  *aaChartView = [[AAChartView alloc] initWithFrame:CGRectMake(0, 0, SCREEN_WIDTH, frame.size.height)];
        aaChartView.backgroundColor = kDashBackgroundColor;
        aaChartView.isClearBackgroundColor = true;
        aaChartView.scrollEnabled = false;

        self.aaChartView = aaChartView;

    }
    return self;
}

// dataSource 是从接口获取的数据
- (void)setChartDataSource:(NSDictionary *)chartSource{

    [self addSubview:self.aaChartView];

	AAOptions *options = [self configColumnrangeMixedLineChartWithSource:chartSource];
    [self.aaChartView aa_drawChartWithOptions:options];

}


- (AAOptions *)configColumnrangeMixedLineChartWithSource:(NSDictionary *)chartSource {
    
    NSMutableArray *yVals1 = chartSource[@"yValue1"];
    NSMutableArray *yVals2 = chartSource[@"yValue2"];
    NSMutableArray *yValsPersent = [[NSMutableArray alloc] init];
    NSMutableArray *y2ValsPersent = [[NSMutableArray alloc] init];
    NSMutableArray *xTitleArray = chartSource[@"xValues"];
    
    float y1Max = [chartSource[@"maxValueY1"] floatValue];
    float perY = y1Max/5;
    for (NSInteger index = 0; index <= 5; index++) {
        NSString *y1Str = [NSString stringWithFormat:@"%.1f",perY * index];
        [yValsPersent addObject:y1Str];
    }
    
    float y2Max = [chartSource[@"maxValueRateY"] floatValue];
    float y2Min = [chartSource[@"minValueRateY"] floatValue];
    
    float perY2 = floorf((y2Max - y2Min)/xTitleArray.count);
    for (NSInteger index = xTitleArray.count-1; index >= 0; index--) {
        NSString *y2Str = [NSString stringWithFormat:@"%.1f",y2Max -  perY2 * index];
        [y2ValsPersent addObject:y2Str];
    }
    
    AATitle *aaTitle = AATitle.new.textSet(@"");
    
    // 设置X轴显示内容
    AAXAxis *aaXAxis = AAXAxis.new.visibleSet(true)
                        .minSet(@0)
                        .categoriesSet(xTitleArray);
    
    // 设置Y轴标题样式
    AAStyle *aaYAxisTitleStyle  = AAStyle.new.colorSet(@"#00ffff")
                                    .fontSizeSet(@"12px")
                                    .textOutlineSet(@"0px 0px contrast");
    
    // 设置Y轴显示内容的样式
    AALabels *aaYAxisLabels = AALabels.new.enabledSet(true)
                                    .formatSet(@"{value:..2f}")
                                    .styleSet(AAStyle.new.colorSet(@"ff0000")
                                    .fontSizeSet(@"10px"));
    
    AALabels *aaY2AxisLabels = AALabels.new.enabledSet(true)
                                    .formatSet(@"{value:..2f}%")
                                    .styleSet(AAStyle.new.colorSet(@"ff0000")
                                    .fontSizeSet(@"10px"));
    // 设置第一个Y轴的显示内容
    AAYAxis *yAxisFirst = AAYAxis.new.visibleSet(true).labelsSet(aaYAxisLabels).titleSet(AAAxisTitle.new.textSet(@"").styleSet(aaYAxisTitleStyle));
    
    // 设置第二个Y轴的显示内容
    AAYAxis *yAxisSencod = AAYAxis.new.visibleSet(true).labelsSet(aaY2AxisLabels).titleSet(AAAxisTitle.new.textSet(@"").styleSet(aaYAxisTitleStyle)).oppositeSet(true);
    
    // 设置ToolTip
    AATooltip *aaToolTip = AATooltip.new.enabledSet(true).sharedSet(true);
    aaToolTip.valueDecimals = @2;
    
    NSDictionary *gradientColorDic1 = [AAGradientColor gradientColorWithDirection:AALinearGradientDirectionToTop startColorString:@"#f54e2a" endColorString:@"#ff9a77"];

    NSDictionary *gradientColorDic2 = [AAGradientColor gradientColorWithDirection:AALinearGradientDirectionToTop startColorString:@"#ff7676" endColorString:@"#007733"];

    NSDictionary *gradientColorDicLine = [AAGradientColor gradientColorWithDirection:AALinearGradientDirectionToTop startColorString:@"#17ead9" endColorString:@"#77ffff"];
    
    AAMarker *marker = AAMarker.new.radiusSet(@1).symbolSet(AAChartSymbolTypeCircle).fillColorSet(@"#000033").lineWidthSet(@3).lineColorSet(@"#77ffff");
    
    NSArray *aaSeries = @[
        AASeriesElement.new.nameSet(@"实际用能").typeSet(AAChartTypeColumn).colorSet((id)gradientColorDic1).yAxisSet(@0).dataSet(yVals1),
        AASeriesElement.new.nameSet(@"计划用能").typeSet(AAChartTypeColumn).colorSet((id)gradientColorDic2).yAxisSet(@0).dataSet(yVals2),
        AASeriesElement.new.nameSet(@"节能率").typeSet(AAChartTypeLine).colorSet((id)gradientColorDicLine).yAxisSet(@1).markerSet(marker).dataSet(chartSource[@"rateValues"])
        ];
    
    AAOptions *aaOptions = AAOptions.new.titleSet(aaTitle).backgroundColorSet(@"#000").xAxisSet(aaXAxis).yAxisSet((id)@[yAxisFirst,yAxisSencod]).tooltipSet(aaToolTip).seriesSet(aaSeries);
    return aaOptions;
}

@end
`
View Debug Hierarchy 工具显示 aaChartView 背景色没问题, 最上层的WKCompositingView 是白色的...

**Comment by JustCompThin** [comment]
```

// 主要代码如下

#import "AAChartKit.h"

@interface ChartView()

@property (nonatomic, strong) AAChartView   *aaChartView;

@end

@implementation ChartView

- (instancetype)initWithFrame:(CGRect)frame {
    if (self = [super initWithFrame:frame]) {

    	self.backgroundColor = [UIColor colorWithHexString:@"#000033"];
        
    	AAChartView  *aaChartView = [[AAChartView alloc] initWithFrame:CGRectMake(0, 0, SCREEN_WIDTH, frame.size.height)];
        aaChartView.backgroundColor = kDashBackgroundColor;
        aaChartView.isClearBackgroundColor = true;
        aaChartView.scrollEnabled = false;

        self.aaChartView = aaChartView;

    }
    return self;
}

// dataSource 是从接口获取的数据
- (void)setChartDataSource:(NSDictionary *)chartSource{

    [self addSubview:self.aaChartView];

	AAOptions *options = [self configColumnrangeMixedLineChartWithSource:chartSource];
    [self.aaChartView aa_drawChartWithOptions:options];

}


- (AAOptions *)configColumnrangeMixedLineChartWithSource:(NSDictionary *)chartSource {
    
    NSMutableArray *yVals1 = chartSource[@"yValue1"];
    NSMutableArray *yVals2 = chartSource[@"yValue2"];
    NSMutableArray *yValsPersent = [[NSMutableArray alloc] init];
    NSMutableArray *y2ValsPersent = [[NSMutableArray alloc] init];
    NSMutableArray *xTitleArray = chartSource[@"xValues"];
    
    float y1Max = [chartSource[@"maxValueY1"] floatValue];
    float perY = y1Max/5;
    for (NSInteger index = 0; index <= 5; index++) {
        NSString *y1Str = [NSString stringWithFormat:@"%.1f",perY * index];
        [yValsPersent addObject:y1Str];
    }
    
    float y2Max = [chartSource[@"maxValueRateY"] floatValue];
    float y2Min = [chartSource[@"minValueRateY"] floatValue];
    
    float perY2 = floorf((y2Max - y2Min)/xTitleArray.count);
    for (NSInteger index = xTitleArray.count-1; index >= 0; index--) {
        NSString *y2Str = [NSString stringWithFormat:@"%.1f",y2Max -  perY2 * index];
        [y2ValsPersent addObject:y2Str];
    }
    
    AATitle *aaTitle = AATitle.new.textSet(@"");
    
    // 设置X轴显示内容
    AAXAxis *aaXAxis = AAXAxis.new.visibleSet(true)
                        .minSet(@0)
                        .categoriesSet(xTitleArray);
    
    // 设置Y轴标题样式
    AAStyle *aaYAxisTitleStyle  = AAStyle.new.colorSet(@"#00ffff")
                                    .fontSizeSet(@"12px")
                                    .textOutlineSet(@"0px 0px contrast");
    
    // 设置Y轴显示内容的样式
    AALabels *aaYAxisLabels = AALabels.new.enabledSet(true)
                                    .formatSet(@"{value:..2f}")
                                    .styleSet(AAStyle.new.colorSet(@"ff0000")
                                    .fontSizeSet(@"10px"));
    
    AALabels *aaY2AxisLabels = AALabels.new.enabledSet(true)
                                    .formatSet(@"{value:..2f}%")
                                    .styleSet(AAStyle.new.colorSet(@"ff0000")
                                    .fontSizeSet(@"10px"));
    // 设置第一个Y轴的显示内容
    AAYAxis *yAxisFirst = AAYAxis.new.visibleSet(true).labelsSet(aaYAxisLabels).titleSet(AAAxisTitle.new.textSet(@"").styleSet(aaYAxisTitleStyle));
    
    // 设置第二个Y轴的显示内容
    AAYAxis *yAxisSencod = AAYAxis.new.visibleSet(true).labelsSet(aaY2AxisLabels).titleSet(AAAxisTitle.new.textSet(@"").styleSet(aaYAxisTitleStyle)).oppositeSet(true);
    
    // 设置ToolTip
    AATooltip *aaToolTip = AATooltip.new.enabledSet(true).sharedSet(true);
    aaToolTip.valueDecimals = @2;
    
    NSDictionary *gradientColorDic1 = [AAGradientColor gradientColorWithDirection:AALinearGradientDirectionToTop startColorString:@"#f54e2a" endColorString:@"#ff9a77"];

    NSDictionary *gradientColorDic2 = [AAGradientColor gradientColorWithDirection:AALinearGradientDirectionToTop startColorString:@"#ff7676" endColorString:@"#007733"];

    NSDictionary *gradientColorDicLine = [AAGradientColor gradientColorWithDirection:AALinearGradientDirectionToTop startColorString:@"#17ead9" endColorString:@"#77ffff"];
    
    AAMarker *marker = AAMarker.new.radiusSet(@1).symbolSet(AAChartSymbolTypeCircle).fillColorSet(@"#000033").lineWidthSet(@3).lineColorSet(@"#77ffff");
    
    NSArray *aaSeries = @[
        AASeriesElement.new.nameSet(@"实际用能").typeSet(AAChartTypeColumn).colorSet((id)gradientColorDic1).yAxisSet(@0).dataSet(yVals1),
        AASeriesElement.new.nameSet(@"计划用能").typeSet(AAChartTypeColumn).colorSet((id)gradientColorDic2).yAxisSet(@0).dataSet(yVals2),
        AASeriesElement.new.nameSet(@"节能率").typeSet(AAChartTypeLine).colorSet((id)gradientColorDicLine).yAxisSet(@1).markerSet(marker).dataSet(chartSource[@"rateValues"])
        ];
    
    AAOptions *aaOptions = AAOptions.new.titleSet(aaTitle).backgroundColorSet(@"#000").xAxisSet(aaXAxis).yAxisSet((id)@[yAxisFirst,yAxisSencod]).tooltipSet(aaToolTip).seriesSet(aaSeries);
    return aaOptions;
}

@end
```
<img width="282" alt="截屏2019-10-15下午4 14 12" src="https://user-images.githubusercontent.com/30522606/66813381-3a485680-ef67-11e9-8fb1-997403646131.png">


图表没有显示期望的深色 而是显示白色......

**Comment by AAChartModel** [comment]
你有所不知,在 AAChartKit 中设置图标背景色主要靠 AAChartModel 来配置

        ```objc

    AAChart *aaChart = AAChart.new
    .backgroundColorSet(AAColor.blackColor);

    aaOption.chartSet(aaChart);
        ```

        加上这部分内容就可以了

        ```objc
        aaChartView.backgroundColor = kDashBackgroundColor;

        ```

        AAChartView 的背景色属性`backgroundColor`除了在设置背景色为透明的时候,基本没有用处

**Comment by AAChartModel** [comment]
```objc
    AAChart *aaChart = AAChart.new
    .backgroundColorSet(AAColor.blackColor);

    aaOption.chartSet(aaChart);

```

加上这部分内容就可以实现你想要的深色背景了

**Comment by AAChartModel** [comment]
```objc
        aaChartView.backgroundColor = kDashBackgroundColor;

        ```

        其实 AAChartView 的背景色属性`backgroundColor`除了在设置背景色为透明的时候,基本没有用处,所以你的这个代码不起作用

**Comment by JustCompThin** [comment]
多谢大佬.....

**Comment by AAChartModel** [comment]
PS: 话说你这链式编程代码干嘛不换行啊,在 GitHub 的 issues 评论区空间太小,一行代码太长,还要来回滚动查看很蛋疼🤣🤣🤣

**Comment by JustCompThin** [comment]
不知道是不是我的Xcode的问题, 如果先换行再写的话就没有代码提示了. 提示完了太长 我也懒得再一个个去换行了.....

**Comment by AAChartModel** [comment]
好吧,我这边换行些, Xcode 倒是提示正常
