### ISSUE TITLE
作者您好，x轴categories必须要跟dataSet保持同样数量吗？

### ISSUE THREAD

**Issue by Goldx4** [AAChartModel/AAChartKit#749]
我这边有个需求，categories是自定义非连续的，所以用tickInterval不满足，看了作者您在别的回答里答道用空字符串@""代替，比如 @[@"Java", @"Python", @"Swift", @"", @"", @"", @""]，这样空字符串的确没有显示，但是底部间距也不能撑开了，是否有属性满足这样的需求？

**Comment by AAChartModel** [comment]
是的,否则后面X轴的标记点文字就会根据当前标记点的 index 进行递增
