### ISSUE TITLE
[提问帖] 标识的数值如何显示%

### ISSUE THREAD

**Issue by xuanInitial** [AAChartModel/AAChartKit#755]
.seriesSet(@[
        AASeriesElement.new
        .nameSet(@"")
        .dataSet(@[@30, @8, @4, @24, @26, @46, @50, @28, @66, @88, @52, @50])

这样只能设置数值  不能设置%

**Comment by AAChartModel** [comment]
数据的DataLabels 统一追加单位 ,参见 https://github.com/AAChartModel/AAChartKit/issues/682#issuecomment-514088892

**Comment by xuanInitial** [comment]
感谢 我看了 [#747 ](https://github.com/AAChartModel/AAChartKit/issues/747)的实例

**Comment by AAChartModel** [comment]
#747 的方法主要可用于解决你的 #754 问题.  只不过需要你自己来遍历查找 data 数组中的最大值和最小值,AAChartKit 本身无此功能.

**Comment by xuanInitial** [comment]
再次打扰一下  
曲线这样设置不起作用

self.aaChartView = [[AAChartView alloc]init];
    self.aaChartView.frame = CGRectMake(0, 134, SCREEN_W, 209);
    self.aaChartView.delegate = self;
    
    [self.contentView addSubview:self.aaChartView];
    self.aaChartView.backgroundColor = [UIColor clearColor];
    
    //设置 AAChartView 的背景色是否为透明
    _aaChartView.isClearBackgroundColor = YES;
    
    _aaChartModel= AAChartModel.new
    .chartTypeSet(AAChartTypeSpline)//图表类型
    .titleSet(@"")//图表主标题
    .subtitleSet(@"")//图表副标题
    .yAxisLabelsEnabledSet(NO)
    .yAxisLineWidthSet(@0)//Y轴轴线线宽为0即是隐藏Y轴轴线
    .yAxisTitleSet(@"")//设置 Y 轴标题
    .tooltipValueSuffixSet(@"%")//设置浮动提示框单位后缀
    .backgroundColorSet(@"#4b2b7f")
    .yAxisGridLineWidthSet(@0)//y轴横向分割线宽度为0(即是隐藏分割线)
    .touchEventEnabledSet(NO)//支持用户点击事件
    .tooltipEnabledSet(NO)
    .dataLabelsEnabledSet(true)
    .connectNullsSet(true)
    .legendEnabledSet(NO)
    .dataLabelsFontColorSet(@"#909399")
    .categoriesSet(@[@"1月",@"2月",@"3月",@"4月",@"5月",@"6月",@"7月",@"8月",@"9月",@"10月",@"11月",@"12月"])
    .xAxisCrosshairColorSet(@"#FFFFFF")
    .xAxisCrosshairWidthSet(0)
    .markerRadiusSet(@3)
    .xAxisCrosshairDashStyleTypeSet(AAChartSymbolStyleTypeDefault)
    .markerSymbolStyleSet(AAChartSymbolStyleTypeDefault)//设置折线连接点样式为
    .xAxisCrosshairColorSet(@"#3AA0FF")
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"")
        .dataSet(@[@30, @8, @4, @24, @26, @46, @50, @28, @66, @88, @52, @50]),
        
        
    ]
            );
    
    AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:_aaChartModel];

          aaOptions.plotOptions.spline.dataLabels
          .ySet(@-10)
          .formatSet(@"{y}%%")
         // .backgroundColorSet(@"rgba(0, 0, 0, 0.75)")
          .shapeSet(@"callout")
          .styleSet(AAStyle.new
                    .colorSet(@"#909399")
                    .textOutlineSet(@"none"));
    
    
    /*配置 Y 轴标注线,)*/
    [self configureTheYAxisPlotLineForAAChartView];
    
    [_aaChartView aa_drawChartWithChartModel:_aaChartModel];

**Comment by AAChartModel** [comment]
绘制图表的函数调用的不对.

将
```objc
    [_aaChartView aa_drawChartWithChartModel:_aaChartModel];
```
修改为
```objc
        [self.aaChartView aa_refreshChartWithOptions:aaOptions];
```
即可.

**Comment by xuanInitial** [comment]
更改了调用方式
只调用
`[self.aaChartView aa_refreshChartWithOptions:aaOptions];`
不起作用


`  .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"")
        .dataSet(@[@30, @8, @4, @24, @26, @46, @50, @28, @66, @88, @52, @50]),]
            );
    
    /*配置 Y 轴标注线,)*/
    [self configureTheYAxisPlotLineForAAChartView];
    
    AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:_aaChartModel];

          aaOptions.plotOptions.spline.dataLabels
        //  .ySet(@-10)
          .formatSet(@"{y}%")
          .styleSet(AAStyle.new
                    .colorSet(@"#909399")
                    .textOutlineSet(@"none"));
    
    [self.aaChartView aa_drawChartWithChartModel:_aaChartModel];
    
    [self.aaChartView aa_refreshChartWithOptions:aaOptions];`

效果图如下
<img width="326" alt="屏幕快照 2019-10-18 下午7 09 42" src="https://user-images.githubusercontent.com/20314658/67089703-e47be480-f1da-11e9-8141-d64dbdf69364.png">

**Comment by AAChartModel** [comment]
抱歉,写错了,应该是将
```objc
[_aaChartView aa_drawChartWithChartModel:_aaChartModel];

```

改成

```objc
    [aaChartView aa_drawChartWithOptions:aaOptions];

```

**Comment by AAChartModel** [comment]
`aa_drawChartWithOptions`方法是绘制图形,  `aa_refreshChartWithOptions`是刷新图形.

你这里只要把

```objc
[self.aaChartView aa_drawChartWithChartModel:_aaChartModel];

[self.aaChartView aa_refreshChartWithOptions:aaOptions];
```

改成
```objc
[aaChartView aa_drawChartWithOptions:aaOptions];

```

就可以了,两个方法同时调用会造成重复绘制,浪费计算资源.

**Comment by xuanInitial** [comment]
感谢回复，已经解决
