### ISSUE TITLE
宽度不够时，x轴刻度显示有问题

### ISSUE THREAD

**Issue by Goldx4** [AAChartModel/AAChartKit#758]
作者您好，我这边测试，数据如下：
1. 自动布局，宽度距左边10，右边10，实际宽度275
 
> type = AAChartTypeLine
>  categories = @[354 objects] 
>   series = @[@[354 objects], @[354 objects], @[354 objects]]
>  step = @(60)

 此时x轴刻度**只显示一个01**

2. 当我**调整布局**，将实际宽度改为400的时候，**此时x轴刻度显示正确**

我的解决办法：使用transformScale使之变形，的确有效，但是导致显示的文字也变形了

#### 所以请问作者，我这个有没有解决办法或者说怎么解决比较好，谢谢！

**Comment by AAChartModel** [comment]
这个问题主要原因是 Highcharts 为自动避免文字堆叠拥挤,所以省略部分文字. 可以尝试这个属性

```objc
//只针对水平轴有效，定义轴标签显示行数。
AAPropStatementAndPropSetFuncStatement(strong, AALabels, NSNumber *, staggerLines)
```

**Comment by AAChartModel** [comment]
或者**缩小文字字体大小**,或者设置**文字旋转角度**,借以腾出足够空间以显示所有X轴文字标签.

X轴文字标签所有属性,参见 API  https://api.highcharts.com.cn/highcharts#xAxis.labels

**Comment by Goldx4** [comment]
我理解Highcharts的省略部分文字的做法，但是我这边已经设置了 step = 60，真正需要显示的也才6个label，这样它为啥还省略呢？或者说有没有允许x轴label叠加的属性？（API中没有找到。。。）

**Comment by AAChartModel** [comment]
> API中没有找到。。。

那估计就是真的没有了....

**Comment by Goldx4** [comment]
我尝试自己添加view去自定义x轴的label, 但是我们这边update比较频繁，支持多条折线的比较，导致每次update的时候，x轴不固定，一会偏上一会偏右，导致自定义这条路也走不通。。。

**Comment by AAChartModel** [comment]
估计`tickPosition`和`tickPositioner` 这两个属性可能有用

 https://api.highcharts.com.cn/highcharts#xAxis.tickPosition

官方问答:

https://www.highcharts.com/forum/viewtopic.php?t=39283

**Comment by AAChartModel** [comment]
这些 JavaScript 代码你可以请教一下公司前端
