### ISSUE TITLE
x轴只显示头尾

### ISSUE THREAD

**Issue by leftzhang** [AAChartModel/AAChartKit#760]
X轴可以实现显示头尾数据，中间数据隐藏，自定义浮动框时能取到X轴的值？

**Comment by AAChartModel** [comment]
能取到值

**Comment by AAChartModel** [comment]
数值只是隐藏了，并不是被移除了

**Comment by leftzhang** [comment]
其实我想问的是 怎样隐藏X轴中间数据?  我现在的做法是中间X轴categories都是空字符，但是又有需求自定义浮动框，需要X轴实际的数据

**Comment by AAChartModel** [comment]
有个关键词属性  `step` 可以满足你的要求,你可以看看

参考此问题   #751

**Comment by AAChartModel** [comment]
Step 属性 API 说明  https://api.highcharts.com.cn/highcharts#xAxis.labels.step

**Comment by leftzhang** [comment]
step可以满足我的需求  谢谢你  谢谢你 谢谢你

**Comment by AAChartModel** [comment]
> 谢谢你 谢谢你 谢谢你

你的心意我已收到,多谢,再会👋🙂
