### ISSUE TITLE
Y轴刻度显示问题

### ISSUE THREAD

**Issue by ZhenYeGuo** [AAChartModel/AAChartKit#765]
yAxisTickPositionsSet (@[@(0),@(50),@(100),@(150),@(200)])  但是当我的dataSet里面没有数据时候，y轴设置刻度也不显示，怎么设置？设置了  .yAxisVisibleSet(true)//设置 Y 轴是否可见
    .yAxisLabelsEnabledSet (YES)//y 轴是否显示数据 但是Y周刻度还是根据数据进行显示，不是我设置的刻度，该怎么设置，请指教，谢谢

**Comment by AAChartModel** [comment]
参见问题 #804

**Comment by ZhenYeGuo** [comment]
> 参见问题 #804

thx
