### ISSUE TITLE
能实现x轴滑动就好了

### ISSUE THREAD

**Issue by AlaricMurray** [AAChartModel/AAChartKit#77]

**Comment by MR-THT** [comment]
x轴不能滑动。。。。。。

**Comment by AAChartModel** [comment]
这个我也有点忧伤,其实是能滑动的,但是 highchart 在手机移动端滑动的体验比较差😢

**Comment by tangaowen** [comment]
不能滑动吗，那我设置contentWidth > width的时候， 右边的内容不滑动不是看不到？

**Comment by AAChartModel** [comment]
你说的这种当然是可以滑动的,他们要的效果是在 contentWidth = width 的时候可以滑动,在这种情况下也是可以滑动的,就是体验不是十分的号.之前的 demo 里面不是添加了 contentWidth 的 setter 方法了吗,你也可以自己自己在 demo 中设置一下,让 contentWidth>width, 看看demo 运行之后的实际效果,再检验它是否能够满足你项目的实际需要.😝

**Comment by tangaowen** [comment]
好像是不能拖动， 即使是 contentWidth >  width的情况下。

**Comment by tangaowen** [comment]
这是个大坑啊， 不能拖动， demo 也试了， 这个数据量多点的时候，就基本上没法被实际项目使用了，希望大神能解决啊。

**Comment by tangaowen** [comment]
拖动的时候，是整个曲线被拖动，而不是 cotent 被移动。

**Comment by AAChartModel** [comment]
现在已经支持手势缩放了啊,默认是X轴缩放,放大后单指左右拖动图表即可,右上角有"恢复缩放按钮",点击恢复至缩放前的大小.

**Comment by tangaowen** [comment]
绝对不能拖， 你再自己试试吧？我一直就是用单手拖的， 拖的时候， 拖动的是曲线，而且放开 曲线会反弹。 另外你说的缩放不太明白，经常会在缩放跟非缩放之间切换，但是可以肯定的是， 确实是拖动有问题， 看不到 超出 width的 content内容。

**Comment by tangaowen** [comment]
或者说要支持拖动， 需要特殊的设置吗？  还是只需要 contentWidth > width就可以了？

**Comment by tangaowen** [comment]
另外有个发现，就是 我点击 图表下面的小圆点，这个时候曲线不显示了。 这个时候去拖动是可以缩放的，然后我再点击 底下的小圆点，然曲线显示出来，这个时候可以看到 曲线的全貌。 

另外 大神可能理解错我的意思了，我是想要类似 ScrollView这样的拖动效果，而不是指缩放功能。 大神的意思是通过缩放来实现对整个图表的预览是吗？

**Comment by AAChartModel** [comment]
@tangaowen 这个确实是我的锅,之前我为了让AAChartView像一个纯粹的 UIView, 避免出现滚动条,所以默认禁用了AAChartView 的滚动功能,导致了图表视图不能够滚动, 现在已移除这段代码,当你设置
```objective-c
    self.aaChartView.contentWidth = chartViewWidth *2;//设置AAChartView 的内容宽度contentWidth为自身宽度的两倍
```
也就是 contentWidth > width,即可进行单指拖动.
更新一下Demo, 尝试一下呗(最好在真机上测试一下效果)我已在真机上完成了测试,图表的单指拖动效果很流畅,完全达到了你所说的
> 我是想要类似 ScrollView这样的拖动效果，而不是指缩放功能

**Comment by tangaowen** [comment]
多谢大神， 发现这就是我想要的效果，我这边试了没问题。再次感谢！
