### ISSUE TITLE
当y轴数值都为0时，如何让y轴的0刻度线不在中间

### ISSUE THREAD

**Issue by Libogold** [AAChartModel/AAChartKit#773]
.seriesSet(@[
                 AASeriesElement.new
                 .nameSet(@"2017")
                 .dataSet(@[@0, @0, @0, @0
                 ]);
dataset 都为0时让y轴0刻度线和x轴重合，

**Comment by NoLiuxin** [comment]
AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:self.aaChartModel];
//设置刻度线个数
aaOptions.yAxis.tickAmount = @6;
//设置是否允许Y轴显示小数
aaOptions.yAxis.allowDecimals = NO;

这样设置后也不需要计算Y轴的刻度尺了。
都为0也会不在中间了，可以试一试

**Comment by AAChartModel** [comment]
```objc
   aaOptions.yAxis
    .minSet(@0)
    .minRangeSet(@1)
```

**Comment by AAChartModel** [comment]
## 配置 AAOptions

```objc
- (AAOptions *)customChartStyleWhenEveryDataValueIsZero {
    AAChartModel *aaChartModel= AAChartModel.new
    .chartTypeSet(AAChartTypeAreaspline)
    .titleSet(@"Custom Chart Style When Every Data Value Is 0")
    .categoriesSet(@[
        @"Java", @"Swift", @"Python", @"Ruby", @"PHP", @"Go",@"C",
        @"C#", @"C++", @"Perl", @"R", @"SQL"])
    .yAxisTitleSet(@"摄氏度 (℃)")
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"Tokyo Hot")
        .dataSet(@[@0, @0, @0, @0, @0, @0, @0, @0, @0, @0, @0, @0, ]),
    ]);
    
    AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];

    aaOptions.yAxis
    .minSet(@0)
    .minRangeSet(@1);
    
    return aaOptions;
}
```

## 折线图图表效果
![image](https://user-images.githubusercontent.com/16357599/71340970-70234000-2593-11ea-8e22-aa33e51aa89e.png)

**Comment by Jins-org** [comment]
@AAChartModel 作者你好，尝试了设置
`   aaOptions.yAxis
    .minSet(@0)
    .minRangeSet(@1)`
在AAChartTypeAreaspline下有效果，但在AAChartTypeLine下没有效果

**Comment by AAChartModel** [comment]
> @AAChartModel 作者你好，尝试了设置
> ` aaOptions.yAxis .minSet(@0) .minRangeSet(@1)`
> 在AAChartTypeAreaspline下有效果，但在AAChartTypeLine下没有效果

已在此次提交 https://github.com/AAChartModel/AAChartKit/issues/773#issuecomment-624997641 中解决, 按照 README 文档中所说, 将pod 更新至最新内容的 AAChartKit 即可.

**Comment by Jins-org** [comment]
@AAChartModel 👍非常感谢～
