### ISSUE TITLE
不能手指捏合放大缩小吗？安卓的怎么可以？

### ISSUE THREAD

**Issue by dream5788** [AAChartModel/AAChartKit#774]
不能手指捏合放大缩小吗？安卓的怎么可以？

**Comment by AAChartModel** [comment]
> 👌 支持手势缩放 . 支持各个方向的图表手势缩放和拖动阅览, 手势缩放类型具体参见 AAChartKit 手势缩放类型, 默认禁用手势缩放功能.

```diff
! 默认禁用手势缩放功能
```

**Comment by AAChartModel** [comment]
https://github.com/AAChartModel/AAChartKit/blob/master/CHINESE-README.md#%E5%BD%93%E5%89%8D%E5%B7%B2%E6%94%AF%E6%8C%81%E7%9A%84%E5%9B%BE%E8%A1%A8%E6%89%8B%E5%8A%BF%E7%BC%A9%E6%94%BE%E7%B1%BB%E5%9E%8B%E5%85%B1%E6%9C%89%E4%B8%89%E7%A7%8D%E8%AF%B4%E6%98%8E%E5%A6%82%E4%B8%8B

**Comment by AAChartModel** [comment]
```diff
typedef NSString *AAChartZoomType;

AACHARTKIT_EXTERN AAChartZoomType const AAChartZoomTypeNone; //禁用手势缩放功能(默认禁用手势缩放)
!AACHARTKIT_EXTERN AAChartZoomType const AAChartZoomTypeX;    //支持图表 X轴横向缩放
!AACHARTKIT_EXTERN AAChartZoomType const AAChartZoomTypeY;    //支持图表 Y轴纵向缩放
!AACHARTKIT_EXTERN AAChartZoomType const AAChartZoomTypeXY;   //支持图表等比例缩放
```

设置AAChartZoomType为黄色的的三个值当中的任意一个即表示支持手势缩放

**Comment by AAChartModel** [comment]
> 安卓的怎么可以？

安卓的我估计没有设置默认禁用

**Comment by dream5788** [comment]
回复那么及时，然后还有两个问题。
1.这个商用有版权问题吗？我看用的也是一个商业公司的js库。
2.数据量大的时候，dataLabelsEnabledSet开启会很卡，不开很流畅。有没有好的办法。

**Comment by AAChartModel** [comment]
> 1.这个商用有版权问题吗？我看用的也是一个商业公司的js库。


这个问题射中我的膝盖了,我因为之前的公司做企业服务软件的,其中有数据可视化相关的统计图表需求,用的 HighCharts,所以接触到了这个 js 框架,AAChartKit 也是由此而来, HighCharts 商用版权问题确实是我想要解决的一个问题.我之前有打算将依赖的 js 改为免费商用的 plotly.js 或 vega.js,不过这个改造的工作量有点大,需要时间. 有这方面的顾虑,可以考虑使用 swift 版本的原生图表库 iOS-Charts,这个通过混编,应该也能满足需求.  

PS:我之前的公司(上上家公司)使用 HighCharts 也没有付费,不过我已经离职很久了,如果公司倒闭了的话,估计也就不用负责了🤣🤣🤣
