### ISSUE TITLE
how can I off name of elements in a pie chart ?

### ISSUE THREAD

**Issue by NgocPhus** [AAChartModel/AAChartKit#777]
I can't see function off name with line of elements in pie chart , can someone help me ?

**Comment by AAChartModel** [comment]
What do you mean `off name of elements`???

**Comment by NgocPhus** [comment]
![Screen Shot 2019-11-12 at 3 34 15 PM](https://user-images.githubusercontent.com/52688735/68655152-11b17d80-0562-11ea-8a13-efbf917996b6.png)
I want to hide this, thank you.

**Comment by AAChartModel** [comment]
```objc
dataLabelsEnabledSet(false)
```

That is all you need to do. 🙂

**Comment by NgocPhus** [comment]
sorry I'm try but it not work for me

**Comment by AAChartModel** [comment]
please show me your code .  (Not code picture but the pure code text)

**Comment by NgocPhus** [comment]
- (void)viewDidLoad {
    [super viewDidLoad];
    
    _aaChartView = [[AAChartView alloc]init];
    _aaChartView.frame = CGRectMake(0, 0, self.contentView.frame.size.width, self.contentView.frame.size.height);
    
    [self.contentView addSubview:_aaChartView];
    
    _aaChartModel = AAObject(AAChartModel)
    .tooltipEnabledSet(NO)
    .dataLabelsEnabledSet(false)
    .colorsThemeSet(@[@"#1e90ff",@"#ededed",])
    .titleSet(@"AAAA")
    .titleFontColorSet(@"#ef476f")
    .legendEnabledSet(NO)
    .chartTypeSet(AAChartTypePie)
    .backgroundColorSet(@"#f2f2f2")
    .seriesSet(
               @[AAObject(AASeriesElement)
                 .innerSizeSet(@"75%")
                 .sizeSet(@100)
                 .dataSet(@[
                            @[@"Income"  , accomplishedPie],
                            @[@"Remaining" , remaining],
                            ]),
                 ]
                );
    [_aaChartView aa_drawChartWithChartModel:_aaChartModel];
}

That all , thank for your help.

**Comment by AAChartModel** [comment]
It was fixed in this commit https://github.com/AAChartModel/AAChartKit/commit/bd536cc273f05da65e752d457ff7d018f4a60ef8 ,

**Comment by AAChartModel** [comment]
```ruby
  pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'

```

`pod update` to the lastest version of AAChartKit
