### ISSUE TITLE
formatterSet问题

### ISSUE THREAD

**Issue by AllenYangShuang** [AAChartModel/AAChartKit#785]
请问一下，我想简单的展示一下X和Y轴的数据，当X轴为中文时，展示框会出现NaN，我该怎么处理，谢谢！
![image](https://user-images.githubusercontent.com/12180694/69421193-5bb51300-0d5b-11ea-8863-afdef537c550.png)

**Comment by AAChartModel** [comment]
给一张你的图表 UI 设计稿

**Comment by AAChartModel** [comment]
顺便贴一下你的 AAChartModel 配置代码(纯文本,不要截图)

**Comment by AllenYangShuang** [comment]
<img width="163" alt="image" src="https://user-images.githubusercontent.com/12180694/69488479-aa21f900-0ea4-11ea-8436-e9a59bc947b0.png">

**Comment by AllenYangShuang** [comment]
NSMutableArray *xTitles = [NSMutableArray array];
    for (int i = 0; i < model.form_columns.count; i++) {
        DGBFormColumnsModel *columnModel = [model.form_columns objectAtIndex:i];
        NSString * str = columnModel.column_title;
        [xTitles addObject:str];
    }
    //设置 AAChartView 的背景色是否为透明
    _aaChartView.isClearBackgroundColor = YES;
    
    AAChartModel *aaChartModel = AAChartModel.new
    .chartTypeSet(AAChartTypeLine)//图表类型
    .titleSet(@"")//图表主标题
    .subtitleSet(@"")//图表副标题
    .yAxisLineWidthSet(@0)//Y轴轴线线宽为0即是隐藏Y轴轴线
    .colorsThemeSet(@[@"#00FDFF"])//设置主体颜色数组
    .yAxisTitleSet(@"")//设置 Y 轴标题
    .backgroundColorSet(@"#4b2b7f")
    .legendEnabledSet(false)
    .yAxisGridLineColorSet(@"#3E4F7C")//Y轴分割线颜色
    .xAxisGridLineColorSet(@"#3E4F7C")//X轴分割线颜色
    .xTickWidthSet(@0)//隐藏X轴刻度线
    .yAxisGridLineWidthSet(@1)//y轴横向分割线宽度为0(即是隐藏分割线)
    .touchEventEnabledSet(YES)//支持用户点击事件
    .tooltipEnabledSet(YES)
    .xAxisLabelsEnabledSet(YES)//X轴是否显示文字
    .xAxisTickIntervalSet(@0)//x轴刻度点间隔数(设置每隔几个点显示一个 X轴的内容)
    .categoriesSet(xTitles)
    .xAxisLabelsFontSizeSet(@(kLYAutoWidthPixel_22px))
    .yAxisLabelsFontSizeSet(@(kLYAutoWidthPixel_22px))
    .xAxisLabelsFontColorSet(@"#8791AC")
    .yAxisLabelsFontColorSet(@"#8791AC")
    .seriesSet(@[
                 AAObject(AASeriesElement)
                 .dataSet(model.form_wave)
                 ]
               );
    AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
   
    AATooltip *tooltip = aaOptions.tooltip;
    tooltip
    .useHTMLSet(YES)
    .formatterSet(@AAJSFunc(function () {
        return 
        +  this.x
        + ' <br/>'
        +  this.y
        + ' </b> ';
    }))
    .valueDecimalsSet(@2)//设置取值精确到小数点后几位
    .backgroundColorSet(@"#0C1D4C")
    .borderColorSet(@"#0C1D4C")
    .styleSet((id)AAStyle.new
              .colorSet(@"#CDD2DC")
              .fontSizeSet(@"12px")
              );
    [_aaChartView aa_drawChartWithOptions:aaOptions];

**Comment by AllenYangShuang** [comment]
<img width="405" alt="image" src="https://user-images.githubusercontent.com/12180694/69488511-2fa5a900-0ea5-11ea-8e0b-a660f8befbf4.png">

**Comment by 1321353970** [comment]
我也遇见了，不过我把this.x前面的+号去掉，就能正常展示了，你可以试试
