### ISSUE TITLE
五边雷达图 polar chart，使用 categoriesSet 设置 x 轴坐标后会变成倒五边，如何处理？

### ISSUE THREAD

**Issue by JermeryLee** [AAChartModel/AAChartKit#789]

**Comment by JermeryLee** [comment]
`    AAOptions *options = [AAOptionsConstructor configureChartOptionsWithAAChartModel:
                          AAChartModel.new
                          .chartTypeSet(AAChartTypeLine)
                          .titleSet(@"")
                          .subtitleSet(@"")
//                          .categoriesSet(@[@"收益", @"抗风险", @"基金规模", @"基金经理", @"基金管理人"])
                          .markerRadiusSet(@0)
                          .polarSet(true)
                          .yAxisTickPositionsSet(@[@(0), @(20), @(40), @(60), @(80), @(100)])
                          .seriesSet(@[
                              AASeriesElement.new
                              .colorSet(@"#6666cc")
                              .dataSet(@[@([_profitS doubleValue]),
                                         @([_riskResistanceS doubleValue]),
                                         @([_scaleS doubleValue]),
                                         @([_fundManagerS doubleValue]),
                                         @([_fundOrgS doubleValue])])
                          ])];
    options.legend.enabled = false;
    options.tooltip.enabled = false;`
categoriesSet 注释掉就是正五边形。

**Comment by bigfingerSon** [comment]
同问

**Comment by JermeryLee** [comment]
> 同问
通过使劲儿的翻文档

在 AASeriesElement.h 中添加
`AAPropStatementAndPropSetFuncStatement(copy,   AASeriesElement, NSString *, pointPlacement)`
AASeriesElement.m 中添加
`AAPropSetFuncImplementation(AASeriesElement, NSString *, pointPlacement)`

设置 AASeriesElement 时
`.pointPlacementSet(@"on")`

然后就正了。

**Comment by AAChartModel** [comment]
重复问题, 问题已修复,参见已修复的相同问题 #301
