### ISSUE TITLE
检查出内存泄露

### ISSUE THREAD

**Issue by jiasongs** [AAChartModel/AAChartKit#793]
有内存泄露
<img width="842" alt="图片" src="https://user-images.githubusercontent.com/22904757/70675964-9d373f00-1cc5-11ea-9f07-7d09002151af.png">
`- (void)dealloc`方法不会被调用

**Comment by jiasongs** [comment]
我用工具没有检查出具体是哪个地方的内存泄露

**Comment by jiasongs** [comment]
![Uploading 图片.png…]()
此方法会引起内存泄露
解决方案：
![Uploading 图片.png…]()
AAWeakProxy有如下实现：
`@interface AAWeakProxy : NSProxy

@property (nonatomic, weak, readonly, nullable) id target;

- (nonnull instancetype)initWithTarget:(nonnull id)target;
+ (nonnull instancetype)proxyWithTarget:(nonnull id)target;

@end

@implementation AAWeakProxy

- (instancetype)initWithTarget:(id)target {
    _target = target;
    return self;
}

+ (instancetype)proxyWithTarget:(id)target {
    return [[AAWeakProxy alloc] initWithTarget:target];
}

- (id)forwardingTargetForSelector:(SEL)selector {
    return _target;
}

- (void)forwardInvocation:(NSInvocation *)invocation {
    void *null = NULL;
    [invocation setReturnValue:&null];
}

- (NSMethodSignature *)methodSignatureForSelector:(SEL)selector {
    return [NSObject instanceMethodSignatureForSelector:@selector(init)];
}

- (BOOL)respondsToSelector:(SEL)aSelector {
    return [_target respondsToSelector:aSelector];
}

- (BOOL)isEqual:(id)object {
    return [_target isEqual:object];
}

- (NSUInteger)hash {
    return [_target hash];
}

- (Class)superclass {
    return [_target superclass];
}

- (Class)class {
    return [_target class];
}

- (BOOL)isKindOfClass:(Class)aClass {
    return [_target isKindOfClass:aClass];
}

- (BOOL)isMemberOfClass:(Class)aClass {
    return [_target isMemberOfClass:aClass];
}

- (BOOL)conformsToProtocol:(Protocol *)aProtocol {
    return [_target conformsToProtocol:aProtocol];
}

- (BOOL)isProxy {
    return YES;
}

- (NSString *)description {
    return [_target description];
}

- (NSString *)debugDescription {
    return [_target debugDescription];
}

@end`

**Comment by jiasongs** [comment]
@AAChartModel

**Comment by AAChartModel** [comment]
AAWeakProxy 已在此次提交 https://github.com/AAChartModel/AAChartKit/commit/dafb7070ab8e9e06ca4f98ec54f01b03de185e48 中合并至 AAChartKit 的 master 中, 感谢指教.
