### ISSUE TITLE
how to set SeriesElement title color 

### ISSUE THREAD

**Issue by cui30366423** [AAChartModel/AAChartKit#798]
our application support light and dark mode 

SeriesElement title is always black color

how to set the title color in light mode?

**Comment by AAChartModel** [comment]
## AAChartModel  property `titleFontColor`

```objc
AAPropStatementAndPropSetFuncStatement(copy,   AAChartModel, NSString *, titleFontColor) //Title label font color

```

**Comment by cui30366423** [comment]
this does not work !     .titleFontColorSet(darkMode==APPModeDark? @"#ffffff":@"000000")  

![6931576842751_ pic](https://user-images.githubusercontent.com/7134534/71253229-47683400-2362-11ea-8ad9-4d3b339877ed.jpg)

still black...

**Comment by AAChartModel** [comment]
You mean the seriesElement `legend` title

Refer to:  https://github.com/AAChartModel/AAChartKit/issues/696#issuecomment-518964720

**Comment by AAChartModel** [comment]
## The key code 

```objc
  //设定图例项的CSS样式。只支持有关文本的CSS样式设定。
    /*默认是：{
     "color": "#333333",
     "cursor": "pointer",
     "fontSize": "12px",
     "fontWeight": "bold"
     }
     */
    aaOptions.legend
    .itemStyleSet(AAItemStyle.new
                  .colorSet(AAColor.whiteColor)//字体颜色
                  .fontSizeSet(@"13px")//字体大小
                  .fontWeightSet(AAChartFontWeightTypeThin)//字体为细体字
                  );
```

**Comment by cui30366423** [comment]
不太理解，难道要修改源代码，还是外部可以设定颜色

发自我的iPhone


------------------ Original ------------------

**Comment by AAChartModel** [comment]
AAChartView 有通过 AAChartModel 绘制图表的方法

```objc
/**
 Function of drawing chart view
 
 @param chartModel The instance object of chart model
 */
- (void)aa_drawChartWithChartModel:(AAChartModel *)chartModel;
```

AAChartView 同时也有通过 AAOptions 绘制图表的方法

```objc
/**
 Function of drawing chart view

 @param options The instance object of chart options
 */
- (void)aa_drawChartWithOptions:(AAOptions *)options;
```

**Comment by cui30366423** [comment]
使用option 哦。



发自我的iPhone


------------------ Original ------------------

**Comment by cui30366423** [comment]
希望改动不会很大



发自我的iPhone


------------------ Original ------------------

**Comment by AAChartModel** [comment]
两者的区别是 AAOptions 支持更多的属性配置.  

```objc
- (void)aa_drawChartWithChartModel:(AAChartModel *)chartModel {
    AAOptions *options = [AAOptionsConstructor configureChartOptionsWithAAChartModel:chartModel];
    [self aa_drawChartWithOptions:options];
}
```

通过这段代码可以看出,实际上`aa_drawChartWithChartModel `内部调用的是`aa_drawChartWithOptions `.

也就是说,你只要配置好 AAOptions 的

```objc
aaOptions.legend
    .itemStyleSet(AAItemStyle.new
                  .colorSet(AAColor.whiteColor)//字体颜色
                  .fontSizeSet(@"13px")//字体大小
                  .fontWeightSet(AAChartFontWeightTypeThin)//字体为细体字
                  );
```
这段属性即可. 不需要额外修改源码

**Comment by cui30366423** [comment]
明白了 却是不错



发自我的iPhone


------------------ Original ------------------
