### ISSUE TITLE
冒昧的问下，如果说我要修改Y轴的指标，比如说设置显示位置或者进行旋转等操作，就必须得修改您的js文件了？？？急等

### ISSUE THREAD

**Issue by ZFKK** [AAChartModel/AAChartKit#8]

**Comment by AAChartModel** [comment]
应该不需要,不过不太明白你的具体意思?

**Comment by ZFKK** [comment]
....纵坐标的指标，比如说产量，文字最好横着水平显示，框架里是竖着排版显示，另外就是位置最好在最上方，而不是在中间，这些细节的调整，我好像在封装里边没有看到
![qq20170419-105347](https://cloud.githubusercontent.com/assets/16482997/25161594/8efabf32-24ef-11e7-88bd-b66de58969c8.png)

**Comment by AAChartModel** [comment]
你的这个红色圈圈标注的部分其实算是副标题,对应的是  AAChartModel 当中的 subtitle, 不过我确实没有开放设置副标题位置的属性,有需要的话,明天之前我给你加上吧!(附:框架当中的纵轴中间的那个是单位,用来标注纵轴坐标的值的单位比如/美元,/摄氏度,/公顷,/万吨之类的)

**Comment by ZFKK** [comment]
对了，这种单位的位置，如果要调整的话，就是在js里边进行的吧？？？，另外位置的话是不是也得开放出来，不好意思，主要是js不懂，但是需要修改，麻烦了。

**Comment by ZFKK** [comment]
忘了感谢大牛了额，希望明天可以见到了哈

**Comment by AAChartModel** [comment]
许下的承诺,欠下的债(😅流汗)!

**Comment by AAChartModel** [comment]
朋友👬,AAChartKit 文件更新一下吧,现已为图表副标题添加了对齐属性,并且副标题修改为默认居左,详情请见 git 历史记录中的这一条:`Add align property for subtitle of chart`.

**Comment by ZFKK** [comment]
实际上，我的重点是那个单位的设置，可能你没看到我后一条回复，👀，哎

**Comment by ZFKK** [comment]
我自己改改看吧
