### ISSUE TITLE
请问大神3个问题

### ISSUE THREAD

**Issue by AllenYangShuang** [AAChartModel/AAChartKit#800]
1.如果使用的是填充样式，填充区域的颜色可否自定义？
2.升级新的版本后，Y轴的文字之前显示3行，现在只显示1行？
3.圆点的大小可否自定义？

**Comment by AllenYangShuang** [comment]
<img width="323" alt="image" src="https://user-images.githubusercontent.com/12180694/70895971-d1df2980-202a-11ea-8e41-9a8276b44212.png">
这是我的设计图

**Comment by AAChartModel** [comment]
>  1.如果使用的是填充样式，填充区域的颜色可否自定义？

参见:  https://github.com/AAChartModel/AAChartKit/issues/636

**Comment by AAChartModel** [comment]
> 2.升级新的版本后，Y轴的文字之前显示3行，现在只显示1行？

有可能是因为之前为了解决这个问题  https://github.com/AAChartModel/AAChartKit/issues/519

新增了属性


```objc
AAPropStatementAndPropSetFuncStatement(assign, AAYAxis, BOOL ,      startOnTick) //Whether to force the axis to start on a tick. Use this option with the minPadding option to control the axis start. 默认是：false.
AAPropStatementAndPropSetFuncStatement(assign, AAYAxis, BOOL ,      endOnTick) //是否强制将坐标轴结束于刻度线，可以通过本属性及 maxPadding 来控制坐标轴的结束位置。 默认是：false.
```
导致的问题.

`startOnTick`和`endOnTick`这两个属性默认是` false`,你可以改成 `true` 试试.

**Comment by AAChartModel** [comment]
>  3.圆点的大小可否自定义？

参见demo 中的示例代码

```objc
        case 5: _aaChartModel.markerRadius = switchView.on ? @0 : @5;

```

调整 AAChartModel 的`markerRadius`属性即可改变折线连接原点点的大小

**Comment by AllenYangShuang** [comment]
<img width="675" alt="image" src="https://user-images.githubusercontent.com/12180694/71430644-11330780-2708-11ea-8c00-55c5f258d067.png">
还有一个问题，就是箭头指向的那根分割线的宽度可以自定义吗？

**Comment by AAChartModel** [comment]
哪根线不是分割线,是 Y轴的轴线

```objc
AAPropSetFuncImplementation(AAYAxis, NSNumber *, lineWidth) //y轴线宽度
```

**Comment by AAChartModel** [comment]
Y轴轴线以上的那几根线是网格线

```objc
AAPropSetFuncImplementation(AAYAxis, NSNumber *, gridLineWidth) //Y轴网格线宽度

```
