### ISSUE TITLE
x 轴 动态改变值 是不是要用AAChartModel 设置  然后 刷新AAmodel 不能像数据一样刷新吗 aa_onlyRefreshTheChartDataWithChartModelSeries  有没有方法直接设置

### ISSUE THREAD

**Issue by LAnqxpp** [AAChartModel/AAChartKit#802]

**Comment by AAChartModel** [comment]
如果你说的是  https://www.highcharts.com.cn/demo/highstock/dynamic-update 这种图表水平动态滚动刷新数据, 你可以下载最新的 AAChartKit 的 demo 示例,因为我已在此次提交https://github.com/AAChartModel/AAChartKit/commit/a8923caeb05ac6c31b00394fe3f693188c95feda中新增了沿X轴动态滚动刷新图表数据的方法示例.

**Comment by AAChartModel** [comment]
参见 #803

**Comment by AAChartModel** [comment]
具体示例代码在 `ScrollingUpdateDataVC`这个视图控制器类中

**Comment by LAnqxpp** [comment]
楼主说滴 也是我后面需要的，我的意思是 我要更换X轴值  一月 二月  三月   通过点击后  周一 周二 周三

**Comment by AAChartModel** [comment]
参见问题  #808 

已为 AAChartView 添加了动态更新 categories 的方法.
```objc
/// Update the X axis categories of chart
/// @param categories the X axis categories array
- (void)aa_updateXAxisCategories:(NSArray *)categories;
```

**Comment by AAChartModel** [comment]
此方法能实现  

https://jshare.com.cn/highcharts/5JZ02l

这种在线图表的动态更新 X 轴 categories 效果
