### ISSUE TITLE
【有关于Legend的提问贴】

### ISSUE THREAD

**Issue by xfbxfb** [AAChartModel/AAChartKit#805]
![截屏2019-12-2015 59 50](https://user-images.githubusercontent.com/15652946/71239565-d3b62f00-2341-11ea-8e81-3cb165e01102.png)
问题1：UI设计要求更改legend显示为下方 对号 选中样式，请问老哥有对应方法吗？
问题2：点击1，2，3，4每个按钮对应的回调事件找了好久没找到？请问老哥可以提供下吗？

**Comment by AAChartModel** [comment]
😅暂时还未添加此两项功能. 不过你其实完全可以禁用 AAChartKit 的 legend,然后自己在 AAChartView 的视图下方,通过 UIButton 来自定义 legend.  这样的话,这两个问题也就完全都不是问题了

**Comment by xfbxfb** [comment]
哈哈好，非常感谢！其实是想看下legend的回调事件里面是怎么执行的哈哈哈
