### ISSUE TITLE
y轴的数据超过了图表的边界，这种问题应该怎么设置？

### ISSUE THREAD

**Issue by tandepeng** [AAChartModel/AAChartKit#807]
![WeChat924a5d78da001b0df78883732c82f339](https://user-images.githubusercontent.com/15227791/71330778-cb403d00-2569-11ea-9d3b-bab69c92e800.png)

做的双Y轴的图表，y轴显示的数据是自动生成的，但有的值确超出了边界。

问题2：有没有什么方法通过数据驱动着X轴的准星线自动滑动到指定数据？

**Comment by AAChartModel** [comment]
> 问题2：有没有什么方法通过数据驱动着X轴的准星线自动滑动到指定数据？

这个问题无解,参见官方 API,压根就没有提供接口
https://api.highcharts.com.cn/highcharts#xAxis.crosshair

**Comment by AAChartModel** [comment]
> y轴的数据超过了图表的边界，这种问题应该怎么设置?

在 AAChart.h 类文件中,有以下属性

```objc
AAPropStatementAndPropSetFuncStatement(strong, AAChart, NSArray     *, margin)//  图表外边缘和绘图区域之间的边距。 数组中的数字分别表示顶部，右侧，底部和左侧 ([👆,👉,👇,👈])。 也可以使用 marginTop，marginRight，marginBottom 和 marginLeft 来设置某一个方向的边距。
AAPropStatementAndPropSetFuncStatement(strong, AAChart, NSNumber    *, marginTop) //👆
AAPropStatementAndPropSetFuncStatement(strong, AAChart, NSNumber    *, marginRight) //👉
AAPropStatementAndPropSetFuncStatement(strong, AAChart, NSNumber    *, marginBottom) //👇
AAPropStatementAndPropSetFuncStatement(strong, AAChart, NSNumber    *, marginLeft) //👈
```

双 Y 轴的话, 应该只要调整一下 `marginLeft`和`marginRight`这两个属性值就可以了
