### ISSUE TITLE
大佬好，我是想更改X轴 底部值   

### ISSUE THREAD

**Issue by LAnqxpp** [AAChartModel/AAChartKit#809]
按日统计  x 轴  0 1 ....24  ，按周统计 x 轴 1 ...7  不是更改x轴 显示数据  类似于这样

**Comment by AAChartModel** [comment]
https://jshare.com.cn/highcharts/5JZ02l

难道不是这个在线示例的这种效果吗?

**Comment by LAnqxpp** [comment]
是的

**Comment by AAChartModel** [comment]
> 是的

这是歧义句啊

**Comment by LAnqxpp** [comment]
对，还有一个问题，因为x轴 分段不固定 导致无法给 数据默认为0；能实现根据 x轴分段 然后给个默认值 0的展示数据

**Comment by AAChartModel** [comment]
> 能实现根据 x轴分段 然后给个默认值 0的展示数据

<img width="516" alt="截屏2019-12-23下午6 29 17" src="https://user-images.githubusercontent.com/16357599/71352530-863ff900-25b1-11ea-8413-3e1118ee2599.png">

不知道你需要的是不是这种数值不连续的效果?

**Comment by LAnqxpp** [comment]
对

**Comment by LAnqxpp** [comment]
还有就是   pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'
我是不是 重新执行下pod  就可以更新代码了

**Comment by AAChartModel** [comment]
## 配置 AAChartModel

```objc
- (AAChartModel *)setUpDiscontinuousDataChart {
    return AAChartModel.new
    .chartTypeSet(AAChartTypeColumn)
    .yAxisTitleSet(@"")//设置Y轴标题
    .dataLabelsEnabledSet(true)//是否显示值
    .tooltipEnabledSet(true)
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"所有专业")
        .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2,[NSNull null],[NSNull null],[NSNull null],[NSNull null], @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6,])
        .colorSet((id)[AAGradientColor deepSeaColor])
    ]);
}
```

## 图形结果如下

![](https://user-images.githubusercontent.com/16357599/47836514-90b69680-dde3-11e8-9474-df6997dc0d56.png)
