### ISSUE TITLE
在模拟器上和真机上都不能显示图表

### ISSUE THREAD

**Issue by tangaowen** [AAChartModel/AAChartKit#81]
错误显示如下： 
```
-------> AAChartView.m [Line 172] 
💀💀💀WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______
Error Domain=WKErrorDomain Code=4 "发生 JavaScript 异常" 
UserInfo={WKJavaScriptExceptionLineNumber=1,
WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: loadTheHighChartView, 
WKJavaScriptExceptionSourceURL=about:blank, 
NSLocalizedDescription=发生 JavaScript 异常,
WKJavaScriptExceptionColumnNumber=21}
```

错误位置：
```objective-c
- (void)evaluateJavaScriptWithFunctionNameString:(NSString *)funcitonNameStr {
    if (AASYSTEM_VERSION >= 9.0) {
        [_wkWebView  evaluateJavaScript:funcitonNameStr completionHandler:^(id item, NSError * _Nullable error) {
            if (error) {
                AADetailLog(@"💀💀💀WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______%@",error);
            }
        }];
    } else {
        [_uiWebView  stringByEvaluatingJavaScriptFromString:funcitonNameStr];
    }
}
```

**Comment by AAChartModel** [comment]
可能你下载的是其中的某一个中间版本，可能中间有稍许问题，你下载最新版的demo运行看看，我现在身边没有电脑💻，实在不行，我回去再帮你看看(●◡●)ﾉ

**Comment by AAChartModel** [comment]
你也可以先看看swift版本的查看一下运行效果

**Comment by tangaowen** [comment]
我是通过 Clone Or Download 下载的， 刚试了下Demo ， Demo可以，但是我工程里面却提示这个错误。

我是在UIView的 init 方法里面 创建 AAChartView, 然后 收到一个事件后 ，去显示一个图标。 直接copy 你的例子里面的代码也不work， 不知道为何？ 跟调用时机有关吗？

**Comment by AAChartModel** [comment]
你的这个文件是什么时候下载的?可能是因为你下载的是之前的某一个无用的历史版本,又或者你不小心改动了我的源码,导致了无法调用`html` 文件中名为`loadTheHighChartView`的方法,你再讲可以正常工作的这个demo 中的`AAChartKit`文件重新添加到你的项目中试试.

**Comment by tangaowen** [comment]
刚测试的就是之前下载的demo， 没有重新下载， 现在项目中用的代码应该跟 demo中用的代码是同一份，没有修改过文件代码呀

**Comment by AAChartModel** [comment]
我记得我之前有在 `UITableView`的自定义 `cell` 里面使用过 `AAChartView`, 和你的使用方法一样,也是在 init 方法里创建的`AAChartView `,但是工作是正常的,并没有出现什么问题呢!

**Comment by AAChartModel** [comment]
难道是 AAChartView 找不到`AAChartView.html`的资源文件?
你确定你将`AAChartKit`中的 `AAJSFiles`文件夹正确的拖入到你的项目中了吗?

**Comment by tangaowen** [comment]
对的， 确定都添加了， 整个 AAChartKitLib 文件夹都拖入了。

**Comment by tangaowen** [comment]
网上搜了下 ， 大概意思好像是说 在错误的时机调用了 JS 文件， 导致调用失败。

**Comment by AAChartModel** [comment]
这样的话,你就和我在demo中做的一样,先在一个空白的 ViewController 里面的 ViewDidLoad 方法里面,将我的代码复制到你的项目中再测试下,这样就可以排除是不是你调用时机除了问题.

**Comment by AAChartModel** [comment]
注意使用的一定要是下面这个绘制图表的方法
```objective-c
[chartView aa_drawChartWithChartModel:chartModel]; 
```
在错误的时机调用了
```objective-c
[chartView aa_refreshChartWithChartModel:chartModel];
```
也会出现上面的那个报错

**Comment by tangaowen** [comment]
好的， 我按你说的试试。 谢谢。

**Comment by tangaowen** [comment]
在 Controller里面的ViewDidLoad里面调用是可以的，但是我在我自己重写的 UIView里面就有问题， 有点晚了，我明天再看看。应该是调用的哪里不太对。

**Comment by AAChartModel** [comment]
(⊙v⊙)嗯,找到了问题的原因就好

**Comment by tangaowen** [comment]
是因为我这边不是在init 里面设置的size， 而是 在layoutSubviews中设置的，如果在init里面设置就没有问题。 估计是您那边没有处理 size的 改变。

**Comment by tangaowen** [comment]
还在吗？ 确定如果不是在 创建 AAChartView的时候 设置frame 和 contentWidth 的 话， 都不work。 现在我需要根据数据的多少来设置ContentWidth, 但是实际上设置了后 横轴 宽度并没有变化。 我感觉跟 我 之前说的 一定要在 创建的时候设置 frame类似， 如果不在创建的时候设置frame, 就无法显示 曲线。

**Comment by tangaowen** [comment]
麻烦 查下哦， 不管是 frame还是 contentSize 只有在 AAChartView创建的时候指定才有效，一旦调用了刷新函数刷新了之后， 再去设置 frame跟 contentSize都不会改变显示的区域了。 @AAChartModel

**Comment by AAChartModel** [comment]
问题已解决,更多结果,参见 #83
