### ISSUE TITLE
浮窗中数值如何实现百分比格式化？如下图。

### ISSUE THREAD

**Issue by tipshot** [AAChartModel/AAChartKit#811]
![image](https://user-images.githubusercontent.com/18547353/71472303-71f83800-280d-11ea-8edd-9322ee047ef0.png)

**Comment by AAChartModel** [comment]
参见 https://github.com/AAChartModel/AAChartKit/issues/524#issuecomment-497241394

**Comment by tipshot** [comment]
很抱歉，我看了，也找了demo，没有发现如何实现。我给的原始数据都是不超过1的小数，如何使得变为百分数？劳烦给看一下，，，非常感谢，，

**Comment by AAChartModel** [comment]
你把你的代码贴一下(别截图)

**Comment by tipshot** [comment]
自己去查了一下highCharts的官方文档，找到了解决方法。如下图：
![image](https://user-images.githubusercontent.com/18547353/71565636-8b3e0480-2aeb-11ea-9781-7186ec65f9f8.png)
代码是：
//浮窗
    NSString * str;
    if (self.index == 3) {
        str = @"{{point.x}:{point.y}米";
    }else{
        str = @"{{point.x}:{point.percentage:.0f}%占比";
    }
    AATooltip *aaTooltip = AATooltip.new
    .enabledSet(true)
    .headerFormatSet(@"{series.name}")
    .pointFormatSet(str);
实现效果如下：
![image](https://user-images.githubusercontent.com/18547353/71565658-e5d76080-2aeb-11ea-9dff-1c3a893862e6.png)

但是浮窗不显示X轴上的姓名数据了。怎么回事呢？

**Comment by AAChartModel** [comment]
https://api.highcharts.com.cn/highcharts#Point.category

> category  
对于分类坐标轴，这个属性是数据点的分类名称，对于其他类型的坐标轴，这个属性是数据点的 X值。

所以你这里估计要改成

```objc
    NSString * str;
    if (self.index == 3) {
        str = @"{{point.category}:{point.y}米";
    }else{
        str = @"{{point.category}:{point.percentage:.0f}%占比";
    }
```

**Comment by tipshot** [comment]
这个point .category并没有起到任何作用。和point.x设置结果是一样的。

**Comment by AAChartModel** [comment]
把你的完整的 AAOptions 配置代码贴一下看看

**Comment by tipshot** [comment]
//图表数据
- (AAOptions *)drawChartsByOptions {
    
    AAChart *aaChart = AAChart.new.typeSet(AAChartTypeColumn);
    AATitle *aaTitle = AATitle.new.textSet(@"").ySet(@10).styleSet(AAStyle.new.colorSet(@"#ffffff").fontSizeSet(@"15"));
    AASubtitle *aaSubtitle = AASubtitle.new
    .textSet(@" ")
    .alignSet(AAChartTitleAlignTypeLeft)
    .styleSet(AAStyle.new.colorSet(HLChartLineColorStr))
    ;
    
    //X轴
    AALabels *xlabels = AALabels.new
    .enabledSet(true)//设置X轴是否显示数字
    .styleSet(AAStyle.new
              .colorSet(@"#ffffff")//yAxis Label font color
              .fontSizeSet(@"12px")//yAxis Label font size
              .fontWeightSet(AAChartFontWeightTypeRegular)//yAxis Label font weight
              );
    
    HLXAxis *aaXAxis = HLXAxis.new;
    aaXAxis
    .tickWidthSet(@0)
    .startOnTickSet(true)
    .lineWidthSet(@1)
    .lineColorSet(HLChartLineColorStr)
    .minSet(@0)
    .labelsSet(xlabels)
    .visibleSet(true)
    .categoriesSet(self.names);
    
    
    //Y轴
    AALabels *Ylabels = AALabels.new
    .enabledSet(true)
    .formatSet(self.chartIsPercent?@"{value}%":@"{value}")
    .styleSet(AAStyle.new
              .colorSet(@"#ffffff")//yAxis Label font color
              .fontSizeSet(@"13px")//yAxis Label font size
              .fontWeightSet(AAChartFontWeightTypeRegular)//yAxis Label font weight
              );
    
    
    HLYAxis *aaYAXis = HLYAxis.new;
    aaYAXis
    .visibleSet(true)
    .lineWidthSet(@1)
    .lineColorSet(HLChartLineColorStr)
    .gridLineWidthSet(@0)
    .gridLineColorSet(HLChartLineColorStr)
    .titleSet(AAAxisTitle.new.textSet(@" "))
    .tickWidthSet(@2)
    .tickPositionSet(@"inside")
    .tickLengthSet(@10)
    .labelsSet(Ylabels);
    
    
    NSArray * aaYaxisArray = @[aaYAXis];
    
    //浮窗
    NSString * str;
    if (self.index == 3) {
        str = @"{{point.category}:{point.y}米";
    }else{
        str = @"{{point.category}:{point.percentage:.0f}%占比";
    }
    AATooltip *aaTooltip = AATooltip.new
    .enabledSet(true)
    .headerFormatSet(@"{series.name}")
    .pointFormatSet(str);
    
    //图例
    AAItemStyle * itemStyle = AAObject(AAItemStyle)
    .colorSet(@"#ffffff")
    .cursorSet(@"#000000")
    ;
    AALegend *aaLegend = AALegend.new
    .enabledSet(true)//是否显示图例。如果不显示，下面的设置就没用。
    .alignSet(AALegendAlignTypeLeft)
    .layoutSet(AALegendLayoutTypeHorizontal)
    .verticalAlignSet(AALegendVerticalAlignTypeTop)
    .xSet(@-0.0)
    .ySet(@-20.0)
    .symbolRadiusSet(@0)
    .itemMarginBottomSet(@40)
    .itemStyleSet(itemStyle)
    ;
    
    AAPlotOptions * plotOptions = AAPlotOptions.new
    .seriesSet(AASeries.new
               .animationSet(AAAnimation.new
                             .easingSet(AAChartAnimationBounce)
                             .durationSet(@1000)
                             )
               )
    .columnSet(AAColumn.new
               .stackingSet(self.chartIsPercent?AAChartStackingTypePercent:AAChartStackingTypeNormal)//是否百分比展示？
               .dataLabelsSet(AADataLabels.new.enabledSet(false))
               );
    
    
    NSArray * colors;
    if (self.index == 1) {
        colors = @[@"#8ff1d2",@"#9cd240",@"#f3db61",@"#f09841",@"#ed6346",@"#bc2c45"];
    }else if (self.index == 2){
        colors = @[@"#8ff1d2",@"#9cd240",@"#f09841",@"#bc2c45"];
    }else if (self.index == 3){
        colors = @[@"#8ff1d2",@"#9cd240",@"#f09841",@"#bc2c45"];
    }
    
    NSMutableArray * series = [NSMutableArray array];
    for (NSInteger i = 0; i < self.chartSeriesArray.count; i ++) {
        NSArray * dataArray = self.chartSeriesArray[i];
        AASeriesElement * elment = AASeriesElement.new
        .typeSet(AAChartTypeColumn)
        .nameSet(HLLanguage(self.chartLegentArray[i]))
        .markerSet(AAMarker.new.radiusSet(@0))
        .borderWidthSet(@0)
        .dataSet(dataArray);
        [series addObject:elment];
    }
    
    AAOptions *aaOptions = AAOptions.new;
    aaOptions.chart = aaChart;
    aaOptions.title = aaTitle;
    aaOptions.subtitle = aaSubtitle;
    aaOptions.xAxis = aaXAxis;
    aaOptions.yAxis = (id)aaYaxisArray;
    aaOptions.tooltip = aaTooltip;
    aaOptions.legend = aaLegend;
    aaOptions.series = series;
    aaOptions.colors = colors;
    aaOptions.plotOptions = plotOptions;
    return aaOptions;
}
