### ISSUE TITLE
大神，请问一下柱状图顶部显示的数字如何放到柱状图里面？图标底部的文字如何更换位置？如下图：

### ISSUE THREAD

**Issue by MiaoMiaoai** [AAChartModel/AAChartKit#812]
![WeChat9bd8c179c6802300f569a8f56d252913](https://user-images.githubusercontent.com/19339100/71512573-d250ad80-28d1-11ea-846e-250110a5920d.png)

1.我想把图表下面的“成功占比”放在“失败占比”前面，并且使“成功占比”的柱状图在“失败占比”柱状图下面

2.柱状图上显示的数据如何放到图里面，而不是顶部？
![WeChata89fa0b22603896e54b1619eb5fd9185](https://user-images.githubusercontent.com/19339100/71512771-95d18180-28d2-11ea-88fd-11eb45ca7804.png)

**Comment by tipshot** [comment]
设置series的时候调整一下顺序就可以了。

**Comment by MiaoMiaoai** [comment]
@tipshot series顺序调完，柱形图上下部分也对调过来了。我想只改变底下两个位置，把成功占比调到前面，而在柱形图上面，成功占比放在下面。

**Comment by tipshot** [comment]
是的，如果你也想这样调整的话，我也遇到了同样的问题，同问！ @AAChartModel

**Comment by AAChartModel** [comment]
> 1.我想把图表下面的“成功占比”放在“失败占比”前面，并且使“成功占比”的柱状图在“失败占比”柱状图下面
1* 调整 Series 顺序
2* 同时设置 AAChartModel 的 yAxisReversed 属性为 true

**Comment by AAChartModel** [comment]
> 2.柱状图上显示的数据如何放到图里面，而不是顶部？

```objc
 AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
    
 aaOptions.plotOptions.column.dataLabels.inside = true;
```

**Comment by tipshot** [comment]
> > 1.我想把图表下面的“成功占比”放在“失败占比”前面，并且使“成功占比”的柱状图在“失败占比”柱状图下面
> 
> 1. 调整 Series 顺序
> 2. 同时设置 AAChartModel 的 yAxisReversed 属性为 true

“同时设置 AAChartModel 的 yAxisReversed 属性为 true”这个只能通过 AAChartModel进行设置么？option如何进行设置？

**Comment by AAChartModel** [comment]
@tipshot 你的 AAOptions 不是通过

```objc
    AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];

```
得到的吗? 完全是由自己配置的 AAOptions?

**Comment by tipshot** [comment]
明白了，我的几十个图表都是完全自己配置AAOptions，只有一个是用的model。这样的话就明白了。

**Comment by AAChartModel** [comment]
> 我的几十个图表都是完全自己配置AAOptions

这样挺好,自由度更高,AAChartModel 只是一个配置 AAOptions 的快捷方式而已.效率不及完全自己配置
