### ISSUE TITLE
使用model创建图表，如何设置X轴和Y轴轴线宽度？

### ISSUE THREAD

**Issue by tipshot** [AAChartModel/AAChartKit#813]
在里面没有找到设置轴线宽度的属性。不知是否可以设置，如果可以，如何设置？

**Comment by AAChartModel** [comment]
`yAxisLineWidth` 用于设置 Y 轴网格线
```objc
AAPropStatementAndPropSetFuncStatement(strong, AAChartModel, NSNumber *, yAxisLineWidth) //y y-axis line width
```

**Comment by AAChartModel** [comment]
AAChartModel 没有X轴轴线宽度属性.  为了避免 AAChartModel 过度膨胀,不常用的属性都没有添加到 AAChartModel 中,可通过 AAOptions 来设置

**Comment by tipshot** [comment]
在柱状图中，轴线会遮挡柱状图底部，哪怕吧轴线宽度设置为0或者设置隐藏轴线依然会遮挡。请问有什么解决办法么？
![image](https://user-images.githubusercontent.com/18547353/71611658-a9802f00-2bd5-11ea-8dc8-9b66d26b05bb.png)

**Comment by AAChartModel** [comment]
把你的 AAOptions 配置代码贴一下看看

**Comment by tipshot** [comment]
![image](https://user-images.githubusercontent.com/18547353/71612279-4ba21600-2bda-11ea-995d-34860a5f2467.png)

- (AAOptions *)getOptions:(AAChartModel*)model{
    AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:model];
    AAXAxis * xAxis = AAXAxis.new
    .reversedSet(true)
    .gridLineWidthSet(@0)
    .lineWidthSet(@0);
    
    AAYAxis * yAxis = AAYAxis.new
    .reversedSet(false)
    .gridLineWidthSet(@0)
    .lineWidthSet(@0);

    aaOptions.xAxis = xAxis;
    aaOptions.yAxis = yAxis;
    return aaOptions;
}



//左边多彩柱形图
- (AAChartModel *)drawLeftChartViewTwoWithModel{
    
    AAChartModel *aaChartModel = AAChartModel.new
    .chartTypeSet(AAChartTypeColumn)
    .titleSet(@" ")
    .subtitleSet(@" ")
    .subtitleFontSizeSet(@14)
    .subtitleFontColorSet(@"#ffffff")
    .colorsThemeSet(@[@"#146fcc"])
    //    .gradientColorsThemeEnabledSet(true)
    .invertedSet(true)//x轴是否垂直
    .xAxisReversedSet(true)//x轴翻转
    .yAxisReversedSet(true)//Y轴翻转
    .xAxisVisibleSet(true)//X轴是否显示
    .yAxisVisibleSet(false)//Y轴是否显示
    .legendEnabledSet(false)//是否显示图例
    .tooltipEnabledSet(false)
    .borderRadiusSet(@10)
    .yAxisMaxSet(@1)
    .xAxisCrosshairWidthSet(@1)//准星线宽度为1
    .xAxisCrosshairColorSet(@"rgba(0,0,0,0)")//准星线背景色为透明色
    //    .dataLabelEnabledSet(true)//是否显示数据
    .seriesSet(@[AASeriesElement.new
                 .nameSet(@"ElementOne")
                 .dataSet(self.team1Data)
                 .colorByPointSet((id)@(true)),//When using automatic point colors pulled from the options.colors collection, this option determines whether the chart should receive one color per series or one color per point. Default Value：false.
                 ]
               );
    
    return aaChartModel;
}

**Comment by tipshot** [comment]
代码截图和代码都发给你了，方便你观看和复制。

**Comment by AAChartModel** [comment]
## 配置 AAOptions

```objc
- (AAOptions *)customAAOptions {
    return AAOptions.new
    .titleSet(AATitle.new
              .textSet(@""))
    .xAxisSet(AAXAxis.new
              .lineWidthSet(@0))
    .yAxisSet(AAYAxis.new
              .visibleSet(false))
    .colorsSet(@[@"#146fcc"])
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"ElementOne")
        .typeSet(AAChartTypeBar)
        .borderRadiusSet(@10)
        .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6])]);
}

```
![](https://user-images.githubusercontent.com/16357599/71615605-f9b6bb80-2bec-11ea-912f-205a6a4f4165.png)

**Comment by AAChartModel** [comment]
# 几点建议

## 1. 你的配置 AAOptions 代码太啰嗦了,有很多不必要的冗余内容

* 例如你在 AAChartModel 中设置了一堆关于 X轴和 Y轴的相关属性之后,

```objc
.xAxisReversedSet(true)//x轴翻转
.yAxisReversedSet(true)//Y轴翻转
.xAxisVisibleSet(true)//X轴是否显示
.yAxisVisibleSet(false)//Y轴是否显示
```

又在AAChartModel 转换为 AAOptions 的代码中重新创建了 AAXAxis 和 AAYAxis,这样之前的属性配置就有被完全覆盖了,变得毫无意义.

所以你的AAChartModel 转换为 AAOptions 这部分代码

```objc
(AAOptions )getOptions:(AAChartModel)model{
AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:model];
AAXAxis * xAxis = AAXAxis.new
.reversedSet(true)
.gridLineWidthSet(@0)
.lineWidthSet(@0);

AAYAxis * yAxis = AAYAxis.new
.reversedSet(false)
.gridLineWidthSet(@0)
.lineWidthSet(@0);

aaOptions.xAxis = xAxis;
aaOptions.yAxis = yAxis;
return aaOptions;
}
```

应改为

```objc
- (AAOptions *)getOptions:(AAChartModel*)model {
    AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:model];
    aaOptions.xAxis
    .minSet(@-0.5)
    .reversedSet(true)
    .gridLineWidthSet(@0)
    .lineWidthSet(@0);

    aaOptions.yAxis
    .reversedSet(false)
    .gridLineWidthSet(@0)
    .lineWidthSet(@0);

    return aaOptions;
}
```

* 既然你想要的是条形图,就应该直接设置图表类型为 `AAChartTypeBar`,而不是将图表设置为 `AAChartTypeColumn`,然后经过各种反转变换最终又在再将 `AAChartTypeColumn` 转变为 `AAChartTypeBar`,这些步骤显然是多余的

* 单色柱状图条形图的`colorByPointSet`没有必要设置

## 2. GitHub 的 issues 评论支持 Markdown

粘贴代码文本时,可使用 Markdown 中的代码高亮功能

`  
```
(```)objc

(```)
```
> 注：为了防止转译，前后三个反引号处加了小括号，实际是没有的。这里只是用来演示，实际中去掉两边小括号即可。

直接对 `objc`代码进行格式化高亮. 支持 swift 或者是 java 、kotlin以此类推.


markdown 语法相关内容, 参见 https://www.jianshu.com/p/191d1e21f7ed

**Comment by tipshot** [comment]
非常感谢，这一块我会好好看看的。。
