### ISSUE TITLE
折线图 数据 0.7  展示出来0.700000000003

### ISSUE THREAD

**Issue by weeKendIce** [AAChartModel/AAChartKit#815]
这个问题该如何解决，就只展示0.7

**Comment by AAChartModel** [comment]
是 Y轴的数据还是 DataLabels 的数据?给个图表效果截图看看

**Comment by weeKendIce** [comment]
![Uploading IMG_0792.PNG…]()
dataLabels的数据~  整数型没问题

**Comment by weeKendIce** [comment]
![Uploading IMG_0792.PNG…]()

**Comment by weeKendIce** [comment]
> 是 Y轴的数据还是 DataLabels 的数据?给个图表效果截图看看
![IMG_0792](https://user-images.githubusercontent.com/19883762/71608951-95313780-2bbf-11ea-83a6-88aa087a2783.PNG)

**Comment by tipshot** [comment]
这是系统在处理json解析的时候遇到特定的数会出现精度丢失的问题。需要你自己处理一下就可以了。

**Comment by weeKendIce** [comment]
> 这是系统在处理json解析的时候遇到特定的数会出现精度丢失的问题。需要你自己处理一下就可以了。建议使用NSDecimalNumber处理。
感谢大佬 已解决~
