### ISSUE TITLE
请确认： 简体中文文档中关于支持iOS版本的描述

### ISSUE THREAD

**Issue by iostang** [AAChartModel/AAChartKit#818]
该项目英文文档和繁体中文都是说支持iOS6+ 
但是简体中文文档写的是iOS9+ 应该是写错了吧？
我没有低版本的测试机来验证，不知道有没有人试过该库是否支持iOS9以下？

**Comment by AAChartModel** [comment]
目前最新的 代码准确来说是最低支持到 iOS 8, 目前英文文档无此描述,繁体中文文档未及时更新,后面更新一下文档.

**Comment by AAChartModel** [comment]
连淘宝等这种亿级用户量的 App 最低支持都是 iOS9 了,更低版本的支持应该已无必要了吧

**Comment by iostang** [comment]
> 最低支持都是iOS9了，一系列版本的支持应该已无必要了吧

😁😁😁从开发者的角度来说 我当然是想直接支持iOS9及以上，但是如果要取消iOS8的支持需要说服产品，还要走流程申请。。。比较麻烦

**Comment by AAChartModel** [comment]
参见 https://github.com/AAChartModel/AAChartKit/issues/737

**Comment by AAChartModel** [comment]
> PS: 考虑到连淘宝、支付宝、微信、微博,这些个亿万级用户的国民APP,最低兼容系统版本号都是iOS 9 +,我有点怀疑这个功能的实际价值😂😂😂

看来这个功能还真的有价值啊🙂
