### ISSUE TITLE
请问AAChartTypeSpline 这个类型的时候图例能设置成圆形的吗?

### ISSUE THREAD

**Issue by LeonardoYanJun** [AAChartModel/AAChartKit#819]

**Comment by AAChartModel** [comment]
![image](https://user-images.githubusercontent.com/16357599/75210156-4cf75580-57bb-11ea-9d91-9ab65b1028e7.png)


AAChartTypeSpline he AAChartTypeAreaspline 类型图表的图例默认就是圆形,不用单独设置.
