### ISSUE TITLE
柱形图X轴的各标题能不能不是斜的, 设置成竖的或者横的该怎么设置呢?求解

### ISSUE THREAD

**Issue by imbawales** [AAChartModel/AAChartKit#82]
![image](https://user-images.githubusercontent.com/24821783/33648097-38cd0052-da93-11e7-8e64-003065258218.png)

**Comment by AAChartModel** [comment]
现已为 AAChartModel 添加设置 X轴坐标点间隔的新属性
```objective
AAPropStatementAndFuncStatement(strong, AAChartModel, NSNumber *, xAxisTickInterval);//x轴刻度点间隔数(设置每隔几个点显示一个 X轴的内容)
```
适当设置X轴坐标点间隔数,释放足够的显示空间, X轴标题文字将自动水平显示

**Comment by guuuJIe** [comment]
设置之后 x轴数据丢失

**Comment by AAChartModel** [comment]
> 设置之后 x轴数据丢失

需要设置足够的间隙，或者同时调整字体大小，否则文字的展示空间不够，就会自动隐藏
