### ISSUE TITLE
Data Refresh Issue when we change orientation from landscape to protrait

### ISSUE THREAD

**Issue by juneadiosdeveloper** [AAChartModel/AAChartKit#824]
when i am in portrait mode . everything works fine. but when i am changing my device orientation from landscape to portrait . it stop refreshing.  I have used everything but failed to refresh my code after device orientation is backed to portrait from landscape.Even data is filled in array but its not refreshed only old data is seen. It means in array we have new data but due to chart is not refreshed  i can not see new data.I have used AAChartView

**Comment by AAChartModel** [comment]
refer to the same issue  #915.

**Comment by AAChartModel** [comment]
## Key content

```objc

/// Set the chart view content be adaptive to screen rotation
- (void)aa_adaptiveScreenRotation;

/// Set the chart view content be adaptive to screen rotation with custom animation effect
/// Refer to https://api.highcharts.com.cn/highcharts#Chart.setSize
///
/// @param animation The instance object of AAAnimation
- (void)aa_adaptiveScreenRotationWithAnimation:(AAAnimation *)animation;
```

**Comment by AAChartModel** [comment]
```ruby
pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'

```

Update the AAChartKit to the latest content and then you can use the new method of AAChartView
