### ISSUE TITLE
可不可以调整series属性文字内容的位置 放在图标顶部而不是图标的下面

### ISSUE THREAD

**Issue by ZeroJson** [AAChartModel/AAChartKit#828]

**Comment by ZeroJson** [comment]
我想把series属性文本控件放置在图表的顶部,一直没找到

**Comment by ZeroJson** [comment]
我的是柱状图类型的图标

**Comment by AAChartModel** [comment]
重复问题, 参见 https://github.com/AAChartModel/AAChartKit/issues/473

**Comment by ZeroJson** [comment]
好的，感谢------------------ 原始邮件 ------------------
发件人: "An An"<notifications@github.com>
发送时间: 2020年1月9日(星期四) 晚上6:25
收件人: "AAChartModel/AAChartKit"<AAChartKit@noreply.github.com>;
抄送: "ZeroJson"<1165889915@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AAChartModel/AAChartKit] 可不可以调整series属性文字内容的位置 放在图标顶部而不是图标的下面 (#828)



重复问题, 参见 #473
 
&mdash;

**Comment by ZeroJson** [comment]
AALegendAlignTypeLeft这个为声明的 让我用AAChartAlignTypeLeft 是吗

**Comment by AAChartModel** [comment]
## 配置 AAOptions

```objc
 AAChartModel *aaChartModel= AAChartModel.new
    .chartTypeSet(AAChartTypeAreaspline)
    .titleSet(@"")
    .subtitleSet(@"")
    .stackingSet(AAChartStackingTypeNormal)
    .markerRadiusSet(@0)
    .colorsThemeSet(@[
        AAGradientColor.oceanBlueColor,
        AAGradientColor.sanguineColor,
        AAGradientColor.lusciousLimeColor,
        AAGradientColor.mysticMauveColor
    ])
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"Tokyo Hot")
        .dataSet(@[@0.45, @0.43, @0.50, @0.55, @0.58, @0.62, @0.83, @0.39, @0.56, @0.67, @0.50, @0.34, @0.50, @0.67, @0.58, @0.29, @0.46, @0.23, @0.47, @0.46, @0.38, @0.56, @0.48, @0.36]),
        AASeriesElement.new
        .nameSet(@"Berlin Hot")
        .dataSet(@[@0.38, @0.31, @0.32, @0.32, @0.64, @0.66, @0.86, @0.47, @0.52, @0.75, @0.52, @0.56, @0.54, @0.60, @0.46, @0.63, @0.54, @0.51, @0.58, @0.64, @0.60, @0.45, @0.36, @0.67]),
        AASeriesElement.new
        .nameSet(@"London Hot")
        .dataSet(@[@0.46, @0.32, @0.53, @0.58, @0.86, @0.68, @0.85, @0.73, @0.69, @0.71, @0.91, @0.74, @0.60, @0.50, @0.39, @0.67, @0.55, @0.49, @0.65, @0.45, @0.64, @0.47, @0.63, @0.64]),
        AASeriesElement.new
        .nameSet(@"NewYork Hot")
        .dataSet(@[@0.60, @0.51, @0.52, @0.53, @0.64, @0.84, @0.65, @0.68, @0.63, @0.47, @0.72, @0.60, @0.65, @0.74, @0.66, @0.65, @0.71, @0.59, @0.65, @0.77, @0.52, @0.53, @0.58, @0.53]),
    ]);
    
    AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
    
    aaOptions.legend
    .enabledSet(true)
    .alignSet(AAChartAlignTypeCenter)
    .layoutSet(AAChartLayoutTypeHorizontal)
    .verticalAlignSet(AAChartVerticalAlignTypeTop);
    
    aaOptions.yAxis.labels.format = @"{value} %";//给y轴添加单位
```

## 图表结果
![image](https://user-images.githubusercontent.com/16357599/72120514-3031ca80-3393-11ea-83ea-8f357583049c.png)

**Comment by AAChartModel** [comment]
## 代码解释

```objc
    aaOptions.legend
    .enabledSet(true)
    .alignSet(AAChartAlignTypeCenter)//设置图例位于水平方向上的正中间
    .layoutSet(AAChartLayoutTypeHorizontal)//设置图例排列方式为水平方向一字排开
    .verticalAlignSet(AAChartVerticalAlignTypeTop);//设置图例位于竖直方向上的顶部
```

 目前来看,其实你应该只需要设置`verticalAlign`这一个属性为`AAChartVerticalAlignTypeTop`就行了.
 也就是

 ```objc
    aaOptions.legend
    .verticalAlignSet(AAChartVerticalAlignTypeTop);//设置图例位于竖直方向上的顶部
```
即可

**Comment by ZeroJson** [comment]
谢谢 对我帮助很大------------------ 原始邮件 ------------------
发件人: "An An"<notifications@github.com>
发送时间: 2020年1月10日(星期五) 上午10:28
收件人: "AAChartModel/AAChartKit"<AAChartKit@noreply.github.com>;
抄送: "ZeroJson"<1165889915@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AAChartModel/AAChartKit] 可不可以调整series属性文字内容的位置 放在图标顶部而不是图标的下面 (#828)



代码解释
     aaOptions.legend     .enabledSet(true)     .alignSet(AAChartAlignTypeCenter)//设置图例位于水平方向上的正中间     .layoutSet(AAChartLayoutTypeHorizontal)//设置图例排列方式为水平方向一字排开     .verticalAlignSet(AAChartVerticalAlignTypeTop);//设置图例位于竖直方向上的顶部
 
目前来看,其实你应该只需要设置verticalAlign这一个属性为AAChartVerticalAlignTypeTop就行了.
 也就是
    aaOptions.legend    .verticalAlignSet(AAChartVerticalAlignTypeTop);//设置图例位于竖直方向上的顶部
 
即可
 
&mdash;

**Comment by ZeroJson** [comment]
还想麻烦大佬指点一下,图例的间距怎么设置?

**Comment by ZeroJson** [comment]
AAPropSetFuncImplementation(AALegend, NSNumber    *, symbolHeight)//标志高度

**Comment by ZeroJson** [comment]
找到了 应该是这个AAPropSetFuncImplementation(AALegend, NSNumber    *, itemMarginTop)
