### ISSUE TITLE
点击事件代理问题，求教！！！

### ISSUE THREAD

**Issue by superlu88** [AAChartModel/AAChartKit#829]
<img width="1" alt="屏幕快照 2020-01-09 15 07 07" src="https://user-images.githubusercontent.com/42953479/72121286-93bcf780-3395-11ea-9710-770e8d10a31d.png">

我现在通过点击事件来显示自己的提示框
所以我把自带的提示框关闭
aaChartModel.tooltipEnabledSet(NO) //是否显示浮动提示框(默认显示)

```objc
#pragma mark -- AAChartView delegate
- (void)aaChartView:(AAChartView *)aaChartView moveOverEventWithMessage:(AAMoveOverEventMessageModel *)message
```

但是添加了之后发现这个柱状图，必须点击这个对应的柱状才能触发点击事件，点上面的空白区域不触发，我显示的柱状小的时候很难点击触发，希望能提供一个解决方案，谢谢，急求！！！

**Comment by superlu88** [comment]
<img width="1" alt="屏幕快照 2020-01-09 15 07 07" src="https://user-images.githubusercontent.com/42953479/72121656-b3085480-3396-11ea-9a9b-cfea262cadf7.png">

**Comment by AAChartModel** [comment]
特殊自定义 tooltip 问题已在  #826 中解决.

**Comment by AAChartModel** [comment]
> <img alt="屏幕快照 2020-01-09 15 07 07" width="1" src="https://user-images.githubusercontent.com/42953479/72121286-93bcf780-3395-11ea-9710-770e8d10a31d.png">
> 
> 我现在通过点击事件来显示自己的提示框
> 所以我把自带的提示框关闭
> aaChartModel.tooltipEnabledSet(NO) //是否显示浮动提示框(默认显示)
> 
> ```objc
> #pragma mark -- AAChartView delegate
> - (void)aaChartView:(AAChartView *)aaChartView moveOverEventWithMessage:(AAMoveOverEventMessageModel *)message
> ```
> 
> 但是添加了之后发现这个柱状图，必须点击这个对应的柱状才能触发点击事件，点上面的空白区域不触发，我显示的柱状小的时候很难点击触发，希望能提供一个解决方案，谢谢，急求！！！

问题已解决,参见 https://github.com/AAChartModel/AAChartKit/issues/826#issuecomment-657490856

详细内容参见 AAChartKit 中的 Demo 示例
