### ISSUE TITLE
你好，请问怎么隐藏X轴刻度

### ISSUE THREAD

**Issue by xiaopeng11** [AAChartModel/AAChartKit#836]
你好，请问怎么隐藏X轴刻度

**Comment by AAChartModel** [comment]
同一个问题,你提两遍干嘛?  #825

**Comment by xiaopeng11** [comment]
抱歉，没找到我提问题的历史记录，请见谅，需要我删除吗😥------------------ 原始邮件 ------------------
发件人: "An An"<notifications@github.com>
发送时间: 2020年1月16日(星期四) 下午5:03
收件人: "AAChartModel/AAChartKit"<AAChartKit@noreply.github.com>;
抄送: "xiaopeng11"<1056400612@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AAChartModel/AAChartKit] 你好，请问怎么隐藏X轴刻度 (#836)



同一个问题,你提两遍干嘛?  #825
 
&mdash;

**Comment by AAChartModel** [comment]
没事,我已经关闭了
