### ISSUE TITLE
显示提示语有一个下角标（0，1，2，3，4等）请问下怎么隐藏谢谢

### ISSUE THREAD

**Issue by zhouhaokefd** [AAChartModel/AAChartKit#837]
显示提示语categories这个属性没有设置后出现啦点击的index下角标 如何隐藏呢。。。谢谢
![72492118-11ca4400-3857-11ea-8836-64665efe9539](https://user-images.githubusercontent.com/9410346/72596134-54b71500-3946-11ea-92c9-380f0fcd8502.png)

**Comment by AAChartModel** [comment]
```objc
    aaOptions.tooltip
     .headerFormatSet(@"") //设置 tooltip 的头部内容为空字符串
```

设置 tooltip 的头部内容为空字符串即可隐藏 tooltip 浮动提示框的默认头部内容
