### ISSUE TITLE
写的真的不很错！有个问题想问一下，能不能监听到：点击x轴的某一列时，和滑动停止时的某一列时，对应的x轴坐标或下标。

### ISSUE THREAD

**Issue by weiweilong** [AAChartModel/AAChartKit#84]
写的真的不很错！有个问题想问一下，能不能监听到：点击x轴的某一列时，和滑动停止时的某一列时，对应的x轴坐标或下标。看到有其他很多用户也提过这个，作者能开放这个就很完美了~~

**Comment by AAChartModel** [comment]
感谢您的反馈，之前我尝试过添加图表的点击事件回调功能，结果发现总是无法正确的获得点击事件，经测试发现`Highcharts`(如 `README` 中所言,`AAChartKit` 是基于流行的前端图表库 `Highcharts`封装的)在 iOS 中有 bug,在 `Android` 中测试测试则是正常的, 这个我是真的搞不定了,后面有机会像 `Highcharts` 官方提 `issue` 吧,眼下真的是无能为力了.😢

**Comment by AAChartModel** [comment]
如果对于获得图表的用户点击事件功能有迫切的需求,可以尝试使用 GitHub 平台上其他的第三方如 `charts` 等原生的图表库,可能会有较好的解决方法㊗️

**Comment by weiweilong** [comment]
感谢作者的及时回复。

**Comment by weiweilong** [comment]
你好，我在demo的基础上pull 了一个，使用给AAChartView添加UITapGestureRecognizer的方式，监听点击的列，希望可以给您带来参考。😊

**Comment by AAChartModel** [comment]
AAChartKit 现已支持点击事件, 参见重复问题 #810 及 AAChartKit 中点击事件相关的 demo 代码.
