### ISSUE TITLE
扇形图 显示不全问题 显示的数据超出边界了

### ISSUE THREAD

**Issue by iostang** [AAChartModel/AAChartKit#840]
作者你好 这个能解吗？

![1580871306442](https://user-images.githubusercontent.com/9524660/73807068-279fa900-4806-11ea-96a5-c8a92230a16e.jpg)

**Comment by iostang** [comment]
使用AAOptions设置distance 解决此问题

**Comment by a123478we** [comment]
怎么设置的

**Comment by AAChartModel** [comment]
> 怎么设置的

调整图表的margin属性就可以了
