### ISSUE TITLE
【提问贴】多折线问题

### ISSUE THREAD

**Issue by xfbxfb** [AAChartModel/AAChartKit#841]
当一个图表有多条折线时，这几条折线单位大小差距很大（如图）
![Uploading WechatIMG1.jpeg…]
（比如Line1区间是从0~100，Line2区间是1000000~10000000，Line3区间是100~1000），这类图表如何让这三条折线相交（如下图）显示呢？
![WechatIMG2 1](https://user-images.githubusercontent.com/15652946/74215792-4954d080-4cdd-11ea-91e4-257b0f34877f.jpeg)

**Comment by AAChartModel** [comment]
可以参考双 Y轴,三重 Y轴的的图表示例,将三种图表各自分成单独的一组

**Comment by AAChartModel** [comment]
参见 #763

**Comment by xfbxfb** [comment]
OK我去看一下，非常感谢回复！
By the way，祝作者新年快乐，更上一层楼！

**Comment by AAChartModel** [comment]
demo 中这些示例都有,详细内容查看 demo.

PS:
效果图请尽量使用屏幕截图,不要使用手机拍照,画质差观感不佳,且体积庞大,加载速度慢
