### ISSUE TITLE
饼图的折线总是超出屏幕，太难受了，老哥快改改吧

### ISSUE THREAD

**Issue by sunjinayushiwo** [AAChartModel/AAChartKit#845]

**Comment by AAChartModel** [comment]
参见相似问题 #776

**Comment by AAChartModel** [comment]
参见安卓端 AAChartCore 的同样问题 https://github.com/AAChartModel/AAChartCore/issues/36

**Comment by AAChartModel** [comment]
**综上所述,解决`饼图折线超出屏幕问题`有三种办法:**

1. 缩小 margin 上下左右边距
2. 缩小 DataLabels 的 distance 距离(默认的距离较长)
3. 在 DataLabels 中插入换行符`<br>`,使其一行(默认是一行)变为多行,借以避免一行文字过长导致超出屏幕

**Comment by sunjinayushiwo** [comment]
DataLabels 的 distance 距离用oc语言怎么设置啊，看了安卓版本的还是不会
