### ISSUE TITLE
AAChartView 里面 dealloc方法根本没有执行啊

### ISSUE THREAD

**Issue by cheng-ren** [AAChartModel/AAChartKit#847]
发现AAChartView有内存泄露问题；
经过排查，咱们Demo里面AAChartView 的 dealloc 也没有执行。请回复

**Comment by cui30366423** [comment]
我也发现了这个问题，图表对象不会释放，是不是webview的关系，希望作者解决一下，虽然影响不是很大，可以正常使用，毕竟有这个问题存在

**Comment by lovephoenix** [comment]
> 我也发现了这个问题，图表对象不会释放，是不是webview的关系，希望作者解决一下，虽然影响不是很大，可以正常使用，毕竟有这个问题存在

自己试着解决了，通过Debug，发现AAChartView的dealloc没有执行，所以自行处理了他dealloc里面相关逻辑。
``` objc
- (void)dealloc {
    if (_aaChartView.configuration.userContentController && [_aaChartView.configuration.userContentController respondsToSelector:@selector(removeScriptMessageHandlerForName:)]) {
        [_aaChartView.configuration.userContentController removeScriptMessageHandlerForName:@"mouseover"];
    }
}
```

**Comment by cui30366423** [comment]
添加你提供的代码。确实可以释放了。 这应该是webview 对于添加的js脚本对象处理的问题，经典的wk的处理，感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 任成 <notifications@github.com&gt;
发送时间: 2020年3月10日 10:23
收件人: AAChartModel/AAChartKit <AAChartKit@noreply.github.com&gt;
抄送: 崔亚鹏 <suoxwd@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[AAChartModel/AAChartKit] AAChartView 里面 dealloc方法根本没有执行啊 (#847)



 
我也发现了这个问题，图表对象不会释放，是不是webview的关系，希望作者解决一下，虽然影响不是很大，可以正常使用，毕竟有这个问题存在
  
自己试着解决了，通过Debug，发现AAChartView的dealloc没有执行，所以自行处理了他dealloc里面相关逻辑。
 - (void)dealloc {     if (_aaChartView.configuration.userContentController &amp;&amp; [_aaChartView.configuration.userContentController respondsToSelector:@selector(removeScriptMessageHandlerForName:)]) {         [_aaChartView.configuration.userContentController removeScriptMessageHandlerForName:@"mouseover"];     } }
