### ISSUE TITLE
请问当图表类型为AAChartTypeColumn  或者 AAChartTypeBar，每个bar的宽度或者高度设置，当dataSet数组为一个时候，那个bar太宽了或太高了

### ISSUE THREAD

**Issue by CoderJackySong** [AAChartModel/AAChartKit#849]
比如图中的红色标记区域，高度太高了，想设置小点，改怎么设置这个高度呢？
<img width="288" alt="截屏2020-03-05上午1 02 20" src="https://user-images.githubusercontent.com/21197997/75904098-8a27ab80-5e7d-11ea-8a6e-8fd157a1befc.png">

**Comment by AAChartModel** [comment]
调整长条的长度只需要调整 AAChartModel 的 yMax(Y轴的最大值即可)

**Comment by AAChartModel** [comment]
关于调整长条的宽度,参见 issue #537
