### ISSUE TITLE
蜘蛛网

### ISSUE THREAD

**Issue by AllenYangShuang** [AAChartModel/AAChartKit#853]
您好，昨天您写的例子在旧的版本中显示不出来，您知道为什么吗？

**Comment by AAChartModel** [comment]
旧的版本中？可能这个X轴的formatter属性在旧的版本中不支持，导致了图表无法被显示。建议你按照readme文档中所说的，将aachartkit更新至最新版本，再尝试一下

**Comment by AllenYangShuang** [comment]
可是更新至最新版本，折线图的X轴文字又显示不全了，咋办

**Comment by AAChartModel** [comment]
你把你的折线图代码复制粘贴出来看一下

**Comment by AllenYangShuang** [comment]
-(void)setModel:(DGBDashListModel *)model
{
    _model = model;
    
    NSMutableArray *xTitles = [NSMutableArray array];
    for (int i = 0; i < model.form_columns.count; i++) {
        DGBFormColumnsModel *columnModel = [model.form_columns objectAtIndex:i];
        if (IS_UN_NIL_STR(columnModel.column_title)) {
            NSString * str = columnModel.column_title;
            [xTitles addObject:str];
        }
    }
    //设置 AAChartView 的背景色是否为透明
    _aaChartView.isClearBackgroundColor = YES;
    AAChartModel *aaChartModel = AAChartModel.new
    .chartTypeSet(AAChartTypeLine)//图表类型
    .titleSet(@"")//图表主标题
    .subtitleSet(@"")//图表副标题
    .yAxisLineWidthSet(@0)//Y轴轴线线宽为0即是隐藏Y轴轴线
    .colorsThemeSet(@[@"#F55A5A"])//设置主体颜色数组
    .yAxisTitleSet(@"")//设置 Y 轴标题
    .backgroundColorSet(@"#ffffff")
    .legendEnabledSet(false)
    .yAxisGridLineColorSet(@"#3E4F7C")//Y轴分割线颜色
    .xAxisGridLineColorSet(@"#3E4F7C")//X轴分割线颜色
    .xTickWidthSet(@0)//隐藏X轴刻度线
    .yAxisGridLineWidthSet(@0.5)//y轴横向分割线宽度为0(即是隐藏分割线)
    .touchEventEnabledSet(YES)//支持用户点击事件
    .tooltipEnabledSet(YES)
    .xAxisLabelsEnabledSet(YES)//X轴是否显示文字
    .xAxisTickIntervalSet(@0)//x轴刻度点间隔数(设置每隔几个点显示一个 X轴的内容)
    .categoriesSet(xTitles)
    .xAxisLabelsFontSizeSet(@(kLYAutoWidthPixel_22px))
    .yAxisLabelsFontSizeSet(@(kLYAutoWidthPixel_22px))
    .xAxisLabelsFontColorSet(@"#8791AC")
    .yAxisLabelsFontColorSet(@"#8791AC")
    .seriesSet(@[
                 AAObject(AASeriesElement)
                 .dataSet(model.form_wave)
                 ]
               );
    AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
   
    AATooltip *tooltip = aaOptions.tooltip;
    tooltip
    .useHTMLSet(YES)
    .formatterSet(@AAJSFunc(function () {
        return
        this.x
        + ' <br/>'
        +  this.y
        + ' </b> ';
    }))
    .valueDecimalsSet(@2)//设置取值精确到小数点后几位
    .backgroundColorSet(@"#ffffff")
    .borderColorSet(@"#ffffff")
    .styleSet((id)AAStyle.new
              .colorSet(@"#666666")
              .fontSizeSet(@"12px")
              );
    [_aaChartView aa_drawChartWithOptions:aaOptions];
}

**Comment by AllenYangShuang** [comment]
<img width="323" alt="image" src="https://user-images.githubusercontent.com/12180694/76917119-7a887800-68fd-11ea-8883-a839541228ac.png">
aaOptions.xAxis
//    .lineWidthSet(@0)//避免多边形外环之外有额外套了一层无用的外环
//    .labels
//    .styleSet(AAStyle.new
//              .colorSet(AAColor.blackColor))
//    .formatterSet(xAxisLabelsFormatter);

**Comment by AllenYangShuang** [comment]
还在吗？

**Comment by AAChartModel** [comment]
> 可是更新至最新版本，折线图的X轴文字又显示不全了，咋办

设置 AAChartModel 的 xAxisTickInterval 属性为`@1`看看

```objc
    .xAxisTickIntervalSet(@1)//x轴刻度点间隔数(设置每隔几个点显示一个 X轴的内容)
```

**Comment by AAChartModel** [comment]
如果只是注释掉下面这段代码
```objc
    aaOptions.xAxis
    .lineWidthSet(@0)//避免多边形外环之外有额外套了一层无用的外环
    .labels
    .styleSet(AAStyle.new
              .colorSet(AAColor.blackColor))
    .formatterSet(xAxisLabelsFormatter);
```
图表显示的效果理应是这样的
<img width="249" alt="截屏2020-03-19上午11 03 42" src="https://user-images.githubusercontent.com/16357599/77027488-5302df80-69d1-11ea-80bf-f7115241157b.png">

蜘蛛网 🕷🕸图表的网线是圆形还是多边形,只和`gridLineInterpolation`这个属性有关

```objc

    aaOptions.yAxis
    .gridLineInterpolationSet(AAYAxisGridLineInterpolationPolygon)//设置蜘蛛网🕸图表的网线为多边形
    .labelsSet(AALabels.new
               .styleSet(AAStyle.new
                         .colorSet(AAColor.blackColor)));
```
gridLineInterpolation属性值的可选项有以下两种👇
```objc
typedef NSString *AAYAxisGridLineInterpolation;
static AAYAxisGridLineInterpolation const AAYAxisGridLineInterpolationCircle  = @"circle";//圆形
static AAYAxisGridLineInterpolation const AAYAxisGridLineInterpolationPolygon = @"polygon";//多边形
```
