### ISSUE TITLE
AASeriesElement 的 dataSet 用字符串数组是不好用的，请问以后会支持字符串数组赋值吗！

### ISSUE THREAD

**Issue by MaTsongaHLJ** [AAChartModel/AAChartKit#859]
AAObject(AASeriesElement)
                       .nameSet(@"海拔")
                       .dataSet(altArr),

**Comment by AAChartModel** [comment]
应该不会,图表是用来对数据进行可视化的,肯定是要支持数值类型的. 如果你的原始数据是字符串的话,需要你自己手动将 NSString 类型转换成 NSNumber 类型.
