### ISSUE TITLE
柱状图y轴最小值设置为0了，当数据为0时，y轴0的线会显示在图的中间

### ISSUE THREAD

**Issue by wtuyp** [AAChartModel/AAChartKit#860]
你好，
     柱状图y轴最小值设置为0了，当数据为0时，y轴0的线会显示在图的中间。如下图。
     我应该怎么设置呀，希望数据为0时，y轴0的线应该是跟x轴重合的。
                                                              谢谢。

<img width="322" alt="Screen Shot 2020-04-11 at 11 25 58" src="https://user-images.githubusercontent.com/2791870/79034270-3ed48b80-7be7-11ea-9bef-f86494c34cc6.png">

**Comment by AAChartModel** [comment]
重复问题,参见 https://github.com/AAChartModel/AAChartKit/issues/773
