### ISSUE TITLE
y轴横线之间设置不同的颜色

### ISSUE THREAD

**Issue by Rubyios** [AAChartModel/AAChartKit#865]
您好，我想给y轴的分割线中间设置不同的颜色表示数据偏低、偏高或正常怎么设置啊？
是设置AAPlotBandsElement这个吗？不知道怎么用

**Comment by AAChartModel** [comment]
不是,设置阈值分割线的是 `AAPlotLinesElement` 这个类, 实现效果类似于

![](https://raw.githubusercontent.com/AAChartModel/Gallery/master/AAChartKit/plotLinesChart.png)

**Comment by AAChartModel** [comment]
`AAPlotBandsElement `是用于设置阈值分割带的,demo 中有此两者详细示例.  更多内容参见 README 文档及 AAChartKit 使用 demo.
