### ISSUE TITLE
请教一下，竖屏转横屏

### ISSUE THREAD

**Issue by theHeroisBack** [AAChartModel/AAChartKit#866]
就是只旋转屏幕，不更改任何chart的属性和内容数据，只适配UI，有高效的方法吗？

我这里在viewDidLayoutSubviews的方法里调用了aa_refreshChartWithChartModel方法，
但是log出警告如下：
☠️☠️💀☠️☠️!!!!!WARNING!!!!! THERE ARE SOME ERROR INFOMATION_______{
    code = 4;
    domain = WKErrorDomain;
    userInfo =     {
        NSLocalizedDescription = "\U53d1\U751fJavaScript\U5f02\U5e38";
        WKJavaScriptExceptionColumnNumber = 21;
        WKJavaScriptExceptionLineNumber = 1;
        WKJavaScriptExceptionMessage = "ReferenceError: Can't find variable: loadTheHighChartView";
        WKJavaScriptExceptionSourceURL = undefined;
    };

**Comment by AAChartModel** [comment]
问题已解决,参见 #915

**Comment by AAChartModel** [comment]
```ruby
pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'

```

更新 AAChartKit 至最新内容,即可使用 AAChartView 中的新增自适应屏幕旋转的方法

```objc

/// Set the chart view content be adaptive to screen rotation
- (void)aa_adaptiveScreenRotation;

/// Set the chart view content be adaptive to screen rotation with custom animation effect
/// Refer to https://api.highcharts.com.cn/highcharts#Chart.setSize
///
/// @param animation The instance object of AAAnimation
- (void)aa_adaptiveScreenRotationWithAnimation:(AAAnimation *)animation;
```
