### ISSUE TITLE
tooltip 设置点击事件

### ISSUE THREAD

**Issue by houxiaodong** [AAChartModel/AAChartKit#870]
tooltip可以设置点击事件吗？点击跳转新的界面，把所选择点的数据传过去？

**Comment by AAChartModel** [comment]
参见内容 https://github.com/AAChartModel/AAChartKit/issues/321#issuecomment-505269528

**Comment by houxiaodong** [comment]
321上面是整个图形的点击事件的嘛，能不能只是点击tolltip，有事件响应，并且跳转新界面呢。

**Comment by AAChartModel** [comment]
> 能不能只是点击tolltip

不支持此功能
