### ISSUE TITLE
iOS 扇形图bug，数据在9个或以上部分百分比数据缺失

### ISSUE THREAD

**Issue by 674397611** [AAChartModel/AAChartKit#871]
iOS 饼状图，数据在9个或以上部分百分比数据缺失，只划线不显示百分比title或者有的部分线也没有画

**Comment by 674397611** [comment]
iOS 扇形图，数据在9个或以上部分百分比数据缺失，只划线不显示百分比title或者有的部分线也没有画

**Comment by AAChartModel** [comment]
这个可能是 Highcharts 为了规避 DataLabels 相互堆积覆盖,自动隐藏部分数据标签时所导致的问题.

**Comment by AAChartModel** [comment]
可以在数据较多时, 设置饼图半径更小一些,腾出更多空间借以显示更多数据标签.

**Comment by 674397611** [comment]
显示空间够，线画出了，但便签没显示，显示标签的位置还有很大

**Comment by AAChartModel** [comment]
麻烦粘贴一下你的问题代码(不要截图)

**Comment by stronger77** [comment]
扇形图明明是有点数据的就是占比小，线画出来，但是数据不显示

**Comment by 674397611** [comment]
AASeriesElement *element = AASeriesElement.new
    .nameSet(@"")
    .innerSizeSet(@"60%")//内部圆环半径大小占比
    .sizeSet(@100)//尺寸大小
    .borderWidthSet(@0)//描边的宽度
    .allowPointSelectSet(false)//是否允许在点击数据点标记(扇形图点击选中的块发生位移)
    .statesSet(AAStates.new
               .hoverSet(AAHover.new
                         .enabledSet(false)//禁用点击区块之后出现的半透明遮罩层
                         ))
    .dataSet(@[@[@"钢铁",@7.4],@["水泥",@4.1],@["焦化",@2.1],@["电力能源",@5],@["玻璃",@3.3],@["医疗",@1.5],@["其它",@10.7],@["制造业",@12.1],@["金属制品",@15.4],@["木材加工",@23.1],@["建材化工",@15.4]]);
    [self.aaChartView aa_drawChartWithChartModel:AAChartModel.new
    .chartTypeSet(AAChartTypePie)
    .colorsThemeSet(@[#DFB780,#34870D,#ABD7EC,#7E90CA,#350F2,#CEA740,#808457,#A373D1,#B6542B,#BD8C9A,#574C45])
    .titleSet(@"")
    .subtitleSet(@"")
     .legendEnabledSet(false)
    .dataLabelsEnabledSet(true)//是否直接显示扇形图数据
    .yAxisTitleSet(@"")
    .seriesSet(@[element])];

**Comment by 674397611** [comment]
后面几个空比较大但标签没显示出来

**Comment by 674397611** [comment]
可以考虑大于5%的画出来，或者小于%5但相邻的有大于%5的也可以画出来，大于5%应该够展示的

**Comment by AAChartModel** [comment]
问题已解决,参见重复问题 #884
