### ISSUE TITLE
该类库可以实现睡眠质量类型的散点柱形图吗？

### ISSUE THREAD

**Issue by RichardDuan** [AAChartModel/AAChartKit#873]
如题，是否可以实现散点柱形图类型，另外附上设计图
![image](https://user-images.githubusercontent.com/15153355/80583851-6169ff80-8a43-11ea-9402-414f891f2df0.png)
还有一个疑问，滑动选中的样式可以进行自定义吗？
希望大佬能够回答一下

**Comment by AAChartModel** [comment]
`AAChartKit` 暂不支持此次功能,参见 `AAChartKit-Swift` 中的问题 https://github.com/AAChartModel/AAChartKit-Swift/issues/140

**Comment by AAChartModel** [comment]
现已支持此功能, 参考:
* https://github.com/AAChartModel/AAChartKit/issues/1445
