### ISSUE TITLE
能不能有X轴有截断的效果

### ISSUE THREAD

**Issue by smsouls** [AAChartModel/AAChartKit#877]
![image](https://user-images.githubusercontent.com/8297200/81259624-ea4bf100-906a-11ea-9b8b-45682a5914d3.png)

像上图那样，本来我想放两个柱状图，但是这样的话可能昨天的数据更小，反而高度更高。

![image](https://user-images.githubusercontent.com/8297200/81259771-3ac34e80-906b-11ea-9057-314fa9571e63.png)
为什么这个数据不会置顶。我是想要把显示的数据放柱形图上面。

**Comment by AAChartModel** [comment]
将Y轴最大值设置的比你的数据中的最大值还要大一些

```objc
AAPropStatementAndPropSetFuncStatement(strong, AAChartModel, NSNumber *, yAxisMax) //y 轴最大值
```
借以空置出更多空间,这样的话 DataLabels 就会自动显示在长条棱柱的最上方了

**Comment by AAChartModel** [comment]
或者修改Y轴最小值,

```objc
AAPropStatementAndPropSetFuncStatement(strong, AAChartModel, NSNumber *, yAxisMin) //y 轴最小值（设置为0就不会有负数）

```

比如如下设置 Y轴最小值为 10, 数值 10 以下的部分就会被截断,图表直接从 Y轴为 10 的位置开始绘制.

```objc
    .yAxisMinSet(@10)//设置 Y轴最小值为 10, 数值 10 以下的部分就会被截断
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"2017")
        .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6]),
        AASeriesElement.new
        .nameSet(@"2018")
        .dataSet(@[@0.2, @0.8, @5.7, @11.3, @17.0, @22.0, @24.8, @24.1, @20.1, @14.1, @8.6, @2.5]),
        AASeriesElement.new
        .nameSet(@"2019")
        .dataSet(@[@0.9, @0.6, @3.5, @8.4, @13.5, @17.0, @18.6, @17.9, @14.3, @9.0, @3.9, @1.0]),
        AASeriesElement.new
        .nameSet(@"2020")
        .dataSet(@[@3.9, @4.2, @5.7, @8.5, @11.9, @15.2, @17.0, @16.6, @14.2, @10.3, @6.6, @4.8]),
    ]);
```

![image](https://user-images.githubusercontent.com/16357599/81261662-08b3eb80-906f-11ea-94bf-e7a2ec2937ee.png)

**Comment by smsouls** [comment]
好的，谢谢讲解这么详细。

**Comment by smsouls** [comment]
.yAxisMaxSet(@(self.maxAmount * 1.3))，我设置一个最大值的1.3的比例，达到了我想要的效果。
对于不同的柱状图，设置同一个最大值，即使是在不同的柱状图里，也可以使得高度也有统一的比例。
