### ISSUE TITLE
饼图去除点击的透明效果以及自定义饼图线条样式

### ISSUE THREAD

**Issue by Jins-org** [AAChartModel/AAChartKit#879]
作者您好，项目中大量使用到了AAChartKit，效果非常棒👍

现在使用饼图的时候遇到一点问题：

1.设置了 `.statesSet(@{@"hover": @{@"enabled": @(bool_false)}` 
现在点击饼图会出现整体半透明效果:
![pie.png](https://i.loli.net/2020/05/09/AhzFJq3OdQXop2Z.jpg)

2.dataLabel延伸的线条是否有其他样式，我们这边给出的样式如下图：
![pie.png](https://i.loli.net/2020/05/09/bCy7EUfdFn6rv81.png)

期待作者的回答。

**Comment by AAChartModel** [comment]
> 2.dataLabel延伸的线条是否有其他样式

AADataLabels 新增了属性 `softConnector`
```objc
AAPropStatementAndPropSetFuncStatement(assign,   AADataLabels, BOOL      , softConnector)//Whether to render the connector as a soft arc or a line with sharp break. Only useful for pie, pyramid and funnel chart
```

属性`softConnector`作用参见官方文档 https://api.highcharts.com.cn/highcharts#plotOptions.pie.dataLabels.softConnector

**Comment by AAChartModel** [comment]
> 1.设置了 `.statesSet(@{@"hover": @{@"enabled": @(bool_false)}`
现在点击饼图会出现整体半透明效果:

```objc
.statesSet(@{@"hover": @{@"enabled": @(bool_false)}
```
这段代码主要是为了禁用饼图的如下图中所示的,扇区被选中后,选中的扇区上会出现的一层半透明浅色遮罩层(此遮罩层主要是为了起到高亮选中区的效果)
![image](https://user-images.githubusercontent.com/16357599/81469562-22dcfd80-9218-11ea-9f9c-e649aa134e8b.png)

**Comment by ZeroJson** [comment]
softConnector这个属性用过后没有生效
```    
     AAChartModel *aaChartModel= AAChartModel.new
    .chartTypeSet(AAChartTypePie)
    .titleSet(@"")
    .colorsThemeSet((@[@"#19CDCD",@"#19A6FB",@"#9A87E0",@"#F37D7D",@"#FF00FF",@"#9400D3",@"#1E90FF",@"#00BFFF",@"#008080",@"#20B2AA",@"#F0E68C",@"#FFA500",@"#FF6347",@"#DC143C",@"#000080",@"#00FF7F",]))
    .dataLabelsEnabledSet(true)//是否直接显示扇形图数据
    .yAxisTitleSet(@"摄氏度")
    .legendEnabledSet(false)
    .polarSet(true)
    .seriesSet(@[
        AASeriesElement.new
        .dataLabelsSet(AADataLabels.new
                       .softConnectorSet(true)
//                                   .distanceSet(@10)
                                   )
        .sizeSet(@135)//环形图的半径大小
        .nameSet(@"数量")
```

**Comment by ZeroJson** [comment]
![image](https://user-images.githubusercontent.com/15608700/93579543-2dcb4a00-f9d1-11ea-9919-28faed324952.png)
类似这样的效果
