### ISSUE TITLE
图表的结构能够显示，线跟左侧的值显示不出来

### ISSUE THREAD

**Issue by asd6802862** [AAChartModel/AAChartKit#882]
我在自定义view中按照demo中创建写死数据，线出不来，把代码复制出来新建一个项目，又能正常显示，也没输出报错，找了好久找不到什么原因

**Comment by AAChartModel** [comment]
问题已解决,参见重复问题 #884

**Comment by asd6802862** [comment]
大佬，我这个问题跟#884不同啊 ,我的数据都是从demo中复制出来的，就是线跟y轴的数值显示不出来，x轴和其他的可以显示
 AAChartModel *aaChartModel = AAObject(AAChartModel)
    .chartTypeSet(AAChartTypeSpline)
    .titleSet(@"趋势图")
    .categoriesSet(@[@"Java", @"Swift"])
    .yAxisTitleSet(@"")
    .seriesSet(@[
                 AASeriesElement.new
                 .nameSet(@"2017")
                 .dataSet(@[@7.0, @6.9]),
                 AASeriesElement.new
                 .nameSet(@"2018")
                 .dataSet(@[@0.2, @0.8]),
                 AASeriesElement.new
                 .nameSet(@"2019")
                 .dataSet(@[@0.9, @0.6]),
                 AASeriesElement.new
                 .nameSet(@"2020")
                 .dataSet(@[@3.9, @4.2]),
                 ]);
    [aaChartView aa_drawChartWithChartModel:aaChartModel];

**Comment by AAChartModel** [comment]
你的代码我复制粘贴到 AAChartKit 的 demo 中运行,显示效果如下

<img width="610" alt="Screen Shot 2020-06-09 at 1 59 51 PM" src="https://user-images.githubusercontent.com/16357599/84111476-9bbeb780-aa59-11ea-9f52-176a80aca9b2.png">


如上图所示, y轴的数值和轴线都是可以正常显示的.

**Comment by AAChartModel** [comment]
可能和你使用的 AAChartKit 版本有关系

```ruby
pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'
```

你可以更新AAChartKit 的 pods 至最新内容试试

或者你可以先试试将代码粘贴到 AAChartKit 的最新 demo 中试试.对比一下看看到底是什么问题.

**Comment by asd6802862** [comment]
是啊 我新建一个工程 也能够正常显示  但是在我的项目中就显示如下图了
![Simulator Screen Shot - iPhone X - 2020-06-09 at 14 08 10](https://user-images.githubusercontent.com/18521959/84112088-b2194300-aa5a-11ea-9132-0343762638bd.png)

**Comment by AAChartModel** [comment]
你可以更新AAChartKit 的 pods 至最新内容试试

**Comment by asd6802862** [comment]
已经按照#884更新到最新了，还是一样的

**Comment by AAChartModel** [comment]
> 大佬，我这个问题跟#884不同啊 ,我的数据都是从demo中复制出来的，就是线跟y轴的数值显示不出来，x轴和其他的可以显示
> 
> ```objc
>  AAChartModel *aaChartModel = AAObject(AAChartModel)
>     .chartTypeSet(AAChartTypeSpline)
>     .titleSet(@"趋势图")
>     .categoriesSet(@[@"Java", @"Swift"])
>     .yAxisTitleSet(@"")
>     .seriesSet(@[
>                  AASeriesElement.new
>                  .nameSet(@"2017")
>                  .dataSet(@[@7.0, @6.9]),
>                  AASeriesElement.new
>                  .nameSet(@"2018")
>                  .dataSet(@[@0.2, @0.8]),
>                  AASeriesElement.new
>                  .nameSet(@"2019")
>                  .dataSet(@[@0.9, @0.6]),
>                  AASeriesElement.new
>                  .nameSet(@"2020")
>                  .dataSet(@[@3.9, @4.2]),
>                  ]);
>     [aaChartView aa_drawChartWithChartModel:aaChartModel];
> ```

在你的项目中, 使用的也是这部分代码吗? 还是你的数据获取有问题?

**Comment by AAChartModel** [comment]
或者你在AAChartView.html 文件中的

```js
function loadTheHighChartView(sender, receivedWidth, receivedHeight) {
```
这一行代码下加上一句`alert(sender);`变成下面这样
```js
 function loadTheHighChartView(sender, receivedWidth, receivedHeight) {
            alert(sender);
```
再运行项目, 查看图表页面的提示框的内容,看看 json 数据中的 series 字段下的数组,看看是否包含了正确的 name 和 data 值.
![image](https://user-images.githubusercontent.com/16357599/84114291-b182ab80-aa5e-11ea-83e1-d3d2bb0a15f6.png)

**Comment by asd6802862** [comment]
webview注入的时候 接收不到我传的seriesSet数据啊  这是为啥啊
![811591688873_ pic](https://user-images.githubusercontent.com/18521959/84120720-ccf2b400-aa68-11ea-8678-fa0f0e761bfb.jpg)

**Comment by asd6802862** [comment]
![Simulator Screen Shot - iPhone X - 2020-06-09 at 15 50 53](https://user-images.githubusercontent.com/18521959/84120902-075c5100-aa69-11ea-8cb7-6bf53bf5d194.png)

**Comment by AAChartModel** [comment]
我看你生成的 json 数据明明不对啊, 你的 keys 数组里为何会有这么多字符串的值?

**Comment by AAChartModel** [comment]
你把 AAChartView 中的

```objc
+ (NSString *)getPureStringWithJSONObject:(id)objc {
    NSString *seriesStr = [self jsonStringWithJsonObject:objc];
    return [self wipeOffTheLineBreakAndBlankCharacter:seriesStr];
}
```

改成
```objc
+ (NSString *)getPureStringWithJSONObject:(id)objc {
    NSString *seriesStr = [self jsonStringWithJsonObject:objc];
    AADetailLog(@"----------- console log AAOptions JSON information of AAChartView -----------:\n%@",seriesStr);
    return [self wipeOffTheLineBreakAndBlankCharacter:seriesStr];
}
```
然后再运行看看控制台打印的json 数据是不是这样的

```js
----------- console log AAOptions JSON information of AAChartView -----------:
{
  "touchEventEnabled" : false,
  "gradientColorEnabled" : false,
  "chart" : {
    "polar" : false,
    "type" : "spline",
    "inverted" : false,
    "pinchType" : "none",
    "panning" : true
  },
  "tooltip" : {
    "useHTML" : false,
    "crosshairs" : true,
    "shared" : true,
    "animation" : true,
    "followTouchMove" : true,
    "enabled" : true
  },
  "xAxis" : {
    "labels" : {
      "style" : {
        "fontSize" : "11px",
        "fontWeight" : "thin",
        "color" : "#778899"
      },
      "useHTML" : false,
      "enabled" : true
    },
    "reversed" : false,
    "startOnTick" : false,
    "opposite" : false,
    "endOnTick" : false,
    "gridLineWidth" : 0,
    "tickmarkPlacement" : "on",
    "tickInterval" : 1,
    "visible" : true,
    "categories" : [
      "Java",
      "Swift"
    ]
  },
  "plotOptions" : {
    "series" : {
      "marker" : {
        "radius" : 5
      },
      "connectNulls" : false,
      "stacking" : "",
      "dataLabels" : {
        "softConnector" : true,
        "useHTML" : false,
        "allowOverlap" : false,
        "crop" : false,
        "enabled" : false,
        "inside" : false
      }
    }
  },
  "series" : [
    {
      "name" : "2017",
      "data" : [
        7,
        6.9000000000000004
      ],
      "showInLegend" : true,
      "allowPointSelect" : false,
      "visible" : true
    },
    {
      "name" : "2018",
      "data" : [
        0.20000000000000001,
        0.80000000000000004
      ],
      "showInLegend" : true,
      "allowPointSelect" : false,
      "visible" : true
    },
    {
      "name" : "2019",
      "data" : [
        0.90000000000000002,
        0.59999999999999998
      ],
      "showInLegend" : true,
      "allowPointSelect" : false,
      "visible" : true
    },
    {
      "name" : "2020",
      "data" : [
        3.8999999999999999,
        4.2000000000000002
      ],
      "showInLegend" : true,
      "allowPointSelect" : false,
      "visible" : true
    }
  ],
  "title" : {
    "style" : {
      "fontSize" : "14px",
      "fontWeight" : "regular",
      "color" : "#000000"
    },
    "useHTML" : false,
    "text" : "趋势图"
  },
  "colors" : [
    "#1e90ff",
    "#ef476f",
    "#ffd066",
    "#04d69f",
    "#25547c"
  ],
  "yAxis" : {
    "labels" : {
      "style" : {
        "fontSize" : "11px",
        "fontWeight" : "thin",
        "color" : "#778899"
      },
      "useHTML" : false,
      "enabled" : true,
      "format" : "{value:.,0f}"
    },
    "reversed" : false,
    "title" : {
      "text" : ""
    },
    "startOnTick" : false,
    "allowDecimals" : true,
    "opposite" : false,
    "endOnTick" : false,
    "gridLineWidth" : 1,
    "visible" : true,
    "lineWidth" : 0.5
  },
  "legend" : {
    "enabled" : true,
    "floating" : false
  }
}

```

**Comment by asd6802862** [comment]
打印如下 series完全不正确

----------- console log AAOptions JSON information of AAChartView -----------:
{
  "subtitle" : {
    "align" : "left",
    "style" : {
      "fontSize" : "9px",
      "fontWeight" : "regular",
      "color" : "#000000"
    }
  },
  "gradientColorEnabled" : false,
  "touchEventEnabled" : false,
  "chart" : {
    "polar" : false,
    "type" : "spline",
    "inverted" : false,
    "pinchType" : "none",
    "panning" : true
  },
  "tooltip" : {
    "useHTML" : false,
    "crosshairs" : true,
    "shared" : true,
    "animation" : true,
    "followTouchMove" : true,
    "enabled" : true
  },
  "xAxis" : {
    "categories" : [
      "Java",
      "Swift"
    ],
    "labels" : {
      "style" : {
        "fontSize" : "11px",
        "fontWeight" : "thin",
        "color" : "#778899"
      },
      "useHTML" : false,
      "enabled" : true
    },
    "tickInterval" : 1,
    "opposite" : false,
    "tickmarkPlacement" : "on",
    "reversed" : false,
    "visible" : true,
    "startOnTick" : false,
    "gridLineWidth" : 0,
    "endOnTick" : false
  },
  "plotOptions" : {
    "series" : {
      "marker" : {
        "radius" : 5
      },
      "keys" : [
        "borderRadius",
        "marker",
        "stacking",
        "animation",
        "keys",
        "connectNulls",
        "events",
        "shadow",
        "dataLabels"
      ],
      "connectNulls" : false,
      "stacking" : "",
      "dataLabels" : {
        "softConnector" : true,
        "allowOverlap" : false,
        "useHTML" : false,
        "inside" : false,
        "enabled" : false,
        "crop" : false
      }
    }
  },
  "series" : [
    {
      "keys" : [
        "type",
        "allowPointSelect",
        "name",
        "data",
        "color",
        "colorByPoint",
        "marker",
        "stacking",
        "dashStyle",
        "threshold",
        "lineWidth",
        "borderWidth",
        "borderColor",
        "fillColor",
        "fillOpacity",
        "negativeColor",
        "borderRadius",
        "innerSize",
        "size",
        "keys",
        "yAxis",
        "dataLabels",
        "step",
        "states",
        "showInLegend",
        "visible",
        "zones",
        "zoneAxis",
        "shadow",
        "stack",
        "tooltip",
        "zIndex",
        "pointPlacement"
      ],
      "allowPointSelect" : false,
      "showInLegend" : true,
      "data" : [
        7,
        6.9000000000000004
      ],
      "visible" : true,
      "name" : "2017"
    },
    {
      "keys" : [
        "type",
        "allowPointSelect",
        "name",
        "data",
        "color",
        "colorByPoint",
        "marker",
        "stacking",
        "dashStyle",
        "threshold",
        "lineWidth",
        "borderWidth",
        "borderColor",
        "fillColor",
        "fillOpacity",
        "negativeColor",
        "borderRadius",
        "innerSize",
        "size",
        "keys",
        "yAxis",
        "dataLabels",
        "step",
        "states",
        "showInLegend",
        "visible",
        "zones",
        "zoneAxis",
        "shadow",
        "stack",
        "tooltip",
        "zIndex",
        "pointPlacement"
      ],
      "allowPointSelect" : false,
      "showInLegend" : true,
      "data" : [
        0.20000000000000001,
        0.80000000000000004
      ],
      "visible" : true,
      "name" : "2018"
    },
    {
      "keys" : [
        "type",
        "allowPointSelect",
        "name",
        "data",
        "color",
        "colorByPoint",
        "marker",
        "stacking",
        "dashStyle",
        "threshold",
        "lineWidth",
        "borderWidth",
        "borderColor",
        "fillColor",
        "fillOpacity",
        "negativeColor",
        "borderRadius",
        "innerSize",
        "size",
        "keys",
        "yAxis",
        "dataLabels",
        "step",
        "states",
        "showInLegend",
        "visible",
        "zones",
        "zoneAxis",
        "shadow",
        "stack",
        "tooltip",
        "zIndex",
        "pointPlacement"
      ],
      "allowPointSelect" : false,
      "showInLegend" : true,
      "data" : [
        0.90000000000000002,
        0.59999999999999998
      ],
      "visible" : true,
      "name" : "2019"
    },
    {
      "keys" : [
        "type",
        "allowPointSelect",
        "name",
        "data",
        "color",
        "colorByPoint",
        "marker",
        "stacking",
        "dashStyle",
        "threshold",
        "lineWidth",
        "borderWidth",
        "borderColor",
        "fillColor",
        "fillOpacity",
        "negativeColor",
        "borderRadius",
        "innerSize",
        "size",
        "keys",
        "yAxis",
        "dataLabels",
        "step",
        "states",
        "showInLegend",
        "visible",
        "zones",
        "zoneAxis",
        "shadow",
        "stack",
        "tooltip",
        "zIndex",
        "pointPlacement"
      ],
      "allowPointSelect" : false,
      "showInLegend" : true,
      "data" : [
        3.8999999999999999,
        4.2000000000000002
      ],
      "visible" : true,
      "name" : "2020"
    }
  ],
  "title" : {
    "style" : {
      "fontSize" : "14px",
      "fontWeight" : "regular",
      "color" : "#000000"
    },
    "useHTML" : false,
    "text" : "趋势图"
  },
  "colors" : [
    "#1e90ff",
    "#ef476f",
    "#ffd066",
    "#04d69f",
    "#25547c"
  ],
  "yAxis" : {
    "lineWidth" : 0.5,
    "labels" : {
      "style" : {
        "fontSize" : "11px",
        "fontWeight" : "thin",
        "color" : "#778899"
      },
      "useHTML" : false,
      "enabled" : true,
      "format" : "{value:.,0f}"
    },
    "title" : {
      "text" : ""
    },
    "opposite" : false,
    "reversed" : false,
    "allowDecimals" : true,
    "visible" : true,
    "gridLineWidth" : 1,
    "startOnTick" : false,
    "endOnTick" : false
  },
  "legend" : {
    "enabled" : true,
    "floating" : false
  },
  "zoomResetButtonText" : "恢复缩放"
}

**Comment by AAChartModel** [comment]
我很想知道你的这部分数据

```js
"keys" : [
"type",
"allowPointSelect",
"name",
"data",
"color",
"colorByPoint",
"marker",
"stacking",
"dashStyle",
"threshold",
"lineWidth",
"borderWidth",
"borderColor",
"fillColor",
"fillOpacity",
"negativeColor",
"borderRadius",
"innerSize",
"size",
"keys",
"yAxis",
"dataLabels",
"step",
"states",
"showInLegend",
"visible",
"zones",
"zoneAxis",
"shadow",
"stack",
"tooltip",
"zIndex",
"pointPlacement"
],
```
是从哪里来的?

你是有改动 AAChartKit 的源码吗?

**Comment by asd6802862** [comment]
series中全是AASeriesElement的属性

**Comment by asd6802862** [comment]
没有动源码啊  文件直接拖进工程的

**Comment by AAChartModel** [comment]
这里面的属性是你加进去的?

**Comment by asd6802862** [comment]
我创建图表到设置数据 就一下代码
![屏幕快照 2020-06-09 下午2 33 31](https://user-images.githubusercontent.com/18521959/84124208-7b98f380-aa6d-11ea-932b-56a19920ec01.png)
![屏幕快照 2020-06-09 下午2 33 42](https://user-images.githubusercontent.com/18521959/84124232-86ec1f00-aa6d-11ea-976f-0de2c138417d.png)

**Comment by AAChartModel** [comment]
那你有没有试过用 cocoapods 导入 AAChartKit 呢?

**Comment by AAChartModel** [comment]
你可以把 AASeriesElement 的.h 文件和.m 文件中的 keys 属性注释掉看看,应该就正常了

**Comment by asd6802862** [comment]
用 cocoapods 导入 AAChartKit 还是一样的 打印的series也还是那些东西

**Comment by AAChartModel** [comment]
> 你可以把 AASeriesElement 的.h 文件和.m 文件中的 keys 属性注释掉看看,应该就正常了

试试这个

**Comment by asd6802862** [comment]
注释掉了  series中数据有了，但是界面效果跟之前一样，😂😂

----------- console log AAOptions JSON information of AAChartView -----------:
{
  "touchEventEnabled" : false,
  "gradientColorEnabled" : false,
  "chart" : {
    "polar" : false,
    "type" : "spline",
    "inverted" : false,
    "pinchType" : "none",
    "panning" : true
  },
  "tooltip" : {
    "useHTML" : false,
    "crosshairs" : true,
    "shared" : true,
    "animation" : true,
    "followTouchMove" : true,
    "enabled" : true
  },
  "xAxis" : {
    "categories" : [
      "Java",
      "Swift"
    ],
    "labels" : {
      "style" : {
        "fontSize" : "11px",
        "fontWeight" : "thin",
        "color" : "#778899"
      },
      "useHTML" : false,
      "enabled" : true
    },
    "tickInterval" : 1,
    "opposite" : false,
    "tickmarkPlacement" : "on",
    "reversed" : false,
    "visible" : true,
    "startOnTick" : false,
    "gridLineWidth" : 0,
    "endOnTick" : false
  },
  "plotOptions" : {
    "series" : {
      "marker" : {
        "radius" : 5
      },
      "keys" : [
        "borderRadius",
        "marker",
        "stacking",
        "animation",
        "keys",
        "connectNulls",
        "events",
        "shadow",
        "dataLabels"
      ],
      "connectNulls" : false,
      "stacking" : "",
      "dataLabels" : {
        "softConnector" : true,
        "allowOverlap" : false,
        "useHTML" : false,
        "inside" : false,
        "enabled" : false,
        "crop" : false
      }
    }
  },
  "series" : [
    {
      "allowPointSelect" : false,
      "showInLegend" : true,
      "data" : [
        7,
        6.9000000000000004
      ],
      "visible" : true,
      "name" : "2017"
    },
    {
      "allowPointSelect" : false,
      "showInLegend" : true,
      "data" : [
        0.20000000000000001,
        0.80000000000000004
      ],
      "visible" : true,
      "name" : "2018"
    },
    {
      "allowPointSelect" : false,
      "showInLegend" : true,
      "data" : [
        0.90000000000000002,
        0.59999999999999998
      ],
      "visible" : true,
      "name" : "2019"
    },
    {
      "allowPointSelect" : false,
      "showInLegend" : true,
      "data" : [
        3.8999999999999999,
        4.2000000000000002
      ],
      "visible" : true,
      "name" : "2020"
    }
  ],
  "title" : {
    "style" : {
      "fontSize" : "14px",
      "fontWeight" : "regular",
      "color" : "#000000"
    },
    "useHTML" : false,
    "text" : "趋势图"
  },
  "colors" : [
    "#1e90ff",
    "#ef476f",
    "#ffd066",
    "#04d69f",
    "#25547c"
  ],
  "yAxis" : {
    "lineWidth" : 0.5,
    "labels" : {
      "style" : {
        "fontSize" : "11px",
        "fontWeight" : "thin",
        "color" : "#778899"
      },
      "useHTML" : false,
      "enabled" : true,
      "format" : "{value:.,0f}"
    },
    "title" : {
      "text" : ""
    },
    "opposite" : false,
    "reversed" : false,
    "allowDecimals" : true,
    "visible" : true,
    "gridLineWidth" : 1,
    "startOnTick" : false,
    "endOnTick" : false
  },
  "legend" : {
    "enabled" : true,
    "floating" : false
  }
}

**Comment by AAChartModel** [comment]
看了你的这个 json 字符串, 你还应该把 AASeries 的.h 文件和.m 文件中的 keys 属性注释掉看看,这下真的应该就正常了

**Comment by asd6802862** [comment]
是的 终于正常显示了，感谢大佬🙏，具体是哪里出问题了呢，为啥新建工程可以，我这个工程需要注释这个keys字段

**Comment by AAChartModel** [comment]
AAChartKit 的代码中有使用到`runtime`

```objc
#import <objc/runtime.h>

@implementation AAJsonConverter
```

估计是你的项目中的什么配置影响到了带有属性字段为`keys`的实例对象的序列化, 具体是什么原因,说实话这种玄学问题我也懒得查了🤣

**Comment by asd6802862** [comment]
哈哈哈哈  好的 谢谢帮忙解决问题哈
