### ISSUE TITLE
textOutline is not working

### ISSUE THREAD

**Issue by sanjhi** [AAChartModel/AAChartKit#886]
Hi, I am using AAChart for funnel graph in Android application. I managed to put the label inside of funnel but there is a white background in labels, I used this

 ```java
        .dataLabels(new AADataLabels()
            .inside(true)
            .verticalAlign("middle")
            .color("#000000")
            .style(new AAStyle()
                .fontSize(14f)
                .textOutline("")))
```

but the background is still there. I want to removethat background completely. please help. 
Thanks in advance.

**Comment by AAChartModel** [comment]
Styles for the label. default values：
```js
{"color": "contrast",
 "fontSize": "11px", 
"fontWeight": "bold", 
"textOutline": "1px 1px contrast"
 }.
```

So if you want to remove that background completely then you should configure AAStyle like this:

```java
.dataLabels(new AADataLabels()
           .inside(true)
           .verticalAlign("middle")
           .color("#000000")
           .style(new AAStyle()
               .fontSize(14f)
               .textOutline("0px 0px contrast")))
```

**Comment by AAChartModel** [comment]
> I am searching for Funnel Chart graph. I am using MPChart library from a very log time and don't want to switch to any other because it is only library I have seen based on native background else every library supports JS in background that slowdown the app and increase the heap memory size.

Maybe AAChartCore is a bad choice for your project.🤣🤣🤣

**Comment by sanjhi** [comment]
haha, 

> 
> 
> > I am searching for Funnel Chart graph. I am using MPChart library from a very log time and don't want to switch to any other because it is only library I have seen based on native background else every library supports JS in background that slowdown the app and increase the heap memory size.
> 
> ---- refer to [PhilJay/MPAndroidChart#4906](https://github.com/PhilJay/MPAndroidChart/issues/4906)
> 
> Maybe AAChartCore is a bad choice for your project.🤣🤣🤣

haha, what to do buddy, the show must go on. I will get back to you with more queries regarding this library. be ready for new requirements. Hopefully I will join you as a moderator(if you allow).

**Comment by sanjhi** [comment]
> 
> 
> Styles for the label. default values：
> 
> ```js
> {"color": "contrast",
>  "fontSize": "11px", 
> "fontWeight": "bold", 
> "textOutline": "1px 1px contrast"
>  }.
> ```
> 
> So if you want to remove that background completely then you should configure AAStyle like this:
> 
> ```java
> .dataLabels(new AADataLabels()
>            .inside(true)
>            .verticalAlign("middle")
>            .color("#000000")
>            .style(new AAStyle()
>                .fontSize(14f)
>                .textOutline("0px 0px contrast")))
> ```

didn't work. Still same reflects. 
![Screenshot_20200520-121757_FunnelAAChartLIbrary 1](https://user-images.githubusercontent.com/9048643/82416808-4dd91400-9a98-11ea-8391-7caf2cd8e837.jpg)

**Comment by sanjhi** [comment]
Thanks brother, Great job 👍
