### ISSUE TITLE
 OC语言   X 轴不能设置虚线。请教大神

### ISSUE THREAD

**Issue by SaveFree** [AAChartModel/AAChartKit#887]
OC语言   X 轴不能设置虚线。请教大神

**Comment by AAChartModel** [comment]
X轴和 Y轴本身不支持设置成虚线样式,但是支持网格线样式设置为多种类型虚线,参见 AAChartKit-Swift 中的 issue 问题,传送门: https://github.com/AAChartModel/AAChartKit-Swift/issues/206
