### ISSUE TITLE
当Y坐标的值相同时，折线图无法显示，只显示几个点

### ISSUE THREAD

**Issue by BinBear** [AAChartModel/AAChartKit#89]
AAChartView的type类型为：AAChartTypeSpline,当Y坐标的值相同时，折线图无法显示，只显示几个点：
![image](https://user-images.githubusercontent.com/13587915/34317613-8c480efe-e7ed-11e7-8d11-7c022eff3f5d.png)

问题特别急，您能帮我看一下吗，谢谢

**Comment by AAChartModel** [comment]
你的数据具体是什么样子的呢?我这边无法复现你的问题啊?

**Comment by BinBear** [comment]
创建的代码：
![image](https://user-images.githubusercontent.com/13587915/34324315-71007516-e8a9-11e7-94b7-da7b336610f3.png)
我建了一个新工程，测试这个，还是这样，无论是全部0还是全部其他相同数值都这样。真机模拟器都一样，系统是iOS 11.2.1,Xcode 9.2

**Comment by BinBear** [comment]
@AAChartModel 找不到你邮箱，想发一个demo工程给你的

**Comment by BinBear** [comment]
@AAChartModel 我在你的podspec文件中看到了你的18256973864@163.com邮箱，把测试工程发你这个邮箱了

**Comment by AAChartModel** [comment]
兄弟,你可能遇到了一个比较罕见的 highcharts 的一个 bug,当Y坐标的值相同时,你同时还开启了图表的渐变色功能,似乎就会遇到这个问题,只需要将渐变色功能关闭即可.
```objective-c
   //关闭图表渐变色
    self.coinChartModel.gradientColorEnable = NO;
```

**Comment by BinBear** [comment]
@AAChartModel 关闭之后还真是解决了，这个bug太蛋疼了，有没有办法当Y坐标的值相同时,同时开启了图表的渐变色功能也能绘制折线图

**Comment by AAChartModel** [comment]
这个除非当所有数据为0时,让点在分布在 X轴的坐标轴上,而不是像现在这样居中显示,至于其他的,恐怕没有办法了.话说回来,折线图开启渐变色功能感觉也不是很有意义吧

**Comment by puyuk** [comment]
这个除非当所有数据为0时,让点在分布在 X轴的坐标轴上,而不是像现在这样居中显示，  这个如何设置

**Comment by puyuk** [comment]
目前这个问题解决了吗
