### ISSUE TITLE
tooltipSet 

### ISSUE THREAD

**Issue by flyOfYW** [AAChartModel/AAChartKit#891]
<img width="911" alt="image" src="https://user-images.githubusercontent.com/17938752/83509458-0c1b8500-a4fe-11ea-89ae-135f5d0cf630.png">

怎么设置单个的浮动框，没效果的

**Comment by AAChartModel** [comment]
目前暂不支持单个 tooltip 的 formatter 功能

**Comment by flyOfYW** [comment]
@AAChartModel 好吧，我现在遇到的问题是当隐藏另一个的AASeriesElement时候，在点击一个AASeriesElement 的时候tooltip，就不显示了，
![1591085900865776](https://user-images.githubusercontent.com/17938752/83513141-e8f3d400-a503-11ea-9e75-7b3fd36e3a70.gif)

**Comment by AAChartModel** [comment]
你的 tooltip 的 formatter 是怎么配置的? 贴一下代码看看(不要截图)

**Comment by flyOfYW** [comment]
- (void)updateModel:(HGHomeNoticeModel *)model{
    
    if (!_chartModel) {

        AAChartModel *aaChartModel =  AAChartModel.new
        .chartTypeSet(AAChartTypeLine)//图表类型随机
        .titleSet(model.name)
        .subtitleSet(@"")
        .xAxisVisibleSet(true)
        
        .xAxisCrosshairColorSet(@"#666666")//浅石板灰准星线
        .xAxisCrosshairDashStyleTypeSet(AAChartLineDashStyleTypeSolid)
        .xAxisCrosshairWidthSet(@1)//Zero width to disable crosshair by default
        .xAxisLabelsFontSizeSet(@10)
        
        .markerSymbolStyleSet(AAChartSymbolStyleTypeInnerBlank)
        
        .categoriesSet(model.categoriesList)
        
        
        
        .yAxisVisibleSet(true)
        .yAxisTitleSet(@"")
        .yAxisLabelsFontSizeSet(@10)
        
        .colorsThemeSet(@[@"#2FC2EB",@"#0088FF"])
        .seriesSet([self configureSeriesWith:model])
        
        .yAxisLineWidthSet(@1)//Y轴轴线线宽为0即是隐藏Y轴轴线
        
        ;
        
        AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
        

        _chartModel = aaChartModel;
        

                aaOptions.tooltip
                .useHTMLSet(true)
                .formatterSet(@AAJSFunc(function () {
                    var s = '<b>' +  this.x + '</b>' + '<br/>';
                    let colorDot1 = '<span style=\"' + 'color:#2FC2EB; font-size:13px\"' + '>◉</span> ';
                    let colorDot2 = '<span style=\"' + 'color:#0088FF; font-size:13px\"' + '>◉</span> ';
        //            let s1 = colorDot1  + this.points[0].series.name + ': ' + this.points[0].y + '%' + '<br/>';
                    let s1 = colorDot1  + '车流量' + ': ' + this.points[0].y + '%' + '<br/>';
                    let s2 =  colorDot2 + '金额' + ': ' + this.points[1].y + '%';
                    s += s1 + s2;
                    return s;
                }))
                .valueDecimalsSet(@2)//设置取值精确到小数点后几位
                .backgroundColorSet(@"#000000")
                .borderColorSet(@"#000000")
                .styleSet(AAStyle.new
                          .colorSet(@"#FFD700")
                          .fontSizeSet(@"12px"));

        
        [_aaChartView aa_drawChartWithOptions:aaOptions];
    }else{
        [_aaChartView aa_onlyRefreshTheChartDataWithChartModelSeries:[self configureSeriesWith:model] animation:YES];
    }
    
}
- (NSArray *)configureSeriesWith:(HGHomeNoticeModel *)model {
    NSMutableArray *see = [NSMutableArray new];
    for (HGSerieItemModel *seItem in model.seriesArr) {
        AASeriesElement *seModel = AASeriesElement.new
        .nameSet(seItem.name)
        .dataSet(seItem.data);
        [see addObject:seModel];
        
    }
    return see.copy;
}

能加个qq吗

**Comment by flyOfYW** [comment]
@AAChartModel 我的写法有问题吗

**Comment by AAChartModel** [comment]
参考 issue https://github.com/AAChartModel/AAChartKit/issues/647

**Comment by flyOfYW** [comment]
@AAChartModel 

(void)updateModel:(HGHomeNoticeModel *)model{

if (!_chartModel) {

  AAChartModel *aaChartModel =  AAChartModel.new
  .chartTypeSet(AAChartTypeLine)//图表类型随机
  .titleSet(model.name)
  .subtitleSet(@"")
  .xAxisVisibleSet(true)
  
  .xAxisCrosshairColorSet(@"#666666")//浅石板灰准星线
  .xAxisCrosshairDashStyleTypeSet(AAChartLineDashStyleTypeSolid)
  .xAxisCrosshairWidthSet(@1)//Zero width to disable crosshair by default
  .xAxisLabelsFontSizeSet(@10)
  
  .markerSymbolStyleSet(AAChartSymbolStyleTypeInnerBlank)
  
  .categoriesSet(model.categoriesList)
  
  
  
  .yAxisVisibleSet(true)
  .yAxisTitleSet(@"")
  .yAxisLabelsFontSizeSet(@10)
  
  .colorsThemeSet(@[@"#2FC2EB",@"#0088FF"])
  .seriesSet([self configureSeriesWith:model])
  
  .yAxisLineWidthSet(@1)//Y轴轴线线宽为0即是隐藏Y轴轴线
  
  ;
  
  AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
  

  _chartModel = aaChartModel;
  

          aaOptions.tooltip
          .useHTMLSet(true)
          .formatterSet(@AAJSFunc(function () {
              var s = '<b>' +  this.x + '</b>' + '<br/>';
              let colorDot1 = '<span style=\"' + 'color:#2FC2EB; font-size:13px\"' + '>◉</span> ';
              let colorDot2 = '<span style=\"' + 'color:#0088FF; font-size:13px\"' + '>◉</span> ';
  //            let s1 = colorDot1  + this.points[0].series.name + ': ' + this.points[0].y + '%' + '<br/>';
              let s1 = colorDot1  + '车流量' + ': ' + this.points[0].y + '%' + '<br/>';
              let s2 =  colorDot2 + '金额' + ': ' + this.points[1].y + '%';
              s += s1 + s2;
              return s;
          }))
          .valueDecimalsSet(@2)//设置取值精确到小数点后几位
          .backgroundColorSet(@"#000000")
          .borderColorSet(@"#000000")
          .styleSet(AAStyle.new
                    .colorSet(@"#FFD700")
                    .fontSizeSet(@"12px"));

  
  [_aaChartView aa_drawChartWithOptions:aaOptions];
}else{
[_aaChartView aa_onlyRefreshTheChartDataWithChartModelSeries:[self configureSeriesWith:model] animation:YES];
}

}

(NSArray *)configureSeriesWith:(HGHomeNoticeModel *)model {
NSMutableArray *see = [NSMutableArray new];
for (HGSerieItemModel *seItem in model.seriesArr) {
AASeriesElement *seModel = AASeriesElement.new
.nameSet(seItem.name)
.dataSet(seItem.data);
[see addObject:seModel];

}
return see.copy;
}

**Comment by AAChartModel** [comment]
issue #647 的示例代码我已进行了相关的优化,解决了和你的这种情况相同的问题. 

原示例代码中的 formatter 我已进行了相应的改动,如下

```js
    .formatterSet(@AAJSFunc(function () {
        var s = '第' + '<b>' +  this.x + '</b>' + '年' + '<br/>';
        let colorDot1 = '<span style=\"' + 'color:red; font-size:13px\"' + '>◉</span> ';
        let colorDot2 = '<span style=\"' + 'color:blue; font-size:13px\"' + '>◉</span> ';
        var s1;
        var s2;
        let pointsNum = this.points.length;
        if (pointsNum === 1) {
            console.log(this);
            var selectedPoint = this.points[0];
            var selectedPointIndex = selectedPoint.series.index;
            if (selectedPointIndex === 0) {
                s1 = colorDot1  + selectedPoint.series.name + ': ' + selectedPoint.y + '只' + '<br/>';
                s2 = "";
            } else if (selectedPointIndex === 1) {
                s1 = "";
                s2 =  colorDot2 + selectedPoint.series.name + ': ' + selectedPoint.y + '棵';
            }
        } else {
            s1 = colorDot1  + this.points[0].series.name + ': ' + this.points[0].y + '只' + '<br/>';
            s2 =  colorDot2 + this.points[1].series.name + ': ' + this.points[1].y + '棵';
        }
        s += s1 + s2;
        return s;
    }))
```

对比之前的代码,你会发现,我之前的代码和你现在一样,没有对AASeriesElement隐藏之后,进行相应的逻辑处理.

**Comment by AAChartModel** [comment]
tooltip的 formatter 的相关 API 参见 Highcharts 官方文档 
 https://api.highcharts.com.cn/highcharts#tooltip.formatter

**Comment by flyOfYW** [comment]
@AAChartModel 谢谢了，这个问题解决了，能设置默认显示tooltip吗，我下午了看下文档和代码，说要模拟一个焦点事件，才可以显示，代码不懂怎么写？还有我设置_aaChartView.backgroundColor和document.getElementById('container').style.backgroundColor，背景色也没有变化

**Comment by AAChartModel** [comment]
改变背景色，应该通过AAChartModel 的背景色属性来进行更改

**Comment by flyOfYW** [comment]
那设置默认显示tooltip的呢，怎么设置

**Comment by AAChartModel** [comment]
兄弟你的QQ号多少来着？

**Comment by flyOfYW** [comment]
1498627884

**Comment by AAChartModel** [comment]
> 那设置默认显示tooltip的呢，怎么设置

参考问题 #892

**Comment by AAChartModel** [comment]
昨天的 formatter 示例有一点点问题, 正确的应该是

```js
    .formatterSet(@AAJSFunc(function () {
        var s = '第' + '<b>' +  this.x + '</b>' + '年' + '<br/>';
        let colorDot1 = '<span style=\"' + 'color:red; font-size:13px\"' + '>◉</span> ';
        let colorDot2 = '<span style=\"' + 'color:blue; font-size:13px\"' + '>◉</span> ';
        var s1;
        var s2;
        let pointsNum = this.points.length;
        if (pointsNum === 1) {
            let selectedPoint = this.points[0];
            var selectedPointIndex = selectedPoint.series.index;
            if (selectedPointIndex === 0) {
                s1 = colorDot1  + selectedPoint.series.name + ': ' + selectedPoint.y + '只';
                s2 = "";
            } else if (selectedPointIndex === 1) {
                s1 = "";
                s2 =  colorDot2 + selectedPoint.series.name + ': ' + selectedPoint.y + '棵';
            }
        } else {
            let selectedPoint0 = this.points[0];
            let selectedPoint1 = this.points[1];
            s1 = colorDot1  + selectedPoint0.series.name + ': ' + selectedPoint0.y + '只' + '<br/>';
            s2 =  colorDot2 + selectedPoint1.series.name + ': ' + selectedPoint1.y + '棵';
        }
        s += s1 + s2;
        return s;
    }))
```

参见我此次提交 https://github.com/AAChartModel/AAChartKit/commit/12ca37285b32b6d2040894f75848cbabb5720889 的修改.  主要删除了 `console.log(this);` 无用的控制台输出代码和 selectedPoint1的取值代码 `this.points[1]`

**Comment by flyOfYW** [comment]
感谢大佬指导，问题得以解决

**Comment by AAChartModel** [comment]
> 感谢大佬指导，问题得以解决

莫要谦虚, 久闻公之大名,今日有幸相会. 🤣  你的 [YWExcel](https://github.com/flyOfYW/YWExcel)  后面有机会我应该也会用到😁

**Comment by flyOfYW** [comment]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/17938752/83615391-1189d580-a5b9-11ea-9588-0cbdd7bd2903.png">
大佬，这个虽然是默认出来，但是缺少跟竖线，有个小瑕疵

**Comment by AAChartModel** [comment]
> 但是缺少跟竖线，有个小瑕疵

这个恐怕真搞不定了, 这个需要 crosshair 追星线的相关 API,但是在官方文档中貌似真的没找到.

或许换个思路, 如你所说的模拟一个焦点事件, 这个我就更不知道怎么弄了🤷‍♀️🤷‍♀️🤷‍♀️

**Comment by flyOfYW** [comment]
嗯， crosshair好像目前的api只有设置样式之类的，没有设置x坐标相关的api
