### ISSUE TITLE
为什么升级最新代码之后，使用AAOptions设置dataLabels的属性没有作用了

### ISSUE THREAD

**Issue by HarveyVey** [AAChartModel/AAChartKit#896]
blueOptions.plotOptions.areaspline.dataLabels.enabled = YES;
blueOptions.plotOptions.areaspline.dataLabels.color = @"#ffffff";
blueOptions.plotOptions.areaspline.dataLabels.backgroundColor = AAColor.clearColor;
blueOptions.plotOptions.areaspline.dataLabels.borderColor = AAColor.clearColor;
blueOptions.plotOptions.areaspline.dataLabels.borderWidth = @0;
blueOptions.plotOptions.areaspline.dataLabels.allowOverlap = YES;
blueOptions.plotOptions.areaspline.dataLabels.style.textOutline = @"0px 0px contrast";
blueOptions.plotOptions.areaspline.dataLabels.style.color = @"#ffffff";

之前我设置的这些属性都是有作用的

**Comment by AAChartModel** [comment]
改为 

```objc
blueOptions.plotOptions.series.dataLabels.enabled = YES;
blueOptions.plotOptions.series.dataLabels.color = @"#ffffff";
blueOptions.plotOptions.series.dataLabels.backgroundColor = AAColor.clearColor;
blueOptions.plotOptions.series.dataLabels.borderColor = AAColor.clearColor;
blueOptions.plotOptions.series.dataLabels.borderWidth = @0;
blueOptions.plotOptions.series.dataLabels.allowOverlap = YES;
blueOptions.plotOptions.series.dataLabels.style.textOutline = @"0px 0px contrast";
blueOptions.plotOptions.series.dataLabels.style.color = @"#ffffff";
```

即可

**Comment by HarveyVey** [comment]
> 改为
> 
> ```objc
> blueOptions.plotOptions.series.dataLabels.enabled = YES;
> blueOptions.plotOptions.series.dataLabels.color = @"#ffffff";
> blueOptions.plotOptions.series.dataLabels.backgroundColor = AAColor.clearColor;
> blueOptions.plotOptions.series.dataLabels.borderColor = AAColor.clearColor;
> blueOptions.plotOptions.series.dataLabels.borderWidth = @0;
> blueOptions.plotOptions.series.dataLabels.allowOverlap = YES;
> blueOptions.plotOptions.series.dataLabels.style.textOutline = @"0px 0px contrast";
> blueOptions.plotOptions.series.dataLabels.style.color = @"#ffffff";
> ```
> 
> 即可

多谢
