### ISSUE TITLE
两个y轴一正一副，可以共用一个0点么

### ISSUE THREAD

**Issue by MrDZ** [AAChartModel/AAChartKit#899]

**Comment by AAChartModel** [comment]
"共用一个0点"指的是什么?

**Comment by MrDZ** [comment]
> "共用一个0点"指的是什么?
就是把两个y轴合成一个，共用一个坐标0点。
目前要实现的效果就是demo里的镜像柱状图，但是要求正负值是两种不同的刻度。

**Comment by MrDZ** [comment]
![61591671250_ pic](https://user-images.githubusercontent.com/13479669/84100981-92c0ec80-aa3f-11ea-9ce5-16217f7332d6.jpg)
这种效果

**Comment by AAChartModel** [comment]
参见 https://github.com/AAChartModel/AAChartKit/issues/759#issuecomment-544848782

**Comment by MrDZ** [comment]
我看代码了， 那个方法相当于没用第二个y轴的值呀，只用了一个titlelabel。我想用不同的值。。。。
