### ISSUE TITLE
选中之后的样式可否开放修改

### ISSUE THREAD

**Issue by liushong** [AAChartModel/AAChartKit#9]
把`AAPlotOptions`的.radius设为@0之后数据节点没有了，选中之后的样式可否修改？
![now](https://cloud.githubusercontent.com/assets/12842023/25166181/a4a7adc8-250c-11e7-8ab8-523ff74b14f2.png)

**Comment by liushong** [comment]
![qq20170419-144848](https://cloud.githubusercontent.com/assets/12842023/25166730/51feded6-250f-11e7-9f8d-60685ba3b525.png)
想做成这个样式

**Comment by AAChartModel** [comment]
现已为 `AAChartModel` 添加了新的 BOOL值属性`pointHollow`,您只需要布尔值为 YES, 便可得到您想要的效果(折线的连接点为空心的)

**Comment by AAChartModel** [comment]
以下为`AAChartModel` 的 **BOOL** 值属性`pointHollow`设置为 YES 之后的示例效果图
