### ISSUE TITLE
执行js崩溃

### ISSUE THREAD

**Issue by ChandHsu** [AAChartModel/AAChartKit#906]
<img width="1177" alt="WeChat15d00b96f953cb5c09f16cda22f65909" src="https://user-images.githubusercontent.com/10771362/84344180-a9507a80-abdc-11ea-8b02-b2c44f48fd92.png">
下面是设置(dataSet)的时候，产生崩溃的区别图：

![Xnip2020-06-11_12-18-09](https://user-images.githubusercontent.com/10771362/84344614-d2bdd600-abdd-11ea-8865-f414d54e92c5.png)
![Xnip2020-06-11_12-18-30](https://user-images.githubusercontent.com/10771362/84344616-d4879980-abdd-11ea-8d47-b7b05369d2ae.png)
怪异！

**Comment by ChandHsu** [comment]
![Xnip2020-06-11_12-18-09](https://user-images.githubusercontent.com/10771362/84344650-ecf7b400-abdd-11ea-8a7d-22d262e417b0.png)
![Xnip2020-06-11_12-18-30](https://user-images.githubusercontent.com/10771362/84344656-eff2a480-abdd-11ea-9e8f-fa82d6d7e1f3.png)

**Comment by AAChartModel** [comment]
`dataSet()` 只支持这种 NSNumber 类型

```objc
        .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6]),

```

**Comment by ChandHsu** [comment]
好的，谢谢
