### ISSUE TITLE
折线图绘制点可以X轴不从0开始吗

### ISSUE THREAD

**Issue by youshuo** [AAChartModel/AAChartKit#907]
折线图绘制点可以从任一一点开始吗，比如（2，3），（4，6）我第一个点的X轴坐标可以自定义

**Comment by AAChartModel** [comment]
折线图支持这种坐标形式的 data 值类型.


![image](https://user-images.githubusercontent.com/16357599/84480772-ad0cfb80-acc7-11ea-96f3-0c49e87951a7.png)

如上图所示的线性回归图中的折线, 

```objc
    return AAChartModel.new
    .chartTypeSet(AAChartTypeLine)
    .markerSymbolStyleSet(AAChartSymbolStyleTypeInnerBlank)
    .markerRadiusSet(@13)
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"观测值")
        .dataSet(valuesArr),
        AASeriesElement.new
        .typeSet(AAChartTypeLine)
        .nameSet(@"线性回归线")
        .dataSet(@[@[@0.014, @3.078], @[@0.969, @4.655]])
        .colorSet((id)AAGradientColor.sanguineColor)
        .lineWidthSet(@4)
        .markerSet(AAMarker.new.radiusSet(@0)),
    ]);
```

如代码所示,`.dataSet(@[@[@0.014, @3.078], @[@0.969, @4.655]])
` 设置 data 数组值的数据结构为这种坐标点形式即可. 详尽内容参见 AAChartKit 的 demo 中的混合图表示例中的折线图混合散点图示例代码

**Comment by youshuo** [comment]
就是有多条线段，有些线段x值从0开始，有些线段x值从任意值开始



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An An"<notifications@github.com&gt;; 
发送时间: 2020年6月12日(星期五) 下午4:17
收件人: "AAChartModel/AAChartKit"<AAChartKit@noreply.github.com&gt;; 
抄送: "王元"<916853591@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AAChartModel/AAChartKit] 折线图绘制点可以X轴不从0开始吗 (#907)





 
折线图支持这种坐标形式的 data 值类型.
 

 
如上图所示的线性回归图中的折线,
     return AAChartModel.new     .chartTypeSet(AAChartTypeLine)     .markerSymbolStyleSet(AAChartSymbolStyleTypeInnerBlank)     .markerRadiusSet(@13)     .seriesSet(@[         AASeriesElement.new         .nameSet(@"观测值")         .dataSet(valuesArr),         AASeriesElement.new         .typeSet(AAChartTypeLine)         .nameSet(@"线性回归线")         .dataSet(@[@[@0.014, @3.078], @[@0.969, @4.655]])         .colorSet((id)AAGradientColor.sanguineColor)         .lineWidthSet(@4)         .markerSet(AAMarker.new.radiusSet(@0)),     ]);
 
如代码所示,.dataSet(@[@[@0.014, @3.078], @[@0.969, @4.655]])  设置 data 数组值的数据结构为这种坐标点形式即可. 详尽内容参见 AAChartKit 的 demo 中的混合图表示例中的折线图混合散点图示例代码

**Comment by youshuo** [comment]
非常感谢，明白啦






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"An An"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 下午4:17
收件人:&nbsp;"AAChartModel/AAChartKit"<AAChartKit@noreply.github.com&gt;;
抄送:&nbsp;"王元"<916853591@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartKit] 折线图绘制点可以X轴不从0开始吗 (#907)





 
折线图支持这种坐标形式的 data 值类型.
 

 
如上图所示的线性回归图中的折线,
     return AAChartModel.new     .chartTypeSet(AAChartTypeLine)     .markerSymbolStyleSet(AAChartSymbolStyleTypeInnerBlank)     .markerRadiusSet(@13)     .seriesSet(@[         AASeriesElement.new         .nameSet(@"观测值")         .dataSet(valuesArr),         AASeriesElement.new         .typeSet(AAChartTypeLine)         .nameSet(@"线性回归线")         .dataSet(@[@[@0.014, @3.078], @[@0.969, @4.655]])         .colorSet((id)AAGradientColor.sanguineColor)         .lineWidthSet(@4)         .markerSet(AAMarker.new.radiusSet(@0)),     ]);
 
如代码所示,.dataSet(@[@[@0.014, @3.078], @[@0.969, @4.655]])  设置 data 数组值的数据结构为这种坐标点形式即可. 详尽内容参见 AAChartKit 的 demo 中的混合图表示例中的折线图混合散点图示例代码
