### ISSUE TITLE
aaOptions.plotOptions.series.events = 这个事件怎么使用

### ISSUE THREAD

**Issue by youshuo** [AAChartModel/AAChartKit#908]
aaOptions.plotOptions.series.events = 这个事件怎么使用
想自定义下点击事件

**Comment by AAChartModel** [comment]
AAChartView 支持点击事件,例如

```objc
    //获取图表上的手指点击及滑动事件
    [_aaChartView moveOverEventHandler:^(AAChartView *aaChartView,
                                         AAMoveOverEventMessageModel *message) {
        NSDictionary *messageDic = @{
            @"category":message.category,
            @"index":@(message.index),
            @"name":message.name,
            @"offset":message.offset,
            @"x":message.x,
            @"y":message.y
        };
        
        NSString *str1 = [NSString stringWithFormat:@"👌👌👌👌 selected point series element name: %@\n",
                          message.name];
        NSString *str2 = [NSString stringWithFormat:@"user finger moved over!!!,get the move over event message: %@",
                          messageDic];
        NSLog(@"%@%@",str1, str2);
    }];
```

更多详细内容参见 AAChartKit 中的点击事件的示例代码

**Comment by youshuo** [comment]
这个好像不起作用呀



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An An"<notifications@github.com&gt;; 
发送时间: 2020年6月16日(星期二) 上午10:16
收件人: "AAChartModel/AAChartKit"<AAChartKit@noreply.github.com&gt;; 
抄送: "王元"<916853591@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AAChartModel/AAChartKit] aaOptions.plotOptions.series.events = 这个事件怎么使用 (#908)





 
AAChartView 支持点击事件,例如
     //获取图表上的手指点击及滑动事件     [_aaChartView moveOverEventHandler:^(AAChartView *aaChartView,                                          AAMoveOverEventMessageModel *message) {         NSDictionary *messageDic = @{             @"category":message.category,             @"index":@(message.index),             @"name":message.name,             @"offset":message.offset,             @"x":message.x,             @"y":message.y         };                  NSString *str1 = [NSString stringWithFormat:@"👌👌👌👌 selected point series element name: %@\n",                           message.name];         NSString *str2 = [NSString stringWithFormat:@"user finger moved over!!!,get the move over event message: %@",                           messageDic];         NSLog(@"%@%@",str1, str2);     }];
 
更多详细内容参见 AAChartKit 中的点击事件的示例代码

**Comment by AAChartModel** [comment]
> 这个好像不起作用呀 

应该是你使用方式的问题,你看 demo 中的图表,手指触摸或滑动的时候,控制台是有信息输出的

**Comment by AAChartModel** [comment]
注意设置AAChartModel 的属性

```objc
    .touchEventEnabledSet(true)//支持用户点击事件
```
