### ISSUE TITLE
折线图点上获取的数据回调

### ISSUE THREAD

**Issue by Chauvetok** [AAChartModel/AAChartKit#920]
你好，当我点击折线图上时，能否取到对应的提示框中的数据？？感谢

**Comment by AAChartModel** [comment]
重复问题,参见  #810 及 AAChartKit 中点击事件相关的 demo 代码.

**Comment by Chauvetok** [comment]
> 重复问题,参见 #810 及 AAChartKit 中点击事件相关的 demo 代码.

感谢大佬回复，用delegate和block都可以，我直接用delegate获取到了。
