### ISSUE TITLE
作者您好，AAChartTypeBar类型下设置AAChartModel的inverted属性为true失效

### ISSUE THREAD

**Issue by Jins-org** [AAChartModel/AAChartKit#923]
经测试之前的demo中没有问题，最新的demo是不生效的

**Comment by Jins-org** [comment]
demo中选中Basic Type---基础类型的第二个demo：Bar Chat---条形图，点击下方的switch：xAxisInverted

**Comment by AAChartModel** [comment]
https://api.highcharts.com.cn/highcharts#chart.inverted

> 如果图表中出现条形图系列，则会自动反转

**Comment by Jins-org** [comment]
已使用column类型代替
