### ISSUE TITLE
折线描绘错误

### ISSUE THREAD

**Issue by XQZZZ** [AAChartModel/AAChartKit#925]
![企业微信截图_b467b582-0c5e-4686-8831-ae6ee441c1af](https://user-images.githubusercontent.com/22762279/86464084-5a23e280-bd61-11ea-99c4-a458da36124a.png)
您好，麻烦您看看这是哪里的问题，国内的数据和国外的数据是比总数小的，描绘的点反而在顶部，Y轴的值也是不对的，总数最大也没有10000。急需，谢谢！
![企业微信截图_ee022218-4a9e-4380-8727-43784d1de1d8](https://user-images.githubusercontent.com/22762279/86464903-1e8a1800-bd63-11ea-8bc2-3c19c38d1064.png)

**Comment by AAChartModel** [comment]
你应该是设置了图表の样式为堆叠效果，取消堆叠效果即可。  堆叠属性为stacking

**Comment by AAChartModel** [comment]
你的代码应该是直接拷贝了demo中的代码，注意查看每个属性的作用，并不是所有属性对你的项目都是合适的
