### ISSUE TITLE
Method for programatically selecting a point in a series element?

### ISSUE THREAD

**Issue by inb4ohnoes** [AAChartModel/AAChartKit#932]
Is there a way to programatically select a point in a series element or an index to emulate a tap selection? Something like:

`- (void)aa_selectIndex:(NSUInteger)index forSeriesElementIndex:(NSUInteger)elementIndex`

If there is, can you point me to it? I may have overlooked it. Thanks!

**Comment by AAChartModel** [comment]
sorry , Highcharts do not support this kind of method

**Comment by inb4ohnoes** [comment]
Does this not work the way I'm thinking? https://api.highcharts.com.cn/highcharts#Point.select
