### ISSUE TITLE
有内存泄漏

### ISSUE THREAD

**Issue by PPLLock** [AAChartModel/AAChartKit#935]
关闭展示页面后内存不释放

**Comment by AAChartModel** [comment]
此问题已修复, 最新的 demo 中页面关闭debug 模式下会有打印信息,信息如下:

```objc
2020-07-15 13:54:29.584058+0800 AAChartKitDemo[44115:4667015] -------> AAChartView.m [Line 621] 
👻👻👻 AAChartView was destroyed!!!
```

**Comment by AAChartModel** [comment]
```pod
pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'
```

CocoaPods 执行以上命令,使用最新内容的 AAChartKit 即可.

**Comment by PPLLock** [comment]
好的，谢谢您



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: An An <notifications@github.com&gt;
发送时间: 2020年7月15日 13:58
收件人: AAChartModel/AAChartKit <AAChartKit@noreply.github.com&gt;
抄送: PPLLock <523439877@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[AAChartModel/AAChartKit] 有内存泄漏 (#935)





 pod 'AAChartKit', :git =&gt; 'https://github.com/AAChartModel/AAChartKit.git'
 
CocoaPods 执行以上命令,使用最新内容的 AAChartKit 即可.

**Comment by PPLLock** [comment]
好的，感谢
