### ISSUE TITLE
希望支持浮窗title和X轴内容自定义  不再是同一个数据

### ISSUE THREAD

**Issue by wangxihu** [AAChartModel/AAChartKit#94]
希望支持浮窗日期和X轴内容自定义   
x轴内容多了真不好看
<img width="372" alt="2017-12-26 8 09 13" src="https://user-images.githubusercontent.com/17714868/34356518-59718364-ea79-11e7-9d58-1162b60cfa29.png">

**Comment by AAChartModel** [comment]
如 X 轴数据内容过多,可选择直接隐藏 X 轴

**Comment by wangxihu** [comment]
好的吧  感谢回复
