### ISSUE TITLE
请问如何对AAChartModel进行本地存储

### ISSUE THREAD

**Issue by YoungXKing** [AAChartModel/AAChartKit#943]
aachartmodel好像没有实现coding协议，无法用归档来存储，请问有什么本地存储的方案吗？

**Comment by AAChartModel** [comment]
存储 AAChartModel 与在 Objective-C 中存储其他 Model 类数据并无不同,将其转换为 NSDictionary 然后序列化存储, 或者在支持存储 Model 类的数据库中存储,又或其他类型的存储方式均可.
