### ISSUE TITLE
请问是否可以单独把准星线拿出来使用

### ISSUE THREAD

**Issue by YoungXKing** [AAChartModel/AAChartKit#955]
就是不使用AAChartKit，单独在自定义view里绘制虚线的时候，使用AACrossHair来按AAChartLineDashStyleType绘制虚线

**Comment by AAChartModel** [comment]
不太清楚你的需求是什么,如果你希望在 iOS 的 UIView 中而不借助 AAChartView 来单独使用AACrossHair应该是不现实的

**Comment by YoungXKing** [comment]
> 不太清楚你的需求是什么,如果你希望在 iOS 的 UIView 中而不借助 AAChartView 来单独使用AACrossHair应该是不现实的

好的，我就是这样的需求，我再想其他办法吧，谢谢！
