### ISSUE TITLE
AATooltip箭头的方向是怎么指定的

### ISSUE THREAD

**Issue by CoderWeiLee** [AAChartModel/AAChartKit#957]
AATooltip箭头的方向是怎么指定的，在头文件中没看到可以设置的属性

**Comment by AAChartModel** [comment]
> 数据点提示框的形状名称。在Highcharts 3.x 以及更早的版本，提示框的形状是 square。 默认是：callout.

https://api.highcharts.com.cn/highcharts#tooltip.shape

这是默认的效果,要么是方框形的,要么是对话框形的, 似乎并没有什么自定义设置样式的功能
