### ISSUE TITLE
AATooltip浮动提示框

### ISSUE THREAD

**Issue by CoderWeiLee** [AAChartModel/AAChartKit#960]
AATooltip浮动提示框怎么去除左右滑动的时候箭头下出现的小圆点，以及浮动框中出现的X轴文字内容。（比如x轴是`六月`, 那么浮动提示框会显示`六月

                                   ·空气湿度`） 这样子

**Comment by AAChartModel** [comment]
自定义 Tooltip 的属性 `pointFormat` 即可

https://api.highcharts.com.cn/highcharts#tooltip.pointFormat

**Comment by AAChartModel** [comment]
相关属性还有 

```js
footerFormat: 尾部格式化字符串
formatter: 格式化回调函数
headerFormat
```

**Comment by CoderWeiLee** [comment]
嗯设置了确实可以，但是浮动框上怎么会有一条竖直的线呀，然后拖动到某个连接点的时候，自动出现的那个圆我也去不掉，有什么办法吗

**Comment by AAChartModel** [comment]
> 但是浮动框上怎么会有一条竖直的线呀

参见 https://github.com/AAChartModel/AAChartKit/issues/382

**Comment by AAChartModel** [comment]
> 自动出现的那个圆我也去不掉

参见 https://github.com/AAChartModel/AAChartKit/issues/909

**Comment by CoderWeiLee** [comment]
非常感谢坐着！圆形已经去除了，那条线还在，可能是我别的设置引起的，我再排查一下。非常感谢

**Comment by AAChartModel** [comment]
十字准星线相关 API 在线文档:

https://api.highcharts.com.cn/highcharts#xAxis.crosshair
