### ISSUE TITLE
数据为0时线不在X轴上

### ISSUE THREAD

**Issue by lzz212** [AAChartModel/AAChartKit#961]
我设置的Y轴的yAxisTickInterval(10)
没有设置y的最小最大值，此时y=0时不是贴近X轴，而是在中间

**Comment by AAChartModel** [comment]
AAChartKit 的 demo中有示例

**Comment by AAChartModel** [comment]
参见 https://github.com/AAChartModel/AAChartKit/issues/773#issuecomment-568376674

![](https://user-images.githubusercontent.com/16357599/71340970-70234000-2593-11ea-8e22-aa33e51aa89e.png)
