### ISSUE TITLE
这种tooltip怎么实现，一值在最上方

### ISSUE THREAD

**Issue by wuxuezhen** [AAChartModel/AAChartKit#966]
![image](https://user-images.githubusercontent.com/31502945/89756798-179ab600-db16-11ea-9776-c095fcda05a8.png)

**Comment by wuxuezhen** [comment]
![image](https://user-images.githubusercontent.com/31502945/89756905-53ce1680-db16-11ea-9d40-a7b406204475.png)

**Comment by AAChartModel** [comment]
https://api.highcharts.com.cn/highcharts#tooltip.positioner

不知道你需要的是不是这种效果

**Comment by wuxuezhen** [comment]
有点类似，点击或滑动时会左右移动，高度固定

**Comment by AAChartModel** [comment]
如下配置 tooltip 的 positioner 函数即可

```js

Highcharts.chart('container', {
chart:{
type:"column"
},
    title: {
        text: 'Custom tooltip positioner function'
    },

    tooltip: {
    distance: 100,
        positioner: function (labelWidth, labelHeight, point) {
            return { x: point.plotX, y: 50 };
        }, 
    },

    xAxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    },

    series: [{
        data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
    },]
});
```

**Comment by AAChartModel** [comment]
不过AAChartKit暂未支持这个功能，稍等一会儿，明天之前添加此功能，到时再给你答复

**Comment by wuxuezhen** [comment]
好的，十分感谢

**Comment by AAChartModel** [comment]
## 配置 AAOptions 实例对象

```objc
- (AAOptions *)customTooltipPostionerFunction {
    NSArray *categoriesArr = @[
        @"孤岛危机",
        @"使命召唤",
        @"荣誉勋章",
        @"狙击精英",
        @"神秘海域",
        @"最后生还者",
        @"巫师3狂猎",
        @"对马之魂",
        @"蝙蝠侠阿甘骑士",
        @"地狱边境",
        @"闪客",
        @"忍者之印"
    ];
    
    AAChartModel *aaChartModel = AAChartModel.new
    .chartTypeSet(AAChartTypeColumn)
    .categoriesSet(categoriesArr)
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"单机大作")
        .colorSet(AAColor.redColor)
        .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6])
               ])
    ;
    
    AAOptions *aaOptions = [AAOptionsConstructor configureChartOptionsWithAAChartModel:aaChartModel];
    
    aaOptions.tooltip
    .positionerSet(@AAJSFunc(function (labelWidth, labelHeight, point) {
        let position = {};
        position["x"] = point.plotX;
        position["y"] = 20;
        return position;
    }));
    
    return aaOptions;
}
```

## 图表效果

![image](https://user-images.githubusercontent.com/16357599/89763108-69e2d380-db24-11ea-8564-f5b6e5c533de.png)

**Comment by AAChartModel** [comment]
```ruby
pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'

```

如上使用 pod 更新 AAChartKit 至最新内容即可.

**Comment by wangxihu** [comment]
当我加上：
    //浮动提示框的的位置设置
    aaTooltip.positionerSet(@AAJSFunc(function (labelWidth, labelHeight, point) {
       let position = {};
        position["x"] = point.plotX;
        position["y"] = 20;
        return position;
    }));
   这段代码后崩溃，有时run不会崩溃但是悬浮窗不会跟着手指滑动而滑动（模拟器没有崩溃也没有悬浮窗不会滑动）。

崩溃代码片段：
@implementation AAJsonConverter

+ (NSDictionary*)dictionaryWithObjectInstance:(id)objc {
    unsigned int propsCount;
    objc_property_t *props = class_copyPropertyList([objc class], &propsCount);
    NSMutableDictionary *propsDic = [NSMutableDictionary dictionaryWithCapacity:propsCount];

    for (NSUInteger i = 0; i < propsCount; i++) {
        objc_property_t prop = props[i];
        NSString *propName = [NSString stringWithUTF8String:property_getName(prop)];
        id value = [objc valueForKey:propName];
        if (value == nil) {
            value = [NSNull null];
            continue;
        } else {
            value = [self getObjectInternal:value];
        }
        propsDic[propName] = value;
    }
    free(props);
    
    return propsDic;
}
     id value = [objc valueForKey:propName];崩在了这句话



模拟器打印josn：
    "positioner" : "(function (labelWidth, labelHeight, point) { let position = {}; position[\\\"x\\\"] = point.plotX; position[\\\"y\\\"] = 20; return position; })",

真机打印josn：
    "positioner" : {
      "cursor" : "pointer",
      "fontSize" : "13px",
      "fontWeight" : "thin",
      "color" : "#0088FF"
    },

是不是oc里面不支持上面悬浮窗的写法

**Comment by AAChartModel** [comment]
@wangxihu 估计还是你的AAChartModel 转换 AAOptions 的问题. 你最好是按照 demo 中给的示例的方式来配置 AAOptions

**Comment by AAChartModel** [comment]
> 是不是oc里面不支持上面悬浮窗的写法



我的示例代码本身就是 Objective-C 的所以不太可能是你说的这种问题

**Comment by wangxihu** [comment]
.positionerSet(@AAJSFunc(function (labelWidth, labelHeight, point) {
        let position = {};
        position["x"] = point.plotX;
        position["y"] = 20;
            return position;
    }));
我在demo的  Double Y Axises Chart---双Y轴混合图     里添加了上面的代码分别跑了真机和模拟器还是真机有问题模拟器没问题

**Comment by wangxihu** [comment]
模拟器json：
2020-09-23 11:48:38.987660+0800 AAChartKitDemo[76304:11257685] ----------- console log AAOptions JSON information of AAChartView -----------:
{
  "credits" : {
    "enabled" : true,
    "style" : {
      "fontSize" : "9px",
      "color" : "red"
    },
    "href" : "https:\/\/github.com\/AAChartModel\/AAChartKit",
    "text" : "https:\/\/github.com\/AAChartModel\/AAChartKit"
  },
  "touchEventEnabled" : true,
  "chart" : {
    "polar" : false,
    "backgroundColor" : "#4b2b7f",
    "inverted" : false,
    "panning" : false
  },
  "tooltip" : {
    "useHTML" : false,
    "followTouchMove" : true,
    "shadow" : true,
    "crosshairs" : true,
    "shared" : true,
    "enabled" : true,
    "positioner" : "(function (labelWidth, labelHeight, point) { let position = {}; position[\\\"x\\\"] = point.plotX; position[\\\"y\\\"] = 20; return position; })",
    "animation" : true
  },
  "xAxis" : {
    "reversed" : false,
    "startOnTick" : false,
    "opposite" : false,
    "min" : 0,
    "endOnTick" : false,
    "tickmarkPlacement" : "on",
    "visible" : true,
    "categories" : [
      "Java",
      "Swift",
      "Python",
      "Ruby",
      "PHP",
      "Go",
      "C",
      "C#",
      "C++",
      "Perl",
      "R",
      "MATLAB",
      "SQL"
    ]
  },
  "series" : [
    {
      "marker" : {
        "radius" : 7,
        "symbol" : "circle",
        "enabled" : true,
        "lineColor" : "",
        "fillColor" : "#ffffff",
        "lineWidth" : 3
      },
      "borderRadius" : 4,
      "type" : "areaspline",
      "name" : "2017",
      "data" : [
        7,
        6.9000000000000004,
        2.5,
        14.5,
        18.199999999999999,
        21.5,
        5.2000000000000002,
        26.5,
        23.300000000000001,
        45.299999999999997,
        13.9,
        9.5999999999999996
      ],
      "color" : {
        "stops" : [
          [
            0,
            "#f54ea2"
          ],
          [
            1,
            "#ff7676"
          ]
        ],
        "linearGradient" : {
          "x2" : 0,
          "x1" : 0,
          "y2" : 0,
          "y1" : 1
        }
      },
      "showInLegend" : true,
      "allowPointSelect" : false,
      "visible" : true,
      "yAxis" : 1
    },
    {
      "type" : "column",
      "name" : "2018",
      "data" : [
        7,
        6.9000000000000004,
        2.5,
        14.5,
        18.199999999999999,
        21.5,
        5.2000000000000002,
        26.5,
        23.300000000000001,
        45.299999999999997,
        13.9,
        9.5999999999999996
      ],
      "color" : {
        "stops" : [
          [
            0,
            "#17ead9"
          ],
          [
            1,
            "#6078ea"
          ]
        ],
        "linearGradient" : {
          "x2" : 0,
          "x1" : 0,
          "y2" : 0,
          "y1" : 1
        }
      },
      "showInLegend" : true,
      "allowPointSelect" : false,
      "visible" : true,
      "yAxis" : 0
    }
  ],
  "title" : {
    "useHTML" : false,
    "text" : ""
  },
  "yAxis" : [
    {
      "labels" : {
        "style" : {
          "fontSize" : "15px",
          "fontWeight" : "bold",
          "color" : "#ff0000"
        },
        "useHTML" : false,
        "enabled" : true,
        "format" : "{value:.,0f}mm"
      },
      "reversed" : false,
      "title" : {
        "style" : {
          "fontSize" : "14px",
          "textOutline" : "0px 0px contrast",
          "fontWeight" : "bold",
          "color" : "#1e90ff"
        },
        "text" : "冬季降雨量"
      },
      "startOnTick" : false,
      "allowDecimals" : false,
      "opposite" : true,
      "endOnTick" : false,
      "visible" : true
    },
    {
      "labels" : {
        "style" : {
          "fontSize" : "15px",
          "fontWeight" : "bold",
          "color" : "#ff0000"
        },
        "useHTML" : false,
        "enabled" : true,
        "format" : "{value:.,0f}mm"
      },
      "reversed" : false,
      "title" : {
        "style" : {
          "fontSize" : "14px",
          "textOutline" : "0px 0px contrast",
          "fontWeight" : "bold",
          "color" : "#1e90ff"
        },
        "text" : "夏季降雨量"
      },
      "startOnTick" : false,
      "allowDecimals" : false,
      "opposite" : false,
      "endOnTick" : false,
      "visible" : true
    }
  ]
}

**Comment by wangxihu** [comment]
真机json：
2020-09-23 11:45:56.777947+0800 AAChartKitDemo[6261:2327140] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2020-09-23 11:45:56.778084+0800 AAChartKitDemo[6261:2327140] WF: _WebFilterIsActive returning: NO
2020-09-23 11:45:56.783520+0800 AAChartKitDemo[6261:2327140] ----------- console log AAOptions JSON information of AAChartView -----------:
{
  "credits" : {
    "enabled" : true,
    "style" : {
      "fontSize" : "9px",
      "color" : "red"
    },
    "href" : "https:\/\/github.com\/AAChartModel\/AAChartKit",
    "text" : "https:\/\/github.com\/AAChartModel\/AAChartKit"
  },
  "touchEventEnabled" : true,
  "chart" : {
    "polar" : false,
    "backgroundColor" : "#4b2b7f",
    "inverted" : false,
    "panning" : false
  },
  "tooltip" : {
    "useHTML" : false,
    "followTouchMove" : true,
    "shadow" : true,
    "crosshairs" : true,
    "shared" : true,
    "enabled" : true,
    "positioner" : [
      {
        "labels" : {
          "style" : {
            "fontSize" : "15px",
            "color" : "#ff0000",
            "fontWeight" : "bold"
          },
          "useHTML" : false,
          "enabled" : true,
          "format" : "{value:.,0f}mm"
        },
        "allowDecimals" : false,
        "opposite" : true,
        "visible" : true,
        "title" : {
          "style" : {
            "color" : "#1e90ff",
            "textOutline" : "0px 0px contrast",
            "fontWeight" : "bold",
            "fontSize" : "14px"
          },
          "text" : "冬季降雨量"
        },
        "endOnTick" : false,
        "reversed" : false,
        "startOnTick" : false
      },
      {
        "labels" : {
          "style" : {
            "fontSize" : "15px",
            "color" : "#ff0000",
            "fontWeight" : "bold"
          },
          "useHTML" : false,
          "enabled" : true,
          "format" : "{value:.,0f}mm"
        },
        "allowDecimals" : false,
        "opposite" : false,
        "visible" : true,
        "title" : {
          "style" : {
            "color" : "#1e90ff",
            "textOutline" : "0px 0px contrast",
            "fontWeight" : "bold",
            "fontSize" : "14px"
          },

          "text" : "夏季降雨量"
        },
        "endOnTick" : false,
        "reversed" : false,
        "startOnTick" : false
      }
    ],
    "animation" : true
  },
  "xAxis" : {
    "reversed" : false,
    "startOnTick" : false,
    "opposite" : false,
    "min" : 0,
    "endOnTick" : false,
    "tickmarkPlacement" : "on",
    "visible" : true,
    "categories" : [
      "Java",
      "Swift",
      "Python",
      "Ruby",
      "PHP",
      "Go",
      "C",
      "C#",
      "C++",
      "Perl",
      "R",
      "MATLAB",
      "SQL"
    ]
  },
  "series" : [
    {
      "marker" : {
        "radius" : 7,
        "symbol" : "circle",
        "enabled" : true,
        "lineColor" : "",
        "fillColor" : "#ffffff",
        "lineWidth" : 3
      },
      "borderRadius" : 4,
      "type" : "areaspline",
      "name" : "2017",
      "data" : [
        7,
        6.9000000000000004,
        2.5,
        14.5,
        18.199999999999999,
        21.5,
        5.2000000000000002,
        26.5,
        23.300000000000001,
        45.299999999999997,
        13.9,
        9.5999999999999996
      ],
      "color" : {
        "stops" : [
          [
            0,
            "#f54ea2"
          ],
          [
            1,
            "#ff7676"
          ]
        ],
        "linearGradient" : {
          "x2" : 0,
          "x1" : 0,
          "y2" : 0,
          "y1" : 1
        }
      },
      "showInLegend" : true,
      "allowPointSelect" : false,
      "visible" : true,
      "yAxis" : 1
    },
    {
      "type" : "column",
      "name" : "2018",
      "data" : [
        7,
        6.9000000000000004,
        2.5,
        14.5,
        18.199999999999999,
        21.5,
        5.2000000000000002,
        26.5,
        23.300000000000001,
        45.299999999999997,
        13.9,
        9.5999999999999996
      ],
      "color" : {
        "stops" : [
          [
            0,
            "#17ead9"
          ],
          [
            1,
            "#6078ea"
          ]
        ],
        "linearGradient" : {
          "x2" : 0,
          "x1" : 0,
          "y2" : 0,
          "y1" : 1
        }
      },
      "showInLegend" : true,
      "allowPointSelect" : false,
      "visible" : true,
      "yAxis" : 0
    }
  ],
  "title" : {
    "useHTML" : false,
    "text" : ""
  },
  "yAxis" : [
    {
      "labels" : {
        "style" : {
          "fontSize" : "15px",
          "fontWeight" : "bold",
          "color" : "#ff0000"
        },
        "useHTML" : false,
        "enabled" : true,
        "format" : "{value:.,0f}mm"
      },
      "reversed" : false,
      "title" : {
        "style" : {
          "fontSize" : "14px",
          "textOutline" : "0px 0px contrast",
          "fontWeight" : "bold",
          "color" : "#1e90ff"
        },
        "text" : "冬季降雨量"
      },
      "startOnTick" : false,
      "allowDecimals" : false,
      "opposite" : true,
      "endOnTick" : false,
      "visible" : true
    },
    {
      "labels" : {
        "style" : {
          "fontSize" : "15px",
          "fontWeight" : "bold",
          "color" : "#ff0000"
        },
        "useHTML" : false,
        "enabled" : true,
        "format" : "{value:.,0f}mm"
      },
      "reversed" : false,
      "title" : {
        "style" : {
          "fontSize" : "14px",
          "textOutline" : "0px 0px contrast",
          "fontWeight" : "bold",
          "color" : "#1e90ff"
        },
        "text" : "夏季降雨量"
      },
      "startOnTick" : false,
      "allowDecimals" : false,
      "opposite" : false,
      "endOnTick" : false,
      "visible" : true
    }
  ]
}

**Comment by wangxihu** [comment]
demo在真机上也崩溃过

**Comment by AAChartModel** [comment]
因为 AAChartKit 中的嵌套 model 转 JSON 使用到了 runtime 当中相关的内容, 肯能因此导致的真机和模拟器表现不一致.

**Comment by wangxihu** [comment]
好吧，这个悬浮窗配置没法用了。

**Comment by silendir** [comment]
![image](https://user-images.githubusercontent.com/11792633/94094297-b9216100-fe51-11ea-9b1f-1627a706e4e7.png)
这样写会报错, 找不到.positionerSet()

**Comment by AAChartModel** [comment]
@silendir 你没有更新到最新版的 AAChartKit 吧,你到 AATooltip 文件中看看是否有 positioner 这个属性, 如果没有请更新 AAChartKit 至最新版再试试

**Comment by silendir** [comment]
我用了AAChartKit pro 我是手动下载的..应该是最新的才是

**Comment by silendir** [comment]
还是说pro的不是最新的?

**Comment by silendir** [comment]
ProModel这个文件夹里的文件还有用么..还是说pro已经停更废弃了?集成到新的AAChartKit里面

**Comment by AAChartModel** [comment]
> 还是说pro的不是最新的?

Pro不是最新的, 最近一次和 常规版本的 AAChartKit 同步已经是接近两个月之前了.

**Comment by AAChartModel** [comment]
> ProModel这个文件夹里的文件还有用么..还是说pro已经停更废弃了

ProModel文件件中的文件对 AAChartKit-Pro 本身肯定是有用的, 用于支持一些非常用类型的图表.  AAChartKit-Pro 项目本身也没有废弃, 只是我最近这一段时间一直都比较忙, 无暇维护多个项目, 所以只能短暂搁置 AAChartKit-Pro.  对我来说 AAChartKit 和 AAChartKit-Pro 两个都同样有用, 如果废弃的话肯定是两个都会废弃. 但是 AAChartKit 现在一直在断断续续的更新, 所以 AAChartKit-Pro 也是一样的会断断续续更新

**Comment by silendir** [comment]
明白

**Comment by AAChartModel** [comment]
> 我用了AAChartKit pro 我是手动下载的..应该是最新的才是

不太清楚你是什么原因选择的 AAChartKit-Pro, 如果不是为了去使用非常用类型(比如桑基图, 河流图, 和弦图, 树图之类的)图表的话, 没有必要使用 Pro 版本的,因为 Pro 版本的除了支持了更多图表类型,其他方面是一点也都不 Pro 的🤣

**Comment by silendir** [comment]
我就是怕老板看了友盟会想用桑基图

**Comment by wangxihu** [comment]
aaTooltip.positionerSet(@AAJSFunc(function (labelWidth, labelHeight, point) {
let position = {};
position["x"] = point.plotX;
position["y"] = 20;
return position;
}));
这个配置在真机上的问题怎么解决呀，我还准备安卓也用AAChartKit呢

**Comment by AAChartModel** [comment]
> 我就是怕老板看了友盟会想用桑基图

友盟的效果图是啥样的?截个图看看👀

**Comment by AAChartModel** [comment]
> aaTooltip.positionerSet(@AAJSFunc(function (labelWidth, labelHeight, point) {
> let position = {};
> position["x"] = point.plotX;
> position["y"] = 20;
> return position;
> }));
> 这个配置在真机上的问题怎么解决呀，我还准备安卓也用AAChartKit呢

我觉得可能还是你这边的配置问题, 因为前面已经有不少人用的这个特性都是好好的🤣

**Comment by silendir** [comment]
我更新了AAChartKit,没有发生问题, xcode12

**Comment by wangxihu** [comment]
我重新下个demo在里面添加上再试试

**Comment by silendir** [comment]
我直接取AAChartKitLib, 拉过去..然后直接复制黏贴上面的代码

**Comment by wangxihu** [comment]
@silendir 你在真机上添加
aaOptions.tooltip.positionerSet(@AAJSFunc(function (labelWidth, labelHeight, point) {
        let position = {};
        position["x"] = point.plotX;
        position["y"] = 20;
        return position;
    }));
跑demo没有问题吗

**Comment by wangxihu** [comment]
[1600928307295047.mp4.zip](https://github.com/AAChartModel/AAChartKit/files/5273874/1600928307295047.mp4.zip)
 @AAChartModel 我录了个视频你看看真机上是不是有问题，别人没有出问题我不知道啥原因，但是我这里就是在demo上加了上面的配置代码出了问题。不可能是我手机的问题吧😝

**Comment by wangxihu** [comment]
AAChartKit  demo是我刚下的，配置我没动

**Comment by AAChartModel** [comment]
你这个视频内容我看了不是显示正常吗?

**Comment by AAChartModel** [comment]
> 但是我这里就是在demo上加了上面的配置代码出了问题

demo 中的代码你也不用改吧?你说的那段代码 demo 中不是本来就有吗?

```objc
//https://github.com/AAChartModel/AAChartKit/issues/966
- (AAOptions *)customTooltipPostionerFunction {
    NSArray *categoriesArr = @[
        @"孤岛危机",
        @"使命召唤",
        @"荣誉勋章",
        @"狙击精英",
        @"神秘海域",
        @"最后生还者",
        @"巫师3狂猎",
        @"对马之魂",
        @"蝙蝠侠阿甘骑士",
        @"地狱边境",
        @"闪客",
        @"忍者之印"
    ];
    
    AAChartModel *aaChartModel = AAChartModel.new
    .chartTypeSet(AAChartTypeColumn)
    .categoriesSet(categoriesArr)
    .seriesSet(@[
        AASeriesElement.new
        .nameSet(@"单机大作")
        .colorSet(AAColor.redColor)
        .dataSet(@[@7.0, @6.9, @9.5, @14.5, @18.2, @21.5, @25.2, @26.5, @23.3, @18.3, @13.9, @9.6])
               ])
    ;
    
    AAOptions *aaOptions = aaChartModel.aa_toAAOptions;
    
    aaOptions.tooltip
    .positionerSet(@AAJSFunc(function (labelWidth, labelHeight, point) {
        let position = {};
        position["x"] = point.plotX;
        position["y"] = 20;
        return position;
    }));
    
    return aaOptions;
}
```

**Comment by silendir** [comment]
我真机和模拟器都没有问题,

**Comment by wangxihu** [comment]
显示是没问题，悬浮窗没有跟据手指的滑动而滑动，它是固定在左上方

**Comment by wangxihu** [comment]
[1600929910587911.mp4.zip](https://github.com/AAChartModel/AAChartKit/files/5273981/1600929910587911.mp4.zip)
这是我想要的效果

**Comment by wangxihu** [comment]
原来我们说的不是一个效果😝，这个视频效果是模拟器上的是我想要的，真机上跑出来的效果悬浮窗是没有根据手指滑动而滑动的

**Comment by silendir** [comment]
现在标签定在左上方了... 能不能让它跟着x轴移动?

**Comment by silendir** [comment]
我也是才发现...

**Comment by silendir** [comment]
模拟器没有问题...真机停在左上角不动

**Comment by wangxihu** [comment]
简单来说就是固定悬浮窗Y值高度固定，X方向跟随手指。或者x值固定，y方向跟随手指。终于把这个问题说明白了😝

**Comment by silendir** [comment]
作者理解了...只是真机实现出bug了...不会动了...在模拟器上是和你说的一致

**Comment by silendir** [comment]
xcode12 调试iPhone 7 和8 太慢... 我用模拟器看效果一下子没注意..模拟器上是 单轴置顶 另外一轴随动的

**Comment by AAChartModel** [comment]
> 简单来说就是固定悬浮窗Y值高度固定，X方向跟随手指。或者x值固定，y方向跟随手指。终于把这个问题说明白了😝

问题已解决, 参见 #1028

**Comment by silendir** [comment]
![89756798-179ab600-db16-11ea-9776-c095fcda05a8](https://user-images.githubusercontent.com/11792633/97846097-785a1900-1d28-11eb-9c8d-56779de679e0.png)
让ToolTip凌在16000上面是要把Y轴下沉么?

**Comment by wuxuezhen** [comment]
如果能监听到手指停止触摸，直接自定义最好

**Comment by AAChartModel** [comment]
> ![89756798-179ab600-db16-11ea-9776-c095fcda05a8](https://user-images.githubusercontent.com/11792633/97846097-785a1900-1d28-11eb-9c8d-56779de679e0.png)
> 让ToolTip凌在16000上面是要把Y轴下沉么?

这个问题不是已经解决了吗? https://github.com/AAChartModel/AAChartKit/issues/1033

**Comment by silendir** [comment]
衣.....是哦....  哈哈哈
