### ISSUE TITLE
dataLabel font size?

### ISSUE THREAD

**Issue by skuske** [AAChartModel/AAChartKit#97]
Is there any way to change the font size of data labels? Thanks.

**Comment by AAChartModel** [comment]
This is the default style setting of data label  in `AADataLabel.m`,you can change it by yourself as your wish.
```objective-c
- (instancetype)init {
    self = [super init];
    if (self) {
        NSDictionary *styleDic = @{@"color": @"contrast",
                                   @"fontSize": @"12.5px",
                                   @"fontWeight": @"bold",
                                   @"textOutline": @"1px 1px contrast" };
        self.style = (id)styleDic;
    }
    
    return self;
}
```

**Comment by skuske** [comment]
Thanks, but: is there any way to set the font size during instance creation of the chart itself. I don't want to set it globally. :o)

**Comment by AAChartModel** [comment]
I need a little bit more time to think about it!😝
