### ISSUE TITLE
更新问题~

### ISSUE THREAD

**Issue by Raysonly** [AAChartModel/AAChartKit#971]
宝宝心里苦~
今天更新了一下，发现有的功能没了，然后退回4.0.0，然后发现都退回去了，之前的很多方法竟然改了或者没了，这是怎么回事？

**Comment by AAChartModel** [comment]
常规的升级优化, 改进了之前 AAChartKit 的很多设计问题.

**Comment by AAChartModel** [comment]
> 今天更新了一下，发现有的功能没了

有的功能没了这个倒不至于, 基本都有替代的方法. 如有更多使用的问题,可以提 issue

**Comment by Raysonly** [comment]
哈哈，刚刚看到了，在看你最近的更新，代码越来越好看了~
