### ISSUE TITLE
设置缩放后的上下滑动事件

### ISSUE THREAD

**Issue by Raysonly** [AAChartModel/AAChartKit#972]
把`AAChartView`放在`tableHeaderView`里，设置缩放`aaChartModel.zoomType = AAChartZoomTypeX`，缩放过后上下滑动的时候`tableview`不滑动了，没有缩放之前就可以滑动，上个版本没这个现象，我需要另外拦截这个上下滑动事件吗？

**Comment by AAChartModel** [comment]
我测试了一下,好像确实是有这个问题, 这就有点蛋疼了,可能是 Highcharts 本身的一个 bug
