### ISSUE TITLE
你好，最新代码能推一个新版本吗

### ISSUE THREAD

**Issue by wuxuezhen** [AAChartModel/AAChartKit#973]
你好，最新代码能推一个新版本吗

**Comment by AAChartModel** [comment]
```ruby

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  AAChartKit (5.0.4) successfully published
 📅  August 18th, 06:31
 🌎  https://cocoapods.org/pods/AAChartKit
 👍  Tell your friends!
--------------------------------------------------------------------------------
MacBook-Pro-2:AAChartKit(master) ios-fn$ 
```

**Comment by AAChartModel** [comment]
https://cocoapods.org/pods/AAChartKit

Cocoapods  上的 AAChartKit 源文件现已更新至 `5.0.4` 版本

**Comment by Abnerzj** [comment]
你好，最新代码能推一个新版本吗？目前我们协同开发拉取的代码不一样，pod的版本又是一样的。目前这个库在协同开发的时候会带来不少问题，希望作者能完善一下，问题出现场景是这样的：作者你在某一次发了一次podspec版本（目前最新的是5.0.4），后面这个库有很多次修改，但是你的podspec版本一直没更新，所以当我们协同开发的时候，每个人拉取到的代码都不一样，因为你的pod命令是：pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'。希望作者在每次有更新时同时更新podspec版本。

**Comment by AAChartModel** [comment]
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  AAChartKit (6.0.0) successfully published
 📅  January 19th, 00:09
 🌎  https://cocoapods.org/pods/AAChartKit
 👍  Tell your friends!
--------------------------------------------------------------------------------

@Abnerzj

**Comment by AAChartModel** [comment]
https://cocoapods.org/pods/AAChartKit

Cocoapods 上的 AAChartKit 源文件现已更新至最新的 6.0.0 版本

@Abnerzj

**Comment by Abnerzj** [comment]
> https://cocoapods.org/pods/AAChartKit
> 
> Cocoapods 上的 AAChartKit 源文件现已更新至最新的 6.0.0 版本
> 
> @Abnerzj

好的
