### ISSUE TITLE
如何修改显示 AASeriesElement 的 name 属性文字内容的Label的颜色

### ISSUE THREAD

**Issue by jxdwinter** [AAChartModel/AAChartKit#974]
![Group](https://user-images.githubusercontent.com/1195524/90582181-af2b9300-e1ff-11ea-9037-2913f9838e83.png)

请问如何修改如图中所示的红圈部分的字体颜色，因为主题是深色，所以显示不明显，
谢谢！

**Comment by AAChartModel** [comment]
参考 https://github.com/AAChartModel/AAChartKit/issues/696

**Comment by AAChartModel** [comment]
另参考相同问题 https://github.com/AAChartModel/AAChartKit/issues/799

**Comment by jxdwinter** [comment]
非常感谢，这么快的回复！
