### ISSUE TITLE
请问如何为柱状图的柱子添加阴影

### ISSUE THREAD

**Issue by program-APE** [AAChartModel/AAChartKit#976]
![图例](https://s1.ax1x.com/2020/08/20/dJrpRI.png)

**Comment by AAChartModel** [comment]
参考 https://github.com/AAChartModel/AAChartKit/issues/591

柱状图📊阴影添加与之同理.

**Comment by AAChartModel** [comment]
关键内容

```js
                 .shadowSet(AAShadow.new
                            .offsetXSet(@15.0)
                            .offsetYSet(@15.0)
                            .opacitySet(@0.1)
                            .widthSet(@8.0)
                            .colorSet(AAColor.redColor))
```

**Comment by program-APE** [comment]
您好,图例中阴影上下是不同的,外扩的宽度也不太相同,按照您给出的代码直接设置效果是有差异的,能否开放每个柱子的样式自定义用 CSS 代码的方式改变,
附柱子阴影 Sketch 标注的样式:

background: #F5F5F5;
box-shadow: -1px -1px 3px 0 #FFFFFF, 2px 2px 3px 0 #D0D0D0;
border-radius: 2px;
border-radius: 2px;

**Comment by AAChartModel** [comment]
这个恐怕搞不定了. 参见 Highcharts 官网链接 https://api.highcharts.com.cn/highcharts#plotOptions.spline.shadow

> 开始阴影可以配置成包含 color、offsetX、offsetY、opacity 和 width 属性的对象形式

Highcharts 的阴影属性也就只是支持这么多的属性设置

**Comment by program-APE** [comment]
好吧,感谢 AnAn
