### ISSUE TITLE
x轴设置文字包含有单引号'的时候，报错，x轴设置的坐标显示不出来

### ISSUE THREAD

**Issue by Choice-Fei** [AAChartModel/AAChartKit#978]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/13918369/91158101-c46d5980-e6f8-11ea-804c-f225de48f04e.png">
像这种的，我也看到了大佬你把单引号替换掉的代码，我现在如果要显示单引号，怎么处理。。。

**Comment by AAChartModel** [comment]
改成这种中文单引号试试?

```js
 ‘ ’
```
