### ISSUE TITLE
请问能否实现简易的心电图效果 跪求！！

### ISSUE THREAD

**Issue by ws1227** [AAChartModel/AAChartKit#983]
我想实现类似https://wenku.baidu.com/view/ae8bb546852458fb770b5662.html 这个里边心电图的效果 有背景网格 ，能否提供一点思路呢

**Comment by AAChartModel** [comment]
背景网格,心电图样式倒是没啥问题,不过一般心电图都有高频刷新的需求,但是 AAChartKit 的高频刷新功能不太行,所以可能并不是你想要的
