### ISSUE TITLE
如何把X轴跟点击点后 显示自定义的数据

### ISSUE THREAD

**Issue by huangjunyang2016** [AAChartModel/AAChartKit#984]
你好，大佬啊。希望看到可以快点回复我 谢谢，刚接手的项目 他们用了这个框架 现在要改一个需求，就是st:lb这种单位 数据格式是 12:10.8 ,我想要设置老是设置不了 想要修改框架代码也不会改，请大佬帮忙。万分感谢。如果不能改这种数据格式 也顺便告诉我，X轴跟点击点后都要显示这种特殊数据格式。

**Comment by AAChartModel** [comment]
贴一张设计稿看看

**Comment by huangjunyang2016** [comment]
![WeChatf7b57821d5919297285304d970681add](https://user-images.githubusercontent.com/17901780/92204378-f4192000-eeb5-11ea-9fa9-5823c344ceaa.png)

就是画红线的数据格式

**Comment by huangjunyang2016** [comment]
> 不是十分明白你的需求,贴一张设计稿看看

我发了  是不是没点击到回复 你没看到呢？

**Comment by AAChartModel** [comment]
看你的这个设计稿,如果你这边的 data 值给到的是以`千克`为单位的,那么你这边应该是要使用 AATooltip 的 formatter 函数来将你的数据根据

```
1 千克=0.157473 英石

1 千克=2.2046226 磅
```

这两个公式来转换一下值,具体可参考 AAChartKit 中的 formatter 使用示例

**Comment by AAChartModel** [comment]
类似需求参考 #653

**Comment by AAChartModel** [comment]
在线文档 参考 https://api.highcharts.com.cn/highcharts#tooltip.formatter

**Comment by huangjunyang2016** [comment]
> 在线文档 参考 https://api.highcharts.com.cn/highcharts#tooltip.formatter

谢谢大佬。我试试看，如果还有啥不懂 再请教你。
