### ISSUE TITLE
柱状图只有一组数据，tooltip怎么设置成方形，不带箭头的

### ISSUE THREAD

**Issue by wtuyp** [AAChartModel/AAChartKit#993]
您好，
       柱状图只有一组数据，tooltip怎么设置成方形，不带箭头的样子。谢谢！

**Comment by AAChartModel** [comment]
tooltip
    .shapeSet(@"square")//数据点提示框的形状名称。在Highcharts 3.x 以及更早的版本，提示框的形状是 square。 默认是：callout.
    .backgroundColorSet(@"#000000")
    .borderColorSet(@"#000000")
    .styleSet(AAStyleColorSize(@"#FFD700", 12))
    ;

**Comment by AAChartModel** [comment]
按照 README 文档所说, 更新 AAChartKit 至最新内容即可使用 tooltip 的 shape 属性
