### ISSUE TITLE
可以对Columnrange 实现分段变色么?

### ISSUE THREAD

**Issue by silendir** [AAChartModel/AAChartKit#994]
好像这样...我没有找到例子..对Columnrange 进行.zonesSet 他只会每条单独变色
![image](https://user-images.githubusercontent.com/11792633/93862853-4602d800-fcf5-11ea-81de-31c5f6de080b.png)

**Comment by silendir** [comment]
顶一下试试看

**Comment by AAChartModel** [comment]
你图中的效果, 在 AAChartKit 中, 目前我能想到的是,只能通过三组不同颜色的 columnrange 来实现, 参考此问题 https://github.com/AAChartModel/AAChartKit-Swift/issues/216

**Comment by silendir** [comment]
写写大神指导

**Comment by silendir** [comment]
![image](https://user-images.githubusercontent.com/11792633/94222596-62cf2380-ff20-11ea-86bc-56de0405228b.png)
为什么我实现出来的...会在纵轴错开,我看了216 的例子不会

**Comment by AAChartModel** [comment]
注意这部分内容 

https://github.com/AAChartModel/AAChartKit-Swift/issues/216#issuecomment-644805692
