### ISSUE TITLE
设置toolTip.followTouchMove没有效果

### ISSUE THREAD

**Issue by silendir** [AAChartModel/AAChartKit#997]
![image](https://user-images.githubusercontent.com/11792633/94001443-19b98b00-fdcb-11ea-93f7-262a56cbf18a.png)
这样写是不是有什么问题?请问正确的写法应该是怎么样

**Comment by AAChartModel** [comment]
你期待的是 tooltip 的什么效果❓

**Comment by silendir** [comment]
![Uploading image.png…]()

**Comment by silendir** [comment]
![image](https://user-images.githubusercontent.com/11792633/94003761-44591300-fdce-11ea-96a2-2729cdb2315f.png)

**Comment by AAChartModel** [comment]
这么说你应该是希望图表有缩放效果吧, 那你应该设置图表的 zoomType 类型为 `AAChartZoomTypeX` 横向缩放, 因为图表默认是不支持缩放的

**Comment by silendir** [comment]
这个我已经设置了...但是双指拖动..就必须特意告诉用户, 然后我看到了
        .tooltip.followTouchMoveSet(NO)这个属性.我根据注释写在链式的头部,后面的.xxx会报错..写着做末尾的话跑的时候曲线AASeriesElement会报错
![image](https://user-images.githubusercontent.com/11792633/94004422-3f489380-fdcf-11ea-9e86-dace5c9437ba.png)

**Comment by AAChartModel** [comment]
```objc
    AAOptions *aaOptions = aaChartModel.aa_toAAOptions;
    
    aaOptions.tooltip.followTouchMoveSet(false);
```

要像上面这样写才行

**Comment by silendir** [comment]
好的,谢谢刚看到tooltip label也是要option
