### ISSUE TITLE
有没有办法把柱状图的圆弧形状做成四边圆弧

### ISSUE THREAD

**Issue by silendir** [AAChartModel/AAChartKit#999]
![Uploading image.png…]()
然后还有下面x轴每个刻度中间那些傻逼箭头..... 可以做么?我他妈裂开了

**Comment by silendir** [comment]
然后还有下面x轴每个刻度中间那些傻逼箭头..... 可以做么?我他妈裂开了

![image](https://user-images.githubusercontent.com/11792633/94099433-854c3880-fe5d-11ea-916b-c4822b43603e.png)

**Comment by silendir** [comment]
borderRadiusSet 我找到了.. 傻逼箭头... 如果我自己贴图..如何对齐x轴上的label

**Comment by AAChartModel** [comment]
![](https://user-images.githubusercontent.com/16357599/87515713-d2b66780-c6ae-11ea-876d-2541402a8279.png)

如上图可知, AAChartKit 支持通过 formatter 函数来实现在 tooltip 和 X 轴的文字标签中插入图片.

**Comment by AAChartModel** [comment]
参见  GitHub issue: https://github.com/AAChartModel/AAChartKit/issues/938

**Comment by AAChartModel** [comment]
参见在线示例: https://www.highcharts.com/demo/column-comparison

**Comment by AAChartModel** [comment]
AAChartKit 的 demo 中有此示例, 下载 demo 运行查看代码及图表效果即可

**Comment by AAChartModel** [comment]
参见在线文档 https://api.highcharts.com.cn/highcharts#xAxis.labels.formatter

**Comment by silendir** [comment]
有没有办法直接控制柱状的粗细

**Comment by silendir** [comment]
是不是通过Padding 来设置?

**Comment by AAChartModel** [comment]
是的,不能直接控制棱柱的粗细, 只能通过 padding 来设置.

**Comment by silendir** [comment]
谢谢大神
